### ISSUE TITLE
Remove PHP code merged into WordPress 5.0

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#11015]
**Important note**: Closing this issue means we update the minimum WP supported version of the plugin to 5.0. (**Edit:** Done in #13370)

---

Now that WordPress 5.0 is ready to be released, we need to start working on the next phase and ensure we don't duplicate code in the plugin.

Things that should be removed from the plugin:

 - [x] ~REST API endpoints and tweaks~ (#13408)
 - [x] ~Block parsing, rendering utilities~ (#13412)
 - [x] ~php files adding the MetaBoxes support~ (#13449)
 - [x] ~Miscellaneous core compatibility (`lib/compat.php`)~ (#13442)
 - [x] Bootstrapping the Gutenberg editor (already done in Core) (#13569)

**See Project:** https://github.com/WordPress/gutenberg/projects/23

The php files that need to remain in the plugin are:

 - Scripts registration (overriding)
 - Dynamic blocks registration

**Comment by danielbachhuber** [comment]
Previously #10656

**Comment by swissspidy** [comment]
Related: #12559.

**Comment by aduth** [comment]
> we update the minimum WP supported version of the plugin to 5.0.

Pull request: #13370

> * REST API endpoints and tweaks

Pull request: #13408

> * Block parsing, rendering utilities

Started on this one. Interestingly the `wordpress_phpunit` Docker image still uses WordPress 4.9.x , so naturally will encounter a fair number of fatal errors when trying to remove functions like `register_block_type`. Will definitely need to update this, but I'm not certain the process for doing so.

**Comment by aduth** [comment]
>php files adding the MetaBoxes support

Pull request: #13449

>Miscellaneous core compatibility (lib/compat.php)

Pull request: #13442

**Comment by aduth** [comment]
This is turning out to be a more significant effort.

Here's a project instead: https://github.com/WordPress/gutenberg/projects/23

**Comment by aduth** [comment]
Unless I've missed something, I'd now consider this effort concluded with the last major merge in #13569 .

https://github.com/WordPress/gutenberg/projects/23

**Comment by youknowriad** [comment]
Thanks Andrew, nice work here.
