### ISSUE TITLE
Upgrade to React 16.6 stable APIs

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#11360]
Ideally, before upgrading, we can get rid of all deprecated APIs surfaced by `StrictMode` of React 16.6.

 - `findDOMNode`
 - The old `context`API
 - `componentWillReceiveProps` and other lifecycle hooks.

Remaining instances (feel free to add items to the list when you notice used deprecated APIs)

 - [x] Remove findDOMNode from Tooltip #11169 
 - [x] Remove findDOMNode from DropZone Provider #11168 
 - [x] Remove findDOMNode from Block #11170 
 - [x] Remove findDOMNode from the inserter #11363
 - [x] Remove findDOMNode from NavigableToolbar #11401
 - [x] Remove findDOMNode from withHoverAreas #11407
 - [x] Remove old context API from Slot/Fill #11123 
 - [x] Remove componentWillMount from LatestPostsEdit https://github.com/WordPress/gutenberg/pull/14637
 - [x] Remove componentWillUpdate from the Fill component #15541
 - [x] Remove componentWillReceiveProps from TinyMCE #8148 #11368
 - [ ] Investigate and Remove componentWillReceiveProps from Resizable (it's React Native code)
 - [x] Remove componentWillReceiveProps from Input at ColorPicker component #11772 @nosolosw

**Comment by iseulde** [comment]
There's a PR for the TinyMCE one: #8148.

**Comment by iseulde** [comment]
I also see:

```
react-dom.24169eaf.js:526 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in Editor (created by ComponentWithSelect)
    in ComponentWithSelect
    in WithSelect(Editor)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Resizable

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

**Comment by youknowriad** [comment]
@iseulde I saw it too, not sure where it come from yet but adding an item to the list above.

**Comment by nosolosw** [comment]
Riad, https://github.com/WordPress/gutenberg/pull/11123 has been merged. Checked the task off from the list.

**Comment by youknowriad** [comment]
>  Remove componentWillUpdate from the Fill component

@aduth when you have some time, I'd appreciate some help on this point

**Comment by nosolosw** [comment]
Did not find anything related to the Resizable component, but searching for `componentWillReceiveProps` did yield one result: the `Input` leaf component of `ColorPicker`. I can look into that.

**Comment by aduth** [comment]
Given the title of the issue, can this be assumed to be closed by #11840?

Or should we update the title if there are remaining tasks?

**Comment by nosolosw** [comment]
I'd rename it to something along the lines of 'Upgrade to 16.6 stable APIs".

**Comment by youknowriad** [comment]
Can we do a push to fix the remaining warnings here?

**Comment by coreymckrill** [comment]
Looks like there is also usage of `componentWillMount` in the Latest Posts block. Would that fall within the scope of this issue?

**Comment by aduth** [comment]
> Looks like there is also usage of `componentWillMount` in the Latest Posts block. Would that fall within the scope of this issue?

I expect so, yes (and for any other occurrence of `componentWillMount`, if exists).

**Comment by notnownikki** [comment]
PR for `LatestPostsEdit` is at https://github.com/WordPress/gutenberg/pull/14637

**Comment by aduth** [comment]
Question: Will using the [`UNSAFE_`-prefixed methods](https://reactjs.org/docs/react-component.html#the-component-lifecycle) trigger StrictMode warnings? While I'd love to avoid them altogether, I'm personally more inclined to see us using development modes in E2E sooner than later to catch other, legitimate, present issues ([related discussion](https://github.com/WordPress/gutenberg/pull/14371#issuecomment-471970997)).

**Comment by chiraggmodi** [comment]
any update on how to solve this issue?

**Comment by aduth** [comment]
@chiraggmodi The warnings logged from the React unsafe methods are not ideal, but are safe to ignore. This issue serves as to track progress from the task of updating individual components to avoid warnings being logged, as they are not future-compatible.

**Comment by gziolo** [comment]
It looks like `componentWillUpdate` in `Fill` component which blocks us from enabling `SCRIPT_DEBUG` in e2e tests env. Is anyone working on it?

**Comment by youknowriad** [comment]
I'd really want us to close this issue. I know the `Fill` issue is not easy though.
Some people running WP in SCRIPT_DEBUG true are getting confused with these warnings.

**Comment by gziolo** [comment]
> I'd really want us to close this issue. I know the `Fill` issue is not easy though.
> Some people running WP in SCRIPT_DEBUG true are getting confused with these warnings.

Have anyone tried using `getSnapshotBeforeUpdate` instead?

**Comment by youknowriad** [comment]
Most of the warnings are now gone when you open the editor. I'm going to close this at the moment. Let's consider any future warnings as bugs.

**Comment by aduth** [comment]
#14851 will resolve some StrictMode errors for Popover usage (`findDOMNode`).

#14845 should be considered a follow-up task here (enable development React and thereby StrictMode in end-to-end testing environments for error log capturing).

**Comment by youknowriad** [comment]
@aduth I created this #15790 to track the Modal refactoring
