### ISSUE TITLE
Tracking issue for merging iseulde/editor-blocks

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#114]
See https://iseulde.github.io/editor-blocks/

- [x] Add single instance TinyMCE prototype that has the same UI as the mock-ups.
- [ ] ~~Add another "playground" prototype where it's easy for me to experiment further. (People could add more playgrounds, feel free to suggest better alternatives.)~~
- [x] Make sure components are reusable (sure as text patterns, cleaning paste...) How to best do this? Shared directory? Hot-link from somewhere else?
