### ISSUE TITLE
Editor: Update withDispatch-wrapped components to use registry if applicable

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#12890]
Previously: #11851

With the changes introduced by #11851, we should seek to refactor components which provide data through `withSelect` for the sole purpose of satisfying a dispatch callback. These components instead should use the new registry argument.

Upon investigation, these are the components I discovered to be refactored:

- [x] `EditorGlobalKeyboardShortcuts` (the `isDirty` prop) (#13288)
- [x] `InserterMenu` (the `selectedBlock` prop) (#13288)
- [x] `EditorModeKeyboardShortcuts` (the `hasBlockSelection` prop) (#13288)
- [x] `BlockConvertButton` (the `block` prop) (#13067)
   - Refactor: `block` is used in `withSelect`, but it should be refactored to use the trivial `getBlockName` selector instead (`getBlock` is deemed expensive)

The workflow for discovering these was to search the codebase for and sort through results of `withDispatch` with a mapping which makes use of the second `ownProps` argument.

```
Searching 1670 files for "withDispatch( ( dispatch, ownProps )"
```

**Comment by gziolo** [comment]
Did you search for `withDispatch( ( dispatch, ` There are 37 matches which we might want to verify, too:

![screen shot 2018-12-17 at 14 53 36](https://user-images.githubusercontent.com/699132/50091412-a0f7c900-020b-11e9-80df-cae84b963b46.png)

**Comment by aduth** [comment]
I did not! The in-place destructuring could certainly qualify.

**Comment by aduth** [comment]
I updated the original comment with two more from a `withDispatch( ( dispatch, {` search.

**Comment by aduth** [comment]
Closing based on referenced subtasks having been merged.
