### ISSUE TITLE
Phase 2 Scope & Features

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#13113]
The following, [initially outlined here](https://make.wordpress.org/core/2018/12/08/9-priorities-for-2019/), is an overview of the major functionality to be introduced in Phase 2 to help visualize the progress in terms of product scope. There’s a lot of unknown unknowns at the moment so this is a living document that will evolve and adapt over time.

### Blocks beyond the Editor
- [ ] Integration of the block editor to the Widgets screen [#13204]
- [ ] Integration of the block editor to the Customizer [#13205]
- [ ] Integration of the Navigation block to the Menu screen [#21340]

### Navigation block
- [ ] Integration of the blocks editor to the Menu Screen [#13206]
- [ ] Drag and drop iterations [#19703]
- [ ] Enter key not to add line break [#18208]
- [ ] Default orientation and existing menus [#20853]
- [ ] Submenus [#20807, #21136]
- [ ] Block Navigator [#20748, #20846, #21372]

### Block Style System [#20331]

Refer to the link provided above.

### Block Patterns
- [ ] Next steps on Inserter [#21080]
- [ ] Create patterns to populate the library [#20345]

### Full Site Editing [#24551]

Refer to the link provided above.

## 💎 Tightening Up
- [ ] Improvements for the Latest Post Block ~[#1594]~ [#20046]
- [ ] Server-side registration [#2751]
- [ ] Reordering Gallery Items, including support for Drag&Drop [#743]
- [ ] Better undo: Fixing any undo traps [#8119] and fixing "misplaced" carets
- [x] Accessible Autocomplete component to use instead of unbounded requests [#7384]

## ✨ New Features
- [ ] Add better variations for Separator block [#16483]
- [ ] New block: Add an Icons block [#16484]
- [ ] New block: Title block [#11553]
- [ ] Responsive layouts and grids[#4314, #13203, #13363]
- [ ] Simple block + simple block = complex block (combining blocks by drag n drop to form more 
 complex existing blocks) [#13202]
    - [ ] Drag an image over another to create a Gallery [#9783]

## ✅ Done

 - Add the UI for a Block Pattern Library and initial block patterns  [#17335]
 - Menu Navigation Block [#1466] -> new [#13690]
 - **Widget-block interface integration**
      - Classic Widget Block [#4770]
      - Reusable `BlockEditor` component that can be embedded in several screens [#13088]
 - **Widgets 2 Blocks:**
      - RSS block [#1799]
      - Search block [#1800]
      - Calendar block [#1462]
      - Tag Cloud block [#1801]
 - Block Management UI [#14139]
 - Group block [#4900]
 - Accessibility navigation mode [#16500] 
 - Animations and Motion [#16065]
 - Introduce the Snackbar notices [#15594]
 - Improvements to existing blocks:
      - Cover block [#10925] 
      - Cover block with nested elements [#13822]
      - Support for Headers and Footers in the Table block [#15409]
      - Support text alignments in the Table block [#15823]
      - Support changing the Separator block color [#16784]
      - Support nested blocks in the Cover block [#13822]
      - Support target blank in the Button block [#8000]
      - Support text color in the Heading block [#15625]
      - Support reordering gallery images inline [#14768]
      - Support custom widths for Column blocks [#15499]. 
      - Support showing the post content and excerpt in the Latest Posts block [#14627]
    - Simplify Button Block Styles #16481 
    - Button Block and Multiple Buttons #16480 
    - Add support for gradients in Button blocks #16482 
    - Resizing columns in the column block [#20597] [#20169]
 - Continual work on performance [#11782] 
 - Improvements to Media Interactions [#14983]
 - Improvements to the nested block selection [#15537][#9628]
 - Improve Keyboard Interactions  (list shortcuts, tabbing..) [#9611, #11581 ...]
 - Improvements to Media Interactions #11952
 - Better style variations and theme integration API [#7551]
 - Tip improvements [#18041]
- Microinteractions [#8029]

**Comment by nicholasio** [comment]
For the idea of themes registering content areas,  Themes already do something similar using "sidebars" it looks like it might be worth it seeing how this notion of content area can be used to rework Widgets/Sidebars into something more generic like content areas while maintaining backward compatibility.

**Comment by mapk** [comment]
I organized the focuses to explicitly reflect the project post of 2019 mentioned above. Also moved the previous research items up since research is an actionable item.

**Comment by CGlingener** [comment]
No explicit plans for *Resizing columns in the column block* yet?

**Comment by youknowriad** [comment]
@CGlingener If this is something that interest you, feel free to join our meetings, claim it and explore it to figure out more explicit plans. Thanks.

**Comment by michaelswengel** [comment]
Any plans to add block indentation? Indenting subparagraphs is an important feature.

**Comment by swissspidy** [comment]
@michaelswengel Feel free to create a new issue for that to describe your use case there.

**Comment by michaelswengel** [comment]
@swissspidy Already done. :) https://github.com/WordPress/gutenberg/issues/14554

**Comment by Blondyna** [comment]
Sylwia Panek

**Comment by karmatosed** [comment]
I added in user facing/tools as section with some recent issues made.

**Comment by trejder** [comment]
Is there any priority roadmap for bugs in Gutenberg development? Is there any general idea of resolving bugs before introducing new features?

I see a lot of discussions around here about new features or how to ease Gutenberg user's lives... Yet, still no resolution on something as stupid (and in the same time affecting millions) as adding spaces when pasting text (#16172).

To paraphrase the "[Upcoming Projects & Roadmap](https://github.com/WordPress/gutenberg/blob/master/docs/roadmap.md)" document: _Gutenberg is already in use by millions of sites through WordPress_... and yet millions of editors of that millions of sites is still forced to delete two spaces, stupidly added in the beginning and end of each pasted text.

How long do we have to wait before a bug that affects general usage of Gutenberg is resolved?

**Comment by paaljoachim** [comment]
Should this issue be updated?

**Comment by youknowriad** [comment]
I think we should close this issue  for now, as we have different "overview" issues for the different projects of phase2 with better organization and that are easier to follow.

**Comment by annezazu** [comment]
For good measure since there are a lot of posts that link to this issue and many of the above linked issues are closed, here are some of those current overview issues: 

- Site Editing Milestones: https://github.com/WordPress/gutenberg/issues/24551
- Block based Widgets Editor: https://github.com/WordPress/gutenberg/issues/24687
- Block based Navigation Editor: https://github.com/WordPress/gutenberg/issues/22931
- Navigation Block: https://github.com/WordPress/gutenberg/issues/27593
- Block Styles (Global Styles, same as linked above): https://github.com/WordPress/gutenberg/issues/20331

Hopefully this helps anyone who finds this issue linked in other places :)

**Comment by youknowriad** [comment]
Thanks @annezazu that's very helpful :)
