### ISSUE TITLE
Follow-up tasks to polish the generic block editor module

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#14043]
- [x] Use the `core/block-editor` store instead of `core/editor` proxied methods #13105
 - [x] Separate the post editor settings and the block editor settings #14082 
 - [x] Move the block editor components to the module (from editor) #14112
 - [ ] Check whether the template synchronization needs to be moved to the module https://github.com/WordPress/gutenberg/pull/13088#discussion_r259095298
 - [x] Add Documentation #14566 
 - [x] Add a static Gutenberg playground #14497 
 - [ ] Implement the reusable blocks as an embedded editor #14367
 - [x] Remove the apiFetch dependency from the block editor module #14527
 - [x] Remove the core data dependency from the block editor module #14387 #14548

**Comment by gziolo** [comment]
There is some JS errors which break some behaviors like removing blocks:

![error-js](https://user-images.githubusercontent.com/699132/54919070-24f2d880-4f00-11e9-9482-9e4edbbd24f1.gif)

**Comment by youknowriad** [comment]
There are still some improvements we can do to the block library, the reusable blocks... but these are going to be enhancements that will be made as we implement other features ( widget screen... ). I'm going to close this issue for now, and we can reopen smaller issues if needed.
