### ISSUE TITLE
Navigation block overview

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#17544]
This is an overview of the work required to complete a first iteration of the Navigation block. The block is currently in a functional state but needs lots of polish at both the block and framework level.

There's been lots of previous discussion about the Navigation block: https://github.com/WordPress/gutenberg/issues/13690, https://github.com/WordPress/gutenberg/issues/16821 and https://github.com/WordPress/gutenberg/issues/16974 contain the bulk of it. **As we turn our attention towards shipping a v1, let's consolidate high level discussion into this issue and more specific technical discussion into the issues linked below.**

## Overview 

![](https://user-images.githubusercontent.com/548849/62833066-d89eff80-bc38-11e9-9993-c154d43a694f.png)

The Navigation block defines the menu area and contains all of the menu items. In its toolbar is a _Navigator_ button for accessing the Block Navigator. Menu items are added using the mechanism for adding child blocks (+).

![](https://user-images.githubusercontent.com/548849/62833108-709ce900-bc39-11e9-9b81-eb49dc358f20.png)

Each menu item is a child block. In its toolbar is a _Link_ button for changing where the menu item links to via the existing `URLInput` component. Menu items can be nested within each other forming submenus. When a menu item is selected, its child menu items are displayed.

![](https://user-images.githubusercontent.com/1204802/63928945-d8806b80-ca50-11e9-927c-12f3f16ec580.png)

Menu items can be re-ordered using the existing block mover controls which will be restyled to look visually similar to the movers in the Gallery block.

### `URLInput`

![](https://user-images.githubusercontent.com/253067/63781712-1317c600-c8e2-11e9-9ff6-22a2c8cf469a.png)

The `URLInput` component will be updated to allow the easy selection of a top-level page.

### Block Navigator 

![Navigator](https://user-images.githubusercontent.com/612155/65407440-dded8d80-de25-11e9-8884-3c5077773bcf.png)

The Block Navigator will be updated to allow blocks to be re-ordered via up/down buttons.

## Tasks

- Navigation block 
  - [x] Immediately insert block when only one block type is allowed https://github.com/WordPress/gutenberg/issues/16659
  - [x] Add horizontal movers https://github.com/WordPress/gutenberg/issues/16637
  - [x] Menu Item enhancements https://github.com/WordPress/gutenberg/issues/17539
    - Add Link button which shows `URLInput` in toolbar
    - Remove 'Move to start', 'Move left', etc.
    - Allow label to be edited using direct manipulation
    - Allow clicking through to an item's linked page
  - [x] Properly align menu items and nested menu items https://github.com/WordPress/gutenberg/issues/17540
  - [x] Navigation block should display top level pages by default https://github.com/WordPress/gutenberg/issues/17541
  - [x] Add default block stylesheet https://github.com/WordPress/gutenberg/issues/17542
- Block Navigator
  - [x] Allow blocks to be reordered using up/down buttons https://github.com/WordPress/gutenberg/issues/11408
  - [x] Add ability to customise labels https://github.com/WordPress/gutenberg/pull/17519
  - [x] Add ability to insert blocks from inside Block Navigator https://github.com/WordPress/gutenberg/issues/17543
  - [x] Rename 'Block navigation' to something less confusing https://github.com/WordPress/gutenberg/pull/18551
- [x] Enhance URLInput and have it show pages and posts by default https://github.com/WordPress/gutenberg/issues/17557
- [x] Allow background and foreground colours to be customised https://github.com/WordPress/gutenberg/issues/16830

## Future tasks

- Allow moving menu items using drag and drop 
- Allow converting an existing menu into a Navigation block 
- Allow reordering of items in the Block Navigator using drag and drop https://github.com/WordPress/gutenberg/issues/11408
- Allow searching inside the Block Navigator
- Automatically add newly published pages to the Navigation block https://github.com/WordPress/gutenberg/issues/16635
- Allow Navigation block to work in external clients https://github.com/WordPress/gutenberg/issues/17194
- Investigate third party customisation of Navigation block https://github.com/WordPress/gutenberg/issues/17194
- Add support for both horizontal and vertical menus https://github.com/WordPress/gutenberg/issues/16829

**Comment by shaunandrews** [comment]
As a way to keep the initial design and scope simple, I've come to this problem with a few initial assumptions up front:

* Use standard/existing UI where possible.
* Consider everything a block, using child blocks for navigation menu items.
* Focus on a single-level navigation structure. Multi-level structures can be added later.
* Focus on only Pages for now. Other `post_type`'s and URLs can be added later.
* Place move controls within menu item blocks.

With those things in mind—and knowing that these assumptions will need to change as we progress—I've worked up the following design for a very simplistic (but also very useful) Site Navigation block.

![Site Navigation - Page Management Animation i4](https://user-images.githubusercontent.com/191598/65620510-f679b700-df8f-11e9-9349-1bb1eb64808f.gif)

**Comment by talldan** [comment]
Thanks for putting that together @shaunandrews, it's a really big help being able to see the whole process. 

One thing that seems different from most of the discussion I've seen recently is the `+` button behaviour, which is in the mockup is a custom component for adding menu items. 

Previously it's been discussed that this would be a normal block appender, and there's some work underway on https://github.com/WordPress/gutenberg/pull/16708 to make the button insert the menu item directly without showing the inserter menu.

It'd be good to get a steer on which approach we want to take. (cc: @mtias)

**Comment by draganescu** [comment]
@shaunandrews this is awesome. Thank you!

Could we explore submenus / item nesting as well? From the above it is unclear how that will work.

Also @mtias as Dan said above, that appender / inserter is its own thing, very different from the default provided by InnerBlocks, we need to reconcile somehow these differences between the niceties we could do in the block and implementing it with generic system components.

**Comment by getdave** [comment]
> that appender / inserter is its own thing, very different from the default provided by InnerBlocks

I did work some time ago in Gutenberg that allows you to create a fully bespoke appender. It's not set in stone any more. You can pass any component you like.

**Comment by mtias** [comment]
Good eye @talldan. I omitted discussing it in depth because I thought the flow could be easily accommodated with a small tweak: clicking the plus would always insert the menu item first, and the search interface would be invoked from the newly created item (automatically), not the + itself. Does that make sense? The only way I'd keep the + opening an inserter is if we used the actual inserter to choose among "page", "post", "link", "category" entities.

As a general guideline, the (+) should insert an item immediately or open the block inserter. We should avoid appending custom interfaces to it.

**Comment by karmatosed** [comment]
I spent some time collating the current state of navigation into a single Figma file (I will try and keep this up to date). https://www.figma.com/file/cUho7Ont8qqJN06hr8z9Wp/Navigation-Story-So-Far?node-id=3%3A3

It's super rough and involves a lot of Frankenmocks, but it's a good check.

First, the separate parts:

<img width="796" alt="Navigation parts" src="https://user-images.githubusercontent.com/253067/65763302-fa861000-e11a-11e9-8721-f48cb495c94e.png">

Note, right now we don't have a decent mock for nesting so that needs to come.

Here are the current mocks being iterated on:

<img width="1160" alt="Mocks collection_ navigation block" src="https://user-images.githubusercontent.com/253067/65763616-b6473f80-e11b-11e9-9a87-aaffebf246d9.png">

<img width="1107" alt="Mocks collection_ customization" src="https://user-images.githubusercontent.com/253067/65763626-bb0bf380-e11b-11e9-8d3d-033d4d53b9a7.png">

I also did a rough collection of every state of the block (not including customization). Note the design is to be iterated but think of it as showing sketch structure for now. 

<img width="906" alt="Mock actions_ designs unfinished" src="https://user-images.githubusercontent.com/253067/65763749-fefef880-e11b-11e9-8139-dcd16249c2c6.png">

A final collection is the current state of the simplified block being explored by @shaunandrews:

<img width="568" alt="Simple proposal" src="https://user-images.githubusercontent.com/253067/65763740-f7d7ea80-e11b-11e9-84b4-23f65d5452e1.png">

**Comment by shaunandrews** [comment]
> As a general guideline, the (+) should insert an item immediately or open the block inserter. We should avoid appending custom interfaces to it.

I can update the design to match this, but I'm curious why? Adding the menu item immediately means that users then have to delete it (which can be confusing) if they choose to not add a new menu item. To me, this discourages the behavior of exploring how the block works, and mixed up the defined pattern for the + button elsewhere.

**Comment by karmatosed** [comment]
I sort of fall in the camp of the '+' icon inserting menu item first. That said, there is some exploration with the link interface will tie back to this.

For me the current flow makes sense to simplify into this:

- Toolbar: navigator (outline of navigation), name of navigation (able to drop down to change to existing pre-made navigation), add link.
- In the actual block the links and ability to '+' a link.

I am not convinced we even out of box need 'more' or other things in toolbar. I know discussion has been around having toggles/formatting there. I think if we can get a simple prototype that will come.

For example (I left more just incase):

<img width="817" alt="Frame" src="https://user-images.githubusercontent.com/253067/65951238-93789c00-e437-11e9-95d5-7a81edf47187.png">

If we all agree on that we can then move into exploring a few things we need to:

- Link interface: explored but needs final direction.
- Nesting: not fully explored yet.
- Customisation: explored but needs final direction.

On those things, I am also going to look at making summaries like this because I feel checking in on the states will help us move forward.

**Comment by karmatosed** [comment]
Adding some latest images of link interface here:

![image](https://user-images.githubusercontent.com/253067/67232686-d531ac80-f40f-11e9-9c12-5f5c6b1c5c74.png)

Customization:

![image](https://user-images.githubusercontent.com/253067/67232783-0a3dff00-f410-11e9-81cb-9e2e364a3ccb.png)

**Comment by noisysocks** [comment]
Closing this out as the MVP described in the issue has shipped in Gutenberg 7.0. Follow-up issues can be found using the [[Block] Navigation](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+Navigation%22) label or the [Navigation block](https://github.com/WordPress/gutenberg/projects/31) project board. A huge thank you to everyone here for all the hard work!
