### ISSUE TITLE
Storybook: Next steps for better experience when developing UI components

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#17973]
[Storybook](https://storybook.js.org/) was introduced in https://github.com/WordPress/gutenberg/pull/17475. The idea was to have a tool for developing UI components in isolation for React. It is integrated with GitHub pages and folks can see how this tool works in action at http://wordpress.github.io/gutenberg/design-system/components/.

## Next steps
- [ ] Add React Native version of Storybook (https://github.com/WordPress/gutenberg/pull/17829)
- [ ] Add stories for all `@wordpress/components` which contain examples in their README files
- [x] Add knobs extension to allow dynamic modifications of props directly in Storybook (https://github.com/WordPress/gutenberg/pull/17891)
- [x] Explore whether it's possible and makes sense to integrate the playground into the Storybook (https://github.com/WordPress/gutenberg/pull/18191)
- [x] Investigate StoryShots addon which adds automatic Jest Snapshot Testing for Storybook (https://github.com/WordPress/gutenberg/pull/18031)
- [x] Investigate options for visual testing (see https://github.com/WordPress/gutenberg/pull/28554)

## Tweaks
- [x] Include knobs integration to all existing stories
- [x] ~Ensure all exported constants with components start with upper-case to make it easier to use React hooks inside without triggering lint errors~ Move out all React hooks from the exported story functions to their own components (#18030)

**Comment by gziolo** [comment]
> Here's a checklist for the components to help with the Storybook effort. I've noticed @mkaz adding a bunch (which is amazing!). I think this will help

Thanks @ItsJonQ! For those who would like to help, @mkaz posted more details about how to add a story for the existing component: https://mkaz.blog/code/coding-a-storybook-story/. It includes also a live coding demo ✨

**Comment by enejb** [comment]
Just added one for FormToggle Component https://github.com/WordPress/gutenberg/pull/18085

**Comment by brentswisher** [comment]
It looks like the checklist of outstanding components has gotten a little out of date. I went through the components directory and made an updated list: 

# Outstanding Components:
- [ ] autocomplete
- [ ] circular-option-picker
- [ ] custom-gradient-picker
- [ ] date-time
- [ ] dimension-control
- [ ] disabled
- [ ] drop-zone
- [ ] dropdown-menu
- [ ] focal-point-picker
- [ ] focusable-iframe
- [ ] form-file-upload
- [ ] form-toggle
- [ ] form-token-field
- [ ] gradient-picker
- [ ] higher-order/navigate-regions/
- [ ] higher-order/with-constrained-tabbing/
- [ ] higher-order/with-fallback-styles/
- [ ] higher-order/with-filters/
- [ ] higher-order/with-focus-outside/
- [ ] higher-order/with-focus-return/
- [ ] higher-order/with-notices/
- [ ] higher-order/with-spoken-messages/
- [ ] isolated-event-container
- [ ] keyboard-shortcuts
- [ ] menu-group
- [ ] menu-item
- [ ] menu-items-choice
- [ ] navigable-container
- [ ] notice
- [ ] query-controls
- [ ] responsive-wrapper
- [ ] sandbox
- [ ] select-control
- [ ] shortcut
- [ ] slot-fill
- [ ] text-control
- [ ] textarea-control
- [ ] toolbar-button
- [ ] toolbar-context
- [ ] toolbar-item
- [ ] tree-select

I plan on working through all of these components and add the missing stories, but if anyone is interested in helping out, please do! I will try to update this comment with PR Numbers as they get created and check them off as they get merged so it's easier to see where it is at.

**Comment by gziolo** [comment]
It looks like http://wordpress.github.io/storybook is no longer updated after merging changes to master. I filed https://github.com/WordPress/gutenberg/issues/21669.

**Comment by haszari** [comment]
Do you have plans to upgrade Gutenberg project to latest version of Storybook (6+)? 

It looks like it has a new API, so might be some code churn updating – might need to tweak all existing stories, and update build/config too. 

However Storybook 6 might provide some dev-experience benefits, so could be worthwhile. Specifically, `args` may automatically handle interactive UI for props (previously `Knobs` addon; now `Controls` in 6+). There are probably other benefits too, I'm still investigating. 

In [WooCommerce Blocks we're considering upgrading to 6](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3028). So if Gutenberg is sticking with 5, OR is likely to upgrade, we're keen to align and learn from your experience.

Here's some more info about the upgrade:

- https://storybook.js.org/docs/react/writing-stories/args
- https://storybook.js.org/docs/react/writing-stories/introduction#using-args
- https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5

**Comment by gziolo** [comment]
@haszari, we always want to have tooling in their most recent version. Did you manage to migrate WooCommerce Blocks to use v6?

**Comment by haszari** [comment]
> we always want to have tooling in their most recent version. 

❤️ 🚀 Indeed!

> Did you manage to migrate WooCommerce Blocks to use v6?

Yes - see PRs for woo blocks and wc-admin: 

- https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3039
- https://github.com/woocommerce/woocommerce-admin/pull/5105 

We're now running Storybook 6.x, but we haven't adopted all new features yet. The [6.0 way of doing interactive props (`args`)](https://storybook.js.org/docs/react/writing-stories/args) seems powerful, but I couldn't get it working for our components. Tracking this in a blocks issue here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3041

So with that in mind, I'd recommend upgrading to 6.x, and if it's not practical to switch to `args`, continue using `knobs` addon, or worst case [manually hint args](https://github.com/storybookjs/storybook/tree/next/addons/controls#my-controls-arent-being-auto-generated-what-should-i-do) (though this is unfortunate, basically another proptypes declaration).

**Comment by gziolo** [comment]
@haszari I opened  #27813 that upgrades Storybook to v6. I didn't look at the section wit best practices shared in https://storybook.js.org/blog/storybook-6-migration-guide/ yet :)

**Comment by haszari** [comment]
@gziolo Nice! We haven't managed to migrate to controls in woocommerce-blocks yet btw.

**Comment by gziolo** [comment]
@ItsJonQ and @saramarcondes, should we close this issue in favor of the tracking issue #28399 for the new Component System? It would be more beneficial to have good coverage for G2 components in the first place.

**Comment by ItsJonQ** [comment]
@gziolo I think we can probably close this up. Having Storybook in the project is valuable. However, it hasn't been clear how to best structure the stories. Some of the previous components also made it difficult to do so.

I have hope that the stories for the new components will do much better.

Re: React Native. It's not something I have a lot of experience in I'm afraid :(. I'm not familiar with the RN workflow other than using [Expo](https://expo.io/) - so I won't know how best to setup Storybook as part of the Gutenberg workflow for RN.
