### ISSUE TITLE
Improve developer experience surrounding end-to-end tests

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#19172]
Some miscellaneous ideas for improving the developer experience surrounding E2E testing in Gutenberg. This list is sourced from the [November 26 2019 JavaScript chat](https://make.wordpress.org/core/2019/12/02/javascript-chat-summary-november-26-2019/). Each item requires initial investigation. 

- [ ] Have Travis CI not run any tests if the PR does not touch any code. For example: documentation changes.
- [ ] Have the E2E test runner automatically retry failed tests when running on Travis CI. 
- [x] Have the E2E test runner dump out a snapshot of the DOM (and possibly a `page.screenshot()`) when there is an E2E test failure.
- [ ] Create a tool which scrapes Travis CI logs via its API and, for each E2E test, calculates the % failure rate. This would help with identifying flaky tests.
- [ ] Document the common issues encountered when writing E2E tests. For example: trying to click an element that is off-screen, async behaviour, etc. See: https://github.com/WordPress/gutenberg/issues/16452
- [ ] Explore expanding `e2e-test-utils` to provide a higher-level API which does not allow one to write a poorly implemented E2E test.

**Comment by ellatrix** [comment]
Sounds great!

> Have the E2E test runner automatically retry failed tests when running on Travis CI.

Why would we do that? This makes it less likely any often failing test will be fixed.

**Comment by talldan** [comment]
> Have the E2E test runner dump out a snapshot of the DOM (and possibly a page.screenshot()) when there is an E2E test failure.

Another common issue is that a snapshot from an e2e test fails and needs to be updated because of a change in a PR. Having a similar system could be pretty useful so that it's easier to inspect the difference of a snapshot without having to dive into the terminal output. If it were possible to update a snapshot without using a local dev environment, that would also be amazing, but probably a big ask!

**Comment by talldan** [comment]
Also noting that on #18929 I didn't have any issues with failing tests on my local machine at all (Mac OS), but there were quite a few failures with failures on Travis CI (Ubuntu) and they ended up being reverted from `master`, so it seems like there's quite a bit of a disparity between the environments. 

I'm not sure there's better tooling that can help with that, but maybe others have ideas.

**Comment by annezazu** [comment]
Closing this out as it's not clear if this is actionably 4-5 years on. Happy to reopen if we need to but, at this point, a new issue is likely best capturing current feedback.
