### ISSUE TITLE
Consider restructuring Block Registration docs in handbook

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#20161]
**Description**
The Block Registration page in the handbook is currently quite long and hard to navigate:
https://developer.wordpress.org/block-editor/developers/block-api/block-registration/

I'd like to propose dividing it up into the following pages to make it easier to navigate and find information:
- [ ] Block Registration—only include details of `registerBlockType` and `registerBlockCollection`. Link to a new `Block Configuration` page with details of the configuration.
- [ ] Block Configuration—Move https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#block-configuration to its own page. Add new subheadings for `edit` and `save` and link to the `Edit and Save` page under those subheadings.
- [x] Transforms—Move https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#transforms-optional to its own new page (but keep a subheading in the Block Configuration page and link to this page from there). https://github.com/WordPress/gutenberg/pull/21734
- [x] Supports—Move https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#supports-optional to its own new page (but keep a subheading in the Block Configuration page and link to this page from there). https://github.com/WordPress/gutenberg/pull/25647

**Comment by nosolosw** [comment]
I've landed https://github.com/WordPress/gutenberg/pull/21734 that addresses the Block Transforms API.

**Comment by talldan** [comment]
That's awesome, thanks so much for doing that @nosolosw!

**Comment by nosolosw** [comment]
I've prepared https://github.com/WordPress/gutenberg/pull/25647 to extract Block Supports API to its own page.

**Comment by talldan** [comment]
I'll close this as it's a stale issue, and I think there's been quite a bit of restructuring in the ensuing time.
