### ISSUE TITLE
Full Site Editing Breakdown

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#20791]
This is an overview of the concrete tasks needed to proceed with the project scope of Full Site Editing (FSE). 

# Part 1

## Framework (Infrastructure)

- [x] Replace EntityProvider’s and useEntity* hooks with the Block Context API. https://github.com/WordPress/gutenberg/issues/19685 @aduth
- [ ] Theme local assets #20966
- [x] Fix template parts saving behavior #21512 @epiqueras #21766
- [x] Support separate entity "block controllers" in the block-editor @noahtallen #21368. (Fixes various issues with undo & dirty state caused by the block-editor store thinking that everything belongs to the same entity.)

## Edit Site Interface

- [ ] Show the current theme template and hierarchy in the template selector https://github.com/WordPress/gutenberg/issues/19252 https://github.com/WordPress/gutenberg/issues/20421
  - [x] Show the current theme name and preview https://github.com/WordPress/gutenberg/issues/20469
    - [x] Show the current theme name https://github.com/WordPress/gutenberg/pull/21578 @ockham 
    - [x] Show the theme preview on hover #21768 @ockham 
  - [ ] Show template parts in flyout menu https://github.com/WordPress/gutenberg/issues/20470 #21275
- [x] Template parts popover menu and preview https://github.com/WordPress/gutenberg/issues/19253 
  - [x] Add device preview option https://github.com/WordPress/gutenberg/pull/21309 @vindl 
  - [x] Template parts popover menu
- [x] Load a specific context depending on the template (single post, category) in order to « fill » the placeholders https://github.com/WordPress/gutenberg/issues/19257
- [ ] UI to create variations of existing templates https://github.com/WordPress/gutenberg/issues/19259 https://github.com/WordPress/gutenberg/issues/20474
- [x] Improving loading time and loading behavior of the Edit Site screen. https://github.com/WordPress/gutenberg/pull/21214 @youknowriad 
- [x] Iterate on the saving flow https://github.com/WordPress/gutenberg/issues/20421 @Addison-Stavlo 
- [x] Show preview for templates and template parts https://github.com/WordPress/gutenberg/issues/20478 @youknowriad 
- [x] Show template part name in the navigator #21104 #21161 @noahtallen 
- [x] Load the editor styles. #20982 @youknowriad 
- [x] Close button extensibility https://github.com/WordPress/gutenberg/pull/22001 https://github.com/WordPress/gutenberg/pull/22179 @vindl
- [ ] Add a "Revert to default" option for templates and template parts #23421
- [ ] UI Parity #21245
  - [x] Add block inserter in the header
  - [x] Undo / Redo. https://github.com/WordPress/gutenberg/pull/21955 @jorgefilipecosta 
  - [x] Ability to toggle and dismiss Inspector
  - [x] Full screen mode https://github.com/WordPress/gutenberg/pull/20691 https://github.com/WordPress/gutenberg/pull/20989 https://github.com/WordPress/gutenberg/pull/21006 @vindl
  - [x] Spotlight mode #22537 @noahtallen 
  - [x] Block toolbar in header #22537 @noahtallen 
  - [x] Add Patterns #22413 @youknowriad 
  - [ ] Add code editor
  - [ ] Add Tools section with keyboard shortcuts, etc.
  - [x] Add Preview (and devices). https://github.com/WordPress/gutenberg/pull/21309 @vindl

## Small Enhancements

- [ ] Allow creating pages from the « Add Template » flow https://github.com/WordPress/gutenberg/issues/20469
- [x] Show a home page indicator https://github.com/WordPress/gutenberg/issues/20788 @epiqueras #22004
- [x] Export the wp_templates as a theme https://github.com/WordPress/gutenberg/issues/19260 (previous PR: #21958) @epiqueras #22922
- [ ] Improve the template part UI (Document tab for the template part info) https://github.com/WordPress/gutenberg/issues/20200 

## Site and Post Blocks

- [ ] Suite of post blocks https://github.com/WordPress/gutenberg/issues/15623
  - [x] Post Author #19696 #19894
  - [ ] Categories #24091
  - [ ] Post Comments
    - [x] Stub https://github.com/WordPress/gutenberg/pull/19581 https://github.com/WordPress/gutenberg/pull/21012
    - [ ] Full implementation for frontend parity https://github.com/WordPress/gutenberg/issues/24101
- [ ] Better design for placeholder blocks https://github.com/WordPress/gutenberg/issues/19256
- [x] More customisation options to FSE blocks https://github.com/WordPress/gutenberg/issues/19491
- [x] Support htmlTag attribute on the Group block  https://github.com/WordPress/gutenberg/issues/20200 @gziolo @youknowriad 
- [ ] Add a Query block https://github.com/WordPress/gutenberg/pull/20106
- [ ] Template Parts with HTML tags: https://github.com/WordPress/gutenberg/issues/20997
- [ ] Feature parity with regular blocks #21087

# Part 2

## Framework (Infrastructure)

- [ ] Load the appropriate FSE template on the post / page editor #21086

## Interface

- [ ] Rethinking the "Current Document" display and settings #20877
- [ ] Mosaic View of Theme Templates #20477
- [ ] Add link to templates and template parts listing in site editor #21246

## Blocks

- [ ] Add a Grid block and use it as a starting point for blank templates https://github.com/WordPress/gutenberg/issues/19254 https://github.com/WordPress/gutenberg/pull/20000

---

## Global Styles

Refer to this issue instead https://github.com/WordPress/gutenberg/issues/20331

**Comment by mtias** [comment]
Moved the _Grid_ block to the second wave so we can focus a bit better on the initial pass.

**Comment by Addison-Stavlo** [comment]
@youknowriad @mtias -  has anything related to #21218 / #21219 been discussed / triaged towards work here yet?  I have noticed these problems and they seem important, but I hadn't noticed anything discussed about them yet so I opened the issues noted above.

**Comment by mtias** [comment]
It was meant to be covered by #19254, though that issue took a spin towards the grid block that wasn't the intention. It's useful to break it apart anyways.

**Comment by epiqueras** [comment]
This is an excellent prioritization of tasks. I am excited to start drilling through!

**Comment by epiqueras** [comment]
Two issues/tasks stand out to me the most here because they are very foundational and require material framework changes.

>Theme local assets #20966

The scope here is a lot broader than it first seems. Things like localization will have the same issue that dynamic URLs have, that our level of granularity for defining dynamic content areas is too coarse, it's entire blocks. I wrote about a possible solution [here](https://github.com/WordPress/gutenberg/issues/20966#issuecomment-616886608), inline "blocks". Ideally, we arrive at a solution that paves the ground for the next phases of Gutenberg.

>Add a Query block #20106

The Query block will be the block editor counterpart of writing a `WP_Query` and rendering "the loop" in PHP. This is a foundational part of the majority of layouts and especially important because [all templates should essentially be rendered under an implicit Query block](https://github.com/WordPress/gutenberg/issues/19257#issuecomment-617947922) computed from the current URL.

We also need to pay a lot of attention to pagination as it should be easy to separate sibling Query blocks by static content and have one continue the other's loop.

**Comment by youknowriad** [comment]
This issue served us well to implement the first iterations of Full Site Editing. We're trying to split this work into well-defined milestones in #24551. So I'm going to close this issue in favor of that one.
