### ISSUE TITLE
Feature parity between FSE Blocks and regular blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21087]
We have several new full site editing blocks that we need to match feature-wise with what regular blocks offer:

- [x] Site Title → Heading (@apeatling) https://github.com/WordPress/gutenberg/pull/22843, #23007
- [x] Site Tagline → Paragraph (@copons) #23788
- [x] Post Title → Heading (@apeatling @copons) #22872 #24246
- [x] Post Date → Paragraph (@copons) #23931
- [x] Post Author → Paragraph (@Addison-Stavlo) #22877, #23044
- [x] Post Content → Paragraph / Group (@noahtallen, #24014)
- [x] Post Excerpt → Paragraph (@Addison-Stavlo) #23945
- [x] Post Tags → Paragraph (@jeyip) #24069 #24082
- [x] Post Categories → Paragraph (@Copons) #24091

--- 

- [x] Comments → Paragraph / Group (@Addison-Stavlo) #24080 (follow up: #24101)
- [x] Comment Count → Paragraph (@Copons) #24167
- [x] Comment Form / Reply → Paragraph (@Copons) #24162 (follow up: #24221)

**Comment by aduth** [comment]
For technical implementation, I'd wondered if it might be something to implement as deferring to the implementation of another block. We have some of the pieces of this, e.g. [`<BlockEdit />`](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-edit/index.js).

But in most of these cases, is it really much more than [`<RichText />`](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/rich-text), with a particular configuration? It would be nice if we could leverage components for the shared baseline. The main unknown at this point would be in implementing common attributes, which I think could be addressed as part of proposals of #15450.

Ideally then, the implementation for _either_ the "Site Title" or "Heading" blocks could look something like:

```js
function edit() {
    useTextAlignment();
    useTextColor();
    // useHeadingLevel(); // ???

    return <RichText { /* ... */ } />;
}
```

_(For demonstration only, not a finished API)_

**Comment by youknowriad** [comment]
@aduth Personally, I'm leaning more towards expanding the approach used in #21021 to all these customizations which is close to the proposal above with a bit less flexibility (support keys) but more capabilities, touching any part of the block registration/filters.

**Comment by aduth** [comment]
@youknowriad Yeah, in the context of this issue, I'm not so much concerned about the specific API for reusing common behaviors, but more to the point that we don't need "Site Title" block to be aware of a "Heading" block if each can be mostly recreated with relative ease by opting in to a combination of common components and block functionality.

**Comment by MichaelArestad** [comment]
Does this need design feedback here or can we provide feedback on individual PRs?

**Comment by mtias** [comment]
We need to map out what tools make sense for each.

**Comment by karmatosed** [comment]
I took a quick look at this to try and surface out what we could have on each block.

## Default parity
Both the heading and paragraph block have the following: 

Align: left/centre/right, Text styling: bold, italic, Link, Inline code, Inline image, Strikethrough, Text color.

There are also extra options for: 

Hide Block Settings, Duplicate, Insert Before, Insert After, Edit as HTML, Add to Reusable blocks, Group, Remove Block.

## FSE blocks
I would say the following should exist across all:

Align: left/centre/right, Text styling: bold, italic, Text color

The ones I am not as sure about would be:

Link, Inline code, Inline image, Strikethrough

The options probably should exist across all, but I could see an argument for trimming some of those.

**Comment by mtias** [comment]
There's a lot of those that don't make sense for the site / post blocks in the context of FSE. All the inline formatting tools, for example, don't make sense because the text is not selectable — only block level changes would apply.

**Comment by karmatosed** [comment]
In light of removing any inline my recommendations then would be:

Align: left/centre/right alone. I do wonder about text color changing it all, but that can be later.

**Comment by dwolfe** [comment]
I touched on this in my most recent update on [the placeholder blocks issue](https://github.com/WordPress/gutenberg/issues/19256#issuecomment-605367908).

My thinking was very close to your original list, @mtias, with the exception of Tags and Categories - would those be lists?

**Comment by nosolosw** [comment]
I've added these blocks in https://github.com/WordPress/gutenberg/issues/22700 to keep track of the work related to style attributes.

**Comment by apeatling** [comment]
@karmatosed @mtias I'm starting with the Site Title block. Changing this to use `RichText` component instead of `PlainText` allows the block to support the standard tooling:

<img width="511" alt="Screen Shot 2020-06-02 at 10 19 59 AM" src="https://user-images.githubusercontent.com/1464705/83549798-b8d41300-a4ba-11ea-89ba-14a7fa1a21a2.png">

 Reading above I'm unclear on what the decision was. The text in this block is selectable and editable so limiting to alignment only seems limiting.

**Comment by apeatling** [comment]
The issue with supporting these formatting options for something like Site Title is WordPress escapes the entities so you get this on the front end:

<img width="712" alt="Screen Shot 2020-06-02 at 10 28 57 AM" src="https://user-images.githubusercontent.com/1464705/83550604-f1c0b780-a4bb-11ea-80fc-abea9ab8761c.png">

**Comment by mtias** [comment]
Yes, we cannot use rich text here. We can support block-level color tools and font-sizes, though.

**Comment by noahtallen** [comment]
> Align: left/centre/right alone.

Which alignments and options should be supported for the post-content block?

**Comment by Copons** [comment]
Just FYI I've updated the issue:
- Checked "Site Title → Heading" (as far as I can see there are no outstanding features left to update).
- Added #23788 to "Site Tagline → Paragraph".

Should we add the [experimental colors, font size, line height](https://github.com/WordPress/gutenberg/pull/23007) to all FSE blocks?
(Colors might not make sense everywhere though, or might be more involved than just add a support property, e.g. for "linked elements", like the Post Title or Comment Count)

**Comment by MichaelArestad** [comment]
> Should we add the experimental colors, font size, line height to all FSE blocks?

It makes sense for a few blocks like Site Title, Description, tags, categories, etc. Blocks that a user won't have design control of elsewhere.

**Comment by Copons** [comment]
With the merge of #24091 we've checked all items for this tracking issue! 🎉 
FSE blocks should, can, and will be updated and improved over time, but I'm going to close this issue for now, since the basic requiremens are all complete.
Thanks y'all for the great work!

**Comment by mtias** [comment]
Thanks!
