### ISSUE TITLE
Site Editing: UI Parity

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21245]
These are some of the features that are lacking in `edit-site` at the moment compared to regular editor.

- [x] Add block inserter in the header.
- [x] Undo / Redo. https://github.com/WordPress/gutenberg/pull/21955 @jorgefilipecosta 
- [x] Ability to toggle and dismiss _Inspector_.
- [x] Full screen mode #20691 #20989 #21006 @vindl
- [x] Spotlight mode (#22537 @noahtallen)
- [x] Top toolbar (#22537 @noahtallen)
- [x] Add _Patterns_  #22413 @youknowriad 
    - [x] Show them everywhere #25915 
- [x] Add code editor @jorgefilipecosta https://github.com/WordPress/gutenberg/pull/37765
- [ ] Add _Tools_ section 
    - [x] block manager
    - [x] reusable blocks link (#22539 @noahtallen)
    - [x] keyboard shortcuts (#37650 @Mamaduka)
    - [x] welcome guide
    - [ ] copy all content @jorgefilipecosta
    - [x] help link (#22539 @noahtallen)
- [x] Add Preview (and devices). https://github.com/WordPress/gutenberg/pull/21309 @vindl

**Comment by vindl** [comment]
> Full screen and spotlight modes.

Just a note that Full screen was added in these PRs: https://github.com/WordPress/gutenberg/pull/2069, https://github.com/WordPress/gutenberg/pull/21006.

**Comment by vindl** [comment]
Device preview added in https://github.com/WordPress/gutenberg/pull/21309.

**Comment by MichaelArestad** [comment]
Noting this here (instead of the above closed issue): I would expect parity on the more menu options shown here:

![image](https://user-images.githubusercontent.com/1123119/80990015-f62d7e00-8df2-11ea-99c1-0e838ee828d4.png)

**Comment by noahtallen** [comment]
PRs up for top toolbar (#22537) and focus mode (#22535)

**Comment by noahtallen** [comment]
Pulling a discussion out of: https://github.com/WordPress/gutenberg/pull/22539#discussion_r429450568 for more visibility. cc @youknowriad & @epiqueras 

For the time being, we have accepted that duplicating some code between edit-post and edit-site is acceptable. We don't want to make an abstraction too early which doesn't make sense in the long run. However, when looking into porting the "tools" section of edit-post into edit-site, I realized there is a significant amount of code to copy over.

For two reasons, I wonder if we should _not_ duplicate some of this stuff until we come up with a better abstraction:
- The amount of code is quite large, particularly as relates to the block manager, keyboard shortcuts, and all of the UI options. And all of this code needs to be essentially duplicated and have the same behavior. (So obviously, it makes no sense at all to duplicate it in the long run.)
- Are any of these features really important for us to have this early in development? Things like managing keyboard shortcuts and blocks are tangential to the FSE experience.

In the future, since we would need to un-duplicate it anyways, I think it would mostly just be wasted time.

This doesn't apply to everything. For example, focus mode and the block toolbar in the header are both primarily implemented in the block-editor package, so the majority of the code is reused between edit-site and edit-post anyways.

Additionally, the code editor will need to be updated to work better with multiple entities.

But some of this other stuff seems like a lot of work for not a lot of benefit at the time being.

This leads me to wonder how much of the "basic UI parity" features should be duplicated before we come up with a good abstraction. I don't think "all of them" makes sense because there would be so much to basically just copy over and hook in. And then we have two copies of everything floating around and we aren't any closer to having a better abstraction.

**Comment by epiqueras** [comment]
A `@wordpress/editor-configuration` or `@wordpress/editor-settings` package makes sense now.

**Comment by vindl** [comment]
> Are any of these features really important for us to have this early in development? Things like managing keyboard shortcuts and blocks are tangential to the FSE experience.

I don't think they are that important at this stage. And I agree with you that it would be a waste of time if they are duplicated now.

**Comment by noahtallen** [comment]
This looks related: https://github.com/WordPress/gutenberg/pull/21430

**Comment by bobbingwide** [comment]
@mtias Perhaps you could update the initial checkbox item "keyboard shortcuts" in the initial comment to reflect the fact that there  have been at least two separate issues raised and closed without a fix or any sign of a plan to fix them.  
I would suggest either attaching #30294, since it's still open,  or re-open the closed issues until they have been fixed.

**Comment by annezazu** [comment]
I see this checked off currently:

>help link (Edit Site: Add basic "tools" menu #22539 @noahtallen)

However, when I look at the experience today, I only see the option to export items but don't see a specific help option in place. Since FSE is so new, it would be advantageous to have a link to support docs built into the interface. Is this something that can be added ahead of 5.9?

**Comment by Mamaduka** [comment]
I started working on Keyboard Shortcut help modal. Unfortunately, it's a bit late for the 5.9, but we should backport it into a minor release.

**Comment by Mamaduka** [comment]
@annezazu, do we have a documentation URL for the "Help" button?

**Comment by annezazu** [comment]
This will eventually be the URL: https://wordpress.org/support/article/site-editor/ This will provide a similar experience as the Post Editor which links to https://wordpress.org/support/article/wordpress-editor/.

**Comment by carolinan** [comment]
@annezazu I'm out of the loop because of the holidays, does that mean the project agreed to keep using the term "site editor" ?
Is it still only going to be called "Editor" under appearance?

**Comment by annezazu** [comment]
It's only going to be called "Editor" under Appearance but I'm not quite sure how else to position this. If we reuse the current https://wordpress.org/support/article/wordpress-editor/ doc and add in FSE related content, it'll likely confuse many of the folks who are just using the Post Editor. The best middle ground I could provide was by creating a separate doc for the Site Editor since that matches what was done with the template editor. Open to ideas/thoughts though around how best to proceed here :) In time, I imagine all of this will turn into just the WordPress editor but, for now, we need some in between solutions. Here's the documentation tracking issue here: https://github.com/WordPress/Documentation-Issue-Tracker/issues/93
