### ISSUE TITLE
Block Library: FSE Blocks: Use block context

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#21665]
Previously: #21467
Related: #21662

**Context:**

#21467 implements support for formal block context. This should be used in the implementation of full-site editing blocks, many of which currently either render static content, or retrieve the post context by other means (see #21662). These should be updated to retrieve entities for their respective context, using block context.

**Progress:**

- [x] `core/post-title` (#21467)
- [x] `core/post-content` (#21696) (resolved in #22473)
- [ ] `core/post-author` (#21696)
- [ ] `core/post-comments` (#21696)
- [ ] `core/post-comments-count` (#21696)
- [ ] `core/post-comments-form` (#21696)
- [ ] `core/post-date` (#21696)
- [ ] `core/post-excerpt` (#21696)
- [ ] `core/post-featured-image` (#21696)
- [ ] `core/post-tags` (#21696)
- [ ] `core/site-title` (#21696)
- [ ] `core/template-part` (#21696)

**Comment by aduth** [comment]
Reopening since #21696 only updated the server-side implementation.

Client-side will still require revisions, largely to reimplement the existing blocks to avoid using `useEntityProp` in most cases in favor of a combination of (a) block context and (b) [`core-data` entities](https://github.com/WordPress/gutenberg/blob/master/packages/core-data/README.md). 

An example reference is #22359, updating the Post Author block to use block context in the client-side implementation.

**Comment by ntsekouras** [comment]
Closing as all of the tasks have been merged.
