### ISSUE TITLE
Coding Guidelines: Transition to multiline syntax for dependency groupings

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#22560]
Related Slack discussion ([link requires registration](https://make.wordpress.org/chat/)): https://wordpress.slack.com/archives/C5UNMSU4R/p1589896942168400

JavaScript files in Gutenberg currently organize imported module members amongst groups "External", "WordPress", "Internal".

Example:

```js
/**
 * WordPress dependencies
 */
import { useSelect } from '@wordpress/data';
```

See documentation: https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#imports

The use of JSDoc `/**` syntax is non-standard for use in all places except for documenting functions and variables:

>Important note: Multi-line comments must not begin with /** (double asterisk). Use /* (single asterisk) instead.

https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/#multi-line-comments

It is also prone to a few potential issues, due to the fact that it can be misinterpreted as JSDoc documentation:

- Editor integrations may wrongly interpret the grouping heading as documenting the first imported assignment following the docblock.
   - ![image](https://user-images.githubusercontent.com/1779930/82709662-1791c500-9c4f-11ea-8e33-c72076c3a311.png)
- The [`@wordpress/docgen`](https://github.com/WordPress/gutenberg/tree/master/packages/docgen) automated documentation tool may wrongly interpret the grouping heading as describing an exported module member.

**Task:**

All import grouping headings should be changed to use the `/*` syntax instead of `/**`.

**Implementation Notes:**

This can be broken down into several subtasks:

- [ ] Update [relevant coding guideline examples](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#imports).
- [ ] Update [`@wordpress/eslint-plugin` `dependency-group` rule](https://github.com/WordPress/gutenberg/blob/master/packages/eslint-plugin/docs/rules/dependency-group.md) to allow for this `/*` syntax.
- [ ] Update `@wordpress/eslint-plugin` `dependency-group` rule to allow use this syntax in its [fixer](https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes) implementation.
- [ ] Mass-update all occurrences of dependency group comments.
- [ ] Update [`@wordpress/eslint-plugin` `dependency-group` rule](https://github.com/WordPress/gutenberg/blob/master/packages/eslint-plugin/docs/rules/dependency-group.md) to flag `/**` as an invalid grouping syntax.

**Comment by annezazu** [comment]
Closing this out as it's not clear if this is actionably 4 years on. Happy to reopen if we need to but, at this point, a new issue is likely best capturing current feedback.
