### ISSUE TITLE
Add READMEs to all block-editor components

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#22891]
The Block Editor package in Gutenberg is full of components used to build blocks or block editors. These components lack documentation.

This issue is a tracking issue for the documentation effort to add READMEs to all these components.

If you want to help with this:

 - Grab [a component in the block-editor package](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components) that lacks a README
 - Comment on the issue that you want to help document this component
 - Write a README.md file for this component following the same format as the already documented components.

**Comment by alita-moore** [comment]
I want to make a README for the block-alignment-matrix-toolbar, issue #22516 ; How should I proceed?

**Comment by youknowriad** [comment]
@alita-moore yes, a README is needed for that component. so you should add a file to the component folder name it README.md, copy some existing component README to get the "base  template" and fill it.

**Comment by alita-moore** [comment]
Okay,

[This README](https://www.github.com/WordPress/gutenberg/tree/master/packages%2Fblock-editor%2Fsrc%2Fcomponents%2Fautocomplete%2FREADME.md)

Doesn't have a very defined structure. Are you saying to copy the format in terms of linking to the parent directory?

**Comment by youknowriad** [comment]
Yes, this is not the best example. This might work better https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/README.md

**Comment by alita-moore** [comment]
Oh okay, that's much better.

Thank you for info, I'll get cracking 👩‍💻

**Comment by JustinyAhin** [comment]
Working on a pull for BlockBreadcrumb componenent https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-breadcrumb

**Comment by JustinyAhin** [comment]
I've identified all the packages that haven't yet a README.

**Comment by JustinyAhin** [comment]
### Block editor packages that still lack README

 - [x] [alignment-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/alignment-toolbar) -- https://github.com/WordPress/gutenberg/pull/25210 --- @JustinyAhin 
 - [ ] [block-actions](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-actions) (not exported)
 - [x] [block-alignment-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-alignment-toolbar) -- https://github.com/WordPress/gutenberg/pull/25212 --- @JustinyAhin 
 - [x] [block-breadcrumb](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-breadcrumb) ---  https://github.com/WordPress/gutenberg/pull/24827 - @JustinyAhin 
 - [ ] [block-caption](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-caption) --- @JustinyAhin (not exported)
 - [x] [block-card](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-card) -- https://github.com/WordPress/gutenberg/pull/25150 --- @JustinyAhin (not exported)
 - [ ] [block-controls](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-controls)
 - [ ] [block-draggable](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-draggable) (not exported)
 - [ ] [block-edit](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-edit)
 - [x] [block-format-controls](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-format-controls) --- https://github.com/WordPress/gutenberg/pull/25573 @jorgefilipecosta 
 - [x] [block-icon](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-icon) -- https://github.com/WordPress/gutenberg/pull/24947  ---  @JustinyAhin 
 - [x] [block-inspector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-inspector) --- https://github.com/WordPress/gutenberg/pull/24929 @JustinyAhin 
 - [ ] [block-list-appender](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-list-appender) (not exported)
 - [ ] [block-list](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-list)
 - [ ] [block-mobile-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-mobile-toolbar)
 - [x] [block-mover](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-mover) --- https://github.com/WordPress/gutenberg/pull/24851 - @JustinyAhin 
 - [x] [block-navigation](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-navigation) --- https://github.com/WordPress/gutenberg/pull/24882 - @JustinyAhin 
 - [x] [block-parent-selector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-parent-selector) --- https://github.com/WordPress/gutenberg/pull/24962 - @JustinyAhin (not exported)
 - [x] [block-patterns-list](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-patterns-list) --- https://github.com/WordPress/gutenberg/pull/24983 -  @JustinyAhin (not exported)
 - [ ] [block-selection-clearer](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-selection-clearer)
 - [ ] [block-settings](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-settings) (not exported)
 - [ ] [block-styles](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-styles) (not exported)
 - [x] [block-switcher](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-switcher) -- not exported
 - [x] [block-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-toolbar) -- https://github.com/WordPress/gutenberg/pull/25245 --- @JustinyAhin 
 - [x] [block-types-list](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-types-list) --- https://github.com/WordPress/gutenberg/pull/25066 - @JustinyAhin (not exported)
 - [x] [block-variation-picker](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-variation-picker) --- https://github.com/WordPress/gutenberg/pull/24995 - @JustinyAhin
 - [ ] [caption](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/caption) --- @vcanales (not exported)
 - [ ] [color-palette](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/color-palette) --- @vcanales 
 - [ ] [color-style-selector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/color-style-selector) --- @vcanales (not exported)
 - [ ] [color-gradients](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/colors-gradients) --- @vcanales
 - [ ] [colors](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/colors) --- @vcanales 
 - [x] [contrast-checker](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/contrast-checker) - https://github.com/WordPress/gutenberg/pull/25570 --- @itsjonq
 - [x] [copy-handler](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/copy-handler) -- https://github.com/WordPress/gutenberg/pull/25342 --- @JustinyAhin 
 - [ ] [default-block-appender](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/default-block-appender)
 - [ ] [default-style-picker](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/default-style-picker) (not exported)
 - [ ] [editor-styles](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/editor-styles) (not exported)
 - [ ] [floating-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/floating-toolbar) (not exported)
 - [x] [focus-detector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/focus-detector) --- #25561 @mcsf  (not exported)
 - [x] [font-family](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/gradients) --- #52118
 - [x] [font-sizes](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/font-sizes) --- https://github.com/WordPress/gutenberg/pull/25568 @jorgefilipecosta
 - [ ] [gradient-picker](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/gradient-picker) --- (not exported)
 - [x] [gradients](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/gradients) --- @georgeh 
 - [ ] [inserter-list-item](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inserter-list-item) -- https://github.com/WordPress/gutenberg/pull/25116 --- @JustinyAhin (not exported)
 - [ ] [inserter-menu-extension](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inserter-menu-extension)
 - [ ] [inserter](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inserter)
 - [x] [inspector-advanced-controls](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inspector-advanced-controls) --- #25566 @mcsf 
 - [ ] [keyboard-shortcuts](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/keyboard-shortcuts) -- https://github.com/WordPress/gutenberg/pull/25284 --- @JustinyAhin (not exported)
 - [x] [line-height-control](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/line-height-control) -- https://github.com/WordPress/gutenberg/pull/25303 --- @JustinyAhin
 - [ ] [multi-select-scroll-into-view](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/multi-select-scroll-into-view)
 - [x] [multi-selection-inspector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/multi-selection-inspector) -- https://github.com/WordPress/gutenberg/pull/25306 --- @JustinyAhin (not exported)
 - [ ] [navigable-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/navigable-toolbar) -- @georgeh 
 - [ ] [page-template-picker](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/page-template-picker) (not exported)
 - [ ] [panel-color-settings](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/panel-color-settings)
 - [ ] [preserve-scroll-in-reorder](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/preserve-scroll-in-reorder)
 - [x] [preview-options](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/preview-options) -- https://github.com/WordPress/gutenberg/pull/25104 --- @JustinyAhin 
 - [ ] [skip-to-selected-block](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/skip-to-selected-block)
 - [ ] [spacing-panel-control](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/spacing-panel-control) (not exported)
 - [ ] [tool-selector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/tool-selector)
 - [ ] [typewriter](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/typewriter)
 - [x] [ungroup-button](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/ungroup-button) - https://github.com/WordPress/gutenberg/pull/25142 --- @JustinyAhin (not exported)
 - [x] [unit-control](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/unit-control) - https://github.com/WordPress/gutenberg/pull/25565 --- @ItsJonQ (not exported)
 - [ ] [use-display-block-controls](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-display-block-controls) (not exported)
 - [ ] [use-moving-animation](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-moving-animation) (not exported)
 - [ ] [use-editor-feature](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-editor-feature) --- @itsjonq
 - [ ] [use-on-block-drop](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-on-block-drop) (not exported)
 - [ ] [use-resize-canvas](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-resize-canvas) --- @johngodley
 - [ ] [use-simulated-media-queries](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-simulated-media-query) --- @johngodley
 - [ ] [video-player](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/video-player) (not exported)
 - [x] [warning](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/warning) --- @mcsf
 - [ ] [writing-flow](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/writing-flow)

**Comment by dgwyer** [comment]
### Block editor packages that still need a README (updated list)

* [ ] [block-actions](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-actions) -- @pbking 
* [ ] [block-caption](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-caption) -- @SiobhyB 
* [ ] [block-content-overlay](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-content-overlay) -- @t-hamano 
* [x] [block-controls](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-controls) -- #52366 @jsnajdr @ciampo 
* [ ] [block-draggable](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-draggable)
* [ ] [block-edit-visually-button](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-edit-visually-button)
* [ ] [block-edit](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-edit)
* [ ] [block-list-appender](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-list-appender)
* [ ] [block-list](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-list)
* [ ] [block-lock](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-lock)
* [ ] [block-mobile-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-mobile-toolbar)
* [ ] [block-navigation](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-navigation)
* [ ] [block-pattern-setup](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-pattern-setup)
* [ ] [block-selection-clearer](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-selection-clearer)
* [ ] [block-settings](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-settings)
* [ ] [block-styles](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-styles)
* [ ] [block-switcher](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-switcher)
* [ ] [block-tools](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-tools)
* [ ] [border-radius-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/border-radius-control)
* [x] [caption](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/caption) -- #52033 @juanmaguitar 
* [ ] [color-palette](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/color-palette)
* [ ] [color-style-selector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/color-style-selector)
* [ ] [color-gradients](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/colors-gradients)
* [ ] [convert-to-group-buttons](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/convert-to-group-buttons)
* [ ] [default-block-appender](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/default-block-appender)
* [ ] [default-style-picker](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/default-style-picker)
* [ ] [duotone](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/duotone)
* [ ] [duotone-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/duotone-control)
---
* [ ] [editor-styles](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/editor-styles) -- @youknowriad, @ellatrix 
* [ ] [floating-toolbar](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/floating-toolbar) -- @jbinda 
* [ ] [font-appearance-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/font-appearance-control) -- @andrewserong, @aaronrobertshaw 
* [x] [font-family](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/font-family) --  #52118 @jorgefilipecosta, @tyxla 
* [ ] [iframe](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/iframe) -- @ellatrix, @t-hamano 
* [ ] [image-editor](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/image-editor) -- @ajlende 
* [ ] [inserter-draggable-blocks](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/inserter-draggable-blocks) -- @youknowriad 
* [ ] [inserter-list-item](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/inserter-list-item) -- @youknowriad 
* [ ] [inserter-list-box](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/inserter-listbox) -- @diegohaz 
* [ ] [inserter-menu-extension](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inserter-menu-extension) -- @noisysocks, @talldan 
* [ ] [inserter](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inserter) -- @talldan, @glendaviesnz 
* [ ] [keyboard-shortcuts](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/keyboard-shortcuts) -- @youknowriad, @ellatrix 
* [x] [letter-spacing-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/letter-spacing-control) -- #45308 @carolinan 
* [x] [panel-color-settings](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/panel-color-settings) -- #52327 @tyxla 
* [x] [recursion-provider](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/recursion-provider) -- #52334 @talldan, @tyxla 
* [ ] [selection-scroll-into-view](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/selection-scroll-into-view) -- @youknowriad, @ellatrix 
* [ ] [spacing-sizes-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/spacing-sizes-control) -- #60086 @glendaviesnz, @aaronrobertshaw 
* [ ] [text-decoration-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/text-decoration-control) -- @noisysocks, @aaronrobertshaw 
* [x] [text-transformation-control](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/text-transform-control) -- #52243 @BenjaminZekavica
* [ ] [tool-selector](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/tool-selector) -- #60145 @youknowriad, @ciampo 
* [ ] [typewriter](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/typewriter) -- @Mamaduka, @ellatrix 
* [ ] [use-display-block-controls](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-display-block-controls) -- @gziolo, @ellatrix 
* [ ] [use-moving-animation](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-moving-animation) -- @youknowriad, @talldan 
* [ ] [use-on-block-drop](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/use-on-block-drop) -- @talldan, @kevin940726 
* [x] [use-setting](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/use-setting) -- #53162 @ingeniumed
* [ ] [video-player](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/video-player) -- @SergioEstevao, @geriux

**Comment by carolinan** [comment]
Do we only document items that are exported? (part of this list https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/index.js)
I would like to help but it has been difficult for me to figure out which of these are actionable.

**Comment by youknowriad** [comment]
I think the highest priority ones are the ones that are exported and don't have any `__experimental` prefix.

**Comment by juanmaguitar** [comment]
For reference, The `README.md` at [https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md) is a good model to follow for the rest of the components

**Comment by talldan** [comment]
Just thought I'd mention that I have a few months of leave coming up, so won't be able to work on these for a while. I notice I was assigned a few.

**Comment by mburridge** [comment]
Hi @talldan, please feel free to re-assign those to someone else that you deem has the technical knowledge required to create the readme. Thanks.

**Comment by t-hamano** [comment]
If someone works on this issue, in addition to adding a README file, it would be great if we could also add JSDoc.
[The block editor package reference](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/) is generated with a JSDoc reference for each component. Components that don't have JSDoc will look like this in the reference:

![Image](https://github.com/user-attachments/assets/825314c7-526f-4ed8-9603-3d3ee9012b3d)

The recommended complete JSDoc format should look like this:

```jsx
/**
 * Component description here.
 *
 * @see https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/my-component/README.md
 *
 * @example
 * ```jsx
 * function MyComponent() {
 *   return (
 *     <MyComponent />
 *    );
 * }
 * ```
 *
 * @param {Object}  props        Component props.
 * @param {string}  props.prop1  props description here.
 * @param {Array}   props.prop2  props description here.
 * @return {Element} My component control.
 */
export default function MyComponent( {
	prop1,
	prop2,
} ) {
	return (
		<div>
			My Component
		</div>
	);
}
```

**Comment by 0x8sksr** [comment]
Can guide me on how to start or just go with the example from the other documented components, such as this one for button? Thanks!

**Comment by t-hamano** [comment]
@0x8sksr There are many components in [the `block-editor` directory](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components) that already have READMEs, so you can use those as a reference.

**Comment by stokesman** [comment]
For components that are used in Block Supports would it be a good idea include a suggestion for that API? For example, `SpacingSizesControl` could point out that [Spacing support](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#spacing) may facilitate their use case. The only concern I can think of might be if the block supports switches to a different control it would make the suggestion incorrect so including such suggestions is more maintenance burden.

**Comment by stokesman** [comment]
A issue with the guidance to follow the format of existing READMEs is that not all aren’t consistent. The biggest difference I find is that some include "Development guidelines" as a heading above "Usage" and "Props". I thought the point should be raised to settle on a more specific guidance. My feeling is the "Development guidelines" heading should be avoided in the future. If so, we could also remove that from existing READMEs that have it. I didn’t see way to get a URL for the exact search but here’s the query that can be pasted in to search:
```
repo:WordPress/gutenberg path:/^packages\/block-editor\/src\/components\//  language:Markdown /#+ Development guidelines/
```

**Comment by carolinan** [comment]
Hi

A suggestion to put this issue on hold was brought up in the [WordPress Slack channel (account needed)](https://wordpress.slack.com/archives/C02QB2JS7/p1741239852974279).

Currently there are 149 developer documentation pull requests open that are awaiting review, from 2021 and later.
https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+is%3Aopen+label%3A%22%5BType%5D+Developer+Documentation%22+review%3Anone

Before opening new pull requests for this issue please consider reviewing one of the existing pull requests.

Another idea is to arrange regular scrubs where these pull requests are reviewed, so that they do not continue to become stale/ out of date.

**Comment by youknowriad** [comment]
I'm going to close this issue. I don't feel like it adds too much value.
