### ISSUE TITLE
Overview - [Block] Navigation

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#22930]
This is an overview issue that we'll maintain going forward into WP 5.5 and 5.6 milestones. It attempts to track discussions and resulting actions about the Navigation Block.

This overview does not track bugs of the Navigation Block, for that you should filter open issues using the labels [Block] Navigation and [Type]Bug.

### Action items
Action items are things that need a PR for implementation or exploration.

- [ ] Iterate on 'add navigation link' #22750
- [ ] Make the Navigation block it Mobile Responsive #22824
- [ ] Consider showing the link url beside the icon when one is set in navigation #22836
- [ ] Hide the empty Links in Navigation when the block is not selected #21848
- [x] Remove the block navigator in the sidebar #20846
- [ ] Visually show selection, for example showing a selection box like when we press Esc. This is quite useful for destructive operations, such as menu item delete.
- [ ] Animate the deletion of an item instead of suddenly removing it from the block’s children.

### Discussions
Discussions are general topics where we're less clear so we cannot start a PR to explore or implement.

- [ ] A “Pages” block sounds like a good idea to replace the global auto-add option. This block would optionally allow this auto adding behavior and also handle automatically build a nested pages navigation.
- [ ] Do we still want menus to be tied to locations?
- [ ] Does the current post type storage for menus offer any advantages over block storage?

**Comment by draganescu** [comment]
Closed in favor of #27593
