### ISSUE TITLE
Overview - [Feature] Navigation Screen

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#22931]
This is an overview issue that we'll maintain going forward into WP 5.5 and 5.6 milestones. It attempts to track discussions and resulting actions about the new Navigation screen

This overview does not track bugs present in the new Navigation screen, for that you should filter open issues using the labels [Feature] Navigation Screen and [Type]Bug.

## Block navigator

The block navigator is getting a lot of new features because of the requirements it has to solve in the new Navigation screen. Some of these updates are useful outside of this context as well, so they're considered also from the point of view of generic Gutenberg block editors (e.g. the Post editor).

### Action items
Action items are things that need a PR for implementation or exploration.

- [x] Block Navigator/Navigation: Drag & Drop #22297
- [x] The action to add a sub-menu should be available in the corresponding navigator item (either in the ellipsis menu or as its own button). potentially #22998
- [x] The ellipsis menu in the navigator UI should replicate the block ellipsis menu (duplicate, remove, etc). 
- [x] In navigator show the inserter only for selected nesting level, like the navigation block currently behaves. #22998

### Discussions
Discussions are general topics where we're less clear so we cannot start a PR to explore or implement.

- [x] Rename Block Navigation (AKA Block Navigator) #22814
- [x] Persistent block navigator panel #22113
- [x] Synchronizing selection between navigator and navigation #22705
- [x] Navigator iterations: ellipsis and movers #22089
- [x] ~Update the Navigation screen’s implementation to be a Block Editor instance and study what design implications this has.~

## Navigation block

The Navigation block has its own Overview issue (#22930), so this list is made if things that move the navigation screen forward in terms of UX, but most of the things here will also affect how the Navigator block works in other Gutenberg contexts (e.g. the post editor).

### Action items
Action items are things that need a PR for implementation or exploration.

- [ ] ~We need to add to drag and drop from the block itself (not the toolbar), at least in "selection" mode.~
- [ ] ~We should try to list the currently set link on the block toolbar for extra clarity #23023~
- [x] Move automatically add top-level pages to ellipsis or somewhere else on the admin screen for navigation #22749
- [x] Add a way to toggle the Navigation block between horizontal and vertical layouts (done via variation selector in the inspector)
- [x] We need to remove all the toolbar buttons of the Navigation block, including the styles selector, and keep the ellipsis.
- [x] We should find a way to display the inspector options in the new navigation screen for the blocks we select, especially if we’ll be allowing other kinds of blocks to be added to the Navigation block.

**Comment by ellatrix** [comment]
Thanks for the overview issue. What is left for 5.5?

**Comment by draganescu** [comment]
A lot! We're still missing a few key components: drag and drop in the block and in the sidebar, a couple of PRs that lag and are important for feature parity (#22600, #22697) and the ongoing work to support more block types in Navigation.

I believe we're in a place where a Gutenberg release after 5.5 will include this new screen, but maybe in the next two weeks some acceleration will occur and prove me wrong.

It is good that it's in "undecided" for now.

In any case I believe that it is wiser that this lands as a part of the plugin 1st, gets some feedback and then is shipped into core.

**Comment by TimothyBJacobs** [comment]
@draganescu would the batch controller only be used by this screen? Or is it also needed for the nav block?

**Comment by draganescu** [comment]
> would the batch controller only be used by this screen? Or is it also needed for the nav block?

👋 The batch/bulk operations are useful for the navigation screen. For now the navigation block only reads from the list of menus and the list of menu items, writes nothing back.

**Comment by TimothyBJacobs** [comment]
Thanks for clarifying @draganescu! I'm going to bump the batch controller out of the 5.5 milestone then.

**Comment by draganescu** [comment]
This overview issue is obsolete.

**Comment by annezazu** [comment]
What's the best place to follow along at this point instead @draganescu :) Want to be sure I have the right links.

**Comment by draganescu** [comment]
I am making an overview issue fot the Navigation screen which will be up to date with the evolution of that project,
