### ISSUE TITLE
Image editing

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#23350]
This is an issue to track what's left to do for image editing.

- [x] ~There's an issue with server side cropping once the image has been edited several times. Needs investigation.~ Seems to be fixed with #23374.
- [ ] Move zoom slider to toolbar. #22569 Cc @ItsJonQ @diegohaz
- [x] Remove other buttons in the toolbar when editing the image. #23707
- [x] Ensure errors reported from the API are communicated to the user. #23536
- [x] Clean up the _experimental_ REST API endpoint.
- [x] Are edits applied to original image? #23440
- [x] Is the edited file name good? #23440
- [x] Test on mobile devices.

Nice to have.

- [ ] Flipping.
- [ ] Animations. #22566.
- [ ] Allow editing of external images.
- [ ] Maybe add processing messages. #22573

**Comment by ellatrix** [comment]
@jasmussen @MichaelArestad Would love your thoughts and further help regarding the design, maybe in particular the zoom controls.

**Comment by jasmussen** [comment]
Some good feedback from https://github.com/WordPress/gutenberg/pull/23284#issuecomment-646596370 worth reading for context. Many are already action items here.

**Comment by ellatrix** [comment]
@jasmussen  I think I've moved those action items here :)

**Comment by TimothyBJacobs** [comment]
We're going to need phpunit tests on the endpoint as well.

**Comment by TimothyBJacobs** [comment]
Opened a PR for the REST endpoint, #23368.

**Comment by MichaelArestad** [comment]
I must be missing something. I loaded up master to test, but this is what I'm seeing:
![image](https://user-images.githubusercontent.com/1123119/85330066-ea744480-b490-11ea-826a-64fbb7b92659.png)

I don't see the tools shown in some of the [gifs](https://github.com/WordPress/gutenberg/pull/23284#issuecomment-646733447) from #23284. I also see  "Crop" instead of the crop icon. Is there another branch I should be testing on?

I'm also noticing sometimes the caption toolbar is open when the zoom is open:
![image](https://user-images.githubusercontent.com/1123119/85330050-e3e5cd00-b490-11ea-94dc-7684fd4fe153.png)

**Comment by jasmussen** [comment]
Some things had to change so as to apply a single operation on apply, rather than immediately after each. Some of that is tracked in https://github.com/WordPress/gutenberg/issues/23350, and I'll be taking a stab today.

**Comment by jasmussen** [comment]
Was not an action item on this list, but was on feedback in https://github.com/WordPress/gutenberg/pull/23284#issuecomment-646596370. #23387 changes the "Edit" button to be the crop icon. It becomes a bit of an umbrella button for even the rotate image feature, but at least it's one click.

On that note, in order to truly address this item:

> Remove other buttons in the toolbar when editing the image.

we really need a classname on the image toolbar to specifically target with some handy `display: none;`s. Ideally instead of this:

<img width="407" alt="Screenshot 2020-06-23 at 12 48 11" src="https://user-images.githubusercontent.com/1204802/85395045-d8a5a680-b54f-11ea-8d7a-5410cf9d9afa.png">

It should look like this:

<img width="280" alt="Screenshot 2020-06-23 at 12 49 32" src="https://user-images.githubusercontent.com/1204802/85395166-012da080-b550-11ea-917b-3c4be2b7f111.png">

It would be trivial if we could specifically target the cropping "mode" of the toolbar, and it would really clean up the flow.

**Comment by jasmussen** [comment]
In #23418, I did a bunch of cleanup with the zoom slider. I still think we should move it to the block toolbar, but in case that's an onerous effort, this can potentially serve as a holdover.

**Comment by mtias** [comment]
I think we can close this as the separate issues stand on their own.
