### ISSUE TITLE
Block Directory

### ISSUE THREAD

**Issue by tellyworth** [WordPress/gutenberg#23378]
### Context

The Block Directory front-end code has been hidden behind an Experimental flag for some time, since #17431.

This is a tracking issue covering the remaining front-end tasks needed to remove the experimental flag and launch the Block Directory feature in core. This supersedes the old follow-up work issue (#17440).

### Required to launch:

- [x] Remove the experimental flag and namespace (#23384)
- [x] Use plugin API for install &amp; delete (#23219)
- [x] Padding and layout fixes (#23346)
- [x] Add plugins endpoints (#22454)
- [x] Image icon bug (#19264)
- [x] Search blocks when plugin deactivated (#19906)
- [x] Missing padding in inserter (#21746)
- [x] Layout improvement (#21963)
- [x] Better UX when installation fails (#23439)
- [x] Fix regression with searching for deactivated blocks (#23570)

### Directly related to the block directory, but not a blocker for launch:</h3>

- [x] Aggressive script tag replacement (#23158)
- [ ] Provide a way to identify the source of a block (#16521)
- [x] Iterate the Block directory search results (#22149)
- [x] Uninstall unused blocks on save (#22307)
- [x] Inline inserter search bug (#23148)

### Indirectly related, but not required for launch:

- [x] Block creation documentation (tracking issue #22151)
- [ ] Improvements to Block Manager (#15121)
- [ ] Extend the block registration API (block.json #16209)
- [ ] Block collections (#19873)
- [x] Allow dependencies on other script handles (#22703)

**Comment by annezazu** [comment]
Doing some clean up and closing this out as it seems most initiatives have been handled and active work hasn't continued in a few years. If this is incorrect, happy to reopen!
