### ISSUE TITLE
Widgets: Follow-up work from refactoring Widgets screen to use sidebars endpoint

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24530]
This issue tracks necessary follow-up work from merging https://github.com/WordPress/gutenberg/pull/24290.

Has PR:

- [x] Previewing an old-style widget in the Block Areas screen results in "Block rendered as empty." #24861 
- [x] Risk of having invalid markup in widgets screen #24866 #24899
- [x] Block Areas screen needs a loading state when you open a widget area. #24855
  - [x] Similarly, Legacy Widget blocks need a loading state. #24855
- [x] Add PHP unit tests for when user is logged out or has insufficient permissions #24784
- [x] Add PHP unit test for slashing behaviour #24785
- [x] 'Gutenberg block' shows up in Legacy Widget dropdown #24787 
- [x] Need to indicate progress when the Block Area screen's Update button is clicked. #24788
- [x] What causes empty spaces in rendered content? #24789
- [x] There's an empty widget area at the top of the Block Areas screen which has no title. Probably it's the inactive widget area. #24790
- [x] Widgets added to the inactive widget area in the Widgets screen don't appear at all in Block Areas screen. #24790
- [x] If you duplicate a Legacy Widget block and then make edits to the duplicate, those changes are saved to both the original and the duplicate widget. #24817
- [x] Do we need a save button on Legacy Widget blocks? #24792
- [x] Unnecessary enqueuing of assets in widgets screen #24793 
  - [x] "Target container is not a DOM element" when loading old Widgets screen 
#24793 

Lower priority:

- [ ] Why do we need to have a post id and use useEntityBlockEditor? https://github.com/WordPress/gutenberg/pull/24290#discussion_r468744412
- [ ] Add unit tests for all of the exported functions in `packages/edit-widgets/store`. https://github.com/WordPress/gutenberg/pull/24290#pullrequestreview-464691675

Discussion in progress:
- [x] Could/should we use HTML widgets instead of a dedicated Gutenberg Block widget? https://github.com/WordPress/gutenberg/pull/24290#issuecomment-671707216
- [ ] Protect from XSS by testing e.g. the text widget for input like `'text' => '<script>alert(1)</script>'` (#24863)

Don't do now:

- [ ] Later, add E2E tests for the screen. Especially for tricky things such as old-style widgets. https://github.com/WordPress/gutenberg/pull/24290#pullrequestreview-464691675 **The design is evolving so any E2E tests we prepare now will likely not apply in the nearest future**.

**Comment by adamziel** [comment]
> Any thoughts on having a new Gutenberg Block widget vs. using the existing HTML widget?

How would that work @noisysocks? HTML widget is good for storing HTML, but we also want to be able to edit these blocks as, well, blocks. Also I think it would break interoperability with the old widgets screen since the custom HTML widget would only render raw contents only, e.g. `<!-- wp:latest-posts /-->`, instead of a block. To make it 1:1 replacement of the block, we would need some custom logic to make sure that Custom HTML widget is treated as Custom HTML widgets in certain contexts, and as a block widget in different contexts. It sounds much more complex than just having a separate widget for that.

**Comment by noisysocks** [comment]
Yep, good points. I think `block` is the way to go. It matches what I ended up doing for menu items in https://github.com/WordPress/gutenberg/pull/24503, too.

**Comment by adamziel** [comment]
> Previewing an old-style widget in the Block Areas screen results in "Block rendered as empty."

I am unable to reproduce that @noisysocks, would you mind providing step-by-step instructions or a gif?

**Comment by noisysocks** [comment]
> > Previewing an old-style widget in the Block Areas screen results in "Block rendered as empty."
> 
> I am unable to reproduce that @noisysocks, would you mind providing step-by-step instructions or a gif?

1. Register a widget that doesn't use `WP_Widget`. Here's some plugin code which will do just that:

```php
function marquee_greeting_init() {
	wp_register_sidebar_widget(
		'marquee_greeting',
		'Marquee Greeting',
		function() {
			$greeting = get_option( 'marquee_greeting', 'Hello!' );
			printf( '<marquee>%s</marquee>', esc_html( $greeting ) );
		}
	);

	wp_register_widget_control(
		'marquee_greeting',
		'Marquee Greeting',
		function() {
			if ( isset( $_POST['marquee-greeting'] ) ) {
				update_option(
					'marquee_greeting',
					sanitize_text_field( $_POST['marquee-greeting'] )
				);
			}

			$greeting = get_option( 'marquee_greeting' );
			?>
			<p>
				<label for="marquee-greeting">Greeting:</label>
				<input
					id="marquee-greeting"
					class="widefat"
					name="marquee-greeting"
					type="text"
					value="<?= esc_attr( $greeting ) ?>"
					placeholder="Hello!"
				/>
			</p>
			<?php
		}
	);
}
add_action( 'init', 'marquee_greeting_init' );
```

2. Navigate to the new block-based widgets screen.

3. Add a _Legacy Widget_ block to one of the block areas.

4. Select the widget registered in step 1 from the dropdown. (_Marquee Greeting_, if you used my code sample.)

5. Click _Preview_ in the block toolbar.

![preview-error](https://user-images.githubusercontent.com/612155/91372867-2d1f1800-e858-11ea-83b5-02d6df4c8b88.gif)

**Comment by adamziel** [comment]
Thank you @noisysocks, I think I got confused with all the wording (beta widgets screen, legacy widgets screen, legacy widgets, legacy not-so-legacy widgets, block widgets), definitely a case something we could solve with a ubiquitous language. Maybe.. function-based legacy widgets, class-based legacy widgets, block-based widgets?

**Comment by draganescu** [comment]
@adamziel  @draganescu maybe create separate issues and let's close this giant one.
