### ISSUE TITLE
Site Editor Navigation: Tracking

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#24552]
Groups the work related to navigating between pages, templates, parts, and the interface work around communicating what area is active, what entity is loaded, and so on.

- [x] Group document settings in the header. #20877
- [x] Indicate current template and template part when in site editor. https://github.com/WordPress/gutenberg/issues/22064
- [x] Move templates and page navigation into the main W sidebar. #23939
- [x] Allow browsing all templates and parts. #21246
- [x] Implement "Add Template" flow. https://github.com/WordPress/gutenberg/issues/26270
- [x] Rename W menu components. #25616
- [x] Indicate customized templates. https://github.com/WordPress/gutenberg/issues/26451 (Closed)

### Explorations

- [ ] Browsing mode / preview mode. #23328

**Comment by vindl** [comment]
Closing this since all of the main tasks from the above list have been completed. For smaller follow-up tasks we can open up separate issues.

**Comment by mtias** [comment]
Thanks!
