### ISSUE TITLE
Widgets Editor Tracking Issue

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#24687]
Last updated June 23, 2021

Extends #24551, preliminary for milestone 7
This is an overview issue that we'll maintain going forward into the  5.8 milestone. It attempts to track discussions and resulting actions about the Widgets Editor.

This overview tries not to track bugs of the Widgets Editor, for that you should filter open issues using the labels [Feature] Widgets Screen and [Type]Bug.

#### Widgets Screen
- [x] Unable to add widgets after Opting out of the Widgets Block Editor in WordPress 5.8-Beta2 Core-53479 
- [x] `wp.editor.initialize` is not a function notice Core-53437
This bug prevents legacy widgets such as Text from working which is a blocker. **Has a (hacky) patch**.
- [x] remove_theme_support doesn’t restore back to classic widgets editor Core-53424 
This bug prevents themes from opting out of the block editor which is a blocker. **Has a patch**.
- [x] Widget preivew not working if widget registered via a instance Core-53427
This bug prevents widgets in LegacyWidget block to render properly. **Has patch from @spacedmonkey**. 
- [x] Blocks that use entities are not saved in the widget editors #32756 
This bug prevents FSE blocks from working properly.

#### Backwards compatibility 

- [x] Bundled Themes: Minor styling issues with blocks in widget areas Core-53422 Some of our bundled themes don’t play nicely with the default blocks that you see in a new WordPress install. **Needs an assignee**.

#### Widget screen
- [x] Latest Posts and Latest Comments blocks don’t look great when editor styles are disabled #32718 
This bug means that two of the default blocks you see in a new WordPress install look broken in the widgets screen and customizer. **Needs an assignee**.
- [x] Add editor styles to the widgets block editor Core-53344 
This is an alternative to the above. It’s more work and so perhaps not feasible for 5.8 but provides quite a nice UX as it makes widgets more WYSIWYG. **@tellthemachines is looking into it.**

### Widgets in Customizer

The widgets editor in the Customizer should have a smooth user experience and be enabled by default.

- [x] Implement undo/redo #30400
- [x] Some legacy widgets don't fit in the customizer block editor #31194
- [x] Design exploration. #26900
- [x] Use temporary fix to make blocks appear in the Customizer #29283
  - [x] Make the block editor talk to the Customizer API #29284
  - [x] Implement slide-out inserter https://github.com/WordPress/gutenberg/issues/29285
  - [x] Implement block inspector panel ~~#29286~~ #30271 #30431
- [x] Ensure compatibility with customizer hooks and filters #25417
- [x] Update Customizer to use Legacy Widget block instead of outputting JSON #30265
- [x] Add some basic e2e tests #30269 
- [x] Remove temporary `__unstable_instance` hack #30266

### Legacy Widget

- [x] Add support for widgets with attributes that can't be serialised into JSON #28902
- [x] Remove deprecated properties #30267
- [x] Some widgets don't load all the scripts they need #22765
- [x] Unable to save edits to existing widgets #27747
- [x] Improved interaction with legacy widgets #26179 #28671 #25960
- [x] Enable conversion and transforms to blocks #25100 #30919
- [x] General stability #26236 #26469 #28672 #28995 #26474

### Feature parity with the classic widgets screen

- [x] Provide ability to Clear Inactive Widgets #26232 #28267
- [x] Adding widgets to widget areas
- [x] Customizing widgets
- [x] Move widgets between widget areas #27409 #24328
- [x] Shortcode block not working in Widgets screen #27793
- [x] Provide 'Manage with Live Preview' #26244

### Widgets editor 

- [x] We need a backward compatibility audit #28673
- [x] Content added in blocks are removed if you deactivate Gutenberg #26217
- [x] General parity #26245 #25945
- [ ] Fallbacks and Default widgets #26298
- [x] Problems keyboarding through the areas #25880 #25877 #28267
- [x] Mirror block editing experience #26297 #26230 #26177 #28123 #27564
- [ ] Custom block styles are not available #25808
- [ ] Improve widget discovery and recognition #25959 #26222
- [ ] Render widgets in the editor with the same style as in the theme #26163 #26181
- [ ] Allow inserting block patterns #26170
- [ ] General stability  #25406 #26153 #26072 #26152 #26156 #26261
- [x] Hello Dolly plugin causes screen breakage #26219 🏆 

### Block support in widget areas

- [x] Previewing blocks and widget areas #26468
- [ ] General stability #26073 #26221 #26240 #26465 #25910
- [ ] Provide an API to prevent certain blocks being shown in Widget Areas #28517
- [x] Adding blocks to widget areas

### REST API

- [ ] General stability #26303 #28561 #25982 #26252 #26186
- [ ] Test sidebars API based on capabilities, not roles #24902
- [ ] Modify `__experimentalBatch` to respect batch size limit #28709
- [x] Use `sidebars` REST API endpoint. #24530

**Comment by draganescu** [comment]
Updated to reflect the new focus on Backwards compatibility and extensibility.

**Comment by draganescu** [comment]
Updated by @noisysocks to reflect priorities for a good merge candidate for WP 5.8.

**Comment by draganescu** [comment]
I have updated this issue with new info (props @noisysocks) about blockers as we head into the code freeze for WP 5.8 RC 1.

**Comment by spacedmonkey** [comment]
@noisysocks @draganescu Flagging https://github.com/WordPress/gutenberg/pull/32781 and https://core.trac.wordpress.org/ticket/53441

**Comment by draganescu** [comment]
Hey! It's WordPress 5.8 RC2! Can you believe this? WIdgets are going to live nicely along with blocks thanks to the feature this issue tracked for so long!

Thanks everyone for the great work. 🎉 🙏🏻  

Closing this as it has run its course. Let's track #33242 instead and make things even better!
