### ISSUE TITLE
Navigation editor: a brief bug list

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#24760]
### Low key review of the navigation editor

I have ran through the current state of the Navigation editor in the master branch of Gutenberg and these are the bugs I found:

- [x] List view: [clicking the "Go to block"](https://user-images.githubusercontent.com/107534/91038279-2d7aa180-e613-11ea-99be-eaf50027e9dd.gif) does reveal the nested selection in the Navigation block, but it does not put focus into that block https://github.com/WordPress/gutenberg/issues/24806
- [x] List view: we should remove [the "Move to" button](https://user-images.githubusercontent.com/107534/91038278-2ce20b00-e613-11ea-85ac-c78ea98a0a6c.png) or add functionality to it https://github.com/WordPress/gutenberg/issues/24807
- [x] List view: we still miss drag and drop (PR - #23952)
- [x] Navigation block: we still miss drag and drop (PR - #24708)
- [x] Navigation block: clicking on an open sub-menu should probably close it back, alternatively closing "outside" the sub-menu should close it https://github.com/WordPress/gutenberg/issues/22626
- [x] Navigation block: t[he transparent sub-menus](https://user-images.githubusercontent.com/107534/91038274-2c497480-e613-11ea-8bc2-08aeeea9639a.png) make editing impossible (PR - #24763)
- [x] Inspector: the changes to Link properties in the inspector after saving navigation, [are lost on page refresh](https://user-images.githubusercontent.com/107534/91038270-2b184780-e613-11ea-8052-6d625e3ee919.gif) https://github.com/WordPress/gutenberg/issues/23731
- [x] Inspector: [clicking on the accordion headings](https://user-images.githubusercontent.com/107534/91038249-25226680-e613-11ea-818c-85776b6b1558.gif) and then in fields [closes the inspector](https://user-images.githubusercontent.com/107534/91038265-29e71a80-e613-11ea-9e44-7b2081bbf717.gif) https://github.com/WordPress/gutenberg/issues/24809
- [x] UI: the save button's text is [not centred properly](https://user-images.githubusercontent.com/107534/91038268-2a7fb100-e613-11ea-80bc-f607bc4e3702.png) https://github.com/WordPress/gutenberg/issues/24810

**Comment by noisysocks** [comment]
@talldan linked a few items to existing PRs and I created issues for the remaining items.

**Comment by draganescu** [comment]
All the issues have been fixed 🥳
