### ISSUE TITLE
Query and Loop Block: Tracking

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#24762]
An initial implementation of the Query and Loop blocks is in place. It's missing some next steps around customizing the query, sidebar controls, and particularly pattern integration for editing and handling different displays of post lists.

### High

- [x] Address missing query functionality. https://github.com/WordPress/gutenberg/issues/24934
  - [x] `post_type`
  - [x] `page`
  - [x] `search`
  - [x] `order`
  - [x] `per_page`
  - [x] `tags`
  - [x]  `offset`
  - [x]  `author`
  - [x] `sticky`
- [x] Template logic: inherit query from template context
    -  [x] Loop: #27128
    -  [x] Query Pagination: https://github.com/WordPress/gutenberg/pull/28125
- [x] Reflect _reading_ settings when the query block inherits query context. #20338
- [x] Expose initial templates as variations. #26194

### Normal

- [ ] Add some patterns.
- [x] Add Custom Post Types support. #25903 
- [ ] Enhance the initialisation of Query. After selecting 'layout'(ex title + excerpt) variation in Placeholder have a second step for easy setting of attributes. https://github.com/WordPress/gutenberg/issues/27031
- [ ] Transform Query in other block variations after creation (this will be handled in a generic way though):
  - [x] Step 1 - issue: #25231, PR: #26687
  - [ ] Step 2 - issue: https://github.com/WordPress/gutenberg/issues/26962
- [ ] Isolated template editing for the Loop. #26190
- [x] Start a new post from the block. #27732
- [x] Add next and prev page links to Query Pagination block. https://github.com/WordPress/gutenberg/pull/28125
- [ ] Allow customizing the no-results behavior of the Query block. #27302

### Needs Decision
- [ ] Explore combining Query and Loop: the current setup is confusing to work with. - There are `InnerBlocks` limitations and needs more explorations. Maybe the Query should absorb the Loop's Toolbar.

**Comment by ntsekouras** [comment]
> Address missing query functionality. (Expand...)

This might be the proper place to discuss some design decisions about the contents of `toolbar` and `sidebar`.

Related PR: https://github.com/WordPress/gutenberg/pull/24691, that adds some order support in the `Query` block.

**Comment by ockham** [comment]
FYI @david-szabo97

**Comment by gziolo** [comment]
@mtias, should we include more items on the todo list, some of references to consider:
- Add an Query Title block (the default title for pages like "Month: April 2020" or "Category: WordPress") - #22724
- Add next and prev page links: WordPress/gutenberg#26557

**Comment by mtias** [comment]
@gziolo definitely, feel free to add them

**Comment by gziolo** [comment]
I included both of them with priority Normal. In addition, I added to the list the following item:
- Allow customizing the no-results behavior of the Query block. #27302

@aristath created it based on his explorations of Drupal's Views module summarized in #25790.

**Comment by mtias** [comment]
@gziolo two things, though: "Query Title" is just "Page Title" and not tied to the query but tied to the template resolver. I think it should be added to the Milestone:4 Theme Blocks — #22724 instead

**Comment by gziolo** [comment]
> @gziolo two things, though: "Query Title" is just "Page Title" and not tied to the query but tied to the template resolver. I think it should be added to the Milestone:4 Theme Blocks — #22724 instead

That's a good point, I will move.

It triggers two questions 
- whether we should have Page Loop and Page Navigation blocks listed in the inserter
- whether Page Title block is separate from Post (type) Title

I'm personally still having harder time visualizing how it would work best for users.

**Comment by ntsekouras** [comment]
>@gziolo two things, though: "Query Title" is just "Page Title" and not tied to the query but tied to the template resolver. I think it should be added to the Milestone:4 Theme Blocks — #22724 instead

I also think that Title could be left separate and be handled with `PostTitle` block and later implement a `TermTitle` block.

**Comment by mtias** [comment]
The initial set of high priority items is done. I think we can close this issue and keep track of further individual items separately for clarity until a full iteration again emerges.
