### ISSUE TITLE
Site Editing Infrastructure and UI: Part 2

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#24818]
The #20791 served as the initial issue to track the initial work to build the Site Editing Infrastructure. That milestone is complete but there are still some pending tasks related to the infrastructure and the current issue is used to track those.

### High
- [x] Incorporate template area in document header: #25085 #20877
- [x] Browse templates and template parts in sidebar (navigation pattern) #23939 (**Has its own milestone in #24552**)
- [x] Template Parts with HTML tags: #20997
- [x] Define template part interactions. #25452 
- [x] Add convert to template part flow. #20445
- [x] Introduce semantic templates parts and distinguish them in block tree. #27337 #26599
  - [x] Template part toolbars and switching. #27397
  - [x] Define header, footer, and sidebar terms #28410
  - [x] Register variations of template parts for easier control flow and hide the variations in the inserter. #29122
  - [x] Apply specific icons to those variations. Color template parts and selection state in the block tree and icon in block description. #27876
  - [x] Ensure we list these template parts more prominently in the W sidebar. #27877
  - [x] Include specific descriptions in the sidebar inspector and "current template dropdown" for header, footer, sidebar to give context. Allow switching a template part context from the inspector. #27875
  - [x] Figure out how to connect template part terms with specific block pattern categories. #27575 
- [x] Remove templates and template parts syncing (or not). #27321
- [x] Add focus / hover indications on the canvas when traversing block list view. #27395
- [x] Explore zooming-out to the template level. #26355 
- [x] Simplify template part toolbar and align with reusable blocks #28659 
- [x] Reusable blocks and Template parts – try a click-through-to-edit-children UX pattern #29337

### Normal
- [ ] Support dynamic values in block-based templates. #20966 #25316
- [ ] Add a Grid block and use it as a starting point for blank templates #16998 
- [ ] UI to create variations of existing templates #19259 #20474
- [x] Add a "Revert to default" option for templates and template parts #23421 
- [ ] Mosaic View of Theme Templates. #20477
- [ ] Audit template resolution and rendering performance.
- [ ] Audit loading performance of the site editor and improve the "preloaded REST API" list.

**Comment by youknowriad** [comment]
I just added a new top priority item here about the potential removal of the templates and template parts syncing https://github.com/WordPress/gutenberg/issues/27321

**Comment by mtias** [comment]
Also included #26599 as a task.

**Comment by youknowriad** [comment]
We just landed the template mode for the post editor #26355
This highlighted some required refactorings and follow-ups that I'll be working on. (Refactoring EntitiesSavedState, Refactoring the editor provider, Support for showing outlines in the template mode)

**Comment by mtias** [comment]
Broke down the tasks for "semantic template parts" a little further.

**Comment by youknowriad** [comment]
We landed the removal of the template syncing behavior in #27910

**Comment by priethor** [comment]
Added #29337 to the list.

**Comment by Copons** [comment]
A bit late, but we closed #27395 by merging #28637 and several follow ups, which made the List View persistent in the Site Editor, pending user testing to determine if it's worthy to be moved to the Post Editor as well.

**Comment by mtias** [comment]
Mentioning that List View was turned into its own smaller project at https://github.com/WordPress/gutenberg/issues/29736

**Comment by Addison-Stavlo** [comment]
The semantic template parts bullets here seem complete now.  Checking off the remaining item:

> Figure out how to connect template part terms with specific block pattern categories.

As this is now being done with the `blockTypes` array in pattern registration.

**Comment by mtias** [comment]
With #29337 closed all the main work is completed. There's still the question of dynamic values that is yet to be answered in a satisfactory way.

**Comment by mtias** [comment]
Marking this milestone as completed, will write a followup with some of the lower priority tasks and some new that have since surfaced.
