### ISSUE TITLE
Navigation Screen: MVP Designs

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#24875]
The current Navigation experiment (which aims to replace Core's Menu screen) looks something like this:

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/191598/91491018-691aa300-e881-11ea-9fd7-96b8e20b62e1.png">

Its an obvious work-in-progress. While it contains a good amount of the functionality required to replace the older Menu screen, its lacking in design.

My first instinct was to suggest we make use of the `Interface` package which would give access to the top bar and sidebar components, which are also used in the Block Editor, the Site Editor, and the experimental Widgets Editor. It could look something like this:

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/191598/91491935-ccf19b80-e882-11ea-8431-7fc793811941.png">

It seems like this might not be the best solution. Instead I've tried to work with the existing experiment to see what I could do to get it ready for prime time. I tried my best to clean up the layout, hierarchy, and (hopefully) improve the overall usability. 

Here's where I've ended up:

![navigation-mvp](https://user-images.githubusercontent.com/191598/91492538-d4fe0b00-e883-11ea-89a0-e5ea8e8a5896.gif)

--

There's a lot in the GIF. Here's a breakdown:

- [ ] The "auto-add" pages option and the menu location settings for the menu have been moved into the Navigation block's settings (Issues #25010 #25011).
- [ ] Add the current menu's name to the top of List view (Issue #25233)
- [ ] When the Navigation block is selected, hovering over a menu item with children should display those children in a dropdown. Selecting a menu item with children will force the display of those children. If a block _other then_ the Navigation block is selected, hovering should have no affect on the display of children (Issue #25012).
- [ ] Theme locations have been moved into a popover containing the list of locations, each with a `select` to choose a menu. This could be problematic if themes offer more than a handful of locations. We could scroll the popover as needed, or simply keep the separate screen (Issue #25011).
- [ ] When the Navigation block is selected it's toolbar displays the name of the menu. Pressing on this name enables you to edit it (Issue #24581).
- [ ] I've updated the Navigation block's description to "A collection of blocks that allow visitors to get around your site." (Issue #25013)
- [ ] Creating a new menu flows more like the Core Menu's experience; A new Navigation block toolbar is displayed, with focus put on the menu name input. The rest of the UI is disabled until the menu is named and the button is pressed (Issue #25014)
- [ ] The Navigation block placeholder takes a cue from #23207. (Issue #25015)
- [ ] Other than the Link block, the Navigation screen should support the Page Listing block (outlined in #23689), variants of the Link block for Categories and Tags (#24670), the Search block (Issue #24643), and the Social Links block (Issue #25016).
- [ ] The List View incorporates the new designs from #24029.
- [ ] I've incorporated the new Link UI designs from #23375.

There's a [clickable Figma prototype](https://www.figma.com/proto/XAWfp6Rrh7fKqB8kwUrbKQ/Navigation-Screen?node-id=429%3A27&viewport=1606%2C6848%2C1&scaling=min-zoom) if you'd like to see full-size designs and experience the flow for yourself.

**Comment by mapk** [comment]
@shaunandrews thanks for sharing the prototype. My initial click-through went something like this... I see 3 different modules that include buttons/text/dividers/icons, but because of the gaps in between each of the modules, they feel disconnected… until I click on something... then visual changes appear everywhere. This was a bit difficult to process how each related and what was happening.

For example:

![everything-happened](https://user-images.githubusercontent.com/617986/91496861-bdb62200-e871-11ea-9236-21e611c4889f.gif)


**Feedback**
- They feel disconnected without the Editor to unify them all together. 
- When editing the menu, I'm a little unclear. Should I be editing in the left module (list view) or in the right one (block)?
- The icon in the topbar is unnecessary. Is it a block icon? Am I editing a block in this screen? I can't tell. It appears clicking that is the same as just clicking the Menu name. 
- There's a lot of popovers that sprout up. In addition to the visually disconnected boxes below them, it's really busy.
- That top bar, because of its positioning on the page, doesn't look like a block toolbar, nor does it look like the Gutenberg topbar. It took me a bit of time to figure out how it was related to the menu below.
- Is the "theme locations" in the settings popover the same as the Manage Locations option at the top of the page? They seem very similar.
- I'm seeing a lot of redundancy throughout. 

I know this screen is a difficult one. It's been lingering around for a long time, so thank you for taking it on! I'm just noting that a lot of these issues could probably be solved by bringing in the Interface package as you mentioned above. It ties everything together in a way that makes sense. My vote would be for that direction. :) It would also align really well with the Widget Editor.

**Comment by afercia** [comment]
Glad to see a visible H1 heading as first thing in the main content, as also asked on #24937. Is there a similar design also for the Widgets page already?

**Comment by paaljoachim** [comment]
Hey @afercia 

Check out this comment by @mapk 
https://github.com/WordPress/gutenberg/issues/24561#issuecomment-681167207
There is a comment and a mockup that includes the Widget page title.

**Comment by draganescu** [comment]
One thing here @shaunandrews: I am not sure the SitePages block makes sense in the Navigation editor as this works all right with the auto add pages functionality and we can also create from pages. This block is a good feature in the context of using the block in the post and site editors where we save the navigation using block storage and so we cannot simply implement the auto add.

I suggest we remove this requirement from the tasks above 😆

**Comment by shaunandrews** [comment]
> I am not sure the SitePages block makes sense in the Navigation editor as this works all right with the auto add pages functionality and we can also create from pages. This block is a good feature in the context of using the block in the post and site editors where we save the navigation using block storage and so we cannot simply implement the auto add

The existing "auto add" checkbox only adds top-level pages; The Page List block is designed to show hierarchy with an option to display literally all pages.

I do think a Page List block would be helpful in the Navigation screen, but its probably not a requirement.

**Comment by talldan** [comment]
@shaunandrews Is there a way to add a label to the 'Change Menu' `select` element? I realize this changes the flow of the design, but preferably there would be a visible label for form fields.

What were you thoughts on how things might look on mobile? This isn't too different to the layout of the current design, so it may be fairly similar.

**Comment by shaunandrews** [comment]
> add a label to the 'Change Menu' select element

We could probably do something like this:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/191598/92165616-5239fa80-ee05-11ea-8047-5b803cab40ba.png">

**Comment by manmotive** [comment]
Can the menu select box also include the names of any locations the menu has been tagged to? As in the current nav-menus.php screen:

<img width="796" alt="menunames" src="https://user-images.githubusercontent.com/63796393/92227145-c0320080-ee9d-11ea-9ce2-a05b851ef936.png">

**Comment by paaljoachim** [comment]
A new test design.. inspired by Shauns designs (took some of the screens), the new Widget screen, the current Navigation screen and the beta Navigation screen.

This is a mix of the current navigation. 
I added the inserter panel,
list view, 
menu title drop down so the user can jump to another menu
and Nav settings.

It would be helpful to use existing methods so the user can understand what each are for in a simple way because he/she has already used most of them in Gutenberg. The title drop down is likely something that will be added in some form or another in relation to Full Site Editing.

This is a sketch to show a possible flow of elements.

I made a wireframe in Figma located here:
https://www.figma.com/file/8it5sK19F8jbmpefHglFx0/New-Nav-screen-exploration?node-id=0%3A1

Here is an animated gif.
![Nav-flow-test](https://user-images.githubusercontent.com/5323259/92304658-37d85c00-ef80-11ea-8c68-3e205ae0122e.gif)

The purpose is to inspire.

**Comment by afercia** [comment]
> The thing that stands out is that the Block Inspector is after Save. Would it be better to switch those in terms of usability?

Thanks for pointing out this @talldan. Yep, the accessibility team asked for having the Save button as last thing in the tab order in the block editor as well, no luck so far 🙂 The thing is that for accessibility, the DOM order and the visual order must match so I do realize that visual design needs and accessibility needs clash here.

The Save button at the end is expected by users who navigate or perceive the content in a linearized fashion. For example, keyboard users or screen reader users navigate the content sequentially, at least at the beginning when they are learning the interface. Screen reader users, once they learned the UI, have lots of tools to jump to parts of the UI, as long as there's a good headings structure, ARIA landmarks, etc. Regardless, it's basically a linearized experience as there's no concept of "layout".

A Save button in the middle of the UI would be more or less equivalent to placing a Submit button in the middle of a long form 🙂 

We also considered to have _two_ visible Save buttons, with the second one placed as last thing in the relevant UI. No luck, and I do realize two buttons would be visually problematic, although not unprecedented in WordPress. One thing we didn't consider so far is to have a second Save button _that gets only revealed on focus_. This could serve well all keyboard users (including screen reader users) and still keep the UI "clean". Will ask the accessibility team for their thoughts.

**Comment by noisysocks** [comment]
A had a go at implementing the broad strokes of this in https://github.com/WordPress/gutenberg/pull/25178.

**Comment by shaunandrews** [comment]
Based on some of the feedback above, I've updated the design and have been working with @noisysocks's PR #25178 to explore these ideas:

![nav-screen-i1](https://user-images.githubusercontent.com/191598/92805364-0cda7780-f387-11ea-976e-3b4f81493a67.gif)

**Comment by mapk** [comment]
This feels so much more cohesive!

**Comment by paaljoachim** [comment]
There is a stronger cohesive with Gutenberg methods. 
This looks really interesting.

Is there a prototype we can test out Shaun? As I would be able to test it out in my own pace.

I see the toolbar and also settings change depending on what is selected. 
There might be some discoverability issues as one will first need to click something to have the options seen, but on the other hand one sees the options needed with a current selected item.

I am wondering if we should have the Navigation structure icon to the right just left of the Save button.... perhaps something similar to this. I also experimented with moving the settings to the right as well.
![Nav-structure-to-right](https://user-images.githubusercontent.com/5323259/92900875-57f49900-f420-11ea-9af7-ba308ae2cd2d.jpg)


Purpose: To have the Nav structure open at the same time as one is working on the menu. As one can see adjustments done in one place reflected in the other. The purpose with moving the settings to the right is so that it does not cover the menu below. As one might be editing a menu item and opening the settings panel might cover the item being worked on.

I am hesitant in moving Nav structure icon and the Settings icon to the right as they were nicely grouped in the toolbar with the other icons on the left side.

----

I assume the Rename word seen in the toolbar will then rename the current menu. I am hesitant in giving the word "Rename" so much attention as it gets in the toolbar. What if the name of the menu is there instead? Clicking the name opens a text field to where it could be edited. Similar to I am guessing would happen when clicking "Rename".

I think it would be better not to have a black background of the current item in the Navigation structure as it creates a very high contrast from what is not selected. Having a more subtile background color would cause less contrast when selecting any Nav structure item. It would also be helpful to add the tree branch lines back again, so it better shows the flow of a top menu item and it's submenu below it.

From the animated gif:
<img width="363" alt="Screen Shot 2020-09-11 at 10 42 48" src="https://user-images.githubusercontent.com/5323259/92895236-9b98d400-f41b-11ea-82b3-b4384fcb5ab1.png">



From the current PR:
<img width="306" alt="Screen Shot 2020-09-11 at 10 33 19" src="https://user-images.githubusercontent.com/5323259/92893805-4d370580-f41a-11ea-959a-b8ca6095fca2.png">

Perhaps something like this:
![Nav-structure-selected-item](https://user-images.githubusercontent.com/5323259/92898511-51652200-f41e-11ea-880f-375c51d4a017.jpg)
(I used it further above in the first mockup.)

I will see what else pops up.

**Comment by manmotive** [comment]
The latest design _looks_ very nice. My concern is it is a further step away from a 'data' view of a menu structure, which is what the current nav-menus.php page provides. (I am aware the data view is available in the drop down and that themes will be able to output the same block html that is being displayed here)

The current nav-menus.php page is used to create a plethora of styles of menus - off canvas mobile menus, vertical menus, accordion menus, 'bog standard' horizontal menus. I have concerns that at best the primary 'preview' view is going to look somewhere close to the front end menu, at worst it will look nothing like the front end at all. In either case I imagine it would be confusing to a good proportion of users.

In the new designs we're effectively looking at a data view of the menu, but presented as a front end menu. Stepping back a bit, is that the intention here and from a users point of view, is primarily presenting the menu structure as a 'front end' menu better than presenting it as a purely structural tree view?

**Comment by afercia** [comment]
Noting that the "Currently editing" select element needs a button and should not trigger changes of context on the `change` event. See https://github.com/WordPress/gutenberg/issues/25312 for more details.
