### ISSUE TITLE
Dev Notes for WP 5.6

### ISSUE THREAD

**Issue by cguntur** [WordPress/gutenberg#26108]
https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22

These are all the PRs that need Dev Notes to be written for. Please share them here as comments, see what is related, and create make/core posts accordingly. Please let me know if you're unable to write a note for our PR. The notes should be posted before WP 5.6 RC, but the sooner, the better.

@adamziel 

- [x] Refactor reusable blocks to not depend on the editor module - https://github.com/WordPress/gutenberg/issues/25853

@youknowriad 

- [x] Make the custom spacing theme support flag and block support API stable - https://github.com/WordPress/gutenberg/pull/25788 
- [x] Add/line height support flag stable  - https://github.com/WordPress/gutenberg/pull/25769
- [x] Mark the font size support flag as stable  - https://github.com/WordPress/gutenberg/pull/25695
- [x] Mark the color support flag as stable - https://github.com/WordPress/gutenberg/pull/25694
- [x] ~Add Custom CSS support to the Group block - https://github.com/WordPress/gutenberg/pull/25413~
- [x] ~Support custom units on theme.json - https://github.com/WordPress/gutenberg/pull/25217~
- [x] Add generated block classname to dynamic blocks - https://github.com/WordPress/gutenberg/pull/24546
- [x] Implement the custom classname support hook in the server - https://github.com/WordPress/gutenberg/pull/24483
- [x] Core Data: Implement `_fields` data reuse for entities - https://github.com/WordPress/gutenberg/pull/19498

@noisysocks 

- [x] ~Widgets editor: Overview of documentation - https://github.com/WordPress/gutenberg/issues/25759~

@ellatrix 

- [x] Block API: stabilize light block hook - https://github.com/WordPress/gutenberg/pull/25642

@aristath 

- [x] Convert all `px` values in front-facing styles to relative (`em`) units - https://github.com/WordPress/gutenberg/pull/24523

@jorgefilipecosta 

- [x] Fix: Media Text: Always show images on top on mobile - https://github.com/WordPress/gutenberg/pull/24468

@diegohaz 

- [x] Make accessible toolbar stable and deprecate old usage - https://github.com/WordPress/gutenberg/pull/23316

@vindl 

- [x] ~Site Editor: make close button replaceable - https://github.com/WordPress/gutenberg/pull/22001~

@ntsekouras 

- [x] Transform multiple selected blocks to Columns block #25829

**Comment by nerrad** [comment]
>  Convert _experimentalCreateInterpolateElement to a stable api - #20699

Pretty sure this was done for WordPress 5.5. It shouldn't be needed for the WordPress 5.6 release?

**Comment by gziolo** [comment]
> Block API: Add new utility to register block types from metadata in PHP - #20794

I believe it was released in WordPress 5.5. Was the dev note never published?

**Comment by youknowriad** [comment]
I think the dev notes for 5.5 here were published but the label from the PRs were not removed.

**Comment by aristath** [comment]
Probably this one too: https://github.com/WordPress/gutenberg/pull/24711

**Comment by jorgefilipecosta** [comment]
Dev note for Fix: Media Text: Always show images on top on mobile - #24468.


## Media & Text blocks on mobile now always show media on top.

Previously, if the stack on mobile behavior was not disabled, and media had the option to appear on the left (the default), on mobile, the media appeared on top and the text on the bottom. If media had the option to appear on the right on mobile when stacked media would appear at the bottom and text on top.
There was feedback that the left/right position of media should not map to top/bottom on mobile and that for a better UX on mobile, media should always appear on top. Starting with WordPress, 5.6 media text blocks will have media on top on mobile unless the stack on mobile option is disabled, and in that case, media appears at the side of text like on desktop.

**Comment by aristath** [comment]
Dev note for _Convert all px values in front-facing styles to relative (em) units - #24523_

## Default block styles now use font-size-relative values instead of absolute pixel values.
Previously, blocks were using hardcoded pixel values for all their sizing properties (paddings, margins, font-sizes etc).
Starting with WordPress 5.6, default block-styles use font-size-relative units (`em`) making it easier for themes to change the default content font-size without having to rewrite/override all block-styles.

**Comment by diegohaz** [comment]
Dev note for Make accessible toolbar stable and deprecate old usage - #23316

## Block toolbars now require controls to be ToolbarButton or ToolbarItem elements

Rendering native `<button>` or other custom tabbable elements directly as toolbar items (for example, using `BlockControls` or `BlockFormatControls`) has been deprecated. In order to improve toolbar accessibility, toolbar items now should use [`ToolbarButton`](https://developer.wordpress.org/block-editor/components/toolbar-button/#inside-blockcontrols) for regular buttons, or [`ToolbarItem`](https://developer.wordpress.org/block-editor/components/toolbar-item/#inside-blockcontrols) for any other kind of control (for example, dropdowns).

**Comment by cguntur** [comment]
I didn't realize that few of them were 5.5 related. 

Thank you @gziolo for the link.

**Comment by youknowriad** [comment]
@diegohaz Do you think we can have a before -> after snippet of code?

**Comment by diegohaz** [comment]
> @diegohaz Do you think we can have a before -> after snippet of code?

Updated my comment. Please, let me know if it's clear enough or there's a better example/wording that could be used.

**Comment by youknowriad** [comment]
Thanks Diego, that's perfect.

**Comment by adamziel** [comment]
Dev notes for Refactor reusable blocks to not depend on the editor module - #25853

## Reusable blocks now live in @wordpress/reusable-blocks which makes them... reusable

Reusable blocks are an experimental feature available in the post editor. To make them available in other editors, they were moved to a separate package called `@wordpress/reusable-blocks`. Keep in mind this feature is still experimental and may change. To enable reusable blocks in your block editor, simply change your `<BlockEditorProvider />` as follows:

```js
import { ReusableBlocksMenuItems } from '@wordpress/reusable-blocks';

const { __experimentalReusableBlocks } = useSelect(
    ( select ) => select( 'core' ).getEntityRecords(
        'postType',
        'wp_block',
    )
);

return (
    <BlockEditorProvider
        settings={ {
            ...settings,
            __experimentalReusableBlocks,
        } }
        { ...props } // value, onInput, onChange, etc.
    >
        <ReusableBlocksMenuItems />
        { children }
    </BlockEditorProvider>
);
```

**Comment by vindl** [comment]
>  Site Editor: make close button replaceable - #22001

We discussed this for the previous version and determined that it's not needed since it's still experimental.

**Comment by noisysocks** [comment]
> Reusable blocks are an experimental feature available in the post editor.

@adamziel: The _feature_ isn't experimental, just some of the APIs surrounding it 🙂

**Comment by ntsekouras** [comment]
Dev note for new Blocks API `createBlocksFromInnerBlocksTemplate`:https://github.com/WordPress/gutenberg/pull/25829/

## There is a new Blocks API  `createBlocksFromInnerBlocksTemplate` with which you can create blocks from `InnerBlocks` template.

Given an array of InnerBlocks templates or Block Objects, it returns an array of created Blocks from them.
It handles the case of having InnerBlocks as Blocks by converting them to the proper format to continue recursively.

This is especially useful for handling `block variations`, transformations and creation/replacement of blocks which use `InnerBlocks template`.

An example that would create new blocks from a block variation using InnerBlocks' template and replace the block's content is:
```
// Variations for block registration.
const variations = [
	{
		name: 'my-variation',
		title: __( 'My variation' ),
		innerBlocks: [
			[ 'core/paragraph', { placeholder: __( 'Write title…' ) } ],
			[ 'core/paragraph', { content: 'Hello' } ],
		],
	},
];

import { InnerBlocks } from '@wordpress/block-editor';
import { useDispatch, useSelect } from '@wordpress/data';
import { createBlocksFromInnerBlocksTemplate } from '@wordpress/blocks';

function MyEditBlock( { clientId } ) {
	const { replaceInnerBlocks } = useDispatch( 'core/block-editor' );
	const { variationWithInnerBlocksTemplate } = useSelect(
		( select ) =>
			select( 'core/blocks' ).getBlockVariations( 'my-block-name' )[ 0 ],
		[]
	);

	// This will be triggered by something like a button in Toolbar for example.
	const onSomethingClicked = () => {
		replaceInnerBlocks(
			clientId,
			createBlocksFromInnerBlocksTemplate(
				variationWithInnerBlocksTemplate.innerBlocks
			)
		);
	};

	return <InnerBlocks />;
}
```
