### ISSUE TITLE
Overview: Consolidating HTML anchor issues.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#26685]
I have noticed that there are a lot of anchor issues and issues associated/duplicates(?).
I want to create this issue to consolidate the anchor issues I came across. Do please add associated issues.
Let's cross these off when they have been taken care of.

- [ ] Add UI for setting ID (anchors) on list items (li) https://github.com/WordPress/gutenberg/issues/29838
- [x] Should anchor hook automatically format attribute text? https://github.com/WordPress/gutenberg/issues/25304
- [x] Auto fill HTML Anchor (IDs) https://github.com/WordPress/gutenberg/issues/6182
- [x] Create Custom HTML Anchor for Cover Image Block https://github.com/WordPress/gutenberg/issues/17781
- [x] Allow anchor links to have user defined title attribute https://github.com/WordPress/gutenberg/issues/17212~~
- [x] Icon of anchor is not shown in the Block Editor https://github.com/WordPress/gutenberg/issues/16621
- [x] Anchor Tags In Gallery Images Are Covered by the Caption, Rendering Them Unclickable https://github.com/WordPress/gutenberg/issues/14304
- [x] Show block ID attribute on navigator https://github.com/WordPress/gutenberg/issues/16307
- [ ] Anchor's ANCHOR_REGEX is incomplete https://github.com/WordPress/gutenberg/issues/16165
- [ ] In page anchor link suggestion in drop down. https://github.com/WordPress/gutenberg/issues/9660
- [x] Auto fill HTML Anchor (IDs) https://github.com/WordPress/gutenberg/issues/6182
- [x] Insert Link: clicking on same-page links reloads the editor https://github.com/WordPress/gutenberg/issues/10117
- [ ] RichText: empty anchor is removed (also in classic editor) https://github.com/WordPress/gutenberg/issues/13331

Stalled PR:
Show block anchor attribute in Block Navigation
https://github.com/WordPress/gutenberg/pull/16898

**Comment by annezazu** [comment]
Closing this out as many of these have been completed and this issue hasn't been kept up to date for 3 years. If we want to revisit, let's create a new issue that's up to date!
