### ISSUE TITLE
Code quality: Replace hardcoded store keys with store definitions

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#27088]
## Description

With #26655 it's possible to use store definitions as param for `select`/`useSelect`/`withSelect` and `dispatch`/`useDispatch`/`withDispatch` API method calls exposed from `@wordpress/data`. It resolves the issue with the need to use unscoped import statements for packages that define stores used as explained in https://github.com/WordPress/gutenberg/issues/8981#issuecomment-717397733:

> To be clear, all packages that use a given datastore should import it in the entry point by convention. It's something that could be improved because if it's missed, it might indeed cause errors. At the moment, there is no simple way to validate it happens. Example:
> https://github.com/WordPress/gutenberg/blob/87fa5f58534281aadd9bdf624f9b8384cfe66c89/packages/edit-post/src/index.js#L4-L10

The next step is to use newly exposed `store` definitions from the corresponding packages similar to how it was applied to the `store` exposef from `@wordpress/viewport` in #26655. Example:

```diff
diff --git a/packages/interface/src/components/complementary-area/index.js b/packages/interface/src/components/complementary-area/index.js
index 56ad63c601e1..f35fcf9d14bc 100644
--- a/packages/interface/src/components/complementary-area/index.js
+++ b/packages/interface/src/components/complementary-area/index.js
@@ -11,6 +11,7 @@ import { useDispatch, useSelect } from '@wordpress/data';
 import { __ } from '@wordpress/i18n';
 import { check, starEmpty, starFilled } from '@wordpress/icons';
 import { useEffect, useRef } from '@wordpress/element';
+import { store as viewportStore } from '@wordpress/viewport';
 
 /**
  * Internal dependencies
@@ -104,10 +105,8 @@ function ComplementaryArea( {
 				isActive: _activeArea === identifier,
 				isPinned: isItemPinned( scope, identifier ),
 				activeArea: _activeArea,
-				isSmall: select( 'core/viewport' ).isViewportMatch(
-					'< medium'
-				),
-				isLarge: select( 'core/viewport' ).isViewportMatch( 'large' ),
+				isSmall: select( viewportStore ).isViewportMatch( '< medium' ),
+				isLarge: select( viewportStore ).isViewportMatch( 'large' ),
 			};
 		},
 		[ identifier, scope ]
```

The goal is to make it simpler to maintain dependencies between packages to avoid bugs when consuming from npm. The other benefit is that we will prevent cyclic dependencies in the early stages of development.

### Tasks

This is the list of store names that should be replaced with their newly introduced store definitions:

- [x] `core`
- [x] `core/annotation` (#28156 @rafaelgalani)
- [x] `core/block-directory` (#27178 @rafaelgalani)
- [x] `core/block-editor`
- [x] `core/blocks` (#27336 @rafaelgalani )
- [x] `core/data`
- [x] `core/edit-navigation` (#27182, #27281 @rafaelgalani)  
- [x] `core/edit-post` (#27414 @rafaelgalani)
- [x] `core/edit-site` (#28695 @david-szabo97)
- [x] `core/edit-widgets` (#28044 @rafaelgalani)
- [ ] `core/editor`
- [x] `core/interface` (#28041 @rafaelgalani)
- [x] `core/keyboard-shortcuts` (#27355 @bosconian-dynamics)
- [x] `core/notices` (#27548 @gziolo)
- [x] `core/reusable-blocks` (https://github.com/WordPress/gutenberg/pull/27094 @grzim)
- [x] `core/rich-text` (#27820 @rafaelgalani)
- [x] `core/viewport` (@gziolo)

**Comment by rafaelgalani** [comment]
Hello! Are the unchecked items (except the one in #27094) available for taking? I would like to replace some of these. 
Initially, the `core/block-directory` one if it's not taken.

**Comment by gziolo** [comment]
Yes, those unchecked and without a PR referenced are up for grabs 👍

**Comment by rafaelgalani** [comment]
Taking `core/edit-navigation` 😸

**Comment by rafaelgalani** [comment]
@gziolo I was going to pick some more items, but I just saw that #27226 is proposing a change to the stores names. Should I wait for the PR to be merged or can I continue refactoring?

**Comment by gziolo** [comment]
> @gziolo I was going to pick some more items, but I just saw that #27226 is proposing a change to the stores names. Should I wait for the PR to be merged or can I continue refactoring?

There is no need to wait. We can always rebase with `master branch and update #27226 if we decide to change exported names. It will be a quick operation in IDE to replace `store as ` with an empty string 😄

**Comment by rafaelgalani** [comment]
Great! I just asked to make sure I wouldn't be complicating things 😸
I'll work on it then 👍🏻

**Comment by bosconian-dynamics** [comment]
I would love to pick up one of these as my inaugural Gutenberg issue, using the other PRs so far as a model for the work. `core/keyboard-shortcuts` looks to me like it might be relatively straightforward?

**Comment by rafaelgalani** [comment]
Can I take `core/blocks`? It looks a little bit more fun than the previous ones I took since other packages depend on it 😄

**Comment by gziolo** [comment]
@rafaelgalani, whatever works for you best. I added your name next to `core/blocks` on the list.

**Comment by gziolo** [comment]
I updated #27368 that removes bare import statements for packages that use now store definitions rather than hardcoded strings.

**Comment by rafaelgalani** [comment]
Taking `core/edit-post` 😸😸😸

**Comment by gziolo** [comment]
I'm looking at `@wordpress/editor` (`core/editor`).

**Comment by rafaelgalani** [comment]
Taking `core/rich-text`.

**Comment by rafaelgalani** [comment]
I'm looking at `core/interface`.

**Comment by rafaelgalani** [comment]
`core/edit-widgets` looks simple. Taking it 👍🏻

**Comment by rafaelgalani** [comment]
Taking `core/annotations`.

**Comment by rafaelgalani** [comment]
@gziolo 
Sorry for taking so long to reply, I'm not having much free time lately. 😞
I was looking into `core/edit-site`, but I got a bit confused with it:
The module's `store` is actually exporting a function that registers the store when called:

https://github.com/WordPress/gutenberg/blob/3458607659e7eaefa0de93f7c36702f6b6afce6b/packages/edit-site/src/store/index.js#L15-L26

This function is called in the exported `initialize` function, in the main module (that's the only place - line 57):

https://github.com/WordPress/gutenberg/blob/3458607659e7eaefa0de93f7c36702f6b6afce6b/packages/edit-site/src/index.js#L53-L65

And, finally, the `initialize` function is called in the PHP libs (again, from what I found, that's the only place - line 144):

https://github.com/WordPress/gutenberg/blob/b864c5de3e0b90b8c9558477176200b54ef6e9e6/lib/full-site-editing/edit-site-page.php#L139-L148

What should be done in this case? Should I use the store's name or take another approach? Also, if that's not the place to ask this question, I'm sorry. 😅

**Comment by gziolo** [comment]
@rafaelgalani, it's a great question and the best place to ask it 😄 You can skip this store, for now. I can tackle it myself at the very end since it might require some changes in how this store is initialized. On the bright side, this store is internal to the package that defines it in Gutenberg, so it's less of an issue that it doesn't use the store definition.

**Comment by rafaelgalani** [comment]
@gziolo OK, great! It would be nice to try it, but if that's the case then I can learn from your PR.
Also, I think there's another store that looks different from the others, `core/data`:
https://github.com/WordPress/gutenberg/blob/5c3a32dabe4393c45f7fe6ac5e4d78aebd5ee274/packages/data/src/store/index.js#L53
Apparently, the store is being registered as followed:

- It's registered in the `createRegistry` function (`packages/data/src/registry.js`):
https://github.com/WordPress/gutenberg/blob/6cfe7a78a82929eddd475f12a1b31cb50f3fb1db/packages/data/src/registry.js#L295
- The `createRegistry` function is exported by the `default-registry.js` module - with no arguments being passed, thus being assumed the default arguments:
https://github.com/WordPress/gutenberg/blob/3317476e6d3d6cf3bb4c9634f377cede661a3aa0/packages/data/src/default-registry.js#L4-L6
- And, finally, the exported function is imported in the package's `index.js` file, which executes the function and registers the store: 
https://github.com/WordPress/gutenberg/blob/77be77c60fc8bedc9c930d3c89a783a1b0f4be2f/packages/data/src/index.js#L9

Should I skip this one too? 😅😅

**Comment by david-szabo97** [comment]
Just opened a PR for `core/edit-site` https://github.com/WordPress/gutenberg/pull/28695

**Comment by david-szabo97** [comment]
@gziolo What do you think about adding an eslint rule in the future? https://github.com/WordPress/gutenberg/pull/28726

**Comment by gziolo** [comment]
> @gziolo What do you think about adding an eslint rule in the future? #28726
> I'm not familiar with eslint selectors so there might be a better/more accurate way though 😄

I like this rule. We want it only for Gutenberg so it makes sense to pick the simplest approach. If the rule is valid, then we have 700-ish occurrences coming from the last 3 stores ... 😱

**Comment by david-szabo97** [comment]
Yeah, that's a lot 😓 Instead of going on replacing strings as you setup the checklist in the PR description, we should go on by packages.
Like I did here: https://github.com/WordPress/gutenberg/pull/28775

**Comment by gziolo** [comment]
Should we maybe land the ESLint rule first at the warning level to make the process simpler?

**Comment by david-szabo97** [comment]
> Should we maybe land the ESLint rule first at the warning level to make the process simpler?

Oh, that sounds like a fantastic idea! We can also warn people working on new PRs to avoid using strings.

**Comment by gziolo** [comment]
@aristath, what's the current status after your recent work in this area? I see a few more warnings, are there any issues discovered? We should promote the warning to error as the last step.

**Comment by aristath** [comment]
There are just a handful of them remaining, these are the ones I couldn't address (*a couple of them were reverted because they were causing an issue with an e2e test)

https://github.com/WordPress/gutenberg/blob/4c3300c148a6398f7ab03fb71ad5f635268c8605/packages/block-library/src/categories/edit.js#L30

https://github.com/WordPress/gutenberg/blob/4c3300c148a6398f7ab03fb71ad5f635268c8605/packages/block-library/src/embed/edit.js#L67

https://github.com/WordPress/gutenberg/blob/4c3300c148a6398f7ab03fb71ad5f635268c8605/packages/edit-post/src/components/header/fullscreen-mode-close/index.js#L27

https://github.com/WordPress/gutenberg/blob/4c3300c148a6398f7ab03fb71ad5f635268c8605/packages/edit-post/src/store/actions.js#L499-L500

https://github.com/WordPress/gutenberg/blob/4c3300c148a6398f7ab03fb71ad5f635268c8605/packages/editor/src/components/post-publish-panel/prepublish.js#L36

https://github.com/WordPress/gutenberg/blob/4c3300c148a6398f7ab03fb71ad5f635268c8605/packages/server-side-render/src/index.js#L19

Once we address these 6 we should promote this to an error :tada:

**Comment by gziolo** [comment]
I started https://github.com/WordPress/gutenberg/pull/32537 which tries to tackle the remaining issues.

**Comment by gziolo** [comment]
We did it 🎉 

Amazing team effort everyone involved. Major props for the achievement.

There is even an ESLint rule `@wordpress/data-no-store-string-literals` that will prevent usage of hardcoded store names in the future.

There are still several places where we have hardcoded store names, but they require some architectural changes because the stores used in the code are present conditionally depending on the execution context.

There is a group of items to look at raised for the code used with native mobile apps in https://github.com/WordPress/gutenberg/issues/27751.

In the web part of the universe, we still have two places that need more work: 

Discovered in #32801:

https://github.com/WordPress/gutenberg/blob/ee69822d9317d0d4c9ca42b951dbf6700b0dadd6/packages/block-library/src/calendar/edit.js#L51-L55

Discovered in #32537 

https://github.com/WordPress/gutenberg/blob/58aab250eb04d8465fbf9a0e5c8ac1af0a8a8450/packages/server-side-render/src/index.js#L19-L23

The related follow-up issue is https://github.com/WordPress/gutenberg/issues/32842.
