### ISSUE TITLE
Tools for grouping PRs by focuses

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#27448]
The tool that we use for Gutenberg releases comes with a [changelog generator](https://github.com/WordPress/gutenberg/blob/master/bin/plugin/commands/changelog.js#L56) that pulls the title of the PRs bundled in the corresponding milestone and groups them together (see [releases](https://github.com/WordPress/gutenberg/releases)). Curating this changelog is now the more time-consuming part of the release process, so it'd be convenient to streamline.

Additionally, we now have a few sources for keeping up with all the work that is going on, see:

- Weekly: core editor summaries ([example](https://make.wordpress.org/core/2020/12/02/editor-chat-summary-25th-november-2020-2/))
- Bi-weekly: release posts ([example](https://make.wordpress.org/core/2020/12/02/whats-new-in-gutenberg-2-december/))
- Monthy: what's next? ([example](https://make.wordpress.org/core/2020/12/01/whats-next-in-gutenberg-december-2/))

and they don't always group the info in the same way. By grouping the info in all places into the same focuses we have for [phase 2](https://github.com/WordPress/gutenberg/issues/13113) and [site editing milestones](https://github.com/WordPress/gutenberg/issues/24551), there'll be more clarity around what's going on in each area.

## Tasks

- [x] ~Create/Rename existing set of labels by focus. See [phase 2 focuses](https://github.com/WordPress/gutenberg/issues/13113), and [site editing milestones](https://github.com/WordPress/gutenberg/issues/24551).~
- [x] https://github.com/WordPress/gutenberg/pull/27744 ~Changelog generator: update how it groups the PRs.~
- [ ] Changelog generator: adding subgroups within each section (group PRs by focuses (FSE, global styles), block types, etc.
- [ ] GitHub bot: suggest labels based on code + pings the PR author if it doesn't have one of the focuses labels.

**Comment by nosolosw** [comment]
Based on the [phase 2 focuses](https://github.com/WordPress/gutenberg/issues/13113) and [site editing milestones](https://github.com/WordPress/gutenberg/issues/24551), this is the first draft I've come up with (will update as necessary):

Label/Focus                  | What needs to be done
---------------------------- | ----------------------
[Focus] Screen: customizer   |  Rename the existing [Customization](https://github.com/WordPress/gutenberg/labels/Customization) label. Remove [Customizer](https://github.com/WordPress/gutenberg/labels/Customizer) + tag the existing issues with the new label. Related: #13205 
[Focus] Screen: menu         | Create the _[Focus] Screen: menu_ label. Related: #21340 
[Focus] Screen: widgets      | Rename the existing [[Feature] Widgets Screen](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Widgets%20Screen). Related: #13204 
[Focus] Navigation block          | What labels should we use? There's [[Block] Navigation](https://github.com/WordPress/gutenberg/labels/%5BBlock%5D%20Navigation) (73 open tasks), [[Feature] Navigation Screen](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Navigation%20Screen) (40 open tasks), [[Feature] Navigation Component](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Navigation%20Component) (7 tasks open), [[Package] Edit Navigation](https://github.com/WordPress/gutenberg/labels/%5BPackage%5D%20Edit%20Navigation) (0 open tasks) Related: #13206 #18208 #20853 #21136 #20748 #20846 #21372 
[Focus] Block Style System   | Rename the existing [Global Styles](https://github.com/WordPress/gutenberg/labels/Global%20Styles). Related: #20331 
[Focus] Block Patterns       | Rename the existing [[Feature] Patterns](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Patterns). Related: #21080 #20345 
[Focus] FSE: Infrastructure  | Rename the [Full Site Editing](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Full%20Site%20Editing) label to _[Focus] FSE: Infrastructure_. Related: #20791 #24818
[Focus] Theme Blocks          | Create the new label. Related: https://github.com/WordPress/gutenberg/issues/22724
[Focus] Query block | Rename the existing [[Block] Query](https://github.com/WordPress/gutenberg/labels/%5BBlock%5D%20Query). Related: https://github.com/WordPress/gutenberg/issues/24762
Tigtening up + New Features areas | Any issue not categorized with some of the above label focuses will fall into this group.


cc @mtias @annezazu @youknowriad @draganescu @karmatosed @mapk what do you think of this? I'm mostly unsure about what to do with the _[Focus] Screen: menu_ and _[Focus] Navigation block_.

**Comment by youknowriad** [comment]
- For me "customizer" and "widgets" go hand in hand. I'll defer to others but personally, I see these as the same focus.
 - should menu be "navigation screen" instead?
 - We should remove  "patterns", it's not a focus anymore or at least not something worth having a dedicated focus.
 - Should we add FSE: something to all FSE related focuses to understand that these are part of the same global project?

Don't let my feedback block you, these things can evolve over time.

Also it would be good to have a way to tell the changelog script to mark some focuses as experimental and automatically put things there even  if the "[type] experimental" label was not put on the PR.

**Comment by gziolo** [comment]
Great idea, some comments regarding technical details for the transition:

- `[Focus] Navigation block` on the list might contain labels related to FSE Navigation sidebar milestone https://github.com/WordPress/gutenberg/issues/24552 that is already closed. As far as I can see [`Navigation Component`](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Navigation%20Component) is related to that. @vindl or @Copons, can you confirm?
- For all screens, it could be shorter as `[Screen] Customizer`, etc.


> Should we add FSE: something to all FSE related focuses to understand that these are part of the same global project?

There is [[Feature] Full Site Editing](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Full%20Site%20Editing) that is applied to most of the existing issues related to FSE. It might need only renaming.

**Comment by annezazu** [comment]
Thanks so much for doing this and getting this rolling!

> I'm mostly unsure about what to do with the [Focus] Screen: menu and [Focus] Navigation block.

I'd recommend using `[Focus] Screen: Navigation` and `[Focus] Navigation block`. I think it's okay to keep navigation in both names as that's how we've been referring to them and there is inherent overlap in that work. 

>Should we add FSE: something to all FSE related focuses to understand that these are part of the same global project?

I agree with @youknowriad here as I think it would help a ton to have consistency in FSE related work as it's not always obvious at a glance if someone is new. This might also help drive home that FSE is actually a collection of work rather than "one project".

**Comment by mtias** [comment]
I'm not sure I understand how [Focus] should be used and what happens when it's no longer a focus but an established product area (like patterns).

**Comment by nosolosw** [comment]
OK, did a first-round and integrated your comments, this is the [current proposal](https://github.com/WordPress/gutenberg/issues/27448#issuecomment-737422675).

> I'm not sure I understand how [Focus] should be used and what happens when it's no longer a focus but an established product area (like patterns).

@mtias I see them as short-lived, and they should be renamed back when they're no longer a focus. For example:

- _[Focus] FSE: Block Navigation_ => renamed to _[Block] Navigation_
- _[Focus] FSE: Block Query_ => renamed to _[Block] Query_
- etc

Having a common prefix `[Focus]` intends to reinforce the messages in all channels (core-editor, release, monthly summary) and reduce the cognitive load when searching/tagging something. When someone ones to check a specific focus, they'll go to [labels](https://github.com/WordPress/gutenberg/labels), search by "Focus", and the 5-10 labels we have at any point in time will show up there. It seems easier to do that than to remember (or learn) that it is `[Block]` for some focus, `[Feature]` for others, etc.

@gziolo I'm not opinionated about the specific names, but it's important to me that all of the labels have the same prefix, otherwise, we don't fix the discoverability issue. Happy to consider shorter prefixes than `[Focus]`, but not sure which one?

---

Open the second round of feedback!

**Comment by gziolo** [comment]
I was only concerned by 3 labels that have both feature and screen keywords. I don't think that it's a focus really, it's just a way to provide more context or grouping for issues.

**Comment by youknowriad** [comment]
Yes, the main thing for me here is that I hope we can get back one hour or so from the time we spend preparing the changelogs. Doesn't solve everything but might help put things in the right place and the right section.

**Comment by draganescu** [comment]
@youknowriad @nosolosw the customizer focus should be separate from the screens as the core of the matter there is totally different. For the screens the focus is to improve the experience those screens offer for their function and to add block management support. For the customizer the focus is to allow the customizer to "talk" to the block editor so that we can get a live preview of block edits and also to create a good experience of block editing with live preview.

Therefore:

- it's ok to have three labels
- @nosolosw the "Customization" label has nothing to do with the customizer, we should leave it as it refers to customisation of the block editor.

**Comment by nosolosw** [comment]
Thanks for the feedback, folks! While I like the clarity this kind of "grouping" could bring, it also comes with some downsides (some management when the focuses change, people involved in the issues/PRs still want the existing labels and know what they should use, etc). So, it doesn't sound like creating this new set of labels is something people would find valuable at the moment. This is what I'd like to do as the next steps:

- Keep existing labels as they are ― no "focus" labels are created.
- Use the existing labels to reduce the amount of time we invest in generating the changelog.

**Comment by nosolosw** [comment]
ok, got https://github.com/WordPress/gutenberg/pull/27744 ready ― it improves a bit the changelog organization.

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/27744 has landed. Updated the tasks in the issue description.

**Comment by oandregal** [comment]
There hasn't been activity on this for years now, so I'm closing.
