### ISSUE TITLE
FSE Milestone:6 Navigation Block

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#27593]
Extends #24551
This is an overview issue that we'll maintain going forward into WP 5.5 and 5.6 milestones. It attempts to track discussions and resulting actions about the Navigation Block.

This overview does not track bugs of the Navigation Block, for that you should filter open issues using the labels [Block] Navigation and [Type]Bug.

### Hierarchy building

- [ ] unlimited nesting (e.g. #23603 #17231 #21691)
- [ ] easy parent/child selection 
- [ ] easy parent change
- [ ] list view
- [ ] inline view (e.g. #18482 #21447)
- [ ] drag and drop for changing nesting (e.g. #19703)
- [ ] multiple kinds of navigation links (e.g. #20542 #24814)
- [ ] multiple blocks available (e.g. #24364)

### Interaction customization

- [x] block orientations and transforming between (e.g. #22824) 
- [ ] fly-out submenus
- [ ] expand/collapse submenus
- [ ] ToC submenus
- [ ] responsive (hamburger) menu (e.g. #22824) 

### Hierarchy design

- [ ] empty canvas approach (similar to group block, or a submenu block) (e.g. #23745)
- [x] placeholder state (e.g. #25015)
- [ ] link editing (e.g. #24099 #18327 #18345 #18442 #18866 #20138)
- [ ] link list block (for accessible markup) (e.g. #24644)
- [ ] pages block (with autoupdate) (e.g. #16635 #27130)
- [ ] separators(e.g. #23293)
- [ ] spacing and padding (e.g. #24028)
- [ ] styling (e.g. #20810 #25691)
- [ ] invalid items (e.g. #23573 #21848)

**Comment by tellthemachines** [comment]
@draganescu for "Support drag and drop to reorder blocks in list view" shouldn't we be pointing to #25067 instead? (or maybe a separate issue to enable drag and drop for the block list view, as it's already working on the Navigation screen.) #19703 isn't about list view but the actual block interface.

**Comment by draganescu** [comment]
Thanks for catching that @tellthemachines 👍 I've corrected the link.

**Comment by fklein-lu** [comment]
Circling back to this issue, since it has been mentioned in the [Editor chat summary 27th January](https://make.wordpress.org/core/2021/01/27/editor-chat-summary-20th-january-2021-2/).

The list above contains no indications on how menus will be shared between templates. An example would be a main navigation, which would be present on every template.

Right now you can use a template part for this. Will this be the way going forward?

**Comment by mtias** [comment]
> Right now you can use a template part for this. Will this be the way going forward?

I think that's so far the most logical conclusion. It _might_ make sense to add "navigation" as one of the validated terms for #27337 and automatically create such parts upon menu creation if we can reduce unnecessary UX overhead. One thing that is not entirely clear yet is how independent navigation should be from the header and whether that should always be the case regardless of how the menu is built. For example, in some themes header and navigation would be virtually indistinguishable and creating further template parts would seem a hindrance. Some themes with complex mega-menus, the navigation would also be the header. However, in cases where the menu is a simple list of the root pages its reusability _as is_ becomes a lot more desirable.

**Comment by tellthemachines** [comment]
> Add support for separators between menu items #23292

Anyone know the correct issue number for this? #23292 is an apparently unrelated PR.

**Comment by jasmussen** [comment]
Good catch, I corrected the link to the separator issue, it was #23293.

**Comment by jasmussen** [comment]
Recent additions like the Page List block, and the incoming menu item setup state (#28440), take giant steps toward a better user experience. At some point, we'll want to create patterns that leverage the navigation block, so we can visualize the variety of different navigation menu designs possible. Currently the divergence in markup between front and backend makes that tricky, and the following efforts would help that a lot:

- The closer the admin markup is to the frontend, the less CSS we will need to write to style both, and the fewer edgecases we will need to handle. It sounds like #24644 can potentially solve that.
- #28575 would further simplify this effort, helping ensure that custom menu items are closer in markup to those inside a Page List.

Both these efforts will benefit the navigation block structure and styling, including patterns. It might even make some of the other tasks easier to address also.

**Comment by priethor** [comment]
Added #29036 to the list.

**Comment by jasmussen** [comment]
Added these two Page List css class related ones: 

https://github.com/WordPress/gutenberg/issues/29422
https://github.com/WordPress/gutenberg/issues/29423

**Comment by talldan** [comment]
Is there any plan to increase the priority of https://github.com/WordPress/gutenberg/issues/24644? It is in the high priority section, but right down at the bottom.

At the moment the Navigation block has lots of invalid markup when the following (non `<li>` elements) are inside the navigation block's `<ul>`:
- Placeholder Preview
- Page List
- Search Block
- Social Links

#24644 is supposed to resolve that by removing the nav block's `ul`.

**Comment by priethor** [comment]
I don’t think the order of the lists specify an order within the group, but if so I would also suggest #29306 and #24644 be a higher priority, as it's key to create a lean HTML markup with no `ul` wrapper and it impacts other work being done in the block.

**Comment by jasmussen** [comment]
To improve the legibility, I edited this one a little bit:

- Added strikethrough on fixed tickets
- Lowered priority on “Expand / collapse submenus: #18395." — This one is very difficult on the frontend, and is arguably not urgent. 
- Removed duplicate "Make it Mobile Responsive"

A couple of the items could use clarification:

- "Explore use of semantic template parts for automatic reusability." 
What does this mean? Is there a ticket it can point to?
- "Flyout submenus"
This one could also do with some context. Is there a ticket it could link to? Is it fixed by #29869? Is it a duplicate of "Expand/collapse submenus"?

**Comment by priethor** [comment]
>"Explore use of semantic template parts for automatic reusability."

I believe #27337 and [mtias' comment above](https://github.com/WordPress/gutenberg/issues/27593#issuecomment-768952678) provide the context for that. It is not actionable yet, though, so there is no specific ticket, but I'll link the issue as a context in the top comment :+1:

**Comment by priethor** [comment]
Regarding flyout submenus in the Navigation block, there is #29101. Is that what "Flyout submenus" in the list refers to?

**Comment by jasmussen** [comment]
I lowered the priority of "Allow insert before / after: #23603". It's a task that needs addressing, but it does not seem as high priority as all the others.

**Comment by jasmussen** [comment]
I added https://github.com/WordPress/gutenberg/issues/28575 to the list as high priority, because we need to level the playing field between menu items generated by the Page List block, and regular menu items:

<img width="583" alt="Screenshot 2021-03-17 at 09 47 06" src="https://user-images.githubusercontent.com/1204802/111439543-c6831e00-8705-11eb-9c88-e55d15e59ca8.png">

**Comment by jasmussen** [comment]
I checked off "Flyout menus", as #29932 has landed, if that item referred to additional things, please feel free to uncheck.

**Comment by priethor** [comment]
Added "_Add an API to retrieve content-only inner blocks_"  #30674 to the list

**Comment by jasmussen** [comment]
Checked off #29437 thanks to @gwwar's work!

**Comment by priethor** [comment]
Added:
- Provide a better way to disable/enable nav block features for the nav editor #30007
- Sidebar/Inspector control improvements #30370
- Add separate overlay color option #29963
- Make it clearer how to delete a Link Block without a link #30116
- Improve flow for deleting submenu items #30115

**Comment by priethor** [comment]
I've created a [Project Board](https://github.com/WordPress/gutenberg/projects/58) as suggested by @gwwar to easier identify PRs needing review, and added all pending issues and most PRs to it.

Feel free to add/tweak columns as needed! 🙂

**Comment by gwwar** [comment]
Awesome, thanks @priethor !

**Comment by jasmussen** [comment]
Checking off "Add Home block (#20542)" courtesy of @gwwar 🎉

**Comment by jasmussen** [comment]
Thanks to work from @vcanales, I checked off "Explore responsive (hamburger) menu: #22824"

**Comment by jasmussen** [comment]
Checked off "Allow folding of nested items" thanks to @gwwar 🥇

**Comment by jasmussen** [comment]
There's been a conversation about enabling more diverse navigation block patterns, that provide highly opinionated defaults, for example site navigations that show exactly 3 menu items, a site logo, and instagram/facebook/twitter links. Perhaps even with the navigation items pre-labelled.

To enable such patterns, the setup/placeholder state for the navigation block needs to be reconsidered with a focus on _menu item setup states_ instead. Consider these:

![quadrat-select-header](https://user-images.githubusercontent.com/1204802/123948807-1ed2e880-d9a2-11eb-9188-321858954cc6.gif)

Those are intrinsically opinionated patterns, and should be allowed to lean into that, just like we already do for Button patterns:

<img width="481" alt="Screenshot 2021-06-30 at 12 14 43" src="https://user-images.githubusercontent.com/1204802/123943807-c816e000-d99c-11eb-8910-b1d7a6b67ce7.png">

The buttons above have their labels pre-filled, but they link no-where. You could think of that as an "opinionated Buttons block pattern", and we need to be able to accommodate similarly opinionated ones for the navigation block. Only, it also needs to be much clearer that those buttons really do link no-where, and that you need to point them to their destinations, or they won't be very useful. 

This is particularly important for the navigation block, and we have a neat little trio of tickets that, when addressed together, should get us pretty far on that:

- [ ] [Navigation Block: Enhancement ideas for the empty placeholder](https://github.com/WordPress/gutenberg/issues/32373) (partially addressed by #32512)
- [ ] [Blocks that link: Provide a split label/URL control and placeholder state](https://github.com/WordPress/gutenberg/issues/30170)
- [ ] [Menu Item placeholder: Show page label in setup state](https://github.com/WordPress/gutenberg/issues/33091)

While those three tickets are not crucially urgent for the overall navigation block "phase 1" as outlined here, they are nevertheless important to address on our navigation block journey, and the solutions we find here can benefit not just Navigation, but also Buttons and potentially Social Links as well. 

I'll add these three items to the navigation block board, as a start, but for anyone reading, let me know if we should add them to the body of this ticket as well.

**Comment by jasmussen** [comment]
On behalf of @tellthemachines I checked the box for "Multiple blocks available". 👏

**Comment by jasmussen** [comment]
On behalf of @georgeh I checked the "Add a separate color overlay option" 🏅

**Comment by jasmussen** [comment]
For anyone reading, I wanted to tease that the task, "Allow insert before / after", will almost certainly be fixed as a side-effect of addressing #34041 and the proposed mockups, which entail creating a "default" block that you insert instantly.

**Comment by carolinan** [comment]
Related to link color settings missing or not working: https://github.com/WordPress/gutenberg/issues/34648

**Comment by priethor** [comment]
As the items in this issue are complete for the most part, I've created #35521 as the next iteration on Navigation Block improvements.

Let's continue there and keep this issue as a first iteration snapshot.

**Comment by jasmussen** [comment]
🚀
