### ISSUE TITLE
Site Editing Infrastructure and UI: Part 3

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#27814]
In #26355 we've introduced an initial version for the template editor mode in the post editor. This highlighted a few issues in the design/flows of that feature. The current issue is an overview tracking the progress for all oft these follow-ups:

### Blank Canvas Template

- [x] Allow creating custom block templates in classic themes #30438
- [x] Better distinguish between the content editor and the template editor. The users should be able to quickly tell which mode they are currently working with. #27849

### Interface

 - [x] Allow deleting new custom block templates, and reverting customized block templates in the template editor #31076
 - [ ] View the template while editing the post #27847
 - [ ] Design UX patterns for blocks based on context (content editing vs template editing) that enable users to flow between content editing and template editing directly on the canvas. #27848
 - [x] #27852
 - [x] Allow selecting custom page templates. #27778
 - [x] Find a visual way to list the available page templates (actually preview the templates and maybe show them in a starting modal). #27850, #31591
 - [ ] Give the user the possibility to save the changes to a template specific to the current post or a custom template that can be used in other posts too. #27851
 - [x] Add a welcome guide for the template mode. #29031
 - [ ] Colorise template parts and reusable blocks in the UI #32163
 - [ ] Mosaic View of Theme Templates. #20477
 - [ ] Bug: Template part click-through #35079
 - [ ] #35503

### Infrastructure

 - [ ] Allow using post meta values as "sources" for some of the blocks used in the template.
 - [x] Allow themes to opt-in/out of the "Create new template" flow.
 - [ ] Support dynamic values in block-based templates. #20966 #25316

**Comment by skorasaurus** [comment]
One more suggestion to add: While editing a template within the post editor, I went to the code editor mode, and the code editor mode returned the content of the post, not the template's content (what I expected); this is a result of https://github.com/WordPress/gutenberg/issues/22528

**Comment by youknowriad** [comment]
#30438 is now merged so classic themes can use blocks to build custom templates for pages and all CPTs that support Page templates now.

**Comment by priethor** [comment]
Added _Allow themes to opt-in/out of the "Create new template" flow_ to the list.

**Comment by youknowriad** [comment]
> Added Allow themes to opt-in/out of the "Create new template" flow to the list.

That's already possible with the `block-templates` support flag. you can do `remove_theme_support( 'block-templates' );`

**Comment by carolinan** [comment]
Short term, are the template and template part menus under Appearance going to be in 5.8?

If not:
- How can user created templates be deleted?
- Editing templates is possible, but you would first have to find a page or post that uses that template, or create a new page or post just to access that template.
- How can users edit templates that are not post or pages, such as search, archive, and 404?

If kept:
The editing views in the appearance>edit templates and block editor>edit template are not the same.
What is the intention with these separate views?

**Comment by youknowriad** [comment]
I think these screens are not meant to be shipped at all. So yeah if the template editor makes it to 5.8, we need at least a "delete" template somewhere in the template mode or the template panel.

**Comment by jameskoster** [comment]
> How can users edit templates that are not post or pages, such as search, archive, and 404?

Assuming dedicated template management (IE Appearance > Templates) doesn't ship in 5.8, it won't be possible to create these templates in the UI. So I think it's fair to assume there will not be an expectation of edit-ability either.

> we need at least a "delete" template somewhere in the template mode or the template panel

There is a revert affordance for customised block theme templates in the site editor. We can use that same design for deletion in the template editor. I'll make an issue.

**Comment by carolinan** [comment]
_it won't be possible to create these templates in the UI_
You meant in the appearance > templates UI?  Or not create templates at all via any sort of UI 😕

**Comment by jameskoster** [comment]
Not create the templates you mentioned specifically: search, archive, 404, etc.

**Comment by priethor** [comment]
> we need at least a "delete" template somewhere in the template mode or the template panel.

Added this to the list based on the recently created #31076

**Comment by adamziel** [comment]
Is there any feature here that could still land until Wednesday next week to be included in WordPress 6.0 release? To increase visibility, we can add it to the WordPress Editor 6.0 project board.

**Comment by mtias** [comment]
Time for a new reset: #41241
