### ISSUE TITLE
Improvements to Reusable Blocks

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#27890]
It's been a while since we gathered thoughts on where to take reusable blocks next. With the work that went into template parts — and particularly #27887 — the experience is going to be radically improved and several longstanding bugs removed. There are some design updates needed to accommodate some of these changes (no direct "edit / save" flow) and to improve the clarity of reusable blocks in general but let's also look into other ideas that can improve the different user flows related to them.

- [ ] Display reusable block title next to block type in toolbar (like template parts).
- [ ] Update block list view and breadcrumbs to show the title of a reusable block instead of "reusable block".
- [ ] Allow modifying saved title of reusable block in sidebar inspector.
- [ ] Show how many posts / pages are using a given block on the publish flow.
- [ ] Ensure post revisions are enabled for reusable blocks. #19149
- [ ] Allow users to see and navigate to posts using a given reusable blocks from the post type management screen.
- [ ] Add support for "excerpts" and use them on the block description (inspector, previews, etc).
- [ ] Review cases with 1000+ reusable blocks for performance bottlenecks.
- [ ] Consider support for categories or tags to organize reusable blocks. #7608

**Comment by paaljoachim** [comment]
Adding the following issue to the list:
Add content alignment option into the main reusable block toolbar
https://github.com/WordPress/gutenberg/issues/17640

**Comment by Tropicalista** [comment]
About my issue linked here, is it possible to add a reducer on https://github.com/WordPress/gutenberg/blob/da8555d258edbe676fa079fb51252f918ae032e1/packages/reusable-blocks/src/store/reducer.js

to let know the block is just been converted from a reusable block?

**Comment by NewYorkerLaura** [comment]
Just adding to the discussion here. In 5.7.1 creating new reusable blocks experience is disastrous. Their primary functions have been stripped away. I've had to roll over 100 client sites back to 5.6.3. It is a UX disaster. The best feature and the strongest selling point to clients of the Block editor is now non-functional

- I have no ability to name a block
- Lots of "untitled blocks" doesn't let me know which one I want
- I am unable to edit the block if my boilerplate has changed and have those changes iterate across the site (kind of a disaster in a where my  call to action purchase buttons across 50+ pages are now a right pain to update)
- I am unable to break a block out into regular blocks if I want a one-off change or are using the reusable block as a template

See attached video:

https://trainingvideoslaura.s3.amazonaws.com/reusable+block+not+working+on+PELC.mp4

**Comment by mtias** [comment]
The ability to name a block upon creation is addressed in trunk and should remove the case of having a bunch of "untitled reusable block" names:

![image](https://user-images.githubusercontent.com/548849/116104218-8e7ddc00-a6b0-11eb-861e-70dae29f32dc.png)

**Comment by jameskoster** [comment]
A possible consideration for inclusion here: https://github.com/WordPress/gutenberg/issues/43261

Edit: Tracked in https://github.com/WordPress/gutenberg/issues/43598 instead.
