### ISSUE TITLE
Integrate new Text Component (for Component System)

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/gutenberg#28020]
This is an extension of [Implementing a Component System](https://github.com/WordPress/gutenberg/issues/27484)

---

### Context ✨

The [`FontSizePicker`](https://github.com/WordPress/gutenberg/pull/27594) component was first to receive the upgrade to use the [new Components System](https://g2components.wordpress.com/).

We opted for a strategy (proposed by @gziolo) that imports and uses the various system parts via [npm dependencies](https://github.com/WordPress/gutenberg/issues/27484#issuecomment-738857333), rather than migrating the code by copying/pasting them over.

This was largely to expedite us figuring out the process for integration.
Using the new Component System code via external packages is not the end goal.

---

### Text Component 🔠

Continuing this work, we'll need to (effectively) "backfill" the dependencies required for `FontSizePicker`. It's worth repeating that this was the original plan, but it was adjusted to expedite integration testing.

After chatting with @saramarcondes , we felt like a good candidate for this would be `<Text />`.

Reasons being that `Text` is a low-level and common UI element we plan on using in many places. Also, `Text` already exists as an experimental component in the project. The one coming [from the new system](https://github.com/ItsJonQ/g2/tree/master/packages/components/src/Text) is vastly improved.

---

### Tasks ✅

In order to integrate the Text component we need to move the following dependencies into the GB repo in this order:
- [ ] partial `utils`
	- [ ] `is`, everything depends on this https://github.com/WordPress/gutenberg/pull/28028
	- [x] `useIsomorphicLayoutEffect` -> update `compose` to export this, dependency of `context` https://github.com/WordPress/gutenberg/pull/28023
	- [ ] `getOptimalTextShade`, dependency of `Text`
	- [ ] `getDisplayName`, dependency of `create-styles` and `context`
	- [ ] `getComputedColor`, dependency of `styles`
- [ ] `substate` https://github.com/WordPress/gutenberg/pull/28116
	- [ ] Migrate package (updated with [fork of `zustand`](https://github.com/ItsJonQ/g2/pull/219))
- [ ] `create-styles`
	- Update to use the following directly:
		- `merge-refs`
		- `hoistNonReactStatics`
		- `memoize` (from `memize`)
- [ ] `styles`
	- Update to use the following directly:
		- `colorize` (from `tinycolor2`)
		-	`reakit-warning`
- [ ] `context`
	- Update to use deepmerge and deep-equal directly and `useIsomorphicLayoutEffect` from `compose`.
- [ ] `Truncate` - completely new
- [ ] `Text` - uses adapter system

---

### Tracking 📆

I've added the tasks (above) on a Google Spreadsheet Gaant chart as another way of tracking progress.

https://docs.google.com/spreadsheets/d/1gfzznyJtTr3hHoGkGRdeBRjhuZVMRalF9NuLrxkl4Nk/edit?usp=sharing

---

cc'ing @saramarcondes

**Comment by ItsJonQ** [comment]
I think we can close this one for https://github.com/WordPress/gutenberg/pull/28475
