### ISSUE TITLE
Improvements to Cover Block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#28385]
The cover block is one of the most capable blocks we have in terms of how much expression it allows, but it can also be hard to understand given we layer its various capabilities conditionally. I've been collecting some various feedbacks on confusing aspects of the cover block.

- [x] Improve the various states: #28384
  - [x] Show alignment matrix and full height in the block placeholder but in a disabled state.
  - [x] Move "full height" after alignment matrix based on importance.
  - [x] Display replace media flow with "Add Media" text.
  - [x] When a background color is set, show "Add Media" instead of "Replace".
  - [x] Only show "Replace" when a video or image is set already.
- [ ] Replicate overlay / background color in the toolbar. #20837
- [ ] #39427
- [x] #34706
- [x] #34707
- [x] Create a better flow from _Image_ to _Cover_ by allowing the user to "Add text overlay" to an image block, which would transform the block into a cover. #28386
- [ ] Action for setting a Cover to match dimensions of background media #28387
- [x] Allow Opacity Option For Gradients/Colors #32339

**Comment by apeatling** [comment]
I would add another here https://github.com/WordPress/gutenberg/issues/17953 -- to stop situations where the background color and text color are the same. For example with TwentyTwenty if I select a white background, the text color defaults to white and is invisible.

**Comment by mtias** [comment]
Closing this as it has outlived its usefulness.
