### ISSUE TITLE
WP 5.7 Dev Notes

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#28539]
https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+is%3Amerged+label%3A%22Needs+Dev+Note%22

Here are all the PRs that need a Dev Note to be written. Please share them here as comments, see what is related, and create Make/Core posts accordingly. Please let me know if you're unable to write a note for your PR. The notes should be posted before WP 5.7 RC (Feb 23), but the sooner, the better.

@jasmussen 

- [x] Try: Make empty paragraphs take up the same space on the frontend, as in the editor #27995

@ajlende 

- [x] Add srcset for cover image #25171

@ntsekouras 

- [x] Display Block Information by matching block variations #27469
- [x] Change replaceInnerBlocks updateSelection property to false #26312

@youknowriad 

- [x] Remove autoFocus prop from URLInput and from the inserter search form #27578

@gziolo 

- [x] Data: Use store defintion as param for select and dispatch #26655, `@wordpress/data-no-store-string-literals` #28726

@ZebulanStanphill 

- [x] Buttons block: overhaul alignment/justification controls #23168

@leewillis77

- [x] Make i18n functions filter their return values #27966

@nosolosw 

- [x] Block supports for style properties added since 5.6. This is so themes have a heads-up on styles that users can now tweak.

**Comment by ntsekouras** [comment]
### Dev Note for: **Change replaceInnerBlocks updateSelection property to false #26312**

## Inner Blocks API Changes

We noticed that the majority of block authors prefer to keep the focus on the parent block upon insertion in the editor rather than move it to one of the child blocks. Prior to the changes introduced the default behavior was the latter, so we decided to change it to follow the more popular choice that is going to simplify API usage. To accomplish that we had to change the definition of the following parts of API:
- `InnerBlock` component
- `useInnerBlocksProps` hook
- `replaceInnerBlocks` action

### `InnerBlock` component and `useInnerBlocksProps` hook
Both handle the focus on the blocks with `templateInsertUpdatesSelection` property. If you want to keep the focus on the parent you can omit this property.

If you want to move the focus to the first child block you have to set this property to `true`. Examples:
```
<InnerBlocks template={ [ [ 'core/heading' ] ] }  templateInsertUpdatesSelection/>

const innerBlocksProps = useInnerBlocksProps(
	{       className: 'wp-block-cover__inner-container'       },
	{
		template: [ [ 'core/heading' ] ],
		templateInsertUpdatesSelection: true,
	}
);
```

### `replaceInnerBlocks` action
Reference: https://developer.wordpress.org/block-editor/data/data-core-block-editor/#replaceInnerBlocks

This action handles focus with the third argument `updateSelection`. If you want to keep the focus on the parent you can skip this argument when calling `replaceInnerBlocks`.

If you want to move the focus to the first child block you have to pass this argument  with `true` value. Examples:
```
replaceInnerBlocks( rootClientId, blocks, true )
```

**Comment by jasmussen** [comment]
_Dev note for #27995, Make empty paragraphs take up the same space on the frontend, as in the editor_

**Empty paragraph changes**

In [27995](https://github.com/WordPress/gutenberg/pull/27995) the default behavior of a published empty paragraph (`<p></p>`) changed. Before, the tag would collapse to zero width and zero height, and be inconsistent with what users saw in the editor. Now an invisible space character is output in empty paragraphs, ensuring linebreaks in the editor correspond to linebreaks on the frontend.
There is a chance of empty paragraphs accidentally published, which will now take up space. If that is the case, it is easily fixed by deleting the empty paragraphs.

**Comment by scruffian** [comment]
Dev note for  Verse Block: Add support for Font Size #27735 and Code block: Add support for font sizes #27294

**Code and Verse Blocks**
The Code and Verse Blocks now support custom font sizes. These can be customized by users on a per block basis using the inspector panel. Themes can also specify a default font size for these blocks using experimental-theme.json.

**Comment by ntsekouras** [comment]
_Dev note for: **Display Block Information by matching block variations #27469**_

### You can match a created block with one of its block variations by using the `isActive` new property in Block Variations API.

This can be useful for cases you want to use information from the block variation, after a block's creation. For example this API is used in `useBlockDisplayInformation` hook to fetch and display proper information on places like the `BlockCard` or `Breadcrumbs`.

Block Variation's settings can include the new property `isActive`. This optional property is a function that is used to find a block variation match from a created `Block`, by providing its attributes and a block variation attributes.

We need this function to be explicitly implemented by us, because in many cases it doesn't make sense to try to find a match by checking dynamically all block properties. An example is `embed` block where we might have changed the responsive attribute, so a match would not be found.

Example in a single block variation:
```
const variations = [
	{
		name: 'apple',
		title: 'Apple',
		description: __( 'Apple variation.' ),
		attributes: { fruit: 'apple', color: 'red' },
		isActive: ( blockAttributes, variationAttributes ) =>
			blockAttributes.fruit === variationAttributes.fruit,
	},
];
```

Example when all variations use the same matching function:
```
const variations = [
	{
		name: 'apple',
		title: 'Apple',
		attributes: { fruit: 'apple', color: 'red' },
	},
	{
		name: 'orange',
		title: 'Orange',
		attributes: { fruit: 'orange' },
	},
];

variations.forEach( ( variation ) => {
	if ( variation.isActive ) return;
	variation.isActive = ( blockAttributes, variationAttributes ) =>
		blockAttributes.fruit === variationAttributes.fruit;
} );
export default variations;
```

Example usage of the API:
```
import { useSelect } from '@wordpress/data';
import { store as blocksStore } from '@wordpress/blocks';
import { store as blockEditorStore } from '@wordpress/block-editor';
function getBlockVariationMatch( clientId ) {
	return useSelect(
		( select ) => {
			if ( ! clientId ) return null;
			const { getBlockName, getBlockAttributes } = select(
				blockEditorStore
			);
			const { getBlockVariations } = select( blocksStore );
			const blockName = getBlockName( clientId );
			const variations = getBlockVariations( blockName );
			if ( ! variations?.length ) return;
			const attributes = getBlockAttributes( clientId );
			const match = variations.find( ( variation ) =>
				variation.isActive?.( attributes, variation.attributes )
			);
			return match;
		},
		[ clientId ]
	);
}
```

**Comment by ajlende** [comment]
Dev note for: **_Add srcset for cover image #25171_**

**Cover Block**

The cover block now uses an `img` element instead of using CSS `background-image` for images that are _not_ using fixed or repeated backgrounds. This means that, when rendering the post, a `srcset` attribute will be applied with the various generated image sizes, saving bandwidth by loading smaller images when possible.

**Comment by aaronrobertshaw** [comment]
_Dev note for: **Block Support: Add border radius support https://github.com/WordPress/gutenberg/pull/25791**_

## Border Radius Support
The ability to manage a border radius style property for blocks has been added. This support is disabled by default however it can be opted into and themes can specify default border radii using `experimental-theme.json`.

#### Opting In
An individual block can opt in by setting the `__experimentalBorder.radius` property to true within its support configuration:
```
{
	...
	"supports": {
		"__experimentalBorder": {
			"radius": true
		}
	}
}
```

#### Default Border Radius Styles
Themes can apply a default border radius for desired block contexts via `experimental-theme.json`:
```
{
	"settings": { ... },
	"styles": {
		"core/group": {
			"border": {
				"radius": "50px"
			}
		}
	}
}
```

#### Sidebar Controls
The inspector control to manage border radius values is disabled by default while the sidebar is being refined. It can still be turned on by updating the appropriate context within `experimental-theme.json`. For example:
```
{
	"settings": {
		"core/group": {
			"border": {
				"customRadius": true
			}
		}
	}
}
```

**Comment by gziolo** [comment]
> An individual block can opt in by setting the __experimentalBorder.radius property to true within its support configuration:

> The inspector control to manage border radius values is disabled by default while the sidebar is being refined. It can still be turned on by updating the appropriate context within experimental-theme.json. For example:

I don't think this is ready for prime time if it is behind the experimental flags. @nosolosw should have a better overview of where the Global Styles project is, but I don't think this is going to be possible to use this Border Radius Support in WP 5.7.

**Comment by leewillis77** [comment]
There's documentation here which can be used (as-is, or with minor tweaks) as a dev note for "Make i18n functions filter their return values #27966". I don't have the ability to create make/core posts AFAIK, but happy to write the words if any changes are required to the content as-is

https://github.com/leewillis77/gutenberg/blob/add/i18n-filter-docs/docs/designers-developers/developers/filters/i18n-filters.md

**Comment by nosolosw** [comment]
@gziolo is correct [here](https://github.com/WordPress/gutenberg/issues/28539#issuecomment-769622898): the border radius is still experimental (as other properties we added in this cycle such as font height, etc). I'm going to remove it from the issue description.

It was me who tagged that PR with "needs dev note", though. @aaronrobertshaw I'm sorry that I made you write this note down! The good news is that we can reuse that text for when it's marked as stable.

**Comment by nosolosw** [comment]
I've reviewed the existing dev notes and it looks like the [ones](https://github.com/WordPress/gutenberg/issues/28539#issuecomment-768970993) for the code and verse block shouldn't be listed either: these are not dev-facing features (don't add, update, remove any API) but user-facing ones. Again, it was me who tagged those PRs ― it seems I've been misusing the "need dev note". Sorry about that. Hopefully, I've learned how to use it in the future! Going to delete them from the issue description.

**Comment by leewillis77** [comment]
Apologies, but I don't think the existing documentation is actually sufficient for "Make i18n functions filter their return values #27966" - there is another API change that should go in the dev note. I'll collate everything today and post here when ready!

**Comment by leewillis77** [comment]
Dev note for #27966 is here, which includes a note about the changes to instantiation of i18n instances:
https://gist.github.com/leewillis77/088c47a89d3319d45f93a7a3b9774ba3

**Comment by noisysocks** [comment]
Thanks for getting in early everyone! Friendly* reminder that the due date for dev notes is 23 Feb. Ping me if you need help or can't do it.

<sup>* read: passive aggressive</sup>

**Comment by adamziel** [comment]
The PR I was asked to write a note on was later reverted: https://github.com/WordPress/gutenberg/pull/26828 – you may safely cross it off the list :-)

**Comment by leewillis77** [comment]
I've had a second pair of eyes over the dev note for #27966 and it's updated based on feedback here:
https://gist.github.com/leewillis77/088c47a89d3319d45f93a7a3b9774ba3

I don't have the ability to post on make core though so someone else would have to actually post it...

**Comment by noisysocks** [comment]
> I don't have the ability to post on make core though so someone else would have to actually post it...

No worries I can handle that.

**Comment by kevin940726** [comment]
_Dev note for: **Add widget id to blocks in the widgets screen #28379**_

`cloneBlock` now only clones the attributes that are specified in the block types, follows the same logic as in `createBlock`.

**Comment by gziolo** [comment]
Dev note for:  **Data: Use store definition to reference registered stored when using `@wordpress/data` API #26655**

It is now possible to pass a store definition instead of the string referencing a given store registered with `@wordpress/data` API. This change ...

@wordpress/data-no-store-string-literals #28726

**Comment by nosolosw** [comment]
_Dev note for:  Block supports for style properties added since 5.6. This is so themes have a heads-up on styles that users can now tweak._

Following the [initial work done for WordPress 5.6](https://make.wordpress.org/core/2020/11/18/block-supports-in-wordpress-5-6/) to automatically support style properties for blocks and expose UI controls for users, in WordPress 5.7 this mechanism has been expanded to new blocks. Themes may want to review if their styles need to adjust their specificity to accommodate the user choices.

User have now the ability to update the font size of the following blocks via the inspector panel:  `core/code`, `core/list`, `core/preformatted`, `core/verse`.

**Comment by youknowriad** [comment]
**URLInput component**

In previous versions the URLInput component available on the `@wordpress/components` package and script had the `autoFocus` prop set to true by default. The main reason for this was that the component was used as the first input in different modals/popovers (link, inserter) but most third-party usage had to explicitly disable that behavior (in blocks for instance). In WordPress 5.6, that prop is `false` by default. It's a better choice for most use-cases as auto-focus is often an accessibility bug, but consider checking your components if you previously relied no this behavior.

**Comment by ZebulanStanphill** [comment]
@youknowriad I spotted a little typo:

> ...if you previously relied **no** this behavior.

**Comment by talldan** [comment]
Dev note for: **Buttons block: overhaul alignment/justification controls #23168**

### Changes to the Buttons block's alignment options

The buttons block now provides justification options for its inner button blocks (Justify items left, Justify items center, Justify items right, Space between items).

To implement this feature, the block's `<div>` element is now a flexbox container (`display: flex`)—previously it was `display: block`. It's recommended that theme developers check that the buttons block still displays correctly for users for the various alignment and justification options it now provides.

The left and right alignment options for the buttons block have now been deprecated. Users can achieve the same results using a combination of a full alignment and left or right justification. Any buttons blocks that were already added to posts with left and right alignment will be migrated (via the block deprecation system) to use justification in this way when a post is loaded—users should see no change in the visual appearance of buttons.

**Comment by noisysocks** [comment]
Thanks everyone!

**Comment by ZebulanStanphill** [comment]
I'd tweak the dev note to be a bit clearer:

The Buttons block now provides justification options for its inner button blocks (Justify items left, Justify items center, Justify items right, Space between items).

To implement this feature, the block's `<div>` element is now a flexbox container (`display: flex`)—previously it was `display: block`. It's recommended that theme developers check that the buttons block still displays correctly for users for the various alignment and justification options it now provides.

The left, right, and center block alignment options for the buttons block have now been deprecated. The center option was deemed redundant with the introduction of the "Justify items center" option, and the left and right options (which applied `display: float` styling) were considered confusing since most users expected them to behave like the new left and right item justification controls.

Users can achieve the same results as the center block alignment option by using the "Justify items center" option, and they can recreate the wrapping/float behavior of the left and right block alignment options by wrapping the Buttons block in a Group block and using its block alignment controls.

Since the wrapping behavior was unexpected and out of place for most use cases of the block, any Buttons blocks that were already added to posts using left, right, or center alignment will be migrated (via the block deprecation system) to use the corresponding justification options when a post is loaded in the editor—Buttons on the front-end will continue to appear as they did until the post they are in is edited and updated.
