### ISSUE TITLE
Improvements to Gallery Block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#29185]
- [x]  Gallery: Refactor as wrapper around core image blocks https://github.com/WordPress/gutenberg/pull/25940
- [x]  [WIP] Extend updateBlockAttributes to provide for different attribute changes for each block in the clientIds array https://github.com/WordPress/gutenberg/pull/29099
- [x]  Fill component throws state update warning https://github.com/WordPress/gutenberg/issues/28478
- [x] Update gallery block fixtures to match with gallery refactor to nested Image Blocks https://github.com/WordPress/gutenberg/pull/28481
- [x] Gallery Block: Edit/remove buttons cover move image buttons https://github.com/WordPress/gutenberg/issues/28600 (_can [potentially be closed now](https://github.com/WordPress/gutenberg/issues/28600#issuecomment-907890379)_)
- [ ] Gallery: Move "Add new" action to Toolbar https://github.com/WordPress/gutenberg/pull/25321 (_following merge of refactor it [may be easier to close this and create a new PR](https://github.com/WordPress/gutenberg/pull/25321#issuecomment-907891679)_)
- [x] Make links in gallery captions white https://github.com/WordPress/gutenberg/pull/27743
- [ ] Move Gallery "Add new / Media Library" actions to the Toolbar https://github.com/WordPress/gutenberg/issues/21247
- [ ] Gallery: Move "Add new" action to Toolbar https://github.com/WordPress/gutenberg/pull/25321
- [x] Refactor GalleryImage to use React hooks https://github.com/WordPress/gutenberg/pull/25305 (_closed - as this code is being deprecated post refactor it probably isn't worth refactoring at this point_)
--
- [ ] New Block: Flowing Masonry Gallery https://github.com/WordPress/gutenberg/issues/28247
- [x] Block height drops to 0 on alignment set to left or right https://github.com/WordPress/gutenberg/issues/27636 (_[seems to be fixed in 5.8 and Gutenberg 11.3](https://github.com/WordPress/gutenberg/issues/27636#issuecomment-907897837_))
- [x] https://github.com/WordPress/gutenberg/issues/26458
- [ ] Gutenberg Gallery block does not center in Full Width Template. https://github.com/WordPress/gutenberg/issues/26674
- [ ] Columns number reset to 3 in gallery settings https://github.com/WordPress/gutenberg/issues/27706
- [ ] It's not clear that you can scroll to view long gallery image captions.
https://github.com/WordPress/gutenberg/issues/7963
- [x] External links in the Gallery block https://github.com/WordPress/gutenberg/issues/10057
- [ ] Image Upload - Invalid JSON warning https://github.com/WordPress/gutenberg/issues/16372
- [x] Media library can only be opened once - upload freezes on second opening https://github.com/WordPress/gutenberg/issues/11373 (_fixed in 5.8_)
- [x] Improve the Gallery images alt attribute within the editor block https://github.com/WordPress/gutenberg/issues/16886 (_after refactor images don't have aria label, so closed_)
- [x] Gallery images not displaying scaled image files... https://github.com/WordPress/gutenberg/issues/20778 - (_appears to be fixed by refactor_)
- [x] Resizing images in the image gallery are not reflected in the Gutenberg UI https://github.com/WordPress/gutenberg/issues/28250

**Mobile**
- [x] [RNMobile] Refactor: gallery to nested image blocks https://github.com/WordPress/gutenberg/pull/26823
- [x] [Gutenberg][Testing] Gallery to inner blocks (mobile) https://github.com/wordpress-mobile/WordPress-iOS/pull/15284

**Associated**
- [x] Image block caption to become an inner/child block https://github.com/WordPress/gutenberg/issues/28920
- [ ] Introduce a way to manage focus on the RichText editor https://github.com/WordPress/gutenberg/issues/9740
- [ ] "Undo trap": Avoid getting stuck in an editing state https://github.com/WordPress/gutenberg/issues/8119
- [x] Consistency between image options in single image and gallery blocks. https://github.com/WordPress/gutenberg/issues/11436

https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+label%3A%22%5BBlock%5D+Gallery%22+

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/issues/11849

**Comment by glendaviesnz** [comment]
@paaljoachim I went through the above and closed some, and added some notes to others (italics)

**Comment by mtias** [comment]
Thanks @glendaviesnz. Actually, we can close this whole issue because the main planned work is done and what remains can be handled in their own issues.
