### ISSUE TITLE
Persistent List View tracking issue

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#29736]
The Persistent List View will benefit as well from the improvements done to the List View feature as collected in #29733

**Milestone 1 - First implementation**
- [x] Persistent block navigator and hover indications on the Canvas #27395

**Milestone 2 - Refinement and usability enhancements**
- [x] Enable Drag and Drop #29729
- [x] Add to the Post Editor #29470, #22113, #31047
- [x] Handle multi-selected blocks #29469
- [x] Show the entire content of Query blocks #29784
- [x] Improve hover, focus, select styles to make the focus clear in relation to the canvas #29467
- [x] Add a way to focus back to the sidebar via keyboard #29466 
- [x] Scroll to show the selected block in List View when selecting a block in the editing canvas #30432
- [ ] #33583 (In progress: #42605)

**Milestone 3 - Further improvements.**
- [x] Merge the list view and the document outline #14956
- [ ] Improve interplay with the other left-side sidebars (split sidebar) #29468
- [ ] Provide access via breadcrumb bar #28745

**Comment by talldan** [comment]
@priethor I made an issue here that might be considered for tracking - https://github.com/WordPress/gutenberg/issues/30432 - what do you think?

**Comment by priethor** [comment]
Seems like a great enhancement to me (and @Copons seems to agree as well 🙂  )

Added to the list! 👍

**Comment by Copons** [comment]
I've updated the issue mentioning #31047, which is the PR that adds the persistent list view to the post editor.

**Comment by simison** [comment]
Should be added to Block Widgets editor as well? It currently has the old version (tested in 10.6):

<img width="354" alt="image" src="https://user-images.githubusercontent.com/87168/118813467-d3fc8600-b8b7-11eb-9263-3d73cb3acae3.png">

**Comment by Copons** [comment]
> Should be added to Block Widgets editor as well? It currently has the old version (tested in 10.6):

@simison I'm not familiar with the Widgets editor, but it should be fairly easy from a code standpoint (see https://github.com/WordPress/gutenberg/pull/31047).
A good chunk of the code diff is about tests, but everything else is quite straightforward, as all have a very similar layout.
The persistent list view as I've developed it, basically needs the header and the interface's secondary sidebar to exist, plus some small updates to the `edit-*` state.

Of course, I can absolutely help with that if needed.

**Comment by simison** [comment]
Cc @draganescu for thoughts on above.

**Comment by priethor** [comment]
Although it doesn't seem like the Widgets Editor hierarchy will usually grow as big as the Post or Site Editor's, it would be good to add it even if it is from a UI consistency point of view. The priority in the Widgets Editor before and after feature freeze is stabilizing it as much as possible, but let's keep it in mind in #32311 👍

**Comment by talldan** [comment]
I've created an issue for improving e2e test coverage of List View - https://github.com/WordPress/gutenberg/issues/38774.

**Comment by slomeli79** [comment]
Is there currently a way (even via code snippet) to force List View to always be open by default?

**Comment by andrewserong** [comment]
I've written up a fresh issue to look at some of the current usability tasks for the list view over in https://github.com/WordPress/gutenberg/issues/49563. While there are still some outstanding tasks in this issue, it's also quite an old one, and after chatting with @talldan, it sounds like it might be a good time to close out this particular tracking issue. Feel free to re-open this issue, though, if anyone would prefer to keep this one going!
