### ISSUE TITLE
Refactored Gallery: Known Issues List

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#29883]
This collects the outstanding known issues related to the [refactored gallery](https://github.com/WordPress/gutenberg/pull/25940) with the view to assist during a wider call for testing. Most of these are not caused by the refactoring of the gallery however are likely to show up during testing.

- [x] Sibling inserter should not show on hover over gallery images, but sometimes does - appears to have been fixed
- [ ] [Undo for uploaded image blocks is broken](https://github.com/WordPress/gutenberg/issues/8119)
- [ ] [Block has no toolbar when first dragged out of Gallery](https://github.com/WordPress/gutenberg/issues/28474)
- [ ] [State update warning thrown when dropping an Image dragged out of the gallery](https://github.com/WordPress/gutenberg/issues/28478)
- [ ] Above image undo problem also breaks the collection of image size options for the gallery
- [ ] Image block style previews still have active dropzones allowing images or entire galleries to be dropped into them
- [ ] RichText toolbar for gallery caption isn't hidden after initial focus of caption field then clicking upload placeholder
- [ ] [ Image size selector appears to have no effect when 'Crop images' selected](https://github.com/WordPress/gutenberg/issues/29917)
- [ ] [Image block crop tool does not work well in gallery context](https://github.com/WordPress/gutenberg/issues/29957)

**Comment by glendaviesnz** [comment]
Closing this in favour of a temporary project board to manage these - https://github.com/WordPress/gutenberg/projects/56
