### ISSUE TITLE
Navigation Block: Sidebar/Inspector control improvements & allow always-collapsed menu

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#30370]
## What problem does this address?

The inspector controls for the navigation block have grown organically and is deviating from proposals in #27331 and https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866 in a few ways. 

<img width="318" alt="Screenshot 2021-03-30 at 09 48 50" src="https://user-images.githubusercontent.com/1204802/112954334-96dd0880-913e-11eb-8453-8fea0c3779a1.png">

Additionally, with improvements ticketed in the following issues, it will be necessary to add some new controls:

- [x] #29963 Add separate overlay color option
- [x] #22824 Make it responsive

This ticket serves to provide a path forward for the design of the navigation sidebar. 

## What is your proposed solution?

<img width="377" alt="Screenshot 2021-03-30 at 09 34 55" src="https://user-images.githubusercontent.com/1204802/112953205-96903d80-913d-11eb-9104-491511bec620.png">

A few things here, but note that each of these can happen as separate steps, and should be looked at holistically in context of #27473 and #27331:

- [ ] Instead of adding additional panels that expand and collapse, show foundational functionality of the block right in the first panel, and retire the "Display settings".
- [x] Simplify and reduce the labels of the panels. "Color" instead of "Color settings", 
- [ ] Show a small preview of the mobile menu, and how it is affected by the toggles below.
- [x] Use a new segmented control (from #27331) to let you toggle between showing the burger never, mobile or always.

## "Unfold nested submenus"

Part of this mockup is also a new toggle in the submenu category, to let you unfold nested submenus. That is, instead of having to expand out in ever expanding menus like this:

<img width="818" alt="Screenshot 2021-03-30 at 10 08 39" src="https://user-images.githubusercontent.com/1204802/112955799-17503900-9140-11eb-9372-f8c8ecaaa517.png">

... nested submenus would expand like this:

<img width="736" alt="Screenshot 2021-03-30 at 10 09 37" src="https://user-images.githubusercontent.com/1204802/112955875-2800af00-9140-11eb-9414-425415fe22e2.png">

**Comment by shaunandrews** [comment]
Everything here seems super great, except for the mobile menu preview thing; I don't quite understand it's purpose, and with the design shown it's not obvious what it actually is/does.

**Comment by jasmussen** [comment]
Absolutely. The "feature card" at the top is something I think will either start to make sense in a PR, and take shape as part of that, or reveal itself to not work in practice. 

It is inspired by some of the [Global Styles patterns](https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866) and aims to elevate the sidebar from being a dull sequence of form widgets to adding some character to each block.

**Comment by mtias** [comment]
Where are we with this one now that the component is ready?

**Comment by jasmussen** [comment]
There are some fresher mockups for this one here: https://github.com/WordPress/gutenberg/issues/18395#issuecomment-909204467

**Comment by jasmussen** [comment]
Changed this one to an overview issue, where #34783 exists as a separate ticket. I'd love to pair on that one.

**Comment by jasmussen** [comment]
The recent #35568 PR actually accomplished most of what's on this list. Except for this one:

> Instead of adding additional panels that expand and collapse, show foundational functionality of the block right in the first panel, and retire the "Display settings".

This item was added to embrace one of the patterns being explored for Global Styles in https://github.com/WordPress/gutenberg/issues/34574, but is arguably best tracked separately, as it is a pattern that can/should be applied to all blocks, not just navigation. In that vein, I'm going to close this one, and follow up with a separate ticket once those pieces come into more clarity.

**Comment by mtias** [comment]
Another thing we don't have is the "preview". Also using it in practice I think we can add more contextual info for each state. (As in, update the help description based on what option is set to better communicate what is going on.)
