### ISSUE TITLE
Improvements to Site Logo block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#30406]
The site logo is currently quite rough. This is a list of improvements to make.

![image](https://user-images.githubusercontent.com/548849/113125768-3ff73200-9217-11eb-8ce6-4184f40714bf.png)

- [x] Add alignments control. #31544
- [x] Add inline cropping. #31607
- [x] Better icon. #30211 
- [x] Add link toggle to "home".
- [x] Set a default width of around 120px. Currently the block displays huge and doesn't seem like a logo at all. #30526 
- [x] Update the placeholder to also be simpler and look like a smaller target for drag and drop instead of the wide default placeholder. #30526 
- [x] Allow using the site logo for the site icon from the block inspector — this is an important flow. #35892
- [x] Expand block description to explain what it is and how it works better. #30526 
- [x] Improve block description.
- [x] #35096
- [x] #34796
- [x] #34146

**Comment by jasmussen** [comment]
Nice one, I'm going to take a stab at a few of these. Though note, when the site logo is used in the right context — in my case the site editor, I'm seeing the alignments control correctly show up:

<img width="483" alt="Screenshot 2021-04-06 at 11 53 08" src="https://user-images.githubusercontent.com/1204802/113693266-b63fdc80-96ce-11eb-95d1-b8b6cef43eae.png">

I'm not sure why they don't show up when used in the post editor, @scruffian do you recall?

**Comment by jasmussen** [comment]
CC: @ajlende, I know you have your plate full, but wanted to point to the cropping task in case it's an easy one.

**Comment by JustinyAhin** [comment]
Just jumping on those
I'd like to tackle the width issue

**Comment by jasmussen** [comment]
@JustinyAhin I've fixed the width issue in a PR I'm currently making 🙈

**Comment by JustinyAhin** [comment]
Oh good to know @jasmussen .
Moving to my usual triage then 😀

**Comment by jasmussen** [comment]
The Site Logo shows up even if my theme has not declared support using `add_theme_support`. This is probably good, but it did surface a few issues:

- [ ] Once I define a site logo and publish it, I cannot unset it just from the block.

I ended up having to switch to a theme that did support custom logos, then removing it in the customizer.

**Comment by jameskoster** [comment]
> Allow using the site logo for the site icon from the block inspector — this is an important flow.

I think it should be possible for users to do this elsewhere as well. I shouldn't have to be displaying my Site Logo in order to set the Site Icon. In fact I ran in to this exact use case when helping a friend with their site over the weekend. They wanted to set a favicon, but also wanted a plain text "logo" in their site header.

Likewise I shouldn't have to go in and edit a _template_ to update my _logo_. This should be possible of course, but not the only way.

I would vote for adding these to the WP settings alongside the Site Title and Tagline. The blocks (and potentially other UIs in the editor) can then manipulate these settings ad hoc.

**Comment by jasmussen** [comment]
I took a stab at a few of the items on this list in https://github.com/WordPress/gutenberg/pull/30526. Specifically the width, the placeholder, and the description.

**Comment by jameskoster** [comment]
If a logo hasn't already been set, I think it might be fun to programatically generate a logo upon insertion. This would fast-forward the user closer to where they want to be, and eliminate the need to the extra UI (placeholder) since they can simply use the already-familiar image tools to replace the auto-generated placeholder.

![logo](https://user-images.githubusercontent.com/846565/113844354-4e4fcb80-978c-11eb-8e29-d1a54090b77e.gif)

**Comment by mtias** [comment]
Description updated in #30909

**Comment by carolinan** [comment]
The alignments are only available if the logo is placed inside another block. It is a feature or side effect of the new way to handle layout/width settings https://github.com/WordPress/gutenberg/issues/30568

**Comment by hedgefield** [comment]
Thanks for the PR Joen, it looks good! I do like the idea of a makeshift logo being generated, kinda like the icons in the plugin directory. I wonder how intuitive it is though for someone just expecting to get a box to upload a logo into. It might be a nice feature to have as a choice: upload your own _or_ let WordPress generate something.

Is the `needs design` tag still on this issue for the 'allow site logo for site icon' flow?

**Comment by mtias** [comment]
The thing that still needs design work is how to present the site icon option.

**Comment by carolinan** [comment]
I pictured that option as a simple toggle in the block settings sidebar. Did you want it in the block toolbar?

**Comment by hedgefield** [comment]
Me too, something like a "Use site logo as icon" checkbox.

**Comment by mtias** [comment]
Definitely in settings, but we should properly explain what it is and we should consider the case when no site icon is set and you upload a logo, should we automatically set icon in such cases or ask users if they also want to use it there?

**Comment by creativecoder** [comment]
Related to these improvements, this seems like a good time to get the logo option name and data type aligned with existing conventions: https://github.com/WordPress/gutenberg/pull/31511

**Comment by jffng** [comment]
Mentioning a small bug fix that will help for removing some logic from theme templates: https://github.com/WordPress/gutenberg/pull/31513

**Comment by hedgefield** [comment]
Thinking about this some more I'm wondering where you would be able to set a site icon in the first place? I know where to find it in the old Customizer, but in FSE there's no block for it because it's not a visible element on the page, and I can't really find it under Templates either...

Ah I see that there's a separate issue for that https://github.com/WordPress/gutenberg/issues/29126. I'll comment there too.

It does sound logical to have some kind of shortcut in the logo block for the site icon, but then I'd rather that is a link to the Site Icon setting itself, otherwise you're controlling two things from two places - like, would the "use logo as site icon" option on the logo block overrule what you set in the site icon option? Complex.

For the explanation, I think we can use the same one that exists in the customizer now:

![Screen Shot 2021-05-06 at 13 40 13](https://user-images.githubusercontent.com/6073772/117292653-c0d9c700-ae70-11eb-8018-7652bb1d4ea3.png)

**Comment by mtias** [comment]
@hedgefield we should at least account for the flow of uploading a site logo when no site icon is set; there should be a way (or maybe it's automatic) to also use that image for the site icon.

**Comment by ajlende** [comment]
Adding cropping in #31607 and updated the description to reflect that.

**Comment by carolinan** [comment]
There is also a problem with the resizing. https://github.com/WordPress/gutenberg/issues/29217

**Comment by hedgefield** [comment]
How's this?

![icon](https://user-images.githubusercontent.com/6073772/117635158-d7896200-b17f-11eb-979b-8927e3d87240.png)

**Comment by jameskoster** [comment]
In https://github.com/WordPress/gutenberg/issues/28341#issuecomment-801911429 I shared a concept that could allow folks to manipulate homepage settings in the midst of an editor session, via modal.

I wonder if there is potential to connect some dots here? IE clicking the "Site icon settings" link in @hedgefield's concept could potentially open the same "Site settings" modal, at a section that contains the site icon configuration options:

https://user-images.githubusercontent.com/846565/117645492-934b9100-b182-11eb-8cf2-a7dd3c595a00.mp4

**Comment by hedgefield** [comment]
That sounds like a proper good idea 👍

**Comment by youknowriad** [comment]
While trying to integrate this block into Core we had feedback about its storage. This is tracked separately here #32065 and is important to land in 5.8. For the remaining improvements tracked on this issue, we should consider them case by case as we're passed the feature freeze date.

**Comment by ramonjd** [comment]
Hello!

I think @stacimc's PR Site Logo: Add option to set site icon from Site Logo block #35892 is working well. I think I'm ready to approve, but it'd be good to get some confidence check 👀 from folks, or maybe @creativecoder (whose name I plucked from https://github.com/WordPress/gutenberg/issues/32065).

Thank you!

**Comment by annezazu** [comment]
Just noting that https://github.com/WordPress/gutenberg/pull/35892 got merged and have checked off that item above. This seems to be the final issue here so wondering if we can close? :) cc @priethor
