### ISSUE TITLE
Improvements to Site Tagline Block

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#30921]
Similarly to the enhancements collected in #30918, the Site Tagline would greatly benefit from the following:

**High priority (target 5.8)**
- [x] General styling option:
  - [x] Letter-spacing (#31118)
  - [x] Margin (#31809)
  - [x] Padding (#31042)
  - [x] Letter-casing (#31042)
- [x] Normalize toolbar

**Low priority**
- [ ] Add an option to link to the site home in the frontend
- [ ] Make the icon more understandable, as it looks very similar to the alignment icon
- [x] Full feature parity with heading block, with fine-grained styling options that require rich text #27830 #30738

**Comment by priethor** [comment]
Thanks for tackling these, @carolinan 🎉

**Comment by carolinan** [comment]
The block only uses `<AlignmentToolbar>`  I don't think there is more to normalize?
![tagline toolbar with one setting and the more options menu.](https://user-images.githubusercontent.com/7422055/118465816-8ee32300-b702-11eb-9609-630846136b6a.png)

**Comment by youknowriad** [comment]
Let's continue improving the blocks but I'm removing this from the 5.8 board as we're passed the feature freeze date. Bug fixes can continue to land though and important iterations (case by case) can be considered.

**Comment by priethor** [comment]
Let's close this issue as the high-priority items are already implemented.
