### ISSUE TITLE
Table: Continued enhancement of color options

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#31261]
Follow-up to https://github.com/WordPress/gutenberg/pull/30791

### Current Situation
The [table block has recently been switched to use block supports](https://github.com/WordPress/gutenberg/pull/30791) to provide greater control over background and text colors.

It was decided that change was a good first step however we need to address some additional issues such as:
- allowing control of table border color
- specifying different colors for table headers and footers
- contrast issues with the striped style
- providing control over secondary background or font colors when striped style is selected

See: https://github.com/WordPress/gutenberg/pull/30791#issuecomment-823815094

### Example Designs Enabled By This

![Frame 61](https://user-images.githubusercontent.com/60436221/123898550-dbc84380-d9a8-11eb-85cf-9ec5d11f63df.png)
![Frame 60](https://user-images.githubusercontent.com/60436221/123898554-dd920700-d9a8-11eb-9a8a-4e390a21ebb4.png)
![Frame 58](https://user-images.githubusercontent.com/60436221/123898558-dec33400-d9a8-11eb-8ef1-ad39ad56f1fa.png)

### Next Steps

The lowest hanging fruit here will be adding control of the border color. We already have border color block support that can be leveraged to achieve this.

Next, adding control over the secondary background and font colors should help to address contrast issues.

Exploring separate color selections for table headers and footers might be the trickiest if we wish to minimise the number of color controls we are adding to the sidebar.

### Tasks
- [x] Add border support ( https://github.com/WordPress/gutenberg/pull/31264 & https://github.com/WordPress/gutenberg/pull/31265 )
- [ ] Add secondary background and font color control
- [ ] Add custom colors for table headers and footers

**Comment by aaronrobertshaw** [comment]
Border support has been added to the Table block via https://github.com/WordPress/gutenberg/pull/31264 & https://github.com/WordPress/gutenberg/pull/31265.

The first PR adds utilities to collect border support CSS classes and styles when skipping serialization. The second uses those to provide border support to the Table block.

**Comment by carolinan** [comment]
Link color should also be enabled.

**Comment by aaronrobertshaw** [comment]
A lot is potentially changing with the Table block including a new version that leverages inner blocks. See:
- https://github.com/WordPress/gutenberg/pull/81593 

This will have larger implications for adoption of block supports and global styles. That said, I think it is best to close this issue for now.
