### ISSUE TITLE
Refine border control panel with design tools

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#31337]
Now that we have border controls (https://github.com/WordPress/gutenberg/pull/30124 🎉) I took a little time to explore how we might apply some of the concepts outlined in https://github.com/WordPress/gutenberg/issues/27331 to refine the UX here a bit. 

Some of the suggestions can be implemented now, others will require underlying components that are yet to be built.

Here's a before / after, and a list of the changes:

<img width="1385" alt="Screenshot 2021-04-29 at 13 48 32" src="https://user-images.githubusercontent.com/846565/116553084-a6906e00-a8f1-11eb-9a4d-525cc2537a45.png">

- [ ] Rename panel to "Border"
- [ ] Removed repetitious "border" copy in labels
- [ ] Re-arranged controls to match css syntax, IE Width → Style → Color
- [ ] Use a segmented control for the style selector (or perhaps just a plain `select`, see https://github.com/WordPress/gutenberg/issues/31333)
- [ ] Use a stepper input for the width control. This one may depend on whether we need to allow users to change the unit from px to em etc.
- [ ] Use the new color control for the color
- [ ] Re-purpose the proposed padding control for border radii (https://github.com/WordPress/gutenberg/pull/31641)

**Comment by karmatosed** [comment]
Goodness this is significantly better to interact with visually, great work. My initial thought after feeling it's just a lot easier to process is that perhaps the order is something to iterate on? I wonder for example if color would come as the last still in the list? Beyond that, I think it's a great iteration.

**Comment by paaljoachim** [comment]
Looking at the Cover block to see how it handles Padding of all sides compared to manually unlocking individual side adjustments.

![Screen Shot 2021-05-04 at 18 10 33](https://user-images.githubusercontent.com/5323259/117035066-31afa080-ad04-11eb-8765-002177a3292d.png)


Here one clicks the lock. (Tool tip is seen.)

![Screen Shot 2021-05-04 at 18 12 05](https://user-images.githubusercontent.com/5323259/117035147-47bd6100-ad04-11eb-9ed5-e4fec3c08d83.png)

Unlocked:
![Screen Shot 2021-05-04 at 18 12 13](https://user-images.githubusercontent.com/5323259/117035203-5441b980-ad04-11eb-80a3-7346af43382b.png)

Should the same method be used for any control that have a similar mechanism? Such as border control.

**Comment by cgaits** [comment]
The After is a better UI/UX as it better aligns with design software UI/UX.

**Comment by aaronrobertshaw** [comment]
Raising some [feedback](https://github.com/WordPress/gutenberg/pull/31366#pullrequestreview-651027251) on the existing border controls here in case it changes anything.

>  It could be confusing to have the width and color controls there when the border style is set to none (or default, depending on defaults), though.

**Comment by jameskoster** [comment]
> Should the same method be used for any control that have a similar mechanism? Such as border control.

If it is easy to re-purpose the existing padding control, that could serve as an interim. Ideally both the padding and border radii controls would be updated to use concepts outlined in #27331.

> It could be confusing to have the width and color controls there when the border style is set to none (or default, depending on defaults), though.

I think the solution here is to not allow a "none" border style. That way the presence of the border is governed entirely by the width control and (hopefully) scope for confusion is reduced.

**Comment by cgaits** [comment]
> Raising some [feedback](https://github.com/WordPress/gutenberg/pull/31366#pullrequestreview-651027251) on the existing border controls here in case it changes anything.
> 
> > It could be confusing to have the width and color controls there when the border style is set to none (or default, depending on defaults), though.

A check-mark and x would also help in choosing a border state, and it would visually guide the user.

**Comment by paaljoachim** [comment]
Pasting in the gif seen in the Dimensions settings area here: https://github.com/WordPress/gutenberg/issues/27331

![100462262-e7c1ef00-30c1-11eb-8274-09eaa3073c3e](https://user-images.githubusercontent.com/5323259/117322374-3e600000-ae8e-11eb-8471-89f5af42ec19.gif)

**Comment by cgaits** [comment]
> > Raising some [feedback](https://github.com/WordPress/gutenberg/pull/31366#pullrequestreview-651027251) on the existing border controls here in case it changes anything.
> > > It could be confusing to have the width and color controls there when the border style is set to none (or default, depending on defaults), though.
> 
> A check-mark and x would also help in choosing a border state, and it would visually guide the user.

I made an example of what would be in my opinion the best for the border state.
![100461228-cc0e1700-30c8-11eb-8ac3-76d353dcc045](https://user-images.githubusercontent.com/12024323/117327031-34bfa380-ae60-11eb-9f62-b99ed770761a.jpg)

**Comment by jameskoster** [comment]
@cgaits it's worth looking at the "Display options" menu in the typography panel designs shared in https://github.com/WordPress/gutenberg/issues/27331: 

<img src="https://user-images.githubusercontent.com/548849/100453148-c578a300-30ba-11eb-8a32-e50bfc2d0888.png">

It could be good to explore extending this heuristic up to the block level, making it possible to toggle panels (color, border, typography, layout) from a centralised interface.

**Comment by cgaits** [comment]
> @cgaits it's worth looking at the "Display options" menu in the typography panel designs shared in #27331:
> 
> ![](https://user-images.githubusercontent.com/548849/100453148-c578a300-30ba-11eb-8a32-e50bfc2d0888.png)
> 
> It could be good to explore extending this heuristic up to the block level, making it possible to toggle panels (color, border, typography, layout) from a centralised interface.

Yes, it is very intuitive and I like it; I was the publisher of a few magazines, including Trivia Times we used to make some heuristic puzzles. Is this a proposition for all WordPress menu items under the Gutenberg full editor?

**Comment by jasmussen** [comment]
> Yes, it is very intuitive and I like it; I was the publisher of a few magazines, including Trivia Times we used to make some heuristic puzzles. Is this a proposition for all WordPress menu items under the Gutenberg full editor?

Most of the details are best outlined on the ticket itself, but it boils down to this:

- Global styles aims to provide themes a way to style most aspects of a page.
- For every such style, a design tool is needed. A design tool can be "font size" or "letter-spacing".
- Both because of the sheer amount of such design tools needed, and out of a need for block inspectors to be user friendly, we need a system that a) allows all blocks to have consistent interfaces that look and behave the same, b) have interfaces that can _curate_ which controls are visible by default, and which aren't.

Ultimately, blocks, and block developers, should only need to declare _support_ for a particular design tool, and not have to do any design work for it to appear in an intuitive and progressively unveiling way.

**Comment by aaronrobertshaw** [comment]
Work toward refining the border block support UI is currently in progress in https://github.com/WordPress/gutenberg/pull/31585.

The designs in this issue required some updates to the underlying block supports mechanism that are still pending review. Any help getting those reviewed will help move this forward.

- [Allow non-pixel units for border width & radius](https://github.com/WordPress/gutenberg/pull/31483)
- [Allow per-corner border radius values](https://github.com/WordPress/gutenberg/pull/31641)

**Comment by aaronrobertshaw** [comment]
@jameskoster the border panel has been updated via https://github.com/WordPress/gutenberg/pull/31585. 

Other than the collapsed color control component I believe everything else is done regarding this issue. The new color control will be picked up by the panel when it is completed. In the meantime, are you happy to close this issue?

**Comment by paaljoachim** [comment]
Hey @aaronrobertshaw 
That sounds great!

I believe that Joen @jasmussen can comment on closing/not closing this issue when he gets back from his vacation, as @jameskoster is on a sabbatical until 8th of September,

**Comment by jasmussen** [comment]
Let's close it! I'm quite sure Jay will reopen if things aren't up to snuff :)
