### ISSUE TITLE
Show "rich" meta data about remote URL when adding URLs as links

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#31466]
## What problem does this address?

Currently when adding a link in the editor, you see a series of results based on whatever you type into the search field. 

<img width="566" alt="Screen Shot 2021-05-04 at 15 24 14" src="https://user-images.githubusercontent.com/444434/117018873-d0300780-acec-11eb-8009-692df32ef9c5.png">

These are _different_ depending on what text you enter and the component tries to "intelligently" discern whether you are:

1. Directly entering a URL 
2. Searching for a WordPress entity (eg: Post, Page, Category...etc).

When you enter a **direct** URL such as `www.wordpress.org` (note the `www.` is required) then the UI simply displays a single result which is a facsimile of what you entered:

<img width="484" alt="Screen Shot 2021-05-04 at 15 26 12" src="https://user-images.githubusercontent.com/444434/117019165-14230c80-aced-11eb-98d6-dca6a6593b9e.png">

This is ok, but it could be better and provide better visual confirmation.

## What is your proposed solution?

I'm proposing we make both:

1. the search results 
2. the selected link details

...a little "richer" by enhancing them with meta data from the remote URL such as:

* `<title>` tag contents.
* favicon/site icon.
* Contents of `<meta name="description" />` tag.

Here's an example of that 

https://user-images.githubusercontent.com/444434/117021116-f656a700-acee-11eb-8199-49cde6c6a626.mov

This would provide a visual confirmation to the user that they have entered a valid URL and that it is the one they are expecting.

Also here is a screenshot showing where we have opportunity to make the selected link details richer:

<img width="678" alt="Screen Shot 2021-05-04 at 15 36 19" src="https://user-images.githubusercontent.com/444434/117021172-04a4c300-acef-11eb-8f82-3ec90a27d212.png">

...for example of how this _could_ look here is what Google Docs shows:

<img width="705" alt="Screen Shot 2021-05-04 at 15 55 24" src="https://user-images.githubusercontent.com/444434/117023703-40d92300-acf1-11eb-8c0e-796c858c6e87.png">

I see this purely as a progressive enhancement - ie: if we cannot enhance the given entry then we simply display the experience as it is now. However, if we do manage to get data then we can enhance the search result.

We already have the [REST API endpoint](https://github.com/WordPress/gutenberg/pull/18042) to get the data (I'm [currently working on making it return more data](https://github.com/WordPress/gutenberg/issues/27762)) so it's about wiring things together and getting a good UX design.

## Todo

- [ ] [Enhance link control UI with remote URL data #31464](https://github.com/WordPress/gutenberg/pull/31464)
- [x] [Add REST API endpoint to retrieve data about a remote URL](https://github.com/WordPress/gutenberg/pull/18042).
- [ ] [Improve REST API endpoint parsing to retrieve more data and improve stability](https://github.com/WordPress/gutenberg/issues/27762).

**Comment by getdave** [comment]
@javierarce I think this could be a really nice enhancement. I wonder would you be able to help with the Design UX here?

**Comment by skorasaurus** [comment]
ref https://github.com/WordPress/gutenberg/issues/27762

**Comment by javierarce** [comment]
@getdave I love the idea! I'll help you with the design.

**Comment by getdave** [comment]
https://user-images.githubusercontent.com/444434/117031687-bdbbcb00-acf8-11eb-8892-26bca208db9b.mov

Here's an example of use fetching details for the link _preview_ to provide a richer experience.

Obviously, it has some glitches, but essentially you see the `url` (which is what we store in the Gutenberg data) whilst the request goes out to fetch the "rich" data. Once that request completes then the UI updates to show the "rich data".

I'm experimenting in https://github.com/WordPress/gutenberg/pull/31464

**Comment by javierarce** [comment]
Here's a first iteration for this feature's design:

<img width="2488" alt="Design@2x" src="https://user-images.githubusercontent.com/4933/117167558-a697de80-adc7-11eb-8161-b5f467fd8e41.png">

The most notable changes I'm introducing are:

- In the current design, the URL that the user is about to add is contained inside a card whose background changes on hover. I think we could get rid of the effect and highlight the title instead (that said, I explored a couple of variations [here](https://www.figma.com/file/OXOmvYcX0Gpwgt7FB5LlKA/?node-id=20%3A3660))
- I've also removed the icon that indicates that a link will get open on a new page. I think this would add a lot of noise in a section containing an avatar and the edit button.

I'm a bit unsure about the "Press ENTER to add this link" help text. I think it works fine when there isn't an image, but when there's one, it gets kind of sandwiched between the image and the title. 

Here's a video of [this Figma prototype](https://www.figma.com/proto/OXOmvYcX0Gpwgt7FB5LlKA/Rich-URL-metadata?page-id=14%3A1429&node-id=14%3A1846&viewport=-1165%2C-964%2C1.3139586448669434&scaling=min-zoom) that shows the different variations depending on what kind of data is available

https://user-images.githubusercontent.com/4933/117170065-f677a500-adc9-11eb-8719-f82a4b24cd56.mov

**Comment by javierarce** [comment]
Ok, here's the first iteration of this feature's design. 

This is the basic add flow where the user searches for an item and we show a list of results. If the text happens to be an URL, we fetch the metadata and render a card (at this point, I wonder if it would be OK to fetch the metadata when the search term doesn't begin with `www.`)

<img width="681" alt="Steps" src="https://user-images.githubusercontent.com/4933/117199564-9f35fc80-adea-11eb-9a78-7fdfe9422b59.png">

The most notable changes I'm introducing are:

- In the current design, the items from the autocomplete are contained inside a card whose background changes on hover. I think we could get rid of the effect and highlight the titles instead (that said, I've explored a couple of variations [here](https://www.figma.com/file/OXOmvYcX0Gpwgt7FB5LlKA/?node-id=20%3A3660))
- I've also removed the icon that indicates that a link will get open on a new page. I think this would add a lot of noise in a section containing an avatar and the edit button.

Here are a table with the possible variations depending on what kind of data is available:
 
<img width="2132" alt="Design" src="https://user-images.githubusercontent.com/4933/117197764-8298c500-ade8-11eb-82c1-5e5e975f4c07.png">

I'm a bit unsure about the `Press ENTER to add this link` help text. I think it works fine when there isn't an image, but when there's one, it gets kind of sandwiched between the image and the title. 

[This Figma prototype](https://www.figma.com/proto/OXOmvYcX0Gpwgt7FB5LlKA/Rich-URL-metadata?page-id=14%3A1429&node-id=14%3A1846&viewport=-1165%2C-964%2C1.3139586448669434&scaling=min-zoom) lets you play with the different types of cards. 

https://user-images.githubusercontent.com/4933/117170065-f677a500-adc9-11eb-8719-f82a4b24cd56.mov

**Comment by getdave** [comment]
@javierarce This is really great - thanks so much for this work and insight.

I like the way the different card options allow for a progressively enhanced approach with increasing levels of fidelity. This is very important as it's not guaranteed that we can fetch metadata in every case.

For a v1 I'm going to propose we go with `Favicon + Title + Description`. This should be easy enough to parse by enhancing the existing endpoint. I'm thinking grabbing a suitable image will be more difficult so that could a v2 enhancement - I really like the way it looks. Do you agree?

I'll start by enhancing the existing REST API endpoint and then try to pull some of that work into https://github.com/WordPress/gutenberg/pull/31464 which is a PoC PR which already does _some_ of what you are planning here.

**Comment by javierarce** [comment]
> For a v1 I'm going to propose we go with Favicon + Title + Description. This should be easy enough to parse by enhancing the existing endpoint. I'm thinking grabbing a suitable image will be more difficult so that could a v2 enhancement -

That's perfect!

**Comment by getdave** [comment]
I'm currently working on improving the endpoint parsing capabilities in https://github.com/WordPress/gutenberg/pull/31763
