### ISSUE TITLE
Refining the Template Part block(s)

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#31750]
Now that template parts can be associated with semantic `area`s like "Header" and "Footer" several opportunities to leverage this and improve the UX emerge:

- [ ] Expose existing Template Parts in the Inserter (https://github.com/WordPress/gutenberg/issues/31748)
- [x] Colorise template part instances (initially proposed in https://github.com/WordPress/gutenberg/issues/26599)
- [ ] https://github.com/WordPress/gutenberg/issues/38908
- [ ] https://github.com/WordPress/gutenberg/issues/29296
- [ ] Creating a from scratch template part via the Inserter (https://github.com/WordPress/gutenberg/issues/31746)
- [x] Polish the swapping interface for template parts (https://github.com/WordPress/gutenberg/issues/31747)
- [x] Provide a way to view block patterns that are contextually relevant to the selected Template Part – #28737
- [x] Contextual icons for template parts (https://github.com/WordPress/gutenberg/issues/31749)

**Comment by mtias** [comment]
I think this is mostly done and we don't need a tracking issue for the left overs.
