### ISSUE TITLE
Mobile: Display issues observed on iPhone 6s in Safari

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#3197]
## Issue Overview

I spent some time testing Gutenberg version ~~1.5.1~~ 1.9.0 on my mobile device. This issue contains all visual flaws that I believe they are worth to be further investigated.

## Steps to Reproduce (for bugs)

Open Gutenberg on iPhone 6s in Safari, iOS 11.0.3.

## Expected Behavior

Everything should be displayed properly on mobile. Mobile gestures should be applied properly even for embeds. They shouldn't take over control.

### ~~Menu icon overlaps inserter~~ WordPress.com only
It is not possible to click on the inserter in the top menu.

![image](https://user-images.githubusercontent.com/699132/32100919-143cfab8-bb16-11e7-83b7-ca1893b59708.png)

### Publish button rendered partially off the screen

When trying to publish a post the dropdown is partially displayed off the screen, making it really hard to use it. 

![image 2](https://user-images.githubusercontent.com/699132/32100920-14568852-bb16-11e7-8e41-9b4d91a8178a.png)

### ~~Advanced settings menu is squeezed~~ Fixed

It seems like the advanced settings menu is squeezed, we might consider making it wider.

![image 3](https://user-images.githubusercontent.com/699132/32100921-146fdadc-bb16-11e7-9c17-27bf6e9dabea.png)

### Inserter's popover renders needs polishing

There are 2 issues here. When you click the inserter button screen scrolls up/down. It doesn't fit the screen and isn't positioned horizontally as expected. It seems like popover could have smaller block items.

![image 4](https://user-images.githubusercontent.com/699132/32100922-148a0e02-bb16-11e7-9899-869c5e890a01.png)

It also doesn't play well with the image that is aligned.

<img width="364" alt="screen shot 2017-12-12 at 10 24 21" src="https://user-images.githubusercontent.com/699132/33876748-ad4a3ebc-df26-11e7-9a9a-bf7867d8cb00.png">

### Anchor's popover displays partially off the screen

Sometimes it is displayed partially behind visible area on the left, sometimes on the right.

Another thing is that I would prefer to see the icon to remove the link as the last item. I removed 2 or 3 times link because I somehow assumed it should be the very far item on the list :)

![image 5](https://user-images.githubusercontent.com/699132/32100923-14a217ae-bb16-11e7-9c75-1e0012d4d445.png)

### ~~Block toolbar partially visible when focus on the end of the block~~ Much better now

It seems like the toolbar for the block should be visible all the time. At the moment when you scroll down, it is still partially visible.

![image 6](https://user-images.githubusercontent.com/699132/32100924-14bbdd1a-bb16-11e7-93fb-c6008386d29d.png)

### ~~Tooltip for advanced setting stays when sidebar activated~~ Fixed

There are two issues here: it should disappear completely as soon as focus goes to the sidebar. It is still displayed and has z-index set in a way that makes it overlap the sidebar. When you scroll in the sidebar this tooltip is positioned in the same place all the time.

<img width="375" alt="image 7" src="https://user-images.githubusercontent.com/699132/32100925-14d5002e-bb16-11e7-9beb-03327f3c6055.png">

### ~~No option to go back to visual mode~~ Fixed

When you start editing as HTML, there is no way to go back to visual mode.

<img width="375" alt="image 8" src="https://user-images.githubusercontent.com/699132/32100926-14f0d20e-bb16-11e7-8dee-916fa2951d4c.png">

### ~~Embeds need some love~~

First of all. It's very easy to trigger tap event on the embed. I don't think it should be possible, as this trigger page redirect, a video starts playing or any other random action happens.

There is also another issue related to that. Embeds often take over control over phone gestures. To give an example of youtube - it scrolls independently to the editor and makes some editor's content to disappear at that time. It also scrolls the screen left or right leading to very bad experience. I think we should consider disabling all gestures from the embed and only handle whatever Gutenberg need to handle.

<img width="375" alt="image 9" src="https://user-images.githubusercontent.com/699132/32100927-150b00d4-bb16-11e7-92ce-ac3c380be80b.png">

### Tasks
- [x] Menu icon overlaps inserter - WordPress.com only
- [ ] Publish button rendered partially off the screen
- [x] Advanced settings menu is squeezed
- [ ] Inserter's popover renders needs polishing
- [ ] Anchor's popover displays partially off the screen
- [x] Block toolbar partially visible when focus on the end of the block
- [x] Tooltip for advanced setting stays when sidebar activated
- [x] No option to go back to visual mode
- [x] Embeds need some love

**Comment by RickorDD** [comment]
What generally interests me for the Gutenberg future,  good responsive View by Phones or a native app? 
The Wordpress APP currently has no good usability. 
Is React Native a good answer?

**Comment by gziolo** [comment]
6 out of 9 items were resolved. I opened 3 issues for the remaining bugs. We can close this one.
