### ISSUE TITLE
Flex Layout Iterations

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#33687]
In https://github.com/WordPress/gutenberg/pull/33359 we added the possibility for blocks to support multiple layouts: the default "flow" layout and the new "Flex" layout. In the future, we'll be also introducing other layouts like "Grid" or "Absolute positioning  container"...

**What is a layout?** 

A layout is a configuration you apply to a container block that changes how its inner blocks are aligned, and also impacts the behavior of these inner blocks (enable/disable some customization options). Right now, we have two types of "layouts" we can apply to container blocks:

 - **Flow layout**: This is the default behavior in HTML, meaning if you apply this to a container block, its children are rendered one after the other vertically without any specific CSS styles (it works just like adding divs inside divs). Blocks inside a flow container can be left/right aligned (float) and in this type of layout, you have the possibility to define a "content size" and a "wide size", by defining these, the inner blocks get centered by default inside the "content size" area and they receive new alignments options (full/wide alignments) 

 - **Flex layout**: This is a layout where the container receives a `display: flex` style. Right now it's opinionated, meaning the inner blocks are positioned horizontally one after the other with a small gap between each block. No alignment options are available for inner blocks inside a "flex container". That said, it is likely that we'll be introducing a number of customizations for this kind of layout. For instance, we could add a config to choose whether the blocks are horizontal or vertical (some argued that flex should be only used for horizontal alignments but it's something we should discuss more). Another option could be the "gap" size, `align-items` could also be a config option for the layout itself. For the children of this particular layout, we could potentially explore adding positioning tools (like align-self and such). 

**Layout switching**

Generic container blocks like the group are most likely going to require a layout switcher UI to allow users to switch layouts and configure its specific options.

Right now, the initial prototype from #33359 contains a very basic undesigned layout switcher that you can enable by replacing [this line](https://github.com/WordPress/gutenberg/blob/e0de351b0b713eb2f7fcec4687616f2a9bf73604/packages/block-library/src/group/block.json#L35) with:

```
"__experimentalLayout": {
	"allowSwitching": true
}
```

You'll get something like:

![125345906-1aee8100-e327-11eb-8d48-95ddf1386281](https://user-images.githubusercontent.com/272444/126960328-78d830dd-41f0-4c8a-9079-3d01a9e27038.gif)

This area is going to require a better design/wording...

**Refactoring blocks to use declarative layouts**

Historically, we've added a number of flex horizontal container blocks over time like: Social Links, Buttons, Columns and Navigation blocks. But we did so in a very ad-hoc way, meaning we just added custom CSS and custom customization options to these blocks. Now that we introduced the "layout" config  and the "flex layouts", we should consider refactoring some of these blocks to be more declarative and remove the specific treatment we have right now for these blocks.

One technical issue that needs solving though to do that is that right now, the **layout** block support renders styles in the editor by using the `__experimentalLayout` prop of the `userInnerBlocksProps` call, but in frontend it relies on the `layout` block attribute. For the editor, the current APIs should be enough but for the frontend, these blocks might not allow users to tweak their "layout", meaning the `layout` attribute might or might not be necessary. We need to find a declarative way in block.json to define the "default layout" of a container block.

**Todo List**

In terms of design, we need a couple of explorations:

 - [x] Design a good layout switcher.
 - [x] What customization options are going to be needed for the Flex layout. Design the flex container config panel.
 - [ ] Should we allow align-self positioning tools for children of flex containers? How to surface these?

In terms of architecture:

 - [x] Refactoring existing horizontal blocks to use the new flex layout.
 - [ ] Write some architecture documentation for contributors about the layout and layout types.

**Comment by mtias** [comment]
Do we need to establish some criteria for when Flex is better over Grid?

**Comment by youknowriad** [comment]
I didn't think much about the Grid layout yet but it seems that "Flex" is easier/simpler when it comes to basic vertical blocks (social icons, navigation, buttons) but Grid would be a better choice for "page layouts", so an option on a generic container/group block (or variation) that you apply at the top level of your template.

I think what we're missing right now to start exploring Grid, is better understanding/exploration on what needs to be configured at the container level and what alignment/config options to expose on the child blocks. Maybe @jasmussen could help with that a bit. I think we could use a separate issue about the Grid layout to answer these questions:

 - When I apply a "grid" layout to a block, what config options can I have on that block?
 - What config options I have on its children?
 - How does a "grid" layout impact the UI and possible interactions on the inner blocks?
 - Potentially some design mockups about the questions above.

**Comment by mtias** [comment]
I think the important aspect is that it's not just a different layout property and it's more about who has more control, the parent block or the child blocks when laying things out. And that's something we should take into account early on since it can dictate the kind of tools that get exposed and where (in the container toolbar/inspector or the children toolbar/inspector). Also [relevant](https://twitter.com/KevinJPowell/status/1419347131719200771).

**Comment by ghost** [comment]
I really like where this is going. From a UX perspective, I think that Webflow does an excellent job with their Grid/Flex layout interfaces.

**Comment by richtabor** [comment]
I riffed on some ideas as part of a big-picture proposal for the Group block's layout panel. Thoughts? https://github.com/WordPress/gutenberg/issues/34558

**Comment by mtias** [comment]
@youknowriad where do you think we stand with this one after the latest work on Row, Stack and the transforms menu like https://github.com/WordPress/gutenberg/pull/40036 ?

**Comment by youknowriad** [comment]
I think in terms of features for the flex layout itself, we're mostly there. Maybe the only potential addition could be this:

>  Should we allow align-self positioning tools for children of flex containers? How to surface these?

Similar to how "alignments" appear when you chose a "flex" layout for the container, specific flex alignment options could appear in child blocks when you select "flex" as their container. 

That said there are a number of issues in terms of "architecture". Right now, some blocks have "align" block support which only works if container is "flow" and it works by adding an "align" attribute to the block. There are several things we should improve here:

 - "align" is not a reserved attribute name and the framework (block-editor) don't really know anything about it. Some blocks might implement the same behavior using a different attribute.
 - "align" is also not something that translates well in all kind of layouts, I'd love for that attribute to be named something like "position" (or maybe "_position" to avoid collisions with existing third-party attributes) and be understood by the framework. The attribute could store the "alignment" in case of a "flow" parent, and when you move the block to another container that is "flex", it should reset itself. In other words, the "position" attribute only make sense in the context of a given layout container. I hope that makes sense. That said It's also fine to track this separately as it's a tangent here.

**Comment by jasmussen** [comment]
One small addition is to consider a matrix-grid like alignment tool, a la what the Cover block has already, for flex containers that allow both vertical and horizontal alignments. Probably worth its own separte issue?

**Comment by mtias** [comment]
For self-positioning?

**Comment by jasmussen** [comment]
Row now has both horizontal and vertical alignments for children in the block toolbar, but not in the inspector:

<img width="1392" alt="Screenshot 2022-04-11 at 11 36 59" src="https://user-images.githubusercontent.com/1204802/162710975-32311128-d8e1-47e3-8081-94197cfc317c.png">

We could potentially use the same interface the Cover block has for aligning. Instead of setting horizontal and vertical separately, it can be a single 9-cell matrix.

**Comment by youknowriad** [comment]
@jasmussen I'm not sure that interface make sense. What's "center": "justify center" or "space between"?

**Comment by jasmussen** [comment]
This is how Figma handles it:
![figma](https://user-images.githubusercontent.com/1204802/162723846-43a9c548-287d-4b78-b036-d2d1c282fb49.gif)

I recognize the dropdown to choose between "packed" and "space between" isn't the most intuitive. Mostly it's the discrepancy between the vertical tools being available in the block toolbar, but not in the inspector, and if we add them to the inspector as well, we should try to avoid this:

<img width="364" alt="to avoid" src="https://user-images.githubusercontent.com/1204802/162724748-2b3404c6-35d9-4c07-bd74-3df86d41ab64.png">

One alternative is to also have dropdowns in the inspector:
<img width="688" alt="Alternative" src="https://user-images.githubusercontent.com/1204802/162725703-da8bfd6e-2bb3-4f09-a710-0b9dadb26757.png">

That just doesn't feel quite as natural as the behavior that exists for Cover, though. 🤔

**Comment by mtias** [comment]
I was talking about self-align, though — so you can place something at the top of a cover, something else at the bottom, etc, which is not possible with the matrix control on the parent.

**Comment by jasmussen** [comment]
Depending on how many of the flex properties we want to support, it can quickly become a lot. Two options:
<img width="688" alt="One idea" src="https://user-images.githubusercontent.com/1204802/162727524-faa40e33-47ea-494d-9cc0-f6f5eab81eda.png">

**Comment by youknowriad** [comment]
@jasmussen orientation doesn't make sense for individual blocks inside a container, justify might not make sense either.

**Comment by jasmussen** [comment]
Right of course, so potentially this; layout container:
<img width="688" alt="Container" src="https://user-images.githubusercontent.com/1204802/162729647-7fa70c6b-dc0d-46e9-8616-ec2f174224f5.png">

Inner block, with justification shown or hidden depending on the block:

<img width="364" alt="Inner block" src="https://user-images.githubusercontent.com/1204802/162729868-e1ccac73-0f28-4e80-89f9-c5cb822797b0.png">

Something like that for a start?

**Comment by youknowriad** [comment]
Yes, I also wonder if it should be on the toolbar. Conceptually it's the alternative to "align left/right/wide/full" that we have for children of "flow" layouts.

**Comment by jasmussen** [comment]
Good point, and it illustrates a challenge with the iconography. When the justification icons are used both for inner blocks, and for _self_, it becomes unclear what they apply to.

I don't like the following icons, consider them placeholders to illustrate how "align self" icons might need to be different from "justify content" icons. Potentially we keep the group block toolbar simple:
<img width="364" alt="Container group" src="https://user-images.githubusercontent.com/1204802/162735950-96da09cc-8378-40b1-bd9f-898ea7644b4a.png">

And then you're suggesting some new align-self options in inspector and block toolbar for inner groups, right? Perhaps something like this:

 
<img width="364" alt="Inner group" src="https://user-images.githubusercontent.com/1204802/162736047-ba5046e8-e1b4-4b23-95cf-a9f60dfe7226.png">

**Comment by mtias** [comment]
@youknowriad do you see anything pending here? I think maybe some of the self-align options, which also overlap with the matrix control, but I think it'd be better to extract that into a separate issue. I feel the core work is done here.

**Comment by youknowriad** [comment]
@mtias 👍 Let's close and do a separate one about self align.
