### ISSUE TITLE
Block drag and drop tracking issue

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#33683]
## Prioritised list of tasks (good to aim for in WP 6.5)

If possible, it'd be good to fix or explore solutions for the following for WordPress 6.5.

* [x] https://github.com/WordPress/gutenberg/issues/56463
* [x] https://github.com/WordPress/gutenberg/issues/56182
* [x] https://github.com/WordPress/gutenberg/issues/13202
* [x] Drag images onto image block to make a gallery ([Images: Support for drag-and-drop multiple images onto image block #9783](https://github.com/WordPress/gutenberg/issues/9783), [Use drag and drop to transform an Image block → Gallery block #32819](https://github.com/WordPress/gutenberg/issues/32819))
* [x] https://github.com/WordPress/gutenberg/issues/24174
* [x] https://github.com/WordPress/gutenberg/issues/26049
* [ ] https://github.com/WordPress/gutenberg/issues/54952
* [x] https://github.com/WordPress/gutenberg/issues/33684
* [x] https://github.com/WordPress/gutenberg/issues/33686

----

## Full list including nice to haves / tracking

The issues below have not been prioritised, but anyone is free to pick up a task of course!

## Bugs

- [ ] No drop indicator shown when dragging into an empty (e.g. group/column) block list (Reported in #32880), #44064
- [x] #28790
- [x] #33678
- [x] #29511
- [x] #24173

### General

- [x] https://github.com/WordPress/gutenberg/issues/56182
- [x] #24174
- [x] Allow for more space around drop zones (#32438, #26049, https://github.com/WordPress/gutenberg/issues/55474)
- [ ] #29931
- [ ] #24750
- [x] #33685
- [x] #33684
- [x] #33686
- [ ] #54952
- [ ] https://github.com/WordPress/gutenberg/issues/36457

### Block-specific drag and drop enhancements

- [x] #13202
- [ ] Drag images onto image block to make a gallery (#9783, #32819)
- [x] #32820
- [x] #18501
- [x] #29145

## Performance

- [ ] #33435
- [x] #33478

## Automated tests

- [x] #31356
- [ ] Add more e2e tests for drag and drop (drop/insertion point positioning, nesting, etc.)

## API

- [ ] Make `useDropZone` stable (#14335)

## Needs feedback or some other kind of progress

- [ ] Improve scroll while dragging behavior (#24770)
- [ ] Dragging blocks with 'top-toolbar' mode enabled (#20078, #25237)
- [x] #20762

**Comment by jasmussen** [comment]
One suggestion left in a comment is to default all nesting groups to closed by default, and persist that state between opening and closing the list view panel. If you then select a nested block in the canvas, the list view if open should expand that tree view, potentially even scroll to it. Are any aspects of this behavior tracked? The scrolling bit I feel has been discussed somewhere. Happy to open a new ticket if need be.

**Comment by ellatrix** [comment]
@talldan It seems most issues here are addressed. Could we close this, and maybe move any remaining important items to #63255?
