### ISSUE TITLE
EDITOR_SETTINGS_DEFAULTS makes it impossible to hide the custom fields toggle

### ISSUE THREAD

**Issue by mreishus** [WordPress/gutenberg#33830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Summary

The "Custom Fields" settings is designed to be hidden by an editor setting set in WP.org core PHP code, however it cannot be hidden, due to these factors:
  * gutenberg JS strictly checks for an undefined value
  * If PHP sends a null or false value, those don't match a === check against undefined
  * If PHP does not send a value, gutenberg's default settings apply a false to the value, which is also !== undefined.

Therefore, to hide the "Custom Fields" setting, it wants an undefined to be sent in `getEditorSettings().enableCustomFields`, but it is impossible to send one.

### Field In Question

Visit the Post Editor -> Click the three dots menu in the top right -> Click preferences at the bottom -> A modal appears -> Click the Panels section on the left side -> See a "custom fields" toggle.
![2021-08-05_10-08](https://user-images.githubusercontent.com/937354/128374349-c43cfb86-5158-40fc-b8b8-6f7ab95fed15.png)

### Mechanism

* This toggle has a mechanism for it to be hidden in some circumstances. If `getEditorSettings().enableCustomFields === undefined`, then it is hidden. [Code 1](https://github.com/WordPress/gutenberg/blob/333668e7149a1f3f2a39810372ecb11422fe4f7c/packages/edit-post/src/components/preferences-modal/meta-boxes-section.js#L57-L58), [Code 2](https://github.com/WordPress/gutenberg/blob/333668e7149a1f3f2a39810372ecb11422fe4f7c/packages/edit-post/src/components/preferences-modal/meta-boxes-section.js#L31).
  * I am ignoring the metaBoxes condition here. It works fine and it doesn't need to be examined for this bug.
* WP.org core code takes care of setting the `enableCustomFields` editor setting.
  * Most of the time, it comes from a [user meta setting](https://github.com/WordPress/WordPress/blob/9a4280c75f7bf76062b61207e3ecdb3a0e0f298e/wp-admin/edit-form-blocks.php#L199).
  * [In some circumstances, it is unset,](https://github.com/WordPress/WordPress/blob/9a4280c75f7bf76062b61207e3ecdb3a0e0f298e/wp-admin/edit-form-blocks.php#L261) which I take to mean it should be hidden completely.
    * This is the clause being run on WP.com (which uses an unmodified version of this file from WP.org core). It does not support this feature and wants the toggle to be hidden.
    * The guard clause in `meta-boxes-section.js` checks for `getEditorSettings().enableCustomFields === undefined`, so this seems like a perfect match.  However, [its state is initialized with a default value of false](https://github.com/WordPress/gutenberg/blob/333668e7149a1f3f2a39810372ecb11422fe4f7c/packages/editor/src/store/defaults.js#L30), so if php does not send a value, false is the value seen by `meta-boxes-section.js`. PHP does not have `undefined`, it has `null`, but that's not sufficient to pass the check.

| WPORG edit-form-blocks.php $editor_settings['enableCustomFields'] | gutenberg meta-boxes-section.js getEditorSettings().enableCustomFields  | notes |
| --- | --- | --- |
| true | true | |
| false | false | |
| null | false | ☹️ |
| *(used unset() to remove value)* | false | ☹️ |
| "1234" | "1234" | |
| 1234 | 1234 | |
| | undefined | this is what we need, but it seems impossible |

### Step-by-step reproduction instructions

1. Have a WordPress.org installation.

2. Create `wp-content/plugins/disable-custom-fields.php`
```php
<?php
/**
 * Plugin Name: Disable Custom Fields
 * Plugin URI: http://www.mywebsite.com/disable-custom-fields
 * Description: Disable Custom Fields
 * Version: 1.0
 * Author: Your Name
 * Author URI: http://www.mywebsite.com
 */

add_action( 'add_meta_boxes', 'plugin_disable_custom_fields', 1 );

function plugin_disable_custom_fields() {
    remove_post_type_support( get_post_type(), 'custom-fields' );
}


add_action( 'do_meta_boxes', 'plugin_meta_boxes', 10, 2 );

function plugin_meta_boxes( $page, $context ) {
    remove_meta_box( 'postcustom', get_post_type(), 'normal' );
}
```

3. Visit /wp-admin and activate this plugin.
4. Visit post editor on WordPress.org site. With this plugin enabled, [this if condition will always trigger](https://github.com/WordPress/WordPress/blob/9a4280c75f7bf76062b61207e3ecdb3a0e0f298e/wp-admin/edit-form-blocks.php#L260), and [the `unset( $editor_settings['enableCustomFields'] );` always runs](https://github.com/WordPress/WordPress/blob/9a4280c75f7bf76062b61207e3ecdb3a0e0f298e/wp-admin/edit-form-blocks.php#L261).
5. Click the three dots menu in the top right
6. Click "preferences" at the bottom
![2021-08-05_10-07](https://user-images.githubusercontent.com/937354/128374126-c22ad772-d02f-4df4-9c4b-bb9be3748a71.png)
7. A modal appears. Click Panels on the left
8. Turn on "Custom Fields"
![2021-08-05_10-08](https://user-images.githubusercontent.com/937354/128374210-5d7311eb-6073-4ffa-8fd5-6754ac3c5aa3.png)
![2021-08-05_10-08_1](https://user-images.githubusercontent.com/937354/128374223-df55a53c-b4ae-4261-b664-b256ee202d28.png)
9. See message asking to enable and reload, click the button
10. Page reloads
11. Re-visit the custom fields setting, see that it is turned off. (Expected to see: The entire "Custom Settings" option does not appear, because `$editor_settings['enableCustomFields']` is unset [by this core code](https://github.com/WordPress/WordPress/blob/9a4280c75f7bf76062b61207e3ecdb3a0e0f298e/wp-admin/edit-form-blocks.php#L261).)
![2021-08-02_13-33_1](https://user-images.githubusercontent.com/937354/127907927-3beac46c-8127-4675-bd71-ece924a1bdbe.png)

### Expected Behavior

Expected to see: The entire "Custom Settings" option does not appear, because `$editor_settings['enableCustomFields']` is unset [by this core code](https://github.com/WordPress/WordPress/blob/9a4280c75f7bf76062b61207e3ecdb3a0e0f298e/wp-admin/edit-form-blocks.php#L261), and the display of the field is guarded by `enableCustomFields` being `undefined`: [part1](https://github.com/WordPress/gutenberg/blob/333668e7149a1f3f2a39810372ecb11422fe4f7c/packages/edit-post/src/components/preferences-modal/meta-boxes-section.js#L57-L58), [part2](https://github.com/WordPress/gutenberg/blob/333668e7149a1f3f2a39810372ecb11422fe4f7c/packages/edit-post/src/components/preferences-modal/meta-boxes-section.js#L31-L32).

### Current Behavior

Actually see: The "Custom Settings" open does appear, even if I do my best to make `$editor_settings['enableCustomFields']` undefined.

I believe it's because [the default settings](https://github.com/WordPress/gutenberg/blob/333668e7149a1f3f2a39810372ecb11422fe4f7c/packages/editor/src/store/defaults.js#L30) ensure that `enableCustomFields` becomes false if not set. I highly suspect it's impossible to send `$editor_settings['enableCustomFields'] === undefined` to gutenberg, because the defaults kick in and always overwrite unset values with `false`, the default, and php does not have an undefined value, only null or not set at all.

**Comment by skorasaurus** [comment]
related https://github.com/WordPress/gutenberg/issues/31848

**Comment by mreishus** [comment]
Updated steps to include adding short plugin to a fresh wp.org install instead of editing core files.

**Comment by mreishus** [comment]
I believe this requires coordination between Gutenberg and WordPress.org. I have opened PRs on both that fix the problem in conjunction.

* Trac issue: https://core.trac.wordpress.org/ticket/53883
* wordpress-develop PR: https://github.com/WordPress/wordpress-develop/pull/1548
* Gutenberg issue: https://github.com/WordPress/gutenberg/issues/33830
* Gutenberg pr: https://github.com/WordPress/gutenberg/pull/33912
* Gutenberg PR (alt): https://github.com/WordPress/gutenberg/pull/33931
