### ISSUE TITLE
Template Part Focus Mode

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#33926]
This issue tracks short-term work to be done on what has been referred to as "isolated template part" mode. This is a view that just focuses on a single template part (like a header) and is available for any template part. It also outlines the role this will play as part of turning existing widget areas into block template parts. This last part is only tentatively written and is not scoped out pending research on both the widgets work and the navigation screen work.

Design overview: #29148.

- [x] The editor canvas should isolate the Template Part (visually inset on the canvas to illustrate its boundaries).
  - [x] Have a clear way to go back / out of the focused view. (https://github.com/WordPress/gutenberg/pull/34732)
  - [x] Ensure canvas height matches contents. (https://github.com/WordPress/gutenberg/issues/35512)
- [x] #35249
- [x] Isolated template part editing should be accessible from:
  - [x] List view as an icon button.
  - [x] The Ellipsis in the Template Part toolbar. (#34679)
  - [x] The Sidebar Menu.
- [x] The Template Part name should be visible in the Top Bar, mimicking the Template editing UI. #35202
- [x] #29687
- [x] Template parts that are assigned to _areas_ should use the relevant area icon (header, footer, sidebar). #35202
- [x] Clicking the gray background should deselect blocks. #35753
- [x] ~In the Inspector, the settings for the Template Part should be visible in the document tab. (Relevant #30641.)~

## Followups

Once the internal UX of editing template parts isolated from their containing template is in a good place, research should continue on how should existing widget areas transition to more ergonomic template parts.

**Comment by draganescu** [comment]
> The canvas should be resizable with a drag handle. (See pattern directory previews.)

@mtias / @jameskoster what is the use of this handle to resize? I see in later designs in #29148 that it went away.

**Comment by mtias** [comment]
We want to introduce viewport resizers through template parts to then scale it up to the whole editor for responsive previewing. (Similar to the pattern directory.)

**Comment by noisysocks** [comment]
Hi! @kevin940726 and I are going to start working our way through this list.

Quick question: What do you mean by "should be accessible from ... The Sidebar Menu"? What is the sidebar menu?

**Comment by draganescu** [comment]
> What is the sidebar menu?

It's the menu that appears when clicking the "W" logo when editing a block theme.

**Comment by kevin940726** [comment]
> > What is the sidebar menu?
> 
> It's the menu that appears when clicking the "W" logo when editing a block theme.

Oh okay I guessed it wrong 😅. I thought it's the right sidebar (inspector).

Isn't the editor already accessible in the sidebar menu then?

**Comment by mtias** [comment]
Yes, it was checked in the list but seems to have been unchecked since :)

**Comment by kevin940726** [comment]
> In the Inspector, the settings for the Template Part should be visible in the document tab.

As mentioned in https://github.com/WordPress/gutenberg/issues/30641#issuecomment-944043239, I don't think this is possible now. I think we should mark it as `wont-fix` until we have a proper solution to the underlying architecture?

**Comment by noisysocks** [comment]
>  List view as an icon button.

I checked this one off now that https://github.com/WordPress/gutenberg/pull/35170 is merged meaning you can edit a template part via the ellipsis button in a List View. Perhaps we can revisit having a dedicated icon after WP 5.9.

**Comment by noisysocks** [comment]
I think we can close this out now that https://github.com/WordPress/gutenberg/issues/35512 is merged. No doubt there's plenty more to iterate on but I think things are in good shape for WP 5.9. Really nice work @kevin940726 and @jameskoster! ❤️🎉

**Comment by mtias** [comment]
Excellent!
