### ISSUE TITLE
Component: `LinkControl` tracking issue

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#35073]
The [`LinkControl`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/link-control/README.md#link-control) Component was added via #17557 as an experimental component in September 2019. 

This Tracking issue is here to keep track of the items that are needed to get the Component out of the `experimental` state.

See also the [Link UI Overview Issue](https://github.com/WordPress/gutenberg/issues/49091) which tracks currently priorities.

### High Priority
- [ ] https://github.com/WordPress/gutenberg/issues/50891
- [ ] https://github.com/WordPress/gutenberg/pull/56384

### Medium Priority
TBD

### Low Priority
TBD

---

### Enhancements
- [x] #13542
- [ ] #31496
- [x] #23011
- [ ] #22833
- [ ] #22442
- [ ] #22439
- [x] #22438
- [x] #22437
- [ ] #21343
- [ ] #19526
- [x] #21905
- [x] #26351
- [x] #26317
- [x] #25414
- [x] #24753
- [x] #31482
- [x] #22435
- [x] #32547
- [x] #32548
- [x] #20271
- [x] #20051
- [x] #17972
- [x] #33754
- [x] #28850
- [x] ~#33146~ Unrelated to `LinkControl`.

### Bugs
- [ ] #27345
- [x] #28373
- [ ] #34125
- [x] #20250
- [x] #33850
- [x] #32725
- [x] #32547
- [x] #32282
- [x] #25946
- [x] #23799
- [x] #21835
- [x] #34779

**Comment by getdave** [comment]
Great work on this. We should add a dedicated `Accessibility` section so as to ensure these are given a high priority.

**Comment by jasmussen** [comment]
Fresh mockups here: https://github.com/WordPress/gutenberg/issues/26351#issuecomment-1288816531

**Comment by fabiankaegy** [comment]
Question:

What's holding us from stabilizing this component?

It was introduced into the codebase in September 2019 https://github.com/WordPress/gutenberg/issues/17557 and whilst it is currently undergoing another design revision that from my perspective has very little to nothing to do with the actual API of the component. Which has changed very little in all these years. 

I feel strongly that this is a core component that is being used widely throughout the Gutenberg codebase and because it was introduced before the new private API system is also widely used outside of core. 

I would love for us to recognize that fact and stabilize the LinkControl component sooner rather than later. 

We can always tweak the underlying tech / the visuals of the component further as we are doing with other stable components. 

CC: @getdave

**Comment by getdave** [comment]
@fabiankaegy Your arguments are sound. 

Because the work to update the UX of the component is still ongoing from 6.2 -> 6.3 (and on into 6.4 where we hope to wrap up) it didn't seem like a great time to stablise the component.

I think @richtabor (who's been working with me on this) would agree that we should be able to wrap up the updates to the component in the 6.4 cycle and thus we could look to stablise for that release.

This depends on contributors and where we need to allocate time however, so it might be better thinking of it as "a near future release" as opposed to committing to an specific release.

**Comment by richtabor** [comment]
> I think @richtabor (who's been working with me on this) would agree that we should be able to wrap up the updates to the component in the 6.4 cycle and thus we could look to stablise for that release.

Yes, it really should be ironed out and used throughout the experience for 6.4.

**Comment by fabiankaegy** [comment]
@getdave  @richtabor coming back to this, do we now feel like we can finally stabilize this component? 

Looking at the [usage stats](https://wpdirectory.net/search/01HFS010RD5NN3X6RG6CCSXNH0) there are over 200 plugins in the official Repo already using the component, many of which have a really large user base. 

Regardless of us continuing to evolve the actual UI of the component I think it is way past time for us to stabilize the API of the component.

**Comment by getdave** [comment]
Just tying up loose ends and making sure that [the Design / UX refresh for this component](https://github.com/WordPress/gutenberg/issues/50891) is linked here.

**Comment by fabiankaegy** [comment]
@getdave like I said before, I do not think that stabilizing this component has much to do with us still iterating on the UX & design of the component. 

The API itself has remained stable for over 3 years now and is getting used in hundreds of plugins in the repository. 

Therefore I think it is time to stabilize the component now.

The work to improve the UI can be an ongoing effort like it is for other components we have.

**Comment by getdave** [comment]
@fabiankaegy my comment is purely for update purposes because I realised the Design refresh was not linked here anywhere. Your previous comments still stand. Let's look at landing your stablising PR in 6.5.

**Comment by otakupahp** [comment]
Another year has passed and this is still on the experimental phase. Any plan to move this fordward?

**Comment by getdave** [comment]
We should look to stabilise in 6.8 which basically means reviewing and landing https://github.com/WordPress/gutenberg/pull/56384

**Comment by tyxla** [comment]
@fabiankaegy @getdave is this issue still relevant/necessary? Perhaps we can close since `LinkControl` has been stable for a while now.

**Comment by fabiankaegy** [comment]
@tyxla happy to close it. The I individual child tickets are still there and valid but no one is actively working on it at the moment so the tracking issue is overkill

**Comment by tyxla** [comment]
👍 Agreed - closing, but feel free to reopen if needed.
