### ISSUE TITLE
Components: update color-related components — Tracking issue

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#35093]
_This is an overview issue to track all of the tasks necessary to refine the color-related components, especially in the context of using it in the updated Global Styles Sidebar._

## Context

To visualize this, there are some good mockups in #34574 that illustrate the behavior above. Instead of duplicating all available color palettes for each a single item in a group is shown as a swatch plus a label:

![step1](https://user-images.githubusercontent.com/1204802/132209474-b98a1f92-b9f6-4f07-8e31-4ba93cfaa3a4.png)

Click an item in the group drills down to a dedicated subpanel showing all available color tools:

![step2](https://user-images.githubusercontent.com/1204802/132209645-113216fd-f6f9-403f-89e1-ed3d87fc5777.png)

Here's an additional mockup that shows how the full flow for collapsible color swatches could work when used in editor inspector panels:

<img width="8920" alt="Color ItemGroup Flow i5" src="https://user-images.githubusercontent.com/1204802/132485764-cf3ac49c-0c71-4167-ad57-ef518744ab15.png">

**Please note that the precise visuals are subject to change per further work in #34574, so definitely defer to that ticket as the source of truth.**

Essentially, multiple color properties are grouped together in an ItemGroup, as swatch+label. 

- In global styles, clicking the swatch+label item slides the inspector and shows all palettes and color tools.
- In editor inspectors, clicking the swatch+label item opens a popover that shows all palettes and color tools. This popover has two states, showing the palette and then showing the color tool.

---

## Next steps

Note: This issue should be considered a draft, and will eventually supersede #33820

### `ColorSwatch`

For more context of the conversation leading to `ColorSwatch` & more, see #33820.

- [ ] Create `ColorSwatch` component
  - [ ] TBD: one component with `isInteractive` prop vs two separate components
  - [ ] Investigate a11y improvements (e.g. should it have a tooltip at all?)
- [ ] Rewrite `ColorIndicator` to use `ColorSwatch` internally
- [ ] Rewrite `CircularOptionPicker.Option` to use `ColorSwatch` internally

### `ColorPicker`

Please refer to #34284 for the work related to the updated `ColorPicker` component

### Higher-level color components

With the new `ColorSwatch` and `ColorPicker` components, we're going to be able to look at higher-level color components (currently `ColorPalette`, `CircularOptionPicker`...)

We will need to reassess the new needs that these components need to fulfil. For example, the custom color and clear/reset features of `ColorPalette` may be assumed by other components (like the newly introduced `ToolsPanel`). And rather than rendering a palette of color options directly in the sidebar, we’ll be moving toward using `ItemGroup` to group color attributes. In Global Styles, clicking an Item will drill down to another sheet displaying the available color options and related components. In block sidebars, this action will likely result in a popover with similar controls.

### `ColorPalette`

- [x] #35292
- [x] #36543

### Gradient Picker & related

- [x] https://github.com/WordPress/gutenberg/pull/34712#issuecomment-926415284
- [ ] Rewrite component to TypeScript
- [ ] Use Emotion and update folder structure

**Comment by glendaviesnz** [comment]
Has any consideration been given to the use of these components in a dropdown menu context along with the inspector panel?

I have been looking at https://github.com/WordPress/gutenberg/issues/20837, but currently the color/gradient controls seem very coupled to the inspector panels.

**Comment by glendaviesnz** [comment]
There is a very rudimentary PoC branch that adds the existing color panel to a dropdown just to see how it looks at https://github.com/WordPress/gutenberg/tree/move/cover-color-to-tool-menu

**Comment by ciampo** [comment]
> Has any consideration been given to the use of these components in a dropdown menu context along with the inspector panel?
> 
> I have been looking at #20837, but currently the color/gradient controls seem very coupled to the inspector panels.

@jasmussen and @mtias may be better suited to answer this question

**Comment by jasmussen** [comment]
> Has any consideration been given to the use of these components in a dropdown menu context along with the inspector panel?

I imagine the primary benefit of having a flyout version of the color swatch picker is that the flyout itself can be invoked either by an Item in the ItemGroup, or a button in the Toolbar. Here's how it could look for the Cover:

<img width="3000" alt="Toolbar ItemGroup" src="https://user-images.githubusercontent.com/1204802/135231028-2047d701-cc26-4b43-bf7d-f7241bc24946.png">

Edit: I've updated the above mockup to include a segmented control for gradients, which I previously forgot about. Some of the details could still be massaged, but the puzzle pieces should be in place.

**Comment by javierarce** [comment]
I like your design, @jasmussen, but there's something I'm starting to get worried about with the increased use of segmented controls: if we end up adding more items, we'll probably need to switch to a dropdown since segmented controls won't scale equally well in every language.

Maybe it's just me optimizing prematurely and we won't have more than two or three options in that flyout, but I'd consider exploring an option with a dropdown.

![image](https://user-images.githubusercontent.com/4933/136003563-35656d21-51b8-4216-b56c-21197fe3197c.png)

**Comment by jasmussen** [comment]
There are definitely cases where the segmented control won't work, good call. I do think that might be a bridge we need to cross when we get there. At the moment, "Linear" and "Radial" are both properties of the gradient control itself, which would make "Image" fit if that ends up being an addition.

**Comment by ciampo** [comment]
> I like your design, @jasmussen, but there's something I'm starting to get worried about with the increased use of segmented controls: if we end up adding more items, we'll probably need to switch to a dropdown since segmented controls won't scale equally well in every language.
> 
> Maybe it's just me optimizing prematurely and we won't have more than two or three options in that flyout, but I'd consider exploring an option with a dropdown.
> 
> ![image](https://user-images.githubusercontent.com/4933/136003563-35656d21-51b8-4216-b56c-21197fe3197c.png)

I believe a similar pattern is being explored for Typography Tools (#34345), where we switch between a segmented control and a dropdown for the Font sizes (depending on the number of items to display)

**Comment by kellychoffman** [comment]
Would like to propose a few minor tweaks for 5.9 to make the current color panel more intuitive and if i may... palatable. (While we are waiting for some improvements to land post 5.9.) If we can't get most of these in, I would hesitate to include this. @jasmussen - what do you think?

<img width="316" alt="Screen Shot 2021-11-04 at 4 30 51 PM" src="https://user-images.githubusercontent.com/5835847/140434224-2d3a1025-bb68-49cb-8e94-821d31b086f0.png">

- change “core” terminology to “default”
- reverse order so “theme” is on top of "default"
- more padding in between each grouping of color
- line separator between each section
- move big transparent rectangle to be small circle. (either keep transparent bg or add a more simple diagonal line thru it as pictured above)
- smaller circles (purely aesthetic, so not a need)

For reference - the current experience is quite overwhelming.
<img width="278" alt="color-overwhelming" src="https://user-images.githubusercontent.com/5835847/140433452-80ff0eca-85a2-4ecb-b6a8-6852f7102f43.png">

**Comment by jasmussen** [comment]
I really like the color card in Global styles. It's primarily the fact that in the post editor it will nearly always show the transparency, which when duplicated like it is without the ItemGroup collapsing makes it lose much of its intrinsic meaning. 

In that vein, I took a stab at Kelly's suggestion above in #36243. It's a quite hacky PR, and if it can be _unhackified_, it might be a better solution than reverting the card.

**Comment by critterverse** [comment]
One more thing to add to @kellychoffman's notes above — I think one thing that's hurting the readability is that there's not a very clear visual hierarchy between the section headings. Squinting at this image, the all caps palette headings almost appear heavier than the regular title case label:

![color-section-heading-hierarchy](https://user-images.githubusercontent.com/77359364/140436629-486bf254-689d-42d5-897b-9dcbb6550ddb.jpg)

Setting the all caps labels in gray-800 would help those recede a bit.

**Comment by jasmussen** [comment]
Good call, that's another aspect. In the original context in which the card was designed, it's meant to be the entirety of the contents of the panel, meaning the sidebar header is the heading:


<img width="366" alt="Screenshot 2021-11-05 at 14 19 07" src="https://user-images.githubusercontent.com/1204802/140516416-c4e4709c-7eea-4a9c-a4e1-0beac2b57295.png">

**Comment by shaunandrews** [comment]
Shared a few ideas over on the related PR: https://github.com/WordPress/gutenberg/pull/36243#issuecomment-962057612


![](https://user-images.githubusercontent.com/191598/140548560-20188daf-a4b0-4b4f-af1f-f869b33a12bd.png)

**Comment by ciampo** [comment]
Hey @kellychoffman @critterverse @shaunandrews! Since this is a tracking issue, would you mind opening a separate issue specific to discuss the Color Panel changes, and link to it from here?

Thank you!

**Comment by kellychoffman** [comment]
Added a design issue here: https://github.com/WordPress/gutenberg/issues/36543

**Comment by markhowellsmead** [comment]
Is there a reference anywhere for adding the new color picker component/s to a custom block? I’ve been using `PanelColorSettings` until now (which looks like this), but this omits the Standard color set and doesn't respect the settings in theme.json.

<img width="290" alt="panelcolorsettings" src="https://user-images.githubusercontent.com/1571592/152021629-fd58f1a4-c20a-4d30-b7b2-656dfe32a3fb.png">

**Comment by ciampo** [comment]
> Is there a reference anywhere for adding the new color picker component/s to a custom block? I’ve been using `PanelColorSettings` until now (which looks like this), but this omits the Standard color set and doesn't respect the settings in theme.json.

Maybe @aaroncampbell or @jasmussen can help you out here?

**Comment by jameskoster** [comment]
Possibly one for consideration here: https://github.com/WordPress/gutenberg/issues/41868. And this one: https://github.com/WordPress/gutenberg/issues/41866

**Comment by jasmussen** [comment]
> Is there a reference anywhere for adding the new color picker component/s to a custom block? I’ve been using PanelColorSettings until now (which looks like this), but this omits the Standard color set and doesn't respect the settings in theme.json.

Perhaps @jorgefilipecosta?

**Comment by jorgefilipecosta** [comment]
> Is there a reference anywhere for adding the new color picker component/s to a custom block? I’ve been using `PanelColorSettings` until now (which looks like this), but this omits the Standard color set and doesn't respect the settings in theme.json.
> 
> <img alt="panelcolorsettings" width="290" src="https://user-images.githubusercontent.com/1571592/152021629-fd58f1a4-c20a-4d30-b7b2-656dfe32a3fb.png">

PanelColorSettings should automatically retrieve theme.json colors and settings if they are not passed. Using the ColorPalette from the block editor package should also automatically include colors and settings. What issues did you found if the color are not passed?

**Comment by ciampo** [comment]
Closing as obsolete. If any of this is applicable, let's move it to a new up-to-date issue
