### ISSUE TITLE
Storybook: Migrate Knobs to Controls

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#35665]
## What problem does this address?

New stories should be written using [Controls](https://storybook.js.org/addons/@storybook/addon-controls/), as this will make things much easier and [Knobs](https://storybook.js.org/addons/@storybook/addon-knobs) are now deprecated.

Because Controls and Knobs are shown in separate panels, to have them both enabled globally is noisy and confusing. It also encourages people to continue using Knobs in new stories.

## What is your proposed solution?

It would probably be better if we migrated the existing Knobs usage to Controls, and remove the global Knobs decorator. For the few stories that would be less than straightforward to migrate at this time, we can keep them as is and add the Knobs decorator for those isolated cases.

**Comment by bph** [comment]
Added the "Needs Dev Note" label to put in our our radar for WordPress 6.2 Fieldguide 
Three options: 

- [ ] stand-alone Dev note post on make blog
- [ ] Mentioned is "Miscellaneous Editor Updates" dev note post
- [ ] Listed under "But Wait there is more" section of the Fieldguide. 

At the moment if seems like a stand-along post would be warranted.

**Comment by mirka** [comment]
Migration complete 🎉 Addon package removed in #47152.
