### ISSUE TITLE
Series of bugs and shortcomings faced during 5.9 go/no go prep

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#35662]
**Compiling a list of bugs, shortcomings, and enhancement ideas I run into when preparing for the go / no go demo.**

- [x] https://github.com/WordPress/gutenberg/issues/35632

There's a lot of small issues related to the roundtrip a `ServerRender` block needs to do for any change and a great showcase for why they should be avoided entirely for any interactive block.

https://user-images.githubusercontent.com/548849/137452684-d2522c35-3f41-4749-8fcd-76e5fbfef0ad.mov

- [x] Pressing shift + click within a rich-text block nested inside a group would lock you out of editing. This one is pretty frustrating.(https://github.com/WordPress/gutenberg/pull/35668)

https://user-images.githubusercontent.com/548849/137452873-c8291abf-9919-4401-be67-741f2d071233.mov

- [ ] Navigation block new link would break with no visible signs of recovery — typing the name of the page would not bring the page up.

Generally can happen after leaving the page open for a little bit or interacting for a while. It's understandable connection might break, but there should be some feedback.

- [x] #35675
- [x] #35677

https://user-images.githubusercontent.com/548849/137453165-6a360e0c-2ae9-4272-804e-d65d2576af97.mov

- [x] Site logo placeholder graphic is not rendered properly in the site editor.
- [x] The template dropdown has template parts with no names when they don't belong to an area. Reported in #35587.

![image](https://user-images.githubusercontent.com/548849/137453710-d35470e1-68df-4cc4-9ae2-40c210f628e6.png)

- [x] Buttons inside groups are misaligned. (Might be theme related.)

![image](https://user-images.githubusercontent.com/548849/137453853-d15b6947-d1e9-4f21-b615-fbe5d0a9e95c.png)

- [ ] Disabling theme editor styles in preferences makes some elements in the page load with default colors and not the current color scheme.

![image](https://user-images.githubusercontent.com/548849/137453971-b79883f4-1c33-4296-86d7-10b9002297e5.png)

- [x] The sibling inserter repositioning, together with the animation, makes it jump around.

https://user-images.githubusercontent.com/548849/137457745-ffc2d0e8-b4fe-4eee-bb71-a102fcc18d2d.mov

----

- [x] The amount of lines shown in the site editor to distinguish active focus, hover focus, current template part focus, etc, is wild. We need to reduce this.

![image](https://user-images.githubusercontent.com/548849/137453338-bfd0d2ca-1821-4771-a1a2-f96aebba7839.png)

- [ ] There's also a weird dotted outline on the site block.

![image](https://user-images.githubusercontent.com/548849/137454633-11626a6f-6b1c-49de-917e-70a5f88021cc.png)

- [ ] More blocks with dotted outlines that don't seem appropriate.

![image](https://user-images.githubusercontent.com/548849/137455752-15da361a-b4ba-434c-a9b0-b2b6f1b6522a.png)

- [x] Search in navigation menus is super awkward. It should be possible to get an icon only button that expands inline or in an overlay. This should likely also be the default. The initial insertion state, in particular, is a terrible experience (https://github.com/WordPress/gutenberg/pull/36026):

![image](https://user-images.githubusercontent.com/548849/137454321-38a71551-808c-4dec-8134-f79e372ad3f2.png)

- [x] Menu settings (called Display) should come before the Typography supports and should probably not be in a panel at all (not collapsible).

- [ ] Typography: default size looks "unset".

![image](https://user-images.githubusercontent.com/548849/137456347-cf46a97a-abac-4cc7-9b9d-84396028ac17.png)

**Comment by MaggieCabrera** [comment]
>  There's also a weird dotted outline on the site block.

I suspect that is a Videomaker bug /cc @scruffian

**Comment by ntsekouras** [comment]
>Typography: default size looks "unset".

Could we use a `help` text here if we have `ToggleGroupControl` and the value is set to default?

**Comment by scruffian** [comment]
> Buttons inside groups are misaligned. (Might be theme related.)

This was fixed by https://github.com/Automattic/themes/issues/4842

**Comment by jasmussen** [comment]
Site logo fixed in #35718. 

> The amount of lines shown in the site editor to distinguish active focus, hover focus, current template part focus, etc, is wild. We need to reduce this.

#35637 removes dotted lines on ancestors. That fixes, or starts work on it.

> Search in navigation menus is super awkward. It should be possible to get an icon only button that expands inline or in an overlay. This should likely also be the default. 

#35688 starts work on it. The issue is also tracked separately in #31127.

**Comment by youknowriad** [comment]
>  Disabling theme editor styles in preferences makes some elements in the page load with default colors and not the current color scheme.

I've been trying but failing to reproduce this one. Any more details?

**Comment by jasmussen** [comment]
> I've been trying but failing to reproduce this one. Any more details?

I'm seeing it happen in my block theme when toggling the editor styles off in preferences:
![colors](https://user-images.githubusercontent.com/1204802/137743873-8653557b-c7e1-480b-9c1e-21d32d2e5ed4.gif)

**Comment by noisysocks** [comment]
>  Pages List server-render component is ill-suited and needs to be converted to a proper editor block.

I can look into this.

**Comment by tellthemachines** [comment]
> Navigation block new link would break with no visible signs of recovery — typing the name of the page would not bring the page up.

Not sure how to reproduce this one, or even what's happening. Could we have more detailed steps please?

**Comment by noisysocks** [comment]
>  Menu settings (called Display) should come before the Typography supports and should probably not be in a panel at all (not collapsible).

Fixed by https://github.com/WordPress/gutenberg/pull/33744.

**Comment by jasmussen** [comment]
> The amount of lines shown in the site editor to distinguish active focus, hover focus, current template part focus, etc, is wild. We need to reduce this.

Checked this one, as fixed by #35637. I suspect additional fixes can be made, but it fixed the immediate issue.

**Comment by mtias** [comment]
This is mostly covered, thanks for the work following up on issues!
