### ISSUE TITLE
Tracking: ToolsPanel Follow Ups

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#36165]
This issue aims to assist in tracking the required follow-ups resulting from the recent merge of the new ToolsPanel component and dimensions panel updates.

### Blocks
- [x] https://github.com/WordPress/gutenberg/pull/34065
- [x] https://github.com/WordPress/gutenberg/pull/33909

### Block Supports

Before the new supports proposed in https://github.com/WordPress/gutenberg/issues/28356 were to be added, it was desired to have a means of progressive disclosure for the Dimensions panel. With the `ToolsPanel` now in place and providing this, the following block supports can be picked up.

- [x] https://github.com/WordPress/gutenberg/pull/32499
- [x] https://github.com/WordPress/gutenberg/pull/33970
- [x] https://github.com/WordPress/gutenberg/pull/32502

### Updating Block Support Panels

Now the `ToolsPanel` has landed we can switch all the block support panels over to using this component. This will hopefully allow greater adoption of block supports while reducing the prominence of those supports' UI when it's not required.

Once all block supports have been switched over to the `ToolsPanel`, ordering these as per https://github.com/WordPress/gutenberg/issues/35541 will only be a matter of reordering the InspectorControls slots accordingly.

- [x] Switch typography block support to use `ToolsPanel`
  - [x] https://github.com/WordPress/gutenberg/pull/33744
  - [x] https://github.com/WordPress/gutenberg/pull/35911
- [x] Switch border block support to use `ToolsPanel`
  - [x] https://github.com/WordPress/gutenberg/pull/33743
  - [x] https://github.com/WordPress/gutenberg/pull/35938
- [x] Switch colors block support to use `ToolsPanel`
  - [x] https://github.com/WordPress/gutenberg/pull/34027

### Determining Default Controls

Different blocks will need different block support controls exposed by default.

For each block support toolset, find all the blocks that opt into that support and determine which if any controls should be shown by default. Each block's block.json file could be updated in separate PRs for more focused discussion or as a batch if this first pass on controls is rather superficial.

- [x] Dimensions panel defaults
  - [x] https://github.com/WordPress/gutenberg/pull/34026
  - [x] https://github.com/WordPress/gutenberg/pull/34060
- [x] Border panel defaults
  - [x] https://github.com/WordPress/gutenberg/pull/34061
- [x] Color panel defaults
  - https://github.com/WordPress/gutenberg/pull/38511
- [x] Typography panel defaults
  - [x] https://github.com/WordPress/gutenberg/pull/34064
  - [x] https://github.com/WordPress/gutenberg/issues/36188
  
### ToolsPanel UI

- [x] https://github.com/WordPress/gutenberg/pull/34107
- [x] https://github.com/WordPress/gutenberg/pull/34369
- [x] https://github.com/WordPress/gutenberg/pull/34530
- [x]  Audit and improve ToolsPanel's a11y (semantics, focus management, announcing changes to screen reader users)
    - [ ] https://github.com/WordPress/gutenberg/issues/40460

### Miscellaneous
- [x] https://github.com/WordPress/gutenberg/pull/34028
- [x] https://github.com/WordPress/gutenberg/pull/34063
- [x] https://github.com/WordPress/gutenberg/pull/35621
- [x] https://github.com/WordPress/gutenberg/pull/35658
- [x] https://github.com/WordPress/gutenberg/pull/35415
- [x] https://github.com/WordPress/gutenberg/pull/35375
- [x] https://github.com/WordPress/gutenberg/pull/34157

### Future Follow-Ups
- [ ] https://github.com/WordPress/gutenberg/pull/32878
- [ ] Possibly exposing underlying Grid component in ToolsPanel for more flexibility and control of panel layout

**Comment by adamziel** [comment]
@aaronrobertshaw @apeatling Is there any feature that you think could still land until Wednesday next week to be included in WordPress 6.0 release? To increase visibility, we can add it to the [WordPress Editor 6.0 project board](https://github.com/orgs/WordPress/projects/27/views/1).

**Comment by apeatling** [comment]
I think all the follow up work in terms of this issue is done for this cycle. Height/min-height/width and future issues can be refreshed and looked at down the line in a new issue.
