### ISSUE TITLE
Update Appearance > Templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36204]
This is a tracking issue for the updates we need to make to the template list view in accordance with the designs shared in #29630.

- [x] https://github.com/WordPress/gutenberg/issues/35990
- [ ] https://github.com/WordPress/gutenberg/issues/35991
- [ ] https://github.com/WordPress/gutenberg/issues/35994
- [x] https://github.com/WordPress/gutenberg/issues/35995
- [ ] https://github.com/WordPress/gutenberg/issues/36348
- [ ] https://github.com/WordPress/gutenberg/issues/36352

<img width="1331" alt="Screenshot 2021-11-04 at 09 55 40" src="https://user-images.githubusercontent.com/846565/140293854-c0a0391b-394d-4d46-9e1d-329806588f77.png">

### Follow-ups 

- [ ] Make it possible to revert customisations from list view

**Comment by jameskoster** [comment]
Now that it's confirmed that https://github.com/WordPress/gutenberg/pull/36379 will be included in 5.9 I think we can close this and its associated issues due to the fact that Appearance > Templates will no longer exist.
