### ISSUE TITLE
Update Appearance > Template Parts

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#36205]
This is a tracking issue for the updates we need to make to the template part list view in accordance with the designs shared in #29630.

- [ ] Use [template part focus mode](https://github.com/WordPress/gutenberg/issues/33926) when navigating to Appearance > Template Parts > Template Part
- [ ] Refine the Add Template Part flow in Appearance > Template Parts
- [ ] Update Appearance > Template Parts to list template parts included with the theme/plugins
- [ ] Refine the columns in Appearance > Template Parts

<img width="1221" alt="Screenshot 2021-11-04 at 10 08 43" src="https://user-images.githubusercontent.com/846565/140295629-ab6a9e90-6f73-4130-9696-02ce7a0964d3.png">
