### ISSUE TITLE
[Site Editor] Templates list screen overview

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#36597]
Based on the design in https://github.com/WordPress/gutenberg/issues/29630#issuecomment-954159446, derived from TODOs in https://github.com/WordPress/gutenberg/pull/36379. Here are the list of tasks we should do for the new Templates list screen.

👀 Needs design
🔺 Blocker for 5.9 Beta
⚠️ Blocker for 5.9 Release

### 🔨 &nbsp; Features

- [x] "Add New" button hasn't been implemented (#36592) (🔺 )
  - [ ] https://github.com/WordPress/gutenberg/issues/36648
  - [x] Error handling and loading state
- [ ] "Actions" button for each template item
  - [x] Implement "Clear customizations" (https://github.com/WordPress/gutenberg/pull/36802)
  - [x] Implement "Delete" for custom templates
  - [ ] Optimistic updates for "Remove template"
  - [x] Snackbars for successful/failed actions (https://github.com/WordPress/gutenberg/pull/36808)
  - [ ] Ability to undo an action
- [x] Show recently edited user in "Added by" column (designs here - https://github.com/WordPress/gutenberg/issues/36597#issuecomment-973893084, PR here - https://github.com/WordPress/gutenberg/pull/36763)
  - [x] Show plugin name when template is added by a plugin
  - [x] Indicate when a template has been customized
- [x] Remove the "Styles" link in the navigation panel (#36637) (⚠️ )
- [x] https://github.com/WordPress/gutenberg/pull/36805
- [ ] Provide a way to edit the description for custom templates (https://github.com/WordPress/gutenberg/issues/36664)
- [x] Provide a way to edit the title of custom templates (https://github.com/WordPress/gutenberg/issues/36773)
- [x] #36488

### 💅 &nbsp; Styles
- [x] The screen is not responsive (⚠️ , 👀 )
  - [x] Collapse the nav panel on smaller screens (https://github.com/WordPress/gutenberg/pull/36638)
- [ ] Make the template row clickable and add hover styles (👀 )
- [x] Consider adding icons to menu items (https://cloudup.com/chpQIrvKePJ, https://github.com/WordPress/gutenberg/pull/36893)

### 🐛 &nbsp; Bugs
- [x] https://github.com/WordPress/gutenberg/pull/36761 (⚠️ )
- [x] https://github.com/WordPress/gutenberg/pull/36762 (⚠️)
- [x] Update link href (https://github.com/WordPress/gutenberg/pull/36379#discussion_r753881439) (⚠️ )
- [x] https://github.com/WordPress/gutenberg/issues/36937 (⚠️ )
- [ ] #36821 (⚠️ )
- [ ] Handle unsaved changes warning when leaving the editor (https://github.com/WordPress/gutenberg/pull/36488#issuecomment-987535740)

### 🧹 &nbsp; Enhancements and Maintenance
- [ ] https://github.com/WordPress/gutenberg/issues/36873 (@Mamaduka is working on this)
  - [x] If it can't be done before 5.9, try improving the code quality of existing client side redirection (https://github.com/WordPress/gutenberg/pull/36488#discussion_r765399473)
- [x] Some dead code hasn't been deleted yet
- [ ] Highlight templates that are used for specific pages (IE home page, posts page, privacy page). This should be extensible (#36612).
- [ ] Consider replacing "Template Parts" menu with area-based alternatives (https://github.com/WordPress/gutenberg/issues/36613)

### Accessibility ⚠️
- [x] https://github.com/WordPress/gutenberg/pull/36707
- [x] #36709
- [x] Consider adding aria-current to the active link in the navigation sidebar (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current).
- [x] Move focus to the navigation toggle button or a custom "skip to content" link when navigating
  - [x] https://github.com/WordPress/gutenberg/pull/37265
  - [ ] https://github.com/WordPress/gutenberg/pull/37314

Feel free to assign yourself to any of the above tasks if no one is working on them. Also any helps or discussions are healthy too either in the comments below or creating a separate issue referencing this.

**Comment by jameskoster** [comment]
> The screen is not responsive (⚠️ , 👀 )

Overall the screen is responsive as demonstrated in https://github.com/WordPress/gutenberg/pull/36379#issuecomment-966271773. However it would be nice if the nav drawer automatically closed itself when you resize the window from desktop orientation down to mobile.

**Comment by jameskoster** [comment]
> "Styles" link in the navigation sidebar (👀 )
> Making it a toggle button seems weird in a nav. What should we do about it?

Personally I am in favor of removing the styles link for now. I agree it feels very strange to actually use as implemented. We already highlight Styles in the welcome guide:

<img width="403" alt="Screenshot 2021-11-18 at 18 14 49" src="https://user-images.githubusercontent.com/846565/142473073-2afcbca8-0d77-4c92-b91a-0b5b3fc229e3.png">

And will no doubt surface it in any [adjustments we make to the wp-admin welcome banner](https://core.trac.wordpress.org/ticket/54460). Not to mention the 5.9 about page...

**Comment by kevin940726** [comment]
> Personally I am in favor of removing the styles link for now. I agree it feels very strange to actually use as implemented.

I agree. Let's remove this from the list?

**Comment by talldan** [comment]
> Show recently edited user in "Added by" column

@jameskoster I had a look at adding this column for the author or user that last edited, but it looks template parts and templates don't support the author field. We will have to make some changes to the REST API code already shipped to WordPress core to support this.

A lot of templates (and I think template parts) are also shipped with the theme as files, so won't have an author. Do you think it's worth continuing to pursue adding this column?

Here's the data we get for a template from the REST API:
<img width="554" alt="Screenshot 2021-11-19 at 4 10 55 pm" src="https://user-images.githubusercontent.com/677833/142588209-dc266309-1f99-41ae-854d-bd67c40d5133.png">

For template parts we might consider adding an 'Area' column, but they also generally don't seem to have a description:
<img width="559" alt="Screenshot 2021-11-19 at 4 13 08 pm" src="https://user-images.githubusercontent.com/677833/142588427-aeaadd84-b6b0-4b1b-99eb-0bfc958c989e.png">

Not really a lot to work with.

**Comment by talldan** [comment]
> Overall the screen is responsive as demonstrated in #36379 (comment). However it would be nice if the nav drawer automatically closed itself when you resize the window from desktop orientation down to mobile.

#36638 tackles this.

**Comment by jameskoster** [comment]
Thanks for looking in to that @talldan. The basic principle of the "added by" column was to:

1. Clarify the original source of the template, whether that be
  * A theme.
  * A plugin.
  * A custom template created by a user at the site.
2. In the case of templates supplied by themes and plugins, inform the user whether those templates have been customised or not.

FWIW, here's the original design:

<img width="645" alt="Screenshot 2021-11-19 at 09 14 30" src="https://user-images.githubusercontent.com/846565/142597106-016d3f73-0901-4e13-b711-ba51ce2b3f34.png">

Would I be correct in assuming we can tell whether the template is custom, or has been customised, by the existence of that template in the db? If we cannot tell the actual author, perhaps we can just display something generic?

Seems we can use the `theme` in the API data for theme supplied templates. I'm not sure about plugins, but I know WooCommerce are working on adding block templates, so perhaps someone can chime in there cc @nerrad @Aljullu.

**Comment by talldan** [comment]
> Would I be correct in assuming we can tell whether the template is custom, or has been customised, by the existence of that template in the db?

Yeah, I think we can use the same logic that determines whether the clear customizations UI is shown, so that should be possible 👍

I'll do some more exploration into adding author support tomorrow (edit: I mean Monday 😄 ).

Thanks for the other clarifications, that helps a lot.

**Comment by Mamaduka** [comment]
Yes, we can use `WP_Block_Template::$source` for this column. The plugins can change this value when adding templates.

https://github.com/WordPress/gutenberg/blob/d718cb0ae5571e9c6199a7eaacf8f063804f7d52/lib/full-site-editing/class-wp-block-template.php#L63-L68

The author support is something we can add after 5.9. I think most of the custom templates will have a single author.

**Comment by paaljoachim** [comment]
I added feedback to the now merged PR: https://github.com/WordPress/gutenberg/pull/36379#issuecomment-973432382

Here are some of the things I noticed while giving feedback. (Let me know if this should be added else where.)
The WP black menu area is too wide and can be thinner. Site title can use truncation if needed.
< Dashboard font size is 13px and should be 14px the same as the Editor menu items.
Clicking Site or Styles should not close the left WP menu (plus it is also very slow to close). Clicking W is a fast way to open and close. W should have a shortcut.
Templates and Template Parts could contain a column for the date a specific template was created.
3 dot menu can contain a duplicate option.

**Comment by tjcafferkey** [comment]
>I'm not sure about plugins, but I know WooCommerce are working on adding block templates, so perhaps someone can chime in there

@jameskoster yeah, [we check the db for any templates](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/95ac903535b45674058148dacd255edc302fba39/src/BlockTemplatesController.php#L59-L70) that have been customized based on the template files we've provided. We then [set the property](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/95ac903535b45674058148dacd255edc302fba39/src/Utils/BlockTemplateUtils.php#L110) `custom` as a means to identify if the template has indeed been customized.

I hope this has answered your question. Let me know if not 🙂

**Comment by jameskoster** [comment]
@tjcafferkey I was more curious about _how_ y'all supply the templates, and whether how the API indicates that those templates were added by WooCommerce in any way?

@paaljoachim I think most of those warrant separate issues.

**Comment by tjcafferkey** [comment]
>I was more curious about how y'all supply the templates, and whether how the API indicates that those templates were added by WooCommerce in any way?

@jameskoster We use the `get_block_templates` filter to [add the templates from WooCommerce](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTemplatesController.php#L56). We also indicate its from WooCommerce by setting `woocommerce` as the `theme` and `source` value [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/Utils/BlockTemplateUtils.php#L138) and [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTemplatesController.php#L348). Hope this helps.

**Comment by paaljoachim** [comment]
I made the following issues:

[Site Editor] WP menu area - make the screen thinner and add truncation to site title.
https://github.com/WordPress/gutenberg/issues/36657

[Site Editor] WP Menu area - Adjust < Dashboard text to 14px font.
https://github.com/WordPress/gutenberg/issues/36658

[Site Editor] WP left menu area - Do not close menu area when selecting Site or Styles
https://github.com/WordPress/gutenberg/issues/36659

[Site Editor] Adding a shortcut to W icon to open and close the WP left menu area.
https://github.com/WordPress/gutenberg/issues/36660

[Site Editor] ~~Templates and Template Parts screens - add Published date.~~
NEW title and focus: Templates and Template Parts screens - Provide a way for users to add a description to custom templates.
https://github.com/WordPress/gutenberg/issues/36664

[Site Editor] Templates list screen - Add duplicate to 3 dot menu. 
https://github.com/WordPress/gutenberg/issues/36665

EDIT 27 Nov - Adding in the following issue:
Site Editor: Add New - Custom/General template
https://github.com/WordPress/gutenberg/issues/36860

**Comment by talldan** [comment]
> @jameskoster We use the get_block_templates filter to add the templates from WooCommerce. We also indicate its from WooCommerce by setting woocommerce as the theme and source value here and here. Hope this helps.

Hmm, it's a shame we didn't opt for something like `source: 'plugin'` to match the way `source: 'theme'` works. The current way makes it hard to detect whether a plugin is the source—the only option seems to be to check that the `source` is different to 'custom' or 'theme'. If other sources are added later this becomes brittle code.

Is the way this is defined likely to be consistent across plugins?

**Comment by kevin940726** [comment]
@jameskoster I noticed that there's currently no way to edit a template part's name, neither in the site editor nor in the list page. Is this feature planned?

In addition, I think we also need a way to delete a template/part in the editor.

**Comment by talldan** [comment]
@kevin940726 It is possible to edit the name/title in the 'Advanced' section of the block sidebar:
<img width="281" alt="Screenshot 2021-11-23 at 3 13 51 pm" src="https://user-images.githubusercontent.com/677833/142983652-0b8d4aed-80c7-4441-b28b-a1ea4368dcef.png">

**Comment by kevin940726** [comment]
Oh I see! It's still counter-intuitive though and we should probably support that in focus mode.

**Comment by tjcafferkey** [comment]
>Hmm, it's a shame we didn't opt for something like source: 'plugin' to match the way source: 'theme' works. The current way makes it hard to detect whether a plugin is the source

@talldan I am going to look at seeing if I can make a change to update this so the `source` is `plugin` for our WooCommerce implementation, it makes much more sense.

**Comment by talldan** [comment]
Thanks @tjcafferkey, appreciate that. BTW, I have a PR as well that tries to implement showing the plugin name - https://github.com/WordPress/gutenberg/pull/36763, I'll update that.

I'll have a think about how we can make this work consistently across plugins too, this might need some documentation.

**Comment by tjcafferkey** [comment]
>I'll have a think about how we can make this work consistently across plugins too, this might need some documentation.

Yeah, that would be great @talldan. As it might be confusing, because at the moment we have the `source` as `plugin` and then the `theme` as `woocommerce` when the templates are not coming from a theme. If you'd like me to read over the documentation when you have something, I'd be more than happy to do so.

I've also opened a [PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5215) for the change described above

**Comment by jameskoster** [comment]
> we should probably support that in focus mode.

In addition to renaming, we also need a way to add descriptions (https://github.com/WordPress/gutenberg/issues/36664). It may make sense to tackle these items together as they are closely related.

**Comment by Mamaduka** [comment]
@kevin940726 I started working on server-side page context/redirection, and I think it might be better to push this enhancement post 5.9.

I will create a separate issue for tracking.

**Comment by alexstine** [comment]
@kevin940726 My PR ##37265 should take care of this hopefully.

"Move focus to the navigation toggle button or a custom "skip to content" link when navigating"

**Comment by noisysocks** [comment]
I believe we can close this now that WP 5.9 is wrapped up. Nice work again, everyone!
