### ISSUE TITLE
Introduce "Browser" and surface main navigation UI

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#36667]
The latest work on the navigation block infrastructure has allowed us to isolate the inner link items of the navigation block into its own post type. This now allows us to have a focused interface for managing the site structure in addition to the presence of the navigation block on the canvas. This can take different views with the focused template part mode and the list view affordances native to the block editor.

We also have all the relevant tools implemented for the tree-view of links to be a viable management interface for pages and link items. It supports reordering, drag and drop, nesting, etc.

At the same time, the W menu has been one of the proposed destinations for managing templates. This issue proposes the combination of these features and an alternate exploration where they become top level items. The aim of this work is to allow prominent access to navigation structure regardless of the state of the site editor. (For example, if navigation is collapsed on an overlay menu, the page is scrolled beyond visibility, etc.)

![image](https://user-images.githubusercontent.com/548849/142651772-6a456425-c48f-48ef-a3d2-38c9423aa3b7.png)

<img width="3310" alt="Sorting flow in W menu" src="https://user-images.githubusercontent.com/548849/142649710-2093083e-0dd9-4dc1-b892-62aca02aff03.png">

---

The list view trigger from the navigation menu (which formerly opened a modal) would open this panel instead, connecting the flows:

<img width="3310" alt="Open navigation from navigator" src="https://user-images.githubusercontent.com/548849/142650388-9aab4eb5-0157-413c-887b-02a05e9e553d.png">

---

Finally, another option that avoids the confusion of the W menu behaving erratically between editors would be to expose this access as top level tools:

![image](https://user-images.githubusercontent.com/548849/142650794-f5793595-9085-4fce-a7bc-79656b54bdef.png)

This might be a more palatable interim solution while the whole experience of the W menu is iterated upon and established across editors. The following video describes how it might work.

https://user-images.githubusercontent.com/548849/142651019-6fd920db-478e-456f-9c12-91c17e48380d.mp4

There's a few unattended details, like having a dropdown to select among different navigations used (in case a footer has a different one, etc), but it paints an idea of how it could work.

_Thanks to @jameskoster and @jasmussen for exploring this idea with me._

Todo List:

 - [x] Introduce the browse mode #44770 
 - [x] Fix aria regions navigation #46509
 - [x] Rework the "Edit" button position and design #46700
 - [x] Restore the of '< Dashboard' button 
 - [x] Hide the inserter buttons from the "view" mode #46763 
 - [x] Move the template list to the left sidebar #45100 
 - [x] Move template creation to the sidebar #46458
 - [x] Move the Navigation menus to the left sidebar #46436 (@jorgefilipecosta )
 - [x] Allow resizing the sidebar/frame #46903 
 - [x] https://github.com/WordPress/gutenberg/issues/46274
 - [ ] https://github.com/WordPress/gutenberg/issues/48022
 - [ ] https://github.com/WordPress/gutenberg/issues/48476

**Comment by pablohoneyhoney** [comment]
There’s also an opportunity to organize those taxonomies (Templates, Navigation, Styles) elevated to the persistent level of the W. Here are some explorations of what that could look and behave. 

In one exploration (likely my preference) we can accommodate those architectural instances in a more visible UI that can be toggled and related more clearly. Here are some variants with slight permutations on how colors and positions can help link the W and the immediate navigational items. 

![Nav2](https://user-images.githubusercontent.com/25516611/142948350-d64202d1-4fdc-4bc9-9234-be8dadaa0812.png)

In another path, those higher level instances can be presented in a flyout when interacting (hover and click) with the W. This permits to keep the current simplicity of the top bar to arguably focus on the content controls. And it also surfaces more evidently the return to wp-admin. Various indicators can hint the presence of the flyout. 

![Nav](https://user-images.githubusercontent.com/25516611/142948282-82fb22e6-9b4a-4ff0-b30f-0e5b56738702.png)


Templates and Navigation can trigger the correspondent left panel, while Styles can (for now) still open the right-side panel. 

![Nav3](https://user-images.githubusercontent.com/25516611/142948367-c802148a-c9d2-4b44-9c5b-aab90c0cc850.png)

![Nav4](https://user-images.githubusercontent.com/25516611/142948393-9f9b165d-7459-4a0e-b81c-c2d78d8a770f.png)

**Comment by jameskoster** [comment]
I like the idea of dark areas of UI equalling global elements very much, it creates an environment for site settings to live as well. Exposing the site structure / navigation is particularly exciting because it means we can offer an intuitive way to navigate and edit different pages in the site editor.

The flyout approach solves potential scalability issues that may occur with the W button expanding horizontally. I explored a vertical approach as well, which adds another layer of abstraction and solves the scalability issues at the expense of 60px horizontal real estate.

https://user-images.githubusercontent.com/846565/142999913-8c454199-8c3c-48c8-bc6b-d6ac6558feb3.mp4

**Comment by jameskoster** [comment]
It occurred to me that Reusable Block management could live in this global UI region too :) 

<img width="1643" alt="Screenshot 2021-11-25 at 16 03 36" src="https://user-images.githubusercontent.com/846565/143473088-e3069474-c43e-4686-9a5f-8eed47ddd7c8.png">

**Comment by SaxonF** [comment]
Some overlap with the thinking here https://github.com/WordPress/gutenberg/issues/32682

**Comment by SaxonF** [comment]
Thinking about this some more, navigation structure within the left sidebar does feel a little strange to me personally because it is so detached from the navigation itself. I would expect it to be part of the block settings on the right, consistent with other blocks. Technically navigation structures might be global, but I'm assuming you would rarely have one set used in multiple places on your site.

**Comment by jasmussen** [comment]
One aspect I like about surfacing a dedicated navigation is that it provides an obvious default for the (presumably majority) of sites that have only a single navigation menu. Such a default can be loaded by default as well, for example in the navigation block.

**Comment by jameskoster** [comment]
Centralised menu management is also useful when

1. There are many menus – the one you want to edit next may not necessarily be on the current canvas. 
2. You want to work on a menu but not attach it to a template yet. Like a draft. 

It does pose an interesting question though. If we say that the contents of global elements like menus are managed in a distinct interface separate from the canvas, do Reusable Blocks and Template Parts get a similar treatment?

**Comment by jasmussen** [comment]
> If we say that the contents of global elements like menus are managed in a distinct interface separate from the canvas, do Reusable Blocks and Template Parts get a similar treatment?

I imagine what we currently do for isolated template part editing being a pattern to be leveraged for a majority of UIs like these, reusable blocks, perhaps even for editing the contents of the navigation modal.

**Comment by SaxonF** [comment]
> There are many menus – the one you want to edit next may not necessarily be on the current canvas.
> You want to work on a menu but not attach it to a template yet. Like a draft.

@jasmussen @jameskoster Could I accomplish the above using re-usable blocks (containing nav block) edited/created in isolation? There are already so many concepts to grasp when it comes to global elements (template parts, templates, re-usable blocks) that I fear introducing yet another will be overwhelming. 

This opinion could just be because I'm used to working in design tools like Figma (with components) but Webflow takes a similar approach with their symbols and it just feels simpler.

**Comment by jameskoster** [comment]
Funnily enough Joen and I were chatting about this last week and yes – you could accomplish this with reusable blocks, or template parts for that matter 😅

I have begun wondering whether "reusability" could be a more abstract concept. So rather than providing multiple elements that all essentially do the same thing, perhaps _all_ blocks have a toggle to make them reusable or "[synced](https://github.com/WordPress/gutenberg/issues/34352)". I'm sure there are many trade-offs to this, but on the whole I agree – adding more reusable elements only makes things more complicated for the end user.

**Comment by SaxonF** [comment]
I really love the thinking behind @luisherranz suggestion in the synced block thread you referenced and believe the same simplification/unification principle could apply here. 

Taking the idea to the extreme you could even argue that a navigation block isn't even needed. Just create a pattern containing a row with a logo and some links. If you need a submenu, add a generic dropdown block to your row.

**Comment by jameskoster** [comment]
Yes, if there was an option to mark patterns with semantic meaning (header, footer, navigation) then we could remove both the Navigation and Tempalte Part blocks.

**Comment by getdave** [comment]
> You want to work on a menu but not attach it to a template yet. Like a draft.

This touches on the concept of "safe exploration" which I feel is a key use case driving the argument for some kind of standalone means to edit the "items" of a Navigation Menu (i.e. `wp_navigation`) in isolation from the Navigation block.

For example, I might have a variation of my primary navigation which I only wish to expose at a certain point in the future. With the current Navigation block that's going to be very hard to achieve.

If we afford a place where menu data can be safely created and manipulated in isolation from the site canvas, then that's going to make it much easier for users to create and manage menus.

Note: this isn't straying far from the direct manipulation paradigm - the primary means for creating menus can still be via the block - but it's important that we recognise the alternative workflows that we need to cater for.

**Comment by SaxonF** [comment]
@getdave the idea @jameskoster and I are discussing definitely goes beyond the scope of this particular issue but its worth mentioning because it would solve the same "safe exploration" problem, but for all blocks, not just navigation/menu.

In Figma you can create a library that is detached from your main design. You're free to add components (e.g. nav menu) and styles to that library without them actually being put to use. When you're ready, you can add these components from your library to your design, or replace existing components. The same mental model applies to Storybook (building components in isolation) and could apply here. We already take a similar sort of approach with templates.

Much like the mindset @luisherranz [has](https://github.com/WordPress/gutenberg/issues/34352#issuecomment-964499762), I do think there is an opportunity here to design a single solution that solves for multiple problems, not just for navigation. I realise there are complexities around backwards compatibility that need to be considered.

Might be worth a separate thread.

**Comment by gwwar** [comment]
I'm going to try a small spike to see what issues I run into, let me know if folks have already started on this one.

**Comment by mtias** [comment]
Extracting some tasks from this to begin next steps:

- [ ] Try a dedicated panel + icon for the navigation structure, reading from `wp_navigation`.
- [ ] Use list view as a basis, with a dark variant and possibly reducing some options or adding new ones (like "add page").
- [ ] Consolidate use of tree-nav in the navigation block (it should open the same thing).

Design:
- Continue to prototype solutions for surfacing high-level items for the site editor (global styles, templates, navigation).

**Comment by getdave** [comment]
@mtias Do you see this work as separate or complementary to [an isolated Navigation Menu editor](https://github.com/WordPress/gutenberg/issues/37950)?

**Comment by mtias** [comment]
Complementary — if it works super well, it might become canonical.

**Comment by talldan** [comment]
> possibly reducing some options or adding new ones (like "add page").

It'd be good to see some design options for adding a page. I'm not sure the flow that's usually used in the block for this would be quite as successful in List View (Add a link, then use the URLControl to search for a page).

We could try a custom block appender in List View. There is (or was) already some support for appenders in List View, it was an experiment in the navigation editor.

The tricky part could be naming the page. I feel like that would probably make sense if the actual text for the item in the List View item were editable.

**Comment by gwwar** [comment]
I've added a prototype for the new navigation sidebar in https://github.com/WordPress/gutenberg/pull/38600, folks are welcome to look 👀

**Comment by jordesign** [comment]
One thing I wanted to note from a user POV (coming from assisting users) is that for a lot of tasks - we'll often guide them straight to the template editor to make changes (things like changing the Post Title Styling for eg). In these instances - having to take them _through_ the Site Editor is something of a roadblock and/or overwhelming distraction.

I'd love if this plan being considered allowed deeper linking directly into the list of template/parts without having to land entirely in the Site Editor first.

**Comment by gwwar** [comment]
Leaving a quick note that @scruffian should be able to continue with explorations here. Y'all are welcome to take over or cherry-pick parts of https://github.com/WordPress/gutenberg/pull/38600 if folks need it.

**Comment by paaljoachim** [comment]
I added comments to both PRs.
**Try: Navigation Menu Sidebar**
https://github.com/WordPress/gutenberg/pull/38600#issuecomment-1063379594
and
**[Experiment] Navigation menu focus mode editor**
https://github.com/WordPress/gutenberg/pull/39286#issuecomment-1063399017

I made a video:
https://youtu.be/qFebtfHZJLU

**Comment by simison** [comment]
Would the work on the navigation interface include indicating visually, and perhaps also allow changing, what template is on front of the page? [Issue](https://github.com/WordPress/gutenberg/issues/28341)

<img width="512" alt="Screenshot 2022-03-10 at 15 41 40" src="https://user-images.githubusercontent.com/87168/157673821-2d8dafc4-bff7-4ed4-8e92-ae02ce1ce156.png">

<img width="233" alt="image" src="https://user-images.githubusercontent.com/87168/157673881-95597292-9722-49d7-b22a-619ccf5b54d1.png">

**Comment by mtias** [comment]
Not initially, because a link to the home may or may not be present in a navigation menu. It'd make sense to always surface it, but it'd need to be clear when it is present in the navigation and when it's not. All of that needs separate consideration to this issue.

**Comment by gziolo** [comment]
Is there any feature that you think could still land until Wednesday next week to be included in WordPress 6.0 release? To increase visibility, we can add it to the [WordPress Editor 6.0 project board](https://github.com/orgs/WordPress/projects/27/views/1).

**Comment by getdave** [comment]
> Is there any feature that you think could still land until Wednesday next week to be included in WordPress 6.0 release? To increase visibility, we can add it to the [WordPress Editor 6.0 project board](https://github.com/orgs/WordPress/projects/27/views/1).

The [Nav Sidebar](https://github.com/WordPress/gutenberg/pull/39290) is a _possibility_ (subject to assessment by contributors).

**Comment by jasmussen** [comment]
We’ve been exploring the proposals on this thread and trying to tie them them together in a dedicated _Design_ section. The basic idea centers around “Browse mode” (#23328), a viewport shown in a frame on the right that lets you navigate around your website. This is not a frontend view, but indeed the editor view, only with clickable links.

Tools that effect change site-wide, for starters Navigation but in the future potentially Global Styles, Template, Site Icon and others, can live outside of this frame on the left, to indicate their global nature.

The combination of the two lets you browse around the site and see the global effect of a navigation or style change, before committing it site-wide. And of course at any one point, you can click “Edit” on a page you want to access.

https://user-images.githubusercontent.com/1204802/161579413-cd0ed368-3ac8-4cc2-a4d4-75c484c8f74e.mp4

Thank you @jameskoster for the prototype.

**Comment by getdave** [comment]
Related https://github.com/WordPress/gutenberg/issues/42257

**Comment by jameskoster** [comment]
I’m sharing an updated design here, but it could just as easily be posted in #32682, #43142, or #39856 as well – there are many overlapping elements here, and it’s important to keep the broader landscape in mind as we work out how to proceed.

---

This concept takes things a step further than [the last](https://github.com/WordPress/gutenberg/issues/36667#issuecomment-1087711883), to explore how the rest of the navigation area could be arranged so that the overall site editing experience feels more like a design tool.  

### Adding style

The contents of the existing Styles panel are migrated to the dark navigation area. This improves discoverability, and affords us the freedom to do some interesting things with the right-hand area of the viewport. For instance we can build a view that displays a curated list of templates / pages, so that users are able to get an idea of how their style changes affect their site more broadly. Hopefully we can reuse some of the work in #33770 to achieve this. The usefulness of such a feature is perhaps best demonstrated as a part of the style variation selection flow:


https://user-images.githubusercontent.com/846565/186902132-fca1c75c-0df9-489e-a40d-d03e7a5e8c17.mp4

Whether the view toggles automatically as a part of specific flows, or via a dedicated button like in the video above remains a detail to discuss.

Other contextual views we can explore include: 

1. Displaying a sheet of text blocks when editing typography.
2. Displaying a preview when editing styles for a specific block.

https://user-images.githubusercontent.com/846565/186902688-1e4ffe53-aead-4711-86c3-ef199f2d6690.mp4


### Library

More complex features (IE global / synced blocks, templates, etc) move to a new ‘Library’ section. Down the road it would be excellent to employ a mosaic view for these (again, we can hopefully use the work in #33770):


https://user-images.githubusercontent.com/846565/186908524-400f7b9d-ba91-4b8d-9125-f1756285c49a.mp4



But in the mean time the existing templates list can work just fine:


https://user-images.githubusercontent.com/846565/186908338-cae1764d-b316-462f-9a26-9acd3190cf0d.mp4



In the future Patterns / Reusable Blocks can live in the Library too.

### Navigation

Bringing things back around to this issue specifically, navigation menu management lives in the ‘Navigation’ section as before. Clicking into this reveals the menu editing interface on the left, and (like the block editing example above) a visual preview of that menu on the right. 


https://user-images.githubusercontent.com/846565/186908800-89222d86-c6b7-41a0-9eef-cd8ba33d714c.mp4



This addresses issues with the existing navigation panel whereby you can often end up editing a menu without being able to see it, which feels very awkward.

---

In the future we can bring other long-requested features into the dark management area, such as homepage and site identity settings:


https://user-images.githubusercontent.com/846565/186909196-a5f17ced-aa6e-48f9-85d0-6cf3400851bd.mp4



But like the mosaic view of templates and browse mode, these are probably less urgent than the other elements discussed here.

**Comment by jasmussen** [comment]
Nice work, Jay! 

It feels substantially stronger to immediately see access to Styles and Typography right at the top of the hierarchy. It implies the global nature of those controls, and appeals to what you're probably going to change most of the time you enter this section.

The thumbnail view feels valuable enough that it could be default rather than two toggles in the top right corner. 

It seems like 80% of this can be implemented today (give or take the need for form widgets that work on a dark background), in that light I'd love to get this going. Could the dark frame that sits around the "viewport" also sit around the existing template list, though?

**Comment by jameskoster** [comment]
> The thumbnail view feels valuable enough that it could be default rather than two toggles in the top right corner.

Yeah that's definitely something to consider, especially as it will probably be a while until we have Browse mode. Another option is that it 'remembers' your last toggle each time you open the site editor. We probably still need the toggle though, so that you're able to view your homepage (and access the Edit button). 

Those toggle buttons are definitely something to noodle on some more, both in terms of their general appearance / position, and the icons themselves. 

> Could the dark frame that sits around the "viewport" also sit around the existing template list, though?

I don't see why not... shouldn't be too much work (famous last words)!

**Comment by pablohoneyhoney** [comment]
Related: https://github.com/WordPress/gutenberg/pull/44770#issuecomment-1289580712

**Comment by paaljoachim** [comment]
It would be nice to have the black sidebar site name (beside the WP logo) clickable so that it goes to the frontend.

Similar to clicking the site title Easy Web Design Tutorials seen in this screenshot.
![Screenshot 2022-10-26 at 19 43 20](https://user-images.githubusercontent.com/5323259/198098353-0238cb16-d5ab-4bfc-a3d6-40ed66ccd7d6.jpg)

**Comment by youknowriad** [comment]
I've just updated this issue and added a list of todo list items. The first step has been merged in #44770 we have now a number of follow-ups to work on. One of the first one is the addition of the template list to the sidebar #45100

**Comment by youknowriad** [comment]
Small update: the template list has been moved to the sidebar in #45100

**Comment by afercia** [comment]
Kindly asking to add https://github.com/WordPress/gutenberg/issues/46509 to the todo list items.

**Comment by youknowriad** [comment]
Some updates here:

 - Aria region navigation is fixed in the site editor
 - I'm re-working the canvas resizing (exclusive to template parts right now) in #46466 
 - @jorgefilipecosta is working on bringing the navigation menus to the site editor sidebar.

**Comment by youknowriad** [comment]
Small update:

 - I've started working on the new designs for the "edit" button and the sidebar in #46700
 - I'll pause working on the canvas resizing until the "edit" button PR lands because it impacts the CSS structure of the page a bit.

**Comment by youknowriad** [comment]
Another update here:

- After receiving some feedback about the "edit" button not clear enough, and not contextual enough. We've added a "hub" to the sidebar of the browse mode to show the active template and the edit button. We shipped these updates in #46700 and #46736 

- We also fixed the lingering block appender in "view" mode in #46763 

Overall, the experience is really solid now.

**Comment by youknowriad** [comment]
Some updates here:

 - we can now move the separator between the sidebar and the frame (we can resize the frame)
 - The "edit" mode is persisted in the URL, so you can refresh the page and keep the state.

**Comment by getdave** [comment]
Please note that Nav Offcanvas is [looking to come out of experimental](https://github.com/WordPress/gutenberg/pull/46995) which may affect this effort.

**Comment by annezazu** [comment]
Wanted to note feedback here that a few folks, [including in the latest call for testing](https://make.wordpress.org/test/2023/01/11/fse-program-testing-call-20-find-your-style/#comment-2905), have asked about having the three dot menu icon next to the templates and template parts while in browse mode. I both see designs that include that as an option and designs that don't along with this note "Move template search, save indicator to the sidebar (potentially clear customization)". 

>Here I expect to see 3 dots as can be seen in the Manage all templates screen. Perhaps these lists should be similar to the List View with the 3 dots and drag and drop.

@youknowriad can you clarify if this is being currently explored or whether it makes sense to open an issue for now otherwise in case it continues to come up? To be clear, talking about this:

<img width="321" alt="Screen Shot 2023-01-22 at 11 36 05 PM" src="https://user-images.githubusercontent.com/26996883/213987172-7049e1af-10a1-41c4-a52b-8e075a6a8328.png">

**Comment by youknowriad** [comment]
@annezazu There's a todo item on the issue about this but so far management tasks like this has been considered to be "advanced tasks" that you can see in the "manage templates" page instead of the sidebar where it's mostly about navigation. I think at the moment, there are still uncertainties around this and I'm basically waiting for more clarity from designers.

**Comment by getdave** [comment]
@youknowriad Would you now consider this complete?

**Comment by mtias** [comment]
No, I think we need to still work on the nav structure setup which hit a lot of hiccups when integrating.

**Comment by getdave** [comment]
Ok thanks for clarifying. So this is only complete once the Navigation aspect of Browse mode has fully landed and is stable in the Plugin.

**Comment by annezazu** [comment]
In trying to do a phase 2 update, it seems the remaining item to complete (Navigation aspect of browse mode) now has its own dedicated issue: https://github.com/WordPress/gutenberg/issues/50396. In light of that and with no remaining work to be done here, can we close this out and defer to the dedicated issue?

**Comment by scruffian** [comment]
I agree with @annezazu that this can be closed.

**Comment by Auxin1296** [comment]
#36667

**Comment by pbearne** [comment]
Can we add this ticket as feature request https://core.trac.wordpress.org/ticket/19867
