### ISSUE TITLE
Tracking: Refining Border Controls

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#37339]
This issue aims to map out what may be required to implement the proposed border control refinements in https://github.com/WordPress/gutenberg/issues/35602.

Additional background on the process behind the current border controls design can be read in the following post: 
[Thinking Through: WordPress Border Controls](https://shaunandrews.com/2021/10/gutenberg-border-controls/)

## Potential Tasks

- [x] Update block support to allow individual borders per side
- [x] Update theme.json and global styles for individual borders
- [x] Create new border control as per [#35602](https://github.com/WordPress/gutenberg/issues/35602)
- [ ] Finish off [API to access global styles](https://github.com/WordPress/gutenberg/pull/34178) values within the block editor
- [ ] Leverage [new API](https://github.com/WordPress/gutenberg/pull/34178) to apply global styles values as defaults within block support controls
- [ ] Move border radius to Dimensions panel and rename to "Radius"
- [ ] Update the `ToolsPanel` to allow toggling of single control via +/- icons 

## Future Considerations

- Border image - will this be an alternate state for the new border control or its own control?

## Historical Links For Context

- https://github.com/WordPress/gutenberg/pull/36942
- https://github.com/WordPress/gutenberg/pull/33743
- https://github.com/WordPress/gutenberg/issues/31337
- https://github.com/WordPress/gutenberg/pull/31585
- https://github.com/WordPress/gutenberg/issues/29616
- https://github.com/WordPress/gutenberg/pull/30124
- https://github.com/WordPress/gutenberg/issues/21540
- https://github.com/WordPress/gutenberg/pull/34178

**Comment by youknowriad** [comment]
Is this issue still relevant?

**Comment by aaronrobertshaw** [comment]
I believe we've settled on Border Radius controls staying under the current Border and Shadow panel. I'll close this.
