### ISSUE TITLE
Tracking: Theme.json schema block properties updates

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#37735]
This issue will track the changes required to address #36630 on a per bock basis.

Each block needs to have its settings property checked to confirm what properties are actually supported in the block. For example, the `core/button` blocks `border` setting only supports the `radius` property so only that property should be added to its entry under the `settingsBlocksPropertiesComplete` property - see https://github.com/WordPress/gutenberg/pull/36746/files#diff-65c0d061536e5fa3369aba19faf1f475337c549f26828424fa224908f0bcf137R373-R394

## Existing Blocks

- [x] core/archives
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/audio
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/block
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/button
    - [x] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/buttons
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/calendar
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/categories
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/code
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/column
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/columns
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comment-author-avatar
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comment-author-name
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comment-date
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comment-content
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comment-edit-link
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comment-reply-link
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comment-template
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/comments-query-loop
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/cover
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/embed
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/file
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/freeform
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/gallery
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/group
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/heading
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/home-link
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/image
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/latest-comments
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/latests-posts
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/list
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/loginout
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/media-text
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/missing
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/more
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/navigation
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/navigation-link
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/nextpage
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/page-list
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/paragraph
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-author
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-comments
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-comments-count
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-comments-form
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-comments-link
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-content
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-date
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-excerpt
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-featured-image
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-navigation-link
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-template
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-terms
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/post-title
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/preformatted
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/pullquote
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/query
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/query-pagination
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/query-pagination-next
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/query-pagination-numbers
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/query-pagination-previous
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/query-title
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/quote
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/rss
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/search
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/separator
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/shortcode
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/site-logo
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/site-tagline
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/site-title
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/social-link
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/social-links
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/spacer
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/table
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/table-of-contents
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/tag-cloud
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/template-part
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/term-description
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/text-columns
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/verse
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/video
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/widget-area
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/legacy-widget
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing 
- [ ] core/widget-group
    - [ ] border
    - [ ] color
    - [ ] typepography
    - [ ] spacing

**Comment by ryanwelcher** [comment]
#36746 addressed the border property for the `core/button` block

**Comment by carolinan** [comment]
I am trying to understand how I can contribute to this, can you provide more details?
"Each block needs to have its settings property checked to confirm what properties are actually supported in the block."

Can this be automated? Because of course there will be more changes made to the block properties as the experimental features change.

If not. perhaps there should also be a checkbox in the pull request template, to encourage contributors to update the schema when they commit changes to the block.

**Comment by carolinan** [comment]
Is this the part that needs to be updated? For each block?
https://github.com/WordPress/gutenberg/pull/36746/files#diff-65c0d061536e5fa3369aba19faf1f475337c549f26828424fa224908f0bcf137R373-R394

**Comment by ryanwelcher** [comment]
> Can this be automated? Because of course there will be more changes made to the block properties as the experimental features change.
> 
> If not. perhaps there should also be a checkbox in the pull request template, to encourage contributors to update the schema when they commit changes to the block.

I'm not sure how much we can automate here, some blocks have explicit entries in their `supports` object that we can use ( i.e [the button block defines` border.radius`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/button/block.json#L81) ) but other settings, such as color,  are not as clear to determine if they are supported without setting up a theme.json and seeing what happens. 

I have been doing this all manually for now and keeping track of it in gist files for now. This is a large initial effort but once we're done I love the idea of adding a checklist item to update the schema moving forward.

**Comment by ryanwelcher** [comment]
> Is this the part that needs to be updated? For each block? https://github.com/WordPress/gutenberg/pull/36746/files#diff-65c0d061536e5fa3369aba19faf1f475337c549f26828424fa224908f0bcf137R373-R394

Yes! That's the example I'd refer to. Sorry it was not made clear in the issue description what needs to be done.

**Comment by ryanwelcher** [comment]
@ajlende it looks like some blocks ( i.e `core/archives` ) don't support any setting overrides at all.

In that case, I am thinking we should keep the reference to the block but add a description to it to indicate that it doesn't support any overrides.

What do you think of omething like the following? The messaging probably need some workshopping but that's the idea

```json
"settingsBlocksPropertiesComplete": {
    "type": "object",
    "properties": {
        "core/archives": {
           "description": "As of WordPress 5.9, this block does not support any settings overrides",
            "additionalProperties": false
        }
   }
}
```

**Comment by carolinan** [comment]
I don't think it is 100% clear what a "setting override" is.
I mean there is filtering the block, and then there is setting true, false or null values in theme.json, and the latter is not overriding, is it? 🤔

**Comment by ryanwelcher** [comment]
> I don't think it is 100% clear what a "setting override" is.

Maybe`block-level settings`?

**Comment by ryanwelcher** [comment]
> I don't think it is 100% clear what a "setting override" is. I mean there is filtering the block, and then there is setting true, false or null values in theme.json, and the latter is not overriding, is it? 🤔

I guess my thought there was that it was overriding the top-level `settings` object setting in theme.json. i.e `settings.border.radius` is true but then a block can disabled/override that setting with `settings.block.{blockname}.border.radius` being set to false

**Comment by ryanwelcher** [comment]
@carolinan I added the approach above to #37778 so we can iterate there. Thanks for the feedback!

**Comment by ajlende** [comment]
> > Can this be automated? Because of course there will be more changes made to the block properties as the experimental features change.
>
>  ...some blocks have explicit entries in their `supports` object that we can use ( i.e the button block defines border.radius ) but other settings, such as color, are not as clear to determine if they are supported without setting up a theme.json and seeing what happens.

@carolinan I think it would be a good idea to generate the entire theme.json from source as much as we can. The [tsconfig-reference](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/tsconfig-reference) seems to be the most advanced that I've seen in that aspect, so it can be used as a reference for our own automation. They generate some documentation from source, but they have a [tsconfigRules.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/scripts/tsconfigRules.ts) that augments and adds additional context to what can be generated from source.

To @ryanwelcher's point, we could maybe generate the things we can from `supports` and add in the rest with a themeJsonRules.js file.

> If not. perhaps there should also be a checkbox in the pull request template, to encourage contributors to update the schema when they commit changes to the block.

I would approve a PR that adds that as an easy first step for now.

**Comment by ryanwelcher** [comment]
Created #37780 for the checklist update.

**Comment by ajlende** [comment]
> In that case, I am thinking we should keep the reference to the block but add a description to it to indicate that it doesn't support any overrides.
>
> What do you think of something like the following? "As of WordPress 5.9, this block does not support any settings overrides"

I think noting that in the description is better than removing the block entirely. Just a couple suggestions for workshopping the wording.

1. These descriptions are for the block, so some additional context for what the block is could be useful. Maybe just copied from the block.json description with the note about no properties afterward. This would be easy to do with automation when we get there too.
2. I think referencing the WordPress version is unnecessary—the schema is already versioned with git tags.

So maybe "Archive block. Display a monthly archive of your posts. This block has no block-level settings." or something?

**Comment by ryanwelcher** [comment]
> So maybe "Archive block. Display a monthly archive of your posts. This block has no block-level settings." or something?

Works for me! I've updated the PR #37778

**Comment by youknowriad** [comment]
It seems like this per-block audit never got traction (2 of 408 items in four years), and the schema now intentionally references the complete settings set for every block. Do we need to keep this issue open?
