### ISSUE TITLE
Global Styles Typography

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#38534]
#### Fonts

Managing fonts as site assets still needs a more formal proposal but broadly speaking the design would incorporate a recognizable small preview. This is the corollary to the palette management interface. These sets would be extensible and configurable, ranging from a single default set (current state) to multiple choices.

![image](https://user-images.githubusercontent.com/548849/132197992-7b6b72e7-181e-4a0e-919b-bf24383f2589.png)

With support for additional pairings and browsing the UI would evolve to accommodate it. There's a larger surface of issues to work through and figure out when it comes to themes switching and the ability to combine sets from different themes or styles.

![image](https://user-images.githubusercontent.com/548849/132197832-82bc6ead-5eeb-4bea-b26c-cbffe3d05b98.png)

An interface for selecting font families is still upcoming as there are quite a few details to get right, including communicating potential performance impact of multiple fonts.

#### Managing Webfonts

- [x] #37140
- [ ] Display font and font pair previews.
- [x] Implement UI for selecting and managing fonts.
- [x] Allow users to upload font assets not coupled to a theme.
- [ ] #39981

### Typography Tools

- [x] #41049

#### Writing Settings

- [x] #37462
