### ISSUE TITLE
Audit block escaping issues

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#38568]
The following PRs introduces regressions in output of markup on the front of the site. This was due to overzealous escaping of Core functions which in hindsight was not a good idea. I apologise for this.

This Issue tracks an audit of each PR. Any escaping of core functions will be revert in [#38569](https://github.com/WordPress/gutenberg/pull/38569) unless otherwise noted:

- [x]  https://github.com/WordPress/gutenberg/pull/37834 - no Core functions escaped. 
- [x]  https://github.com/WordPress/gutenberg/pull/37835 -  no Core functions escaped. 
- [x]  https://github.com/WordPress/gutenberg/pull/37860 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37865 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37866 - fixed in [#38145](https://github.com/WordPress/gutenberg/pull/38145) + additional fixes in `#38568`
- [x]  https://github.com/WordPress/gutenberg/pull/37870 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37873 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37874 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37875 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37876 - reverting in `#38567` and also in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37877 - fixed in `#38519`.
- [x]  https://github.com/WordPress/gutenberg/pull/37878 - fixed in `#38117`
- [x]  https://github.com/WordPress/gutenberg/pull/37879 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37880 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37881 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37882 - no Issues identified.
- [x] Post Pagination - fixed in [`#38519`](https://github.com/WordPress/gutenberg/pull/38519)

**Comment by getdave** [comment]
All of the above blocks whose escaping logic was originally modified have been audited and fixes have been merged in https://github.com/WordPress/gutenberg/pull/38569. 

Essentially the issue was that the original PRs were overzealous in escaping the output of Core functions, many of which could be filtered. 

**Takeaway**: do not blanket escape output of Core functions if they are outputted as HTML content. Rather be selective - sometimes `wp_kses` will be appropriate but other times it's best simply to trust the Core function.
