### ISSUE TITLE
BaseControl: Deprecate bottom margin

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#38730]
## What problem does this address?

The `BaseControl` component currently has an [inherent `margin-bottom`](https://github.com/WordPress/gutenberg/blob/fdce407ae43fc121f36797b96e6d808ed1f3077e/packages/components/src/base-control/styles/base-control-styles.js#L19), making it hard to reuse in different contexts, since it requires a style override of an internal element. This kind of internal override is something we want to discourage.

Additionally, the current margin-bottom leads to inconsistent results when `help` text is supplied, because the margin is inserted _before_ and not after the help text.

## What is your proposed solution?

Deprecate the bottom margin (similar to #37160), following the [guidelines](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CONTRIBUTING.md#deprecating-styles) stipulated in the devdocs.

Because this change impacts a large number of components (even just inside the Gutenberg codebase), I suggest we approach this in phases:

- [x] 1. Add a `__nextHasNoMarginBottom` prop to BaseControl to opt-in to the correct styles, without adding a deprecation warning
  - [x] BaseControl #39325
  - [x] CheckboxControl #43720
  - [x] ComboboxControl #43165
  - [x] DimensionControl #64346
  - [x] FocalPointPicker #43996
  - [x] RadioControl (cleanup of ad hoc override styles) #43868
  - [x] RangeControl #43062
  - [x] SearchControl #43871
  - [x] SelectControl #41269
  - [x] TextControl #43782
  - [x] TextareaControl #43782
  - [x] ToggleControl (also [tweak spacing before help text](https://github.com/WordPress/gutenberg/pull/39209#issuecomment-1072175095)) #43717
  - [x] ToggleGroupControl #43062
  - [x] TreeSelect (Based on SelectControl)
- [x] 2. Migrate all usages in the Gutenberg codebase (some components may require official deprecations)
  - [x] CheckboxControl #45434
  - [x] ComboboxControl #45796
  - [x] FocalPointPicker #45958
  - [x] RadioControl (cleanup of adhoc override styles) #43868
  - [x] RangeControl #45985
  - [x] SearchControl #46081
  - [x] SelectControl #46448 
  - [x] TextControl
	  - [x] #47157
	  - [x] #47158
	  - [x] #47160
	  - [x] #47161
  - [x] TextareaControl #46559
  - [x] ToggleControl #47866
  - [x] ToggleGroupControl #47269
  - [x] TreeSelect (Based on SelectControl) #47515
  - Other usages in Block Editor, Block Library, and Edit Site packages (TBD)
	  - [x] URLInput #46692
	  - [x] FontFamilyControl #64280
- [x] 3. Add eslint rules to prevent backslides within the Gutenberg codebase
  - [x] BaseControl #64355
  - [x] CheckboxControl #63679
  - [x] ComboboxControl #63679
  - [x] DimensionControl #64346 
  - [x] FocalPointPicker #63633
  - [x] RangeControl #63821 
  - [x] SearchControl #63679
  - [x] SelectControl #64283
  - [x] TextControl #64212
  - [x] TextareaControl #63633
  - [x] ToggleControl #64213
  - [x] ToggleGroupControl #63960
  - [x] TreeSelect #63633
- [x] 4. Add an official deprecation warning for `BaseControl`, with a relatively long grace period #64408

## ✍️ Dev Note (WordPress 6.2 release)

A number of UI components currently ship with styles that give them top and/or bottom margins. This can make it hard to reuse them in arbitrary layouts, where you want different amounts of gap or margin between components.

To better suit modern layout needs, we will gradually deprecate these outer margins. A deprecation will begin with an opt-in period where you can choose to apply the new margin-free styles on a given component instance. Eventually in a future version, the margins will be completely removed.

Continuing the effort started in previous releases, for the WordPress 6.2 release we focused on the `BaseControl` component and its consumers. While the effort is still ongoing, the outer margins on the following components have been deprecated.

- `BaseControl`
- `CheckboxControl`
- `ComboboxControl`
- `FocalPointPicker`
- `RadioControl`
- `RangeControl`
- `SearchControl`
- `SelectControl`
- `TextControl`
- `TextareaControl`
- `ToggleControl`
- `ToggleGroupControl`
- `TreeSelect`

To start opting into the new margin-free styles, set the `__nextHasNoMarginBottom` prop to `true`.

```jsx
<SelectControl
  options={ selectOptions }
  value={ selectValue }
  label={ __( 'Label' ) }
  onChange={ onSelectChange }
  __nextHasNoMarginBottom={ true }
/>
```

We're in the process of migrating all internal usages to use the new `__nextHasNoMarginBottom` prop. Once all usages are migrated, an official deprecation will be added to the `BaseControl` component

**Comment by ciampo** [comment]
Just flagging that, with #41269, the `__nextHasNoMarginBottom` prop was added to the `SelectControl` component.

**Comment by ciampo** [comment]
Related:
- https://github.com/WordPress/gutenberg/issues/49796
