### ISSUE TITLE
Migrate E2E tests to Playwright

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/gutenberg#38851]
This issue tracks progress on migrating Gutenberg's E2E tests from Puppeteer (`packages/e2e-tests`) to Playwright (`test/e2e`).

Resources:

- [Migrating WordPress E2E tests to Playwright](https://make.wordpress.org/core/2022/03/23/migrating-wordpress-e2e-tests-to-playwright/)
- [End-to-End Testing](https://developer.wordpress.org/block-editor/contributors/code/testing-overview/e2e/)
- [Migration guide](https://developer.wordpress.org/block-editor/contributors/code/testing-overview/e2e/migration/)
- [Overusing snapshots](https://developer.wordpress.org/block-editor/contributors/code/testing-overview/e2e/overusing-snapshots/)
- #38570
- [Meeting notes: Discussion about Playwright as the e2e framework for WordPress](https://make.wordpress.org/test/2022/01/21/meeting-notes-discussion-about-playwright-migration/)
- [Proposal: Migrate e2e to Playwright!](https://make.wordpress.org/test/2021/10/04/proposal-migrate-e2e-to-playwright/)

### Flaky tests

These tests are ranked by their estimated flaky rates. Experience developers should prioritize migrating them in this order.

- [x] `editor/blocks/image.test.js` (#40804)
- [x] `site-editor/template-part.test.js` (#41048)
- [x] `editor/various/post-editor-template-mode.test.js` (#40175)
- [x] `site-editor/template-revert.test.js` (#41310)
- [x] `site-editor/document-settings.test.js` (#40258)
- [x] `editor/various/preview.test.js` (#41380)
- [x] `editor/blocks/navigation.test.js` (#45070)
- [x] `editor/blocks/gallery.test.js` (#45202)
- [x] `editor/plugins/templates.test.js` (#45393)
- [x] `editor/various/list-view.test.js` (#47919)
- [x] `editor/plugins/iframed-multiple-block-stylesheets.test.js` ( #55003) (#45622)
- [x] `site-editor/style-variations.test.js` (#41427)
- [x] `site-editor/settings-sidebar.test.js` (#46174) (#57392)
- [x] `editor/various/autosave.test.js` (#49026) (#58171)
- [x] `experiments/blocks/comments-query.test.js` (#39826)
- [x] `editor/various/writing-flow.test.js` (#43637)
- [x] `editor/various/taxonomies.test.js` (#57662)
- [x] `editor/various/block-grouping.test.js` (#57684)
- [x] `editor/various/change-detection.test.js` (#58767)
- [x] `editor/various/publish-button.test.js` (#52285)
- [x] `editor/various/toolbar-roving-tabindex.test.js` (#46634)
- [x] `widgets/editing-widgets.test.js` (#57483)
- [x] `editor/blocks/list.test.js` (#41555)
- [x] `editor/various/embedding.test.js` (#57969)
- [x] `editor/various/inserting-blocks.test.js` (#58108)
- [x] `editor/various/block-editor-keyboard-shortcuts.test.js` (#57422)
- [x] `editor/various/multi-block-selection.test.js` (#48035)
- [x] `editor/plugins/custom-post-types.test.js` (#50031)
- [x] `editor/various/block-deletion.test.js` (#48012)
- [x] `editor/blocks/classic.test.js` (#46689)
- [x] `editor/blocks/post-title.test.js` (#55297)
- [x] `editor/blocks/group.test.js` (#42801)
- [x] `editor/blocks/site-title.test.js` (#55704)
- [x] `editor/plugins/iframed-inline-styles.test.js` (#44498) (#55009)
- [x] `editor/plugins/meta-boxes.test.js` (#41519)
- [x] `editor/various/copy-cut-paste-whole-blocks.test.js` (#39807)
- [x] `editor/various/draggable-block.test.js` (#43798)
- [x] `editor/various/keyboard-navigable-blocks.test.js` (#54944)
- [x] `editor/various/links.test.js` (#50996)
- [x] `editor/various/manage-reusable-blocks.test.js` (#45621)
- [x] `editor/various/rich-text.test.js` (#53493)
- [x] `editor/various/undo.test.js` (#48701)
- [x] `site-editor/multi-entity-saving.test.js` (#52372)
- [x] `site-editor/site-editor-export.test.js` (#56675)
- [x] `widgets/customizing-widgets.test.js` (#39540)

### Other tests

These tests don't have corresponding flaky reports. Newcomers can start migrating these since they are more stable and probably easier to start with.

- [x] `editor/blocks/buttons.test.js` (#41494)
- [x] `editor/blocks/code.test.js` (#41136)
- [x] `editor/blocks/columns.test.js` (#43964)
- [x] `editor/blocks/cover.test.js` (#45784)
- [x] `editor/blocks/heading.test.js` (#47955)
- [x] `editor/blocks/html.test.js` (#41231)
- [x] `editor/blocks/missing.test.js` (#41680)
- [x] `editor/blocks/paragraph.test.js` (#40779)
- [x] `editor/blocks/preformatted.test.js` (#41128)
- [x] `editor/blocks/query.test.js` (#47995)
- [x] `editor/blocks/quote.test.js` (#46549)
- [x] `editor/blocks/separator.test.js` (#41130)
- [x] `editor/blocks/spacer.test.js` (#41590)
- [x] `editor/blocks/table.test.js` (#41945)
- [x] `editor/blocks/pullquote.test.js` (#50085)
- [x] `editor/plugins/align-hook.test.js` (#56480)
- [x] `editor/plugins/allowed-blocks.test.js` (#53171)
- [x] `editor/plugins/annotations.test.js` (#55966)
- [x] `editor/plugins/block-api.test.js` (#40217)
- [x] `editor/plugins/block-context.test.js`(#55793)
- [x] `editor/plugins/block-directory-add.test.js` (#56593)
- [x] `editor/plugins/block-icons.test.js` (#55501) (#56610)
- [x] `editor/plugins/block-variations.test.js` (#53266)
- [x] `editor/plugins/child-blocks.test.js` (#55199)
- [x] `editor/plugins/container-blocks.test.js` (#56141)
- [x] `editor/plugins/cpt-locking.test.js` (#55929)
- [x] `editor/plugins/custom-taxonomies.test.js` (#45178) (#56486)
- [x] `editor/plugins/deprecated-node-matcher.test.js` (#42759)
- [x] `editor/plugins/format-api.test.js` (#42035)
- [x] `editor/plugins/hooks-api.test.js` (#42584)
- [x] `editor/plugins/iframed-block.test.js` (#44164)
- [x] `editor/plugins/iframed-masonry-block.test.js` (##55016)
- [x] `editor/plugins/image-size.test.js` (#40467)
- [x] `editor/plugins/inner-blocks-allowed-blocks.test.js` (#51677)
- [x] `editor/plugins/inner-blocks-render-appender.test.js` (#55814)
- [x] `editor/plugins/meta-attribute-block.test.js` (##55830)
- [x] `editor/plugins/nonce.test.js` (#44929)
- [x] `editor/plugins/plugins-api.test.js` (#55958)
- [x] `editor/plugins/register-block-type-hooks.test.js` (#43170)
- [x] `editor/plugins/wp-editor-meta-box.test.js` (#41519)
- [x] `editor/various/a11y.test.js` (#39638) (#46038)
- [x] `editor/various/adding-inline-tokens.test.js` (#52020)
- [x] `editor/various/adding-patterns.test.js` (#50083)
- [x] `editor/various/allowed-patterns.test.js` (#57399)
- [x] `editor/various/block-hierarchy-navigation.test.js` (#51517)
- [x] `editor/various/block-locking.test.js` (#51541)
- [x] `editor/various/block-mover.test.js` (#42039)
- [x] `editor/various/block-switcher.test.js` (#50845) (#57381)
- [x] `editor/various/compatibility-classic-editor.test.js` (#43979)
- [x] `editor/various/convert-block-type.test.js` (#42760)
- [x] `editor/various/core-settings.test.js` (#46176) (#57581)
- [x] `editor/various/datepicker.test.js` (#57545)
- [x] `editor/various/dropdown-menu.test.js` (#57663)
- [x] `editor/various/duplicating-blocks.test.js` (#43171)
- [x] `editor/various/editor-modes.test.js` (#57574)
- [x] `editor/various/font-size-picker.test.js` (#46591)
- [x] `editor/various/format-library/text-color.test.js` (#55323)
- [x] `editor/various/fullscreen-mode.test.js` (#43963)
- [x] `editor/various/invalid-block.test.js` (#57508)
- [x] `editor/various/is-typing.test.js` (#56616)
- [x] `editor/various/keep-styles-on-block-transforms.test.js` (#49719)
- [x] `editor/various/manage-reusable-blocks.test.js` (#45621)
- [x] `editor/various/mentions.test.js` (#43064)
- [x] `editor/various/navigable-toolbar.test.js` (#51514)
- [x] `editor/various/new-post-default-content.test.js` (#45267)
- [x] `editor/various/new-post.test.js` (#39539)
- [x] `editor/various/nux.test.js` (#39772) (#57542)
- [x] `editor/various/pattern-blocks.test.js` (#58486)
- [x] `editor/various/popovers.test.js` (#39910)
- [x] `editor/various/post-visibility.test.js` (#44488)
- [x] `editor/various/preferences.test.js` (#57446)
- [x] `editor/various/publish-panel.test.js` (##57432)
- [x] `editor/various/publishing.test.js` (#57521)
- [x] `editor/various/rtl.test.js` (#41495)
- [x] `editor/various/scheduling.test.js` (#57539)
- [x] `editor/various/shortcut-help.test.js` (#53832)
- [x] `editor/various/sidebar-permalink.test.js` (#56253)
- [x] `editor/various/sidebar.test.js` (#57448)
- [x] `editor/various/splitting-merging.test.js` (#44916)
- [x] `editor/various/style-variation.test.js` (#40216)
- [x] `editor/various/switch-to-draft.test.js` (#48120)
- [x] `editor/various/typewriter.test.js` (#57673)
- [x] `local/demo.test.js` (#55054)
- [x] `performance/post-editor.test.js` (#51084) (#52022)
- [x] `performance/site-editor.test.js` (#51084) (#52022)
- [x] `site-editor/iframe-rendering-mode.test.js` (#44535)
- [x] `site-editor/multi-entity-saving.test.js` (#52372) (#56670)
- [x] `site-editor/site-editor-inserter.test.js` (#44507)

### Performance tests

- [x] `packages/e2e-tests/specs/performance` (#51084, #52022)

**Comment by JustinyAhin** [comment]
## In `e2e-test-utils-playwright`

- [ ] activate-plugin.js
- [ ] activate-theme.js
- [ ] are-pre-publish-checks-enabled.js
- [ ] auto-accept-page-dialogs.js
- [ ] canvas.js
- [ ] change-site-timezone.js
- [ ] clear-local-storage.js
- [ ] click-block-appender.js
- [ ] click-block-toolbar-button.js
- [ ] click-button.js
- [ ] click-menu-item.js
- [ ] click-on-close-modal-button.js
- [ ] click-on-more-menu-item.js
- [ ] create-new-post.js
- [ ] create-reusable-block.js
- [ ] create-url.js
- [ ] create-user.js
- [ ] deactivate-plugin.js
- [ ] delete-theme.js
- [ ] delete-user.js
- [ ] disable-pre-publish-checks.js
- [ ] drag-and-resize.js
- [ ] enable-pre-publish-checks.js
- [ ] ensure-sidebar-opened.js
- [ ] find-sidebar-panel-toggle-button-with-title.js
- [ ] find-sidebar-panel-with-title.js
- [ ] get-all-block-inserter-item-titles.js
- [ ] get-all-blocks.js
- [ ] get-available-block-transforms.js
- [ ] get-block-setting.js
- [ ] get-current-post-content.js
- [ ] get-current-user.js
- [ ] get-edited-post-content.js
- [ ] get-option.js
- [ ] get-page-error.js
- [ ] has-block-switcher.js
- [ ] index.js
- [ ] inserter.js
- [ ] install-plugin.js
- [ ] install-theme.js
- [ ] is-current-url.js
- [ ] is-in-default-block.js
- [ ] list-view.js
- [ ] login-user.js
- [ ] menus.js
- [ ] observe-focus-loss.js
- [ ] offline-mode.js
- [ ] open-document-settings-sidebar.js
- [ ] open-publish-panel.js
- [ ] open-typography-tools-panel-menu.js
- [ ] plugins.js
- [ ] posts.js
- [ ] press-key-times.js
- [ ] press-key-with-modifier.js
- [ ] preview.js
- [ ] publish-post-with-pre-publish-checks-disabled.js
- [ ] publish-post.js
- [ ] rest-api.js
- [ ] save-draft.js
- [ ] select-block-by-client-id.js
- [ ] set-browser-viewport.js
- [ ] set-option.js
- [ ] set-post-content.js
- [ ] show-block-toolbar.js
- [ ] site-editor.js
- [ ] switch-editor-mode-to.js
- [ ] switch-user-to-admin.js
- [ ] switch-user-to-test.js
- [ ] templates.js
- [ ] theme-installed.js
- [ ] toggle-more-menu.js
- [ ] toggle-preferences-option.js
- [ ] transform-block-to.js
- [ ] uninstall-plugin.js
- [ ] visit-admin-page.js
- [ ] wait-for-window-dimensions.js
- [ ] widgets.js
- [ ] wp-data-select.js

**Comment by JustinyAhin** [comment]
cc @kevin940726

**Comment by JustinyAhin** [comment]
## In `e2e-tests-playwright`

- [ ] Editor
    - [ ] Various
        - [ ] a11y.test.js
        - [ ] adding-inline-tokens.test.js
        - [ ] adding-patterns.test.js
        - [ ] allowed-patterns.test.js
        - [ ] autosave.test.js
        - [ ] block-deletion.test.js
        - [ ] block-editor-keyboard-shortcuts.test.js
        - [ ] block-grouping.test.js
        - [ ] block-hierarchy-navigation.test.js
        - [ ] block-mover.test.js
        - [ ] block-switcher.test.js
        - [ ] change-detection.test.js
        - [ ] compatibility-classic-editor.test.js
        - [ ] convert-block-type.test.js
        - [ ] copy-cut-paste-whole-blocks.test.js
        - [ ] core-settings.test.js
        - [ ] datepicker.test.js
        - [ ] draggable-block.test.js
        - [ ] dropdown-menu.test.js
        - [ ] duplicating-blocks.test.js
        - [ ] editor-modes.test.js
        - [ ] embedding.test.js
        - [ ] font-size-picker.test.js
        - [ ] fullscreen-mode.test.js
        - [ ] inserting-blocks.test.js
        - [ ] invalid-block.test.js
        - [ ] is-typing.test.js
        - [ ] keep-styles-on-block-transforms.test.js
        - [ ] keyboard-navigable-blocks.test.js
        - [ ] links.test.js
        - [ ] list-view.test.js
        - [ ] manage-reusable-blocks.test.js
        - [ ] mentions.test.js
        - [ ] multi-block-selection.test.js
        - [ ] navigable-toolbar.test.js
        - [ ] new-post-default-content.test.js
        - [ ] new-post.test.js
        - [ ] nux.test.js
        - [ ] popovers.test.js
        - [ ] post-editor-template-mode.test.js
        - [ ] post-visibility.test.js
        - [ ] preferences.test.js
        - [ ] preview.test.js
        - [ ] publish-button.test.js
        - [ ] publish-panel.test.js
        - [ ] publishing.test.js
        - [ ] reusable-blocks.test.js
        - [ ] rich-text.test.js
        - [ ] rtl.test.js
        - [ ] scheduling.test.js
        - [ ] shortcut-help.test.js
        - [ ] sidebar-permalink-panel.test.js
        - [ ] sidebar.test.js
        - [ ] splitting-merging.test.js
        - [ ] style-variation.test.js
        - [ ] taxonomies.test.js
        - [ ] toolbar-roving-tabindex.test.js
        - [ ] typewriter.test.js
        - [ ] undo.test.js
        - [ ] writing-flow.test.js

**Comment by JustinyAhin** [comment]
cc @kevin940726

**Comment by noisysocks** [comment]
I reformatted this issue a little bit, added some links, and un-checked all the checkboxes since, to my knowledge, we haven't merged anything that migrates any tests yet. (https://github.com/WordPress/gutenberg/pull/38570 is just the infrastructure.)

**Comment by noisysocks** [comment]
It would be nice to flag 🚩 which tests are [flaky](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BType%5D+Flaky+Test%22) so that we can prioritise them. That will show us if Playwright offers any improvements there.

**Comment by JustinyAhin** [comment]
I removed the e2e-utils checkboxes from the issue description, since they will be added if necessary when we are migrating tests.

**Comment by juhi123** [comment]
@JustinyAhin Can you please update the `README.md` and `MIGRATION.md` links in the description 

https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/MIGRATION.md
https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/README.md

**Comment by kevin940726** [comment]
@juhi123 Updated! Thanks!

**Comment by talldan** [comment]
I started looking at the second most flakey test (`site-editor/template-part.test.js`).

I hit a roadblock that I think is worth trying to solve early on while there's a chance to put the right structure in place.

The site editor is using an iframe for the editor canvas. Because of this, none of the existing test utils for interacting with the editor canvas can be used for site editor tests. That's because they all use `page.locator` and the like, while for an iframe `frameLocator` needs to be used to find the iframe first, and then `frame.locator` can be used to select elements inside the iframe.

It's clear this was also a problem in Puppeteer, most of the puppeteer site editor tests have duplicate utility functions in the test file.

I'm not all that familiar with playwright, but I wonder if it could be an option to move the canvas utils into a class and do something like the following:
```jsx
test.use( {
	editorCanvasUtils: async (
		{ page, pageUtils },
		use
	) => {
		await use(
			new EditorCanvasUtils( { page, pageUtils, isSiteEditor: true } )
		);
	},
} );
```

`EditorCanvasUtils` could have a private `canvas` property that uses either the iframe or the page depending on the `isSiteEditor` param. All utilities defined in the class then use `canvas.locator`.

**Comment by juhi123** [comment]
Hi @kevin940726 @JustinyAhin 👋 

I have migrated [image-size.test.js ](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/plugins/image-size.test.js) to Playwright, can you please review it and share your feedbacks https://github.com/WordPress/gutenberg/pull/40467

**Comment by juhi123** [comment]
Hi @JustinyAhin 👋 
I was wondering if we are still maintaining this list as it seems `editor/blocks/quote.test.js` this [test](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/specs/editor/blocks/quote.spec.js) is already migrated but not checked in the list.

**Comment by JustinyAhin** [comment]
Hello @juhi123.

Yes, this list is still our reference for tracking tests that are being migrated. I haven't done contributions to tests in a while because I switched jobs recently, and I'm still adapting to my new contribution schedules.

In the meantime, if you come across a test that is already migrated but not check, can you update it on the list? :)

**Comment by talldan** [comment]
I don't think Quote tests have been migrated yet, the old puppeteer tests are still present, and there are quite a lot of test cases that haven't been ported - https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/blocks/quote.test.js.

**Comment by juhi123** [comment]
Hey @JustinyAhin 
No problem, congratulations!

I can update but I don't think I have enough access to check the list as I am not able to click on that.

@talldan Yeah that's why I also got confused as it's still there, but I can see this in Playwright tests also 
https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/specs/editor/blocks/quote.spec.js

**Comment by talldan** [comment]
@juhi123 I don't think that's a migration, just someone decided to write an individual test in playwright. The other test cases still need to be migrated.

**Comment by Mamaduka** [comment]
I started working on the `editor/various/writing-flow.test.js` migration.

**Comment by Mamaduka** [comment]
I've updated the resource links to include new E2E tests handbook pages.

I would recommend it to anyone working or who already has a migration PR(s) to get familiar with the recommendations.

New resource links:

- [End-to-End Testing](https://developer.wordpress.org/block-editor/contributors/code/testing-overview/e2e/)
- [Migration guide](https://developer.wordpress.org/block-editor/contributors/code/testing-overview/e2e/migration/)
- [Overusing snapshots](https://developer.wordpress.org/block-editor/contributors/code/testing-overview/e2e/overusing-snapshots/)

**Comment by ndiego** [comment]
@Mamaduka @JustinyAhin I wanted to highlight here that the explanations page for [Automated Testing](https://developer.wordpress.org/block-editor/explanations/architecture/automated-testing/) is now outdated as mentioned here: https://github.com/WordPress/gutenberg/issues/48757

I am in favor of either updating the page or simply removing it if you all feel like the e2e resources should be simplified and kept in the [Testing Overview](https://developer.wordpress.org/block-editor/contributors/code/testing-overview/) section of the handbook. If removing the explanation doc is the desired outcome, let me know, and I can take care of that PR.

**Comment by Mamaduka** [comment]
Every end-to-end test has been migrated to the Playwright. Thank you everyone for contributing!

**Comment by kevin940726** [comment]
Thank you all! ❤️ 💯 

There is still some work left to do to clean up. We'll do them in follow-up PRs!
