### ISSUE TITLE
Block Themes tracking issue

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#39188]
This is an overview issue, tracking what features we are missing from block themes.

# High impact issues
- [ ] https://github.com/WordPress/gutenberg/issues/43852
- [ ] https://github.com/WordPress/gutenberg/issues/39142
- [x] https://github.com/WordPress/gutenberg/issues/4543
- [ ] https://github.com/WordPress/gutenberg/issues/42299
- [x] https://github.com/WordPress/gutenberg/issues/14744

Beyond this there are different areas which need addressing:

## Global Styles
By expanding the scope of Global Styles we make more tools available to themes through theme.json. This means that we can create more interesting themes without using CSS. The approach here is to add support for new features via the theme.json mechanism. Adding a UI for these settings is an additional step that should happen later:

- [ ] https://github.com/WordPress/gutenberg/issues/33447
- [ ] https://github.com/WordPress/gutenberg/issues/38534
- [x] https://github.com/WordPress/gutenberg/issues/40966
- [x] https://github.com/WordPress/gutenberg/issues/35114
- [ ] https://github.com/WordPress/gutenberg/issues/40181
- [ ] https://github.com/WordPress/gutenberg/issues/38862
- [ ] https://github.com/WordPress/gutenberg/issues/7551
- [x] https://github.com/WordPress/gutenberg/issues/30142
- [ ] https://github.com/WordPress/gutenberg/issues/42319
- [ ] Visual font management - https://github.com/WordPress/gutenberg/issues/38534
- [ ] https://github.com/WordPress/gutenberg/issues/42298
- [ ] https://github.com/WordPress/gutenberg/issues/37582
- [ ] https://github.com/WordPress/gutenberg/issues/49279
- [ ] https://github.com/WordPress/gutenberg/issues/57286
- We need block previews for block type customization
- More integration and guidelines for plugins

## Blocks
Block themes are limited by the abilities of the blocks they are composed of. By adding more features to blocks we can expand the scope of features in all themes. The navigation block is the most complex of all blocks - by pushing this block forward we can open possibilities for all blocks.

- [ ] https://github.com/WordPress/gutenberg/issues/38275
- [ ] https://github.com/WordPress/gutenberg/issues/36444
- [x] https://github.com/WordPress/gutenberg/issues/40762
- [ ] https://github.com/WordPress/gutenberg/issues/31446
- [ ] https://github.com/WordPress/gutenberg/issues/24952
- [ ] https://github.com/WordPress/gutenberg/issues/38796
- [ ] https://github.com/WordPress/gutenberg/issues/39380
- [ ] https://github.com/WordPress/gutenberg/issues/42296
- [x] https://github.com/WordPress/gutenberg/issues/42322
- [x] https://github.com/WordPress/gutenberg/issues/42330
- [ ] https://github.com/WordPress/gutenberg/issues/42332
- [ ] https://github.com/WordPress/gutenberg/issues/42339
- [x] https://github.com/WordPress/gutenberg/issues/34997
- [x] https://github.com/WordPress/gutenberg/issues/42416
- [ ] https://github.com/WordPress/gutenberg/issues/42444
- [ ] https://github.com/WordPress/gutenberg/pull/42015
- [ ] https://github.com/WordPress/gutenberg/issues/49249
- [ ] https://github.com/WordPress/gutenberg/issues/30701

## Templates
Templates should be portable between themes. Using templates from one theme in a different theme greatly expands the number of themes that can be created, through these combinations.
- [x] https://github.com/WordPress/gutenberg/issues/31954
- [x] https://github.com/WordPress/gutenberg/issues/25071
- [x] https://github.com/WordPress/gutenberg/issues/37407
- [ ] https://github.com/WordPress/gutenberg/issues/41257
- [ ] https://github.com/WordPress/gutenberg/issues/38413
- [x] https://github.com/WordPress/gutenberg/issues/19254
- [ ] https://github.com/WordPress/gutenberg/issues/41399
- [x] https://github.com/WordPress/gutenberg/issues/40791
- [x] https://github.com/WordPress/gutenberg/issues/41397
- [x] https://github.com/WordPress/gutenberg/issues/42130
- [x] https://github.com/WordPress/gutenberg/issues/36648
- [ ] https://github.com/WordPress/gutenberg/issues/42732

## Site Editor
The site editor is still immature compared to the Post Editor. We should add some of the same features that exist in the Post Editor to make it more powerful.
- [ ] Placeholder states for blocks https://github.com/WordPress/gutenberg/issues/19256
- [ ] https://github.com/WordPress/gutenberg/issues/39556
- [ ] https://github.com/WordPress/gutenberg/issues/29575
- [ ] https://github.com/WordPress/gutenberg/issues/29398
- [ ] https://github.com/WordPress/gutenberg/issues/28564
- [ ] https://github.com/WordPress/gutenberg/issues/42290
- [x] https://github.com/WordPress/gutenberg/issues/42316
- [ ] https://github.com/WordPress/gutenberg/issues/39068
- [x] https://github.com/WordPress/gutenberg/issues/41823
- [x] https://github.com/WordPress/gutenberg/issues/42226

## Theme switching
- [ ] https://github.com/WordPress/gutenberg/issues/39324

## Patterns
- [ ] https://github.com/WordPress/gutenberg/issues/39500
- [ ] https://github.com/WordPress/gutenberg/issues/42734

## Theme creation
- [x] https://github.com/WordPress/create-block-theme/issues/81
- [x] https://github.com/WordPress/create-block-theme/issues/80
- [ ] https://github.com/WordPress/gutenberg/issues/39196
- [ ] https://github.com/WordPress/gutenberg/issues/42730

We have a separate issue that tracks missing block supports:
https://github.com/WordPress/gutenberg/issues/41113

# Complete!
## Remove CSS from block themes
The immediate priority should be to make it possible to create workable themes without relying on CSS. The following issues need to be resolved to allow us to remove [this CSS](https://href.li/?https://github.com/WordPress/wordpress-develop/blob/e169c4923b9739ccd6b75ee2303dcc42779f50c7/src/wp-content/themes/twentytwentytwo/style.css) from Twenty Twenty Two:

- [x] https://github.com/WordPress/gutenberg/issues/27075
- [x] https://github.com/WordPress/gutenberg/issues/35607
