### ISSUE TITLE
Visual Theme Building Tracking Issue

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#39189]
Improving the export tools in the Site Editor to make them more useful to Theme Designers to update their themes and create new ones.

- [x] https://github.com/WordPress/gutenberg/pull/39173
- [x] https://github.com/WordPress/gutenberg/issues/39194
- [x] https://github.com/WordPress/gutenberg/issues/38199
- [x] https://github.com/WordPress/gutenberg/issues/38194
- [x] https://github.com/WordPress/gutenberg/issues/39190
- [x] https://github.com/WordPress/gutenberg/issues/39191
- [x] https://github.com/WordPress/gutenberg/issues/39193
- [ ] https://github.com/WordPress/gutenberg/issues/39195
- [ ] https://github.com/WordPress/gutenberg/issues/39196
- [x] https://github.com/WordPress/gutenberg/issues/27941

**Comment by Mamaduka** [comment]
I think we need to define what purpose current export functionality should serve. For example, is it for creating new themes or exporting modifications for the current theme?

I also wanted to mention this issue (#27941) by @mtias.

**Comment by scruffian** [comment]
> I think we need to define what purpose current export functionality should serve. For example, is it for creating new themes or exporting modifications for the current theme?

I agree. Could it be both?

**Comment by adamziel** [comment]
@scruffian is there any feature tracked here that you think could land until Wednesday next week to be included in WordPress 6.0 release? To increase visibility, we can add it to the [WordPress Editor 6.0 project board](https://github.com/orgs/WordPress/projects/27/views/1).

**Comment by scruffian** [comment]
@adamziel there are a few, but I have already added them to the board :)

**Comment by getdave** [comment]
> Save theme edits from the site editor to the theme files #39194

@scruffian should this be removed or marked as "for Plugin only" as I don't see this landing in Core any time soon. It feels like plugin territory.

**Comment by draganescu** [comment]
In the same note as @getdave 's comment should creating a new theme be considered as well? I think (see https://github.com/WordPress/gutenberg/issues/39194#issuecomment-1138294471) that this is plugin domain as well.

**Comment by scruffian** [comment]
I'm not sure, I feel like that is simple enough that it could be part of Gutenberg, but we probably shouldn't attempt it until it's possible to create a block theme without any CSS.

**Comment by mtias** [comment]
@scruffian should this be closed and moved to wherever the create-block-theme plugin home is?

**Comment by scruffian** [comment]
I think we can just close it.

**Comment by MaggieCabrera** [comment]
For reference in case someone comes looking, this should be tracked in [the plugin's repo](https://github.com/WordPress/create-block-theme)
