### ISSUE TITLE
Plugin: Backport PHP changes for WordPress 6.0 release

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#39889]
## Description

Related [Trac ticket 55505](https://core.trac.wordpress.org/ticket/55505).

This is the tracking issue to coordinate the process of backporting all PHP changes added in the Gutenberg plugin that needs to be backported for the WordPress 6.0 release. 

### [`lib/block-supports`](https://github.com/WordPress/gutenberg/tree/trunk/lib/block-supports)

- [x] 🟢 [border.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/border.php) |  [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2500) | Assigned @ramonjd 
- [x] 🟢 [colors.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/colors.php) |  [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2500) | Assigned @ramonjd 
- [x] 🟢 [dimensions.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/dimensions.php) |  [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2500) | Assigned @ramonjd 
- [x] 🟢 [duotone.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/duotone.php) | [Gutenberg backport PR from WordPress Core](https://github.com/WordPress/gutenberg/pull/40067) | assigned @ajlende 
- [x] 🟢 [elements.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/elements.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2500) | Assigned @ramonjd 
- [x] 🟢 [layout.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2518) | Assigned @ramonjd 
- [x] 🟢 [spacing.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/spacing.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2500) | Assigned @ramonjd 
- [x] 🟢 [typography.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/typography.php)  | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2500) | Assigned @ramonjd 
- [x] 🟢 [utils.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/utils.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2500) | Assigned @ramonjd 

### [`lib/compat/wordpress-6.0`](https://github.com/WordPress/gutenberg/tree/trunk/lib/compat/wordpress-6.0)

- [x] 🟢 [block-editor-settings.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/block-editor-settings.php) | Assigned @oandregal 
- [x] 🟢 [block-patterns.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/block-patterns.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2488) | Assigned: @hellofromtonya 
- [x] 🟢 [block-patterns-update.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/block-patterns-update.php) ([Block Patterns](https://github.com/WordPress/gutenberg/pull/39904#issuecomment-1084262971)) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2488) | Assigned: @hellofromtonya 
- [x] 🟢 [block-template-utils.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/block-template-utils.php) | Assigned @scruffian 
- [x] 🟢 [block-template.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/block-template.php) ([Resolve homepage template PR](https://github.com/WordPress/gutenberg/pull/38817)) | Assigned @Mamaduka
- [x] 🟢 [blocks.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/blocks.php) (Query Loop block) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2488) | Assigned: @hellofromtonya
- [-] 🔴 [blocks.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/blocks.php) (multiple view scripts) | Assigned: @gziolo
- [x] 🟢 [blocks.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/blocks.php) (core blocks) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2543) | Assigned: @DAreRodz 
- [x] 🟢  [class-gutenberg-rest-edit-site-export-controller.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-gutenberg-rest-edit-site-export-controller.php) | Assigned: @scruffian 
- [x] 🟢 [class-gutenberg-rest-global-styles-controller.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-gutenberg-rest-global-styles-controller.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2503) | Assigned: @youknowriad 
- [x] 🟢 [class-gutenberg-rest-pattern-directory-controller.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-gutenberg-rest-pattern-directory-controller.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2488) | Assigned: @hellofromtonya 
- [x] 🟢 [class-wp-rest-block-pattern-categories-controller.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-rest-block-pattern-categories-controller.php) (Block Patterns) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2488) | Assigned: @hellofromtonya 
- [x] 🟢 [class-wp-rest-block-patterns-controller.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-rest-block-patterns-controller.php) (Block Patterns) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2488) | Assigned: @hellofromtonya 
- [x] 🟢 [class-wp-theme-json-gutenberg.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-gutenberg.php) (([Theme Export](https://github.com/WordPress/gutenberg/pull/39842)) | Assigned @scruffian 
- [x] 🟢 [class-wp-theme-json-resolver-6-0.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-resolver-6-0.php) ([Style Variations i18n](https://github.com/WordPress/gutenberg/pull/39960))
- [x] 🟢  [client-assets.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/client-assets.php) ([React Fast Refresh]( https://github.com/WordPress/gutenberg/pull/28273)) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2519)  | Assigned: @gziolo
- [x] 🟢 [edit-form-blocks.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/edit-form-blocks.php) | Assigned @jsnajdr 
- [x] 🟢 [functions.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/functions.php) ([Theme Export](https://github.com/WordPress/gutenberg/pull/39842)) – there is also a unit test | assigned @scruffian 
- [x] [get-global-styles-and-settings.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/get-global-styles-and-settings.php) – all changes got backported to WordPress Core as part of 5.9.x releases
- [x] 🟢 [post-lock.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/post-lock.php) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2508) | Assigned: @Mamaduka
- [x] [rest-api.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/rest-api.php) – no need to backport anything here, it only registers local version of REST API controllers
- [x] 🟢 [theme-i18n.json](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/theme-i18n.json) ([Style Variations i18n](https://github.com/WordPress/gutenberg/pull/39960))| [WordPress Core backport commit](https://github.com/WordPress/wordpress-develop/commit/39a5bacbc1a3a1d6cfd535995d330094b4ad22f0) | assigned @gziolo

### [`lib/experimental`](https://github.com/WordPress/gutenberg/tree/trunk/lib/experimental)

Webfonts are still in development. PR #39559 moves the files into the `lib/experimentation` folder until the API is ready for WordPress Core commit:
- [ ] 🟡 [class-wp-theme-json-resolver-gutenberg.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-resolver-gutenberg.php) (Webfonts API, #39960) | [WordPress Core backport PR](https://github.com/WordPress/wordpress-develop/pull/2503)
- [ ] 🟡 [class-wp-webfonts-provider-local.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-webfonts-provider-local.php) (Webfonts API, #39888)
- [ ] 🟡 [class-wp-webfonts-provider.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-webfonts-provider.php) (Webfonts API, #39888)
- [ ] 🟡 [class-wp-webfonts.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-webfonts.php) (Webfonts API, #39888)
- [ ] 🟡 [register-webfonts-from-theme-json.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php)
- [ ] 🟡 [webfonts.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/webfonts.php) (Webfonts API,  #39888)

**Legend:**

🟢 – confirmed for WP 6.0
🟡 – needs the decision
🔴 – moved to future WP release

## Getting Involved

If you are interested in helping with the efforts, can you comment (or edit the issue's description) with your name next to the file if you plan to help with backporting. It would also help to link to Track issues / GitHub PRs in WordPress core when they are available.

Action items when working on backports:
- Update the files to follow [best practices](https://github.com/WordPress/gutenberg/tree/trunk/lib#best-practices). Mostly rename functions/classes to use `wp_` prefix instead of `gutenberg_` and guard with declaration checks for code that needs to be backported to WordPress core.
- Identify files and functionality that need to be backported to WordPress core.
- Ensure all files, classes, methods, properties, and functions have `@since 6.0.0` documentation tag included.
- Ensure all functionality backported to WordPress core has unit tests written.

**Comment by Mamaduka** [comment]
@gziolo, I can handle post lock PR for the WP core (mostly later this week).

**Comment by gziolo** [comment]
>  I can handle post lock PR for the WP core (mostly later this week).

Awesome, thank you @Mamaduka ❤️

**Comment by hellofromtonya** [comment]
✋ raising my hand to help with audits, prepping and reviewing the PHP code to be ready for Core commit (i.e. compliant with Core standards and practices). A request @peterwilsoncc made is to create smaller patches. I agree. I can help to create these smaller PRs to ease the code review and commit burden / effort.

**Comment by ramonjd** [comment]
> [class-wp-style-engine-gutenberg.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/style-engine/class-wp-style-engine-gutenberg.php) (Style Engine)

Thanks for pulling this together @gziolo 

We merged the [Style Engine class and associated tests](https://github.com/WordPress/gutenberg/pull/39446) with the intention of following up on @youknowriad's [suggestion](https://github.com/WordPress/gutenberg/pull/39446#issuecomment-1076050281) of moving it to the `style-engine` [package directory](https://github.com/WordPress/gutenberg/tree/trunk/packages/style-engine).

I've got a [WIP PR](https://github.com/WordPress/gutenberg/pull/39736) going to do this, following the example of how we copy, parse and build the block-library packages, but it's not ready yet.

If https://github.com/WordPress/gutenberg/pull/39736 doesn't look like making the cut, there are a couple of options I see, though I'd lean on @youknowriad's expert opinion.

1. We leave the Style Engine class and the related changes to `lib/block-supports/spacing.php` out of WordPress 6.0 (I am happy to take care of the revert `spacing.php` or whatever else needs to be done there) while we work out a decent way to include it from the packages directory.
2. We migrate it as-is and deal with subsequent changes in a later WordPress migration. 

I suppose I'd be inclined to do the former. The class doesn't bring any new functionality - it's more of a first iteration in a set of long-term changes.

**Comment by gziolo** [comment]
> 1. We leave the Style Engine class and the related changes to lib/block-supports/spacing.php out of WordPress 6.0 (I am happy to take care of the revert spacing.php or whatever else needs to be done there) while we work out a decent way to include it from the packages directory.
> 2. We migrate it as-is and deal with subsequent changes in a later WordPress migration.

Are there any functional changes for block supports introduced in WordPress 6.0 release cycle that need to be included? Maybe we can simply postpone backporting those refactoring until the Style Engine has a stable API. Option (2) doesn't seem like an appealing idea from the WordPress core perspective because we will have to support the current implementation even when the API changes completely. Unless you are sure that the public API of the class is going to stay like this.

**Comment by hellofromtonya** [comment]
[Trac ticket 55505](https://core.trac.wordpress.org/ticket/55505) is now opened for the `@wordpress` package updates and backporting the PHP changes to Core.

**Comment by ramonjd** [comment]
The last major update that I'm aware of was [Block Supports: Allow skipping serialization of individual features #36293](https://github.com/WordPress/gutenberg/pull/36293), which affected all block supports files.

@aaronrobertshaw do you see these changes as required for WordPress 6.0?

> Maybe we can simply postpone backporting those refactoring until the Style Engine has a stable API. 

Agree. What can I do to help here? 

Do you need me to roll back [the plugin integration of the Style Engine](https://github.com/WordPress/gutenberg/pull/39446/files#diff-0321a678e2795e0e5570dd728551f49256232729ccdabe171ce84d6de5d1a13b) from `spacing.php`?

I'm thinking we could also abstract the current logic that the Style Engine replaces (and will replace) to make this kind of swapping in and swapping out easier.

**Comment by aaronrobertshaw** [comment]
> The last major update that I'm aware of was https://github.com/WordPress/gutenberg/pull/36293, which affected all block supports files.
>
> @aaronrobertshaw do you see these changes as required for WordPress 6.0?

I'm not sure where to draw the line here. #36293 does give us much greater flexibility in applying block supports and fixes some oversights in existing supports that missed allowing skipping serialization.

It was also required for us to neatly [re-adopt text-decoration support for the navigation block](https://github.com/WordPress/gutenberg/pull/36345).

**Comment by gziolo** [comment]
In the meantime, I opened #39972 trying the remaining files living in the `lib` folder. I want to move them to proper subfolders so we exactly know whether they are still experimental, they were shipped in WordPress 5.9 or they should be backported to WordPress core as part of the 6.0 major release.

**Comment by oandregal** [comment]
> [class-wp-theme-json-resolver-gutenberg.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-resolver-gutenberg.php)

I'm not sure about the changes for the webfonts (`get_theme_data`) but we're adding some other changes for translating the style variations to that file ([see](https://github.com/WordPress/gutenberg/pull/39960)) which should go in WordPress 6.0.

**Comment by ramonjd** [comment]
I've added a backport PR for block supports `spacing.php` and `utils.php` over at https://github.com/WordPress/wordpress-develop/pull/2500 and put my name against it.

Includes the latest changes, that is allowing skipping serialization of individual properties, but removes the reference to the Style Engine. It's very minimal.

If I get time I can add migrations to border, color, dimensions, elements and typography and associated tests to that PR, since all rely on the new `utils.php` anyway. They seem to be all related and fairly straightforward.

I'd do `layout.php` separately as it contains a lot more changes.

**Comment by youknowriad** [comment]
I've opened this https://github.com/WordPress/wordpress-develop/pull/2503 to backport the "global styles variations" related tests. This includes some parts of the theme.json class changes and some parts of the global styles controller changes as well.

**Comment by adamziel** [comment]
I've combed through the files that didn't come up in the discussion and don't have anyone assigned in the issue description above. If your name or PR is on the list below, please reply with:

1) Do you want to include these changes in WordPress 6.0?
2) Do you have the availability to prepare a backport PR for [wordpress-develop](https://github.com/WordPress/wordpress-develop)?

### [lib/block-supports](https://github.com/WordPress/gutenberg/tree/trunk/lib/block-supports)

* [duotone.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/block-supports/duotone.php), changed in
    * https://github.com/WordPress/gutenberg/pull/36236
    * https://github.com/WordPress/gutenberg/pull/37954
    * https://github.com/WordPress/gutenberg/pull/38891
    * cc @ajlende @westonruter
* [typography.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/block-supports/typography.php), changed in
    * https://github.com/WordPress/gutenberg/pull/36293
    * cc @aaronrobertshaw @andrewserong @ramonjd

### [lib/compat/wordpress-6.0](https://github.com/WordPress/gutenberg/tree/trunk/lib/compat/wordpress-6.0)

* [block-editor-settings.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/block-editor-settings.php), changed in
    * #39185 
    * #39543
    * #39180
    * #39030 
    * cc @jsnajdr @Mamaduka @talldan @noisysocks @oandregal 
* [block-template-utils.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/block-template-utils.php), changed in 
    * #39751
    * #39471
    * #39202
    * #39173
    * #39048
    * cc @scruffian @oandregal @Mamaduka 
* [class-gutenberg-rest-edit-site-export-controller.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/class-gutenberg-rest-edit-site-export-controller.php), changed in
    * #39471
    * #39173
    * #39048
    * cc @scruffian @oandregal @Mamaduka 
* [class-wp-theme-json-gutenberg.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-gutenberg.php), changed in 
    * #39842
    * #39921
    * #39715
    * #39322
    * #38816
    * #39048
    * #38323
    * cc @scruffian @ramonjd @oandregal @ntsekouras 
* [edit-form-blocks.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/edit-form-blocks.php), changed in
    * #39185
    * #39470
    * #39256
    * cc @jsnajdr 
* [get-global-styles-and-settings.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/get-global-styles-and-settings.php), changed in
    * #38681
    * #38883
    * cc @ajlende @oandregal 
* [rest-api.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/rest-api.php), changed in
    * #39185
    * #39048
    * #38323
    * #38124
    * cc @jsnajdr @Mamaduka @oandregal @ntsekouras

**Comment by ramonjd** [comment]
> [typography.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/block-supports/typography.php), changed in
[Block Supports: Allow skipping serialization of individual features #36293](https://github.com/WordPress/gutenberg/pull/36293)
cc @aaronrobertshaw @andrewserong @ramonjd

For the "Allow skipping serialization of individual features" feature, I've pulled across _most_ of the related changes for `lib/block-supports` in https://github.com/WordPress/wordpress-develop/pull/2500

@aaronrobertshaw might want to take a look to confirm if things look okay 🙇 

Layout is notably absent on that PR as it involves changes beyond #36293 that need auditing.

_Edit:_ Just to clarify, I'll be adding the `layout.php` migration to https://github.com/WordPress/wordpress-develop/pull/2500 separately as it requires singular attention (it's a bigger diff). So it'll still be in that PR.

**Comment by ajlende** [comment]
> * [duotone.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/block-supports/duotone.php), changed in
>    * https://github.com/WordPress/gutenberg/pull/36236
>    * https://github.com/WordPress/gutenberg/pull/37954
>    * https://github.com/WordPress/gutenberg/pull/38891
>    * cc @ajlende @westonruter

> 1. Do you want to include these changes in WordPress 6.0?
> 2. Do you have the availability to prepare a backport PR for [wordpress-develop](https://github.com/WordPress/wordpress-develop)?

Yes and yes. I can make some time for opening a PR to backport duotone.php tomorrow.

**Comment by Mamaduka** [comment]
@ajlende, I think we backported those into a minor release, so they should be already in the WP trunk. At least the items I see on [that list](https://github.com/WordPress/gutenberg/issues/39889#issuecomment-1088256854). But I would recommend double-checking, just in case :)

**Comment by Mamaduka** [comment]
I created PR to backport Post Lock fixes - https://github.com/WordPress/wordpress-develop/pull/2508.

**Comment by gziolo** [comment]
> I created PR to backport Post Lock fixes - [WordPress/wordpress-develop#2508](https://github.com/WordPress/wordpress-develop/pull/2508).

Backported with https://core.trac.wordpress.org/changeset/53070.

**Comment by youknowriad** [comment]
> I've opened this https://github.com/WordPress/wordpress-develop/pull/2503 to backport the "global styles variations" related tests. This includes some parts of the theme.json class changes and some parts of the global styles controller changes as well.

This is now committed but when I compared the global styles controller files, I noticed the following small diff

https://github.com/WordPress/wordpress-develop/pull/2516

I wasn't able to find when we introduced this fallback in Gutenberg.

**Comment by Mamaduka** [comment]
> I wasn't able to find when we introduced this fallback in Gutenberg.

#38883

**Comment by gziolo** [comment]
> > [typography.php](https://github.com/WordPress/gutenberg/commits/trunk/lib/block-supports/typography.php), changed in
> > [Block Supports: Allow skipping serialization of individual features #36293](https://github.com/WordPress/gutenberg/pull/36293)
> > cc @aaronrobertshaw @andrewserong @ramonjd
> 
> For the "Allow skipping serialization of individual features" feature, I've pulled across _most_ of the related changes for `lib/block-supports` in [WordPress/wordpress-develop#2500](https://github.com/WordPress/wordpress-develop/pull/2500)

This is now committed with https://core.trac.wordpress.org/changeset/53076.

**Comment by ntsekouras** [comment]
>This is now committed but when I compared the global styles controller files, I noticed the following small diff

It was changed in core first and backported to GB here: https://github.com/WordPress/gutenberg/pull/38888

**Comment by ramonjd** [comment]
Deprecated block supports functions deleted in 

- https://github.com/WordPress/wordpress-develop/pull/2500

Now reinstated with deprecation notice in

- https://github.com/WordPress/wordpress-develop/pull/2522

**Comment by ajlende** [comment]
@Mamaduka  I confirmed the changes to duotone.php are already ported core. There were a couple things in core that weren't in the plugin, so I've opened https://github.com/WordPress/gutenberg/pull/40067 to bring them here.

**Comment by adamziel** [comment]
**Checklist for the block-editor-settings.php:**

[Changes before the move to lib/compat:](https://github.com/WordPress/gutenberg/blame/b828f5a1774324cf28f7c835d9ae456c03611176/lib/global-styles.php#L15)
- [x] #36327 by @oandregal – it seems to be affecting the part that wasn't backported to 5.9. @oandregal, do you want it to be backported to 6.0?
- [x] #38883 by @oandregal ([direct file link](https://github.com/WordPress/gutenberg/commit/74201dacd2c1a2f233e14d448e0e8d25ed5ba70d#diff-0b8e98dead5542e95159bd3c482158111d3f16637e7eef9af13373358fa42ded)) – looks like a plugin-specific change that  doesn't require backporting, 
- [x] #37885 by @oandregal seems to be already backported – the core file reflects that change

[Changes after the move to lib/compat:](https://github.com/WordPress/gutenberg/commits/trunk/lib/compat/wordpress-6.0/block-editor-settings.php)
- [x] #39030 by @oandregal is just a file move that doesn't seem to require a backport
- [x] #39180 by @talldan – I prepared a backport here: https://github.com/WordPress/wordpress-develop/pull/2523
- [x] #39543 by @scruffian affects the part of the code introduced 11 months ago in #31762 and not previously backported. @oandregal, is it fine to skip this one, or do you think this entire segment needs to be backported?
- [ ] #39185 by @jsnajdr that also introduces `WP_REST_Block_Pattern_Categories_Controller`, meaning it would make sense to backport these two together – cc @hellofromtonya

**Comment by Mamaduka** [comment]
> block-template.php (Resolve homepage template PR)

Done in https://github.com/WordPress/wordpress-develop/pull/2529

**Comment by scruffian** [comment]
> [functions.php](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/functions.php) (https://github.com/WordPress/gutenberg/pull/39842) – missing unit test

I added a unit test here: https://github.com/WordPress/gutenberg/pull/40149/files

**Comment by scruffian** [comment]
I've created a PR for the files listed against my name above (and a few extra connected changes)
https://github.com/WordPress/wordpress-develop/pull/2534

**Comment by gziolo** [comment]
We still need to backport code that was moved to `lib/compat/wordpress-6.0/blocks.php` in #40179 and introduced in https://github.com/WordPress/gutenberg/pull/36176 by @aristath:

- `wp_enqueue_block_view_script` function
- `gutenberg_block_type_metadata_multiple_view_scripts` filter's callback

**Comment by gziolo** [comment]
We will also have to backport code that is about to be moved to `lib/compat/wordpress-6.0/blocks.php` in https://github.com/WordPress/gutenberg/pull/40186:

- `build_comment_query_vars_from_block` function
- `get_comments_pagination_arrow` function
- `gutenberg_extend_block_editor_settings_with_discussion_settings ` filter's callback
- `gutenberg_rest_comment_set_children_as_embeddable` filter's callback
- [class-block-library-comment-template-test.php](https://github.com/WordPress/gutenberg/blob/trunk/phpunit/class-block-library-comment-template-test.php) unit test

**Comment by oandregal** [comment]
> lib/compat/wordpress-6.0/block-editor-settings.php | Assigned @oandregal

I've marked this as done as all changes are part of 5.9 or 6.0.

I'm creating a bugfix that modifies this code for something I ran into but can be done after the beta1. For reference, https://github.com/WordPress/wordpress-develop/pull/2542 and https://github.com/WordPress/gutenberg/pull/40185

**Comment by oandregal** [comment]
> https://github.com/WordPress/gutenberg/pull/36327 by @oandregal – it seems to be affecting the part that wasn't backported to 5.9. @oandregal, do you want it to be backported to 6.0?

This PR is trying to adapt from the changes in core. No need to backport.

> https://github.com/WordPress/gutenberg/pull/31762 and not previously backported. @oandregal, is it fine to skip this one, or do you think this entire segment needs to be backported?

Yeah, no need to backport this one. It's only relevant in relation to a REST endpoint that mobile uses that is yet experimental ([see](https://github.com/WordPress/gutenberg/blob/trunk/lib/experimental/block-editor-settings-mobile.php)).

**Comment by oandregal** [comment]
> https://github.com/WordPress/gutenberg/pull/39543 by @scruffian

This is also not to be backported. It's code only relevant for Gutenberg.

**Comment by adamziel** [comment]
> * `wp_enqueue_block_view_script` function
> * `gutenberg_block_type_metadata_multiple_view_scripts` filter's callback

@gziolo Is this the last missing backport as of today? 🎉 

Edit: Two more:

* https://github.com/WordPress/wordpress-develop/pull/2542
* https://github.com/WordPress/wordpress-develop/pull/2576

**Comment by gziolo** [comment]
> * `wp_enqueue_block_view_script` function
> * `gutenberg_block_type_metadata_multiple_view_scripts` filter's callback

Let’s move that to WordPress 6.1. It’s a nice improvement for plugin/block developers but let’s not rush it since we didn’t prepare necessary backports on time. I will move code and update docs in Gutenberg to reflect this.

I’m watching progress on both linked PRs and I will land them when they get approved by reviewers. They are being tracked in WordPress ticket: https://core.trac.wordpress.org/ticket/55567.

I think that concludes this issue 🎉

**Comment by gziolo** [comment]
Major props to everyone involved in the process. We wouldn’t make it in such a short time without your invaluable help 🙇‍♂️💯❤️
