### ISSUE TITLE
WordPress 6.0 editor pending issues and blockers

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#40139]
_This is a tracking issue to provide a quick overview of the editor's remaining **triaged** tasks and is expected to evolve in the coming weeks as the 6.0 release proceeds, in the spirit of [the similar issue used in the last release cycle](https://github.com/WordPress/gutenberg/issues/36556)._

_What was [found in the 6.0 walk-through](https://make.wordpress.org/core/2022/03/30/6-0-product-walk-through/) and [what currently exists in the project board](https://github.com/orgs/WordPress/projects/27/views/1) is serving as the foundation._

___
### 🚨 Major blocking issues
✅  All good! Nothing is blocking the next Beta release.

___

### ⚠️ Must-haves before RC
Specific functionalities require the following issues, but they **do not** block or put at risk the whole release.
- [x] Webfonts API: https://github.com/WordPress/gutenberg/issues/40472
- [x] Layouts: https://github.com/WordPress/gutenberg/issues/39651 
- [x] Block placeholders: https://github.com/WordPress/gutenberg/issues/40061 
___

### ✨ Nice to have and feature polishing  - Not for 6.0 anymore as time run out 🙅
- [ ] Block transforms: https://github.com/WordPress/gutenberg/issues/40059. **Punted to 6.1.** TL;DR; it's not a Gutenberg bug and it [needs to be addressed conceptually](https://github.com/WordPress/gutenberg/issues/40059#issuecomment-1111008261).
- [ ] https://github.com/WordPress/gutenberg/issues/36664 
- [x] Group block variations: https://github.com/WordPress/gutenberg/pull/40062 
- [ ] https://github.com/WordPress/gutenberg/issues/40063 
- [x] Multi-selection: https://github.com/WordPress/gutenberg/issues/40066 
- [x] Block placeholders: https://github.com/WordPress/gutenberg/issues/40074 
- [ ] Styles sidebar: https://github.com/WordPress/gutenberg/issues/39700 
- [ ] More granular multi-entity saving options for global style changes: https://github.com/WordPress/gutenberg/issues/29388 
- [ ] Refine the global styles panel, the prominence, and placement items: https://github.com/WordPress/gutenberg/issues/38934 
- [ ] https://github.com/WordPress/gutenberg/issues/39629
- [ ] #35331 🐛
- [x] https://github.com/WordPress/gutenberg/pull/37728 🐛
___

_Major kudos to @annezazu for helping compile this list_

**Comment by kjellr** [comment]
I'd suggest we add https://github.com/WordPress/gutenberg/issues/35331 to **Nice to have and feature polishing**. Duotone is applied in one of the [Twenty Twenty-Two alternate styles](https://core.trac.wordpress.org/ticket/55433) that we plan to ship with 6.0, but it does not currently render in the site editor. We can strip it out if need be, but it would be great to have it working.

**Comment by priethor** [comment]
Thanks @kjellr, I triaged it and added to the list 💯

**Comment by gziolo** [comment]
@priethor, is there anything actionable left for WP 6.0? Should we update it to target 6.1 instead?

**Comment by priethor** [comment]
With the Webfonts API alternative merged in #40472, the only remaining high-priority issue is #40059. Considering it's a bug, I would say we are in a good place. cc @ndiego for awareness of this issue, too

At this late stage, the other nice-to-haves should be punted to 6.1.

**Comment by ndiego** [comment]
@priethor see my latest comment on #40059. This is an issue in the Twenty Twenty-Two theme. It should be addressed in the theme by the 6.0 release but is not Gutenberg specific.

**Comment by priethor** [comment]
@youknowriad also shared some insightful feedback that explains it's not a bug, but a conceptual issue; solving it holistically in the editor doesn't seem feasible for 6.0.

In any case, at this point, it doesn't seem to me that this unexpected behavior should be a blocker to shipping the new block variations in 6.0, and I'd lean towards downgrading its severity here.

Any thoughts or objections, @adamziel @gziolo @ndiego @annezazu @youknowriad ?

**Comment by annezazu** [comment]
I agree with your read and don't think this should be a blocker, especially after reading the insights from Riad (thank you, as always).

**Comment by priethor** [comment]
Thanks for the feedback; I updated the opening post with the latest status update and de-prioritized it. Let's continue the #40059-specific convo there and confirm whether it can be fixed at the theme level.

**Comment by priethor** [comment]
Let's wrap this up. The only actionable item for 6.0 at this point is bug #35331, which has been partially fixed for the Site Editor and backported but still has a few loose ends ([further context here](https://github.com/WordPress/gutenberg/issues/35331#issuecomment-1102862654)).
