### ISSUE TITLE
Outreach to component maintainers for Field Guide "But Wait, There is More!" section (WordPress 6.0)

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#40609]
[Publishing Field Guide](https://make.wordpress.org/core/handbook/tutorials/publishing-the-field-guide/)
"Each Component team is sent a group direct message in Slack, pulling the list of maintainers from the [individual component pages](https://make.wordpress.org/core/components/)"

Example message: 
_It’s that time again `Component Name` component maintainer(s)… are there any tickets in the 6.0 release that you’d like called out in the Field Guide that aren’t already included in a Dev Note? As a reference, here are the ## tickets currently in the milestone for you: https://core.trac.wordpress.org/query?component=`ComponentName`&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority. Note that we intend to publish the Field Guide next week, so the sooner you can respond the better… thanks!_

## List of components
The link goes to the list of tickets for the milestone for the component.  The number of tickets is in parentheses. 
A blue check mark means maintainers were contacted or no issues. 

- [x] [Administration ](https://core.trac.wordpress.org/query?component=Administration&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (16)
- [x] [Bootstrap/Load](https://core.trac.wordpress.org/query?component=Bootstrap%2FLoad&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3)
- [x] [Build/Test Tools](https://core.trac.wordpress.org/query?component=Build%2FTest+Tools&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (33)
- [x] [Bundled Theme](https://core.trac.wordpress.org/query?component=Bundled+Theme&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (19)
- [x] [Cache API](https://core.trac.wordpress.org/query?component=Cache+API&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3) 
- [x] [**Comments**](https://core.trac.wordpress.org/query?component=Comments&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (6)
- [x] -- [Pings/Trackbacks](https://core.trac.wordpress.org/query?component=Pings%2FTrackbacks&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Cron API](https://core.trac.wordpress.org/query?component=Cron+API&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Customize](https://core.trac.wordpress.org/query?component=Customize&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(7)
- [x] [Database](https://core.trac.wordpress.org/query?component=Database&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (5)
- [x] [Date/Time](https://core.trac.wordpress.org/query?component=Date%2FTime&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(2)
- [x] [**Editor**](https://core.trac.wordpress.org/query?component=Editor&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(13) _also shared [Gutenberg Dev Note tracking issue](https://github.com/WordPress/gutenberg/issues/39654)_
- [x] -- [Autosave](https://core.trac.wordpress.org/query?component=Autosave&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1)
- [x] -- [Quick/Bulk Edit](https://core.trac.wordpress.org/query?component=Quick%2FBulk+Edit&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(5) 
- [x] -- [TinyMCE](https://core.trac.wordpress.org/query?component=TinyMCE&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Export](https://core.trac.wordpress.org/query?component=Export&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [External Libraries](https://core.trac.wordpress.org/query?component=External+Libraries&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(11)
- [x] [Feeds](https://core.trac.wordpress.org/query?component=Feeds&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(2)
- [x] [Filesytems API](https://core.trac.wordpress.org/query?component=Filesystem+API&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3)
- [x] [**Formatting**](https://core.trac.wordpress.org/query?component=Formatting&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(14)
- [x] -- [Charset ](https://core.trac.wordpress.org/query?component=Charset&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(0)
- [x] -- [Emoji](https://core.trac.wordpress.org/query?component=Emoji&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1)
- [x] -- [Shortcodes ](https://core.trac.wordpress.org/query?component=Shortcodes&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(0)
- [x] [General](https://core.trac.wordpress.org/query?component=General&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(23)
- [x] [Help/About Page](https://core.trac.wordpress.org/query?component=Help%2FAbout&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(4)
- [x] [HTTP API](https://core.trac.wordpress.org/query?component=HTTP+API&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(3)
- [x] [i18n](https://core.trac.wordpress.org/query?component=I18N&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(13)
- [x] [Import](https://core.trac.wordpress.org/query?component=Import&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Mail ](https://core.trac.wordpress.org/query?component=Mail&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(1)
- [x] [**Media**](https://core.trac.wordpress.org/query?component=Media&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(28)
- [x] -- [Embeds](https://core.trac.wordpress.org/query?component=Embeds&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1)
- [x] -- [Gallery](https://core.trac.wordpress.org/query?component=Gallery&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] -- [Upload](https://core.trac.wordpress.org/query?component=Upload&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Network/Sites](https://core.trac.wordpress.org/query?component=Networks+and+Sites&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(8)
- [x] [Options/Meta APIs](https://core.trac.wordpress.org/query?component=Options%2C+Meta+APIs&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3)
- [x] [**Permalinks**](https://core.trac.wordpress.org/query?component=Permalinks&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(3)
- [x] -- [Canonical ](https://core.trac.wordpress.org/query?component=Canonical&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(2) (sub component)
- [x] -- [Rewrite Rules](https://core.trac.wordpress.org/query?component=Rewrite+Rules&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1) (sub component)
- [x] [Plugins ](https://core.trac.wordpress.org/query?component=Plugins&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (5)
- [x] **[Posts, Post Types](https://core.trac.wordpress.org/query?component=Posts%2C+Post+Types&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)** (12)
- [x] -- [Post Formats](https://core.trac.wordpress.org/query?component=Post+Formats&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] -- [Post Thumbnails](https://core.trac.wordpress.org/query?component=Post+Thumbnails&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] -- [Revisions](https://core.trac.wordpress.org/query?component=Revisions&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1)
- [x] [Privacy](https://core.trac.wordpress.org/query?component=Privacy&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(1)
- [x] [Query](https://core.trac.wordpress.org/query?component=Query&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4)
- [x] [REST API](https://core.trac.wordpress.org/query?component=REST+API&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (10)
- [x] [Application Passwords](https://core.trac.wordpress.org/query?component=Application+Passwords&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (2)
- [x] [Script Loader ](https://core.trac.wordpress.org/query?component=Script+Loader&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(5)
- [x] [Security](https://core.trac.wordpress.org/query?component=Security&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Site Health](https://core.trac.wordpress.org/query?component=Site+Health&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Sitemaps](https://core.trac.wordpress.org/query?component=Sitemaps&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1)
- [x] [Taxonomy](https://core.trac.wordpress.org/query?component=Taxonomy&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (14)
- [x] [**Themes**](https://core.trac.wordpress.org/query?component=Themes&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (13)
- [x] -- [Menus ](https://core.trac.wordpress.org/query?component=Menus&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(5)
- [x] -- [Widgets](https://core.trac.wordpress.org/query?component=Widgets&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3)
- [x] [Toolbar](https://core.trac.wordpress.org/query?component=Toolbar&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (2)
- [x] [Upgrade/Install](https://core.trac.wordpress.org/query?component=Upgrade%2FInstall&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (17)
- [x] [**Users**](https://core.trac.wordpress.org/query?component=Users&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (15)
- [x] -- [Login & Registration](https://core.trac.wordpress.org/query?component=Login+and+Registration&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4)
- [x] -- [Role/Capability](https://core.trac.wordpress.org/query?component=Role%2FCapability&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [XML-RPC (1)](https://core.trac.wordpress.org/query?component=XML-RPC&milestone=6.0&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)

**Comment by bph** [comment]
[Mentioned in async release check-in 2022-04-26 ](https://wordpress.slack.com/archives/C035NHLFUSY/p1650981807263339?thread_ts=1650971160.803229&cid=C035NHLFUSY)

**Comment by bph** [comment]
Closing it now as the [Field Guide was published and updated](https://make.wordpress.org/core/2022/05/03/wordpress-6-0-field-guide/) last week.
