### ISSUE TITLE
Block Supports: Tracking issue

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#41113]
This is an issue to track what block supports are missing so we can add them. Please feel free to add more as you discover them:

- [x] https://github.com/WordPress/gutenberg/pull/31465
- [ ] https://github.com/WordPress/gutenberg/issues/30982
- [ ] https://github.com/WordPress/gutenberg/issues/39053
- [ ] https://github.com/WordPress/gutenberg/issues/39071
- [x] https://github.com/WordPress/gutenberg/issues/39074
- [ ] https://github.com/WordPress/gutenberg/issues/34638
- [ ] https://github.com/WordPress/gutenberg/issues/14744
- [ ] https://github.com/WordPress/gutenberg/issues/34637
- [ ] https://github.com/WordPress/gutenberg/pull/23403
- [x] https://github.com/WordPress/gutenberg/pull/31366
- [x] https://github.com/WordPress/gutenberg/pull/31370
- [x] https://github.com/WordPress/gutenberg/pull/37662
- [ ] https://github.com/WordPress/gutenberg/pull/41082
- [ ] https://github.com/WordPress/gutenberg/pull/41011
- [x] https://github.com/WordPress/gutenberg/pull/33587
- [ ] https://github.com/WordPress/gutenberg/issues/18989
- [x] https://github.com/WordPress/gutenberg/pull/31996
- [x] https://github.com/WordPress/gutenberg/issues/35323
- [ ] https://github.com/WordPress/gutenberg/pull/38986
- [ ] https://github.com/WordPress/gutenberg/issues/34647
- [ ] https://github.com/WordPress/gutenberg/issues/34652
- [x] https://github.com/WordPress/gutenberg/issues/34757
- [x] https://github.com/WordPress/gutenberg/pull/41435

**Comment by MaggieCabrera** [comment]
I think https://github.com/WordPress/gutenberg/issues/43241 has the same intention as this issue

**Comment by scruffian** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/43241
