### ISSUE TITLE
Global Styles Ongoing Roadmap

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#41232]
_Previously #34574, #9534, #37550._ This issue tracks the ongoing roadmap of **global styles** features and `theme.json` development.

---

### Style Variations

<img width="1851" alt="Variations" src="https://github.com/WordPress/gutenberg/assets/846565/8e734dbc-c6a3-4469-bfef-56e44cbecba2">

The theme objects were designed to be composable. The next idea to unlock is to allow full style objects to be attached to specific templates or patterns. The style objects are managed globally and hooked into concrete templates or patterns. That would allow styling an `archive` very differently to other templates; having specific color palettes and font sizes for a header template; or using synchronized patterns while modifying them through style objects managed globally.

- [ ] #40318
- [ ] https://github.com/WordPress/gutenberg/issues/53480
- [x] #38333.
- [ ] https://github.com/WordPress/gutenberg/issues/53476
- [ ] #7551

### Style Book

<img width="1684" alt="Style Book" src="https://github.com/WordPress/gutenberg/assets/846565/0f7fa654-96e4-4ef3-b05b-a461264c7543">

- [x] https://github.com/WordPress/gutenberg/issues/53431
- [x] https://github.com/WordPress/gutenberg/issues/53432
- [x] https://github.com/WordPress/gutenberg/issues/53437

### Interface

<img width="1684" alt="UI" src="https://github.com/WordPress/gutenberg/assets/846565/eb2b8577-2ad4-44e2-ae42-4d99e3f57dd9">

- [x] https://github.com/WordPress/gutenberg/issues/53483
- [ ] #49278
- [ ] https://github.com/WordPress/gutenberg/issues/53484
- [x] #27075, #38277, #34717.
- [x] #27393.

### Tools

- [ ] #38534
- [ ] #65723
- [x] #40966
- [x] #45198

**Comment by annezazu** [comment]
I'd like to list the following for inclusion in this general roadmap: https://github.com/WordPress/gutenberg/issues/44840, https://github.com/WordPress/gutenberg/issues/29388. In particular, being able to have more granular information when saving feels critical in a world of style variations and an increasing number of controls within Styles.

**Comment by oandregal** [comment]
Substituted https://github.com/WordPress/gutenberg/issues/33977 (closed, high-level strategic point of view) by https://github.com/WordPress/gutenberg/issues/45198 (tactical next steps) in the "per block styles & supports" section.

**Comment by mtias** [comment]
Reorganizing the issue, documenting done tasks here for posterity:

- [x] #30142
- [x] #44412
- [x] #39629
- [x] #38167
- [x] #49601
- [x] Implement block preview on the panels, similar to the typography previews. (Needs design.)
- [x] #41113.
- [x] Allow going from local styles (editing a block in the post editor) to modifying global styles for all blocks of that type (apply these styles to all headings, etc).
- [x] #40386.
- [x] #40364.
- [x] #40362.
