### ISSUE TITLE
Document known changes in editor behavior

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#4186]
As a user switching from the Classic to Gutenberg editor, it would be helpful to have a documented list of UX changes so I can know which changes are intentional vs. which might be bugs. My expectation, as a user switching from one to the other, is that they're as consistent as possible.

A non-exhaustive list of changes includes:

* [ ] Using the `tab` button no longer indents an ordered or unordered list #4181
* [ ] Many buttons have been removed from the text formatting toolbar, including text color #6080
* [ ] Some HTML attributes and additional markup are stripped from blocks #5876 #6096 #4498
* [ ] Text content is automatically wrapped with `<p>` tags https://github.com/WordPress/gutenberg/issues/4446#issuecomment-394719166
* [ ] Hidden metaboxes no longer exist #7570

Previously #4181

Related:

* Document WordPress classic editor integration points and Gutenberg equivalents #4151
* https://github.com/danielbachhuber/gutenberg-migration-guide

**Comment by youknowriad** [comment]
> My expectation, as a user switching from one to the other, is that they're as consistent as possible.

While I'm not sure I agree with this statement as we're trying to improve the editor so being consistent is not a goal in itself but yeah we should educate users and NUX #3670 #4173 is part of the solution here.

**Comment by danielbachhuber** [comment]
> While I'm not sure I agree with this statement as we're trying to improve the editor so being consistent is not a goal in itself

Maybe a better way of phrasing is:

> Any editor UX changes are deliberate and documented. Those that aren't can be considered bugs.

The default should be consistent behavior between editors, except where a deliberate decision has been made to change the behavior.

**Comment by danielbachhuber** [comment]
@chrisvanpatten volunteered to help get this over the finish line. We can use https://github.com/danielbachhuber/gutenberg-migration-guide as a starting point for these details.

**Comment by designsimply** [comment]
@danielbachhuber what action is still needed for this issue. Since 11252 and 11251 each mention documentation sections such as "What's different about the new editor?" and "Important deprecations/changes from 4.x" respectively, can we close this issue in favor of finalizing work in the new issues?

**Comment by danielbachhuber** [comment]
> Since 11252 and 11251 each mention documentation sections such as "What's different about the new editor?" and "Important deprecations/changes from 4.x" respectively, can we close this issue in favor of finalizing work in the new issues?

Sure, that's fine. It seems like moving chairs around though.

**Comment by designsimply** [comment]
Cool. It looked to me like several things had already been addressed in closed PRs and I am working to consolidate issues where possible. Thank you!
