### ISSUE TITLE
Add code examples for actions/selectors in Data Module packages.

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#42125]
## What problem does this address?
Working with any of the data modules provided by WordPress can be very confusing. When looking at the [Data Modules section in the handbook](https://developer.wordpress.org/block-editor/reference-guides/data/), there are almost no code examples for developers to use as reference.

I would love to see an example for each action or selector that is exposed for use.

Packages:
- [x] ~~core/annotations~~ _edit_ @t-hamano the selector and actions in the `annotations` package are all experimental
- [ ] core/block-editor - https://github.com/WordPress/gutenberg/pull/51853
- [x] core/blocks
    - [x] [selectors](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-blocks/#selectors) - https://github.com/WordPress/gutenberg/pull/42572
    - [x] [actions](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-blocks/#actions) - #42637
    - [x] [Public API Examples](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-blocks/#api) ( [see this comment](https://github.com/WordPress/gutenberg/pull/42637#pullrequestreview-1051940588) ) -  #42745
- [x] core/customize-widgets - https://github.com/WordPress/gutenberg/pull/52141
- [ ] core/data - https://github.com/WordPress/gutenberg/pull/42639
- [ ] core/edit-post
- [ ] core/edit-site
- [ ] core/edit-widgets
- [ ] core/editor
- [x] core/keyboard-shortcuts #42831
- [x] core/notices - https://github.com/WordPress/gutenberg/pull/42023,https://github.com/WordPress/gutenberg/pull/42077
- [x] ~~core/nux~~ - Package was removed with https://github.com/WordPress/gutenberg/pull/46110
- [ ] core/preferences
- [x] ~~core/reusable-blocks~~  _edit_ @t-hamano the selector and actions in the `annotations` package are all experimental
- [x] core/rich-text - https://github.com/WordPress/gutenberg/pull/52089
- [x] core/viewport #42921

## What is your proposed solution?
Add an @example tag to each docblock. This will be picked up by the documentation generator and added to the handbook.

**Comment by ryanwelcher** [comment]
#42023 introduced one example and makes usage much clearer for [getNotices](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-notices/#getnotices)

![Notices_Data___Block_Editor_Handbook___WordPress_Developer_Resources](https://user-images.githubusercontent.com/1259027/177167671-ddc8ddb2-d19c-4ece-9503-7ada9fcd57ba.png)

**Comment by skorasaurus** [comment]
In case you weren't aware, some resources that you may want to draw off of, for core/data:

https://github.com/WordPress/gutenberg/blob/bd06705979ad63ace26d15de47144c253c3b0fc8/docs/getting-started/data.md
https://wordpress.stackexchange.com/questions/390985/how-do-i-access-site-and-block-editor-state-data-and-use-useselect-or-withs/390986#390986

**Comment by t-hamano** [comment]
@ryanwelcher 

I have added missing data module references by #42651.
Could you please add it to the task list as well?

- block-directory
- customize-widgets
- edit-site
- edit-widgets
- preferences
- reusable-blocks
- rich-text

And I would love to help add code examples too 😊

**Comment by ryanwelcher** [comment]
> I have added missing data module references by #42651.
> Could you please add it to the task list as well?

This is fantastic! Thanks for putting that together. I've updated the list.

**Comment by t-hamano** [comment]
@ryanwelcher 
I have created PR #42831 about `core/keyboard-shortcuts`.

**Comment by t-hamano** [comment]
I have created PR #42921 about core/viewport.

**Comment by t-hamano** [comment]
I noticed that of the references I added in #42651, the selector and actions in the `reusable-blocks` package are all experimental.
Should this package be excluded from the documentation?

**Comment by t-hamano** [comment]
I noticed that the selector and actions in the `annotations` package are all experimental too.

**Comment by ryanwelcher** [comment]
It probably makes sense to exclude packages that are fully experimental.

**Comment by ryanwelcher** [comment]
Some package are not exporting their stores. To keep the DX consistent, I have created the following PRs to to export the store:

- https://github.com/WordPress/gutenberg/pull/52189
- https://github.com/WordPress/gutenberg/pull/51986
- https://github.com/WordPress/gutenberg/pull/52190

**Comment by ryanwelcher** [comment]
@troychaplin you might be interested in this issue.

**Comment by troychaplin** [comment]
I have added a few examples in core/editor in https://github.com/WordPress/gutenberg/pull/63768, need a label added

**Comment by youknowriad** [comment]
@Mamaduka made the point that adding the same kind of examples over and over in these selectors doesn't bring a lot of value. People that know how to use useSelect don't need these. And I agree, so I'm closing this issue and related PRs.
