### ISSUE TITLE
Tracking: Native Bottom Sheet V2

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#42192]
This issue tracks various tasks related to an iteration of the native editor bottom sheet to address #37559. Specifically, this project looks to replace our custom implementation (V1) with [`@gorhom/bottom-sheet`](https://gorhom.github.io/react-native-bottom-sheet/) (V2). 

## Sheets 

This list represents the various sheets found throughout the app that would ultimately be migrated to use the new bottom sheet implementation. 

- [ ] Block (Reusable)
- [ ] Block Settings
- [ ] Block Variation Picker
- [ ] Dropdown Menu
- [ ] Editor Help
- [ ] Embed Preview
- [ ] Inserter
- [ ] Link Modal
- [ ] Link Settings Navigation
- [ ] Text Color

## Content Usage

This list represents the various bottom sheet specific UI and abstractions utilized within the bottom sheet. These would need to be tested and/or updated for compatibility. 

- [ ] Cells 
  - [ ] Bottom Sheet Select Control
  - [ ] Button
  - [ ] Color
  - [ ] Link
  - [ ] Picker
  - [ ] Radio
  - [ ] Range
  - [ ] Ripple
  - [ ] Stepper
  - [ ] Switch
  - [ ] Text Control
- [ ] Color/Gradient Picker
- [ ] Dynamic height adjustments
- [ ] Focal point picker
- [ ] Footer
- [ ] Footer message link
- [ ] Header
- [ ] Navigation 
- [ ] Scrollable
- [ ] Sub-sheet abstraction

**Comment by tyxla** [comment]
This is no longer relevant after the React Native implementation was removed in #78747. Closing.
