### ISSUE TITLE
UnitControl: Improve handling of long values in unit select

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#42879]
<img width="239" alt="UnitControl with unit select" src="https://user-images.githubusercontent.com/846565/181240123-c1fd3c71-e246-4f32-a3c2-d77c0ba812dc.png">

## Tasks

- [ ] Change the implementation so the dropdown itself is a standard `select` but the visible trigger button is a custom component.
- [x] #42650 
- [ ] Make the button width [hug the selected value](https://github.com/WordPress/gutenberg/pull/42000#issuecomment-1196629350).
- [ ] Figure out how to deal with [long values](https://github.com/WordPress/gutenberg/pull/42000#issuecomment-1196658961) (max-width, flex, etc.)

**Comment by hbhalodia** [comment]
Hi @mirka, I would like to propose a solution to deal with long values, Let me know if that approach is worth implementing or not?

A potential approach could be to introduce a new prop to `UnitControl`, such as `maxUnitWidth`, which would accept either a `string` or `number` value (e.g., `48` or `48px`). This value could then be passed to `UnitSelect` to dynamically adjust the width based on consumer preference, updating the `max-width` defined in `baseUnitLabelStyles` accordingly. 

Also, For mobile and smaller screens truncation can as it as around 48px?

I can create a draft PR to add the above approach.
