### ISSUE TITLE
ColorGradientControl: Update design

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#43014]
- [x] Flip the element order so the current color indicator is always the first item ([mockups](https://github.com/WordPress/gutenberg/pull/41900#issuecomment-1205124434)) #43577
- [x] Make the current color indicator go edge-to-edge when inside a popover (related: #39452)
- [x] Remove the bottom margin from GradientPicker #43436
- [x] [Update swatch sizes](https://github.com/WordPress/gutenberg/pull/43018#pullrequestreview-1063031655) to be 20px instead of 28px (see also https://github.com/WordPress/gutenberg/issues/45781)

**Comment by youknowriad** [comment]
All the todo list items are done here. I'm closing this issue. Let me know if something is missing.
