### ISSUE TITLE
Synced / Global blocks: Improving clarity in the UI

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#43598]
We have a few open issues dedicated to addressing the lack of clarity around these blocks across different UI regions and flows. It would be good to track them all so that we don't end up with divergent / incompatible solutions.

- [x] https://github.com/WordPress/gutenberg/issues/42501
- [x] https://github.com/WordPress/gutenberg/issues/32163
- [ ] https://github.com/WordPress/gutenberg/issues/43261
- [x] https://github.com/WordPress/gutenberg/issues/43608

**Comment by jameskoster** [comment]
Closing this as there's only one outstanding item and it already has a dedicated issue.
