### ISSUE TITLE
Contextual data in template blocks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44322]
In https://github.com/WordPress/gutenberg/pull/43699 we merged a change to ensure that the Query blocks in templates for specific categories only display posts from the chosen category. 

There's an opportunity to do similar things with other templates / blocks to provide a more consistent overall template editing / creating experience.

- [ ] https://github.com/WordPress/gutenberg/issues/44158
- [ ] https://github.com/WordPress/gutenberg/issues/42554
- [ ] https://github.com/WordPress/gutenberg/issues/41947
- [ ] When creating a template for a specific tag, display posts with that tag in the Query block
- [ ] When creating a template for a specific custom taxonomy term, display posts with that term in the Query block
