### ISSUE TITLE
Post Template: Refactor ad hoc flex container to use layout block support flex type

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#44557]
The Post Template block currently uses an ad hoc approach to generating flex layout rules for its option for a grid view. This ad hoc approach adds an `is-flex-container` classname, linked to some hard-coded rules in its `style.scss` file, here: https://github.com/WordPress/gutenberg/blob/61152833b45a6eefc3f2fb1966c7e315ab9d8d44/packages/block-library/src/post-template/style.scss#L13

It would be good to refactor the approach of this block to use the layout block support's flex type for the grid styles (`is-layout-flex`), so that we can then directly opt-in to `blockGap` support, to allow flexible control over the spacing between instances of the Post Template block.

## Tasks to address

* [ ] Replace the `is-flex-container` rules with the ability to switch between flow / flex layout types using the layout block support (or should this always be `flex`, but use vertical orientation as the switch?)
* [ ] Work out how to reliably swap out the `width` rules and their calculation so that the ad hoc columns rules still work as-is
* [ ] Ensure backwards compatibility with the block's existing `gap: 1.25em` rule, when making the switch
* [ ] Opt-in to `blockGap` controls to allow spacing between instances of the Post Template block

## Why

The overall goal would be to utilise the layout block support for all structural layout styling of this block, so that users can have control over block spacing and content justification, and so that if and when additional layout types are rolled out, these can be used in the Post Template / Query Loop blocks, too, enabling a wider variety of designs.

## Related issues (and semi-related issues)

This issue has been touched on already in other feature requests — because those feature requests are typically from the perspective of the user of the theme, I thought it'd be helpful to have a separate issue for tracking the technical issues in implementing those changes. This issue should primarily be for tracking / breaking down the tasks of refactoring away the block's ad hoc layout rules.

* https://github.com/WordPress/gutenberg/issues/39380
* https://github.com/WordPress/gutenberg/issues/48224
* https://github.com/WordPress/gutenberg/issues/39599
* https://github.com/WordPress/gutenberg/issues/41410 (flags the need for design tools at the Post Template level)

**Comment by tellthemachines** [comment]
Thanks for writing this up!

I think the Grid view in Post Template is an ideal candidate for an actual grid layout type. The current implementation is shoehorning grid-like behaviour into a flex layout by forcing a certain number of cols through a complicated width calculation, whereas `display: grid` and its companion properties do this natively, plus  `gap` works exactly like flex, so we can reuse the existing logic 🎉

**Comment by andrewserong** [comment]
> I think the Grid view in Post Template is an ideal candidate for an actual grid layout type.

Oh, that's a great idea! I suppose ideally Post Template would support any number of potential future layouts, too (e.g. a future wish-list item might be if layout support winds up eventually allowing for carousel-like behaviour for a Netflix-like scrollable row of post titles 🤔). But yes, I think a grid layout type would be a better fit here, too 👍

**Comment by skorasaurus** [comment]
> > I think the Grid view in Post Template is an ideal candidate for an actual grid layout type.
> 
> Oh, that's a great idea! I suppose ideally Post Template would support any number of potential future layouts, too (e.g. a future wish-list item might be if layout support winds up eventually allowing for carousel-like behaviour for a Netflix-like scrollable row of post titles thinking). But yes, I think a grid layout type would be a better fit here, too +1

I would love to see this; i came across this because I'm trying to figure out how to avoid using columns block within the post template block. (running into the issue described at https://github.com/WordPress/gutenberg/issues/30480)

**Comment by sophiegyo** [comment]
I would love to have the `blockGap` controls too, I was just trying to figure out a blocks layout for having a grid of featured images but there's no block spacing control on the query loop which lets me remove the block gap without overriding the CSS.

Default:

![queryloopgap](https://user-images.githubusercontent.com/36608681/195339121-64ee3d71-e719-4aca-adc9-d3d604ad3124.png)

What I'd like to achieve:
![queryloopgap2](https://user-images.githubusercontent.com/36608681/195339644-0e58b69d-5fd5-4d2a-b2b6-f28346f4e321.png)

**Comment by andrewserong** [comment]
Thanks for adding the screenshot @sophiegyo, that captures the desired goal of this issue perfectly 👍

**Comment by paaljoachim** [comment]
It is awesome to see the movement happening here! Thank you, thank you and another thank you!

**Comment by paaljoachim** [comment]
This issue explores different ways to manage image sizes:
Image Block: Surface aspect-ratio tool for custom image dimensions
https://github.com/WordPress/gutenberg/issues/38990

It should also carry over to the Featured Image block, so that we can have the same cropped size Query Loop featured images.

**Comment by andrewserong** [comment]
Just a quick update: I think it'd still be beneficial to explore our options with the flex layout, and see what kinds of back compat issues we'll run into with enabling different types of layout types on the Post Template block. It sounds like a Grid layout type will be especially useful for this block in the longer term (https://github.com/WordPress/gutenberg/issues/47809), but in the shorter-term, it could still be useful to have a play with the flex layout + block spacing and alignment controls. I've started a (very) early PR over in #48340 to have a play and identify what the blockers will be.

**Comment by richtabor** [comment]
Just noting that https://github.com/WordPress/gutenberg/issues/48224 is a duplicate of the longer-standing https://github.com/WordPress/gutenberg/issues/44899.

**Comment by tellthemachines** [comment]
Now that #49050 is merged I'm going to go ahead and close this one.
