### ISSUE TITLE
Migrate React Test Renderer tests to React Testing Library

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#44780]
A tracking issue for refactoring React Test Renderer tests to use React Testing Library.

Please comment if you're planning to pick up any of these tests.

### Editor

- [x] packages/editor/src/components/post-text-editor/test/index.js - https://github.com/WordPress/gutenberg/pull/44923
- [x] packages/editor/src/components/post-type-support-check/test/index.js - https://github.com/WordPress/gutenberg/pull/44872

### Data

- [x] packages/data/src/components/with-select/test/index.js - https://github.com/WordPress/gutenberg/pull/45058
- [x] packages/data/src/components/with-dispatch/test/index.js - https://github.com/WordPress/gutenberg/pull/44855
- [x] packages/data/src/components/use-dispatch/test/use-dispatch.js - https://github.com/WordPress/gutenberg/pull/44802

### Edit Post

- [x] packages/edit-post/src/components/editor-initialization/test/listener-hooks.js - https://github.com/WordPress/gutenberg/pull/45066
- [x] packages/edit-post/src/components/sidebar/plugin-post-status-info/test/index.js - https://github.com/WordPress/gutenberg/pull/44835
- [x] packages/edit-post/src/components/preferences-modal/options/test/enable-custom-fields.js - @tyxla #45011

### Block Editor

- [x] packages/block-editor/src/components/block-settings-menu/test/block-mode-toggle.js - @tyxla #45071
- [x] packages/block-editor/src/components/colors-gradients/test/control.js - @tyxla #44869
- [x] packages/block-editor/src/components/color-palette/test/control.js - @tyxla #44870
- [x] packages/block-editor/src/components/provider/test/use-block-sync.js - @tyxla #44871
- [x] packages/block-editor/src/hooks/test/align.js - @tyxla #45152

### Components

- [x] packages/components/src/mobile/bottom-sheet/test/range-cell.native.js @geriux #44830
- [x] packages/components/src/higher-order/with-focus-return/test/index.js @tyxla #45012
- [x] packages/components/src/tree-grid/test/roving-tab-index.js @tyxla #44820
- [x] packages/components/src/tree-grid/test/roving-tab-index-item.js @tyxla #44821
- [x] packages/components/src/tree-grid/test/row.js @tyxla #44824
- [x] packages/components/src/tree-grid/test/cell.js @tyxla #44826
- [x] packages/components/src/tooltip/test/index.native.js @geriux #44831
- [x] packages/components/src/notice/test/index.js - https://github.com/WordPress/gutenberg/pull/44801
- [x] packages/components/src/notice/test/list.js - @tyxla #45072

### Compose

- [x] packages/compose/src/higher-order/with-global-events/test/index.js - @tyxla #45108
- [x] packages/compose/src/hooks/use-instance-id/test/index.js - @tyxla #44818
- [x] packages/compose/src/hooks/use-viewport-match/test/index.js - @tyxla #44819
- [x] packages/compose/src/hooks/use-resize-observer/test/index.native.js @geriux #44832 
- [x] packages/compose/src/hooks/use-media-query/test/index.js - #44912

### Element

- [x] packages/element/src/test/create-interpolate-element.js - https://github.com/WordPress/gutenberg/pull/44804

### Block Library

- [x] packages/block-library/src/code/test/edit.native.js @geriux #44833 

### Interface

- [x] packages/interface/src/components/fullscreen-mode/test/index.js - https://github.com/WordPress/gutenberg/pull/44803

**Comment by tyxla** [comment]
Thanks for wrangling the issue! I'm going to work on a few of those as we've gained some momentum already.

**Comment by geriux** [comment]
Hey there 👋 I'll take the native ones 🚀

**Comment by tyxla** [comment]
All tasks seem to be addressed @Mamaduka! Have you been planning any further cleanup before closing this one?

**Comment by Mamaduka** [comment]
@tyxla, I think we can close this. Thank you both for helping with the effort 🙌
