### ISSUE TITLE
Min Height block support follow-up tasks

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#45501]
As of https://github.com/WordPress/gutenberg/pull/45300, a minimally viable version of the minimum height block support has been introduced, which opts both the Group and Post Content blocks in to a minimum height control in the dimensions panel, which is hidden by default.

There were some good suggestions and ideas flagged both on that PR and some related issues. This issue is to group together some of those tasks and notes so that they don't get missed.

## Tasks

* [x] Add a range control slider beside the Min height control, similar to font size and custom padding controls. While there is not (yet) a SliderUnitControl component (as discussed in https://github.com/WordPress/gutenberg/pull/42315), in the shorter-term, we can likely create a block editor component for both the post editor and global styles that groups together the `UnitControl` with a `RangeControl`.
* [x] Add a resizeable box that users can drag to set the height of the block, similar to how the Cover block's ad hoc controls work. There is a comment here that provides more context and ideas: https://github.com/WordPress/gutenberg/pull/45300#issuecomment-1296814993 — that comment links to explorations in https://github.com/WordPress/gutenberg/pull/41153
* [x] Refactor the Cover block to use this block support, both for consistency, and so that it can benefit from the improvements in controls (e.g. the added slider). This was suggested in this comment: https://github.com/WordPress/gutenberg/pull/45300#issuecomment-1296975201
* [ ] Add support for height presets, similar to spacing presets, to allow easier access to good values for responsive design (e.g. clamped heights, etc) https://github.com/WordPress/gutenberg/issues/48810

## Issues to (potentially) close out once these tasks are done

* [ ] https://github.com/WordPress/gutenberg/issues/28845 (the resizeable box + opt-in to template parts are the remaining tasks)
* [x] https://github.com/WordPress/gutenberg/issues/45117

**Comment by poof86** [comment]
Will minHeight also be added to the Column Block?
I'm asking because the Column Block has the options for vertical alignment.

Maybe we could include vertical alignment to the Group Block also?
It would go well with this minHeight setting.

Sidenote:
I was hoping to get this minHeight feature in my Gutenberg installation before the next milestone releases.
But I don't know how to get this into my current project. If somebody could help me in the right direction how to do this that would be awesome.

I presume I pull the current trunk, because this feature is already merged.
Next I "npm run build" the project to get my release right? (probably need to do a npm install first?)
Or is there a compile git command that can do this for me on the GitHub server?

Thank you, sorry for going off topic

**Comment by cbirdsong** [comment]
Here is a related issue: 
- https://github.com/WordPress/gutenberg/issues/48810

**Comment by andrewserong** [comment]
Oh, that's a great idea @cbirdsong! I've added that to the list of tasks in the issue description and added the needs design feedback label to the issue.

**Comment by jasmussen** [comment]
Thanks for putting this list together. Looking at trunk, the remaining work here is done or tracked elsewhere. Min-height presets arrived in [#73811](https://github.com/WordPress/gutenberg/pull/73811) through the new dimensions.dimensionSizes presets and the DimensionControl in packages/block-editor/src/components/global-styles/dimensions-panel.jsx. The slider came in [#45875](https://github.com/WordPress/gutenberg/pull/45875). The resizable Group/Template Part idea ([#28845](https://github.com/WordPress/gutenberg/issues/28845)) was closed as not planned. Moving Cover's min-height control over is tracked in [#56020](https://github.com/WordPress/gutenberg/issues/56020) and [#62509](https://github.com/WordPress/gutenberg/pull/62509). I'll close this follow-up. Please reopen, or open a new issue, if anything specific is still missing.
