### ISSUE TITLE
First milestone: Prototype Parity

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#462]
Remaining tasks for prototype parity

**All blocks:**

- [x] Scroll the page to keep your place as you move blocks up and down #161
- [x] Animate controls as they appear, fade out block boundaries #15 #489

---

**Text / Quote / List:**

- [x] Inline formatting #452 #460
- [ ] Block level alignments https://github.com/WordPress/gutenberg/pull/443

---

**Image / Video:**

- [ ] Basic alignments and full-width https://github.com/WordPress/gutenberg/pull/416
- [ ] Cite/caption support https://github.com/WordPress/gutenberg/issues/378
- [ ] Cite/caption placeholder text block is selected, disappears if empty and unselected https://github.com/WordPress/gutenberg/issues/455
- [ ] Embedded video is as big as the editor main column

Tickets:

- https://github.com/WordPress/gutenberg/issues/310
- https://github.com/WordPress/gutenberg/issues/316

---

**Quote:**

- [x] Two quote styles https://github.com/WordPress/gutenberg/issues/311
- [ ] Support switcher

---

**Inserter:**

- [ ] Shows up after two linebreaks at the end https://github.com/WordPress/gutenberg/issues/323
- [ ] `/` when written on a new line invokes inserter https://github.com/WordPress/gutenberg/issues/71
- [x] Inserter is searchable.
- [ ] Inserter has arrowkey navigation. #515
- [x] All built blocks should be in the inserter

---

**See also:**

- <a href="https://github.com/WordPress/gutenberg/milestone/1">Github milestone</a>
- Older <a href="https://github.com/WordPress/gutenberg/issues/190">Prototype: Requirements</a> ticket
- <a href="https://github.com/WordPress/gutenberg/projects/2">Project overview</a>

**Comment by iseulde** [comment]
See https://github.com/WordPress/gutenberg/milestone/1 for an up-to-date list.
