### ISSUE TITLE
Global styles: Block color palette bugs

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#46395]
### Description

When accessing a single block's color styles in the global styles system, it's possible to change the color palette too:
![Screen Shot 2022-12-08 at 5 01 52 pm](https://user-images.githubusercontent.com/677833/206403879-a9efadfd-5ab4-4120-8434-341f400a1eed.png)

I discovered a few bugs with this part of the UI
- [ ] After clicking on 'Palette', changing a color, most of the blocks in the canvas do not seem to update to reflect the changes. Some do. Compared to the 'Randomize Colors' option it doesn't seem right as that has an immediate effect on all blocks in the canvas.
- [ ] After clicking on 'Palette', changing a color, and then clicking the back button, the changes are not reflected in the swatch.
- [ ] After clicking on 'Palette', changing a color, and then clicking 'Reset to defaults' in the dropdown in the 'Styles' header, nothing happens. The colors aren't reset. They do reset if the 'Reset colors' option in the dropdown where it says 'Theme' is clicked.
- [ ] Clicking 'Randomize colors' and then clicking into the Palette, the randomized colors aren't reflected in the palette.

### Step-by-step reproduction instructions

1. Open the global styles panel
2. Click the 'Blocks' menu item
3. Choose a block with color support, like Paragraph
4. Click Colors
5. Follow the steps in the description.

### Environment info

- Gutenberg `trunk`
- Mac OS / Brave

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
