### ISSUE TITLE
Fixed / Sticky position follow up tasks

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#47043]
Related:

* This issues follows on from: #30121
* Discussion in: https://github.com/WordPress/gutenberg/discussions/46032

An initial implementation of sticky position block support was added and enabled on the Group block in: https://github.com/WordPress/gutenberg/pull/46142. This issue lists follow-up tasks now that the initial PR has landed. Some of these could be split out into their own issues depending on complexity.

### Current state of sticky position support

The screengrab below demos wrapping a header template part in a group block, setting that group block to full width, then setting that group block to "sticky":

https://user-images.githubusercontent.com/14988353/211697403-f9f80970-c51f-4684-92d0-7dbfe03d56c6.mp4

### Follow-up tasks

* [x] Re-enable sticky in non-root positions. Once this has been resolved, we can then close out https://github.com/WordPress/gutenberg/issues/49903 and https://github.com/WordPress/gutenberg/issues/47892 — [WIP PR](https://github.com/WordPress/gutenberg/pull/49321)
* [ ] Explore opting the Columns block in to sticky position
* [x] Update List View to flag in the UI when a block has a position value set ([WIP PR](https://github.com/WordPress/gutenberg/pull/49122))
* [ ] Update z-index approach to remove hard-coded z-index values and replace with presets in `theme.json`.
* [x] Look into enabling `fixed` position on the Group block, and what other controls are required (e.g. width or more fine-grained position controls as described in #30121)
* [ ] Look into position UI for top/left/right/bottom positions and offsets, in particular support for fixed/sticky footers
* [ ] Improve the experience for setting a sticky or fixed header, e.g. is it possible to achieve without having to wrap the header template part in a sticky Group block? Related issue: https://github.com/WordPress/gutenberg/issues/50617
* [ ] Explore whether there needs to be a control to lock the position settings to just desktop or mobile viewports?
* [ ] Explore outputting scroll-padding-top for fixed / sticky headers to ensure that links to parts of a page scroll correctly without being cut off: https://github.com/WordPress/gutenberg/issues/48656
* [x] https://github.com/WordPress/gutenberg/pull/49151
* [x] https://github.com/WordPress/gutenberg/pull/49085 (Note: reverted in https://github.com/WordPress/gutenberg/pull/49219)
* [x] Open up a PR in `wordpress-develop` to enable position CSS values in core ([PR](https://github.com/WordPress/wordpress-develop/pull/3865) | [Trac ticket](https://core.trac.wordpress.org/ticket/57504))

### Related tasks and issues

These tasks might not be immediately related, but in terms of UX and features, there could be some overlap to explore in the implementation:

* [x] https://github.com/WordPress/gutenberg/issues/32644 (this would likely require some kind of z-index controls)

**Comment by jameskoster** [comment]
> e.g. is it possible to achieve without having to wrap the header template part in a sticky Group block?

I've said this elsewhere, but I don't think this is something to be avoided. My opinion is that the _document_ should decide the position of its blocks rather than the blocks themselves. Otherwise it prohibits things like template parts or reusable blocks from being conditionally sticky, unless we build a complex position over-ride UI which probably _is_ something to avoid. 

We can still simplify the process though. Perhaps there's an option in the template part toolbar (ellipsis menu?) to make it sticky, which is essentially a shortcut to wrap it in a container with position: sticky applied.

Which leads me neatly to:

> Update List View to flag in the UI when a block has a position value set

It might be interesting to try a simple prefix (or suffix) added to the block name, denoting non-default position values. "Group (sticky)", for example. We could even consider surfacing this as a variation in the Inserter to enable quick creation of sticky regions in a document.

**Comment by priethor** [comment]
> I've said this elsewhere, but I don't think this is something to be avoided. My opinion is that the document should decide the position of its blocks rather than the blocks themselves.

That's good reasoning. On the other hand, it could also be applied to settings like width and height, as a reusable block will have a different width within a full-width container vs. when placed inside a column. For now, _I think_ we might want to not open that can of worms because if we want the position to be set at the document level, we would need to review what other settings should follow the same logic.

**Comment by jameskoster** [comment]
The challenge we face with any such setting is clarity around where/when they will be applied. For example we used to have a background color option for template parts. This constantly tripped people up, because they'd edit a template, select the Header, change the background, and expect that change to be applied to the template part globally.

We'd run into that problem again here. That's not to say it's insurmountable. Just that we'd need to consider a 'local overrides' UI with resetting, or some foundational changes to the inline editing experience that draws clearer lines between document + template part / reusable block (https://github.com/WordPress/gutenberg/issues/43608 might help).

**Comment by apeatling** [comment]
My vote would go for allowing block supports on template parts, because:

* This follows the most logical path for a user based on how everything else works. Select the template part like a block, set to sticky.
* It allows a user to decide which templates a template part is sticky on.
* It avoids any extra UI, wrapping it in a group block will be unexpected, muddy block selection, and users will wonder how it got there.
* You can be super selective on which block supports a template part utilizes -- just leave out things like background color that have confused in the past. *(Edit: this doesn't solve the global vs local confusion)*
* Maybe there could be a way in the future to set the default supports values (like sticky) by a pattern author when being inserted within a template part?

I'm probably missing some important details and nuance. :)

**Comment by andrewserong** [comment]
Great discussion here, folks! I love the idea of exposing the position controls at the template part block level in terms of making it that accessible / discoverable to a user. However, @jameskoster makes a good point that this runs into issues to do with the local versus global nature of editing template parts. That is, the position value will only be set on the particular instance of the template part within the template being edited, and won't be applied globally to the header template part across all templates. Figuring out the desired UX there (and technical implementation if we went with document-level attributes) might be quite tricky, too... 🤔

To give us a little more to play with to come up with a direction forward, I've opened up a PR to opt the template part block in to the position support over in https://github.com/WordPress/gutenberg/pull/47133 — this PR isn't intended to land, but I thought I'd open it up to hopefully have something to aid the discussion about how we should proceed. My first impression is that it feels pretty good to use, but as in the reasoning behind the earlier removal of styles from the template part block (in https://github.com/WordPress/gutenberg/pull/36571), I can definitely see how a user would expect their changes to apply across templates, and be confused as to why it isn't. I could imagine that being a blocker.

**Comment by fabiankaegy** [comment]
I was just playing with the position control and struggled to figure out how to make my header template part sticky. So the current flow is creating a bad experience for someone that doesn't necessarily understand the technical details. 

I really like the idea of exposing the position controls on the template part as well. I think that would help a lot. Additionally, it might be a good enhancement to hide the sticky position setting in areas where it doesn't do anything. If we know that setting it on the wrapping group inside of a template part it isn't ideal that the setting is even available.

**Comment by andrewserong** [comment]
Thanks for the continued feedback, everyone! As another potential idea for how we might improve the UX here, I've opened up a PR to explore adding a warning notice next to the Sticky position control if the group block is at a non-root level (a little bit like how we have contrast checker warnings). The PR is here: https://github.com/WordPress/gutenberg/pull/47207

Using Sticky positioning for things that are not site-wide headers and footers can be quite useful (I see this a lot on real estate websites, or on some sites with contact info areas that scroll for only a particular section), however it's likely not the common use case (which we're imagining to be sticky headers). I'm wondering if the additional notice when the block is not at the root level could help nudge users in the right direction / help with the UX there, irrespective of whether or not we wind up enabling sticky support for the template block.

Another option could be to hide the Sticky position controls altogether if the block is not set to the root of the document — personally, I'd prefer to avoid this if possible, since it's quite cool to be able to create sticky areas within a larger document, and it'd be nice to make that available if we can. Happy for any feedback / ideas / discussion over in #47207 if folks are interested.

**Comment by richtabor** [comment]
> I was just playing with the position control and struggled to figure out how to make my header template part sticky. So the current flow is creating a bad experience for someone that doesn't necessarily understand the technical details.

I agree. It's not intuitive and also buries the Header template part in List view. 

And if buried, the template doesn't show up in the "Template" inspector sidebar. 

<img width="1368" alt="CleanShot 2023-01-17 at 15 48 23@2x" src="https://user-images.githubusercontent.com/1813435/212839413-3f9f1447-0e46-40b6-9ec9-df765aabd28a.png">

**Comment by richtabor** [comment]
Ideally, you'd edit the template part, add sticky positioning, and the stickiness would be applied to the parent template part across the site. 

Kind of a tall order, but is there way to detect and apply the positioning to the template part, if the stickied block is a direct child of a template part block?

**Comment by jameskoster** [comment]
> And if buried, the template doesn't show up in the "Template" inspector sidebar.

I'd say that's a bug. Edit: I opened https://github.com/WordPress/gutenberg/issues/47213

**Comment by andrewserong** [comment]
> I've opened up a PR to explore adding a warning notice next to the Sticky position control

Based on feedback, I've closed out that PR and opened up an alternate PR that explores a simpler change that updates the hint text for Sticky Position to be aware of whether or not the block currently has a parent. It's a subtle change, but hopefully will improve that part of things a little bit: https://github.com/WordPress/gutenberg/pull/47230

**Comment by richtabor** [comment]
Now that https://github.com/WordPress/gutenberg/pull/47334 is merged (and the position is only available on root blocks), we can punt these follow-ups post 6.2.

**Comment by fabiankaegy** [comment]
> - [ ] Open up a PR in wordpress-develop to enable position CSS values in core

I believe this would still be required to happen before the code freeze in order to land the feature in core at all for 6.2

**Comment by emdashftw** [comment]
IMHO it should work for template parts too.

I dislike having to create an inner block to be able to set sticky positioning. 

I've just ended using (as workaround):
```css
.site-header {
    position: sticky;
    top:0;
}
```

**Comment by andrewserong** [comment]
> I believe this would still be required to happen before the code freeze in order to land the feature in core at all for 6.2

@fabiankaegy yes, there's an open PR for this over in https://github.com/WordPress/wordpress-develop/pull/3865. Assuming that lands in time, I'll put up a PR this week for the remaining pieces. I've updated the issue description with a link to that PR and the related trac ticket, thanks for the reminder!

> It'll work on template part elements ?

For 6.2, sticky positioning will not be available on template part elements directly, it'll just be the Group block that's opted in to sticky positioning. To create sticky headers, it's possible to wrap the template part in a sticky group block with a template (the video in the issue description captures the current state).

**Comment by courtneyr-dev** [comment]
I thought I almost had a weird workaround going through **Template Parts**, but it doesn't display on front of site this way. 
https://user-images.githubusercontent.com/5519705/221712563-a65e8c1f-6466-45e5-9fdc-49aeff3dccee.mp4

**Comment by andrewserong** [comment]
@courtneyr-dev for it to work with template parts, the template part itself needs to be wrapped in a Group within the template, at the root level, as `sticky` sticks to the immediate parent. If the sticky block is set within the template part, then it will only stick to the scope of the template part itself (which is to say, it won't appear to be sticky at all).

**Comment by robglidden** [comment]
I would like sticky to work fully with smooth scrolling (scroll-behavior: smooth, scroll-padding-top).  

Canva web pages do this out of the box.  

Like putting sticky on a header template part, then creating a new css variable that would contain the height of the sticky header template part.

**Comment by andrewserong** [comment]
That sounds like a pretty cool feature idea @robglidden. If you have time, would you mind opening up an issue for it, with a little more detail about how you'd expect it to work? Currently the sticky position support is fairly naive, in that it doesn't really know anything about what it's been applied to, and whether or not it should affect things like scroll-padding-top globally, so there could be some nuance in trying to come up with a reliable solution for it.

**Comment by robglidden** [comment]
Sure, @andrewserong 

See #48656 "Make sticky positioning work with internal links and scroll padding"

A starting point: currently, an internal link scrolls to the wrong place when sticky positioning is set on a group.

A modern-Web-first design review would help.

**Comment by andrewserong** [comment]
Thanks so much for the extra detail @robglidden! I've added that issue to the list of tasks in this issue's description.

**Comment by bobbingwide** [comment]
I have a question about sticky blocks in posts. 

I just created a post with a sticky block and then displayed this post in a query loop on an archive page that displayed the posts using post content. 

The sticky block was sticky all right. But should it have been?
My view is "Yes, That's fine. It's the documentation of the limitations of sticky position that doesn't cater for this edge case."

PS. I had the same problem as Rich Tabor noted in https://github.com/WordPress/gutenberg/issues/47043#issuecomment-1384956555  But I figured it out while watching the 6.2 Live Demo.

**Comment by andrewserong** [comment]
> The sticky block was sticky all right. But should it have been?

Thanks for raising the question. The sticky position is fairly naive, like all other block supports, so it isn't contextually aware of where it is being displayed when it's rendered. So in this case, I think that's to be expected.

**Comment by andrewserong** [comment]
Small update: I have [an open PR](https://github.com/WordPress/gutenberg/pull/49085) to try to improve the experience of dealing with wrapping a template part block in a sticky group. In https://github.com/WordPress/gutenberg/pull/49085, a "Make sticky" button is added to the block menu for the template part block — when clicked, it'll wrap the block in a sticky group block, and the button only shows if the template part is at the root of the document. Happy for any feedback over on the PR!

**Comment by annezazu** [comment]
👋🏼 [Some feedback that came in](https://wordpress.slack.com/archives/C015GUFFC00/p1681820564058179) through the FSE Outreach Program around a use case for using sticky positioning that I thought would be helpful to pass along. Sharing in case it helps ground future work -- someone wants to create a site where the left hand side is sticky and doesn't scroll whereas on the right side photos/posts scroll by:

https://user-images.githubusercontent.com/26996883/233431043-65c111c7-79cd-4856-8a1e-6ab9fd0c76dd.mov

Because sticky positioning can't be added to a columns block, this isn't currently possible.

**Comment by andrewserong** [comment]
Thanks for sharing @annezazu! That'll be a good test case for us to use when we explore re-adding the sticky position support to non-root positions, and will make a solid argument for its inclusion. Along with opting-in for the columns block (I've added this to the list of tasks). Cheers!

**Comment by apeatling** [comment]
These real usage examples are great and help keep the development grounded. Also gives good ideas for demoing the new functionality. :)

**Comment by andrewserong** [comment]
I have a PR open in https://github.com/WordPress/gutenberg/pull/49321 to explore re-enabling non-root sticky position, and adding a visualizer to define the sticky area visually. It's a little experimental, but very happy for feedback and/or ideas on the PR!

**Comment by ndiego** [comment]
@andrewserong can I remove this from the 6.3 Project Board, or would you prefer we keep it? Just trying to tidy up the board 😅

**Comment by andrewserong** [comment]
Thanks for the ping @ndiego! I've removed this from the project board now as the PRs for 6.3 have all been merged (e.g. https://github.com/WordPress/gutenberg/pull/49321 and https://github.com/WordPress/gutenberg/pull/49122) 🙂

**Comment by apeatling** [comment]
Nice work so far on this @andrewserong, lots of good changes for folks upgrading to 6.3. 👍

**Comment by miklb** [comment]
Has there been any movement on this? I'm struggling to understand how in the current UI to wrap the header template-part in a group in a template? Do I have that part right?

**Comment by miklb** [comment]
> Ideally, you'd edit the template part, add sticky positioning, and the stickiness would be applied to the parent template part across the site.
> 
> Kind of a tall order, but is there way to detect and apply the positioning to the template part, if the stickied block is a direct child of a template part block?

Seems like there should be a way using`:has` but I haven't dug in deep. Just experienced this issue and the counter intuitiveness. Editing every template that uses a header if you want it sticky site wide seems a bit much.

**Comment by SporeProductions** [comment]
Still not working in Twenty Twenty-Five

**Comment by lmisch** [comment]
+1

**Comment by paaljoachim** [comment]
It would be helpful with an update here.
I am not seeing sticky work with Twenty Twenty five theme.

I was able to get it to work with this code:
`/* Sticky header */
header:has(>.is-position-sticky) {
	position: sticky;
	top: calc( 0px + var( --wp-admin--admin-bar--height, 0px ) );
	z-index: 100;
}

@media (max-width: 600px) {
	header:has(>.is-position-sticky) {
		top: 0;
	}
}`

**Comment by andrewserong** [comment]
Hi folks, as described in the issue, Sticky does work in Twenty Twenty Five theme, but the feature currently requires the Header to be wrapped in a root-level Group block that is set to sticky. Here's how that looks (basically the same as in the video in the issue description):

<img width="1276" height="918" alt="Image" src="https://github.com/user-attachments/assets/57a34fbf-3265-4e41-8141-af2bdc15c404" />

The task for allowing template parts to be set to sticky hasn't been implemented yet, I believe due to overall concerns about attaching styles directly to template parts. It's this one from the to-do list:

> Improve the experience for setting a sticky or fixed header, e.g. is it possible to achieve without having to wrap the header template part in a sticky Group block? Related issue: https://github.com/WordPress/gutenberg/issues/50617

@paaljoachim in the meantime, if you're wanting to allow blocks _within_ the header to affect the stickiness of the header itself, the CSS you've described should do the job. It's a bit opinionated, so makes sense to me if individual sites or themes add that kind of CSS if they so choose, rather than including it directly in core themes.

Now that `:has()` has wider browser support, though, it could be worth revisiting how the Sticky position support works if anyone's interested in digging in.
