### ISSUE TITLE
Tracking: Duotone filters

### ISSUE THREAD

**Issue by ajlende** [WordPress/gutenberg#47304]
This tracking issue includes issues that are specific to duotone. https://github.com/WordPress/gutenberg/issues/47302 contains issues for SVG filter support in general.

## Toolbar UI

- [ ] https://github.com/WordPress/gutenberg/issues/31373
- [ ] https://github.com/WordPress/gutenberg/issues/39011
- [ ] https://github.com/WordPress/gutenberg/issues/39452
- [ ] https://github.com/WordPress/gutenberg/issues/38898
- [x] https://github.com/WordPress/gutenberg/issues/38797
- [ ] https://github.com/WordPress/gutenberg/issues/50333

## Missing support

- [x] https://github.com/WordPress/gutenberg/issues/34122
- [ ] https://github.com/WordPress/gutenberg/issues/36541
- [ ] https://github.com/WordPress/gutenberg/issues/49595

## Bugs

- [x] https://github.com/WordPress/gutenberg/issues/48586
- [ ] https://github.com/WordPress/gutenberg/issues/50332

## Performance/Reliability

- [x] https://github.com/WordPress/gutenberg/issues/49169
- [x] https://github.com/WordPress/gutenberg/issues/49170
- [x] https://github.com/WordPress/gutenberg/issues/49171

**Comment by MaggieCabrera** [comment]
Should we add https://github.com/WordPress/gutenberg/issues/50333 to this tracking issue too?

**Comment by hanneslsm** [comment]
@ajlende Can you please add this issue to the list? Thanks!
- [ ] https://github.com/WordPress/gutenberg/issues/52875

**Comment by ajlende** [comment]
@hanneslsm thanks for the report 🙂

There's already an issue for CSS custom properties tracked in https://github.com/WordPress/gutenberg/issues/47302

**Comment by jasmussen** [comment]
Coming back to this one, with most of the issues merged or fixed, I'm going to close this one out in favour of the remaining pieces. Thanks for the work everyone!
