### ISSUE TITLE
Tracking: Top Toolbar Improvements

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#47723]
This issue aims to help track the work, feedback, and issues surrounding enhancing the Top Toolbar.

Primary Issue: https://github.com/WordPress/gutenberg/issues/40450
PR: https://github.com/WordPress/gutenberg/pull/47277

## Goal

Find a MVP for the Top Toolbar enhancements that could potentially land in the next WordPress release.

<details>
<summary>Design Direction</summary>

<image src="https://user-images.githubusercontent.com/846565/210546838-3ea8ba01-6391-4024-8421-cc8e9fd3cd03.png" />
</details>

## Tasks
- [x] Block toolbar needs to be shown when multiple blocks are selected
- [x] Display the block inserter button regardless of if a block is selected
- [x] Toolbar navigation component - Up arrow to switch to doc tools, block type/group icon to switch to block toolbar
- [x] Implement toolbar navigation, trying to [keep the nav buttons in the same position initially](https://github.com/WordPress/gutenberg/pull/47277#issuecomment-1414031006)
- [x] Create a component to combine the parent block, dot delimiter, and block transforms button
- [x] Use combined parent.block component in top toolbar fixing the current parent block button's position
- [x] Add new separators to block toolbar to match the design
- [ ] Update e2es covering Top Toolbar interactions
- [ ] Any a11y enhancements/issues raised through feedback (e.g. fixing [tab order](https://github.com/WordPress/gutenberg/pull/47277#issuecomment-1415169855) )
- [x] [Improve undo/redo visibility on smaller viewports](https://github.com/WordPress/gutenberg/issues/49774)

## Known Issues / Bugs

- In small viewports, or blocks with big toolbars, there isn't enough horizontal space to display all toolbar items neatly. This is especially true when text labels are shown. ( [#40450 (comment)](https://github.com/WordPress/gutenberg/issues/40450#issuecomment-1396557184) )
    - Potential solution: Adding a new component to handle overflow items from the menu. Would require a11y review.
    - Short-term option: Horizontal scrolling for the toolbar was suggested.
- Tooltip positioning is off when opening URLInput popover from block toolbar (appears to be an issue on trunk as well)
    <img width="400" alt="Screenshot 2023-02-02 at 3 25 40 pm" src="https://user-images.githubusercontent.com/60436221/216518284-26177f93-ab69-471f-bef1-c1e8b1cbdf1d.png" />

## Solved Issues / Bugs
- [x] Block toolbar dropdowns display incorrectly (Fixed via https://github.com/WordPress/gutenberg/pull/47277/commits/c22e1029273d72df97095f1c1fe3fd2b68ed24fe)
- [x] Block toolbar dropdowns appear behind the list view sidebar (Fixed after https://github.com/WordPress/gutenberg/pull/47277/commits/c22e1029273d72df97095f1c1fe3fd2b68ed24fe)
- [x] Block transform preview popover trips over cursor and repeatedly animates. Also a problem in the multi-block selection toolbar ( Fixed again by https://github.com/WordPress/gutenberg/pull/47277/commits/c22e1029273d72df97095f1c1fe3fd2b68ed24fe)
- [x] Mutli-block selections result in two toolbars in the header (Fixed in https://github.com/WordPress/gutenberg/pull/47277/commits/06b21538df6e13399cdba1280fd17cf5a0a6b68c)

---
cc/ @draganescu, @talldan, @priethor

**Comment by draganescu** [comment]
We should close this and track #53013. The only remaining item here is 

> Any a11y enhancements/issues raised through feedback (e.g. fixing https://github.com/WordPress/gutenberg/pull/47277#issuecomment-1415169855 )

which is more complex and detailed in #53013 and actioned in https://github.com/WordPress/gutenberg/pull/53779
