### ISSUE TITLE
6.2 Dev Note Tracking Issue

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#47771]
## Tracking all Dev Notes from Gutenberg plugin releases 14.2 - 15.1

Please read the information below carefully. If you have questions, connect with @bph or @zzap via Slack or comment here. 

- **🗓 **Deadline** March 3rd, 2022** 

Not all developer related information needs to be in a separate DevNote on the Make Core blog for the field guide. We can group related information.  We can already make decision on some features if it warrants a stand-alone blog post or if the information will be part of a group post. 

## Stand-alone post
To streamline the process and eliminate bottlenecks, all writers of stand-alone dev notes will receive privileges on the Make Core Blog. (Please connect with @bph or @zzap, if you need access)
**Instructions**
<details>
- Create your note in a new post,
- Save as Draft
- Enable public preview
- Share the link to the public preview in a comment below, as "ready for review"
- "For dev notes, each one must have at least two reviewers" ([Handbook](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/))
</details> 
## Part of a group post
If the information related to your PR will be part of a group post, please write the **dev note in a comment on the PR**, so it can be reviewed and, if necessary commented on, by the release docs team or a reviewer. 

## Before you start writing  📣  please read the handbook pages: 
<details>
- ⭐️ [Writing developer notes](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/)
- ⭐️ [Style & Substance section](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance) of the Post & Comment Guidelines for Make Blog 
- ⭐️ [Documentation Style Guide](https://make.wordpress.org/docs/style-guide/) - Good for reference, when in doubt, especially when English is not your native language.
</details>

The list is incomplete. We are in the process of reviewing plugin release changelogs and add as we progress on the task. 

There are two labels: 
[`needs dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22) and [`has dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+) 

If you worked on a feature/module/component that definitely needs dev note, please assign the label `needs dev note` If you already added the Dev Note to the make blog on draft or as comment on the PR, please label it `has dev note` 

---

~-  #46212 @ellatrix ~ not in core for 6.2
- [x] ~#46885 @getdave~
- [x] #45235 @youknowriad @jsnajdr @tyxla 

### Navigation
- [x] #45976 ~@getdave~ @jffng  
- [x] ~#44739 @draganescu~

### CustomCSS
- [x] #46141
- [x] #46571 @carolinan 

### InspectorControls + Split Block Tools
- [x] #47105 @aaronrobertshaw 
- [x] #47045
- [x] #45005
- [x] #46321
- [x] #46147 

### Experimental APIs
- [x] #43386 @adamziel 

### WP_HTML_Tag_Processor 
- [x] #44410 @adamziel @dmsnell 

### Blocks
- [x] #44455 @tyxla  (G) [DevNote](https://github.com/WordPress/gutenberg/pull/44455#issuecomment-1258045795)
~-  #44771 @Soean ~ no in 6.2
- [x] #42122 @adamziel 
- [x] #46138 @adamziel 

### Theme.json /Appearance Tools
- [x] #45171 @oandregal 
- [x] #45643 @scruffian 
- [x] #45536 @ramonjd (was backport to 6.1.1. but there wasn't a dev note, unless I missed it. ) (covered by dev note for below PR)
- [x] #42489 @ramonjd @andrewserong
- [x] #45089 @adamziel 
- [x] #46138 @adamziel 
- [x] #46502 @madhusudhand

### Components @ciampo @mirka 
- [x] #45340
~-  #43393~
- [x] #45139
- [x] #45302
- [x] #45272
- [x] #46865
- [x] #44391
- [x] #38730 
- [x] #46692 @mirka @brookewp 
- [x] #46006
- [x] #45463
- [x] #46315 
- [x] #47827
- [x] #47883

### Global Styles
- [x] #45960 @ramonjd @andrewserong 
- [x] #45300 @andrewserong 
- [x] #45334 @andrewserong 
- [x] #46388 @andrewserong 

### Layout/ Templates
- [x] #45364 @tellthemachines 
~-  #45509~ @Mamaduka UI only
- [x] #46142 @andrewserong 

### Deprecations/Removals
- [x] #46106 @youknowriad 
~ #46110 @youknowriad~ not yet merged into core
- [x] #47055 @getdave 

### Create Block scaffolding
- [x] #44649 @ryanwelcher  (most updates were already [mentioned in the 6.1 Dev Note](https://make.wordpress.org/core/2022/10/07/create-block-scaffolding-tool-updates/), but it seems to be missing the `customBlockJSON' part. 
- [x] #44185 @gziolo - (already in 6.1)

### Pattern and Pattern Directory
-  #45293 @ryelle - not relevant
-  #45814 @jorgefilipecosta  backend code only. 

### ServerSideRender package
- [x] #44491 @t-hamano

**Comment by ciampo** [comment]
Just flagging that @noisysocks is on parental leave as of today, I guess that the dev note for #45960 could be written by @ramonjd or @andrewserong who also helped on that PR?

**Comment by bph** [comment]
Appreciate the flag @ciampo - I updated the ping for the PR #45960 :-)

**Comment by gziolo** [comment]
> https://github.com/WordPress/gutenberg/pull/44185 @gziolo

That were code changes that propagated what was included in the dev note for WordPress 6.1.

**Comment by t-hamano** [comment]
For some blocks with caption, a toolbar button has been added to add / remove caption. Should a Dev note be written about these UI changes as well?

- #45113
- #44965
- #47325 
- #45112

**Comment by ntsekouras** [comment]
>For some blocks with caption, a toolbar button has been added to add / remove caption. Should a Dev note be written about these UI changes as well?

I don't think a dev note is needed for these, as they are UI changes.

**Comment by bph** [comment]
Totally agree, @t-hamano + @ntsekouras - Keep the questions coming, though.

**Comment by oandregal** [comment]
@bph I've added @pbking and @mikachan for #43337 as they were the ones who implemented that feature :)

---

In the case of https://github.com/WordPress/gutenberg/issues/45171 there's only 1 thing worth having a devnote about (I presume the performance improvements do not require a devnote?). Here's the suggested text:

> `wp_theme_has_theme_json`
>
> WordPress 6.2 introduces a new method called `wp_theme_has_theme_json()`, that returns whether the active theme or its parent has a `theme.json` file. The goal is to provide 3rd parties with a public API they can use to query the active theme for this information.

Being so small a note, I presume it can be published as part of a bigger one?

**Comment by bph** [comment]
@oandregal thanks for the flag, if you want to combine PRs dev notes that is a great way to serve all the details in one post. This might go well with #45089 and others round theme.json and providing extenders with ways to interact with the settings.

**Comment by oandregal** [comment]
> if you want to combine PRs dev notes that is a great way to serve all the details in one post.

I don't plan to, as that's my only and single contribution, and it's quite small :) I'll let others chime in. If there's no better place, it could go as part of the "miscellaneous changes" note ([example in 5.9](https://make.wordpress.org/core/2022/01/04/miscellaneous-core-changes-in-wordpress-5-9/))?

**Comment by t-hamano** [comment]
I added a "ServerSideRender Package" section and wrote a dev note to #44491.

**Comment by draganescu** [comment]
I am not sure that #44739 needs a dev note, it was more like an oversight ... @Mamaduka what do you think?

**Comment by Mamaduka** [comment]
@draganescu probably not. It's a new feature for users.

**Comment by getdave** [comment]
> https://github.com/WordPress/gutenberg/pull/46885 @getdave

This was a selector originally added in https://github.com/WordPress/gutenberg/pull/46531 and then subsequently modified in https://github.com/WordPress/gutenberg/pull/46885. We then decided due to its instability to make it private which I did in  https://github.com/WordPress/gutenberg/pull/47638.

As a result we don't need a dev note as it's a private API.

**Comment by getdave** [comment]
> Fully remove Navigation Editor screen and associated edit-navigation package https://github.com/WordPress/gutenberg/pull/47055 @getdave

Please see [dev note here](https://github.com/WordPress/gutenberg/pull/47055#issuecomment-1424597090).

**Comment by andrewserong** [comment]
> I guess that the dev note for https://github.com/WordPress/gutenberg/pull/45960 could be written by @ramonjd or @andrewserong who also helped on that PR?

Thanks for the ping @ciampo! I've added a draft dev note to the PR for the Style Book here: https://github.com/WordPress/gutenberg/pull/45960#issuecomment-1425002512

Update: draft dev note blog post is here: https://make.wordpress.org/core/?p=102735&preview=1&_ppp=03ed6e05f5

**Comment by andrewserong** [comment]
> * https://github.com/WordPress/gutenberg/pull/45536 @ramonjd (was backport to 6.1.1. but there wasn't a dev note, unless I missed it. ) (covered by dev note for below PR)
> * https://github.com/WordPress/gutenberg/pull/42489 @ramonjd @andrewserong

Since Ramon isn't around, I've added a draft dev note to cover these two over in this comment: https://github.com/WordPress/gutenberg/pull/42489#issuecomment-1425032620

**Comment by aaronrobertshaw** [comment]
> InspectorControls + Split Block Tools

I added a draft dev note in https://github.com/WordPress/gutenberg/pull/47045#issuecomment-1425428525 that aims to cover all the closely related PRs under the "InspectorControls + Split Block Tools" section in this issue's description.

**Comment by adamziel** [comment]
I marked https://github.com/WordPress/gutenberg/pull/43386 as done – it doesn't require a dev note as it's a special case of an API specifically designed not to be used by contributors. I may write a separate post about it, but not a dev note.

**Comment by andrewserong** [comment]
> * https://github.com/WordPress/gutenberg/pull/45300 @andrewserong
> * https://github.com/WordPress/gutenberg/pull/45334 @andrewserong

I've drafted a dev note in this comment (https://github.com/WordPress/gutenberg/pull/45300#issuecomment-1429145904) to cover these PRs under the umbrella of introducing the `minHeight` dimensions block support

> * https://github.com/WordPress/gutenberg/pull/46142

I've drafted a dev note for the sticky position block support in this comment: (https://github.com/WordPress/gutenberg/pull/46142#issuecomment-1429110220) — I've added a couple of "why" headings there to provide answers to some of the feedback raised so far.

**Comment by tellthemachines** [comment]
Dev note for children of flex layout blocks [here](https://github.com/WordPress/gutenberg/pull/45364#issuecomment-1430619266)!

**Comment by andrewserong** [comment]
> * https://github.com/WordPress/gutenberg/pull/46388 @andrewserong

Added a small draft dev note to be included in a Misc dev note in this comment: https://github.com/WordPress/gutenberg/pull/46388#issuecomment-1436142259

**Comment by carolinan** [comment]
I have removed [ ] #43337 @pbking @mikachan  from the list because the feature is not in 6.2.

**Comment by carolinan** [comment]
Short dev note for per-block custom CSS https://github.com/WordPress/gutenberg/pull/46571#issuecomment-1434571591

**Comment by ciampo** [comment]
I made a few changes to the list of components-related PRs:

- Removed #45432 from the list, as it didn't need a dev note (it's just an improvement to the Storybook controls)
- Replaced #45412 with #45139, which seemed more fitting as the PR to which apply the dev note
- Removed #44388, as it didn't need a dev note. Instead, I added #46865 to the list
- Added #47827 and #47883

I then went ahead and added dev notes for all of the PRs in the updated list.

**Comment by adamziel** [comment]
I've drafted a dev note for #42122 and #46138 in a comment at [[Heading block] Add a wp-block-heading CSS class](https://github.com/WordPress/gutenberg/pull/42122#top)

I also drafted a dev note for https://github.com/WordPress/gutenberg/pull/45089 in a comment there.

**Comment by bph** [comment]
Thank you  so much @adamziel  I added the Heading block dev note to the [Misc Editor post ](https://make.wordpress.org/core/?p=102924&preview=1&_ppp=1f21a08839)
And @ndiego drafted the dev note for #45089 on the make blog. (Thank you, Nick)

**Comment by youknowriad** [comment]
@bph I've drafted a dev note for the removed APIs here https://github.com/WordPress/gutenberg/pull/46106#issuecomment-1447800134 We might want to include this in a "miscellaneous editor changes" dev note.

**Comment by bph** [comment]
@ciampo  Thank you so much for re-organizing the Component section of the DevNote tracking issue and writing the small snippets Dev note for each listed PR.  
I put them all into a [stand alone post in the Make Core Blog](https://make.wordpress.org/core/?p=102950&preview=1&_ppp=e9506fe77e) with your name on it. Would you please review it, just to double-check, I didn't have the copy/paste devil on my shoulder. 
Please edit as you see fit.

The two deprecation items, useAnchorRef and DateTimePicker, I added the deprecation section of the [Misc Editor post ](https://make.wordpress.org/core/?p=102924&preview=1&_ppp=1f21a08839)

**Comment by fabiankaegy** [comment]
@bph There is a typo in this section of the Misc Editor post: 

> ## useAnchorRef hook not deleted in 6.3
> 
> The deprecated useAnchorRef hook from the @wordpress/rich-text package will not be deleted in WordPress 6.3, as initially planned. ([#45302](https://github.com/WordPress/gutenberg/pull/45302))

I think it should be 6.2 instead of 6.3

**Comment by bph** [comment]
## Dev Notes published for WordPress 6.2 

- [Introduction of Block Inspector Tabs](https://make.wordpress.org/core/2023/03/07/introduction-of-block-inspector-tabs/) 
- [Shadows in Global Styles with WordPress 6.2](https://make.wordpress.org/core/2023/03/07/shadows-in-global-styles-with-wordpress-6-2/) 
- [Introducing the HTML API in WordPress 6.2](https://make.wordpress.org/core/2023/03/07/introducing-the-html-api-in-wordpress-6-2/)
- [Sticky position block support](https://make.wordpress.org/core/2023/03/07/sticky-position-block-support/)  
- [Upgrading to React 18 and common pitfalls of concurrent mode](https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/) 
- [Add new prop to ServerSideRender component](https://make.wordpress.org/core/2023/03/06/add-new-prop-to-serversiderender-component/) 
- [Custom CSS for global styles and per block](https://make.wordpress.org/core/2023/03/06/custom-css-for-global-styles-and-per-block/)  
-  [Minimum height dimensions block support](https://make.wordpress.org/core/2023/03/06/minimum-height-dimensions-block-support/) 
- [Editor Components updates in WordPress 6.2](https://make.wordpress.org/core/2023/03/03/editor-components-updates-in-wordpress-6-2/)
- [Customize settings for any block in WordPress 6.2](https://make.wordpress.org/core/2023/02/28/custom-settings-wordpress-6-2/)
- [Patterns API expanded to include template_types property](https://make.wordpress.org/core/2023/03/07/patterns-api-expanded-to-include-template_types-property/) 

### [Miscellaneous Editor changes in WordPress 6.2](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/)  

- [Fluid typography minimum font size](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#fluid-typography-minimum-font-size)
-- [How to use the minimum font size in your theme](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#how-to-use-the-minimum-font-size-in-your-theme)
- [Sizing controls for flex layout children](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#sizing-controls-for-flex-layout-children)
- [wp-block-heading CSS class added to every Heading block](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#wp-block-heading-css-class-added-to-every-heading-block)
- [wp_theme_has_theme_json()](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#wp-theme-has-theme-json)
- [Edit block style variations from theme.json](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#edit-block-style-variations-from-theme-json)
- [Updated caching behavior for APIs to access global styles and settings.](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#updated-caching-behavior-for-apis-to-access-global-styles-and-settings)
- [Retaining navigation when switching themes](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#retaining-navigation-when-switching-themes)
- [Disable Openverse category in new Media tab](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#disable-openverse-category-in-new-media-tab)
- [Fixed focus issue after block removal.](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#fixed-focus-issue-after-block-removal)
- [Bug fix: Global Styles for admin users on multi-site](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#bug-fix-global-styles-for-admin-users-on-multi-site)
- [Removal of deprecated APIs and Components](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#removal-of-deprecated-apis-and-components)
-- [Formatting prop in RichText component](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#formatting-prop-in-richtext-component)
-- [useAnchorRef hook not deleted in 6.3](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#useanchorref-hook-not-deleted-in-6-3)
-- [DateTimePicker deprecated prop removal postponed to 6.3](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#datetimepicker-deprecated-prop-removal-postponed-to-6-3)
-- [Deprecate non-string descriptions](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#deprecate-non-string-descriptions)
-- [Removal of the Navigation Editor screen and associated package](https://make.wordpress.org/core/2023/03/07/miscellaneous-editor-changes-in-wordpress-6-2/#removal-of-the-navigation-editor-screen-and-associated-package)

Huge Thank you to all who contributed to dev notes and helped to review them 

_If you find anything missing, please let me know so we can correct that oversight quickly, preferable before the release of 6.2 final release._

**Comment by draganescu** [comment]
In #48204 a change was introduced to the behavior of removing blocks. Previously, when a block was removed, the previous block was selected. However sometimes that resulted in focus loss, if there was no previous block to select.

The update is that if there is no previous block to select, the remove block behavior is updated to select the first parent instead. This should be of little impact, but if an extender relies on always getting the previous block as selection they should update their code to account for the option that sometimes the parent is selected on block removal or opt out of this new default behavior. 

For example the list block had to be updated for this reason in #48204, and it opts out of parent block selection by [passing](https://github.com/WordPress/gutenberg/pull/48204/files#diff-02ae94c65e4e2483a38a6082784e1ff8aa792ee1e9cca282b6c4bab5592e2d26R115) `false` as the second argument when calling `removeBlock`.

**Comment by bph** [comment]
Thank you @draganescu Do you have time to write that in a Dev Note so it can be added to the Misc Editor note?

**Comment by draganescu** [comment]
@bph that is the devnote :)

**Comment by bph** [comment]
@draganescu  You write: "they should update their code to account for the option that sometimes the parent is selected on block removal or opt out of this new default behavior." 

How do extenders opt-out of this new default behavior? I know you link to some other source code, but that's now what dev notes are doing. If you point to code, you can also create a code example, and the reader isn't taking to another page for this tiny information. 


Is the `shouldSelectParent = false;` attributes documented anywhere yet?

**Comment by bph** [comment]
@draganescu Please review the [dev note](https://github.com/WordPress/gutenberg/pull/48204#issuecomment-1460767183). Feel free to augment it.

**Comment by bph** [comment]
The [Field Guide for WordPress 6.2 ](https://make.wordpress.org/core/2023/03/09/wordpress-6-2-field-guide/)was published March 9th at 5am UTC
