### ISSUE TITLE
Tracking: Aspect Ratio

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48079]
### Why aspect ratios

When you add a pattern from the directory to a page, then replace any images with one of your own, the new images are unlikely to fit within the intended design of the pattern. I.e. square images in the pattern won't be square — unless you crop your image further in the editor. The expectation is that you can replace images _without_ breaking the layout. 

This would be especially beneficial for wireframe-style patterns, where an image placeholder could be represented accurately in size and ratio. Patterns actually wouldn't need to include images altogether. 

In the current state, the aspect ratio control exists within the `core/post-featured-image` block. Ideally the aspect ratio control would be exposed to other image-like blocks (and their placeholder states). 

### Theme.json aspect ratios

As detailed in https://github.com/WordPress/gutenberg/issues/38990#issuecomment-1396621330, the available aspect ratio options should be customizable from the theme.json file. 

This way the available ratios could be tailored to a specific site's design language, or new aspect ratios could be added. The expectation here the aspect ratios would be shared across any aspect ratio controls (_including the hard-crop image edit control_). 

### Priority 

- [x] https://github.com/WordPress/gutenberg/issues/48041
- [ ] https://github.com/WordPress/gutenberg/issues/55059
- [ ] https://github.com/WordPress/gutenberg/issues/53652
- [ ] https://github.com/WordPress/gutenberg/issues/47962

### Secondary 
- [x] https://github.com/WordPress/gutenberg/issues/54032
- [x] https://github.com/WordPress/gutenberg/pull/47271
- [ ] https://github.com/WordPress/gutenberg/issues/48110
- [x] Ensure that srcset still works correctly with aspect ratio enabled
- [x] https://github.com/WordPress/gutenberg/issues/47274
- [x] https://github.com/WordPress/gutenberg/issues/38990
- [x] https://github.com/WordPress/gutenberg/issues/48081
- [x] https://github.com/WordPress/gutenberg/issues/48080
- [x] https://github.com/WordPress/gutenberg/issues/47963

**Comment by richtabor** [comment]
>  Ensure that srcset still works correctly with aspect ratio enabled

Confirmed this is working as expected: 

![CleanShot 2023-10-04 at 14 50 29](https://github.com/WordPress/gutenberg/assets/1813435/9dc3f561-266b-4238-9bd7-d2e4dfc1902d)
![CleanShot 2023-10-04 at 14 50 24](https://github.com/WordPress/gutenberg/assets/1813435/53fa90b9-1773-43ea-899a-7eb5faa2ab6d)

**Comment by fabiankaegy** [comment]
Hey @richtabor 👋

What's currently blocking us from moving forward with a spec for defining aspect ratio sizes in theme.json?

In the PR you mention there are some thing to be worked out first but I'm not finding any further insights about what they are. 

Any insights would be greatly appreciated. 

We are very interested in helping move this forward as it is a very common issue we encounter in the enterprise world where style guides call for specific aspect ratios

**Comment by jasmussen** [comment]
Now that the Cover block has aspect ratio support, it'd be nice to revisit the flyout (#48110) so there's some preview of the shape.
