### ISSUE TITLE
Gutenberg 15.3 release checklist

### ISSUE THREAD

**Issue by priethor** [WordPress/gutenberg#48649]
- Gutenberg version to release: 15.3 ([milestone](https://github.com/WordPress/gutenberg/milestone/198))
- Release Manager (a.k.a. Release Lead): @richtabor @priethor 
- Release Date 15.3 RC: March 1st
- Release Date 15.3: March 8th
- Release Manager Buddy: @juanmaguitar
- Previous version changelog (as a reference): [15.2](https://github.com/WordPress/gutenberg/releases/tag/v15.2.0)

### Resources
<details>

 📖 Read: [Leading a Gutenberg Plugin Release](https://codep2.wordpress.com/2021/07/22/leading-a-gutenberg-plugin-release/)
 📖 Read: [Gutenberg Release Process](https://developer.wordpress.org/block-editor/contributors/code/release/)
 📽 Watch: [Gutenberg Plugin: New Release Workflow](https://www.youtube.com/watch?v=TnSgJd3zpJY)
 📽 Watch: [Creating the Gutenberg plugin v12.0 Release Candidate](https://www.youtube.com/watch?v=FLkLHKecxWg)
 📽 Watch: [Gutenberg plugin v12.0.0 Release Party!](https://www.youtube.com/watch?v=4SDtpVPDsLc)
 
</details>

#### Preparation for RC
- [x] Organize and Label PRs on the relevant milestone

#### RC Day
- [x]  Post a [message](https://wordpress.slack.com/archives/C02QB2JS7/p1674637170352029) in #core-editor channel to let folks know you are leading the next GB release
- [x]  Post a [message](https://wordpress.slack.com/archives/C02QB2JS7/p1675155705836649) in #core-editor channel to let folks know you are starting the RC release process
- [x]  Organize any last-minute PRs for the changelog process
- [x]  [Create Draft Release](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
- [x]  Once the changelog is created, publish it(RC) Release
- [x]  [Announce](https://wordpress.slack.com/archives/C02QB2JS7/p1675253355327909) in #core-editor channel that RC1 has been released and is ready for testing
- [x]  Ping any other relevant channels announcing that the RC is available
- [x]  Create [Draft Document](https://docs.google.com/document/d/1ejfJj2zgKCc-6P61FOjSm_2BduUZaMutNz4hmbCODdE/edit) of Release post to be published on Make Core blog ([example](https://docs.google.com/document/d/1quftMN3zhKmph_OTGe4ZiA4pi0ftaA_nBbAU52HG9Dk/edit#))

#### Between RC and stable release
- [x]   [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed). See [Release process docs for details](https://developer.wordpress.org/block-editor/contributors/code/release/#creating-release-candidate-patches-done-via-git-cherry-pick)
- [x]  [Draft Release Post Highlights and changelog](https://github.com/WordPress/gutenberg/issues/47996#)
- [x]  Get assets from [Design team](https://make.wordpress.org/design/) for the post
- [x]  Reach out to Highlight Authors to draft sections (if necessary)

#### Release Day

- [x]  Ensure there are no pending [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed)
- [x]  Check there are [no open PRs in the proper milestone](https://github.com/WordPress/gutenberg/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Gutenberg+15.2%22)
- [x]  Check the release branch (release/15.2) build has no visible regressions
- [x]  Post [a message](https://wordpress.slack.com/archives/C02QB2JS7/p1675848099953319) in #core-editor channel to let folks know you are starting the release process
- [x]  Run [Build Gutenberg Plugin Zip Action](https://github.com/WordPress/gutenberg/actions/workflows/build-plugin-zip.yml) workflow for the stable version
- [x]  Organize and Label PRs on the relevant milestone
- [x]  Create Draft Release
- [x]  Publish Release
- [x]  Trigger the update to the plugin directory - SVN (get approval from member of Core team if necessary)
- [x]  Announce in #core-editor channel that the plugin has been released
- [x]  Reach out to other contributors to help get the post reviewed
- [x]  Publish Release post on Make Core blog
