### ISSUE TITLE
Add descriptions to all panels in the Site Editor's dark sidebar

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48718]
The description affordance in the design provides space for us to explain complex concepts like templates and template parts, and generally make the site editing experience feel more friendly / approachable. We should make use of this affordance and to empty panels like this one:

<img width="1055" alt="Screenshot 2023-03-03 at 10 16 45" src="https://user-images.githubusercontent.com/846565/222694468-dabb006d-fc71-4034-8e47-997db95022d0.png">

- [x] Design panel: https://github.com/WordPress/gutenberg/issues/48712
- [x] Navigation panel: https://github.com/WordPress/gutenberg/pull/48689
- [x] Templates panel
- [x] Manage templates panel
- [x] Template Parts panel
- [x] Manage template parts panel
- [ ] Individual template part panels: https://github.com/WordPress/gutenberg/issues/48483

**Comment by jameskoster** [comment]
A first pass at those panels that do not already have a dedicated issue:

**Templates**
> Express the layout of your site with templates.

**Manage templates**
> Create new templates, or reset any customisations made to the templates supplied by your theme.

**Template Parts**
> Template Parts are small pieces of a layout that can be reused across multiple templates and always appear the same way. Common template parts include the site header, footer, or sidebar.

**Manage template parts**
> Create new template parts, or reset any customisations made to the template parts supplied by your theme.

**Comment by jasmussen** [comment]
Good one. This issue is one of the most important ones we need to still land for 6.2. Just going through these and adding my own:

* Design
"Customise your Navigation menus, Templates, and more."
  * Design → Navigation (:white_check_mark:)
    * Design → Navigation → Page
    "This is a static page.", at minimum
    * Design → Navigation → Posts page
    Ideally "This is your posts page." but "This is a static page." at minimum.
  * Design → Templates
  "Express the layout of your site with templates." seems fine.
    * Design → Templates → Manage all templates
    "Create new templates, or reset any customisations made to the templates supplied by your theme." seems good.
  * Design → Template Parts
   "Template Parts are small pieces of a layout that can be reused across multiple templates and always appear the same way. Common template parts include the site header, footer, or sidebar." seems good.
    * Design → Template Parts → Manage all template parts
    "Create new template parts, or reset any customisations made to the template parts supplied by your theme." seems good.
    * Design → Template Parts → [any random template part]
    At minimum: "This is your [any random template part] part."
    * Design → Template Parts → [any random custom template part]
    At minimum: "This is your [any custom template part] part."

**Comment by jasmussen** [comment]
Essentially, no drilldown detail page should ever be empty. There should always be, at minimum, a description.

<img width="1392" alt="footer template part with missing description" src="https://user-images.githubusercontent.com/1204802/222743616-3c764a61-8af7-40fc-b01e-babeb784b947.png">

It might be useful (not urgent) to refactor the component so a description becomes required, i.e. it outputs something like "This detail page is missing a description".

**Comment by jameskoster** [comment]
> "This is your posts page."

That's a great point. It would be nice if we can mark all those key pages, like in the wp-admin list view:

<img width="327" alt="Screenshot 2023-03-03 at 14 26 52" src="https://user-images.githubusercontent.com/846565/222745723-2fa7e8f8-4af3-49e2-9d56-089ea54a11d0.png">

**Comment by jasmussen** [comment]
Yep. But if it becomes a challenge to snatch those special descriptions, we can do that in a V2, a V1 should at least have a "page" description. 👍 👍
