### ISSUE TITLE
Tracking Issue - Interactivity API runtime for core blocks

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#49868]
- Part of #41236.

The Interactivity API aims to provide a standard way to develop the frontend of Gutenberg blocks, in a way that they can communicate and be combined with each other easily.

Until now, most Gutenberg APIs have focused on the Block Editor, leaving an intentional gap in the frontend. The Interactivity API aims to cover that gap.

Imagine providing user experiences like instant search, add to cart, or comments form without a page reload, in a way that is immediately familiar and compatible with the block ecosystem, without complex scaffolding or external tools, and without sacrificing PHP server rendering and the plugin ecosystem. That's what the Interactivity API is for.

The goal of these tasks is to provide a basic runtime to start experimenting with interactivity in some of the core blocks.

We will start shaping the version of the runtime on [a branch](https://github.com/WordPress/block-interactivity-experiments/tree/refactoring-for-gutenberg) of the [block interactivity experiments repo](https://github.com/WordPress/block-interactivity-experiments), and once it's ready we'll move it to this repository:

- [x] https://github.com/WordPress/block-interactivity-experiments/pull/216
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/103
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/217
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/220
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/223
- [x] Solve bug of props passing to the next element ([context](https://github.com/WordPress/block-interactivity-experiments/pull/156#issuecomment-1438807273)) - won't fix! [check this video](https://github.com/WordPress/gutenberg/issues/49868#issuecomment-1516459288)
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/225
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/224 ([related issue](https://href.li/?https://github.com/WordPress/block-interactivity-experiments/issues/191))
- [x] https://github.com/WordPress/gutenberg/pull/49994
    - **Move the code to `/packages/block-library/src/interactivity`**
    - Prepare a new [webpack config](https://github.com/WordPress/gutenberg/tree/trunk/tools/webpack) with the runtime and the Navigation + Image lightbox view files, [similar to this](https://github.com/WordPress/block-interactivity-experiments/blob/wpmoviesdemo/webpack.config.js). Special attention to [`runtimeChunk`](https://github.com/WordPress/block-interactivity-experiments/blob/wpmoviesdemo/webpack.config.js#L18)
    - Enqueue runtime + vendors + views manually
    - Add `defer` manually to the runtime + vendors + views
    - [x] Add wp-init directive
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/226
- [x] https://github.com/WordPress/block-interactivity-experiments/pull/235
- [x] https://github.com/WordPress/gutenberg/pull/50041
- [x] https://github.com/WordPress/gutenberg/pull/50377
- [x] https://github.com/WordPress/gutenberg/pull/49972
- [x] https://github.com/WordPress/gutenberg/pull/50373 (includes wp-portal)
- [x] https://github.com/WordPress/gutenberg/pull/50732
- [ ] Merge `vendors` and `runtime` in a single file and rename the handle to `wp-interactive`

### Navigation block

- [x] https://github.com/WordPress/gutenberg/pull/50670
- [x] https://github.com/WordPress/gutenberg/issues/50744
- [x] https://github.com/WordPress/gutenberg/issues/50746
- [x] https://github.com/WordPress/gutenberg/issues/50752

**Comment by DAreRodz** [comment]
I've opened a PR that removes full hydration and client-side navigation. It is ready to be reviewed.

- https://github.com/WordPress/block-interactivity-experiments/pull/216

**Comment by DAreRodz** [comment]
I've done the same for removing components.

- https://github.com/WordPress/block-interactivity-experiments/pull/217

**Comment by luisherranz** [comment]
I've [asked the Preact team](https://preact.slack.com/archives/C3M9NTD16/p1681813547348559) about [this PR](https://github.com/preactjs/signals/pull/290) to know if they plan to merge it soon or not. If they don't, I'll add a new issue to incorporate that `data-wp-effect` fix/feature in our codebase. We need that to avoid having to resort to `tick` in cases [like this](https://github.com/WordPress/gutenberg/pull/44509/files#diff-ac3ab677b419ffc1a9537b403c75d082df4ce82942495c2fd7b880e83844002bR24).

**Comment by luisherranz** [comment]
Once we finish, I think the next step would be to introduce priorities because that's going to affect the code of the `Directive` component.

**Comment by luisherranz** [comment]
This is ready for review:

- https://github.com/WordPress/block-interactivity-experiments/pull/103

**Comment by DAreRodz** [comment]
This one is merged:
- https://github.com/WordPress/block-interactivity-experiments/pull/216

And this other one ready for review

- https://github.com/WordPress/block-interactivity-experiments/pull/220

**Comment by luisherranz** [comment]
I have updated the [refactoring-for-gutenberg](https://github.com/WordPress/block-interactivity-experiments/tree/refactoring-for-gutenberg) branch with the latest changes from the main one.

**Comment by luisherranz** [comment]
I've opened a PR for these items: https://github.com/WordPress/block-interactivity-experiments/pull/223

- Switch _wrapper to runningDirectives
- Keep directives in the DOM (related conversation)
- Pass the whole store to evaluate (instead of just state)

---

I'll work on _Solve bug of props passing to the next element_ now.

**Comment by luisherranz** [comment]
> I'll work on Solve bug of props passing to the next element now.

I don't think there's anything to fix at this moment for this one.

It's a bit difficult to explain, so I made a video, but I'll mark the task as completed:

<a href="https://www.loom.com/share/c797fa787d5b4b2da1d19e832fc7205b">
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/c797fa787d5b4b2da1d19e832fc7205b-with-play.gif">
  </a>

https://www.loom.com/share/c797fa787d5b4b2da1d19e832fc7205b

**Comment by luisherranz** [comment]
We've merged everything that was needed before moving this to Gutenberg.

We'll try to move it to Gutenberg now in a new PR.

**Comment by DAreRodz** [comment]
This is the PR that adds the Interactivity API to Gutenberg. It is ready to review.

- https://github.com/WordPress/gutenberg/pull/49994

**Comment by luisherranz** [comment]
I've added these additional items to the list:

- Implement directive priorities
- Add wp-portal directive
- Add wp-init directive

**Comment by artemiomorales** [comment]
I added the following to the list:
- [WIP: Behaviors UI](https://github.com/WordPress/gutenberg/pull/49972)
- [Experiment: Add lightbox to image using directives](https://github.com/WordPress/gutenberg/pull/50373) to the list.

**Comment by gziolo** [comment]
I added the following PRs to the list of tasks:
- https://github.com/WordPress/gutenberg/pull/50041
- https://github.com/WordPress/gutenberg/pull/50377

**Comment by luisherranz** [comment]
I've added three issues to the Tracking Issue discovered by @jeryj that contain accessibility discrepancies between this implementation and the previous one (thanks, Jerry!).

- https://github.com/WordPress/gutenberg/issues/50744
- https://github.com/WordPress/gutenberg/issues/50746
- https://github.com/WordPress/gutenberg/issues/50752 

He also [reported a problem with the `register_block_script_handle` function](https://wordpress.slack.com/archives/C02RP4X03/p1684425991407019?thread_ts=1684403764.422519&cid=C02RP4X03) that we should look into.

**Comment by gziolo** [comment]
> He also [reported a problem with the register_block_script_handle function](https://wordpress.slack.com/archives/C02RP4X03/p1684425991407019?thread_ts=1684403764.422519&cid=C02RP4X03) that we should look into.

I can't reproduce it with the latest version in `trunk`. I'm wondering whether there is anything different with the testing env. I'll also double-check if all files get correctly included in the plugin's zip file.

**Comment by luisherranz** [comment]
It looks like that one was [just a problem with `node_modules`](https://wordpress.slack.com/archives/C02RP4X03/p1684522829778249?thread_ts=1684403764.422519&cid=C02RP4X03) so there's nothing to fix 🙂

Also, @darerodz has been working on the priorities:

- https://github.com/WordPress/block-interactivity-experiments/pull/235

**Comment by luisherranz** [comment]
Closing this as finished, we'll keep working on the next steps on: https://github.com/WordPress/gutenberg/issues/50866

**Comment by luisherranz** [comment]
Reopened to add an additional task to merge both `vendors` and `runtime` together in a single file, and use the `wp-interactivity` handle [because that handle needs to be maintained if this is merged with Core](https://github.com/WordPress/gutenberg/pull/50906#issuecomment-1573643213).

**Comment by luisherranz** [comment]
Closed as we don't need to that anymore.
