### ISSUE TITLE
Patterns / Pattern block tracking issue

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#50159]
This is a high-level tracking issue for patterns. See '[The wp:pattern block](https://github.com/WordPress/gutenberg/issues/48458#top)' for an overview.

### Implement pattern overrides (aka 'partial syncing') in the pattern block

- [ ] https://github.com/WordPress/gutenberg/issues/53705

### Backlog

- [ ] https://github.com/WordPress/gutenberg/issues/57530
- [ ] https://github.com/WordPress/gutenberg/issues/57011

### Completed

<details><summary>WordPress 6.4</summary>

### Allow users to set categories for Patterns
- [x] #53835
- [x] #53163

</details>
<details><summary>WordPress 6.3</summary>

### Rename Reusable block to Pattern and add `unsynced` version

- [x] #51144
- [x] #51078 (Now renamed from 'Library' to 'Patterns'
</details>

**Comment by talldan** [comment]
This tracking issue is pretty old now, so closing
