### ISSUE TITLE
Components: audit accessibility

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#50166]
We should run a package-wise audit for the `@wordpress/components` package.

Each component should be audited primarily in [Storybook](https://wordpress.github.io/gutenberg/), to ensure that it doesn't present any accessibility-related issues in isolation. Of course, more testing in the editor would be great to make sure that the component is used correctly and in an accessible manner.

We could use this PR as a tracking issue for any problems that will arise from the audit.

Instructions:
- whenever you start auditing a component, place your github username next to the component's name (to avoid repeated work)
- add the results of the audit to a new issue, and link it next to the component's name (so that this issue can act as a tracking issue)

**List of components:** 

 - [ ] [`AlignmentMatrixControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/alignment-matrix-control/)
 - [ ] [`AnglePickerControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/angle-picker-control/)
 - [ ] [`Animate`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/animate/)
 - [ ] [`Animation`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/animation/)
 - [ ] [`Autocomplete`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/autocomplete/)
 - [ ] [`BaseControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/base-control/)
 - [ ] [`BorderBoxControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/border-box-control/)
 - [ ] [`BorderControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/border-control/)
 - [ ] [`BoxControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/box-control/)
 - [ ] [`ButtonGroup`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/button-group/)
 - [ ] [`Button`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/button/)
 - [ ] [`Card`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/card/)
 - [ ] [`CheckboxControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/checkbox-control/)
 - [ ] [`CircularOptionPicker`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/circular-option-picker/)
 - [ ] [`ClipboardButton`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/clipboard-button/)
 - [ ] [`ColorControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/color-control/)
 - [ ] [`ColorIndicator`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/color-indicator/)
 - [ ] [`ColorPalette`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/color-palette/)
 - [ ] [`ColorPicker`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/color-picker/)
 - [ ] [`ComboboxControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/combobox-control/) (de-prioritise, since it may be soon overhauled)
 - [ ] [`Composite`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/composite/)
 - [ ] [`ConfirmDialog`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/confirm-dialog/)
 - [ ] [`CustomGradientPicker`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/custom-gradient-picker/)
 - [ ] [`CustomSelectControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/custom-select-control/)
 - [ ] [`Dashicon`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/dashicon/)
 - [ ] [`DateTime`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/date-time/)
 - [ ] [`DimensionControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/dimension-control/)
 - [ ] [`Disabled`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/disabled/)
 - [ ] [`Disclosure`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/disclosure/)
 - [ ] [`Divider`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/divider/)
 - [ ] [`Draggable`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/draggable/)
 - [ ] [`DropZone`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/drop-zone/)
 - [ ] [`DropdownMenu`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/dropdown-menu/) (deprioritize, since it's going to be overhauled soon)
 - [ ] [`Dropdown`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/dropdown/)
 - [ ] [`DuotonePicker`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/duotone-picker/)
 - [ ] [`Elevation`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/elevation/)
 - [ ] [`ExternalLink`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/external-link/)
 - [ ] [`Flex`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/flex/)
 - [ ] [`FocalPointPicker`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/focal-point-picker/)
 - [ ] [`FocusableIframe`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/focusable-iframe/)
 - [ ] [`FontSizePicker`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/font-size-picker/)
 - [ ] [`FooterMessageControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/footer-message-control/)
 - [ ] [`FormFileUpload`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-file-upload/)
 - [ ] [`FormToggle`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-toggle/)
 - [ ] [`FormTokenField`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-token-field/)
 - [ ] [`GradientPicker`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/gradient-picker/)
 - [ ] [`Grid`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/grid/)
 - [ ] [`Guide`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/guide/)
 - [ ] [`HStack`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/h-stack/)
 - [ ] [`Heading`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/heading/)
 - [ ] [`HigherOrder`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/higher-order/)
 - [ ] [`Icon`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/icon/)
 - [ ] [`InputControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/input-control/)
 - [ ] [`IsolatedEventContainer`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/isolated-event-container/)
 - [ ] [`ItemGroup`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/item-group/)
 - [ ] [`KeyboardShortcuts`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/keyboard-shortcuts/)
 - [ ] [`MenuGroup`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/menu-group/)
 - [ ] [`MenuItem`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/menu-item/)
 - [ ] [`MenuItemsChoice`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/menu-items-choice/)
 - [ ] [`Modal`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/modal/)
 - [ ] [`NavigableContainer`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/navigable-container/)
 - [ ] [`Navigation`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/navigation/)
 - [ ] [`Navigator`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/navigator/)
 - [ ] [`Notice`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/notice/)
 - [ ] [`NumberControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/number-control/)
 - [ ] [`PaletteEdit`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/palette-edit/)
 - [ ] [`Panel`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/panel/)
 - [ ] [`Placeholder`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/placeholder/)
 - [ ] [`Popover`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/popover/)
 - [ ] [`QueryControls`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/query-controls/)
 - [ ] [`RadioControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/radio-control/)
 - [ ] [`RadioGroup`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/radio-group/)
 - [ ] [`RangeControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/range-control/)
 - [ ] [`ResizableBox`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/resizable-box/)
 - [ ] [`ResponsiveWrapper`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/responsive-wrapper/)
 - [ ] [`Sandbox`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/sandbox/)
 - [ ] [`ScrollLock`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/scroll-lock/)
 - [ ] [`Scrollable`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/scrollable/)
 - [ ] [`SearchControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/search-control/)
 - [ ] [`SelectControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/select-control/)
 - [ ] [`Shortcut`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/shortcut/)
 - [ ] [`SlotFill`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/slot-fill/)
 - [ ] [`Snackbar`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/snackbar/)
 - [ ] [`Spacer`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/spacer/)
 - [ ] [`Spinner`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/spinner/)
 - [ ] [`StyleProvider`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/style-provider/)
 - [ ] [`Surface`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/surface/)
 - [ ] [`TabPanel`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tab-panel/) (deprioritize, since it may be soon overhauled)
 - [ ] [`TextControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/text-control/)
 - [ ] [`TextHighlight`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/text-highlight/)
 - [ ] [`Text`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/text/)
 - [ ] [`TextareaControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/textarea-control/)
 - [ ] [`Theme`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/theme/)
 - [ ] [`Tip`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tip/)
 - [ ] [`ToggleControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/toggle-control/)
 - [ ] [`ToggleGroupControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/toggle-group-control/)
 - [ ] [`Toolbar`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/toolbar/)
 - [ ] [`ToolsPanel`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tools-panel/)
 - [ ] [`Tooltip`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tooltip/) (deprioritize, since it may be soon overhauled)
 - [ ] [`TreeGrid`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tree-grid/)
 - [ ] [`TreeSelect`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tree-select/)
 - [ ] [`Truncate`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/truncate/)
 - [ ] [`UnitControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/unit-control/)
 - [ ] [`Utils`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/utils/)
 - [ ] [`VStack`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/v-stack/)
 - [ ] [`View`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/view/)
 - [ ] [`VisuallyHidden`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/visually-hidden/)
 - [ ] [`ZStack`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/z-stack/)

**Comment by joedolson** [comment]
A great starting point for this would be if somebody could add a list of components to be tested as tasks on this ticket. That would really help to give a starting point; and as each task is worked on, we can create related issues as subtasks.

**Comment by ciampo** [comment]
That is exactly the plan. @andrewhayward should be able to start looking into this relatively soon, but of course, feel free to help!

I've updated the issue's description with a list of components and instructions on how to collaborate.

**Comment by andrewhayward** [comment]
Probably also worth writing up an auditing guide/template, so that we can be reasonably sure each component is following a similar process.

**Comment by ciampo** [comment]
Sounds like a good idea — happy to follow the advice of folks with more a11y testing expertise

**Comment by joedolson** [comment]
How detailed do you think we'd want to make the auditing guide? Should it be written at a level of detail that people with no prior experience with accessibility testing can do it? Or would it be better to have a multi-level testing process? E.g., a first pass that requires less expertise, then a second pass for more experienced testers.

**Comment by andrewhayward** [comment]
I created an issue (#50931) to track the auditing guide work, just to keep that conversation somewhat separate. Ideally I think it would allow most people to participate, even with limited or testing experience, but I don't really know what the community is capable of, or who's likely to be helping out, so I'm open to suggestions!

**Comment by ciampo** [comment]
We've made several improvements over the years to our components. Also, our efforts are not focused on the new `@wordpress/ui` which is supposed to provide replacements for (most) of the legacy components from `@wordpress/components`.

Given that Andrew is also not working on Gutenberg anymore. I'm going to close this issue. Folks can still open new issues targeting any specific new findings.
