### ISSUE TITLE
Navigation 6.3 Priorities

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#50165]
This issue captures the current priorities for Navigation which we are aiming to include in **WordPress 6.3**. There's also a longer backlog used to more exhaustively track open issues, bugs, and pending tasks at https://github.com/WordPress/gutenberg/issues/38275.

### Main tasks
- [ ] https://github.com/WordPress/gutenberg/issues/45512
- [x] Improvements to fallback mechanics

### Secondary tasks
- [ ] https://github.com/WordPress/gutenberg/issues/50891
- [x] https://github.com/WordPress/gutenberg/issues/50179
- [x] https://github.com/WordPress/gutenberg/issues/50180
- [ ] https://github.com/WordPress/gutenberg/issues/50171
- [x] https://github.com/WordPress/gutenberg/issues/38497
- [x] https://github.com/WordPress/gutenberg/issues/50178
- [ ] https://github.com/WordPress/gutenberg/issues/42598
- [ ] https://github.com/WordPress/gutenberg/issues/31452

--------

### Browse Mode

In addition the following tasks from Browse Mode are related to Navigation and will be worked on by contributors.

https://github.com/WordPress/gutenberg/issues/50396#issuecomment-1545626228

**Comment by getdave** [comment]
## Update 17th May 2023 

- The intended scope of work for the Nav block in WP 6.3 has been refined and confirmed (see this Issue).
- Contributors have [shipped improvements to the fallback mechanics for the block](https://github.com/WordPress/gutenberg/pull/50032). This is now normalised in a dedicated `class` on the PHP side and accessible from the front end via the REST API. These changes improve the UX of the block by always ensuring a Navigation Menu is pre-created meaning there is no "transition" state in the block when it moves from uncontrolled to controlled.
- Contributors have been improving performance by [preloading the key Navigation-related network calls in the Site Editor](https://github.com/WordPress/gutenberg/pull/48683#issuecomment-1451837658).
- Contributors have been engaging in ongoing discussions to refine the scope and purpose of [Navigation in the Browse Mode sidebar](https://github.com/WordPress/gutenberg/issues/50396).
- Work is underway to improve the Link creation interface to improve its utility for the Navigation block (and the editor in general).

**Comment by getdave** [comment]
## Update 7th June 2023

- Contributors are largely focused on adding a Navigation section to the Browse Mode sidebar.
- The sidebar now lists all Navigations and allows basic modifications.
- Work is in progress on [a focus mode for Navigation Menus](https://github.com/WordPress/gutenberg/pull/39286).
- Work on the block itself has been focused largely on [improving the `LinkControl` component](https://github.com/WordPress/gutenberg/issues/50891) in order to provide greater utility to the Navigation block (as well as other contexts).
- Bug fixes and improvements to test coverage continue to receive attention.

**Comment by getdave** [comment]
## Update 16th June

- Contributors have focused heavily on Navigation in Browse mode as a means to enhance the overall experience of Navigation in WordPress in ways that could not be solved via the block. There has been [a lot of progress](https://github.com/WordPress/gutenberg/issues/50396#issuecomment-1594836796).
- [Focus Mode for Navigation Menus](https://github.com/WordPress/gutenberg/pull/39286) has now merged.
- If a [Navigation Menu exists in a Template Part it now displays in the Browse Mode sidebar](https://github.com/WordPress/gutenberg/pull/51492).

**Comment by getdave** [comment]
## Update 4th July

- Contributors are heavily focused on triaging bugs identified during WP 6.3 Beta cycle.
- Navigation ~on Browse Mode~ in Site View will be included in WP 6.3 - you can learn more in [this overview video](https://www.youtube.com/watch?v=s1L28GuA-y0&t=1s). 
- Contributors are also assessing feedback and thinking about tasks to prioritise for the 6.**4** cycle.
- We continue to work on test coverage.

**Comment by getdave** [comment]
## Update 27th July

- A quiet time whilst contributors are (temporarily) focused elsewhere.
- Contributors have been working on some last minute critical bug fixes for 6.3.
- Some thought is going into [what's next for WP 6.4](https://github.com/WordPress/gutenberg/issues/38275#issuecomment-1619747714).

**Comment by getdave** [comment]
As this Issue was regarding 6.3 I think we can close it. The tasks still remain tracked in https://github.com/WordPress/gutenberg/issues/38275.
