### ISSUE TITLE
Template Parts and path towards "library" management

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#50397]
## Milestone 1

- [x] Use two rhomboid icon symbol for template parts menu.

## Milestone 2

- [x] Explore combining patterns, template parts, reusable blocks, font management in a single menu called Library. 
- [ ] Look at lifting Headers and Footers as its own sidebar items. (https://github.com/WordPress/gutenberg/issues/50958)

**Comment by SaxonF** [comment]
Adding a potential pathway here.

We've put far more emphasis on patterns as of late and [will continue to do so](https://github.com/WordPress/gutenberg/issues/48458). The site editor currently doesn't reflect these efforts. This project aims to set the stage for [block unification](https://github.com/WordPress/gutenberg/issues/41717) by introducing the concept of a library which is a dedicated space for all the building blocks of your site.

For this bit of work we can simply rename the Template Parts menu item to Library and introducing category grouping to the list page. This includes Headers, Footers, and any other template parts available.

This new "Library" space is a natural fit for when pattern management becomes a thing.


https://user-images.githubusercontent.com/1072756/236734920-ce774590-52e7-4944-b9c6-2dbd9267db1c.mp4

- [x]  The top level template parts menu item is renamed to library using rhomboid icon initially 
- [ ]  The library panel contains a menu listing all template part areas. Headers and Footers use their corresponding icon while General + others use template-part. Whether these need to drilldowns or just panel sections is worth considering.
- [x] There is an additional "Reusable blocks" menu item that links off the existing re-usable blocks management screen in a new tab
- [x] Much like the existing template parts screen the + button triggers the new template part modal
- [ ] Clicking an area/category takes you to a full list of template parts for that area
- [ ] Within each area, the + button automatically sets the template area on part creation
- [x] Quick links section at the bottom contains "Manage all template parts" which opens the existing template parts page.

**Comment by jasmussen** [comment]
Noting #50028 as related to this one.

**Comment by jasmussen** [comment]
@SaxonF not urgent, but per recent designs (https://github.com/WordPress/gutenberg/issues/50379#issuecomment-1545973738 and https://github.com/WordPress/gutenberg/issues/50392#issuecomment-1553413185 come to mind), would you be able to update your video, or share screenshots instead, with the latest sidebar design? I think we can update this issue and mark it ready for dev with that.

**Comment by briceduclos** [comment]
Is there a Figma file of the UI available on the WordPress.org Team?

**Comment by annezazu** [comment]
Noting that as we explore this Library concept, it would be advantageous to explore how to show the relationship between template parts and templates: https://github.com/WordPress/gutenberg/issues/42482

**Comment by jameskoster** [comment]
Agreed. It doesn't even need to be granular to begin with (though that would be nice). Just marking the items that are actively in use would be helpful. It probably requires a dedicated design effort though, to get the placement right.

Anyway here are some updates to Saxon's earlier visuals, taking into account the latest work around other panels:

<img width="1493" alt="Library" src="https://github.com/WordPress/gutenberg/assets/846565/9d8a4e73-9db7-42e3-9f4b-dcb5210aa788">

Instead of drilldowns for each type, I lean slightly towards a single list for a couple of reasons:

* Sites do not generally have _that_ many template parts, so clicks are reduced.
* It allows the reuse of the browse/manage toggle that has been [proposed for Templates](https://github.com/WordPress/gutenberg/issues/49597#issuecomment-1559628139).
* Doesn't require any hefty modifications to the existing template part management view.
* It's pretty close to what we currently have on trunk, so involves a bit less work. 

The drilldown pattern can be utilised in the future, once _all_ patterns are displayed in the Library and scalability becomes a bigger issue. Of course if I've missed something and the intention is to have that as a part of 6.3, then we should probably use the drilldown straight-away – though it will require some modifications to the management view. 

What do y'all think?

**Comment by jasmussen** [comment]
I like starting simple.

**Comment by jameskoster** [comment]
If font management is to live in a modal, it could easily be accessed from the Library panel, which feels conceptually appropriate. 

We might use the same format as the theme button at the design root:

<img width="862" alt="Screenshot 2023-05-25 at 13 45 37" src="https://github.com/WordPress/gutenberg/assets/846565/2f8264d9-c18d-4f49-886d-6e82c962cb87">

I also moved Reusable blocks outside of the main list, since they will not appear in the management view.

**Comment by mtias** [comment]
One last follow up here: #52042 

Rest is considered accomplished.
