### ISSUE TITLE
Gutenberg Plugin Version 15.8 Release Checklist

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#50426]
This issue is to provide visibility on the progress of the release process of Gutenberg 15.8 and to centralize any conversations about it. The ultimate goal of this issue is to keep the reference of the steps, resources, work, and conversations about this release so it can be helpful for the next contributors releasing a new Gutenberg version.

-   Gutenberg version to release: 15.8 ([milestone](https://github.com/WordPress/gutenberg/milestone/203))
-   Release Manager (a.k.a. Release Lead): @fabiankaegy 
-   Release Date 15.8 RC: May 10th 2023
-   Release Date 15.8: May 17th 2023
-   Previous version change log (as a reference): [15.7](https://github.com/WordPress/gutenberg/releases/tag/v15.7.0)

## Resources

-   📖 Read: [Gutenberg Release Process](https://developer.wordpress.org/block-editor/contributors/code/release/)
-   📽 Watch: [Gutenberg Plugin: New Release Workflow](https://www.youtube.com/watch?v=TnSgJd3zpJY)
-   📽 Watch: [Creating the Gutenberg plugin v12.0 Release Candidate](https://www.youtube.com/watch?v=FLkLHKecxWg)
-   📽 Watch: [Gutenberg plugin v12.0.0 Release Party!](https://www.youtube.com/watch?v=4SDtpVPDsLc)

### RC Day - {Wednesday, May, 10th}

-   [x] _Optional:_ Attend `#core-editor` meeting (14:00UTC)
-   [x] Post a message in `#core-editor` channel to let folks know you are starting the RC release process
-   [x] Organize and Label PRs on the relevant milestone
-   [x] Start the release process by triggering the `rc` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
-   [x] [Update the created Draft Release accordingly](https://developer.wordpress.org/block-editor/contributors/code/release/#view-the-release-draft)
-   [x] [Curate the changelog](https://developer.wordpress.org/block-editor/contributors/code/release/#1-curating-the-changelog) before publishing
-   [x] Publish Release
-   [x] Announce in `#core-editor` channel that RC1 has been released and is ready for testing
-   [x] Ping any other relevant channels announcing that the RC is available
-   [x] Create Draft of Release post on Make Core blog _(initial draft in [Google doc](https://docs.google.com/document/d/1D-MTOCmL9eMlP9TDTXqlzuKVOg_ghCPm9_whHFViqMk/edit))_

### Between RC and Release

-   [x] Post a reminder in #core-editor for backporting PRs to RC (~Label Backport to Gutenberg RC)
-   [x] If there are any PRs marked as [Backport to RC](https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+label%3A%22Backport+to+Gutenberg+RC%22+is%3Aclosed), run the [cherry-pick command to apply them](https://developer.wordpress.org/block-editor/contributors/code/release/auto-cherry-picking/#how-can-i-use-it-for-a-gutenberg-plugin-release) to the release branch. **This needs to be run locally**
-   [x] [Draft Release Post Highlights and Change Log](https://docs.google.com/document/d/1D-MTOCmL9eMlP9TDTXqlzuKVOg_ghCPm9_whHFViqMk/edit)
-   [x] Get assets from [Design Team](https://make.wordpress.org/design/) for the post
-   [x] Reach out to Highlight Authors to draft sections (if necessary)

### Release Day - {Wednesday, May, 17th}

-   [x] Post a message in `#core-editor` channel to let folks know you are starting the release process
-   [x] Start the release process by triggering the `stable` [workflow](https://developer.wordpress.org/block-editor/contributors/code/release/#running-workflow)
-   [x] Update the created Draft Release accordingly. Typically by copy/pasting the last RC release notes and add any changes/updates as needed.
-   [x] Publish Release
-   [x] Trigger the update to the plugin directory. _(Get approval from a member of [Gutenberg Release team](https://github.com/orgs/WordPress/teams/gutenberg-release/members) if necessary)_
-   [x] Announce in `#core-editor` channel that the plugin has been released
-   [x] Reach out to other contributors to help get the post reviewed
-   [x] Publish Release post on Make Core blog

**Comment by bph** [comment]
## Testing changelog 
- Ran the following command: 
```npm run other:changelog -- --milestone="Gutenberg 15.8"``` 
- Reviewed Enhancements and Bugfixes for PRs that are not in a subgroup 
- Looked at Various category = PRs without labels and added labels
- Copy/pasted the issues in a note taking app to curate them further

## List of PRs that had to change the labels. 
### Enhancements - found with no subgroup
- Command center: Add a button to open it from the site editor view mode. ([[50425](https://github.com/WordPress/gutenberg/pull/50425)](https://github.com/WordPress/gutenberg/pull/50425)) -> Addedd Experimental
- Extract the WordPress reusable commands to a dedicated package. ([[49956](https://github.com/WordPress/gutenberg/pull/49956)](https://github.com/WordPress/gutenberg/pull/49956)) -> Added Experimental
- Multi-select: Capitalise B in blocks. ([[50356](https://github.com/WordPress/gutenberg/pull/50356)](https://github.com/WordPress/gutenberg/pull/50356)) -> removed Enhancement, added Bug, and Block Multi Selection
- Remove extraneous "Link" copy from PanelBody components. ([[50186](https://github.com/WordPress/gutenberg/pull/50186)](https://github.com/WordPress/gutenberg/pull/50186)) -> Added Bub + Block Library
### Bug Fixes - found with no subgroup
- Command Center: Fix a style glitch on Safari. ([[50138](https://github.com/WordPress/gutenberg/pull/50138)]
- Fix command menu not re-opening after closing it. ([[50213](https://github.com/WordPress/gutenberg/pull/50213)](https://github.com/WordPress/gutenberg/pull/50213)) -> Added Experimental
- Remove gutenberg plugin mention in schema. ([[50207](https://github.com/WordPress/gutenberg/pull/50207)](https://github.com/WordPress/gutenberg/pull/50207))

### Various


1. - (e2e)(template-parts) Add end-to-end test for editing the title of a new custom template part. ([50195] (https://github.com/WordPress/gutenberg/pull/50195)) -> added E2E Tests
2. - Add a few import required for the React Native wrapper distribution as iOS XCFramework. ([[50009](https://github.com/WordPress/gutenberg/pull/50009)](https://github.com/WordPress/gutenberg/pull/50009))  - mobile - needs to be deleted in RC.
3. - Cleaned up Port Validation and Removed Unnecessary Default Ports. ([[50300](https://github.com/WordPress/gutenberg/pull/50300)](https://github.com/WordPress/gutenberg/pull/50300)) -> Added Bug + Env
4. - Do not show dynamic add new post, add new page commands. ([[50221](https://github.com/WordPress/gutenberg/pull/50221)](https://github.com/WordPress/gutenberg/pull/50221)) -> Added Experimental
5. - Global Styles: Fix positioning of gradient palette popovers on mobile. ([[50233](https://github.com/WordPress/gutenberg/pull/50233)](https://github.com/WordPress/gutenberg/pull/50233)) -> Added Global Styles + Bug
6. - Make eslint-plugin validate dependencies in `useSelect` and `useSuspenseSelect` hooks. ([[49900](https://github.com/WordPress/gutenberg/pull/49900)](https://github.com/WordPress/gutenberg/pull/49900)) -> Added Code Quality
7. - Migrate Adding Patterns Test to Playwright. ([[50083](https://github.com/WordPress/gutenberg/pull/50083)](https://github.com/WordPress/gutenberg/pull/50083)) -> E2E
8. - Migrate Keep Transform Block Test Case to Playwright. ([[49719](https://github.com/WordPress/gutenberg/pull/49719)](https://github.com/WordPress/gutenberg/pull/49719)) -> E2E
9. - Migrate undo to Playwright. ([[48701](https://github.com/WordPress/gutenberg/pull/48701)](https://github.com/WordPress/gutenberg/pull/48701)) -> E2E
10. - Refactor theme previews. ([[50338](https://github.com/WordPress/gutenberg/pull/50338)](https://github.com/WordPress/gutenberg/pull/50338)) -> Added Themes + Bug
11. - Save Hub: Reuse the save button component to save code. ([[50145](https://github.com/WordPress/gutenberg/pull/50145)](https://github.com/WordPress/gutenberg/pull/50145)) -> Added Edit Site + Code Quality
12. - Simplify CustomCSS UI. ([[49721](https://github.com/WordPress/gutenberg/pull/49721)](https://github.com/WordPress/gutenberg/pull/49721)) -> Added Global Styles + Code Quality
13. - Skip  iframe-inline-styles end-to-end test. ([[50320](https://github.com/WordPress/gutenberg/pull/50320)](https://github.com/WordPress/gutenberg/pull/50320)) -> Added E2E Test
14. - Theme Preview: Restrict to admin users. ([[50335](https://github.com/WordPress/gutenberg/pull/50335)](https://github.com/WordPress/gutenberg/pull/50335)) Added Themes + Bug
15. - Theme Previews: Fix refactor. ([[50354](https://github.com/WordPress/gutenberg/pull/50354)](https://github.com/WordPress/gutenberg/pull/50354)) -> Themes + Bug
16. - Typography: Remove duplicate comment. ([[50304](https://github.com/WordPress/gutenberg/pull/50304)](https://github.com/WordPress/gutenberg/pull/50304)) -> Typography + Code Quality
17. - Update some visual details in the add-template modal(s). ([[50143](https://github.com/WordPress/gutenberg/pull/50143)](https://github.com/WordPress/gutenberg/pull/50143)) -> Added Template Editing Move + Bug
18. - Use apiFetch instead of window.fetch. ([[50043](https://github.com/WordPress/gutenberg/pull/50043)](https://github.com/WordPress/gutenberg/pull/50043)) -> Added Core Data + Code Quality
19. - `NavigableContainer`: Convert to TypeScript. ([[49377](https://github.com/WordPress/gutenberg/pull/49377)](https://github.com/WordPress/gutenberg/pull/49377)) -> Added Components + Code Quality

CC @fabiankaegy @priethor 

It took about an hour including documenting the process. 

How to speed it up? 
It probably could be about half the time, without documenting the process, and even less if developers and reviewers of PRs made sure that there are labels attached to PRs.
