### ISSUE TITLE
Expose the minimal Interactivity API in a public package

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#50866]
- Part of #41236.

This list of tasks is aimed at exposing publicly the [minimal version of the Interactivity API](https://github.com/WordPress/gutenberg/issues/49868) that we are using privately for the Core blocks so people can start experimenting with it.

**IMPORTANT**
- We'll work on this in a separate `interactivity` branch. 
- ⚠️ **We won't merge any of this with `trunk`**.
- We'll wait until the WP 6.3 feature freeze to merge it.

### Next

- [x] Add the runtime to its own package (`@wordpress/interactivity`)
- [x] Build that package with Preact
  - We should use our custom Webpack config.
  - We probably don't need this for the `view.js` files. 
- [x] Expose the `store` as a global
  - We don't need to add the `DependencyExtractionWebpackPlugin` yet, we can do `const { store } = wp.interactivity`, but ~~maybe it works out of the box~~ (it worked out of the box).
- [x] Delete the filter that adds defer to the scripts
  - We can add `defer` again later.
- [x] Make the necessary changes to the blocks/behaviors, so they start using this version
  - Move the `interactivity.js` files to simple `view.js` files?
- [x] Delete the private runtime

Once we finish this list of tasks, the `interactivity` branch will be ready to be merged with `trunk` and we can continue adding more features. But again, **we'll wait until the 6.3 feature freeze to merge it**.

**Comment by DAreRodz** [comment]
I'll start moving the runtime to `@wordpress/interactivity`. Once I have a PR, I'll continue with the following tasks in the same PR (if I feel it appropriate). 🧑‍💻

**Comment by DAreRodz** [comment]
This is the PR I've created (currently a draft).

- https://github.com/WordPress/gutenberg/pull/50906

Development is progressing well, although I faced some issues I'd like to discuss. I posted a [comment](https://github.com/WordPress/gutenberg/pull/50906#issuecomment-1561402154) in the PR summarizing them.

**Comment by DAreRodz** [comment]
All tasks are currently finished on https://github.com/WordPress/gutenberg/pull/50906. ✅ 

I think we still have to write a proper README file, but other than that, I don't see any pending work.

The PR is still a draft. As we don't want to merge it yet, I don't know if it would be better to wait to set it as ready for review.

**Comment by luisherranz** [comment]
Amazing work, David! 🎉 

Closing this as finished, we'll keep working on the next steps on: https://github.com/WordPress/gutenberg/issues/51056
