### ISSUE TITLE
LinkControl: Surface contextual suggestions

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50884]
Part of https://github.com/WordPress/gutenberg/issues/50891

Anytime you apply a link initial suggestions `isInitialSuggestions` should be available. Navigation Link block variations already do this; the behavior should be the default across any LinkControl implementation. 

**Default suggestions:** Pages are the default suggestions, though if a `suggestionsQuery` is passed, those defined types use the suggested types instead—i.e. Category Link block uses categories as the default suggestions. 

**Search suggestions (results):** Searching returns all content types, unless there is a `suggestionsQuery` passed. In that case, suggestions should be based on the `suggestionsQuery` type—i.e. Category Link block results are all categories. 

### Tasks
- [x] Suggestions are always surfaced in LinkControl (default to pages _only_). 
- [x] Search suggestions (i.e. results) return all content, unless there are types from `suggestionsQuery`  
- [x] [Remove the "Recently updated" search results label](https://github.com/WordPress/gutenberg/pull/50977).

### Visual 

| Before  | After |
| ------------- | ------------- |
|<img width="350" alt="CleanShot 2023-08-14 at 21 15 13" src="https://github.com/WordPress/gutenberg/assets/1813435/217483cb-38d2-4f02-98d8-d674d2c67bca">|<img width="343" alt="CleanShot 2023-08-14 at 21 16 41" src="https://github.com/WordPress/gutenberg/assets/1813435/0818d9cd-b91b-47f2-9d64-d4d033b167a9">|

**Comment by getdave** [comment]
> Remove the "Recently updated" search results label.

To confirm do you expect that visual users will have sufficient context to know that these are "recent". I think that's a fair assumption. However, for non-visual users we might like to retain this cue in a visually hidden way in order that they can better perceive the interface. Would you agree?

**Comment by richtabor** [comment]
> However, for non-visual users we might like to retain this cue in a visually hidden way in order that they can better perceive the interface. 

Yea, this should do here: https://github.com/WordPress/gutenberg/pull/50977

**Comment by getdave** [comment]
Questions

- should suggestions always be showing on link _creation_ or on editing as well?
- should we apply this conditionally only to rich text links. This would avoid backwards compatibility issues with the UI/UX for consumers of the `<LinkControl>`. We have a prop `showInitialSuggestions` which governs this already.

**Comment by richtabor** [comment]
Only on link creation I think. When you’re editing a link, you should see matched results (already there today).

**Comment by richtabor** [comment]
@draganescu what do you think about rolling out the suggestions work to the general link editing? 

Ideally, anytime you add a link you should have suggestions. This below would have suggestions: 

![CleanShot 2023-10-04 at 11 38 57](https://github.com/WordPress/gutenberg/assets/1813435/ed2c43f9-f84e-4237-84e2-53176be1c4cb)


Related to https://github.com/WordPress/gutenberg/pull/54622#issuecomment-1727796681.

**Comment by draganescu** [comment]
I thought about it as well. The problem is what to suggest? Pages? When linking random bits of text _are the usual_ links more to external contents? Would suggestions that add clutter?

**Comment by richtabor** [comment]
> I thought about it as well. The problem is what to suggest? Pages? 

Yes. What about pages for page post types, and posts for post post types perhaps?

> When linking random bits of text are the usual links more to external contents? Would suggestions that add clutter?

I don't think they'll clutter. There's room as-is to fill in without adding much cognitive load.

**Comment by mikeicode** [comment]
Suggestion:

When adding pages to a navigation block using Page Link, a few page suggestions pop up. However, these options don't update once I add the page to the menu. Ideally, once I add the "services" page to the menu, it wouldn't suggest adding that page again.

![Screen Shot on 2023-11-27 at 15_36_28](https://github.com/WordPress/gutenberg/assets/10353785/b863b626-ad5c-48f5-bfb1-03a810701f06)

In this example, there is an "about" page on the site that I need to add to the menu; ideally, that would be one of the suggestions.

**Comment by richtabor** [comment]
> However, these options don't update once I add the page to the menu. 

Makes sense to me, thanks for sharing this.

**Comment by draganescu** [comment]
I think we should update the PR description and mockups to include this tiny spec of removing what is already added. It could be easily achieved with an exclude list coming from a flattening of the navigation tree.

**Comment by getdave** [comment]
@richtabor @draganescu I'm a bit lost as to the status of this one. I know Andrei did some work here but do we still want to do the tasks in the Issue description?

**Comment by getdave** [comment]
> Search suggestions (i.e. results) return all content, unless there are types from suggestionsQuery

I think we do this already right? If so we can ✅ the relevant box in the description.

**Comment by draganescu** [comment]
This doesn't currently work

![Screenshot 2024-01-12 at 15 37 12](https://github.com/WordPress/gutenberg/assets/107534/2f1b5925-1f20-46aa-8dfb-a0d59ad31866)

The idea is that we show suggestions (defaulting to pages) as soon as the input for link appears.

**Comment by getdave** [comment]
Will be partially solved by https://github.com/WordPress/gutenberg/pull/57743.

**Comment by richtabor** [comment]
> Will be partially solved by https://github.com/WordPress/gutenberg/pull/57743.

Let's close this now. Good work team.
