### ISSUE TITLE
LinkControl: Add control for adding blocks

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50888]
Part of https://github.com/WordPress/gutenberg/issues/50891

Currently, the Navigation Link block adds `LinkControlTransforms` to the foot of LinkControl. 

Instead, let's simplify (while adding more functionality) by nesting the available blocks so that they are available after indicating the intent of adding a block. 

I'm thinking a single "Add block" control that changes the state of LinkControl to a form of the quick inserter. 

### Tasks
- [ ] Append "Add block" item to the foot of LinkControl, from Navigation Link block context _only_. Should be available on the initial state and when search results are rendered (no change from today). 
- [ ] Add "Back" button that when clicked reverts back to initial state of LinkControl.
- [ ] Prioritize the Page Link, Custom Link, Submenu, Home Link, Site Logo, and Social Icons blocks.
- [ ] Add "Browse all" button to open the block inserter in full (same as quick inserter).

### Visual

| Before  | After |
| ------------- | ------------- |
|<img width="360" alt="CleanShot 2023-05-23 at 13 13 10" src="https://github.com/WordPress/gutenberg/assets/1813435/788d2948-21e3-474d-8080-098e2dfa2c54">|<img width="345" alt="CleanShot 2023-05-23 at 13 13 28" src="https://github.com/WordPress/gutenberg/assets/1813435/b6653cab-b80c-4e31-99bb-e738591311bb">|

### Full flow
<img width="885" alt="CleanShot 2023-05-23 at 13 34 57" src="https://github.com/WordPress/gutenberg/assets/1813435/e38fc97b-477c-4997-b5ef-045d967be3e9">

### Related

https://github.com/WordPress/gutenberg/issues/47063

**Comment by getdave** [comment]
This seems good. It's specific to the Navigation Link and Submenu blocks so I'll bear that in mind.

**Comment by richtabor** [comment]
>  and Submenu blocks so I'll bear that in mind.

You can add blocks to submenus?

**Comment by getdave** [comment]
> > and Submenu blocks so I'll bear that in mind.
> 
> You can add blocks to submenus?

Oh no actually you can't. Only "link" blocks. Ignore me 😄

**Comment by draganescu** [comment]
What if we just show the inserter sidebar directly when add block is clicked?
