### ISSUE TITLE
LinkControl: Improve Edit State

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50890]
This proposal focuses on improving the state of LinkControl when editing an existing link.

Part of https://github.com/WordPress/gutenberg/issues/50891

### Tasks

Feel free to break these into individual PRs as needed: 

- [x] Implement general UI changes.
- [x] https://github.com/WordPress/gutenberg/issues/50948
- [x] #50949
- [x] Render the link settings below the "Text" field when toggled.
- [x] #50947
- [x] Suggestions do not render unless the "Link" field value has changed. 
- [ ] If suggestions render, advanced settings do not.
- [x] #50945

### Visuals

| Current  | Proposed |
| ------------- | ------------- |
|<img width="358" alt="CleanShot 2023-05-23 at 14 00 21" src="https://github.com/WordPress/gutenberg/assets/1813435/a1fa8fa8-2382-4fd9-81c4-a2cc521396a6">|<img width="344" alt="CleanShot 2023-05-30 at 11 27 34" src="https://github.com/WordPress/gutenberg/assets/1813435/d4e9c8f1-604a-466b-97d2-a3d0d4b7f165">|

#### Editing a link, showing suggestions
Note that the suggestions in this mockup are based on design tweaks from https://github.com/WordPress/gutenberg/issues/50885:

<img width="857" alt="CleanShot 2023-05-30 at 11 28 47" src="https://github.com/WordPress/gutenberg/assets/1813435/83e38394-4106-49cd-915f-cefb8a0baf86">

#### Toggling link settings
<img width="789" alt="CleanShot 2023-05-30 at 11 29 39" src="https://github.com/WordPress/gutenberg/assets/1813435/cd729d18-651d-4df3-9417-4ebc5eb5654e">

Note that in the visual above the new tab checkbox was value was changed, setting the "Save" button as not disabled.

**Comment by hz-tyfoon** [comment]
Thanks @richtabor for creating this. I'm keeping a note about this one. After checking I'll share a proper feedback on this.

**Comment by getdave** [comment]
Here is a PR which looks lay the ground work to start addressing some of these issues https://github.com/WordPress/gutenberg/pull/50668

**Comment by richtabor** [comment]
Updated visuals based on a11y feedback from https://github.com/WordPress/gutenberg/issues/50950#issuecomment-1564718192

**Comment by christianoliveira** [comment]
We use these controls a lot (nofollow + open in a new tab) and with WordPress 6.3 the controls are now hidden, increasing the amount of clicks/work needed to achieve the same result 😭. 

Is it possible manually roll this specific change back in my installation and/or be able to configure it otherwise?

Thanks so much in advance!

**Comment by getdave** [comment]
There is no way to roll this back for a specific installation. However if you run the Gutenberg Plugin you can take advantage of https://github.com/WordPress/gutenberg/pull/52799/ which "remembers" when you toggle the control open and will persist it in that state across _all_ links until such time as you manually toggle it closed again.

**Comment by christianoliveira** [comment]
@getdave that seems perfect, thanks so much for the fast and helpful answer. Will try it!

**Comment by christianoliveira** [comment]
@getdave sorry, got too excited very early. I have the latest version of Wordpress, is it possible to get this fix (#52799 ) there? If so, how? You mention the plugin, but the plugin was supposed to be used only in older installations, or does it make sense to install it in the latest version of Wordpress?

**Comment by getdave** [comment]
@christianoliveira The Plugin is where rapid development of the block editor takes place. It is merged into WP Core at each major WordPress release. 

The Plugin could be considered "beta" software as it undergoes less testing than when the code ultimately gets merged into WP Core. Therefore I would use with caution.

Unfortunately despite best efforts of all involved [the fix didn't make it into WordPress 6.3](https://github.com/WordPress/gutenberg/pull/52799#issuecomment-1662219172) so you cannot utilise it in that release.

I'm working on https://github.com/WordPress/gutenberg/pull/53531 as well but again that won't land in WP Core until the 6.4 release at the earliest.

**Comment by christianoliveira** [comment]
@getdave thanks for the explanation and for your time

That's sad news, as it will increase the amount of work we have until the next release (or we will need to add the nofollow/"open in a new tab" in other ways, directly in the code)

Unfortunately, this will be a lesson for me in not updating WordPress immediately in the future.
