### ISSUE TITLE
Tracking Issue: Expose the full Interactivity API in `@wordpress/interactivity`

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#51056]
- Part of #41236.

In [Expose the minimal Interactivity API in a public package](https://github.com/WordPress/gutenberg/issues/50866), we exposed publicly the private and minimal version of the Interactivity API that we were using to test the Core blocks.

This new list of tasks is aimed to complete the Interactivity API publicly testable version, so it's the same _full_ version as the one used in the [block interactivity experiments repository](https://github.com/WordPress/block-interactivity-experiments) (but without client-side navigation yet, which we'll add in a second phase).

_Please, refer to the new [Docs Tracking Issue](https://github.com/WordPress/gutenberg/issues/53296) to keep track of the documentation efforts._

### Tasks

- [x] Add the full Interactivity API runtime (but removing the client-side navigation)
  - [x] Add missing directives: https://github.com/WordPress/gutenberg/pull/51194
  - [x] Add missing e2e tests: https://github.com/WordPress/gutenberg/pull/52952
  - [x] Add missing JSDocs to the code: https://github.com/WordPress/gutenberg/pull/52469
- [x] Add first docs and structure (as markdown files in Gutenberg for now): https://github.com/WordPress/gutenberg/pull/52462
- [x] Add server-side rendering: https://github.com/WordPress/gutenberg/pull/51229
  - [x] Add the `wp_store` function: https://github.com/WordPress/gutenberg/pull/51191
- [x] Add `defer` again to all the interactive blocks (and runtime): https://github.com/WordPress/gutenberg/pull/52536

### Discarded

- ~~Add `wp-html` (decide final name and research security issues).~~

**Comment by luisherranz** [comment]
I'm working on the `wp_store` function. I'll open a PR tomorrow.

**Comment by luisherranz** [comment]
There you go:

- https://github.com/WordPress/gutenberg/pull/51191

---

I'll start migrating the SSRing next. I'll update the Tracking Issue with more detailed tasks for that.

**Comment by DAreRodz** [comment]
I recently created a draft PR with the branch where I started working on porting the entire Interactivity API runtime (without CSN).

- https://github.com/WordPress/gutenberg/pull/51194

So far, I moved the missing directives and all the e2e tests unrelated to the client-side navigation feature. I had to refactor the tests a little bit, and I'm not yet convinced with the current arrangement.

I think we can get rid of our fixture to serve local HTML files and use a custom plugin with compiled `view.js` files. There are some examples of plugins used for e2e tests in [/packages/e2e-tests/plugins](https://github.com/WordPress/gutenberg/blob/adefb8905a17bc3d2b991fc15a3e1a387d10e0c2/packages/e2e-tests/plugins).

Also, I'm not compiling any `js` file yet, and I had to expose `preact`, `preact/hooks` and `deepsignal` from the runtime, as some test implementations were using them.

**Comment by luisherranz** [comment]
> I'll start migrating the SSRing next. 

There you go:

- https://github.com/WordPress/gutenberg/pull/51229

> I'll update the Tracking Issue with more detailed tasks for that.

I don't think it's necessary anymore as I did all the tasks in that PR.

**Comment by luisherranz** [comment]
Surficing [this comment](https://github.com/WordPress/gutenberg/pull/51194#issuecomment-1576676659) here. I will work on a PR to do the syntax changes from https://github.com/WordPress/block-interactivity-experiments/pull/239.

Also, I added a task to the list to work on `wp-html` at a later point.

**Comment by luisherranz** [comment]
Done: 

- https://github.com/WordPress/gutenberg/pull/51241

---

Let's try this order:

1. Merge the syntax changes.
1. Merge `trunk` with `interactivity`
1. Merge the server-side rendering.

**Comment by luisherranz** [comment]
Ok, those are merged and I also merged `trunk`.

**Comment by DAreRodz** [comment]
I just merged the PR that adds the missing directives and the e2e tests we had in the block-interactivity-experiments repository. Those tests have been adapted to follow the same format used in Gutenberg.

- https://github.com/WordPress/gutenberg/pull/51194

**Comment by DAreRodz** [comment]
I created a small PR to improve security on the store serialization. It's ready for review.

- https://github.com/WordPress/gutenberg/pull/51974

**Comment by luisherranz** [comment]
An update on the progress of these tasks, and other related Interactivity API improvements:

- @westonruter opened a PR that adds the `defer` strategy to all the frontend block scripts, including the Interactivity API ones: https://github.com/WordPress/gutenberg/pull/52536
- @darerodz and I improved the logic of the priority levels: https://github.com/WordPress/gutenberg/pull/52323
- @juanmaguitar created the first version of the Interactivity API Readme: https://github.com/WordPress/gutenberg/pull/52104
- @juanmaguitar added the docs folder and some initial texts, including a Getting Started guide: https://github.com/WordPress/gutenberg/pull/52462
- @juanmaguitar added an interactive block template for `@wordpress/create-block`: https://github.com/WordPress/gutenberg/pull/52612
- @ryanwelcher added some refinements to the interactive block template for `@wordpress/create-block`: https://github.com/WordPress/gutenberg/pull/52801
- @darerodz added JSDoc coverage of the public APIs: https://github.com/WordPress/gutenberg/pull/52469
- @darerodz after moving all the e2e tests from the old repo to Gutenberg (https://github.com/WordPress/gutenberg/pull/51194), he started working to add the missing e2e tests and increase our test coverage
- @c4rl0sbr4v0 and I added the runtime logic of the `wp-style` directive: https://github.com/WordPress/gutenberg/pull/52645
- I changed the way we identify blocks without parent blocks because it was messing up with a CSS hash: https://github.com/WordPress/gutenberg/pull/52557

---

So this is almost ready to go. I think we can consider it completed as soon as David publishes his e2e PR, we merge the JSDocs one, and Weston's `defer` PR is merged.

After that, we'll think about the next milestones and we'll publish a new Tracking Issue.

**Comment by luisherranz** [comment]
@darerodz opened a draft PR for the last task, add missing e2e tests:

- https://github.com/WordPress/gutenberg/pull/52952

**Comment by luisherranz** [comment]
An update on the progress of these tasks, and other related Interactivity API improvements:

- @westonruter merged his PR to add the `defer` strategy to all the frontend block scripts, including the Interactivity API ones: https://github.com/WordPress/gutenberg/pull/52536
- @juanmaguitar opened and merged a PR to add the first docs for the API: https://github.com/WordPress/gutenberg/pull/52948
- I opened and merged a PR to remove `wp-show` from the runtime until we finally figure out how it should behave: https://github.com/WordPress/gutenberg/pull/53240
- @DAreRodz opened a PR to add the missing e2e tests and increase our test coverage: https://github.com/WordPress/gutenberg/pull/52952
- @c4rl0sbr4v0 opened and merged a PR to add support for underscores and leading dashes in the suffix part of the directive: https://github.com/WordPress/gutenberg/pull/53337

Apart from that, @juanmaguitar opened a new [Docs Tracking Issue](https://github.com/WordPress/gutenberg/issues/53296) to coordinate the documentation efforts, so I won't report documentation updates here anymore. Please subscribe to that Tracking Issue to keep track of that progress.

**Comment by luisherranz** [comment]
Everything here is finished, including:

- https://github.com/WordPress/gutenberg/pull/53363

I've opened a new Tracking Issue with a new set of improvements to the Interactivity API.

- https://github.com/WordPress/gutenberg/issues/53740

Please, subscribe to the new one if you want to keep updated!
