### ISSUE TITLE
Image block: Implement aspect ratio control

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51138]
Based on the design explorations in https://github.com/WordPress/gutenberg/issues/38990, let's implement the  aspect ratio control for the `core/image` block. 

### Visual 

<img width="1621" alt="CleanShot 2023-05-31 at 15 58 05" src="https://github.com/WordPress/gutenberg/assets/1813435/8fc50d61-d8de-4d02-89b0-423d5b7590dc">

[Figma Prototype](https://www.figma.com/proto/fyUf77Obv8KszngM2PQeMG/Image-Filters%2C-Editing-Tools%2C-Image-Masking?page-id=1001%3A15505&type=design&node-id=1041-19768&viewport=-3683%2C93%2C0.5&scaling=min-zoom&starting-point-node-id=1041%3A19768&show-proto-sidebar=1)

### Objective

If I have an aspect ratio applied to an Image block with a set height and width, I should be able to drop in another image and the aspect ratio, height, and width values are all maintained. 

### Tasks

- [ ] Add "Aspect Ratio" SelectControl below "Resolution" to core/image block.
- [ ] Set default value of the aspect ratio control to "Original".
- [ ] Update edit/save.
- [ ] If block has aspect ratio and intrinsic height/width, set both inputs to "Auto"
- [ ] If block has aspect ratio value, render Contain/Cover ToggleGroup.
- [ ] If one input is changed, calculate the other (maintaining "Auto" visually). 
- [ ] If both inputs are changed, set aspect ratio select to "Custom" and use the non-intrinsic height/width values as the aspect-ratio css.

### Follow-up

- [ ] Add support for height, width, and aspect ratio controls for Image blocks without media (placeholder).

**Comment by ajlende** [comment]
In order to use the same dropdown we had in the Featured Image block, I think 'Custom' will have to be an option from the beginning.

I can probably auto-fill the width/height controls when it is selected if that's okay. For example, if square ratio is selected and width is 100, then selecting custom will set height to be 100. If both are auto, then it can use the values from the intrinsic width and height.

@richtabor does that seem reasonable to you?

**Comment by ajlende** [comment]
> I think 'Custom' will have to be an option from the beginning.

One problem I see with doing this is that I'd expect to be able to set the custom aspect ratio and let the image fill the wide width or something, for example. Unfortunately, that won't be possible because the width and height have units.

Likewise, if I wanted the image to be 50% width and 16:10 (custom) aspect ratio, that isn't possible.

**Comment by ajlende** [comment]
I'd say 'classic' makes me think 3:2 instead of 4:3. Not sure why we chose 4:3 for the cropping tool, but since we're already diverging from that, maybe we could use 3:2 instead here?

**Comment by richtabor** [comment]
> In order to use the same dropdown we had in the Featured Image block, I think 'Custom' will have to be an option from the beginning.

In trunk, the Post Featured Image block uses "Original" if there is no aspect ratio set:

<img width="278" alt="CleanShot 2023-05-31 at 12 43 35" src="https://github.com/WordPress/gutenberg/assets/1813435/a752d9d5-e0bc-4d77-9ab3-305c32428efe">

> I can probably auto-fill the width/height controls when it is selected if that's okay. For example, if square ratio is selected and width is 100, then selecting custom will set height to be 100. If both are auto, then it can use the values from the intrinsic width and height.

I'm not following. A user wouldn't _select_ "Custom"—"Custom" would be applied for you, if both the height and width input fields are modified.

**Comment by richtabor** [comment]
> Likewise, if I wanted the image to be 50% width and 16:10 (custom) aspect ratio, that isn't possible.

I think that's fine. The alternative is to set the image in a row/column and use that as the bounding element (which is what most folks do with layouts/patterns that include images anyhow).

**Comment by ajlende** [comment]
> I think that's fine. The alternative is to set the image in a row/column and use that as the bounding element (which is what most folks do with layouts/patterns that include images anyhow).

Does that mean the meaning of width/height changes if you have an aspect ratio selected?

i.e. When aspect ratio is 'Original' the width and height set, `width` and `height` is set in CSS. And when aspect ratio is something else, `aspect-ratio` is set to the `width / height` and `width` is not set.

**Comment by ajlende** [comment]
> I'm not following. A user wouldn't select "Custom"—"Custom" would be applied for you, if both the height and width input fields are modified.

Even if it gets automatically selected when you set both width and height, 'custom' has to be part of the list.

![aspect ratio options](https://github.com/WordPress/gutenberg/assets/5129775/0285fe3b-f4b0-4945-81a6-a0b668c6552f)

And to be clear, 'original' would still need to exist as an option too–it has a different meaning from 'custom'.

**Comment by ajlende** [comment]
If width and height are both set, does the aspect ratio select become disabled?

If so, do you think it will be clear that deleting one of the widths or heights is the way to make it not disabled?

Or if not, what should happen when one of the other aspect ratios is selected?

**Comment by richtabor** [comment]
> And to be clear, 'original' would still need to exist as an option too–it has a different meaning from 'custom'.

Yes, "custom" uses the height/width attributes to define the aspect ratio. 

> 'custom' has to be part of the list.

Good point. I'd almost want it to be labeled "Freeform". 

> If width and height are both set, does the aspect ratio select become disabled?

No, if height and width are set, then aspect ratio should be "custom" and the height/width are used as the aspect ratio CSS. That way I could drop in a new image and maintain the aspect ratio, re https://github.com/WordPress/gutenberg/issues/38990#issuecomment-1562799519.  

> Or if not, what should happen when one of the other aspect ratios is selected?

If I change from a custom/freeform aspect ratio to a defined ratio, like square, then we should keep the width and reset height to auto - to employ the aspect ratio. What do you think of that?

**Comment by ajlende** [comment]
Thanks for the answers!

> 'custom' has to be part of the list.
>
> > Good point. I'd almost want it to be labeled "Freeform".

> if height and width are set, then aspect ratio should be "custom" and the height/width are used as the aspect ratio CSS.

Brainstorming ideas here to make it clear that the width and height controls change their meaning. Maybe it could be something like "Use width/height for aspect ratio"? That seems a bit long, but I worry, as it is, that there could be some confusion around what width/height do.

> If I change from a custom/freeform aspect ratio to a defined ratio, like square, then we should keep the width and reset height to auto - to employ the aspect ratio. What do you think of that?

👍

**Comment by richtabor** [comment]
I think it's clear enough that "Custom" will use the height/width values. It's also more likely "custom" is applied when the height and width have been changed (instead of selecting it from the Select). 

We can follow-up with additional descriptive text perhaps, if custom is selected; not a blocker imo though.

**Comment by richtabor** [comment]
> I'd say 'classic' makes me think 3:2 instead of 4:3. Not sure why we chose 4:3 for the cropping tool, but since we're already diverging from that, maybe we could use 3:2 instead here?

I've updated the proposal above with this:

<img width="204" alt="CleanShot 2023-05-31 at 15 59 25" src="https://github.com/WordPress/gutenberg/assets/1813435/0e00d1e1-0920-4b34-9f4b-8a6200ec3818">

I think I like it fine. Can surely iterate further, but not a blocker.

**Comment by ajlende** [comment]
@richtabor I'm struggling again with the details of custom ratios as I've been trying to implement this.

At the moment, the image block dimensions represent pixel values, but in many other places, like the post featured image block, the fields include selectable units. I see units in your design, and I'd rather not add a second implementation for aspect ratio specific to the image block, so I'd like to add units to the image block as part of my PR.

There are three problems that I'm running into while I'm trying to do this.

1. An aspect ratio is unitless. If we're replacing the width/height controls to represent an aspect ratio, we can only really do that if the units are the same. I can't convert `width: 100%; height: 300px;` to a ratio without knowing the layout of the page and converting the `%` to `px` or vice versa. I was going to just clear the values if the units are different, but that doesn't really feel good—to have the values you typed in disappear when selecting a ratio and having the units disappear as well.

2. Switching from `px` units to the default `height: auto; max-width: 100%;` is going to change the layout of the page. This issue exists even if we create a separate implementation for the image block that doesn't use the unit controls because there are still implicit `px` units. Someone who selects an aspect ratio is going to be surprised when their 200px width image suddenly becomes full width when they select an aspect ratio. If they want to keep the 200px width they have to know to add a wrapper block where a width can be set. It's removing functionality that people are used to in the image block when an aspect ratio is selected, and that doesn't feel very good.

3. The Post Featured Image block currently supports setting a custom width with the aspect ratio selected. This functionality would be removed using these designs. It isn't a problem allowing existing blocks to still render the same as it did before, but from a UX perspective, that functionality may be missed.

Problems 1 & 3 could be solved by creating a second implementation for the image block, but eventually we're going to want to use the same implementation in all places—it's just postponing the problem and adding additional complexity with deprecations and backwards compatibility.

**Comment by richtabor** [comment]
>  I see units in your design, and I'd rather not add a second implementation for aspect ratio specific to the image block, 

> so I'd like to add units to the image block as part of my PR.

> Switching from px units to the default height: auto; max-width: 100%; is going to change the layout of the page. 

I don't think we should change too much with the initial implementation. I'd be fine omitting units; just using px (as-is) and auto. 

> The Post Featured Image block currently supports setting a custom width with the aspect ratio selected. This functionality would be removed using these designs.

I'm not following. We set them to auto if an aspect ratio is applied (say 1:1), but if you type in an integer value that value should be applied — like in this view below, where I'm adding 100 (px) for the width. The result would be a 100x100px image. 

<img width="351" alt="CleanShot 2023-06-10 at 11 24 22" src="https://github.com/WordPress/gutenberg/assets/1813435/fc9bea87-79ab-4622-87a2-3b4541f925ee">

**Comment by richtabor** [comment]
> Someone who selects an aspect ratio is going to be surprised when their 200px width image suddenly becomes full width when they select an aspect ratio. 

We shouldn't need to make the image full width/wider — just use the intrinsic width value. If I upload an image that is 800px wide, and select 1:1 aspect ratio, it would be 800x800px.

**Comment by ajlende** [comment]
> We shouldn't need to make the image full width/wider — just use the intrinsic width value. If I upload an image that is 800px wide, and select 1:1 aspect ratio, it would be 800x800px.

Let's say I upload an image with a resolution of 3840x2160px. In the editor, I changed the width to be 800px so it isn't so wide on the page. Then I select 1:1 aspect ratio. Now the size of the image is 3840x3840px on the page, not the 800px that I want it to be.

**Comment by ajlende** [comment]
The css changes from 

```css
height: auto;
max-width: 100%;
width: 800px;
```

to 

```css
height: auto;
max-width: 100%;
aspect-ratio: 1;
```

if the meaning of the height and width controls is supposed to represent an aspect ratio.

**Comment by ajlende** [comment]
> I don't think we should change too much with the initial implementation. I'd be fine omitting units; just using px (as-is) and auto.

I want to use the same component for Post Featured Image, so that would be removing the existing unit select functionality there.

<img width="264" alt="image" src="https://github.com/WordPress/gutenberg/assets/5129775/95ac867b-f8ca-4be5-8674-f38be9a25c2e">

**Comment by porg** [comment]
When you do this, please also closely observe these aspects:
1. Resizing via drag-handles: Resizes proportionally.
    - Modifier key to temporarily override proportional resizing: Not offered. Would be fine.
    - Proposed modifier keys should respect design app conventions:
      - SHIFT to toggle proportional resizing
      - ALT to resize from the center (where appropriate).
      - CMD to toggle snapping to nearest preset AR (should this get implemented)
   - As soon as you trigger a manual override, the dropdown menu (as in the mockups) would need to update to "Custom".
      - Further resizing would maintain that "Custom" AR.
      - Using the modifier key again later would update the "Custom" AR again to a new value.
2. Resize image by number fields
    - Mostly resizes without maintaining aspect ratio.
    - But a few times I experienced that numerical resizing (by either of the three methods: number input, arrow-up/down keys, arrow up/down buttons within numfield) maintained aspect ratio!
    - I cannot reproduce the precondition reliably, but the instance I remember, prior to num-input I had resized via handles.
    - Observed in: WordPress 6.2, plugin Gutenberg  15.9.1, Safari 16.5, macOS 11 Big Sur

**Comment by porg** [comment]
https://github.com/WordPress/gutenberg/assets/737143/e0850830-0e88-4153-89f1-d5b6001842d1


https://github.com/WordPress/gutenberg/assets/737143/7cbdab1f-514e-41ac-a1dd-795e1abb45dd


https://github.com/WordPress/gutenberg/assets/737143/8708c237-8c57-4ec3-aa73-6f6e24d1abc1

**Comment by ajlende** [comment]
@porg Thanks for taking the time to make some videos. I'll keep them in mind when working on this, but dragging and modifier keys are related to the `ResizableBox` component which would add too much to the scope of this issue. Would you mind opening up a new separate issue with those things?

**Comment by ajlende** [comment]
@richtabor I think I was just confused earlier by the units disappearing in the design. After coming back to this after a break I think what you intended was having the width/height controls always control the `width` or `height` CSS properties like always.

The "Custom" aspect ratio shouldn't actually create a custom aspect ratio, and it probably doesn't even need to set the `aspect-ratio` property if both width and height are specified in CSS.

**Comment by richtabor** [comment]
> The "Custom" aspect ratio shouldn't actually create a custom aspect ratio, and it probably doesn't even need to set the aspect-ratio property if both width and height are specified in CSS.

As long as the aspect ratio is unset if both height and width are changed.

**Comment by AhmadRaza9** [comment]
Is there any way to filter gutenberg image block aspect ratio, I want to add my custom aspect ratio (5/4)

**Comment by annezazu** [comment]
@AhmadRaza9 check out the latest WordPress developer post on adding custom aspect ratios: https://developer.wordpress.org/news/2024/08/05/registering-custom-aspect-ratios-in-wordpress-6-6/
