### ISSUE TITLE
Wayfinder: Second round of commands

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51502]
Not all of these may be possible, but here's a list of what would be interesting to include based on [context](https://github.com/WordPress/gutenberg/pull/50543):

## Site Editor, view & edit
- [x] Reset styles to default / Same action as pressing the "Reset to defaults" control in the Styles panel, actions menu #51637
- [x] Open style revisions / Same action as pressing the "X revisions" control in the Styles panel, actions menu #51637
- [x] Open custom CSS /  Same action as pressing the "Additional CSS" control in the Styles panel, actions menu
- [x] Learn about Styles / Same action as pressing the "Welcome Guide" control in the Styles panel, actions menu #51637
- [x] View site in new tab / Same action as the "View site" control in the Site Editor

## Site Editor, edit mode
- [x] Open styles panel / Opens the style panel on the right

## Site Editor & Post Editor, edit mode
- [x] Open settings panel / Opens the block inspector settings panel
- [x] Toggle list view / 
- [x] Toggle spotlight mode /
- [x] Toggle distraction free mode ([related](https://github.com/WordPress/gutenberg/pull/51173))
- [x] Toggle top toolbar / Sets the editor to use the top toolbar, if not already (and vise-versa)
- [x] Toggle code editor / Sets the editor to the code editor view, if not already (and vise-versa)
- [x] Editor preferences / Opens the "Preferences" modal from the top-level "Options" vertical ellipsis menu
- [x] Keyboard shortcuts / Opens the "Keyboard shortcuts" modal from the top-level "Options" vertical ellipsis menu
- [x] Manage Reusable blocks

## Post Editor
- [x] Toggle fullscreen mode
- [ ] Allow comments on this post (if disabled) 
- [ ] Disable comments on this post (if enabled)
- [x] View outline / Opens the List view > Outline sidebar

**Comment by richtabor** [comment]
cc @youknowriad

**Comment by youknowriad** [comment]
I started adding some of these commands here https://github.com/WordPress/gutenberg/pull/51637 (the first group above). I'd love for more folks to help adding commands because:

 1- It's easy
 2- The more persons try, the better feedback we get on the API...

**Comment by youknowriad** [comment]
>  Allow comments on this post (if disabled)
> Disable comments on this post (if enabled)

I think these two commands are a bit weird, in the sense that they actually make changes to the post, contrary to all the other commands listed above. I think it's fine to have them but maybe better for another issue with similar commands. It feels a bit random here.

**Comment by richtabor** [comment]
> I think it's fine to have them but maybe better for another issue with similar commands. It feels a bit random here.

Sure, that's fine. I was just thinking of different _types_ of commands that would require varying methods of implementation, to help lay solid examples for other commands of this nature.

**Comment by ntsekouras** [comment]
Should we make the `open styles` -> `toggle styles sidebar`? 🤔 If yes and we're not in `edit` mode, should we have a different command to only `open styles`?
