### ISSUE TITLE
Enhancement: Add "Turn to Columns" to the Block Options dropdown

### ISSUE THREAD

**Issue by mathetos** [WordPress/gutenberg#5190]
## Issue Overview
Columns is an experimental feature. For it to be successful, there should be quite a few things. Namely:

* Column area padding setting (issue to be created)
* Support for all block types within columns (issue to be created)
* Converting existing paragraphs into columns (which is this issue)

Very often, users create content simply by typing it into the screen. From there, they might circle back and want to adjust the layout of the page. In order to do that effectively with columns, we need a "Turn into Columns" feature of the existing paragraph block. See here:

![image](https://user-images.githubusercontent.com/930724/36518194-58839d78-173a-11e8-83af-8b2a51065884.png)

## Todos
- [ ] Add the option into existing paragraph blocks
- [ ] Test that it works as expected in various browsers
- [ ] Test that it works after saving the page both in Preview and Publish mode

**Comment by mathetos** [comment]
Sounds good. I've got Zenhub so I can see the Projects there, that looks great. Thanks for the heads up!
