### ISSUE TITLE
Tracking: Library & Pattern Management Issues

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#51948]
The following lists cover known bugs and issues for the current state of the Library and pattern management features. Ideally, we'll get as many of these done as possible before the 6.3 beta 1; however, some work is likely to flow into the beta period, as enabled by the [_Introducing the Library_ blessed ticket](https://core.trac.wordpress.org/ticket/58579).

**Note: When adding a PR to this tracking issue, make sure it has the `Backport to WP Beta/RC` label on it if it should be included in the WP beta, thanks**

## Todo

- [ ] https://github.com/WordPress/gutenberg/issues/52005
- [ ] https://github.com/WordPress/gutenberg/issues/52421 - (Possible duplicate: [51937](https://github.com/WordPress/gutenberg/issues/51937)) - actually just displaying padding as specified by the theme - I think [we might have to live with this](https://github.com/WordPress/gutenberg/pull/52776#issuecomment-1642872876)

## In Progress

- [ ] https://github.com/WordPress/gutenberg/issues/52227 - [PR](https://github.com/WordPress/gutenberg/pull/52548)
- [x] https://github.com/WordPress/gutenberg/pull/52476

## Completed

- [x] [Rename "Library" to just "Patterns"](https://github.com/WordPress/gutenberg/issues/52042#top) - [PR](https://github.com/WordPress/gutenberg/pull/52102) - @aaronrobertshaw
- [x] [Where’s the template part table view gone?](https://github.com/WordPress/gutenberg/pull/51078#issuecomment-1607488515) - [PR](https://github.com/WordPress/gutenberg/pull/51961)  - @aaronrobertshaw
- [x] [Library: synced pattern shows as "standard" and unsynced](https://github.com/WordPress/gutenberg/issues/51923#top) - [PR](https://github.com/WordPress/gutenberg/pull/51952) - @aaronrobertshaw 
- [x] https://github.com/WordPress/gutenberg/issues/52003 - [PR](https://github.com/WordPress/gutenberg/pull/52021) - @kevin940726
- [x] [Patterns: when editing in the Site Editor, sidebar lists "Template" rather than "Pattern"](https://github.com/WordPress/gutenberg/issues/51925#top) - [PR](https://github.com/WordPress/gutenberg/pull/51953) - @aaronrobertshaw~
- [x] [Patterns: Detail page doesn't reference sync state](https://github.com/WordPress/gutenberg/issues/51926#top) - [PR](https://github.com/WordPress/gutenberg/pull/51954) - @aaronrobertshaw
- [x] [My Patterns vs. Custom Patterns](https://github.com/WordPress/gutenberg/issues/51939) - [PR](https://github.com/WordPress/gutenberg/pull/51949) @SaxonF
- [x] [Library: Set custom patterns as the initial state](https://github.com/WordPress/gutenberg/issues/51943) - [PR](https://github.com/WordPress/gutenberg/pull/51946) @SaxonF
- [x] [Normalize template parts and pattern icons in "new" dropdown](https://github.com/WordPress/gutenberg/issues/52043#top) - [PR](https://github.com/WordPress/gutenberg/pull/52108) - @jameskoster
- [x] [Inconsistent pattern creation modals](https://github.com/WordPress/gutenberg/issues/51941) - [PR](https://github.com/WordPress/gutenberg/pull/51946) @SaxonF
- [x] [Custom Patterns not displayed in Pattern Modal](https://github.com/WordPress/gutenberg/issues/51844#top) - [PR](https://github.com/WordPress/gutenberg/pull/51889)
- [x] [Switching from editing page to pattern causes incorrect editing template notification](https://github.com/WordPress/gutenberg/issues/51927#top) - Was already fixed in [51880](https://github.com/WordPress/gutenberg/pull/51880)
- [x] [Library: In the mosaic of entries template parts do not display the correct icon](https://github.com/WordPress/gutenberg/issues/51905#top) - [PR](https://github.com/WordPress/gutenberg/pull/51963) - @carolinan
- [x] https://github.com/WordPress/gutenberg/issues/51992.
- [x] https://github.com/WordPress/gutenberg/pull/51897
- [x] [Make library's default category fallback to header template parts if user has no custom patterns](https://github.com/WordPress/gutenberg/pull/51949#pullrequestreview-1500638083)
- [x] https://github.com/WordPress/gutenberg/issues/52023 - [PR](https://github.com/WordPress/gutenberg/pull/52034) - @t-hamano 
- [x] https://github.com/WordPress/gutenberg/pull/52112~ - @kevin940726 
- [x] #52151
- [x] https://github.com/WordPress/gutenberg/issues/51969
- [x] https://github.com/WordPress/gutenberg/issues/51295
- [x] https://github.com/WordPress/gutenberg/pull/51990 - @kevin940726
- [x] https://github.com/WordPress/gutenberg/issues/52101 - [PR](https://github.com/WordPress/gutenberg/pull/52159) - @aaronrobertshaw 
- [x] [In 16.1 synced patterns added in the library have incorrect sync status set](https://github.com/WordPress/gutenberg/pull/52229) - @glendaviesnz 
- [x] https://github.com/WordPress/gutenberg/pull/52230
- [x] [Fix site editor animation when moving from "edit" to "view" mode](https://github.com/WordPress/gutenberg/issues/51903) - [PR](https://github.com/WordPress/gutenberg/pull/51956) - (status: looking for volunteers to take this over)
- [x] https://github.com/WordPress/gutenberg/issues/52253
- [x] https://github.com/WordPress/gutenberg/pull/52273 - @aaronrobertshaw 
- [x] https://github.com/WordPress/gutenberg/pull/52263 - @kevin940726 
- [x] https://github.com/WordPress/gutenberg/pull/52340
- [x] https://github.com/WordPress/gutenberg/pull/52382
- [x] https://github.com/WordPress/gutenberg/pull/52395
- [x] https://github.com/WordPress/gutenberg/pull/52355
- [x] ["Manage Patterns" to open the Library > Custom patterns](https://github.com/WordPress/gutenberg/issues/51944) - [PR](https://github.com/WordPress/gutenberg/pull/52403) - @aaronrobertshaw
- [x] [Custom Patterns: Allow renaming and duplication within the Site Editor](https://github.com/WordPress/gutenberg/issues/51919#top) (particularly renaming for 6.3) - [PR](https://github.com/WordPress/gutenberg/pull/52270) - @aaronrobertshaw 
- [x] https://core.trac.wordpress.org/ticket/58716
- [x] https://github.com/WordPress/gutenberg/issues/52006
- [x] https://github.com/WordPress/gutenberg/issues/52009
- [x] https://github.com/WordPress/gutenberg/issues/52435
- [x] https://github.com/WordPress/gutenberg/issues/51310
- [x] [Add client side pagination to improve performance of list page](https://github.com/WordPress/gutenberg/pull/52538)
- [x] [Add pagination to the 'My Patterns' view & switch sync status to toggle group filter](https://github.com/WordPress/gutenberg/pull/52303) - [Alt approach](https://github.com/WordPress/gutenberg/pull/52396) - @kevin940726 
- [x] https://github.com/WordPress/gutenberg/pull/51898 - @getdave 
- [x] https://github.com/WordPress/gutenberg/pull/52599 
- [x] https://github.com/WordPress/gutenberg/issues/52419  - [PR](https://github.com/WordPress/gutenberg/pull/52449) @t-hamano
- [x] https://github.com/WordPress/gutenberg/pull/52458
- [x] https://github.com/WordPress/gutenberg/pull/52656
- [x] [Snackbar notices don't stay anchored to bottom of Patterns page](https://github.com/WordPress/gutenberg/pull/52270#issuecomment-1623647731)
- [x] [Block Inserter: Error displayed in browser console when opening custom pattern categories](https://github.com/WordPress/gutenberg/issues/51873#top) - [PR](https://github.com/WordPress/gutenberg/pull/51947) @glendaviesnz @talldan
- [x] [Custom Pattern: Each time you switch pattern categories, the number of custom patterns increases](https://github.com/WordPress/gutenberg/issues/51872#top) - [PR](https://github.com/WordPress/gutenberg/pull/51947) @glendaviesnz @talldan
- [x] [Patterns: remove ability to change sync state in UI with a classic theme](https://github.com/WordPress/gutenberg/issues/51920#top) - [PR](https://github.com/WordPress/gutenberg/pull/51998) - @glendaviesnz
- [x] [Pattern block: Rename "Convert to regular block" to "Unsync"](https://github.com/WordPress/gutenberg/issues/51940) - [PR](https://github.com/WordPress/gutenberg/pull/51993) @richtabor
- [x]  [Move the sync_status field to top level post field](https://github.com/WordPress/gutenberg/pull/52146)
- [x] Should we rename `sync_status` to `wp_sync_status`? - [question asked here](https://wordpress.slack.com/archives/C02QB2JS7/p1688091498250399). Looks like we are too late to consider this as 16.1 already out with existing naming.
- [x] [Unsynced patterns created in site editor not appearing in post inserter]
- [x] https://github.com/WordPress/gutenberg/pull/52346
- [x] [ Import and export of patterns does not take into account sync status](https://github.com/WordPress/gutenberg/issues/52333) - [PR](https://github.com/WordPress/gutenberg/pull/52346) - @glendaviesnz
- [x] [ Import notice is incorrect](https://github.com/WordPress/gutenberg/issues/52331)  - [PR](https://github.com/WordPress/gutenberg/pull/52346) - @glendaviesnz
- [x] https://github.com/WordPress/gutenberg/pull/52012
- [x] [Patterns: update block description based on sync status/optionality](https://github.com/WordPress/gutenberg/issues/51922#top) - [PR](https://github.com/WordPress/gutenberg/pull/52010) - @glendaviesnz 
- [x] https://github.com/WordPress/gutenberg/issues/52139 - [PR](https://github.com/WordPress/gutenberg/pull/52160) 
- [x] https://github.com/WordPress/gutenberg/issues/52194
- [x] https://github.com/WordPress/gutenberg/issues/52614
- [x] https://github.com/WordPress/gutenberg/pull/51771 
- [x] [Adding pattern from wp-admin page gives no option to add sync status ](https://github.com/WordPress/gutenberg/issues/52329) - [PR](https://github.com/WordPress/gutenberg/pull/52352) - @glendaviesnz 
    - This might be something that has to wait until post 6.4, the PoC proved we could rely on the summary panel to present the modal.
- [x] https://github.com/WordPress/gutenberg/pull/52497 
- [x] https://github.com/WordPress/gutenberg/pull/52663
- [x] https://github.com/WordPress/gutenberg/pull/52747
- [x] https://github.com/WordPress/gutenberg/pull/52742
- [x] https://github.com/WordPress/gutenberg/pull/52780
- [x] [Library: Browser scrollbar blinks at certain browser width](https://github.com/WordPress/gutenberg/issues/52027#top)
- [x] https://github.com/WordPress/gutenberg/issues/52491 - [PR](https://github.com/WordPress/gutenberg/pull/52817)
- [x] https://github.com/WordPress/gutenberg/pull/52764
- [x] https://github.com/WordPress/gutenberg/pull/52933 
- [x] https://github.com/WordPress/gutenberg/pull/52961

## Closed

- [x] https://github.com/WordPress/gutenberg/pull/51985

## Future Follow-ups

- [ ] [Make lock icons more consistent between theme patterns in the site editor page and the "Lock" menu item from the block toolbar's more menu](https://github.com/WordPress/gutenberg/issues/51948#issuecomment-1631540891)
- [ ] [Add nicely designed empty state explaining how to use patterns for when default category is empty](https://github.com/WordPress/gutenberg/pull/51949#issuecomment-1609240546)
- [ ] [Custom patterns: Library and Inserter 1:1](https://github.com/WordPress/gutenberg/issues/51945) 
    - Needs design / Pending feedback
    - We could still get a draft PR together that includes synced patterns alongside unsynced patterns
- [ ] Add import/export for patterns to the Patterns library
- [ ] https://github.com/WordPress/gutenberg/issues/52360
- [ ] https://github.com/WordPress/gutenberg/issues/52150
- [ ] https://github.com/WordPress/gutenberg/issues/51099
- [ ] https://github.com/WordPress/gutenberg/issues/52137
- [ ] https://github.com/WordPress/gutenberg/issues/52107 - Different to 51919 by adding to pattern/template sidebar nav screen
- [ ] [Patterns: use correct icon when searching with the slash inserter](https://github.com/WordPress/gutenberg/issues/51921#top) have suggested we push this to post 6.3. The current behaviour is by design so an enhancement and not a bug - should be reviewed but not critical enough to prioritise for 6.3
 - [ ] https://github.com/WordPress/gutenberg/issues/52132
 - [x] https://github.com/WordPress/gutenberg/issues/53209 - [PR](https://github.com/WordPress/gutenberg/pull/53205)

**Comment by jasmussen** [comment]
As a followup to #51939, and based on the designs attached for that, one thing we could do is add a little lock icon with a tooltip for theme patterns, indicating that they are not editable in the library:

<img width="842" alt="read-only patterns" src="https://github.com/WordPress/gutenberg/assets/1204802/a326398f-3efb-4df4-a1f0-5ef3be0c7ac5">

<img width="839" alt="read-only patterns 2" src="https://github.com/WordPress/gutenberg/assets/1204802/db23caa9-9ad2-4fd3-b236-2aab4709c9f6">

**Comment by kevin940726** [comment]
@jasmussen I created https://github.com/WordPress/gutenberg/pull/51990 for [this](https://github.com/WordPress/gutenberg/issues/51948#issuecomment-1609222337)!

**Comment by ndiego** [comment]
I believe https://github.com/WordPress/gutenberg/issues/52101 needs to be added to this list.

**Comment by annezazu** [comment]
Offering up https://github.com/WordPress/gutenberg/issues/52137 and https://github.com/WordPress/gutenberg/issues/52139 for consideration

**Comment by t-hamano** [comment]
I believe #51295 is no longer reproduced in WordPress 6.3 and the latest Gutenberg, so I have closed it. Please see [this comment](https://github.com/WordPress/gutenberg/issues/51295#issuecomment-1616660620).

**Comment by t-hamano** [comment]
I added #52107 because I think it is partially related to this tracking issue.

**Comment by pablohoneyhoney** [comment]
Would it make sense to connect a bit better the lock icon identifiers? https://github.com/WordPress/gutenberg/pull/51771#issuecomment-1602515612

**Comment by colorful-tones** [comment]
#52614 might need to be added to this list. @ndiego @annezazu

**Comment by aaronrobertshaw** [comment]
As the 6.3 release cycle is coming to a close, it's time to close this tracking issue. Anything left outstanding will continue to be addressed through follow-ups for 6.4, or a 6.3.1 point release if required.

A huge thanks to everyone that helped in the effort to improve pattern management in time for 6.3! 🙇

**Comment by aaronrobertshaw** [comment]
A project has been created to track follow-up efforts for patterns: https://github.com/orgs/WordPress/projects/129

**Comment by bvlgn** [comment]
> A project has been created to track follow-up efforts for patterns: https://github.com/orgs/WordPress/projects/129

I get a 404.
Is that link correct?

**Comment by annezazu** [comment]
Ah the project is accidentally private. @aaronrobertshaw I tried to update the project to be public but found I can only close it. Perhaps we need to recreate and have it public from the start or you might be able to see more settings here: https://github.com/orgs/WordPress/projects/129/settings

**Comment by glendaviesnz** [comment]
It should be public now hopefully.

**Comment by aaronrobertshaw** [comment]
Apologies for missing that @bvlgn & @annezazu.

Thanks @glendaviesnz for tweaking the project's visibility 👍
