### ISSUE TITLE
Duplicating templates and patterns in the site editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52107]
<img width="480" alt="Screenshot 2023-06-29 at 10 33 22" src="https://github.com/WordPress/gutenberg/assets/846565/29a2a0fb-90c7-4674-8bb6-8b954bb2a07e">

Extracted from https://github.com/WordPress/gutenberg/issues/50392.

Sometimes the quickest way to get started with a new template or pattern design is to duplicate an existing one, and customise from there. Currently this is a manual process that involves opening the target entry, copying all blocks, then pasting them into the new one. This flow can be streamlined.

Patterns and $custom templates are relatively simple to envision, but other templates will need some design exploration to get right as the template hierarchy will need be considered and communicated during the flow.

### Phase 1
- [x] Duplicate patterns (including reusable blocks and template parts) https://github.com/WordPress/gutenberg/pull/52270
- [ ] Duplicate $custom templates

### Phase 2
- [ ] Duplicate all templates

**Comment by jameskoster** [comment]
For patterns and $custom templates, I think the main question in terms of design is whether the user is asked to name the template on duplication, or whether the system handles that for them, IE creates something like "Template with sidebar (copy)", which can be renamed later.

**Comment by aaronrobertshaw** [comment]
@jameskoster I have a proof of concept up in https://github.com/WordPress/gutenberg/pull/52270

I was working through a separate issue before connecting the dots here. The PR for the moment works via prompting the user to supply a name etc when duplicating a pattern or template part. It reuses the create pattern and create template part modals.

That PR also supports the following:
- renaming and deleting any custom patterns or custom template parts
- duplicating all patterns and template parts (custom or otherwise)

**Comment by jameskoster** [comment]
@aaronrobertshaw Nice, I'll check it out. 

I don't think that will fully close this issue though, as we'll still need to handle templates. Obviously it's fine to do that separately, I'm just noting incase you wanted to remove the `fixes` keyword in the pr.

**Comment by aaronrobertshaw** [comment]
> I'm just noting incase you wanted to remove the fixes keyword in the pr.

Good catch, thank you, I'll remove the `fixes` keyword.

**Comment by annezazu** [comment]
As it relates to duplicating, I wanted to note this issue for consideration as improving the duplication flow might resolve some current user pain points: https://github.com/WordPress/gutenberg/issues/53320
