### ISSUE TITLE
Align page edit features in Site Editor and Post Editor

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52632]
There are a number of smaller edit actions that are available in the post editor, but not the site editor. The mis-alignment means users sometimes need to hop between editors, which can be frustrating.

In addition to the Page Inspector, we should consider the new details panel, and the Command Palette when working out the placement for these items.

- [x] Access to revisions: https://github.com/WordPress/gutenberg/issues/51343
- [x] Switch page template: https://github.com/WordPress/gutenberg/issues/51347
- [x] Create new template while editing the page.
- [x] https://github.com/WordPress/gutenberg/issues/52763
- [x] Make pages trash-able in the full screen editor.
- [x] https://github.com/WordPress/gutenberg/issues/53188
- [x] Page attributes (parent page, order).
- [x] Edit slug.
- [x] Change Author.
- [x] Unify preferences
  - [x] right click override #57468
  - [x] top toolbar #57531
  - [x] spotlight mode #57533
  - [x] whether the list view opens by default #57504
  - [x] show/hide block breadcrumbs #57506
  - [x] distraction free #57590
  - [x] which panels to show on the sidebar #57529
  - [x] showing button text labels #57480
  - [x] constrain text cursor #57479
  - [x] show most used blocks in the inserter #57637
  - [x] block visibility #57639
  - [x] default editor (code/visual) #57642
- [x] Unify commands.
- [x] Unify publishing flow #59878

**Comment by youknowriad** [comment]
Hello folks, so I've been thinking a little bit about it and shared some comments here https://github.com/WordPress/gutenberg/pull/55844#issuecomment-1794318027

I think we've been going about this in the wrong way. We're duplicating more and more components while we could unify both post editor and site editor to use the same code and share components through the existing `@wordpress/editor` package and ultimately just use the exact same "editor" entirely.

I'm going to start working on some of this and my plan is the following:

 - Use the EditorProvider in the site editor (to set the correct postType/postId...)
 - Move the UI components one by one from the site editor to the @wordpress/editor package. (which might allow us to remove duplicated components)
 - Move the shell of the editor (probably the most complex task) as it requires thinking about extensibilty/preferences...
 - Final step: Once all UI components have moved, remove the duplicated state from the site-editor and store and proxy the selectors/actions.

**Comment by jameskoster** [comment]
Should we close this issue and work on refining the document inspector design in the post editor instead?

**Comment by youknowriad** [comment]
I think we should keep this open, we can use it to track that work. IT's going to be a bit of a ride but let's see how it goes. We can consider this one some kind of overview for this unification.

**Comment by youknowriad** [comment]
What about the other way around:

 - The different "template" modes are different between the post and site editor, should we have the exact same way to show pages, lock them, switch to template... in the post editor as well ?

**Comment by youknowriad** [comment]
There's something that also needs design thinking: the way to publish / mark things as private / pending ... differ between both editors, how to align there?

**Comment by ntsekouras** [comment]
>There's something that also needs design thinking: the way to publish / mark things as private / pending ... differ between both editors, how to align there?

It seems to be buggy too(maybe a regression happened at some point). In post editor you have limited statuses available, which can result for example, not being able to make a page a draft again. Unless I'm missing some other UI...

**Comment by youknowriad** [comment]
@ntsekouras there's a "revert to draft" button that appears in the sidebar for this.

**Comment by jameskoster** [comment]
Ideally the entire panel needs some design attention, but that's a larger effort. 

For status my preference would be the site editor implementation where it is clearly communicated including the `private` option. It eliminates the need for the clunky "Revert to draft" button, and feels more aligned with the pages data view work.

Same for the template dropdown, especially as it makes the swap flow more visual. We'll need to add the missing "New template" action though:

<img width="303" alt="Screenshot 2023-11-21 at 11 59 58" src="https://github.com/WordPress/gutenberg/assets/846565/010ea623-b977-48bc-b116-9dceaccb2083">

**Comment by youknowriad** [comment]
@jasmussen @SaxonF @jameskoster A few questions about aligning the "template mode" of the post editor with the site editor.

 - In the site editor we have three modes: template visible but disabled with post, template editable without post, post only (no template). Also the default mode is "template visible but disabled with post"
 - In the post editor, we have two modes: post only and template+post both visible and editable. Also default mode is "post-only"

We need to make decisions about how to align these two flows. The UI @jameskoster shared above is a first step which for me means:

 - The post editor gets the "template editable without post" mode and drops the "template+post both editable at the same time".
 - The post editor gets the "preview template" option to allow "template visible + post and template readonly".

The last remaining question is:

 What do we do with the "default mode". Should that be something configurable? 

 - I think for posts and maybe most CPTs, it's clear that it should probably remain "post-only" in the post editor.
 - What do we do for pages? Do we follow the site editor (template visible but locked by default) or do we keep "post-only" mode as default too in this case.

The other hidden question here is:

The site editor is going to get post and CPT editing capabilities at some point as well. So it should probably also be "post-only" by default for posts there. My thinking is that post editors and site editors should probably have the same behavior for all CPTs and that potentially whether "preview" is enable or not initially could be a CPT config.

**Comment by jameskoster** [comment]
> The post editor gets the "template editable without post" mode and drops the "template+post both editable at the same time".
> The post editor gets the "preview template" option to allow "template visible + post and template readonly".

My instinct is that's fine. 

For pages, I lean towards including the template by default. We got lots of feedback endorsing that direction in the original template preview issue, and I'd say it has been working well in the site editor so far. 

Still, I agree that pages are probably an exception. For other post types, "post-only" makes sense as the default edit mode, with an option to configure otherwise like you suggest.

**Comment by SaxonF** [comment]
+1 to what @jameskoster said.

**Comment by youknowriad** [comment]
Left: Post Editor, Right: Site Editor
<img width="282" alt="Screenshot 2023-12-18 at 11 42 03 AM" src="https://github.com/WordPress/gutenberg/assets/272444/9c9d89c2-77cc-4b0d-8cba-fb8b3c82d3f6"><img width="280" alt="Screenshot 2023-12-18 at 11 42 16 AM" src="https://github.com/WordPress/gutenberg/assets/272444/1d541509-cf20-4e4b-b02d-fa3975fada5e">

These screenshots show the difference between post and site editors sidebar for "pages" after we merge the last two PRs above.

Notice that there's a number of difference still:

 - There's a "Card" with the page title and edit date in the site editor at the top. This card is absent in the post editor. Should we keep the card or remove it in both?
- There's a "Content" panel that is only present in the site editor when "template preview is on", should we add the same panel to the post editor?
- The publish flow is different between post and site editors:
    - In the site editor, everything happens with the "status" dropdown and the save button. So to publish, you change the status in the dropdown and click save, same for marking as draft...
    - In the post editor, it's a bit more involved: Publishing a button that does both save and update the status, we have dedicated buttons for switch to draft and a dedicated small button for saving (keeping as draft). We also have a post publish panel and flow. 
 I believe we should unify these flows, I think the post editor one is probably a bit better because "publishing" is clearer and we want to retain that for posts. So even if the site editor flow is simpler, I think it might be less ideal for users. Curious about your thoughts and how we should unify here.

**Comment by jameskoster** [comment]
The "Card" feels like a hallmark of the site editor to me. It appears when editing templates, parts, patterns, etc. so should remain for pages too imo.

I believe the "Content" panel is a pattern we'll repeat elsewhere (partially synced patterns), so it probably makes sense to persist with that one then refine holistically later as needed.

In general publish flows feel like a separate endeavour and needs further exploration. It's essentially a question of global vs local saving which is tricky in the site editor where you can edit so many different things all in the same session. For instance how would the post editor publish flow work if you also edited global styles, the template, and created a new synced pattern while working on the new page? What if you wanted to save the style changes but discard the page?

**Comment by youknowriad** [comment]
> The "Card" feels like a hallmark of the site editor to me. It appears when editing templates, parts, patterns, etc. so should remain for pages too imo.

My goal is to ultimately have no difference at all between post editor and site editors. I think after the redesign it might even be the same URL. So I believe we should align somehow, I can definitely leave this specific for now but I don't think we should see "post editor" and "site editor" as different things.

> For instance how would the post editor publish flow work if you also edited global styles, the template, and created a new synced pattern while working on the new page? What if you wanted to save the style changes but discard the page?

For what it's worth, this is already possible, the publish flow won't change but you'll have a "dot" next to the "publish button" to save the other changes before going to the publish flow.

**Comment by jameskoster** [comment]
It's possible in the context of a single post or page. But what if you drafted 10 pages in the site editor, would you have to work through the publish panel for each consecutively after saving other global changes? Considering multiple sessions over time that UX starts to feel a bit clunky in my head.

> So I believe we should align somehow, I can definitely leave this specific for now but I don't think we should see "post editor" and "site editor" as different things.

100%, I didn't mean to suggest otherwise. More that the answer to most of these questions would be to lean in the Site Editor direction than the Post Editor one. So in this case including the "Card" with the page/post title.

**Comment by youknowriad** [comment]
> It's possible in the context of a single post or page. But what if you drafted 10 pages in the site editor, would you have to work through the publish panel for each consecutively after saving other global changes? Considering multiple sessions over time that UX starts to feel a bit clunky in my head.

I agree that it's not perfect. I don't like the "double" save effect as well. I feel like the button should do both at the same time personally "publish the current post/page and save all changes to all the other entities" in the same step. Even in the current site editor state, it's clunky to go change the state to publish in a dropdown and then click save, so imagine doing the same for all the pages. That said, I guess what I'm saying is that both are not ideal but that I'd like us to find a way to unify. What it looks like, I don't know.

**Comment by jameskoster** [comment]
In the context of site editing I think we need to tread a little carefully in assuming that users will always want to publish pages at the same time as creating them. The scope is so broad, and its conceivable that you might want to structure your site but not publish anything at all yet. Or publish some but not others, etc. 

If we wanted to align on something _before_ the content editing experience in the admin redesign is fully visualised, I might lean towards the Site Editor approach, but also make the post editors publish panel accessible somehow. Could be a 'split' Save button, a dedicated "Publish" button in the Inspector, or something else...

<img width="1059" alt="Save" src="https://github.com/WordPress/gutenberg/assets/846565/d31c4bac-499b-4b16-b41a-f05669629cc3">

Another option could be to surface the page status in the multi-entity save modal so that you can publish from there:

<img width="1059" alt="modal" src="https://github.com/WordPress/gutenberg/assets/846565/d4db1f04-7444-4adc-afc6-4424ca031f9e">

But these are just rough ideas, and demonstrate why this (imo) needs more design exploration to get right.

**Comment by youknowriad** [comment]
It seems we've largely addressed the initial scope of this issue and we're now moving into aligning the post and site editors more globally. Feels like we should maybe reorganize this issue a bit.

**Comment by SaxonF** [comment]
> Another option could be to surface the page status in the multi-entity save modal so that you can publish from there:

When I originally added status etc to the site editor this was the direction I was leaning towards in the long term. We can still keep status etc in the page inspector its just that we are including a publish flow as part of saving. If we detect only a single post or page has been modified than the save modal can change slightly to put more emphasis on publishing vs saving.

Two follow up issues might be:
- Path towards directing people to this new unified editor from existing post and pages lists
- Improve publish flow

**Comment by jameskoster** [comment]
@youknowriad It's connected to saving a bit, but the one part still missing is the ability to trash a page from the Inspector. I don't know that it needs to be as prominent as the current post editor:

<img width="280" alt="Screenshot 2023-12-19 at 10 32 14" src="https://github.com/WordPress/gutenberg/assets/846565/873bd666-098d-42f7-9eec-b8627ec494d1">

But it should probably be present. There's this menu for templates / parts:

<img width="280" alt="Screenshot 2023-12-19 at 10 33 41" src="https://github.com/WordPress/gutenberg/assets/846565/01f2f22b-403b-4adf-8522-f1a5893a5cd8">

Perhaps we can reuse this pattern for pages? Alternatively we could add an action to the Command Palette (we should probably do that regardless).

**Comment by youknowriad** [comment]
I've started looking at the editor's more menu and the preferences modal. There's a number of preference that IMO should be shared between both editors (since ultimately, both editors will be just one after the WP Admin redesign anyway).

 - right click override
 - top toolbar
 - spotlight mode
 - whether the list view opens by default
 - show/hide block breadcrumbs
 - distraction free
 - which panels to show on the sidebar (note that this one is not visible at the moment in the site editor's modal)
 - showing button text labels 
 - constrain text cursor
 - show most used blocks in the inserter (note that this preference is not used in the site editor today)
 - block visibility (same this one is not available in the site editor today but I don't see any reason why it shouldn't be)
 - default editor (code/visual)

I'm going to be working on several PRs to unify these. first one is in #57468

**Comment by talldan** [comment]
> There's a number of preference that IMO should be shared between both editors

@youknowriad I think this is really good idea.

One way to do it would be migrating the preferences. This folder contains the current migrations:
https://github.com/WordPress/gutenberg/tree/trunk/packages/preferences-persistence/src/migrations

The `legacy-local-storage-data` folder has all the migrations from the old preferences system, and the `preferences-package-data` folder has any migrations for the new preferences system, which is where code could be written for this migration. May need to think about what to do when a user has conflicting preferences (i.e. top toolbar enabled in one editor, but unset or turned off in another).

It might also be good to notify users about the change in the modal, like adding a short pointer/notice.

Feel free to ping me for reviews/assistance.

**Comment by youknowriad** [comment]
@talldan I think at the moment, I'm going to keep the core/edit-post preferences and use them in both to avoid migrations entirely. We have a precedent of using these in editor package.

**Comment by t-hamano** [comment]
Can this issue also be applied to the Widget Editor and Customize Widget editor? I submitted #57660 to unify `DocumentTools` components.

**Comment by fabiankaegy** [comment]
Hey all 👋 

I just tested the "Preview template" option the the post editor and freaking love it!!! This is such a valuable addition that is making editing content so much nicer. Thank for for adding it. 

Something I would love to add is a setting in either the editor preference, or in some global config where I could change the default to always show the preview by default. 

Currently, my workflow here is that every time I am opening a post I need to click the option again because I always want to use this mode. Ideally I would love it if the editor could remember my preference.

_Edit: I also added a new issue for this: #58038_

---

Another thing I notices is that I am only able to select which template I want to use if I am an Administrator. Any other user roles is not able to switch between the available templates. (This is a regression and I created #58037 for it). Additionally I would like to also be able to preview the template if I am not an administrator.

![CleanShot 2024-01-20 at 14 00 15@2x](https://github.com/WordPress/gutenberg/assets/20684594/0dc888bd-32e1-4875-8e89-fc07c0435e5d)

Ideally, the template preview would be especially useful for lower user roles such as authors & editors so that they can see what their page is going to look like.

**Comment by youknowriad** [comment]
@fabiankaegy Great idea, I always thought that this should be a CPT config. Would you mind creating a dedicated issue for it

**Comment by fabiankaegy** [comment]
Now that we are past the Beta 1 cut off point I'm removing this tracking issue from the 6.5 Project board. From now on the board should only contain individual bugs that we want to still fix before 6.5 gets released.

**Comment by richtabor** [comment]
> Make pages trash-able in the full screen editor.

Is the idea to have the red "Move to trash" button on both? 

Site editor: 
![CleanShot 2024-04-24 at 17 14 53](https://github.com/WordPress/gutenberg/assets/1813435/67560f84-bf2d-42c1-9efd-bd7bf4cf04be)

Post editor: 
![CleanShot 2024-04-24 at 17 15 47](https://github.com/WordPress/gutenberg/assets/1813435/03f8fdaa-aa51-4ad0-9447-e8da40905320)

**Comment by youknowriad** [comment]
The idea for me is to have the same thing, what's that "thing" is up to you and the rest of the designers :P

**Comment by jameskoster** [comment]
The big red button in the post editor is perhaps a bit too prominent. It will likely be removed in favor of the menu item as a part of https://github.com/WordPress/gutenberg/issues/59689.

**Comment by youknowriad** [comment]
I think with the `Editor` component introduced in #62274 and expanded into the post editor in #62339 we can consider this project complete. There are some small things that we can still improve/unify but the biggest part is done. Both post and site editor are using the same code and same UI for all post types.
