### ISSUE TITLE
Components: Remove usage of Reakit

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#53278]
## What problem does this address?

[Reakit](https://reakit.io/) does not explicitly support React 18, so it is causing peer dependency warnings.

Reakit has already been succeeded by [Ariakit](https://ariakit.org/), so it will not receive any more updates.

## What is your proposed solution?

Replace Reakit usage with Ariakit, or possibly other libraries like Radix UI.

### Components remaining

Make sure we have sufficient test coverage of the existing components before we start a migration.

- [x] Composite @andrewhayward
  - [x] https://github.com/WordPress/gutenberg/pull/54225
  - [x] https://github.com/WordPress/gutenberg/issues/55224
  - [x] https://github.com/WordPress/gutenberg/issues/56548
- [x] Disclosure @flootr #55639
- [x] Divider @flootr #55622
- [x] RadioGroup (already deprecated — need to decide how to proceed) #55580
- [x] ToggleGroupControl https://github.com/WordPress/gutenberg/pull/50278
- [x] Tooltip #48440
