### ISSUE TITLE
Search block: Use the interactivity API to handle client side logic

### ISSUE THREAD

**Issue by cbravobernal** [WordPress/gutenberg#53292]
## What problem does this address?

#51207 added a check-list with the task of moving the Search Block client side logic to use the Interactivity API.
Now that API is integrated in File and Navigation block, so moving all the client side logic to a similar approach will improve the project's code consistency.

## What is your proposed solution?

Explore using [the Interactivity API](https://make.wordpress.org/core/2023/03/30/proposal-the-interactivity-api-a-better-developer-experience-in-building-interactive-blocks/) for the Search block.

## Todos
- [x] Use Interactivity API for frontend interaction
- [x] Add on-click on search button to toggle class if search input is closed
- [x] Submit the form is the search input is opened, apply the validation.  
- [ ] Add on-click listener in body html tag to toggle class if search input is opened. 
- [x] Set button type, ariaHidden, tabIndex, ariaExpanded, ariaLabels on expand. See: https://github.com/WordPress/gutenberg/blob/8093bb03c23116115baa2ebdea61d00e8a685590/packages/block-library/src/search/view.js#L93)
- [ ] Set button type, ariaHidden, tabIndex, ariaExpanded, ariaLabels on collapse.
- [ ] Fix initial form bad state due to directive processing order of tags. @luisherranz @DAreRodz 
- [ ] Add on keys listeners. See: https://github.com/WordPress/gutenberg/blob/8093bb03c23116115baa2ebdea61d00e8a685590/packages/block-library/src/search/view.js#L104

**Comment by SantosGuillamot** [comment]
I've been taking a look at this issue this morning, and I wanted to share my findings. Please double-check because I might be missing something.

## How it works

First of all, the search block only has interactivity when the "Button only" option is activated:

![Screenshot 2023-08-07 at 13 00 04](https://github.com/WordPress/gutenberg/assets/34552881/8c49cb58-1aff-43c8-baae-fc187e319f87)

When that setting is enabled, the search block only shows a button, and the input is shown only after the button is clicked:


https://github.com/WordPress/gutenberg/assets/34552881/938d8f9e-2e95-463f-b981-62a22a405a77

## Interactivity

I believe the use cases we need to handle are basically:

* Change HTML attributes depending on if the input is open or not.
* Logic to open/close the input when appropriate.

For reference, the HTML structure of the search block is somehting like this:

```html
<form>
    <label></label>
    <div>
        <input></input>
        <button></button>
    </div>
</form>
```

### Status = close

When the input is not open, and only the button is shown:

#### HTML Changes

* The `FORM` element has the class `wp-block-search__searchfield-hidden`.
* The `INPUT` element has `aria-hidden="true"`.
* The `INPUT` element has `tabinfex="-1"`.
* The `BUTTON` element has `aria-expanded="false"`.
* The `BUTTON` element has `aria-label="Expand search field"`.
* The `BUTTON` element has `type="button"`.
* The `BUTTON` elements has `aria-controls="_search_input_id_"`.

#### Logic needed

* Clicking (or Enter) the button should show the input field (change the status to open), and focus on the input HTML element.

### Status = open

When the input is open:

#### HTML Changes

* The `FORM` element REMOVES the class `wp-block-search__searchfield-hidden`.
* The `INPUT` element has `aria-hidden="false"`.
* The `INPUT` element has `tabinfex="0"`.
* The `BUTTON` element has `aria-expanded="true"`.
* The `BUTTON` element has `aria-label="Submit Search"`.
* The `BUTTON` element has `type="submit"`.
* The `BUTTON` elements REMOVES `aria-controls` attribute.

#### Logic needed

* Focusing out the search form, by clicking or tabbing, should close the input.
* The ESC key should close the input and focus on the form button.

---
For the HTML changes, I believe all of them can be achieved by using a combination of `data-wp-bind` and selectors. For the `aria-label` attribute, we might need to use `wp_store` in PHP to define those values. I assume they should support APIs like translations.

For the logic, I believe we can get the desired results using `data-wp-on--click`, `data-wp-on--focusout`, or `data-wp-on--keywdown`.

I believe most of the cases are similar to the work done in the [Navigation block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/view-interactivity.js), in case that's helpful.

Apart from that, once the implementation is ready, it'd be great to ping someone with accessibility knowledge to ensure the current search block is accessible and make any improvements if necessary.

**Comment by figureone** [comment]
> Apart from that, once the implementation is ready, it'd be great to ping someone with accessibility knowledge to ensure the current search block is accessible and make any improvements if necessary.

We actually got flagged by the Siteimprove accessibility checker when using the Search block, see screenshot:

<img width="948" height="795" alt="Image" src="https://github.com/user-attachments/assets/5f864e1b-2bfa-4fd2-890d-f4b2c6ed47d8" />


This is in line with the documentation for `aria-hidden` which do mention you should not use it on an `input` element:
> **Warning:** Do not use `aria-hidden="true"` on focusable elements.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-hidden

I think perhaps the `hidden` attribute should be wired up with the Interactivity API instead of `aria-hidden`? This makes sense since the element is also visually hidden when not toggled open, so we don't need to hide it from just screen readers.

Let me know if I can provide more info, or open a trac ticket or github issue! Cheers

**Comment by cbravobernal** [comment]
> Let me know if I can provide more info, or open a trac ticket or github issue! Cheers

Thanks for the report! The best option is to open a Github issue here in Gutenberg.

**Comment by figureone** [comment]
Thanks @cbravobernal! You know, I got halfway through a pull request before I stepped back and realized this may be a false positive from our accessibility checker. The current Search block code sets `tabindex="-1"` when `aria-hidden="true"`, which should satisfy the "Do not use aria-hidden="true" on focusable elements" criteria (since `tabindex="-1"` prevents it from being focusable).
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/tabindex

I'm pasting my fix below just in case this issue comes up again in the future. Note that there is a style tweak in there (if theme authors set a custom line-height on the search block via theme.json `styles.blocks.core/search.typography.lineHeight`, the search icon will jump vertically when the input is revealed). Setting `align-items: center` will vertically center the search icon, making it consistent at any line-height of the parent.

```diff
diff --git a/packages/block-library/src/search/index.php b/packages/block-library/src/search/index.php
index 7073d6ce8a..1abc07f76e 100644
--- a/packages/block-library/src/search/index.php
+++ b/packages/block-library/src/search/index.php
@@ -80,13 +80,11 @@ function render_block_core_search( $attributes ) {
        if ( $is_expandable_searchfield ) {
            wp_enqueue_script_module( '@wordpress/block-library/search/view' );
 
-           $input->set_attribute( 'data-wp-bind--aria-hidden', '!context.isSearchInputVisible' );
-           $input->set_attribute( 'data-wp-bind--tabindex', 'state.tabindex' );
+           $input->set_attribute( 'data-wp-bind--hidden', '!context.isSearchInputVisible' );
 
            // Adding these attributes manually is needed until the Interactivity API
            // SSR logic is added to core.
-           $input->set_attribute( 'aria-hidden', 'true' );
-           $input->set_attribute( 'tabindex', '-1' );
+           $input->set_attribute( 'hidden', true );
        }
    }
 
diff --git a/packages/block-library/src/search/style.scss b/packages/block-library/src/search/style.scss
index a6a5c40f29..ab40b98455 100644
--- a/packages/block-library/src/search/style.scss
+++ b/packages/block-library/src/search/style.scss
@@ -50,6 +50,7 @@ $button-spacing-y: math.div($grid-unit-15, 2); // 6px
        box-sizing: border-box;
        display: flex;
        justify-content: center;
+       align-items: center;
    }
 
    .wp-block-search__inside-wrapper {
diff --git a/packages/block-library/src/search/view.js b/packages/block-library/src/search/view.js
index 46eb3ec4b1..56d72405ab 100644
--- a/packages/block-library/src/search/view.js
+++ b/packages/block-library/src/search/view.js
@@ -42,6 +42,10 @@ const { actions } = store(
                if ( ! ctx.isSearchInputVisible ) {
                    event.preventDefault();
                    ctx.isSearchInputVisible = true;
+                   // Although hidden is bound to !isSearchInputVisible, we must manually
+                   // set it here before focusing since context isn't immediately updated
+                   // and we can't focus a hidden element.
+                   ref.parentElement.querySelector( 'input' ).hidden = false;
                    ref.parentElement.querySelector( 'input' ).focus();
                }
            } ),
```
