### ISSUE TITLE
Documentation for the Interactivity API - Tracking Issue

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#53296]
Interactivity API is [a proposal](https://make.wordpress.org/core/2023/03/30/proposal-the-interactivity-api-a-better-developer-experience-in-building-interactive-blocks/) for a new standard to create interactive blocks. It's still in an [experimental phase](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity/README.md) and is [available with Gutenberg 16.2 or later](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity/docs/1-getting-started.md#requirements-of-the-interactivity-api)

This tracking issue compiles all issues related to the documentation of the Interactivity API to keep track of the pending tasks and to ease the coordination of this work.

Interactivity API Docs are currently being created as Markdown files in the [`/docs` folder of the `interactivity` package ](https://github.com/WordPress/gutenberg/tree/trunk/packages/interactivity/docs). When the Interactivity API is no longer in an experimental phase or is integrated into WordPress Core, the plan is to move this documentation to the [Block Editor HandBook](https://developer.wordpress.org/block-editor/)

If you are willing to help with the documentation, please add a comment to   https://github.com/WordPress/gutenberg/discussions/51928, and we'll coordinate everyone's efforts.

## Tasks

Tasks related to Interactivity API Docs are labelled with [`[Feature] Interactivity API]` & `[Type] Developer Documentation]`](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Interactivity+API%22+label%3A%22%5BType%5D+Developer+Documentation%22)

- [x] https://github.com/WordPress/gutenberg/issues/63672
- [x] https://github.com/WordPress/gutenberg/issues/63570
- [ ] https://github.com/WordPress/gutenberg/issues/62922
- [ ] https://github.com/WordPress/gutenberg/issues/62921
- [ ] https://github.com/WordPress/gutenberg/issues/62920
- [ ] https://github.com/WordPress/gutenberg/issues/62872
- [x] https://github.com/WordPress/gutenberg/issues/62055
- [x] https://github.com/WordPress/gutenberg/issues/60783
- [x] https://github.com/WordPress/gutenberg/issues/60781
- [ ] https://github.com/WordPress/gutenberg/issues/56638 
- [x] https://github.com/WordPress/gutenberg/issues/56641
- [x] https://github.com/WordPress/gutenberg/issues/56640
- [x] https://github.com/WordPress/gutenberg/issues/52922
- [x] https://github.com/WordPress/gutenberg/issues/52929
- [x] #53384
- [x] #53386

**Comment by juanmaguitar** [comment]
The following new issues related to Interactivity API documentation have been created
- [ ] https://github.com/WordPress/gutenberg/issues/56638
- [x] https://github.com/WordPress/gutenberg/issues/56639
- [x] https://github.com/WordPress/gutenberg/issues/56641
- [x] https://github.com/WordPress/gutenberg/issues/56640

They're also part of https://github.com/WordPress/gutenberg/issues/53740

**Comment by luisherranz** [comment]
This is the list of APIs that in my opinion would cover the whole spectrum of what the Interactivity API encompasses:

It would be great to review it and start adding the missing items so this is ready before the WP 6.5 Release Candidate 1.

## Reference API

- Blocks
  - [x] `supports.interactivity`
  - [x] `supports.interactivity.clientNavigation`
- Directives
  - Framework
    - `data-wp-interactive`
    - `data-wp-ignore`
    - `data-wp-key`
  - State
    - `data-wp-context`
  - Attributes
    - `data-wp-bind--{attribute}`
    - `data-wp-class--{className}`
    - `data-wp-style--{styleProperty}`
  - Inner content
    - `data-wp-text`
  - Event listeners
    - `data-wp-on--{event}`
    - `data-wp-on-window--{event}`
    - `data-wp-on-window--{event}`
  - Side effects
    - `data-wp-init`
    - `data-wp-watch`
    - `data-wp-run`
      - Hooks
        - `useInit()`
        - `useWatch()`
        - `useEffect()`
        - `useLayoutEffect()`
        - `useCallback()`
        - `useMemo()`
        - `useState()`
        - `useRef()`
  - Templating
    - `data-wp-each`
      - `data-wp-each-child`
- Store
  - Client
    - `store()`
    - `getContext()`
    - `getElement()`
    - `getConfig()`
    - `withScope()`
  - Server
    - `wp_interactivity_state()`
    - `wp_interactivity_config()`
  - Private and read-only stores
- Router
  - Store - `core/router`
    - `state.url`
    - `actions.navigate()`
    - `actions.prefetch()`
  - Directives
    - `data-wp-router-region`

---

The Core Concepts guides are optional and could be released after WP 6.5, but they would be a good addition to understanding the mental model behind the Interactivity API.

## Core Concepts

- Namespaces
- State
  - Local, global, derived state
  - Server state -> Client state
- Server directive processing
- Declarative vs imperative code (don't mutate the DOM manually!)
- Client-side navigation

---

The readmes should be updated to point to the official documentation, the getting started guide and the [Interactivity API discussions](https://github.com/WordPress/gutenberg/discussions/categories/interactivity-api) for questions.

## Readmes

- `@wordpress/interactivity` package
- `@wordpress/interactivity-router` package

**Comment by juanmaguitar** [comment]
The following new issues related to Interactivity API documentation have been created

- https://github.com/WordPress/gutenberg/issues/60781
- https://github.com/WordPress/gutenberg/issues/60783

**Comment by karstengresch** [comment]
As a dev user, I'd love to see a full CRUD example (with dynamic form submission) walkthrough, such as https://learn.wordpress.org/course/using-the-wordpress-data-layer/ b.t.w. :)

**Comment by juanmaguitar** [comment]
Interactivity API Docs are now available from [Block Editor Handbook > Reference Guides > Interactivity API Reference](https://developer.wordpress.org/block-editor/reference-guides/interactivity-api/)

**Comment by juanmaguitar** [comment]
I have opened https://github.com/WordPress/gutenberg/issues/62055 to review and update the `README` of the `@wordpress/interactivity-router` package

**Comment by WPLake** [comment]
@juanmaguitar The current format of the Interactivity API Docs is well-suited for developers with some experience in Gutenberg blocks. However, it lacks basic explanations and a separate guide on how to apply this outside of Gutenberg. We've posted a [detailed explanation in our blog](https://wplake.org/blog/wordpress-interactivity-api/) that aims to fill the gaps. Wouldn't it be useful to mention this article in the [Docs & Examples](https://developer.wordpress.org/block-editor/reference-guides/interactivity-api/#docs-examples) section?

**Comment by juanmaguitar** [comment]
Wow! [That post](https://wplake.org/blog/wordpress-interactivity-api/) is great! Congratulations @WPLake 🙌

WordPress Docs does have a [external linking policy](https://make.wordpress.org/docs/tag/external-linking-policy/) that doesn't allow to link resources outside of wordpress.org (with some exceptions), but I would love that some of the explanations and ideas that are covered in your article are also included in the official docs. 

Would you like to help shape and improve the official docs? 
If so, the best next step would be opening an issue detailing the specific improvements you'd like to see in the docs.
I'd also be happy to connect via Make WordPress Slack (`@JuanMa`) to discuss any other ways to collaborate to improve the iAPI docs.

**Comment by juanmaguitar** [comment]
After a conversation with @luisherranz at WCEU about improving the Interactivity API Docs, I've created the following issues that reflect some of the suggested changes we discussed:
- https://github.com/WordPress/gutenberg/issues/62922
- https://github.com/WordPress/gutenberg/issues/62921
- https://github.com/WordPress/gutenberg/issues/62920
- https://github.com/WordPress/gutenberg/issues/62872

_Note: They have also been added to the description of this issue_

**Comment by WPLake** [comment]
@juanmaguitar I'm also open to collaboration on the iAPI Docs. I wrote you in Slack DM (@JuanMa from WPLake) on 18th June. Should we rather chat by email?

**Comment by juanmaguitar** [comment]
@WPLake, I apologize for the delay in getting back to you. 
I've been intensely focused lately on the [Docs Squad work for WP 6.6 release](https://make.wordpress.org/core/2024/06/25/wordpress-6-6-field-guide/) 😅
I actually had my response in draft form, but I wanted to provide some background GitHub issues to frame our conversation. I finally completed that today, so I'm happy to continue the discussion via Slack. I'll ping you there today.

**Comment by juanmaguitar** [comment]
The issue https://github.com/WordPress/gutenberg/issues/63570 has been created and added to the list in the description of this issue

**Comment by luisherranz** [comment]
I've created and added this issue to the list:

- https://github.com/WordPress/gutenberg/issues/63672

**Comment by DAreRodz** [comment]
👋 @juanmaguitar, I'm revisiting this issue.

From the issues that appear in the description, I closed #62055 as completed.

Regarding #56638, not sure if it still applies; I think it could be closed. It seems like most of the related docs are already present in the iAPI router's [README.md](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity-router/README.md) file. I guess we can expand on client-side navigation as part of #62921 in a new document under the `/docs/reference-guides/interactivity-api/` folder. 🤔

And regarding #62920, do you still think it is required? It would involve changing the overall structure of the documentation. Maybe it is not worth it to go for that change.

**Comment by DAreRodz** [comment]
@juanmaguitar, forgot to mention, I created the following PR for https://github.com/WordPress/gutenberg/issues/61207:

- https://github.com/WordPress/gutenberg/pull/74974

The issue is not listed above, though I thought it was still relevant. Let me know if that's not the case.

**Comment by DAreRodz** [comment]
@juanmaguitar, I created this PR to fix a typo in one of the iAPI guides' file names, just so you are aware:

- https://github.com/WordPress/gutenberg/pull/75480

**Comment by DAreRodz** [comment]
The previously mentioned PR was superseded by https://github.com/WordPress/gutenberg/pull/75357. I approved it and it's ready to be merged.

- https://github.com/WordPress/gutenberg/pull/75357
