### ISSUE TITLE
Tracking: Writing Experience

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#53305]
Writing in WordPress, whether a latest post or new page, needs to be seamless and enjoyable–the tooling should aid creativity rather than get in the way. Blocks with all of their variations, design tools, and transforms should make you feel empowered. Let’s focus on continuing to polish this experience. If you have items you’d like to have considered, comments are strongly encouraged. What’s shared here is meant to be a step forward rather than wholly comprehensive. Expect iterations and updates as the weeks go on. 

**Enhancing writing flow**

- [x] https://github.com/WordPress/gutenberg/issues/44055
- [x] https://github.com/WordPress/gutenberg/issues/52774
- [x] https://github.com/WordPress/gutenberg/issues/48747
- [x] https://github.com/WordPress/gutenberg/pull/53306
- [x] https://github.com/WordPress/gutenberg/issues/53197
- [x] https://github.com/WordPress/gutenberg/issues/44755
- [x] #53333
- [x] https://github.com/WordPress/gutenberg/issues/45436
- [x] https://github.com/WordPress/gutenberg/pull/48708
- [x] #53346
- [x] https://github.com/WordPress/gutenberg/issues/46039
- [x] https://github.com/WordPress/gutenberg/issues/52773
- [x] https://github.com/WordPress/gutenberg/issues/16436
- [x] https://github.com/WordPress/gutenberg/issues/53353
- [x] https://github.com/WordPress/gutenberg/issues/55177
- [x] https://github.com/WordPress/gutenberg/issues/45404
- [x] https://github.com/WordPress/gutenberg/issues/51554
- [x] https://github.com/WordPress/gutenberg/issues/47767
- [x] https://github.com/WordPress/gutenberg/issues/55474
- [ ] 🚧 https://github.com/WordPress/gutenberg/issues/40979
- [ ] #21558
- [ ] https://github.com/WordPress/gutenberg/issues/27221
- [ ] https://github.com/WordPress/gutenberg/issues/53128
- [ ] https://github.com/WordPress/gutenberg/issues/44753
- [ ] https://github.com/WordPress/gutenberg/issues/52745
- [ ] https://github.com/WordPress/gutenberg/issues/53674
- [x] #55757
- [x] #56223
- [x] #60025
- [x] #51047
- [ ] ❓ https://github.com/WordPress/gutenberg/issues/53195

**Improving pasting**

- [x] https://github.com/WordPress/gutenberg/issues/46832
- [x] https://github.com/WordPress/gutenberg/issues/24895
- [x] https://github.com/WordPress/gutenberg/issues/54261
- [ ] 🚧 https://github.com/WordPress/gutenberg/issues/45774
- [x] 🚧 https://github.com/WordPress/gutenberg/issues/53076
- [ ] 🚧 https://github.com/WordPress/gutenberg/issues/42570
- [ ] #48040
- [x] #33312
- [ ] #52743
- [ ] #32917

**Add E2E tests**

- [ ] https://github.com/WordPress/gutenberg/issues/53774#issuecomment-1862950888

**Legend**

- 🚧: Has PR, work-in-progress
- ℹ️: Needs more information
- ❓: Needs decision

**Comment by ellatrix** [comment]
I'm going to tick items when there's a solution but still needs approval.

**Comment by alexstine** [comment]
@annezazu Just added this one to your list: https://github.com/WordPress/gutenberg/issues/47767.

This is a serious bug that apparently we only fixed on Windows due to the lack of testing by me on Mac. Need to fix this regression for all screen readers. Really sad I missed this.

**Comment by fabiankaegy** [comment]
@annezazu thanks for creating this tracking issue :)

I think https://github.com/WordPress/gutenberg/issues/52018 may be a good addition

**Comment by annezazu** [comment]
@fabiankaegy that seems a bit outside of the base writing experience. I'm going to leave it out for now but I do think it's worth addressing.

**Comment by fabiankaegy** [comment]
@annezazu no worries if you feel it shouldn't be tracked here. The reason I mentioned it for writing experience is because the writing experience when you are within a content only locked context for the list isn't great since new list items cannot be added :) but I can see how it is outside the scope of what is tracked here

**Comment by colorful-tones** [comment]
It looks like #53197 got closed as a duplicate of #27221. Perhaps we can consider replacing it in the list above please @annezazu ?

**Comment by annezazu** [comment]
Yes! Adding in. Thanks for pointing out.

**Comment by getdave** [comment]
Noticing that there are a lot of items in the todo here. Could it be helpful to get a sense of what we might be targeting for 6.6, or perhaps a level of prioritisation to aid contributors in determining what to work on?

At first glance these seem pretty important:

- https://github.com/WordPress/gutenberg/issues/48040
- https://github.com/WordPress/gutenberg/issues/53774
- https://github.com/WordPress/gutenberg/issues/52743
- https://github.com/WordPress/gutenberg/issues/40979
- https://github.com/WordPress/gutenberg/issues/44753
- https://github.com/WordPress/gutenberg/issues/56223

...

**Comment by colorful-tones** [comment]
Hi folks,
We are only one week away from the Beta 1 cut-off date for [WordPress 6.6](https://make.wordpress.org/core/6-6/). This issue hasn’t seen any movement in a while, so we (the editor triage leads of the 6.6 release) have decided to remove it from the [WordPress 6.6 Editor Tasks project board](https://github.com/orgs/WordPress/projects/179/views/1).

**Comment by ellatrix** [comment]
Let's close this in favour of a new issue for 6.7: #63255
