### ISSUE TITLE
Custom CSS Enhancements

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#53326]
This is a simple tracking issue to help bring together different issues around the Global Styles Custom CSS feature

- [ ] https://github.com/WordPress/gutenberg/issues/47946
- [ ] https://github.com/WordPress/gutenberg/issues/50761
- [ ] https://github.com/WordPress/gutenberg/issues/47945
- [ ] https://github.com/WordPress/gutenberg/issues/52644
- [ ] https://github.com/WordPress/gutenberg/issues/52304
- [x] https://github.com/WordPress/gutenberg/issues/52217 - related https://github.com/WordPress/gutenberg/issues/48439
- [ ] https://github.com/WordPress/gutenberg/issues/50160
- [ ] https://github.com/WordPress/gutenberg/issues/49970
- [ ] https://github.com/WordPress/gutenberg/issues/47862
- [ ] https://github.com/WordPress/gutenberg/issues/47433

**Comment by carolinan** [comment]
[Block styles: add block instance custom CSS #56127](https://github.com/WordPress/gutenberg/issues/56127)

**Comment by westonruter** [comment]
Custom CSS should allow for media queries, cf. https://github.com/WordPress/gutenberg/issues/48989
