### ISSUE TITLE
Design Tools: Expand styling options for container blocks

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#53720]
Part of: https://github.com/WordPress/gutenberg/issues/40318

This is a tracking issue to detail efforts towards implementing a subset of the [section-specific theme.json](https://github.com/WordPress/gutenberg/issues/40318) functionality.

## Todo

- [x] Add further element color options to container blocks e.g. buttons & headings
    - https://github.com/WordPress/gutenberg/pull/53667
    - Draft PR above explores implementing button and heading element colors by following how link colors work.
- [ ] Allow elements within container blocks to also have typographic styles applied
- [x] Explore implementing mechanism to generate per block-type styles scoped by container block instance
- [x] Investigate how we allow defining block type styles for a section i.e. through the UI
    - Is a whole UI required e.g. the "Blocks" screen in Global Styles?

**Comment by talldan** [comment]
@aaronrobertshaw Is this issue still relevant? It doesn't seem to have been updated for a while, but has been added to 'Top of mind' and '6.5 Editor Tasks' projects.

**Comment by aaronrobertshaw** [comment]
I believe this has been superseded by the recent [section styling](https://github.com/WordPress/gutenberg/issues/40318), [colorways, typesets](https://github.com/WordPress/gutenberg/issues/48581), and extended block style variations [issues](https://github.com/WordPress/gutenberg/issues/56632) and [explorations](https://github.com/WordPress/gutenberg/pull/56540).

The outstanding "Allow elements within container blocks to also have typographic styles applied" task could be considered completed as well when https://github.com/WordPress/gutenberg/pull/56540 lands.

I think we can close this issue now. I'm also in the process of writing up an issue that should bring together the above concepts and related issues .

**Comment by aaronrobertshaw** [comment]
New issue attempting to bring everything together can be found at: https://github.com/WordPress/gutenberg/issues/57537
