### ISSUE TITLE
Command Palette: Block commands that do not work on the selected block are displayed

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53921]
### Description

Related to #52509

By #52509, commands related to blocks were added. However, you will see commands that are not expected to be used with the selected block.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/5fef782a-fb06-4229-bf8d-531df2faf404

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ntsekouras** [comment]
Thanks for the issue. I'll open a PR about the `grouping` commands soon.

**Comment by t-hamano** [comment]
Thank you for bringing this issue to your attention. From my new research, it seems that all block commands need to be given some sort of condition.

- [x] Ungroup / Group : Should check if the block is groupable or ungroupable; the [useConvertToGroupButtonProps](https://github.com/WordPress/gutenberg/blob/a9252ece268e0a458016d65d302440c46db9b044/packages/block-editor/src/components/convert-to-group-buttons/use-convert-to-group-button-props.js#L33) hook may be reusable. #53988
- [x] Move to: Should not be displayed when there is only one block or when the move is locked #53994
- [x] Add after / Add before: When a default block cannot be inserted, it should not be displayed. For example, this is the case when the paragraph block is excluded by the `allowed_block_types_all hook`. #53994
- [x] Remove: Should not be displayed when `canRemoveBlocks` is false. #53994
- [x] Duplicate: Should not be displayed when the block [cannot be duplicated](https://github.com/WordPress/gutenberg/blob/a9252ece268e0a458016d65d302440c46db9b044/packages/block-editor/src/components/list-view/block-select-button.js#L165-L173). #53994
