### ISSUE TITLE
[Tracking] Font Library. Stage 3: UI, UX and performance improvements

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#53926]
[Tracking] **[Font Library](https://github.com/WordPress/gutenberg/issues/54169)**
**Stage 3: Performance optimization**

## What needs to be done:
- [ ] https://github.com/WordPress/gutenberg/issues/54527
- [ ] https://github.com/WordPress/gutenberg/issues/54226
- [ ] https://github.com/WordPress/gutenberg/issues/54399
- [ ] https://github.com/WordPress/gutenberg/issues/54401
- [ ] https://github.com/WordPress/gutenberg/issues/54431
- [ ] https://github.com/WordPress/gutenberg/issues/54506
- [ ] https://github.com/WordPress/gutenberg/issues/54528
- [ ] https://github.com/WordPress/gutenberg/issues/51151
- [ ] https://github.com/WordPress/gutenberg/issues/54688
- [ ] https://github.com/WordPress/gutenberg/issues/54698
- [ ] https://github.com/WordPress/gutenberg/issues/54797
- [ ] https://github.com/WordPress/gutenberg/issues/54779
- [ ] Performance optimization

## Needs discussion:
- https://github.com/WordPress/gutenberg/issues/54222 
- https://github.com/WordPress/gutenberg/issues/54671
- https://github.com/WordPress/gutenberg/issues/54826

## In Progress
- [ ] https://github.com/WordPress/gutenberg/pull/54477

## Links
Stage 1: https://github.com/WordPress/gutenberg/issues/52698
Stage 2: https://github.com/WordPress/gutenberg/issues/53307

**Comment by annezazu** [comment]
Noting this for @WordPress/performance awareness!

**Comment by matiasbenedetto** [comment]
I'm closing this issue because this stage was part of the plan to make the font library ready to merge in WordPress core 6.4, but since it was [punted to 6.5](https://wordpress.slack.com/archives/C02RQBWTW/p1696525101347939), we should focus on making it ready for 6.5. This is the new tracking issue: https://github.com/WordPress/gutenberg/issues/55277
