### ISSUE TITLE
[Tracking] Command Palette: Turn off DFM mode when a command not suitable for DFM mode is executed

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#53993]
## What problem does this address?

The problem was discovered from [this comment](https://github.com/WordPress/gutenberg/pull/53983#issuecomment-1695662100)

Many commands do not take into account whether or not you are currently in DFM mode. As a result, unintended commands may be executed in DFM mode, causing layout corruption, etc.

## What is your proposed solution?

~~As far as I could find out, at least the following commands should not be displayed in DFM mode.~~

Update: It seems better to leave these commands in place and remove DFM mode when they are executed.

### Post Editor

- [x] Toggle block inspector
- [x] Toggle settings inspector
- [x] Toggle list view
- [x] Toggle top toolbar
- [x] Toggle code editor / Exit code editor: This can be toggled from the options menu, but I think that it would be better to force visual editor mode in DFM mode and disable the switch to the code editor.
- [ ] Hide block breadcrumbs / Show block breadcrumbs: The breadcrumb is not always displayed in DFM mode. Is this command necessary?

### Site Editor

- [x] Toggle block inspector #54030
- [x] Toggle settings inspector #54030
- [x] Toggle list view #54030
- [x] Toggle top toolbar #54030
- [x] Toggle code editor / Exit code editor: This can be toggled from the options menu, but I think that it would be better to force visual editor mode in DFM mode and disable the switch to the code editor. #54030
- [ ] Hide block breadcrumbs / Show block breadcrumbs: The breadcrumb is not always displayed in DFM mode. Is this command necessary?
- [x] Open styles: This can be toggled from the options menu, but I think it should be non-switchable. #54030
- [x] Learn about styles: The welcome guide being displayed is not a problem in itself, but the style sidebar being displayed at the same time is a problem. #54030
- [ ] Reset styles to defaults: Is this action necessary even though global styles cannot be manipulated in DFM mode?
- [x] Customize CSS: I think this is unnecessary since it would open the Styles sidebar. #54030
- [x] Style revisions: I think this is unnecessary since it would open the Styles sidebar. #54030

**Comment by richtabor** [comment]
Are you thinking of a way to omit from DFM (maybe an allowed list?), or adding a check in each command? The latter would be tough to mitigate as we continue adding commands.

**Comment by t-hamano** [comment]
> Are you thinking of a way to omit from DFM (maybe an allowed list?), or adding a check in each command? The latter would be tough to mitigate as we continue adding commands.

Not only in DFM mode, I think various conditions must be checked to see if the command is displayed. Therefore, I think we have to take the latter approach. The following recently submitted PRs are examples.

- #53994
- #53988

**Comment by ntsekouras** [comment]
>As far as I could find out, at least the following commands should not be displayed in DFM mode.

Should we hide these commands in DFM mode or just disable the mode? 🤔 Any thoughts @draganescu ?

**Comment by draganescu** [comment]
So far we littered the codebase with code that disables DFM when the UI is no longer conforming to DFM mode. 

As an UX I think so far it's the right path. As an implementation it's hard to discern if at the root is better (less flexible but prevents these UI  bugs once and for all) or at the consumer (it's a few more lines to always toggle DFM off).

I think as far as UX goes we should leave the commands there and just turn off DFM for everything that causes UI bugs mostly because we want [to improve DFM](https://github.com/WordPress/gutenberg/pull/53407) to a level where it won't have to be turned off anymore.

**Comment by t-hamano** [comment]
Thanks for the advice, @draganescu ! I have changed the title of the issue.

BTW, #52522 has also been reported that the Settings/Styles panel is unintentionally displayed in DFM mode.

**Comment by ntsekouras** [comment]
I'll have a PR soon that handles most of the cases.

**Comment by ntsekouras** [comment]
`Reset styles to defaults` doesn't open a sidebar but the changes aren't saved and this might not be obvious. 

>Hide block breadcrumbs / Show block breadcrumbs: The breadcrumb is not always displayed in DFM mode. Is this command necessary?

I think breadcrumbs doesn't affect anything with DFM..

**Comment by t-hamano** [comment]
Thank you for addressing this issue, @ntsekouras!

Does this mean that this issue can be closed since DFM does not need to be considered for the following commands?

-  Hide block breadcrumbs / Show block breadcrumbs
- Reset styles to defaults

**Comment by ntsekouras** [comment]
I think we can close this now, yes.
