### ISSUE TITLE
Docs: Update the Getting Started section to provide a better developer experience

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#54124]
This issue tracks improvements to the [Getting Started](https://developer.wordpress.org/block-editor/getting-started/) section of the [Block Editor Handbook](https://developer.wordpress.org/block-editor/). 

Getting Started is arguably the most important section of the Handbook. It aims to provide an onramp for developers who are new to working with the Editor and/or blocks. Currently, the section contains very outdated information and needs to provide a better learning pathway.

The project will include rearranging existing docs, removing outdated content, updating everything, and adding new docs to illustrate the essential concept of block development. The resulting structure will look quite similar to what currently exists but with updated content and an improved flow. 

All content updates will also focus on referencing existing developer docs, Learn WordPress courses/material, and the WordPress Developer Blog articles for additional information. Let's cut down on content duplication as much as possible. 

## Section structure

Getting started
- Block Development environment
  - Node.js development environment
  - Get started with `wp-env`
  - Get started with `wp-scripts`
  - Get started with `create-block`
- Quick start guide
- Create a block tutorial
- Fundamentals of block development
  - Anatomy of a block
  - Static vs. dynamic blocks
  - _More docs can/should be added as needed (block.json, components, etc.)_
- Frequently asked questions
- Glossary

## Tasks

**Content to be moved or removed**
- [x] Move [Glossary](https://developer.wordpress.org/block-editor/explanations/glossary/) to Getting Started 
  - https://github.com/WordPress/gutenberg/pull/54120
- [x] Move [FAQ](https://developer.wordpress.org/block-editor/explanations/faq/) to Getting Started
  -  https://github.com/WordPress/gutenberg/pull/54117
- [x] Remove [Full Site Editing](https://developer.wordpress.org/block-editor/getting-started/full-site-editing/) and move any relevant information to other docs
  - https://github.com/WordPress/gutenberg/pull/54516
- [x] Remove [Outreach](https://developer.wordpress.org/block-editor/getting-started/outreach/) and move any relevant historical information to the [History](https://developer.wordpress.org/block-editor/explanations/history/) doc
  - https://github.com/WordPress/gutenberg/pull/54314
- [x] Remove [Create a Block Tutorial](https://developer.wordpress.org/block-editor/getting-started/create-block/) and all subpages (content will be repurposed/replaced with updated guide)
- [x] Remove [How to setup local WordPress environment on Ubuntu](https://developer.wordpress.org/block-editor/getting-started/devenv/docker-ubuntu/) and add this info to the new `wp-env` guide (see below)
  - https://github.com/WordPress/gutenberg/pull/54395

**Content to be updated**

- [ ] Update [Glossary](https://developer.wordpress.org/block-editor/explanations/glossary/)
- [ ] Update [FAQ](https://developer.wordpress.org/block-editor/explanations/faq/)
- [x] Update [Developer Environment ](https://developer.wordpress.org/block-editor/getting-started/devenv/)and break out the `wp-env` guide into a separate doc
  - https://github.com/WordPress/gutenberg/pull/54395
- [x] Update main [Getting Started](https://developer.wordpress.org/block-editor/getting-started/) doc to reflect the planned changes

**New content**
- [x] Add a dedicated doc for setting up a local dev environment with `wp-env` (subpage of Developer Environment)
  - https://github.com/WordPress/gutenberg/pull/54395
- [x] #54960
- [x] #54961
- [x] Add a new "Quick start guide" 
  -  https://github.com/WordPress/gutenberg/pull/56056
- [x] https://github.com/WordPress/gutenberg/issues/56305
- [ ] #56282

**Comment by juanmaguitar** [comment]
> Remove [Create a Block Tutorial](https://developer.wordpress.org/block-editor/getting-started/create-block/) and all subpages (content will be repurposed/replaced with updated guide)

This tutorial is linked from several articles (see https://richtabor.com/publish-blocks/ for example) so I would redirect this URL https://developer.wordpress.org/block-editor/getting-started/create-block/ to a page (or section within a page) that recommends tutorials or courses (within wordpress.org) to start with Block Development

**Comment by juanmaguitar** [comment]
This is the diagram we're using to organize how ideas should be distributed over the Getting Started Section (please, feel free to chime in and share your thoughts)
https://excalidraw.com/#room=8c538e461500a1fe8523,7pSlj3w0awiHsHxiWS6tCw

**Comment by juanmaguitar** [comment]
This is the diagram we're using to organize how do we think ideas should be distributed along this section (please, feel free to chime in and share your thoughts)
https://excalidraw.com/#room=8c538e461500a1fe8523,7pSlj3w0awiHsHxiWS6tCw

_PS: Right now the diagram only reflects the changes on the "Block Development Environment" section but it will be expanded with ideas on the whole Getting Started section_

![image](https://github.com/WordPress/gutenberg/assets/422576/095fb5b6-47a9-4cec-b98d-aa5c0e1f3e13)

**Comment by colorful-tones** [comment]
> This is the diagram we're using to organize how do we think ideas should be distributed along this section (please, feel free to chime in and share your thoughts)

@juanmaguitar, was this something we wanted more extensive WordPress community engagement around? I'm happy to share and amplify.

**Comment by juanmaguitar** [comment]
> @juanmaguitar, was this something we wanted more extensive WordPress community engagement around? I'm happy to share and amplify.

Hi @colorful-tones, more feedback is always welcome although this revamped getting started guide aims to address feedback shared during the last years at https://github.com/WordPress/gutenberg/issues/22151 as explained in https://github.com/WordPress/gutenberg/issues/55432

Issues are available for the different pages planned to improve the onboarding experience so feel free to chime in and share your ideas on them. PRs for these issues are coming so comments can also be made over these more specific content proposals.

We can also iterate on them once they're published.

**Comment by annezazu** [comment]
Is this still being worked on?

**Comment by ndiego** [comment]
Not actively. I'll close this out, and we can open new issues as needed.
