### ISSUE TITLE
Classic Block: Tracking Issue for Bugs and Enhancements

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#54265]
In an effort to conslidate issues for the most used Gutenberg blocks - this is a Tracking Issue for those related to the Classic Block.

## Bugs
- [ ] https://github.com/WordPress/gutenberg/issues/53698
- [ ] https://github.com/WordPress/gutenberg/issues/52132
- [ ] https://github.com/WordPress/gutenberg/issues/50358
- [ ] https://github.com/WordPress/gutenberg/issues/49008
- [ ] https://github.com/WordPress/gutenberg/issues/40676
- [ ] https://github.com/WordPress/gutenberg/issues/35049
- [ ] https://github.com/WordPress/gutenberg/issues/24173
- [ ] https://github.com/WordPress/gutenberg/issues/11211
- [ ] https://github.com/WordPress/gutenberg/issues/10837
- [ ] https://github.com/WordPress/gutenberg/issues/29742
- [ ] https://github.com/WordPress/gutenberg/issues/41432

## Enhancements 
- [ ] https://github.com/WordPress/gutenberg/issues/43889

**Comment by annezazu** [comment]
Closing this out, along with the other various issues you created for specific blocks since it replicates filtering we already have in GitHub. Thanks for the initial push to make this happen -- let's just keeping using the filters instead of needing to keep these individual issues up to date.
