### ISSUE TITLE
Cover Block: Tracking Issue for Bugs and Enhancements

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#54276]
In an effort to consolidate issues for the most used Gutenberg blocks - this is a Tracking Issue for those related to the Cover block that may provide high impact improvements.

## Bugs
- [ ] https://github.com/WordPress/gutenberg/issues/17582
- [ ] https://github.com/WordPress/gutenberg/issues/23198
- [ ] https://github.com/WordPress/gutenberg/issues/36549
- [ ] https://github.com/WordPress/gutenberg/issues/43092
- [ ] https://github.com/WordPress/gutenberg/issues/45353
- [ ] https://github.com/WordPress/gutenberg/issues/46789
- [x] https://github.com/WordPress/gutenberg/issues/50610
- [ ] https://github.com/WordPress/gutenberg/issues/50751
- [ ] https://github.com/WordPress/gutenberg/issues/52511
- [x] https://github.com/WordPress/gutenberg/issues/52835
- [ ] https://github.com/WordPress/gutenberg/issues/41989

## Enhancements
- [ ] https://github.com/WordPress/gutenberg/issues/53857
- [ ] https://github.com/WordPress/gutenberg/issues/38975
- [ ] https://github.com/WordPress/gutenberg/issues/39077
- [ ] https://github.com/WordPress/gutenberg/issues/41245
- [x] https://github.com/WordPress/gutenberg/issues/44167
- [ ] https://github.com/WordPress/gutenberg/issues/45560
- [ ] https://github.com/WordPress/gutenberg/issues/46042
- [ ] https://github.com/WordPress/gutenberg/issues/46155
- [ ] https://github.com/WordPress/gutenberg/issues/47904
- [ ] https://github.com/WordPress/gutenberg/issues/48804
- [ ] https://github.com/WordPress/gutenberg/issues/49785
- [x] https://github.com/WordPress/gutenberg/issues/49902
- [ ] https://github.com/WordPress/gutenberg/issues/50503
- [ ] https://github.com/WordPress/gutenberg/issues/51625
- [ ] https://github.com/WordPress/gutenberg/issues/52585
- [ ] https://github.com/WordPress/gutenberg/issues/52898
- [ ] https://github.com/WordPress/gutenberg/issues/10853
- [ ] https://github.com/WordPress/gutenberg/issues/10854
- [ ] https://github.com/WordPress/gutenberg/issues/12684
- [ ] https://github.com/WordPress/gutenberg/issues/15696
- [ ] https://github.com/WordPress/gutenberg/issues/17606
- [ ] https://github.com/WordPress/gutenberg/issues/17953
- [ ] https://github.com/WordPress/gutenberg/issues/18962
- [ ] https://github.com/WordPress/gutenberg/issues/20402
- [ ] https://github.com/WordPress/gutenberg/issues/23169
- [ ] https://github.com/WordPress/gutenberg/issues/28117
- [ ] https://github.com/WordPress/gutenberg/issues/28860
- [ ] https://github.com/WordPress/gutenberg/issues/30960
- [ ] https://github.com/WordPress/gutenberg/issues/31773
- [ ] https://github.com/WordPress/gutenberg/issues/33723
- [ ] https://github.com/WordPress/gutenberg/issues/37036
- [ ] https://github.com/WordPress/gutenberg/issues/27809

**Comment by annezazu** [comment]
Closing this out, along with the other various issues you created for specific blocks since it replicates filtering we already have in GitHub. Thanks for the initial push to make this happen -- let's just keeping using the filters instead of needing to keep these individual issues up to date.
