### ISSUE TITLE
Background Image block support follow-up tasks

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#54336]
Related to #16479, following on from #14744.

Now that the background image block support has been introduced in #53934, this issue captures some ideas for follow-up tasks and features.

## Prioritized tasks for WP 6.8 and beyond
* [x] https://github.com/WordPress/gutenberg/issues/60401 - WIP https://github.com/WordPress/gutenberg/pull/60739
   * [ ] https://github.com/WordPress/gutenberg/issues/32787 - Get the block support to work with gradient backgrounds in a logical way. See related comment: https://github.com/WordPress/gutenberg/pull/59354#issuecomment-1975782474 
   * [ ] Update Core safecss_filter_attr/kses to support linear gradient/rgb(a). See: https://github.com/WordPress/gutenberg/pull/60739#discussion_r1575567729
* [ ] https://github.com/WordPress/gutenberg/issues/60939
* [ ] Allow for background-attachment and other controls to be disabled via theme.json (?)
* [ ] https://github.com/WordPress/gutenberg/issues/63096
    - https://github.com/WordPress/gutenberg/pull/63216
    - https://github.com/WordPress/gutenberg/pull/64242
    - https://github.com/WordPress/gutenberg/pull/65304
    - https://github.com/WordPress/gutenberg/pull/66736
* [ ] https://github.com/WordPress/gutenberg/issues/62254
* [ ] Add support for relative theme paths in variation styles and variation block styles. See:  https://github.com/WordPress/gutenberg/pull/60100/files#r1639128861
* [ ] Fix default controls support for background support and panel https://github.com/WordPress/gutenberg/pull/68085
* [ ] Add ability to skip background support serialization in line with other block supports

## Prioritized tasks for WP 6.7
* [x] https://github.com/WordPress/gutenberg/pull/64565
* [x] https://github.com/WordPress/gutenberg/pull/64128
* [x] https://github.com/WordPress/gutenberg/pull/64328
* [x] https://github.com/WordPress/gutenberg/pull/64192
* [x] https://github.com/WordPress/gutenberg/pull/64182
* [x] https://github.com/WordPress/gutenberg/pull/60151
    * [x] https://github.com/WordPress/gutenberg/pull/63225 
* [x] https://github.com/WordPress/gutenberg/pull/61382  - adds support for [background-attachment ](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment) 
* [x] https://github.com/WordPress/gutenberg/pull/60100
    - Hook up post editor to inherited global styles and allow setting to "None". See: https://github.com/WordPress/gutenberg/pull/60100#issuecomment-2159878163
* [x] https://github.com/WordPress/gutenberg/pull/62497
* [x] https://github.com/WordPress/gutenberg/pull/62498
* [x] https://github.com/WordPress/gutenberg/pull/62499
* [x] https://github.com/WordPress/gutenberg/pull/63551

## Completed for WP 6.6
* [x] https://github.com/WordPress/gutenberg/pull/62046
* [x] https://github.com/WordPress/gutenberg/pull/61998
* [x] https://github.com/WordPress/gutenberg/issues/61928
* [x] Add support for theme relative url paths for site-wide background images 
    - https://github.com/WordPress/gutenberg/pull/61401 (experiment)
    - https://github.com/WordPress/gutenberg/pull/61271 
* [x] Ensure that the site editor and frontend body `min-height` values match when a background is selected. https://github.com/WordPress/gutenberg/pull/59809
* [x] Move background default values logic to block supports https://github.com/WordPress/gutenberg/pull/59889 and https://github.com/WordPress/gutenberg/pull/60008
* [x] https://github.com/WordPress/gutenberg/pull/59454
* [x] https://github.com/WordPress/gutenberg/pull/60229
* [x] https://github.com/WordPress/gutenberg/pull/60264
* [x] https://github.com/WordPress/gutenberg/pull/60687
* [x] https://github.com/WordPress/gutenberg/pull/61304
* [x] https://github.com/WordPress/gutenberg/pull/61387
    * [x] https://github.com/WordPress/gutenberg/pull/61469
* [x] https://github.com/WordPress/gutenberg/pull/61388
* [x] https://github.com/WordPress/gutenberg/pull/61526
* [x] https://github.com/WordPress/gutenberg/issues/61494

## Completed for WP 6.5

* [x] Add `contain`, fixed size and repeat controls: https://github.com/WordPress/gutenberg/pull/57005
* [x] https://github.com/WordPress/gutenberg/pull/58592
* [x] https://github.com/WordPress/gutenberg/issues/56261
* [x] https://github.com/WordPress/gutenberg/pull/57495 
* [x] https://github.com/WordPress/gutenberg/pull/57474
* [x] https://github.com/WordPress/gutenberg/pull/54341
* [x] https://github.com/WordPress/gutenberg/pull/54439
* [x] https://github.com/WordPress/gutenberg/pull/54711
* [x] https://github.com/WordPress/gutenberg/pull/57005 

---

## Unprioritized tasks 
* [ ] Enable editor background tools image preview for theme.json `url(...)` string values. See https://github.com/WordPress/gutenberg/pull/64128#issuecomment-2264402255
* [x] Redesign background controls, taking into account background fills/gradients
    - Design proposal: https://github.com/WordPress/gutenberg/pull/60100#issuecomment-2160054475
* [x] https://github.com/WordPress/gutenberg/pull/61561
* [ ] https://github.com/WordPress/gutenberg/issues/62608
* [x] Propose adding `stylesheet_uri` and `template_uri` field to themes endpoint ([Trac ticket](https://core.trac.wordpress.org/ticket/61021), [Core PR](https://github.com/WordPress/wordpress-develop/pull/6399))
* [ ] https://github.com/WordPress/gutenberg/issues/61804
* [ ] https://github.com/WordPress/gutenberg/issues/61809
* [ ] For global styles and custom background images (uploaded to wp-content) save relative paths in the database.
* [ ] Improve performance by allowing support for optimized image size output https://github.com/WordPress/gutenberg/issues/59113
* [ ] Add support for background images via URL rather than just via media library
* [ ] Add option to use Featured Image
* [ ] Enable Duotone support (this will likely require outputting an `img` element)
* [ ] Enable video background (this will also likely require outputting child elements in rendered markup)
* [x] Explore potentially allowing aspect ratio support, as requested for the Cover block: https://github.com/WordPress/gutenberg/issues/54032
* [ ] Explore an option for opacity or overlay of the background image - https://github.com/WordPress/gutenberg/issues/66019
* [ ] https://github.com/WordPress/gutenberg/issues/59113
* [ ] https://github.com/WordPress/gutenberg/issues/62219
* [ ] Should it be possible to set background images on a per page/post basis? https://github.com/WordPress/gutenberg/issues/61928#issuecomment-2218658971

### Background position improvements

* [ ] Allow non-percent-based units (e.g. rem, em, etc)
* [ ] Allow values that are relative to a particular side (see [3-value and 4-value syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position) on MDN) to allow for example "4em from top"
* [ ] Improve experience for adding values from an empty state
* [ ] Consolidate controls with those in the Cover block
* [ ] Look into preventing the controls from displaying until a background image is set (e.g. by moving the size, etc controls into a popover)

**Comment by Ren2049** [comment]
Image embeds are vital for prototyping within the block editor (before comitting them to the media library).

**Comment by annezazu** [comment]
Pulling from the[ FSE Outreach Program's Final Touches call for testing,](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3177) I wondered if the focal point option would eventually be added in as well:

>Color adjustments are fine, but having the same background adjustments available as the cover block would be great. Focus point, at least.

[& more here:](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3178)

>Here it would be great with similar controls that exist in the Cover block such a focus and color overlay and opacity.

[& more here:](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3189)

>The task was fairly straight forward, although I agree with most of the responders here that an image editing toolbar, like the Cover block has, would make a better handle.

Happy to open a separate issue if that's easier!

**Comment by andrewserong** [comment]
>  I wondered if the focal point option would eventually be added in as well:

Oh, yes! It'd be good to have that as an option, too. I've added it to the list in this tracking issue — no need to create a separate issue for it just yet, I think this is a good place to gather together the ideas for now.

> Color overlay and opacity.

Color overlay is possibly a little out of scope for the Group block, as it's well handled by the Cover block and would require additional markup to achieve. The main differences between what we can do for the Group vs Cover blocks at the moment is whether the additional styling rules can be applied to a simple outer wrapper (Group block) vs requiring an additional inner wrapper (Cover block).

**Comment by eduardozulian** [comment]
I'm +[1 a few of the recommendations here](https://github.com/WordPress/gutenberg/issues/54336#issuecomment-1737730825). Here's the list I gathered based on stuff we offer for the Cover Block, all of them already shared:

* Focal point picker
* Overlay opacity
* Set as a fixed background
* Set as repeated background (great for small images that would work as a background pattern)
* Image filters/Duotone support

@andrewserong I believe you're also aware of https://github.com/Automattic/wp-calypso/issues/82284 but I wanted to move it here just to confirm if the lack of padding on the group block is currently expected or if we should indeed offer a default padding if there is a background image/color.

Thank you!

**Comment by andrewserong** [comment]
Thanks for adding that feedback here @eduardozulian!

> I wanted to move it here just to confirm if the lack of padding on the group block is currently expected

Lack of padding on the Group block is expected. The Cover block is a more opinionated block when it comes to adding a background image, and so padding is formally a part of that block's background image implementation. The Group blocks are more general purpose blocks so it's up to the user (or pattern) to add padding when required. There are currently no plans to add padding by default when a user selects a background image.

**Comment by webzunft** [comment]
I see that the generated inline style escapes the quotation marks within `url()`. E.g., 

`style="background-image:url(&#039;https://example.com/wp-content/uploads/2023/10/img-scaled.jpg&#039;);background-size:cover;"`

I don’t see this being a standard in core. If it isn’t, could this be changed to using unescaped quotes?

**Comment by andrewserong** [comment]
@webzunft I believe the escaping occurs due to how the attribute is output in server rendering as the HTML Tag Processor internally calls `esc_attr` when updating an HTML attribute. Is the presence of escaped quotes causing any visual issues on the site frontend for you? The inline styles are only injected at render time, and aren't saved in post content, so it should be possible to make tweaks to how the styles are output in the future.

**Comment by webzunft** [comment]
@andrewserong thanks for your reply. The browser (Chrome) correctly renders the output, so no problem there. I have a plugin that changes HTML in the frontend to inject some information (image captions), which broke with these escaped quotes, but nothing I can’t adjust on my end.

**Comment by joemcgill** [comment]
I'm currently looking at image optimizations for various blocks in the editor, and wanted to raise the issue here of needing to allow the browser to optimize loading the most appropriate image for the user. For blocks that render images as `img` elements, WordPress will automatically add `srcset` and `sizes` attributes, and possible add `loading="lazy"` or `fetchpriority="high"` to optimize resource loading. Coming up with a way of applying resource optimizations to background images would be an important performance improvement.

Related: 
- https://github.com/WordPress/gutenberg/issues/35290
- https://github.com/WordPress/gutenberg/issues/19223

**Comment by mikemcalister** [comment]
> Color overlay is possibly a little out of scope for the Group block, as it's well handled by the Cover block and would require additional markup to achieve.

Not sure if you meant opacity here as well. I'm genuinely curious what the use case is for the group block with a background image but no way to control the overlay?

Groups have content, usually text,and most background images will make text illegible without some way of reducing the brightness. I've created hundreds of patterns, and I can't think of a single use case where I didn't use opacity when using a background image on the cover block. 

Unfortunately, background images and the ability to control opacity and background color are inextricably tied together. If we're adding it to groups, for consistency and usability, it has to come with these controls to make it practically usable. It will be an ongoing battle with users for sure!

**Comment by andrewserong** [comment]
> Not sure if you meant opacity here as well. I'm genuinely curious what the use case is for the group block with a background image but no way to control the overlay?

Great question. In my experience there are heaps!

A good example of use cases for background images that don't require overlay colors are ones that already include transparency within them, or images that folks have selected for their particular content (i.e. I know I'm going to write something with white text, so I'll pick a nice subdued dark image as my background). For examples of some good transparent background images, I've been playing with those at https://www.transparenttextures.com/ and https://www.toptal.com/designers/subtlepatterns/. Many of those sorts of background images require being able to set the image to repeat, which is being worked on over in https://github.com/WordPress/gutenberg/pull/57005.

In terms of the user being able to adjust the opacity or overlay of the background image itself from within the editor, I think that's a great idea, it's just not a very simple task to implement within block supports or to enable for the Group block, so for now I think the other block support features are more pressing to implement, as the Cover block can already handle the overlay case.

I'm just one contributor chipping away at this, but in my opinion, I'd go for us building out the remaining features of the background image support that don't require altering markup (as overlay would require injecting an additional element), and to revisit the idea a little further down the track. It would be nice to support opacity/overlay for it eventually, for sure. I've added it as an item to the issue's description 👍

**Comment by andrewserong** [comment]
Update: the background size / repeat controls (https://github.com/WordPress/gutenberg/pull/57005) are now available on `trunk`, so we can now use repeating background textures in Group block backgrounds. Here's one example of how it can look with a transparent texture as the background image, and then using background color to expose a color through that texture:

https://github.com/WordPress/gutenberg/assets/14988353/c43c91b9-6b66-43fd-bf38-a1a7b47ff462

There were some good ideas for UI follow-ups (e.g. https://github.com/WordPress/gutenberg/pull/57005#issuecomment-1866076523) that I'm hoping to look into in the new year, along with background position controls.

**Comment by colorful-tones** [comment]
I did some testing on this today and it was neat to see in action. Lots of great work. 

However, I believe that the lack of background positioning will cause more frustration than the feature set offers without it. I might consider punting this if we’re not able to get the positioning in place.

**Comment by andrewserong** [comment]
Thanks for testing this out @colorful-tones! The extra controls are currently hidden by default, so my hope was that we could iteratively build out the features before making them more prominent.

You had good timing, though, I was just working on a prototype for background position controls. I have a WIP PR over in #58592 to see if we can add in a simple version of the controls (basically borrowing from the Cover block) and see if that might be viable for now. Happy for any feedback over on that PR if you have the time to test it out! 🙂

**Comment by annezazu** [comment]
Considering the work that's been completed for 6.5, I'm moving this to the "done" column for triaging the board as the individual PRs will capture what's been done here.

**Comment by andrewserong** [comment]
Following on from Anne's comment above, the prioritised tasks for 6.5 are all complete. The main user facing features for this release are:

* Background size controls can now be optionally displayed (defaults to being hidden behind the ToolsPanel ellipsis menu). Enabling these controls exposes:
* Ability to select background size of Cover, Contain, or Fixed
* Toggle Repeat to allow for repeating background images
* A background position picker so users can set a background position / focal point (similar to the Cover block's)

They're the main highlights for 6.5, with these features hidden by default. For 6.6, I'm hoping we can dig into redesigning how we display these controls as suggested in https://github.com/WordPress/gutenberg/pull/57005#issuecomment-1866076523 — that design proposes adding the controls to a popover for the background image (a bit like the color popovers). That idea would have the benefit of making the controls more visible when folks are going to add an image, while tucking them neatly away once the controls have been set to the desired values.

Thanks again for all the feedback and collaboration on these features, all!

**Comment by westonruter** [comment]
What about what @joemcgill raised in https://github.com/WordPress/gutenberg/issues/54336#issuecomment-1828706952? Really, the use of `background-image` should be avoided in favor of `img` whenever possible (e.g. as the Cover block does).

**Comment by andrewserong** [comment]
That's a good point @westonruter — to my knowledge no-one's picked that up as a task yet. One challenge that presents is that so far the Group block hasn't had any supports that inject additional elements within its hierarchy, which could be challenging to get working in a reliable way, particularly when block level or site wide global styles are added for background image support, and for features that `img` doesn't support (i.e. repeating or contained backgrounds). Could one potential approach be to look into using [image-set](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set) notation for optimised image sizes, to avoid having to add an `img` element?

**Comment by westonruter** [comment]
@andrewserong Unfortunately `image-set()` only works with [pixel density descriptors](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set#resolution). It doesn't work with [width descriptors](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset#:~:text=pixels%2C%20provide%20a-,width%20descriptor,-comprised%20the%20number) like `srcset` provides. See also [A Guide to the Responsive Images Syntax in HTML](https://css-tricks.com/a-guide-to-the-responsive-images-syntax-in-html/#:~:text=If%20you%E2%80%99re%20looking%20to%20let%20the%20browser%20choose%20the%20best%20option%2C%20like%20srcset/sizes%2C%20but%20in%20CSS%2C%20the%20solution%20is%20ultimately%20going%20to%20be%20the%20image%2Dset()%20function.%20There%E2%80%99s%20two%20problems%20with%20image%2Dset()%2C%20today%2C%20though) which recommends instead to use media queries. But this requires injecting a `style` element, which would have the same problem as injecting `img`, right?

**Comment by andrewserong** [comment]
Oh, thanks for the link @westonruter! Injecting a media query could potentially be easier in that the `style` element could be anywhere on the page, so possibly enqueued a little bit like how block supports like `layout` attach a classname with a container id to the wrapper element, and then output their styles separately. That way the DOM hierarchy isn't interrupted for the Group block itself 🤔

Definitely worth investigating the options and seeing how they might look. Another potential option could be to give users the control to choose a background image's resolution in the UI (like how the Image block allows users to be explicit about it) — but that has the downside of it not being an automatic optimisation that users don't need to think about.

**Comment by westonruter** [comment]
@andrewserong Nevertheless, what this media query approach for responsive background images doesn't provide is support for lazy-loading. So yeah, `img` still is best.

> Another potential option could be to give users the control to choose a background image's resolution in the UI (like how the Image block allows users to be explicit about it) — but that has the downside of it not being an automatic optimisation that users don't need to think about.

cf. https://github.com/WordPress/gutenberg/issues/19223

**Comment by andrewserong** [comment]
Thanks for the discussion surrounding performance of the block support @westonruter and @joemcgill! It's a pretty nuanced one, and I think there'll be some trade-offs to figure out or to determine the right path forward. Since this is a tracking issue and there's still more to figure out, I've opened up a separate issue over in #59113 to continue the discussion. I've added a few notes to the issue description, but please add any comments there if I've missed anything we've discussed.

**Comment by djcowan** [comment]
Apologies for the brevity.
I am finding it very difficult to understand the need for the structure of each core block to be different.
A good example is the core/cover block compared with the core/group block
Both blocks offer image support - but in completey different ways.
I'm not a React specialist but aren't components meant to be combined to create larger UI components? Cards and such?
What has happen to ideas and principals like polyphorphism and D.R.Y?
Reading back a 2019 comment i followed to get here; regarding the difference between blocks is filling me with despair.
`"Yeah, I'm not sure about this as this will just be a cover block in the end if we do this."` @youknowriad 
<https://github.com/WordPress/gutenberg/issues/14744#issuecomment-478883650>
Which leads me to ask "why?" - isn't this the point?
Now i'm going to leave before I start ranting about the need for separation between content, code and the presentation layer. 
PS. We are trying to apply css [filter functions](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function) to elements that use images. This is how I got here. It can't be done in Wordpress. And this fact frustrates me.

**Comment by colorful-tones** [comment]
Hi folks,
We are only one week away from the Beta 1 cut-off date for [WordPress 6.6](https://make.wordpress.org/core/6-6/). This issue hasn’t seen any movement in a while, so we (the editor triage leads of the 6.6 release) have decided to remove it from the [WordPress 6.6 Editor Tasks project board](https://github.com/orgs/WordPress/projects/179/views/1).

**Comment by andrewserong** [comment]
@colorful-tones this issue is under active work, but the work has been updated in the issue description rather than in separate comments here (CC: @ramonjd). In the issue description, there are two tasks yet to be finished for 6.6 (and one of them is a polishing issue, so it might be able to be worked on during the beta period).

Additionally, there are currently two backport PRs underway for backporting site-wide background images with support for theme relative URLs:

* https://github.com/WordPress/wordpress-develop/pull/6482
* https://github.com/WordPress/wordpress-develop/pull/6608

Can we re-add this issue to the board, or would it be more helpful adding the specific backports that need to make it in?

There have been quite a few PRs landing for 6.6, but they largely all fall under the umbrella of enabling site wide background images. Hope that helps!

**Comment by ramonjd** [comment]
Thanks @andrewserong and @colorful-tones!

> This issue hasn’t seen any movement in a while

If you look at the description edit history, it's seen quite a lot action 😄 

I'll tentatively add the two backport ~issues~ PRs to the board since they're the most important. All the major tasks have been completed for 6.6, with a couple of JS-only package updates to come this week.

Thanks!

**Comment by t-hamano** [comment]
This ticket was featured on today's 6.9 Bug Scrub.

I'd be grateful if you could let me know if there are any tasks that need to be prioritized for the 6.9 release. Thank you!

**Comment by ramonjd** [comment]
> I'd be grateful if you could let me know if there are any tasks that need to be prioritized for the 6.9 release. 

Thanks @t-hamano 

The most important in my opinion are the following:

- https://github.com/WordPress/gutenberg/issues/60401 
- https://github.com/WordPress/gutenberg/issues/32787

They are related.

However I don't think folks will have time to work on a solution for this before 6.9 beta unfortunately.

**Comment by t-hamano** [comment]
@ramonjd Thanks for the reply.

Let's punt this issue to 7.0 if anyone doesn't pick up tasks.

**Comment by t-hamano** [comment]
This issue was featured on today's 6.9 Bug Scrub. There is no activity on this issue, so let's punt it to 7.0.
