### ISSUE TITLE
6.4 Dev Note Tracking Issue

### ISSUE THREAD

**Issue by properlypurple** [WordPress/gutenberg#54998]
## Tracking all Dev Notes from Gutenberg plugin releases 16.2 - 16.7

Please read the information below carefully. If you have questions, ask in `#core-editor` on Slack or comment here.

Not all developer-related information needs to be in a separate DevNote on the Make Core blog for the field guide. We can group related information. We can already make decisions on some features if it warrants a stand-alone blog post or if the information will be part of a group post.

## Stand-alone post

To streamline the process and eliminate bottlenecks, all writers of stand-alone dev notes will write the dev notes on the Make Core Blog. If you need access to write on the Blog, connect with @hellofromtonya or @abhansnuk via Slack or comment here.

#### Instructions
<details><summary>Details</summary>
<p>

- Create your note in a new post, - Save as Draft - Enable public preview - Share the link to the public preview in a comment below, as "ready for review" - "For dev notes, each one must have at least two reviewers" ([Handbook](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/))

</p>
</details> 

## Part of a group post 

If the information related to your PR will be part of a group post, please write the **dev note in a comment on the PR**, so it can be reviewed and, if necessary commented on, by the release docs team or a reviewer.

## Before you start writing 📣 please read the handbook pages:

<details><summary>Details</summary>
<p>

- ⭐️ [Writing developer notes](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/) 
- ⭐️ [Style & Substance section](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance) of the Post & Comment Guidelines for Make Blog 
- ⭐️ [Documentation Style Guide](https://make.wordpress.org/docs/style-guide/) - Good for reference, when in doubt, especially when English is not your native language.

</p>
</details> 

The list is incomplete. We are in the process of reviewing plugin release changelogs and add them as we progress on the task.

There are two labels:
[needs dev note](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22) and [has dev note](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+)

If you worked on a feature/module/component that definitely needs a dev note, please assign the label needs dev note If you already added the Dev Note to the make blog on draft or as a comment on the PR, please label it has dev note

<hr>

## Standalone dev notes:

Block hooks
- [x] [Experiment: Auto-inserting blocks on the frontend and in the editor (via REST API) #51449](https://github.com/WordPress/gutenberg/pull/51449) @ockham
- [x] [Block API: Stabilize Block Hooks feature #54293](https://github.com/WordPress/gutenberg/pull/54293) @gziolo 

### Miscellaneous dev notes: (these are the ones which already have the `neds-dev-note` tag, grouped by release)

- [x] [RichText: replace deprecated multiline prop with simple multiple instances #54310](https://github.com/WordPress/gutenberg/pull/54310) @ellatrix 

- [x] [Theme Previews: Make the back button customizable #54242](https://github.com/WordPress/gutenberg/pull/54242) @scruffian 
- [x] [Add edits data to the useEntityRecord #54167](https://github.com/WordPress/gutenberg/pull/54167) @matiasbenedetto 
- [x] [Indicate nested paths on __experimentalSaveSpecifiedEntityEdits #54161](https://github.com/WordPress/gutenberg/pull/54161) @matiasbenedetto 

-------
  
- [x]  [Always render the fallback Popover anchor within the Popover's parent element #53982 ](https://github.com/WordPress/gutenberg/pull/53982) @ciampo  

-------
 
- [x] [Fonts Library: Backend #52704](https://github.com/WordPress/gutenberg/pull/52704) @matiasbenedetto 
- [x] [Make useBlockEditingMode() public #52094](https://github.com/WordPress/gutenberg/pull/52094) @ramonjd  

-------

  
- [x] [Add new registerInserterMediaCategory API to make media categories extensible #51542](https://github.com/WordPress/gutenberg/pull/51542) @ntsekouras

**Comment by ellatrix** [comment]
> * https://github.com/WordPress/gutenberg/pull/54310

Doesn't make sense as a standalone dev note, would be good to add to miscellaneous.

> `RichText`'s `multiline` prop has been deprecated since 6.1 and was scheduled for removal in 6.3. We're leaving the deprecated prop in place, but its functionality has been simplified internally, so you may experience changes. Instead of one large rich text field, each line is now its own rich text field. We added splitting and merging functionality so the fallback is gracious, but some things like paste may work differently. It's worth noting that this prop remains deprecated and all block authors are encourage to use [`InnerBlocks`](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/) instead.

**Comment by gziolo** [comment]
- https://github.com/WordPress/gutenberg/pull/54293
- https://github.com/WordPress/gutenberg/pull/51449

It's a single feature now called Block Hooks, and @ndiego is helping with the dev note.

**Comment by abhansnuk** [comment]
Thanks for the efforts that have gone into this and the ongoing review of tickets. In the docs release team and with the cohort, we have been helping newer contributors get involved and had been working through a similar ticket review. Thanks to @bph for sharing that this ticket review is also being done in core-editor, so to avoid duplicating with two lists, we will lose the one we had been working on, and focus effort on this tracker. 

Just a signpost to the handbook information, please do not make any dev notes live until seen by the docs release co-leads so that we can keep an overview of where we are and to avoid too many dev notes being published together which can be difficult for those receiving the RSS feed. We also want to build on the efforts from 6.0 onwards to make sure dev notes have useful excerpts and intro paragraphs for search results to help users/ devs know if a note is what they are looking for. 

Thanks again to everyone contributing to this. I am @abhanonstopnewsuk on Slack if you need dev note access.

**Comment by ntsekouras** [comment]
Draft dev note in make core for Add new registerInserterMediaCategory API to make media categories extensible [PR](https://github.com/WordPress/gutenberg/pull/51542) is [here](https://make.wordpress.org/core/?p=108427&preview=1&_ppp=88ba8ff4e5).

**Comment by abhansnuk** [comment]
Thanks Nik. I will have a look.
________________________________

**Comment by properlypurple** [comment]
If you've been pinged in here, please take a look at the PRs below, and comment if the PR needs a dev note.

- [x] #53115 @getdave 
- [ ] #52189 @ryanwelcher 
- [ ] #52190 @ryanwelcher 
- [x] #52982 @hellofromtonya 
- [x] #52133 @chad1008 
- [ ] #52801 @ryanwelcher 
- [x] #53030 @tyxla 
- [x] #54566 @matiasbenedetto 
- [x] #52083 @sethrubenstein 
- [x] #52280 @tyxla 
- [x] #52645 @luisherranz 
- [x] #52579 @westonruter 
- [ ] #53647 @richtabor 
- [x] #53363 @DAreRodz 
- [x] #50122 @gziolo 
- [x] #53733 @luisherranz 
- [x] #53958 @DAreRodz 
- [x] #52094 @noisysocks 
- [x] #53081 @ramonjd 
- [x] #53378 @tellthemachines 
- [x] #53328 @ciampo

**Comment by abhansnuk** [comment]
I am creating Dev Note tracking issues for the items listed above. I will add them to this list. This allows to have an overview of all the Dev Notes in one place.

**Standalone dev notes**
UPDATE ON BELOW combined these two to be one on the documentation tracker given the note above from @gziolo that these have been combined to be 'Block Hooks'.
https://github.com/WordPress/Documentation-Issue-Tracker/issues/1144
- Dev Note tracking: Experiment: Auto-inserting blocks on the frontend and in the editor (via REST API) #51449
- Experiment: Auto-inserting blocks on the frontend and in the editor (via REST API) #51449 

Please can you update this with items relating to the Dev Note. If a google doc has not already been started for this, please let me know and I will create it in the docs area we are using for 6.4 and share it with you. 

If you have already started the Dev Note in the CMS, please add the public preview link to the ticket. 

**Miscellaneous Editor Dev Notes for 6.4**
This has been set up reading for those writing dev notes in the Make/Core CMS. Please can you add any links and updates to the [Docs tracking issue 1146](https://github.com/WordPress/Documentation-Issue-Tracker/issues/1146) 

Thanks so much.

**Comment by luisherranz** [comment]
The Interactivity API is still private in WP 6.4 and only used internally for Core blocks, so there's nothing to inform yet. I've checked all the related items:

- https://github.com/WordPress/gutenberg/pull/52645
- https://github.com/WordPress/gutenberg/pull/52579
- https://github.com/WordPress/gutenberg/pull/53363
- https://github.com/WordPress/gutenberg/pull/53733
- https://github.com/WordPress/gutenberg/pull/53958

**Comment by matiasbenedetto** [comment]
Font Library was punted to 6.5, and for that reason not included in 6.4, so a dev note is not required. 
- https://github.com/WordPress/gutenberg/pull/54566
- https://github.com/WordPress/gutenberg/pull/52704

**Comment by sethrubenstein** [comment]
@properlypurple Yes, but probably just updating the existing [InnerBlocks tutorial doc](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md) to include these stabilized apis? When would you need those updates by?

**Comment by bph** [comment]
After a conversation with @abhansnuk last night, we agreed that I will centralize the Dev Notes wrangling here.  
After I get up to speed, I will coordinate what will be as single post (ie Block Hooks) what will go into a Miscellaneous Editor Changes post and what will just get a mention in the Fieldguide with the Gutenberg contributors.

**Comment by bph** [comment]
Hi @sethrubenstein Thank you! 

Tt would help to alert people that something has changed even if it's just a one paragraph, update to the docs would also be quite appreciated. The deadline for the blurb  is Monday, so we get it into the FieldGuide on Tuesday. For the docs updated, it should happen between now and and Nov 7 (release date for 6.4)

**Comment by gziolo** [comment]
- https://github.com/WordPress/gutenberg/pull/50122

I'm not sure whether it requires a dev note. From the WordPress core, it's mostly an internal optimization to send less code to the browser. It could be useful for folks using `@wordpress/scripts` to inform them they can put some debug code behind:

```
if ( typeof SCRIPT_DEBUG !== 'undefined' && SCRIPT_DEBUG === true ) {
    // This code runs only in the development mode and gets completely removed from the production build.
}
```

However, it's something that we could as well put into the README for `@wordpress/scripts` in the advanced section.

**Comment by andrewhayward** [comment]
- https://github.com/WordPress/gutenberg/pull/52028

This was a minor fix to bring a component in line with some others. No dev note needed.

**Comment by matiasbenedetto** [comment]
My contribution to the miscellaneous dev notes:

---

### Add edits data to the useEntityRecord

- https://github.com/WordPress/gutenberg/pull/54167

Now, the useEntityRecord adds to its output a key called `edits` containing the nonTransientEdits of an entity record. A code example:
```javascript
const widget = useEntityRecord( 'root', 'widget', 1 );
widget.edit( { hello: 'foo' } );

```

Expected result:
```javascript
{
    edits:  { hello: 'foo' }
    ...
}
```

---

### Indicate nested paths on __experimentalSaveSpecifiedEntityEdits

- https://github.com/WordPress/gutenberg/pull/54161

Previously, one could only indicate which top-level properties one wanted to save using __experimentalSaveSpecifiedEntityEdits. So we were limited to doing something like this:
```javascript
__experimentalSaveSpecifiedEntityEdits( 'root', 'globalStyles', globalStylesId, [ 'settings' ] );
```
The latest changes enable developers to indicate which nested paths want to be saved into the database. For example, if one made some client-side changes to the fontFamilies array of the global styles settings ( settings.typography.fontFamilies ) and wants to save to the database only those changes instead of all the changes that the settings objects may have.
```javascript
__experimentalSaveSpecifiedEntityEdits( 'root', 'globalStyles', globalStylesId, [ 'settings.typography.fontFamilies' ] );
```

--- 


Thanks, @bph and @properlypurple for the ping and for running this.

**Comment by ciampo** [comment]
@youknowriad  I'll write the dev note for https://github.com/WordPress/gutenberg/pull/53982

**Comment by scruffian** [comment]
> https://github.com/WordPress/gutenberg/pull/54242 @scruffian

## Site Editor: Make the back to dashboard link text customizable

It has been possible to customize the "Back to Dashboard" link in the Site Editor since 6.2, but not the link text. Now it is possible to also customize the text of the link, by providing a `__experimentalDashboardLinkText` setting:

```
function gutenberg_custom_back_to_dashboard_link( $settings ) {
	$settings['__experimentalDashboardLink']     = '/* Put your custom link here */';
	$settings['__experimentalDashboardLinkText'] = /* Put your custom link text here */;
	return $settings;
}

add_filter( 'block_editor_settings_all', 'gutenberg_custom_back_to_dashboard_link' );
```

This gives extenders the ability to ensure that link labels are updated when they change this back button, which is important for accessibility.

**Comment by ryanwelcher** [comment]
## Dev Note for
* https://github.com/WordPress/gutenberg/pull/52189
* https://github.com/WordPress/gutenberg/pull/52190


## Developer Experience: Exporting stores for the core/customize-widgets and core/edit-widgets packages

Most code examples import the [store directly from the package](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-blocks/#getblocktype) and it is now possible from these packages as well.

**Comment by ramonjd** [comment]
> https://github.com/WordPress/gutenberg/pull/53081 @ramonjd

Dev note here:

- https://github.com/WordPress/gutenberg/pull/53081#issuecomment-1760471177

**Comment by ramonjd** [comment]
> https://github.com/WordPress/gutenberg/pull/52094 @ramonjd

Dev note here:

- https://github.com/WordPress/gutenberg/pull/52094#issuecomment-1760553683

**Comment by tellthemachines** [comment]
Thanks for the ping @properlypurple! 

Dev note for disabling layout controls from theme.json is [here](https://github.com/WordPress/gutenberg/pull/53378#issuecomment-1760568708).

**Comment by tyxla** [comment]
Thanks for wrangling the dev notes, @properlypurple 🙌 

> https://github.com/WordPress/gutenberg/pull/53030 @tyxla

✍️ I've added a dev note at the bottom of the PR description: https://github.com/WordPress/gutenberg/pull/53030

> https://github.com/WordPress/gutenberg/pull/52280 @tyxla

🚫 This was an enhancement to an internal API that is not public-facing, so a dev note is not needed.

**Comment by bph** [comment]
## The state of Gutenberg Dev Notes

We will have four post about developer relevant Gutenberg changes in 6.4 on Make Blog: 

Two of them are in review
Two are WIP


- [Editor Components updates in WordPress 6.4](https://make.wordpress.org/core/?p=108709&preview=1&_ppp=3968f716f0)  (public preview) 
    - Thank you to @brookewp , @tyxla @chad1008  and @ciampo 

- **Introducing Block Hooks**  dev note by @ndiego  is in the works. 
- [New `registerInserterMediaCategory` API](https://make.wordpress.org/core/?p=108427&preview=1&_ppp=aa6e13eab3) (public preview) by @ntsekouras 
- [Miscellaneous Editor changes in WordPress 6.4](https://make.wordpress.org/core/?p=108646&preview=1&_ppp=93ab1c13e2) (public preview) assembled by me (WIP)
    - Thank you to @ellatrix @scruffian @gziolo @matiasbenedetto @tyxla @ramonjd @ryanwelcher 

cc: @hector @anne @richtabor @mamaduka are there things missing? 

Huge thank you to @properlypurple for surfacing all PRs possibly needing Dev Notes.

**Comment by abhansnuk** [comment]
Thank you @bph and @properlypurple , and everyone working on these dev notes.

I think Birgit is already doing a first review, so I will add second review comments below.

1) [Editor Components updates in WordPress 6.4](https://make.wordpress.org/core/?p=108709&preview=1&_ppp=3968f716f0) (public preview)
Really useful note. 
Only 2nd review comments are below:
- In the section 'Introducing a new experimental...', semi-colons could be added at the end of the bullet points to keep in the style used elsewhere in the post for bullet points
- At the end of that section 'More information are' to change to 'More information is'
- 'New props for modal component' - "Note that it is the responsibility of the consumer". What is meant by the description 'consumer', is it the developer or extender?
- excerpt for search results and to give a concise text when people link to it
- once the item has had both reviews, reviewers IDs to be added to the end of the props list


**General comments about this and other dev notes**
a) Links to GitHub
For links out for more information, we have had discussions before about whether dev notes should make clear the link is going outside the blog, eg in this case to GitHub, for accessibility reasons. I can't find the answer in a search of slack but @bph may recall. I thought the decision was to try and say visit GitHub then ticket number.  

b) Categories
From my notes, in 6.0 and 6.1 I think there was a discussion if 'dev notes' should also tick the 'updates' category in addition to 'general' as they are about something new. @bph what do you think?

**Comment by sethrubenstein** [comment]
@bph Updated InnerBlocks doc https://github.com/WordPress/gutenberg/pull/55375

**Comment by andrewserong** [comment]
@bph apologies, it looks like I missed that Block Supports: Add background image support to Group block (#53934) also could use a dev note for 6.4. As with other block supports for previous releases, I think this could be added to your [Miscellaneous Editor changes in WordPress 6.4](https://make.wordpress.org/core/?p=108646&preview=1&_ppp=93ab1c13e2) post, as it's just a short one to make sure folks know how to opt-in for their themes.

I've drafted a short dev note to be added to that post over in this comment: https://github.com/WordPress/gutenberg/pull/53934#issuecomment-1763624385

**Comment by bph** [comment]
Thank you @andrewserong 

> Note that as of WP 6.4, the backgroundImage support is only available at the individual block level, and not in global styles or at the site root.

That bears the question: Are there plans in place to broaden the support?

**Comment by bph** [comment]
@sethrubenstein @andrewserong both items made it into the [Misc Editor changes dev note. ](https://make.wordpress.org/core/?p=108646&preview=1&_ppp=9a325f3cd2)

**Comment by bph** [comment]
@abhansnuk I am not aware of the discussions regarding additional annotating source for the link or the Updates category. For 6.1 and 6.2 I didn't implement either

**Comment by nalininsbs** [comment]
Suggest we take the question on the link @abhansnuk  to accessibility. This can be implemented later if needed. In terms of Updates category, is there a definition or description of what category to use in the handbook?

**Comment by andrewserong** [comment]
> That bears the question: Are there plans in place to broaden the support?

Yes! I touched on it earlier in the dev note in the sentence "Ideas for enhancements in future releases are being tracked in this Github issue: https://github.com/WordPress/gutenberg/issues/54336", but we could add another similar sentence at the end there to make sure it's clear. How about: 

> Note that as of WP 6.4, the backgroundImage support is only available at the individual block level, and not in global styles or at the site root. These features will be explored in subsequent releases, with progress tracked in this Github issue: https://github.com/WordPress/gutenberg/issues/54336.

**Comment by bph** [comment]
Field Guide published: [WordPress 6.4 Field Guide](https://make.wordpress.org/core/2023/10/23/wordpress-6-4-field-guide/)
