### ISSUE TITLE
CustomSelectControl: refactor with ariakit

### ISSUE THREAD

**Issue by brookewp** [WordPress/gutenberg#55023]
## Context

Continuing with the exploration started by @ciampo in #41466, this issue will track the migration of `CustomSelectControl` to Ariakit.

Legacy: https://github.com/WordPress/gutenberg/pull/55234
New version: https://github.com/WordPress/gutenberg/pull/55790

##  Initial steps

- [x] Analyze the legacy component, learn how it works, take note of its features
- [x] Study Ariakit's Select component
- [x] Look into ARIA roles 
- [x] Consider using WordPressComponentsProps https://github.com/WordPress/gutenberg/pull/56998
- [x] Create a new, temporary component which should implement:
  - [x] `children` (and a CustomSelectControlV2.Item component) to allow its consumers to specify select options
  - [x] basic functionality (`value` / `onChange` / `defaultValue` / `label` / `size` props)
  - [x] styles that match the legacy component
  - [x] Storybook docs and examples (maybe one with post authors)
- [x] Refine README, types stories, etc #57902

##  V2 Legacy Wrapper

Completed in #57902

- [x] Analyze the "API gap" between the legacy and the new component 
- [x] Come up with a strategy on how to bridge the gap
- [x] Add support for the "monolithic" usage of the component with the options prop
- [x] Bolster the legacy CustomSelectControl unit tests https://github.com/WordPress/gutenberg/pull/56575
- [x] Use the previously bolstered unit tests to certify that the new component behaves like the legacy one
- [x] Align unit tests #62706
- [x] Fix option extra attributes types and propagation to `onChange` callback and DOM elements #62255
- [x] Investigate potential issues when using v2 legacy adapter in controlled mode, as the component doesn't seem to update correctly when a new `value` is passed? (can be reproduced by following the testing instructions in #62255 re. `FontAppearanceControl` in global styles) — fix in https://github.com/WordPress/gutenberg/pull/62733
- [x] Double check initial item selection, including the fact that `onChange` doesn't fire on first render on v1 while it does on legacy v2 (WIP PR #62308, [comment](https://github.com/WordPress/gutenberg/pull/62706#discussion_r1647734766)) — fix in https://github.com/WordPress/gutenberg/pull/62733
- [x] Double check any styling issues as flagged in [this comment](https://github.com/WordPress/gutenberg/pull/61272#issuecomment-2136367426) and following conversation  (plus check WIP in https://github.com/WordPress/gutenberg/pull/62424)
  - [x] #62821
  - [x] https://github.com/WordPress/gutenberg/pull/62198
  - [x] https://github.com/WordPress/gutenberg/pull/62803
  - [x] https://github.com/WordPress/gutenberg/pull/62848
  - [x] https://github.com/WordPress/gutenberg/pull/62844
  - [x] https://github.com/WordPress/gutenberg/pull/62850
  - [x] #62825
  - [x] #62869
  - [x] #63131
  - [x] #63229
  - [x] #63230
- [x] Align keyboard event propagation while focussing select popover ([context](https://github.com/WordPress/gutenberg/pull/30557)) #62907 
- [x] Check arrow down behaviour #62919
- [x] #63137
- [x] Make the V2 legacy wrapper available via private APIs #62936
- [x] Swap all V1 usages with V2 legacy wrapper (remember to also check and possibly remove unnecessary style overrides)
  - [x] #63134
  - [x] #63139
  - [x] #63171
  - [x] #63179
  - [x] #63190
- [x] Check that there are no unknown style overrides remaining
- [x] #63357
- [x] https://github.com/WordPress/gutenberg/pull/63248
- [x] #63343
- [x] #63258
- [x] Prepare dev note

### To discuss

- [ ] Review API surface:
  - [ ] Based on how much we expect V2 default to diverge from V2 legacy wrapper, does it make sense to keep a common underlying implementation, since it comes at the cost of higher complexity in the internal implementation 
    - [ ] if so, let's see if there is a better way to allow different behavior / styles between the two versions (we currently use React context + passing props to Styled components)
  - [ ] Should the components forward refs? If so, should they expose multiple refs? (ie. to the label, the button, and the popover)
  - [ ] How to differentiate between props for wrapper vs props for trigger? Should we have a trigger render prop, like we do for `DropdownMenuV2` ? (see https://github.com/WordPress/gutenberg/pull/62803#discussion_r1652321562))
- [ ] Popover behavior and APIS:
  - [ ] Should the popover be modal ? Regardless, should it always prevent body scroll?
  - [ ] Where should the popover render in the DOM ? Always inline? Always portal-ed ? If so, in which slot (see https://github.com/WordPress/gutenberg/issues/56482)? Should we expose any props?
    - [ ] This should influence / should be influenced by `DropdownMenuV2` too
- [ ] Consider cloning + splitting V1 and V2 implementations, so that V2 can diverge without affecting V1
- [ ] Do we need an `isMultiple` prop? (especially when neither `value` nor `defaultValue` are specified, but also for TS ergonomics)
- [ ] Discuss whether it makes sense to tweak the size of each item based on the pointer type (smaller items for fine pointer control, larger items for coarser pointer)
- [ ] Discuss best approach to the select popover `height` (including the maximum and minimum heights) (see #49110)
- [ ] Discuss best approach to the select popover flip behavior (especially in the light of #63180)
- [ ] Consider adding new features (like exporting more subcomponents, separators, group and group labels, etc)
  - [ ] Including new `Select`-related components recently added to Ariakit
- [ ] Ask design for specs/review
  - [ ] Should it have more specific prefix/suffix structure, similarly to the new `DropdownMenuItem` ?
  - [ ] Checkmark/`SelectItemCheck`
    - [ ] should it be optional? 
    - [ ] should it be instead exported as a subcomponent, and used by consumers when needed?
    - [ ] [placement](https://github.com/WordPress/gutenberg/pull/55790#issuecomment-1820693281):
        > Should the design for CustomSelectItem be inspired by the work? Specifically; placing the checkmark icon on the left?
  - [ ] review line height ([see comment](https://github.com/WordPress/gutenberg/pull/62825#discussion_r1661310349))

### To implement

- [x] Remove legacy adapter layer (make two separate exports) #59420
- [x] Rename to `CustomSelectControl` and `CustomSelectControl.Item` #60178
- [x] Should the list of items always have the same width as the closed component? #57902
- [x] Add compact size #57902
- [x] Focus / hover styles on both the items and the selected value #60261
- [ ] Try to make the TS types for the single/multiple selection modes be more ergonomic
- [ ] Update ariakit to latest version and see new `Select` components (see [changelog](https://ariakit.org/changelog))
- [ ] See what unit tests can be applied also to the v2 implementation (non legacy)
- [ ] Needs a utility padding wrapper like `InputControlPrefixWrapper`
- [ ] Allowing the trigger button to be `disabled`
- [ ] #49110
- [ ] #63180

### To check before releasing

- [ ] Public-facing docs (Types, Storybook examples, READMEs)
- [ ] Export the component as private API, start experimenting in the editor
- [ ] Check with accessibility folks on this and for overall feedback

**Comment by brookewp** [comment]
@andrewhayward  @afercia  @alexstine 

Hey folks! We're looking into improving the `CustomSelectControl` component. To start, we've created [a basic experimental component](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-customselectcontrol-v2--docs) based on [Ariakit's Select](https://ariakit.org/components/select). 

Before getting too far into this, we wanted to check in with you all to hear your thoughts on this. Do you have any concerns with the existing `CustomSelectControl` or with Ariakit's `Select`? How does [the new version](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-customselectcontrol-v2--docs) of the new component feel so far? 
<hr>

>[!NOTE] 
>When testing the new version, the select's popover will appear to be misaligned. You can use the shortcut `S` to toggle the sidebar or open the story in its own window to see the correct styling.

**Comment by afercia** [comment]
@brookewp thanks for the ping.

> Do you have any concerns with the existing CustomSelectControl

The only concern I have with the existing `CustomSelectControl` is that it seems to use a wrong ARIA role of `listbox`. The `listbox` role is more similar to a HTML `select` element _with size attribute greater than one_. Instead, what we want is to emulate a HTML `select` element _with size one_.

[The Ariakit's Select implementation](https://ariakit.org/components/select) seems more correct to me, at a first glance. It uses a `combobox` role which is more appropriate. However, the `combobox` role has a few variants and several optional behaviors. it's a bit complex to understand. It's important to get it right since the start. Reference with examples in the ARIA Authoring Practices (APG): https://www.w3.org/WAI/ARIA/apg/patterns/combobox/

> Some comboboxes allow users to type and edit text in the combobox and others do not. 

**To emulate a HTML select element**
When a combobox does not support text input, it is referred to as **select-only**, meaning the only way users can set its value is by selecting a value in the popup. For example, in some browsers, an HTML select element with size="1" is presented to assistive technologies as a combobox.

This is the behavior we'd want to use for a HTML select-like component. All the properties to be used and intereaction are detailed in the APG. Example available here: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only

**Input with suggestions**
Instead, when a combobox supports text input, it is referred to as **editable**. An editable combobox may either allow users to input any arbitrary value, or it may restrict its value to a discrete set of allowed values, in which case typing input serves to filter suggestions presented in the popup

This is the pattern we'd want to use for `ComboboxControl` and `FormFieldToken`, which is more commonly called 'autocompleter with suggestions'.

## Initial testing

Quickly testing with Safari and VoiceOver:

- The default example seems to work okay to me.
- The [Multi-Select](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-customselectcontrol-v2--docs#stories) example dosn't work correctly: the announcement of the selected options is wrong, at least with Safari and VoiceOver.
- The [Controlled](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-customselectcontrol-v2--docs#controlled) example: same, the announcement of the selected option is wrong.

**Comment by ciampo** [comment]
Thank you for looking in to this, @afercia ! And also for sharing some very useful links to the relevant parts of the specs.

> [The Ariakit's Select implementation](https://ariakit.org/components/select) seems more correct to me, at a first glance.

Thank you! That's good to know, especially since the new version of the component that Brooke has been working on is indeed based on the ariakit `Select` component family.

> Quickly testing with Safari and VoiceOver:
> 
> * The default example seems to work okay to me.
> * The [Multi-Select](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-customselectcontrol-v2--docs#stories) example dosn't work correctly: the announcement of the selected options is wrong, at least with Safari and VoiceOver.
> * The [Controlled](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-customselectcontrol-v2--docs#controlled) example: same, the announcement of the selected option is wrong.

Could you be more specific about what exactly is wrong vs the expected behaviour? 


I'm also going to re-open this issue, since it was meant to be a tracking issue for @brookewp's ongoing work on those components.

**Comment by afercia** [comment]
> I'm also going to re-open this issu

Oh sorry I think I closed it not intentionally, somehow.

> Could you be more specific about what exactly is wrong vs the expected behaviour?

Well simply testing it with a screen reader clearly shows the bugs so I'm assuming this hasn't been tested properly.

In both the Multi-Select and the Controlled example, the 'selected' announcement is wrong. I think it's because of incorrect usage of `aria-selected` but I haven't looked into it in depth. I think this originates from some confusion about `aria-selected' as this attribute in some ARIA widgets configurations is meant to indicate the actually _selected_ option while in other cases is meant to indicate the _highlighted_ option for example while navigating with the arrow keys through a list of suggestions. More confuzion may arise when multi-selection comes into plau.  The correct usage is well detailed in the ARIA Authoring Practices but it may be source of confusion.
I _think_ it's an ariakit bug and should be fixed upstream. But, so far, we can't use the Multi-Select and the Controlled configurations.

I'm testing with:
- macOS Sonoma 14.1.1
- Safari Version 17.1 (19616.2.9.11.7)
- VoiceOer Version 10 (919.1)

## Multi-Select

Initial announcement of the two selected options looks correct:

![Screenshot 2023-11-30 at 09 59 09](https://github.com/WordPress/gutenberg/assets/1682452/5057c6e8-e13e-44d4-81e5-acb6a0e1f97f)

But, as soon as arrow keys are used to move to the other options, the announcement is wrong: 'flamingo pink' is not selected but it is announced as 'added to selection'.

![Screenshot 2023-11-30 at 09 59 25](https://github.com/WordPress/gutenberg/assets/1682452/51afe358-103e-474c-84bb-22c2e614bb63)

or, it announces that a selection has bee 'replaces' while it is not true:

![Screenshot 2023-11-30 at 10 26 04](https://github.com/WordPress/gutenberg/assets/1682452/7af6d653-fcbe-47b8-81e8-3b6ce635926d)

And again, moving through the options it announces  'removed from selection' or  'added to selection' when it's not true.

## Controlled 

This is a bit uncomfortable to test as there are a few containers with CSS overflow property that cut-off the dropdown. I removed those CSS using the dev tools inspector properties for testing purposes.

Again, navigating through the options, it may announce an option as 'selected' while it is not true:

![Screenshot 2023-11-30 at 10 04 08](https://github.com/WordPress/gutenberg/assets/1682452/0c89aa12-07d8-4e33-b7c9-39d3c6b68621)

**Comment by diegohaz** [comment]
> > Could you be more specific about what exactly is wrong vs the expected behaviour?
> 
> Well simply testing it with a screen reader clearly shows the bugs so I'm assuming this hasn't been tested properly.
> 
> In both the Multi-Select and the Controlled example, the 'selected' announcement is wrong. I think it's because of incorrect usage of `aria-selected` but I haven't looked into it in depth. I think this originates from some confusion about `aria-selected' as this attribute in some ARIA widgets configurations is meant to indicate the actually _selected_ option while in other cases is meant to indicate the _highlighted_ option for example while navigating with the arrow keys through a list of suggestions. More confuzion may arise when multi-selection comes into plau. The correct usage is well detailed in the ARIA Authoring Practices but it may be source of confusion. I _think_ it's an ariakit bug and should be fixed upstream. But, so far, we can't use the Multi-Select and the Controlled configurations.

@afercia, thanks for testing. There's a bug in WebKit/Safari. I can reproduce the same behavior on the [APG Multi-Select Listbox example](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/examples/listbox-rearrangeable/#ex2_label).

Safari has known issues with `aria-activedescendant`. [It appears the issue is being addressed for combobox widgets in the upcoming version](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-183#Accessibility:~:text=Fixed%20comboboxes%20not%20notifying%20assistive%20technologies%20when%20aria%2Dactivedescendant%20changes.%20(270182%40main)%20(117747058)). So, we can expect improvements in the near future.

For now, the `aria-activedescendant` can be disabled for the Ariakit Select component by setting the [`virtualFocus`](https://ariakit.org/reference/select-provider#virtualfocus) prop to `false`. This will enable the use of the roving tabindex approach, which seems to function well on Safari.

**Comment by ciampo** [comment]
Thank you Diego for the reply!

> For now, the `aria-activedescendant` can be disabled for the Ariakit Select component by setting the [`virtualFocus`](https://ariakit.org/reference/select-provider#virtualfocus) prop to `false`. This will enable the use of the roving tabindex approach, which seems to function well on Safari.

Do you suggest, for now, always setting `virtualFocus: false` to provide a better, more consistent experience across browsers?

**Comment by alexstine** [comment]
The Safari bug is a really bad one. It also affected the block autocompleter.

https://github.com/WordPress/gutenberg/pull/54902

Safari needs to keep support for ARIA attributes, that's the least Apple could do.

**Comment by afercia** [comment]
> Safari has known issues with aria-activedescendant.

Yes that's a known problem but I don't think it's the only one.

Latest Safari version seems to made things even worse. However, we already went through listboxes, comboboxes, autotompleters, `aria-activedescendant`, and 'aria-selected` a few times. For example, we had an issue with the UrlInput in https://github.com/WordPress/gutenberg/issues/47147 and we fixed it in https://github.com/WordPress/gutenberg/pull/47148. At that time, the UrlInput worked with Safari and VoiceOver. Instead, now it doesn't work. Other autocompleters don't work with Safari / VoiceOver, for example the Command center, see https://github.com/WordPress/gutenberg/pull/52930. 
Although the combobox with autocompleter is a different pattern than a Listbox, I suspect the root problem is the same.
These ARIA patterns are extremely delicate and even a small detail could make a difference. _Even the markup structure_, like unexpected wrappers could have an impact.

Still, it's important to note that the 'Add new tag' combobox with suggestions does work with Safari / Voiceover. It does use 
`aria-activedescendant`, it does use `aria-selected`, and it uses the old ARIA 1.0 pattern with `arira-owns` instead of `aria-controls`. It does not use the `speak` workaround implemented in https://github.com/WordPress/gutenberg/pull/54902. It just works out of the box.

Since this combobox + listbox does work, I'd suggest to investigate in depth why it works and why the other ones don't. There must be something that we are missing (and I couldn't find it out so far).

Screenshot of the Tag suggestions working with Safari / Voiceover:

![Screenshot 2023-12-01 at 10 12 11](https://github.com/WordPress/gutenberg/assets/1682452/1ce3ded1-5f50-4cef-962b-428e453773f2)

Tested with:
macOS Sonoma 14.1.1
Safari Version 17.1 (19616.2.9.11.7)
VoiceOver Version 10 (919.1)

**Comment by ciampo** [comment]
> it's important to note that the 'Add new tag' combobox with suggestions does work with Safari / Voiceover

That would be the `FormTokenField` component, which you can see in isolation [in Storybook](https://wordpress.github.io/gutenberg/?path=/docs/components-formtokenfield--docs)

**Comment by alexstine** [comment]
I believe it works likely because the controlled descendant appears directly after the input in the DOM.

**Comment by afercia** [comment]
> I believe it works likely because the controlled descendant appears directly after the input in the DOM.

Yes it is possible. Also, I seem to recall Safari / VoiceOver don't work at all with options _nested_ within groups.

**Comment by mirka** [comment]
This is now superseded by the `Select` component in `@wordpress/ui`.
