### ISSUE TITLE
Migrate `Composite` consumers from `reakit` to `ariakit`

### ISSUE THREAD

**Issue by andrewhayward** [WordPress/gutenberg#55224]
## What problem does this address?

As per #53278, we need to move away from `reakit` to use `ariakit` instead. #54225 started on migrating [the `Composite` component](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/composite), by adding the equivalent `ariakit` modules as a `v2`. This work needs to be completed by migrating all `Composite` consumers to use the `v2` alternative.

## What is your proposed solution?

We need to...
- [x] ...identify all `Composite` consumers across Gutenberg
- [x] ...iteratively refactor all usages of the `reakit` implementation.
  - [See below 👇](#issuecomment-1756246824)

When all consumers are migrated, we should then...
- [x] ...remove the `reakit` version of `Composite`
- [ ] ...make the `ariakit`-based version standard
- [ ] ...move all consumer away from the private API
- [ ] ...remove the private API export

**Comment by andrewhayward** [comment]
# `Composite` consumers

## `block-directory`
  - [x] [`downloadable-block-list-item`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-directory/src/components/downloadable-block-list-item/index.js)
    - #55272
  - [x] [`downloadable-blocks-list`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-directory/src/components/downloadable-blocks-list/index.js)
    - #55272

## `block-editor`
  - [x] [`block-pattern-setup`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/block-pattern-setup/index.js)
    - #55425
  - [x] [`block-patterns-list`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/block-patterns-list/index.js)
    - ~~#55383~~
    - #56210
  - [x] [`block-switcher/pattern-transformations-menu`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/block-switcher/pattern-transformations-menu.js)
    - #56122
  - [x] [`inserter/media-tab/media-list`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/inserter/media-tab/media-list.js)
    - #56195
  - [x] [`inserter/media-tab/media-preview`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/inserter/media-tab/media-preview.js)
    - #56195
  - [x] [`inserter-listbox`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/inserter-listbox/index.js)
    - #56246
  - [x] [`inserter-listbox/item`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/inserter-listbox/item.js)
    - #56246
  - [x] [`inserter-listbox/row`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/block-editor/src/components/inserter-listbox/row.js)
    - #56246

## `edit-site`
  - [x] [`add-new-template/add-custom-template-modal-content`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/edit-site/src/components/add-new-template/add-custom-template-modal-content.js)
    - #55256
  - [x] [`style-book`](https://github.com/WordPress/gutenberg/blob/6a04d57b280490ec1a33c168c3f3f47603b08161/packages/edit-site/src/components/style-book/index.js)
    - #55344

**Comment by andrewhayward** [comment]
Closing with #58850 to track remaining work.
