### ISSUE TITLE
Increase mobile app E2E test robustness

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#55251]
## What problem does this address?

In addition to other test types, we rely upon [E2E tests](https://github.com/WordPress/gutenberg/tree/0c216e400b3cc7764cc27713bf44c31e3712dc57/packages/react-native-editor/__device-tests__) for critical flows related to native OS features. The current native mobile editor E2E tests provide a good foundation for our needs. However, there is opportunity to increase the tooling robustness, refactor to make it more approachable, and remove dead code/unused abstractions now that we prioritize integration tests. 

## What is your proposed solution?

We could work on the following tasks to improve the robustness and approachability of the E2E tests. 

* [x] Clearing Metro caches before bundling for E2E tests, as it can cause cryptic failures between test runs after running `npm install` - https://github.com/WordPress/gutenberg/pull/55554
* [x] #55567
* [x] https://github.com/WordPress/gutenberg/pull/55711
* [x] https://github.com/WordPress/gutenberg/pull/55716
* [x] https://github.com/WordPress/gutenberg/pull/55898
* [ ] Refactor E2E test `EditorPage` and `utils` to support applying changes in watch mode
* [ ] Reassess impact and necessity of artificial delays, durations, etc
* [ ] Remove low-value, single-use E2E test abstractions considered unnecessary indirection

**Comment by dcalhoun** [comment]
Closing given the most impactful tasks were completed, and we do not plan to spend time on further improvements at this time.
