### ISSUE TITLE
Canvas and sidebar interaction polish tracking issue

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#55578]
## What problem does this address?
Using the editor / interacting with the canvas should feel intuitive. This requires a level of polish, particularly surrounding microinteractions, that we currently don't have. There are expected interactions that either don't exist (e.g. infer layout via drop position) , don't work as expected, or buggy.

This is a tracking issue that highlights opportunities for improvement with the ultimate goal to create a polished editing experience that is enjoyable to use.

## Prioritised tasks, aiming for WP 6.5

- [ ] Drag & drop overarching issue: https://github.com/WordPress/gutenberg/issues/33683
- [x] List view drag and drop: Make it more obvious blocks can be dragged: https://github.com/WordPress/gutenberg/issues/33686
- [x] List View: Right click on items to expose settings: https://github.com/WordPress/gutenberg/pull/50273

## Needs design and/or more info and a separate issue to be created

- [ ] Expose drag & drop: https://github.com/WordPress/gutenberg/issues/54952
- [ ] Transforms: should expose variations for things that have them in a fly out menu.
- [ ] Consider removing the toolbar handle
- [ ] The chip when drag&dropping in the list view is too big
- [ ] Multi-selection down works, but not when you move the mouse up
- [ ] Selecting multiple blocks in canvas that span multiple levels
- [ ] On canvas controls for padding and gap

## Long-term (not yet prioritised for a particular release)

- [ ] https://github.com/WordPress/gutenberg/issues/59646
- [ ] Image resize handles: https://github.com/WordPress/gutenberg/issues/44357

**Comment by andrewserong** [comment]
I've done a little re-ordering of this issue to add a section for issues that are prioritised for 6.5 and are ready to be worked on (or are already in progress), with other issues moved to a section flagging that new issues need to be created, or where design work is needed before development can commence.

Feel free to update and edit the description as needed!

**Comment by andrewserong** [comment]
Tiny update: the List View right click [PR](https://github.com/WordPress/gutenberg/pull/50273) has been merged. I've opened up a follow-up issue in https://github.com/WordPress/gutenberg/issues/57091 to discuss ideas for other areas in Gutenberg where a custom right-click contextual menu could be useful. There's likely lots to consider if expanding it to the editor canvas, so hopefully that issue will be a good place to tease out the ideas or designs if and when it's to be explored.
