### ISSUE TITLE
Tracking: Style Revision UX Improvements

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#55776]
I'm documenting some discussion around improvements to style revisions in the block editor. Specifically refinements to improve the UX and discoverability of the feature. These will be broken out as separate issues over time, but this can act as a tracking issue.

- [x] https://github.com/WordPress/gutenberg/issues/53621
    - https://github.com/WordPress/gutenberg/pull/56799 
    - Use load more for pagination instead of number pagination??
- [x] https://github.com/WordPress/gutenberg/issues/55577
    - https://github.com/WordPress/gutenberg/pull/56800
- [x] Update the saving flow for style revisions to provide detail instead of just a "custom styles" checkbox. 
    - https://github.com/WordPress/gutenberg/pull/57411
    - https://github.com/WordPress/gutenberg/pull/57470
- [ ] https://github.com/WordPress/wordpress-develop/pull/5699
- [x] https://github.com/WordPress/gutenberg/pull/54046
- [x] https://github.com/WordPress/gutenberg/pull/55827
- [x] #55779
- [x] #55647
    - https://github.com/WordPress/gutenberg/pull/56577
- [x] https://github.com/WordPress/gutenberg/issues/55648
- [x] https://github.com/WordPress/gutenberg/pull/55881
- [x] https://github.com/WordPress/gutenberg/pull/56491
- [x] Explore a link to the code revisions view https://github.com/WordPress/gutenberg/pull/56577#issuecomment-1846305014

Future once these are done: https://github.com/WordPress/gutenberg/issues/53484

### Related

- https://github.com/WordPress/gutenberg/issues/56413

**Comment by annezazu** [comment]
Not sure if this is intentional but wanted to note these additional related items for consideration:

https://github.com/WordPress/gutenberg/issues/53484
https://github.com/WordPress/gutenberg/issues/55577

**Comment by alexstine** [comment]
Sorry, wrong issue.

**Comment by apeatling** [comment]
@annezazu Thanks for those. I've added #55577, and https://github.com/WordPress/gutenberg/issues/53484 will be looked at once these smaller improvements are done.

**Comment by ramonjd** [comment]
> Update the saving flow for style revisions to provide detail instead of just a "custom styles" checkbox

Note to self - looking into this, I think the following needs to occur:

1. We can add a description for the `globalStyles` entity somewhere around in [packages/editor/src/components/entities-saved-states/entity-type-list.js](https://github.com/WordPress/gutenberg/blob/071082ce485b36f84ca654de5f1a4e1a57d7eb80/packages/editor/src/components/entities-saved-states/entity-type-list.js#L91-L91)
2. But because this is in the editor package, we'd probably need to move packages/edit-site/src/components/global-styles/screen-revisions/get-revision-changes.js, possibly to where `GlobalStylesContext` lives in `blockEditorPrivateApis` (@wordpress/block-editor) so we can consume it. `getRevisionChanges()` could be renamed to something else 🤷🏻 
3. Then we can create a specific hook/whatever to fetch the changes and use as the change description in the EntityTypeList

Some untested pseudo code:

```js

import { privateApis as blockEditorPrivateApis } from '@wordpress/block-editor';
import { useMemo, useContext } from '@wordpress/element';
import { getBlockTypes } from '@wordpress/blocks';

import { unlock } from '../../lock-unlock';

const { GlobalStylesContext, getRevisionChanges } = unlock( blockEditorPrivateApis );

function foo() {
	const { user: currentEditorGlobalStyles } =
		useContext( GlobalStylesContext );

	const blockNames = useMemo( () => {
		const blockTypes = getBlockTypes();
		return blockTypes.reduce( ( accumulator, { name, title } ) => {
			accumulator[ name ] = title;
			return accumulator;
		}, {} );
	}, [] );

	const changeDescription = getRevisionChanges(
		currentEditorGlobalStyles,
	        {},
		blockNames
	);
       ....
}
```

**Comment by getdave** [comment]
👋 Hello team. Whats the update on this feature for WP 6.5? Is it likely to land and if so which features (as originally outlined in [the roadmap](https://make.wordpress.org/core/2023/12/07/roadmap-to-6-5/)) will make it. Thanks in advance 🙏

**Comment by ramonjd** [comment]
Thanks @getdave 

This issue can be closed off.

The following, outstanding task is ongoing, but comprises a refactor only and I'd say not required for 6.5

- https://github.com/WordPress/wordpress-develop/pull/5699

All other relevant PRs attached to this issue have Core backport PRs already (well, one):

- https://github.com/WordPress/wordpress-develop/pull/5622
