### ISSUE TITLE
Tracking Issue: Server Directive Processing

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#55938]
_We previously referred to this as "server-side rendering" (SSR), but that term is too generic, so we renamed this initiative to "server directive processing" instead._

This Tracking Issue tracks the ongoing efforts to process the Interactivity API directives in the server.

We will hook into the block rendering pipeline using a combination of `render_block_data` and `render_block`. We should also start measuring performance as early as possible to make sure that processing directives is as performant as it can be. For the processing itself, we will try to leverage the new HTML API, as it will be the most performant and safe way to do this.

## Tasks

These are some of the initial tasks, although we will edit this post once we progress and discover what other things we need to do.

- [x] Make sure we only process the directives once.
  - https://github.com/WordPress/gutenberg/pull/55739
- [x] Improve the way we save references to the root blocks.
  - https://github.com/WordPress/gutenberg/pull/56107
- [x] Get rid of the `md5` + `serialize` and find a better way to identify blocks.
- [x] Differentiate between interactive and non-interactive blocks.
  - https://github.com/WordPress/gutenberg/pull/56302
- [x] Integrate the HTML API in the directives processing.

**Comment by cbravobernal** [comment]
I added a PR refactoring how we save references to check root blocks. Also update the tests to be more unit (focused on add/delete root block variable).

#56107

**Comment by cbravobernal** [comment]
https://github.com/WordPress/gutenberg/pull/56107 has been merged.

I'll start working on the next list item. "Differentiate between interactive and non-interactive blocks."

**Comment by luisherranz** [comment]
@c4rl0sbr4v0 opened this PR to start working on the final rendering:

- https://github.com/WordPress/gutenberg/pull/56302

I've also added a new item to the list:

- Get rid of the `md5` + `serialize` and find a better way to identify blocks.

**Comment by luisherranz** [comment]
We're going to consolidate this one into the new public 1.0 version tracking issue:

- https://github.com/WordPress/gutenberg/issues/56803

Let's report our progress on the server directive processing there instead.
