### ISSUE TITLE
Tracking: Adding a new `Dialog` Component

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#56452]
# What?

A new `Dialog` component family leveraging third party libraries that will serve as a more modular and flexible version `Modal`.

# Why

`Modal` has a lot of overrides applied to it, which is a sign that the current approach isn't meeting consumer's needs. A more flexible component should help remedy that. See #56231 for more detail and discussion.

# To Do

Initially this will be a general outline of the work to be done, but new todos will get added as the new components progress and specific challenges/needs emerge.

## Planning/Exploration
- [ ] Work up a list of planned sub-components and each one's features and purpose
- [ ] Discuss and modify approach for those sub-components as needed
- [ ] Put together a demo/proof of concept using those sub-components

## Development
- [ ] Gather feedback from the demo component and define tasks for improvement, fixes, or additions
- [ ] Armed with this feedback, evaluate `Dialog` and `Modal` to determine if the former can truly replace the latter (meaning we'd deprecate `Modal`) or if there's room and benefit for both components to exist alongside each other.
- [ ] Implement and gather feedback on preset sizes, with specific attention to the interplay between widths and heights
- [ ] Implement unit tests, using `Modal's` tests as a starting point and adjusting for any new or changed features in `Dialog`

## Implementation
There are approximately 50 existing implementations of `Modal` sprinkled across the editor, which I can list out in more detail when we get closer to this stage of the work. Once all of the existing implementations are moved over to the new components we can proceed with deprecating `Modal`, if that is indeed what we ultimately decide to do.

**Comment by youknowriad** [comment]
This looks like a stale issue. I'm closing right now. I know there are plans for a new DS package that might explore better dialog components.

cc @aduth for awareness.
