### ISSUE TITLE
`Button` creates new HTML elements every time it internally flips between showing tooltips or not

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#56522]
_As discussed originally in https://github.com/WordPress/gutenberg/discussions/44735_

### The problem

The `Button` component can, [based on which props are passed](https://github.com/WordPress/gutenberg/blob/aa7cc4d0404e0a830144c57e5211335b48f9ba2d/packages/components/src/button/index.tsx#L195-L206), show a tooltip when hovered or focused.

This feature is implemented by[ wrapping conditionally the button's contents in a `Tooltip` component](https://github.com/WordPress/gutenberg/blob/aa7cc4d0404e0a830144c57e5211335b48f9ba2d/packages/components/src/button/index.tsx#L259-L292).

The current implementation causes React not to be able to [reconciliate](https://react.dev/learn/preserving-and-resetting-state) the Button's contents if the need for showing a tootlip changes at runtime. In return, this causes the current `button` (or `a`) element rendered in the DOM to be removed and replaced by a new element, which causes focus loss.

### Known workarounds and potential solutions

The most clear way to avoid the re-render is to make sure that the `Tooltip` component is always rendered (instead of being rendered conditionally). This can be achieved in a few ways:

1. by specifying the `showTooltip` prop on `Button` (although this will force the tooltip to be always visible) ([example](https://github.com/WordPress/gutenberg/blob/ca2ee4d6fa8c7044cd1d3045c0985a77659f44fa/packages/editor/src/components/post-saved-state/index.js#L155-L161))
2. by avoiding to trigger the internal tooltip in `Button`, and instead wrapping `Button` externally with a `Tooltip`  (tested in #56502)
3. by tweaking the `Button` component to internally always render a `Tooltip` component (proposed in #56490)

Approaches 1 and 2 can work well to fix specific instances of `Button`, while approach 3 would solve the problem fundamentally for all `Button` usages (although it has the potential to introduce a breaking change).

A 4th approach (yet to be tested) would be to try to use the `key` special prop as a way to flag to React that a given component is stable (and therefore doesn't need to be destroyed and re-created across re-renders).

### Plan of action

- [x] Merge #56502
- [x] Work on a workaround for all `Button` components
    - [x] Try out the `key` method #56527
    - [x] Alternatively, understand if the solution proposed in #56490 is viable
- [x] Potentially undo previously added workarounds (like in #56502)
