### ISSUE TITLE
Epic: Interactivity API - public 1.0 version

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#56803]
- Part of #41236.

In [More core blocks and new `store()` API](https://github.com/WordPress/gutenberg/issues/53740), we first worked on preparing Core blocks for WP 6.4, including the new enhanced pagination of the Query block, and after the release of WP 6.4, we also worked on the migration of the new `store()` API.

For this iteration of the Interactivity API, we want to focus on the **preparation of a 1.0 version that can be released publicly in WordPress Core** and serve as the base for future enhancements. 

We also want to consolidate here the work of the [Tracking Issue: Server Directive Processing](https://github.com/WordPress/gutenberg/issues/55938) to keep all the implementation work under the same issue, but we will keep tracking the documentation-related tasks in the [Documentation Tracking Issue](https://github.com/WordPress/gutenberg/issues/53296).

### Tasks

This is the list of initial tasks, although we will edit this post as we progress and discover other things that we need to do.

- **Directives**
  - [x] Implement the `wp-run` directive
    - https://github.com/WordPress/gutenberg/discussions/51863
    - https://github.com/WordPress/gutenberg/pull/57805
  - [x] Expose the `useInit` and `useWatch` hooks
    - https://github.com/WordPress/gutenberg/pull/57805
  - [x] Add `data-wp-on-window` and `data-wp-on-document` directives
    - https://github.com/WordPress/gutenberg/pull/57931
  - [x] Remove the `navigation-link` directive
    - https://github.com/WordPress/gutenberg/pull/57853
  - [x] Remove the `wp-slot` and `wp-fill` directives if we don't finally need them
    - https://github.com/WordPress/gutenberg/pull/57854
  - [x] Prevent using components in `data-wp-text`, only strings
    - https://github.com/WordPress/gutenberg/pull/57879
  - [x] Remove support for element state until naming and use cases are clearer
    - https://github.com/WordPress/gutenberg/pull/57974
  - [x] Add support for element attributes
    - https://github.com/WordPress/gutenberg/pull/57974
  - [x] Update Preact to the latest version and remove the custom `role` logic in our codebase
    - https://github.com/WordPress/gutenberg/pull/57891
  - [x] Expose `withScope` and add support for async functions (generators)
    - https://github.com/WordPress/gutenberg/pull/58013
  - [x] Add support for `wp-each`
    - https://github.com/WordPress/gutenberg/pull/57859
  - [x] Put all the private exports behind a locked proxy
    - https://github.com/WordPress/gutenberg/pull/58496
  - [x] Remove the non-default `wp-context` suffix
    - https://github.com/WordPress/gutenberg/pull/58664
  - [x] Use `data-wp-interactive="namespace"`
    - https://github.com/WordPress/gutenberg/pull/58743
  - [x] Review the `@wordpress/interactivity` exports
    - https://github.com/WordPress/gutenberg/pull/58864
  - [x] Remove the `wp-body` directive
    - https://github.com/WordPress/gutenberg/pull/58835/
  - [x] **Fix**: Improve the way we merge contexts after navigation
    - https://github.com/WordPress/gutenberg/pull/59187
  - [x] **Fix**: Prevent proxifying non-plain objects
    - https://github.com/WordPress/gutenberg/pull/59039
- **Store**
  - [x] Re-implement `wp_store` as `wp_initial_state`
    - https://github.com/WordPress/gutenberg/pull/57556
  - [x] **Fix**: Merge new SSR state on client-side navigation ([discussion](https://github.com/WordPress/gutenberg/discussions/53056))
    - https://github.com/WordPress/gutenberg/pull/57134
- **Router**
  - [x] Create the `core/router` store and move the `navigate` and `prefecth` actions there 
    - https://github.com/WordPress/gutenberg/pull/57924
  - [x] Code-split the `core/router` store in `@wordpress/interactivity/router`
    - https://github.com/WordPress/gutenberg/pull/57924
  - [x] Rename `data-wp-navigation-id` to `data-wp-router-region`
    - https://github.com/WordPress/gutenberg/pull/58191
  - [x] Add a top loading bar on navigation
    - https://github.com/WordPress/gutenberg/pull/58377 
  - [x] Add a screen reader announcement on navigation
    - https://github.com/WordPress/gutenberg/discussions/55129
    - https://github.com/WordPress/gutenberg/pull/58377 
  - [x] Expose a way to trigger virtual pageviews, like `state.url` in the `core/router` store
    - https://github.com/WordPress/gutenberg/pull/58377 
  - [x] **Fix**: Fix the initial page cache ([code](https://github.com/WordPress/gutenberg/blob/92bd375239a7623f39fbae5012e8aa483918bed4/packages/interactivity-router/src/index.js#L78-L82))
    - https://github.com/WordPress/gutenberg/pull/58496
  - [x] ~Populate `state.url` from the server~
    - We finally decided to maintain the code that adds it from the `core/router` store in JS.
  - [x] Switch to global config `config['core/router'].regionNavigation = false`
    - https://github.com/WordPress/gutenberg/pull/58749
  - [x] **Fix**: Add `data-wp-key` to the page numbers
    - https://github.com/WordPress/gutenberg/pull/58189
- **Block metadata**
  - [x] Add `clientNavigation` and `interactive` to block supports metadata.
    - https://github.com/WordPress/gutenberg/pull/58132 
  - [x] Move block script module registration to the `render_callback` and use `wp_scripts_get_suffix`
    - https://github.com/WordPress/gutenberg/pull/58678
  - [x] Use private stores for all the interactive core block stores
    - https://github.com/WordPress/gutenberg/pull/58722 
- **Server Directive Processing**
  - [x] Make sure we only process the directives once
    - https://github.com/WordPress/gutenberg/pull/55739
  - [x] Sort directives by priority
    - https://github.com/WordPress/gutenberg/pull/56302
  - [x] Add support for `data-wp-interactive='{ "namespace": "..." }'`
    - https://github.com/WordPress/gutenberg/pull/57556
  - [x] Improve block identification (check the block name before the md5)
    - https://github.com/WordPress/gutenberg/pull/57556
  - [x] Render the root interactive blocks
    - https://github.com/WordPress/gutenberg/pull/57729
  - [x] Encapsulate everything into a single function `wp_interactivity_process_directives()`
    - https://github.com/WordPress/gutenberg/pull/58066
  - [x] Make sure it bails out on unbalanced tags
    - https://github.com/WordPress/gutenberg/pull/58066
  - [x] Add tests for edge cases
    - https://github.com/WordPress/gutenberg/pull/58066
  - [x] Add processor for `wp-each`
    - https://github.com/WordPress/gutenberg/pull/58498
  - [x] **Optional**: Add a helper function to add `data-wp-context` on PHP
    - https://github.com/WordPress/wordpress-develop/pull/5953
  - [x] **Optional**: Add support for private stores
    - https://github.com/WordPress/gutenberg/discussions/51596
    - https://github.com/WordPress/gutenberg/pull/58722
    - https://github.com/WordPress/gutenberg/pull/58754
  - [x] **Fix**: Skip SVG and MathML (instead of bail out)
     - https://github.com/WordPress/wordpress-develop/pull/6091 
- **Debug**
  - [ ] **Optional**: Show an error in the browser console when the server directive processing fails
    - https://github.com/WordPress/wordpress-develop/pull/5953#discussion_r1478777841'
- **Code Quality**
  - [ ] **Optional**: Typscript the entire runtime. Add comments to functions. Etc.
    - https://github.com/WordPress/gutenberg/pull/58718

**Comment by cbravobernal** [comment]
The[ directive processing of only interactive blocks is ready for review.](https://github.com/WordPress/gutenberg/pull/56302) I will add more tests during this week.

**Comment by felixarntz** [comment]
Related to the server-side directive processing and the above PR #56302, are there any plans to provide an API function that is decoupled from blocks? I think there are many use-cases (primarily classic "hard-coded" HTML in core, plugins, and themes) that could use the Interactivity API. If such use-cases could then call a simple function to process the directives on the HTML string, that would be really helpful.

Potentially the function `gutenberg_process_interactive_html()` introduced in #56302 could be what I'm looking for? As far as I can tell, the only block specific part is `$inner_blocks` which could be omitted?

**Comment by luisherranz** [comment]
@felixarntz yeah, we're still trying different things here. To be honest, I'm not very happy with the current approach. And as you say, it's quite coupled with blocks. 

I think we can simplify it to process only on the "root interactive blocks" and try to encapsulate everything in a single function. Maybe something like this that also classic themes could use:

```php
$html = do_interactivity( $html );
```

To do so, we need to get rid of all the things that depend on knowing which part of the HTML belongs to which block during the processing (like [private stores](https://github.com/WordPress/gutenberg/discussions/51596#discussioncomment-8024058)), but I think it's doable and it will simplify things.

What do you think?

**Comment by felixarntz** [comment]
Thanks @luisherranz, that sounds like a good plan to me. I have to admit, my understanding of private stores is quite limited still. But what you're saying sounds solid as far as I can assess.

Regarding a function name, I'd prefer to do away with the "do" prefix. While it's sort of common for some WP processing functions, I think it's also somewhat legacy. I would find something like `process_interactivity` or `parse_interactivity` or `parse_interactivity_directives` more suitable. But a function name is probably the last challenge in this 😆

**Comment by luisherranz** [comment]
Haha, sure. That's because I was thinking about `do_blocks`, but those names sound good to me. Let's see if we can condense everything into a single function 🙂

**Comment by cbravobernal** [comment]
Added a PR to render the root interactive blocks in Server Directives Processing. Ready to review!
 - https://github.com/WordPress/gutenberg/pull/57729

**Comment by DAreRodz** [comment]
I created a PR to implement the `data-wp-run` directive. I saw it convenient to include also the hooks `useWatch` and `useInit` in the same PR. Ready for review.

- https://github.com/WordPress/gutenberg/pull/57805

**Comment by luisherranz** [comment]
The PR with `wp_initial_state` was merged:

- https://github.com/WordPress/gutenberg/pull/57556

**Comment by cbravobernal** [comment]
Created two PRs that remove directives that are not being used:
 - https://github.com/WordPress/gutenberg/pull/57854
 - https://github.com/WordPress/gutenberg/pull/57853

I labeled them as breaking changes, in case some external developers have been using them.

**Comment by DAreRodz** [comment]
The `wp-run` directive implementation, the new `useWatch` and `useInit` hooks, and the scoped version of all callback-based hooks have been recently merged.

- https://github.com/WordPress/gutenberg/pull/57805

**Comment by cbravobernal** [comment]
Prevent using components in `data-wp-text` is ready for review:
- https://github.com/WordPress/gutenberg/pull/57879

**Comment by DAreRodz** [comment]
I'm currently working on the `data-wp-each` directive. Only the documentation needs to be included at this point.

- https://github.com/WordPress/gutenberg/pull/57859

I'll set the PR ready for review shortly.

**Comment by cbravobernal** [comment]
I'm currently working on the upgrade of the dependencies. ~~Is still draft, as needs some testing and I found the role in navigation is only appearing at the second click on the open button.~~ Working and merged.
 - https://github.com/WordPress/gutenberg/pull/57891

**Comment by cbravobernal** [comment]
Added a bugfix that @luisherranz spotted while discussing `wp-on-window` and `wp-on-document`.
- https://github.com/WordPress/gutenberg/pull/57925

**Comment by cbravobernal** [comment]
New directives `wp-on-window` and `wp-on-document` are ready for review:
 - https://github.com/WordPress/gutenberg/pull/57931

**Comment by getdave** [comment]
👋 Hello team. Whats the update on this feature for WP 6.5? Is it likely to land and if so which features (as originally outlined in [the roadmap](https://make.wordpress.org/core/2023/12/07/roadmap-to-6-5/)) will make it. Thanks in advance 🙏

**Comment by cbravobernal** [comment]
Added a PR to rename props to attributes and remove state from `getElement()`:
 - https://github.com/WordPress/gutenberg/pull/57974

**Comment by luisherranz** [comment]
> Whats the update on this feature for WP 6.5? Is it likely to land and if so which features (as originally outlined in the roadmap) will make it.

Hey Dave 👋 

The main addition is the server directive processing. I'm currently working on the backport. I'll open a couple of PRs tomorrow, one here in Gutenberg in the `/compat/wordpress-6.5` folder and another one in WordPress Core.

The rest of the features that require backports are optional, and it's not clear which ones we will finally include. We'll evaluate them next week and we'll let you know.

**Comment by cbravobernal** [comment]
Made a PR for "Expose `withScope` and add support for async functions (generators)"
 - https://github.com/WordPress/gutenberg/pull/58013

**Comment by luisherranz** [comment]
I did a refactor of the server directive processing logic that covers most of the remaining SDP tasks and is prepared to be backported into WordPress 6.5:

- https://github.com/WordPress/gutenberg/pull/58066

EDIT: @getdave, I'll open another PR in WordPress Core with these changes.

**Comment by getdave** [comment]
Thank you. If you're able to keep https://github.com/WordPress/gutenberg/issues/57959 updated that would be much appreciated 🙇

**Comment by luisherranz** [comment]
Small update here.

This is in really good shape now. We'll try to merge the new server directive processing refactor in time for GB 17.6. Apart from that:

- `wp-each`:
  - The client runtime is ready. The PR is not merged yet due to failing tests in `trunk`, but it should be available for GB 17.6.
  - I'll start working on the `wp-each` server processor.
- `@wordpress/interactivity/router` store
  - @darerodz is working on it, making good progress.
- Query block
  - We'll work on adding the top-loading bar animation and screen announcement to the `navigate` action.
  - We'll also move the `data-wp-navigation-disabled` directive to a global `core/router` config using the new `wp_interactivity_config` API.
  - We'll add `supports.clientNavigation` to the `block.json` schema and we'll update the Query block to check for `supports.clientNavigation`.
- We'll add `supports.interactivity` to the `block.json` schema.

The rest of the tasks are smaller details or optional items. We will keep working on them and reporting here.

**Comment by cbravobernal** [comment]
> - We'll add supports.interactivity to the block.json schema.
 
 Once tests passed it will be ready to review.
 - https://github.com/WordPress/gutenberg/pull/58132

**Comment by DAreRodz** [comment]
I created a PR to move all the router-related code to its own module and package. Awaiting tests to be merged.

- https://github.com/WordPress/gutenberg/pull/57924

**Comment by DAreRodz** [comment]
I've also created another one to rename the `data-wp-navigate-id` directive to `data-wp-router-region`.

- https://github.com/WordPress/gutenberg/pull/58191

**Comment by DAreRodz** [comment]
I've opened a new PR to move all the logic related to the ARIA live region and the loading bar from the Query block to the Interactivity Router. Ready for review.

- https://github.com/WordPress/gutenberg/pull/58377

**Comment by Tropicalista** [comment]
Can someone please clarify what is the name of the function for a default store in PHP?

In previous release was `wp_store`, then changed to `wp_initial_state`. Now it seems it's renamed to `wp_interactivity_state`. 

Can we please specify this in docs as well?

https://github.com/WordPress/gutenberg/issues/58436

**Comment by luisherranz** [comment]
@Tropicalista: yes, we've renamed the function. I'll make a PR to update the docs once GB 17.6 is released with the final name.

Please follow the [changelog and breaking changes](https://github.com/WordPress/gutenberg/discussions/52906) discussion to get the latest updates on how the API evolves.

**Comment by DAreRodz** [comment]
I have opened a draft PR to fix the initial page cache in the `@wordpress/interactivity-router` module.

- https://github.com/WordPress/gutenberg/pull/58496

**Comment by luisherranz** [comment]
I opened a PR that adds a server processor for `data-wp-each`:

- https://github.com/WordPress/gutenberg/pull/58498

**Comment by luisherranz** [comment]
Small update. 

- The last two server directive processors (`data-wp-each` and `data-wp-router-region`) have been merged. 
- The `navigate` function now triggers the loading bar and screen reader announcement by default.
- 

Remaining tasks:

- Query block: switch from `data-wp-navigation-disabled` to `config['core/router'].clientNavigation = false`
- Image block: see if we can remove the `data-wp-body` directive.
- Other small tweaks.

**Comment by cbravobernal** [comment]
I added two more PRs:
 - https://github.com/WordPress/gutenberg/pull/58678
 - https://github.com/WordPress/gutenberg/pull/58664

**Comment by cbravobernal** [comment]
Added a PR with some small changes in comments. And refactors to TS.
- https://github.com/WordPress/gutenberg/pull/58718

**Comment by DAreRodz** [comment]
I've created a PR to make all core block stores private.

- https://github.com/WordPress/gutenberg/pull/58722

It includes a bugfix that solves a problem with the async initialization of private stores.

**Comment by luisherranz** [comment]
I've opened a PR to support `data-wp-interactive="myPlugin"`.

- https://github.com/WordPress/gutenberg/pull/58743

**Comment by DAreRodz** [comment]
Here, a draft PR that implements global configs in the JS runtime:

- https://github.com/WordPress/gutenberg/pull/58749/

It also gets rid of the `data-wp-navigation-disabled` attribute we were adding to Query blocks when they contain unsupported blocks. Instead, a property `clientNavigation` inside the `core/query` config is used.

EDIT: the PR is ready for review now.

**Comment by DAreRodz** [comment]
I have updated the task list to mark "Populate `state.url` from the server" as complete, explaining that we decided not to implement that and keep the logic that initializes it from JS in `@wordpress/interactivity-router`.

**Comment by DAreRodz** [comment]
This PR limits the exposed API from `@wordpress/interactivity`:

- https://github.com/WordPress/gutenberg/pull/58864

**Comment by luisherranz** [comment]
I opened a PR to remove the `data-wp-body` directive and refactor the Image block to add the overlay using `wp_footer` instead:

- https://github.com/WordPress/gutenberg/pull/58835

**Comment by mtias** [comment]
Regarding one meta aspect of how we communicate this functionality more broadly, I think **Interactivity API** is ok as the technical aspect for developers, but when we talk broadly about what it does I think we should refer to it as **Interactions**. Interactions is the feature, and it's powered by this new developer API.

So similar to `block API -> blocks` we'll have `interactivity API -> interactions`. I find that clearer and easier than `interactivity` on its own, but curious what others think. I don't believe this has any material considerations on namespace issues at the code level, except perhaps the possibility of renaming the entry package to `@wordpress/interactions`.

**Comment by ajgagnon** [comment]
> Regarding one meta aspect of how we communicate this functionality more broadly, I think **Interactivity API** is ok as the technical aspect for developers, but when we talk broadly about what it does I think we should refer to it as **Interactions**. Interactions is the feature, and it's powered by this new developer API.
> 
> So similar to `block API -> blocks` we'll have `interactivity API -> interactions`. I find that clearer and easier than `interactivity` on its own, but curious what others think. I don't believe this has any material considerations on namespace issues at the code level, except perhaps the possibility of renaming the entry package to `@wordpress/interactions`.

This would need careful consideration, for sure. Having 2 names for the same functionality can also make things less clear in some cases. There is currently this issue with people referring to the "WordPress Block Editor" as "The Gutenberg Editor". Maybe `interactivity API -> interactivity"? Just a thought.

**Comment by cbravobernal** [comment]
Added a PR to fix directives not being processed if the HTML contained a SVG or a MATH.
 - https://github.com/WordPress/wordpress-develop/pull/6091

**Comment by fabiankaegy** [comment]
Now that we are past the Beta 1 cut off point I'm removing this tracking issue from the 6.5 Project board. From now on the board should only contain individual bugs that we want to still fix before 6.5 gets released.

**Comment by gziolo** [comment]
Should we also close the issue an open separate issues for remaining tasks so those applicable can be put on the 6.5 board and tackled before 6.5 Beta 3 scheduled for Tuesday next week?

**Comment by cbravobernal** [comment]
I will miss this tracking issue 😅, but yep, I will do that.
