### ISSUE TITLE
Tracking further improvements to Layout support

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#57571]
Follows #44720. Now that layout support is stable, focus is shifting to UI improvements for a more intuitive experience and adding new features, especially for flex and grid types.

## UI improvements

* [ ] https://github.com/WordPress/gutenberg/issues/42385
* [x] https://github.com/WordPress/gutenberg/issues/13202
* [x] https://github.com/WordPress/gutenberg/issues/49272
* [x] https://github.com/WordPress/gutenberg/issues/47902
* [ ] https://github.com/WordPress/gutenberg/issues/46128
* [x] https://github.com/WordPress/gutenberg/issues/44560
* [x] https://github.com/WordPress/gutenberg/issues/43218

## New features

* [ ] https://github.com/WordPress/gutenberg/issues/43248 (tracks container blocks that don't yet support layout but could do so)
* [ ] https://github.com/WordPress/gutenberg/issues/57478
* [ ] https://github.com/WordPress/gutenberg/issues/27629 (perhaps not so much extending the current toolbar, but providing extra functionality as part of layout support)
* [x] https://github.com/WordPress/gutenberg/issues/16271
* [x] https://github.com/WordPress/gutenberg/issues/57186
* [x] https://github.com/WordPress/gutenberg/issues/53766 (there should be a way to actually set a fixed width on flex children)
* [ ] https://github.com/WordPress/gutenberg/issues/42240 (this could leverage the grid layout type)
* [ ] https://github.com/WordPress/gutenberg/issues/37124 (allow setting content and wide widths per-block in global styles)

## Bugs and code quality improvements

* [ ] https://github.com/WordPress/gutenberg/issues/57242
* [ ] https://github.com/WordPress/gutenberg/issues/52099
* [ ] https://github.com/WordPress/gutenberg/issues/41260
* [ ] https://github.com/WordPress/gutenberg/issues/40159

This is not an exhaustive list but means to track the highest priority features. I'll be following up with some triage to the layout label and may add a list of bugs in the next few days. Feel free to add and edit as needed!

**Comment by bph** [comment]
Today, during Extensibility Issue Triage meeting, we picked up on this issue: 
- https://github.com/WordPress/gutenberg/issues/10791

Would this be a good issue to add to the list of layout support improvements? It's not just a problem for columns, also Gallery block could use a maxColumns theme.json setting or something...

**Comment by tellthemachines** [comment]
@bph thanks for bringing it up here! It's an interesting issue but unrelated to the layout support. That's unfortunate because it would be easier to fix if it were just a matter of adding a `maxColumn` setting to layout 😅 but each of those blocks have their own custom layout implementations controlling the number of columns so I'm afraid solution will also have to be a custom one.

**Comment by tellthemachines** [comment]
Closing as most issues have been addressed here. Follow up in #81767. Thanks everyone!
