### ISSUE TITLE
Renaming UI doesn't work for some blocks

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#57954]
## What problem does this address?

Renaming UI is now available for almost all blocks. However, in some blocks where `__experimentalLabel` is opted in, I found that the label entered in this UI is not reflected in the list view.

For example, a paragraph block returns a custom label if the context is `list-view`.

https://github.com/WordPress/gutenberg/blob/8b5bc0e22480d9001d43f29b30e2c781dae8d221/packages/block-library/src/paragraph/index.js#L33-L35

On the other hand, in the Image block, there is [no process](https://github.com/WordPress/gutenberg/blob/8b5bc0e22480d9001d43f29b30e2c781dae8d221/packages/block-library/src/image/index.js#L31-L47) to return a custom label in the case of `list-view` context.

## What is your proposed solution?

We need to resolve this issue in blocks that have opted in to `__experimentalLabel` and where `supports.renaming` is not `false` in `block.json.`

As far as I've researched, the problem needs to be resolved in the following blocks:

- [x] Image (core/image) #57955
- [x] More (core/more) #58160
- [x] Submenu (core/navigation-submenu): This block displays the text entered in the label field in a list view. If any text is entered in the rename UI, like the heading block, it should overwrite the text in the list view. #58296

On the other hand, we shouldn't need to do anything with the following blocks.

- ✅ Heading (core/heading): Works correctly
- ✅ Paragraph (core/paragraph): Works correctly
- ⚠️ Page List Item (core/page-list-item): This is the child block when you insert the Page List block. It will be displayed in the list view, but when you click on the block, a modal will be displayed to convert it to a link. Since the block sidebar cannot be operated, there is virtually no need to fix it.
- ⚠️ Unsupported (core/missing): If a block is broken, nothing will be displayed in the block sidebar. Therefore, there is virtually no need to fix it.

**Comment by annezazu** [comment]
@getdave as a heads up based on your work here. Adding this to 6.5.

**Comment by getdave** [comment]
@t-hamano Thank you for spotting these and following up.

**Comment by merijnponzo** [comment]
Does this already work with custom blocks?

I added 
```
 "renaming": true,
 ```
 To my custom block.json within the block.json **support** object
I also added:
```
 "metadata":{
      "type": "object",
      "default": {
        "name": "Test"
      }
    }
```
to my block.json **attributes** object but no rename field shows up.

Only when i add :
```
"__experimentalMetadata": true
```
to my block.json i see the name field when selecting my block, but the name doesn't appear in the list view

Thank you

**Comment by getdave** [comment]
@merijnponzo Could you please post information about how you are testing this? For example is the Gutenberg Plugin enable (version) and which version of WP. Many thanks

**Comment by merijnponzo** [comment]
@getdave sorry i can confirm this works with 6.5
Since i'm using worpdress Bedrock i realised i was still testing with 6.4 so i copied the files manually and now it works

without using:
```
 "__experimentalBlockRenaming":true,
    "__experimentalMetadata":true
```
and only
```
"renaming": true
```
I am not sure if i still have to add:
```
"metadata":{
      "type": "object",
      "default": {
        "name": "Test"
      }
    }
```
To my block.json


Great work!

**Comment by getdave** [comment]
By default all blocks have renaming support so you shouldn't need to do anything.

Please see https://github.com/WordPress/gutenberg/pull/54426#issuecomment-1927069908.

**Comment by dannyreaktiv** [comment]
For a custom block, I was using just `"renaming": true` in 6.4, and now it isn't working in 6.4.3. Is there any more documentation I could look at?

**Update** Same code _does_ work in 6.5 RC1… guess I just gotta wait a little bit.

**Comment by t-hamano** [comment]
@dannyreaktiv 

Rename support varies by WordPress version.

- WP6.4: Only group block supports renaming. The rename UI is displayed for all blocks, this is an unintended bug.
- WP6.4.3: The rename UI that was displayed unintentionally has been fixed. ([#55995](https://github.com/WordPress/gutenberg/pull/55995))
- WP6.5: Most core blocks and custom blocks support renaming UI. Rename defaults to `true`.
