### ISSUE TITLE
DataViews: Group by field

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#57967]
<img width="1716" alt="Grouping" src="https://github.com/WordPress/gutenberg/assets/846565/7f717ec1-41d9-469a-8479-a8d726b59ac0">

Allowing users to group by field can be useful, and would enable us to more closely replicate the current templates list:

<img width="285" alt="Screenshot 2024-01-18 at 13 30 20" src="https://github.com/WordPress/gutenberg/assets/846565/4dccefd2-392a-47b0-bb11-d51b59688683">

## Tasks

- [x] Grid layout https://github.com/WordPress/gutenberg/pull/70752
- [x] Table layout https://github.com/WordPress/gutenberg/pull/71055
- [x] List layout https://github.com/WordPress/gutenberg/pull/71548
- [ ] UI to enable users to change how and whether the data is grouped by.
- [ ] Make groups collapsible.
- [ ] Allow fields to provide a groupBy function or similar. The goal is to enable custom groupings. For example, when grouping by date, we may want to group by "yesterday/last week/last month" rather than the specific field date ([example](https://github.com/WordPress/gutenberg/pull/70752#issuecomment-3083891010)).

**Comment by tyxla** [comment]
@jameskoster I was looking at #70752 and wondering if we also [wondered](https://github.com/WordPress/gutenberg/pull/70752#pullrequestreview-3037555262) about supporting the table view. Is this something we've considered?

**Comment by oandregal** [comment]
@tyxla yeah, it is. ~There are some mockups somewhere (can't find them now 😅 ) about that.~

**Edit**: there's a mockup for each view type in the OP.

**Comment by jameskoster** [comment]
Not a high-priority item, but it might be neat to allow groups to be collapsible.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/71548 adds support for `groupBy` in the list layout.

**Comment by oandregal** [comment]
@jameskoster thinking about next steps here. All layouts implemented support for group by. Is there anything else to do for WordPress 6.9? Do we need the group by config to be configurable by the user, for example?

**Comment by jameskoster** [comment]
I think that would be nice to have, yes. Unsure if it's a requirement for 6.9 though?

**Comment by t-hamano** [comment]
Let's add this issue to the 6.9 Editor Tasks board just to be sure.

**Comment by ryanwelcher** [comment]
This was reviewed in the 6.9 Bug Scrub today. We're 1 week from the Beta 1 cutoff and there has been no movement on this issue so I am going to punt it to 7.0.

Please comment if I am mistaken to do so :)

**Comment by youknowriad** [comment]
I'm not sure a UI to configure this is needed at the moment. Let's close and reopen later if the need for it becomes more clear.
