### ISSUE TITLE
Aspect ratio block support: Follow-up tasks

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#58230]
This is a small issue to track follow-up tasks associated with the aspect ratio block support that landed in #56897.

## Short-term To-do

* [x] Backport PHP code for the block support (Core PR: https://github.com/WordPress/wordpress-develop/pull/5963)
* [x] When updating aspect ratio in the Cover block, see if we can reset / clear the value for the Cover block's ad hoc minimum height control (so that it's clear to a user that the aspect ratio overrides the minimum height) — PR: https://github.com/WordPress/gutenberg/pull/59191
* [ ] The aspect ratio dropdown displays _Original_ as the selected item both when there is no aspect ratio set on the block _and_ when the aspect ratio is explicitly set to `auto`. The default / unset state should be clearer. In terms of labelling, one idea would be to use the word `Auto` in all cases as suggested in this comment: https://github.com/WordPress/gutenberg/pull/56897#issuecomment-1907636143
* [ ] https://github.com/WordPress/gutenberg/issues/60224
* [ ] https://github.com/WordPress/gutenberg/issues/60922

## Longer term (for discussion and possibly to open separate issues)

* [ ] See which other blocks can use the block support rather than an ad hoc aspect ratio control — this way the controls are more consistent between blocks, and we can opt other blocks in to using aspect ratio in global styles. For example, what would be involved in converting the Featured Image block to use the block support?
* [ ] Which panel does aspect ratio best belong in? It would ultimately be good for it to be in a consistent place across all blocks.
* [ ] https://github.com/WordPress/gutenberg/issues/61326
* [ ] https://github.com/WordPress/gutenberg/issues/60224

## Tracked elsewhere

* https://github.com/WordPress/gutenberg/issues/47962
* https://github.com/WordPress/gutenberg/pull/47271

**Comment by eric-michel** [comment]
@andrewserong Could you include [this issue](https://github.com/WordPress/gutenberg/issues/60922) in your follow-up tasks list? I see that the Aspect Ratio Control is being folded into a lot of other blocks, including the Group and Image blocks. If inline styles eliminating `aspect-ratio` start getting added to every Group and Image block even when the control is not used, it would be catastrophic for us. 

I am very worried that a future WP update will break large portions of sites we have in production. We use `aspect-ratio` in our theme CSS to target Cover, Group, and Image blocks regularly. We've already had to fix all of our Cover block aspect ratio CSS, and we use Cover blocks the least out of those three.

**Comment by andrewserong** [comment]
Thanks for calling that out, I've added it to the list. That behaviour was introduced to remove any aspect ratio that might have been set in global styles, and it didn't factor in that themes might be setting `aspect-ratio` intentionally via a classname.

I currently don't have scope to work on this particular block support right now, but feel free to pick this up if anyone else is interested in contributing in this area. For now, as mentioned in #60922, a workaround would be to ensure that theme CSS that intends to override it has a higher specificity, though I'm aware that's not an ideal long-term solution.
