### ISSUE TITLE
Add e2e tests for "MetaBoxes: Fix meta boxes toggling"

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#5909]
It would be helpful to have e2e tests for #5902. However, doing so requires:

* [ ] Producing a custom plugin that recreates the issue.
* [ ] Figuring out how to get the plugin onto the Docker filesystem.
* [ ] Writing aforementioned tests.

See conversation in https://wordpress.slack.com/archives/C02QB2JS7/p1522418894000176

Related #5906

**Comment by danielbachhuber** [comment]
Punting on this. It's low priority in the grand scheme of things.
