### ISSUE TITLE
Advancing site editor index views

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#59659]
Related https://github.com/WordPress/gutenberg/issues/55083 https://github.com/WordPress/gutenberg/issues/53322

## What problem does this address?
As part of the [admin track of work](https://github.com/WordPress/gutenberg/issues/53322) we want to start adopting some of the new UX paradigms within the site editor index views. 

https://github.com/WordPress/gutenberg/assets/1072756/8fe4bd09-694c-44d7-b9a9-c91d6c87d56c

Pages and templates within the site editor currently drill-down the navigation sidebar showing a list of records, but what we want to work towards is always using the "content frame" for lists, including the "side by side" layout type which lets you quickly preview posts before editing. This also solves the weird "manage pages" and "manage templates" links that currently exist. The goal of this work is bring those "manage" pages forward so they are visible when visiting /pages or /templates, much like /patterns.

### Site editor responsiveness

- [ ] https://github.com/WordPress/gutenberg/issues/60847

### Replace current pages with manage pages
Replace the existing pages view that shows pages in sidebar and update with the "manage pages" view. For this piece of work we can keep the "custom views" as experimental.

Old
<img width="1512" alt="image" src="https://github.com/WordPress/gutenberg/assets/1072756/e4185722-2c11-406e-ba48-6590ae72a32a">

New
<img width="1512" alt="image" src="https://github.com/WordPress/gutenberg/assets/1072756/2a087496-e970-4423-a3d1-9d19c074a176">

Criteria:

- [x] Clicking "pages" in top level navigation opens pages data views with "side by side" layout type enabled by default. https://github.com/WordPress/gutenberg/pull/59950
- [x] Default views for pages include [All, Published, Draft, Scheduled, Utility, Trash] https://github.com/WordPress/gutenberg/pull/62021
- [ ] Pages: "Trash" view should default to `table` layout
- [ ] https://github.com/WordPress/gutenberg/issues/60772
- [ ] https://github.com/WordPress/gutenberg/issues/41716
- [x] When in side by side layout, clicking an item previews in the frame on right.
- [x] Clicking the frame expands into edit mode
- [x] Each item in side by side has an "edit" icon that expands frame into edit mode
- [x] Each item in side by side has an ellipsis icon that triggers page actions [Delete, rename, edit]
- [x] When in table view, clicking a page title should open editor
- [x] Mobile: show the content frame. https://github.com/WordPress/gutenberg/pull/60409
- [x] https://github.com/WordPress/gutenberg/issues/57763

### Replace current templates with manage pages
Much like pages, we want to do the same for templates.

Old
<img width="1512" alt="image" src="https://github.com/WordPress/gutenberg/assets/1072756/2082239f-fec2-46d3-9ed2-be423bda0f93">

New
<img width="1512" alt="image" src="https://github.com/WordPress/gutenberg/assets/1072756/4e83ee3c-d2b6-4789-b2c1-059ff0bfed40">

Criteria:

- [x] Clicking "templates" in top level navigation opens templates data views with "grid" layout type enabled by default. https://github.com/WordPress/gutenberg/pull/59792
- [x] Use grid layout by default with loading indicator. https://github.com/WordPress/gutenberg/pull/60069
- [x] Clicking template name in table view opens editor
- [ ] Custom views for templates include default views [All, pages, posts, utility, custom] https://github.com/WordPress/gutenberg/pull/62075
- [x] When in side by side layout, clicking an item previews in the frame on right.
- [x] Clicking the frame expands into edit mode
- [x] Each item in side by side has an "edit" icon that expands frame into edit mode
- [x] Each item in side by side has an ellipsis icon that triggers templates actions

### Updates patterns to remove template parts management

The current patterns page makes use of the new data views but we still have a "manage template parts" link. We should aim to remove that link and bring the missing functionality over to the patterns view.

Criteria:

- [x] Clicking patterns in top level opens current patterns page
- [x] The template parts group that currently sits _below_ pattern categories should be moved to the top https://github.com/WordPress/gutenberg/pull/60359
- [x] "Manage template parts" link should go away https://github.com/WordPress/gutenberg/pull/60689
  - [x] https://github.com/WordPress/gutenberg/pull/60667
  - [x] https://github.com/WordPress/gutenberg/pull/60659
  - [x] https://github.com/WordPress/gutenberg/pull/60372
  - [x] https://github.com/WordPress/gutenberg/pull/60775
- [x] "Manage all my patterns" should go away https://github.com/WordPress/gutenberg/pull/60345
- [x] "Table" layout type should be added to patterns data views https://github.com/WordPress/gutenberg/pull/60337
  - [ ] https://github.com/WordPress/gutenberg/issues/61245
- [x] Clicking a pattern in table view should open editor https://github.com/WordPress/gutenberg/pull/60337
- [ ] Consolidate Patterns & Template Parts categories ([comment](https://github.com/WordPress/gutenberg/pull/60689#issuecomment-2071970132)):
  - "All patterns" view should include template parts (probably the most challenging part).
  - The separate menus should ideally converge ([mockup](https://github.com/WordPress/gutenberg/issues/57011#issuecomment-1972878319)).
  - We need to settle on a more intuitive name for the "General" category.
  - Align or differentiate the "Header" + "Headers" categories.
  - Update the creation flow ([mockup](https://github.com/WordPress/gutenberg/issues/57011#issuecomment-2023173050)).

**Comment by youknowriad** [comment]
Thanks for opening this issue, these are some nice flows.

>  Left sidebar remains at the top level with "templates" selected UNLESS "custom views" experiment is enabled

I think this one is going to be challenging to pull off, I'd navigate to "custom views" (or default views if the experiment is disabled) on the first iteration. We'd need stronger routing to be able to stay in the top view in the sidebar while navigating to templates.

>  "Manage template parts" link should go away

This item is also to be addressed with care, currently the patterns list view doesn't show "template parts", so it might mean "merging them", adding fields to filter one or the other... It might require its own issue for clarity.

**Comment by oandregal** [comment]
Index for templates https://github.com/WordPress/gutenberg/pull/59792

@SaxonF the screenshot for templates uses the table layout, though the texts mentions grid layout. Which one should be the default? The PR uses the existing (table).

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/59858 makes the `list` layout stable, so it becomes available for Pages, Templates, and Parts without the experiment enabled.

**Comment by oandregal** [comment]
Updates index for pages https://github.com/WordPress/gutenberg/pull/59950

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60069 explores using `grid` layout for templates.

**Comment by annezazu** [comment]
Adding the tracking label to this as it tracks work across the experience and is part of the [broader Overview issue of Data Views](https://github.com/WordPress/gutenberg/issues/55083) and Admin Redesign.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60337 enables `table` layout for patterns.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60345 removes "Manage all of my patterns" link.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60359 looks at template parts in patterns (needs feedback on target design).

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60409 to display the content frame for Pages in mobile.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60372 adds the author field & filter to the template parts in the Patterns page.

**Comment by getdave** [comment]
I'm wondering if any of this work should/could be extended to the `Navigation` (Menus) section? 


In the past, we've received feedback that users would like to be able to _edit_ (including ability to create) menus within the sidebar but I'm not sure that (especially editing) fits with the new UX paradigm outlined here.

Questions:

1. Do we see `Navigation` making use of these new data views?
2. Do we think Navigation Menus should be partially editable from these views, and if so how would that work?

**Update:** I noticed in https://github.com/WordPress/gutenberg/issues/53322 there is a UI (see `Example of the "drill down"` below) which allows for drill down into individual entities from the "List" layout. This drill down could expose the UI for editing the Navigation Menu.

<details>
<summary>Example of the "drill down"</summary>
<img width="1524" alt="Screen Shot 2024-04-10 at 10 56 43" src="https://github.com/WordPress/gutenberg/assets/444434/cdd5a86b-8eb6-4872-b430-922586709a0c">
</details>


Also I notice the term "Navigation" is being used a lot to described moving through "stacks" in the UI. That's fine, but just noting we may need to be careful to distinguish menus by referring to them as "Navigation Menus".

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60659 adds `edit` and `viewRevision` actions to parts in Patterns page.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60667 sets the backPath for Template Parts to the Patterns page.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60689 removes the "Manage all parts" link, page, and code.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60775 adds a "All template parts" section in the Patterns sidebar. It's a pre-requisite for https://github.com/WordPress/gutenberg/pull/60689.

**Comment by oandregal** [comment]
There's been a lot of activity in the Patterns screen and we're almost there: https://github.com/WordPress/gutenberg/pull/60689 removes the "Manage template parts" link and old code. After this one lands, I'm focusing a bit on the DataViews component again – improving the list layout with actions, etc.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60689 has landed and all listed tasks for Patterns are implemented. It's been a bit more involved than expected, and there's probably other things we need to polish now that this is ready.

Next, I'm planning to look at the task related to the `DataViews` component (list layout).

**Comment by SaxonF** [comment]
I wanted to highlight [this issue](https://github.com/WordPress/gutenberg/issues/60847) because although it is not directly tied to data views it does become more important to solve after we've added the new 3 column layout. Once we close this work out, and [the inspector](https://github.com/WordPress/gutenberg/issues/59689), we should follow it up with responsive changes.

**Comment by oandregal** [comment]
Based on @jameskoster comment, I've added some more tasks for consolidating Patterns/Parts:

> Consolidate Patterns & Template Parts categories (https://github.com/WordPress/gutenberg/pull/60689#issuecomment-2071970132):
> - "All patterns" view should include template parts (probably the most challenging part).
> - The separate menus should ideally converge (https://github.com/WordPress/gutenberg/issues/57011#issuecomment-1972878319).
> - We need to settle on a more intuitive name for the "General" category.
> - Align or differentiate the "Header" + "Headers" categories.
> - Update the creation flow (https://github.com/WordPress/gutenberg/issues/57011#issuecomment-2023173050).

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/60805 landed adding "edit" & "all actions" buttons in list layout for all index views that support it (pages, templates).

**Comment by oandregal** [comment]
Update on my availability for this: I have some upcoming AFK in a few days and won't be able to be back at this until the week of the 27th.

**Comment by jameskoster** [comment]
In case anyone is able to pick up the work here in @oandregal's absence, it would be really great if the following could be closed out for 6.6:

* https://github.com/WordPress/gutenberg/issues/57763
* https://github.com/WordPress/gutenberg/issues/60772
* https://github.com/WordPress/gutenberg/issues/58198
* https://github.com/WordPress/gutenberg/issues/60477
* https://github.com/WordPress/gutenberg/issues/60457
* https://github.com/WordPress/gutenberg/issues/56199

Most of them are small adjustments, so hopefully we can get it done 🤞

**Comment by oandregal** [comment]
> Pages data view: clarify 'Date' field

PR at https://github.com/WordPress/gutenberg/issues/60477

**Comment by oandregal** [comment]
> Pages data view: Update title field so that homepage and posts page are marked with a badge

PR at https://github.com/WordPress/gutenberg/pull/61718

**Comment by oandregal** [comment]
> custom views for pages include default views [All, Published, Draft, Scheduled, Utility, Trash]

https://github.com/WordPress/gutenberg/pull/62021 adds the missing Published & Scheduled items.

I've left "Utility" out. I presume it's related to [this discussion](https://github.com/WordPress/gutenberg/issues/60772) about "utility pages", for which there's an ongoing conversation — it can be addressed separately.

**Comment by oandregal** [comment]
> Custom views for templates include default views [All, pages, posts, utility, custom]

https://github.com/WordPress/gutenberg/pull/62075 addresses the preliminary steps to implement the above: it adds the `postType` & `isCustom` fields & filters to the templates page.

**Comment by jameskoster** [comment]
Most of the items here have been addressed, so I think we can close this one out.

I've tracked any relevant outstanding items in a new tracking issue for 6.7: https://github.com/WordPress/gutenberg/issues/63128
