### ISSUE TITLE
DataForm component

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#59745]
This document keeps track of all the work and tasks to build a powerful DataForm component capable of rendering all kind of forms and panels used to edit data. Document inspector in the editor, quick edit panels, settings forms...

DataForm is based on the same Fields abstraction that powers the [DataViews component](#55083) and support grouping fields, layouts, label positioning, conditional rendering, validation.

<img width="544" height="489" alt="Image" src="https://github.com/user-attachments/assets/85d4ad54-f1ac-4e67-a848-aff6b277b3f3" />

## Tasks

- [x] https://github.com/WordPress/gutenberg/pull/63032
- [x] https://github.com/WordPress/gutenberg/pull/63600
- [x] https://github.com/WordPress/gutenberg/pull/63840
- [x] https://github.com/WordPress/gutenberg/pull/63895
- [x] https://github.com/WordPress/gutenberg/pull/63983
- [x] https://github.com/WordPress/gutenberg/pull/64164
- [x] https://github.com/WordPress/gutenberg/pull/64168
- [x] https://github.com/WordPress/gutenberg/issues/64519
- [x] https://github.com/WordPress/gutenberg/issues/66338
- [x] Layout flexibility https://github.com/WordPress/gutenberg/pull/66531

## Next Steps

- [x] Implement Form Validation tools
- [ ] Strong conditional rendering
- [x] Grouping fields in cards, tabs, field sets (needs design)
- [ ] https://github.com/WordPress/gutenberg/issues/65685

## Low priority

- [ ] https://github.com/WordPress/gutenberg/issues/66616
- [ ] https://github.com/WordPress/gutenberg/issues/66336
- [ ] https://github.com/WordPress/gutenberg/issues/66332

**Comment by joshuatf** [comment]
@youknowriad @oandregal Out of curiosity, will the DataForm ever allow control over layout within a form (columns, tabs, sections, etc) or would those be comprised of multiple DataForms?

**Comment by youknowriad** [comment]
@joshuatf My current thinking is that "columns" and "tabs" are something you should be able to control on the `form` object. It's not clear to me at this point if a single "form type" can absorb everything or if we'd need several "form layouts" or "form types" like we have for data views, but I think we should be able do say, I want to group these fields in a tab...

**Comment by jameskoster** [comment]
Noting this is closely related to https://github.com/WordPress/gutenberg/issues/63624.

**Comment by oandregal** [comment]
Added a new section in the issue for "Task/Log".

Also: created https://github.com/WordPress/gutenberg/pull/63895 that prepares the initial structure for validation.

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/63983 adds the ability to update the author in the quick edit form.

**Comment by oandregal** [comment]
In https://github.com/WordPress/gutenberg/pull/63983 I ran into some issues with sorting. While working on them we discussed the need to formalize a bit the existing field types. This is the ongoing work:

- https://github.com/WordPress/gutenberg/pull/64064
- https://github.com/WordPress/gutenberg/pull/64164
- https://github.com/WordPress/gutenberg/pull/64168
- https://github.com/WordPress/gutenberg/pull/64171

**Comment by oandregal** [comment]
Edited a bit the issue description, including updating the issue title to `DataForm component`, like we have the [DataViews component](https://github.com/WordPress/gutenberg/issues/55083).

Also added some new tasks:

> - [ ] https://github.com/WordPress/gutenberg/issues/65685
> - [ ] Sync edits
>   - [ ] When user edit the title in the editor and then visit Pages, both the DataViews and QuickEdit should have the new title.
>   - [ ] When users edit the title via QuickEdit, DataViews should reflect the new title immediately. If the users visit the Editor at that point, they should also see the new title.

**Comment by gigitux** [comment]
Edited a bit the issue description, adding some issues that we opened in the last weeks. I hope that it is fine!

cc @youknowriad @oandregal @louwie17

**Comment by youknowriad** [comment]
@oandregal Same here, should we close this issue?

**Comment by oandregal** [comment]
@youknowriad I just took a look, and this one is showing its age. I've been more focused on maintaining the [iteration issue](https://github.com/WordPress/gutenberg/issues/70936) up to date to current work. Let's close this one.
