### ISSUE TITLE
Consolidate BlockSelectionButton toolbar

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#60124]
We currently have two cases of the `BlockSelectionButton` toolbar: a variant when select mode is engaged and an alternative when zoom out (https://github.com/WordPress/gutenberg/issues/50739)  is engaged. 

The key difference between both is that select mode enables you to select blocks of any depth, while zoom out (will) enable you to only select the top-level blocks. The experiences are otherwise quite similar across both—and may even end up merging at some point anyhow, so let's consolidate ahead of time. 

### Tasks

- [ ]  https://github.com/WordPress/gutenberg/issues/59961
- [ ] https://github.com/WordPress/gutenberg/issues/60126
- [ ] https://github.com/WordPress/gutenberg/issues/60121
- [ ] https://github.com/WordPress/gutenberg/issues/60125

### Select mode
In select mode, there is the block icon, drag control, and block name:

![CleanShot 2024-03-22 at 12 12 05](https://github.com/WordPress/gutenberg/assets/1813435/96e25a62-9530-4492-9278-d923ee269ee6)

### Zoom out mode

In zoom out mode (when selecting a top-level block), there is the block icon, mover controls, shuffle icon, block name: 

![CleanShot 2024-03-22 at 12 13 22](https://github.com/WordPress/gutenberg/assets/1813435/84a5679f-b333-40b6-8ef3-ab9aaf083443)

### Proposal 

Let's have consistent use of block icon, drag, movers, then extra actions—such as shuffling when supported by the block, and a [delete control](https://github.com/WordPress/gutenberg/issues/60121). 

![CleanShot 2024-03-22 at 12 25 23](https://github.com/WordPress/gutenberg/assets/1813435/ebc49746-1e83-4526-b89b-92995a289064)

It's worth noting that this may become the zoomed-out vertical toolbar for zoomed out mode (and perhaps both, if the modes are combined) (https://github.com/WordPress/gutenberg/issues/59737).

**Comment by draganescu** [comment]
> It's worth noting that this may become the zoomed-out vertical toolbar for zoomed out mode

I think this bit makes it so that we should _not_ consolidate.

**Comment by richtabor** [comment]
> I think this bit makes it so that we should not consolidate.

I'm thinking this vertical toolbar may become the only "alternate" toolbar. We don't need the main block toolbar, these two alternates, and a vertical toolbar.

**Comment by jeryj** [comment]
For the Select mode, I think we should retain the visible text label. There are a lot of different blocks, and the icons are not always clear as to what the block really is. For the zoom-out mode, are the only blocks available Group and Pattern blocks? If only the outer layer items are there, I think it's less important what the thing is (Group, pattern, etc). This mode seems just for arranging, so only having an icon (or ditching it entirely?) could be warranted.

> Let's have consistent use of block icon, drag, movers, then extra actions—such as shuffling when supported by the block, and a https://github.com/WordPress/gutenberg/issues/60121.

I agree. Having a consistent order would be great.

> The experiences are otherwise quite similar across both—and may even end up merging at some point anyhow, so let's consolidate ahead of time.

I think consolidating the _design and interactions_ of these is a good idea. I don't know if we should _technically_ consolidate them into one component yet though. It may make it harder to maintain and work with, especially early on when we're not sure what all we'll need in Zoom out mode.

**Comment by richtabor** [comment]
> For the Select mode, I think we should retain the visible text label. There are a lot of different blocks, and the icons are not always clear as to what the block really is. 

What's the difference between select and edit modes? We don't have text labels on toolbars elsewhere. 

> This mode seems just for arranging, so only having an icon (or ditching it entirely?) could be warranted.

Yes, I expect it to be more rearranging, shuffling.

**Comment by richtabor** [comment]
Closing this for now
