### ISSUE TITLE
Polish design of edit interfaces for meta in page inspector

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60291]
As a part of the work in https://github.com/WordPress/gutenberg/issues/59689 it would be nice to tidy up the edit interface for page meta data. These UIs looking a little rough around the edges, and the designs in 59689 call for some options like discussion and parent selection to move into the Summary panel.

Here's the current state of affairs:

![current-panels](https://github.com/WordPress/gutenberg/assets/846565/ecc1ad17-fe92-4fb4-8ebd-65b0419773c5)

- [x] Slug https://github.com/WordPress/gutenberg/pull/60632
- [x] Page attributes: https://github.com/WordPress/gutenberg/issues/61869
- [x] Discussion
- [x] Author
- [x] Post status https://github.com/WordPress/gutenberg/pull/60456

**Comment by jameskoster** [comment]
Status panel is being worked on in https://github.com/WordPress/gutenberg/pull/60456.

**Comment by jameskoster** [comment]
Mockups for the other panels:

<img width="1404" alt="Screenshot 2024-04-04 at 14 40 25" src="https://github.com/WordPress/gutenberg/assets/846565/eb5ce261-c7eb-455c-910f-5767bb2b5421">

**Comment by ntsekouras** [comment]
@jameskoster  what about the pingbacks & trackbacks in posts? How do they fit with the comments setting? You can see the current checkbox in post editor in `posts`.

**Comment by jameskoster** [comment]
It could live in the discussion popover as a checkbox for now, I suppose that would be least disruptive. But it _might_ be too prominent there – seems like a setting more likely to be configured at the global level, and rarely overridden locally. We could consider placing it in the ellipsis menu down the road:

<img width="1178" alt="Screenshot 2024-04-10 at 09 47 03" src="https://github.com/WordPress/gutenberg/assets/846565/3f02c3af-405b-46d7-9269-4348afc17ff6">

**Comment by ntsekouras** [comment]
>It could live in the discussion popover as a checkbox for now,

What about the label of the button though? It can't just say `comments open/closed`, right?

Also there is the possibility that we only have the trackbaacks checkbox available and not the comments, if the post type supports only that..

**Comment by jameskoster** [comment]
Perhaps it moves to the ellipsis now, then :) It doesn't feel worthy of a main item in the summary panel to me, but happy to hear other opinions about that.

**Comment by jasmussen** [comment]
The only challenge with the ellipsis is whether that check enables the pingbacks/trackbacks, or whether it surfaces the toggle in the panel, ToolsPanel style. I'd agree on the emphasis, pingbacks is a bit of a vestigial thing, and I'd think it even something you set once in your reading settings and then have a default based on that. Honestly we can even surface the control in the panel based on those same reading settings.

**Comment by jameskoster** [comment]
The tools panel pattern here would be a little convoluted I think. The idea was that selecting the menu item basically worked the same as the current checkbox.

**Comment by ntsekouras** [comment]
I think we can close this issue now, no?

**Comment by jameskoster** [comment]
There's probably some minor polishing to do, but that can happen in individual issues / PRs 👍
