### ISSUE TITLE
Global styles revisions ongoing enhancements

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#60450]
Bugs and enhancement specific to global styles revisions, and where not specific, potentially affecting them.

## Tasks

- [ ] https://github.com/WordPress/gutenberg/issues/58526
- [ ] https://github.com/WordPress/gutenberg/issues/58353
- [ ] https://github.com/WordPress/gutenberg/issues/60394
- [ ] https://github.com/WordPress/gutenberg/issues/60096
- [x] https://github.com/WordPress/gutenberg/issues/60251
- [ ] https://github.com/WordPress/gutenberg/issues/53484
- [x] https://github.com/WordPress/gutenberg/issues/66642
- [ ] https://github.com/WordPress/gutenberg/issues/66525

## Related

- https://github.com/WordPress/gutenberg/issues/61161
- https://github.com/WordPress/gutenberg/issues/49601
- https://github.com/WordPress/gutenberg/pull/50089
- https://github.com/WordPress/gutenberg/issues/62216

**Comment by annezazu** [comment]
This has Tracking in the title but is labeled as an iteration issue. Is this meant for 6.6? If so, let's update the title!

**Comment by ramonjd** [comment]
Thanks, it's not targeted for 6.6. I've moved any confusing terms and left it as a plain ol' issue 😄
