### ISSUE TITLE
Font Library post-WP 6.5 Issues

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#60528]
This is a collection of open Font Library bugs and enhancements to be considered for WP 6.6, grouped by category, with bugs at the top of each category:

### Accessibility

- [ ] #58319 (bug)
- [ ] #55179

### Collections and installing fonts

- [x] #59408
- [x] #58011
- [ ] #58989
- [x] #58277
- [x] #54797
- [ ] #54779
- [ ] #60914
- [x] #63418
- [ ] #62875
- [ ] [Font Library: Replace error message "A font face matching those settings already exists" with notice (trac#60716)](https://core.trac.wordpress.org/ticket/60716)
- [ ] [Font Library: add terms and conditions (trac#60593)](https://core.trac.wordpress.org/ticket/60593)

### Managing installed fonts

- [x] #54401 (bug)
- [ ] #54601 (bug)
- [ ] #60392 (bug)
- [x] #59704
- [x] #58403
- [x] #55220
- [ ] #58276
- [ ] #55176
- [ ] #62977
- [ ] [Font Library: Add an ability to replace font (trac#60717)](https://core.trac.wordpress.org/ticket/60717)
- [ ] https://github.com/WordPress/gutenberg/issues/51151

### Font files

- [ ] #58375 (bug)
- [x] #59417
- [ ] #59102
- [ ] #58229

### Font post types

- [ ] #59486 (bug)
- [ ] #59353 (bug)
- [ ] #59137 (bug)
- [ ] #58670

### REST API

- [ ] **[Install several formats of the same font one by one is not possible (trac#60654)](https://core.trac.wordpress.org/ticket/60654)**

### Google Fonts collection

- [ ] #54671
- [ ] #58521

### All collections

- [ ] #58774
- [x] #58695
- [ ] #59094
- [ ] https://github.com/WordPress/gutenberg/pull/59412

## Font Names and Previews

- [ ] #60188 (bug)
- [ ] https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/23
- [ ] #58411
- [ ] #59976
- [x] https://github.com/WordPress/gutenberg/pull/59569
- [ ] https://github.com/WordPress/gutenberg/issues/62701

## System Fonts

- [ ] #57295
- [ ] #54186

## Relation to Global Styles and Themes

- [ ] #59974 (bug)
- [ ] #55175
- [ ] #54985
- [ ] #54222

## Related Typography Issues

- [ ] #59974 (bug)
- [x] #49090
- [x] #45136
- [ ] #59952
- [ ] #59951
- [ ] #57301
- [ ] #57207
- [ ] #59574

## Importing/Exporting

- [ ] #59109 (bug)
- [ ] #54226

## Code Quality

- [ ] [Fix and improve handling of uploading of font files (trac#60835)](https://core.trac.wordpress.org/ticket/60835) (bug)
- [ ] #58428

## Misc

- [x] #54880
- [ ] #53653

**Comment by afercia** [comment]
@creativecoder can we add https://github.com/WordPress/gutenberg/issues/55179 to this list please? Thanks.

**Comment by creativecoder** [comment]
> @creativecoder can we add https://github.com/WordPress/gutenberg/issues/55179 to this list please? Thanks.

@afercia I've added it to the list.

**Comment by annezazu** [comment]
Can someone provide an update on where this work is with 6.6 beta 1 coming up? Curious what improvements we might see for the release and where we are with these efforts.

**Comment by creativecoder** [comment]
@annezazu I believe the checklist in the issue description is up to date. It looks like we have a few small improvements:

- https://github.com/WordPress/gutenberg/issues/54797
- https://github.com/WordPress/gutenberg/issues/54401
- https://github.com/WordPress/gutenberg/issues/55220

Additionally, there's some in progress work on https://core.trac.wordpress.org/ticket/60835 to improve the underlying code.

That's all I'm aware of, right now.

**Comment by fabiankaegy** [comment]
Hi all 👋 

Reminder: The release candidate for Gutenberg Version 18.5 is scheduled for next Friday (May 31st). So anything that is supposed to make it into WordPress 6.6 must be merged by then. 

Please raise any important issues that need additional attention :)

**Comment by creativecoder** [comment]
I've updated the labels on this issue to be a Tracking Issue (rather than Iteration). At this point the issue description is more a collection of categorized font library issues than a scoped set of issues for a specific iteration.

I've also combed through Gutenberg and Trac and added additional font library issues I found to the description.

**Comment by luminuu** [comment]
@creativecoder I've been stumbling upon this request again, is there a reason why it's not included in this list? https://github.com/WordPress/gutenberg/issues/55239

**Comment by creativecoder** [comment]
@luminuu I still think Adobe/Typekit support is best done with a separate plugin, as I don't see any way to download or use Adobe fonts without signing up for an account, and many of the fonts seem to require a paid subscription.

But if their licensing allows free downloading and use without an account, and there's an API we can use to generate a font collection (see the [google fonts collection scripts](https://github.com/WordPress/google-fonts-to-wordpress-collection) for reference), please let me know!

**Comment by luminuu** [comment]
I have a licensed link available for testing and I tried to add these fonts as a font collection but I didn't got it working. It would be nice if there would be some possbility, apart from a very hacky way that I found. What technically happens is you get a link to a .css file which contains the `@font-face` declarations. I'd imagine the editor to load that CSS file and via the font collection, you can define the fonts, weights etc so they correctly appear in the editor. Ideally these fonts would show up the same way in the design tools and font library, just coming from a different source. This way could be used for other font providers as well, as long as you have a .css file that contains the fonts.
