### ISSUE TITLE
Increase the PHP minimum supported version to 7.2

### ISSUE THREAD

**Issue by anton-vlasenko** [WordPress/gutenberg#60680]
On April 8th, WordPress announced it is dropping PHP 7.0 and 7.1 support, raising the minimum supported version to PHP 7.2 for WordPress 6.6.0.

https://make.wordpress.org/core/2024/04/08/dropping-support-for-php-7-1/

## What is your proposed solution?

To keep parity with WordPress Core, this ticket proposes for Gutenberg to:

* Raise the minimum support PHP version.
* Drop the PHP 7.0 and 7.1 CI jobs.

## Tasks

1. [x] Drop PHP 7.0 and 7.1 CI jobs running on WordPress trunk.
    PR: https://github.com/WordPress/gutenberg/pull/60686#top
2. [x] Get consensus on when to raise the minimum required PHP version.
3. [x] Change the plugin header `Requires PHP:` to `7.2`.

**Comment by anton-vlasenko** [comment]
I'm working on this issue.

**Comment by johnbillion** [comment]
#52982 was the previous bump

**Comment by talldan** [comment]
The CI tests were failing, so 7.0 and 7.1 have been dropped via this PR - [PHP unit test workflow: Try removing 7.0 and 7.1](https://github.com/WordPress/gutenberg/pull/60686#top).

**Comment by anton-vlasenko** [comment]
> The CI tests were failing, so 7.0 and 7.1 have been dropped via this PR - https://github.com/WordPress/gutenberg/pull/60686#top.

Thank you for pointing this out, @talldan.

**Comment by anton-vlasenko** [comment]
The question I have is this: is it acceptable to merge  https://github.com/WordPress/gutenberg/pull/60714 sooner rather than later?

The argument for merging it now is to keep WordPress Core and Gutenberg in sync, but doing so will break compatibility with WordPress 6.5 and 6.4.

These versions of WordPress support PHP version 7.1 and below, and with the merge of this PR, Gutenberg will drop support for those PHP versions.

There was an excellent discussion at https://github.com/WordPress/gutenberg/issues/52344 discussing similar issue, and everyone concluded that it's better not to wait and to raise the minimum PHP version as soon as possible.

Do you think it would also be acceptable to drop support for PHP 7.1 and 7.0 in this manner?

**Comment by talldan** [comment]
> Do you think it would also be acceptable to drop support for PHP 7.1 and 7.0 in this manner?

I personally think it's ok to follow the same process as in https://github.com/WordPress/gutenberg/issues/52344.

**Comment by ironprogrammer** [comment]
+1 for updating now, rather than later. Code worked on and merged from the plugin to Core during the 6.6 cycle wouldn't be expected to support 7.0/7.1 considering their imminent drop of support.

I also agree with [a comment in #52344](https://github.com/WordPress/gutenberg/issues/52344#issuecomment-1650690167) that refers to Gutenberg as the [cutting edge for early access](https://wordpress.org/plugins/gutenberg/#do%20i%20have%20to%20use%20the%20gutenberg%20plugin%20to%20get%20access%20to%20these%20features%3F), and not intended to support older WP versions (which, when upgraded, will receive whatever had recently synced from the plugin anyways 👍🏻).

**Comment by anton-vlasenko** [comment]
Thank you! The bump has just been merged.
