### ISSUE TITLE
Block Library: Migrate to the new textAlign block support

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#60763]
> [!NOTE]
> ~There is currently an issue with not being able to override text alignment support at the block instance level, which is being addressed in #62260.~
> ~Please note that in order to address this issue, #62260 must be resolved first.~

Update: Now that #62260 has been merged, so we can tackle this issue.

## What problem does this address?

Over 20 core blocks have attributes and UI implemented for each block to control the `text-align` style. For example, it looks like the following.

<details><summary>block.json</summary>

```json
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 3,
	"name": "core/heading",
	"title": "Heading",
	"attributes": {
		"textAlign": {
			"type": "string"
		}
	}
}
```

</details> 

<details><summary>edit.js</summary>

```javascript
import {
	AlignmentControl,
	BlockControls,
	useBlockProps,
} from '@wordpress/block-editor';

function Edit( { attributes, setAttributes } ) {
	const { textAlign } = attributes;
	return (
		<>
			<BlockControls group="block">
				<AlignmentControl
					value={ textAlign }
					onChange={ ( nextAlign ) => {
						setAttributes( { textAlign: nextAlign } );
					} }
				/>
			</BlockControls>
			<div { ...useBlockProps() } />
		</>
	);
}
```

</details> 

These are all almost the same implementations and feel redundant.

## What is your proposed solution?

In #59531, `textAlign` is added as block support. I believe that we can gradually migrate to this block support.

Below is a list of blocks that provide attributes and UI to control text-aligin.

- [x]  core/button #73732
- [x]  core/comment-author-name #74068
- [x]  core/comment-content #74269
- [x]  core/comment-edit-link #74720
- [x]  core/comment-reply-link #74760
- [x]  core/comment-title #74945
- [x]  core/heading #74383
- [x]  core/paragraph: Note that the attribute is named "align" and not "textAlign". https://github.com/WordPress/gutenberg/pull/73111
- [x]  core/post-author: This block has been deprecated, and no action is required. #55352
- [x]  core/post-author-biography #74997
- [x]  core/post-author-name #75109
- [x]  core/post-comments-count #75321
- [x]  core/post-comments-form #75322
- [x]  core/post-comments-link #75332
- [x]  core/post-navigation-link #75557
- [x]  core/post-time-to-read #75541
- [x]  core/post-terms #75545
- [x]  core/post-title #75629
- [x]  core/query-title #75802
- [x]  core/site-tagline #75690
- [x]  core/site-title #75551
- [x]  core/term-description #75542
- [x]  core/verse #74724
- [x]  core/post-excerpt #75860
- [x]  core/post-date #75856
- [ ]  core/pullquote
- [ ] core/term-name

**Comment by t-hamano** [comment]
All blocks have been migrated. Thank you to everyone who contributed!
