### ISSUE TITLE
Tracking Issue: Full-page client-side navigation

### ISSUE THREAD

**Issue by DAreRodz** [WordPress/gutenberg#60951]
## What problem does this address?

Full-page, client-side navigation (for lack of a better name) is another navigation mode we want to include in the Interactivity API along with the current region-based, client-side navigation already implemented.

Region-based navigation works by updating the HTML of those regions defined on the current and target pages. When there are no matching regions between the two pages, navigation is delegated to the browser, and the page is reloaded. In such cases, the application's JS state is reset, and it is not possible to implement features such as keeping a video open or a song playing while navigating the page.

In contrast, full-page navigation updates the HTML of the entire page when navigating without the need to specify regions. This allows you to transition from one page to another on the site while maintaining the application's state. This is, in fact, what is implemented at [https://wpmovies.dev/](https://wpmovies.dev/), although that implementation needs to be polished and improved before it can be published.

In that regard, @SantosGuillamot has created a PR with a first iteration under an experimental flag in #59707, although work remains to be done, especially in relation to the handling of new assets appearing on the target page, whether inside `<head>` or `<body>`. This feature is also missing for region-based navigation.

## Current tasks

The following list of tasks is based on feedback received in #59707:

- [x]  ~Explore how to modify the body tag without the hack: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1559952673).~
  - fixed in https://github.com/WordPress/gutenberg/pull/61212
- [ ]  Revisit how to fetch head assets: [link](https://github.com/WordPress/gutenberg/pull/59707#pullrequestreview-1975274682).
    - [x]  Change innerText for textContent and revisit how styles are injected: [link](https://github.com/WordPress/gutenberg/pull/59707).
    - [x]  Check if **[Preact fails to reconcile scripts correctly when doing client-side navigation](https://github.com/WordPress/block-interactivity-experiments/issues/242)** is still an issue.
    - [ ]  If the stylesheet remains the same, it should probably be left as-is: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1559964017).
- [ ]  Explore how this interacts with Speculation Rules API: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1559663664).
- [ ]  Explore if we want to listen to `touchstart` in addition to `mouseenter` on mobile devices for prefetching: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1559664794). (Maybe on click is enough)
- [ ]  Explore how to update query attribute when the experiment is enabled: [link](https://github.com/WordPress/gutenberg/pull/59707#pullrequestreview-1974040313). It looks like a core bug (see [ticket/56417](https://core.trac.wordpress.org/ticket/56417)).
- [ ]  Accept only a string in the `url` parameter and adapt the tests to reflect that: [link](https://github.com/WordPress/gutenberg/pull/59707#issuecomment-2022343602).
- [x]  ~Explore deeper how to use event delegation in the client: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1541233377).~
  - Already implemented in https://github.com/WordPress/gutenberg/pull/59707/commits/d72cd023eae40645e8e787f24d91f515b12ce4ee
- [ ]  Add e2e tests: [link](https://github.com/WordPress/gutenberg/pull/59707#issuecomment-2031730825).
- [ ]  Fix valid link logic to handle multisites and subdirectories: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1569287625)
- [ ]  Consider adding `touchstart` or changing `mouseenter` event to `pointerenter` for prefetching: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1569603167)
- [ ] Pass URLs ineligible for client-side navigation from PHP (e.g. `get_admin_url()`, `wp_login_url()`) as opposed to hard-coding them: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1591299199)

**Comment by westonruter** [comment]
> Explore how to modify the body tag without the hack: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1559952673).

See https://github.com/WordPress/gutenberg/pull/61212

**Comment by michalczaplinski** [comment]
> Add e2e tests: https://github.com/WordPress/gutenberg/pull/59707#issuecomment-2031730825.

I've started implementing some new e2e tests for full-page client-side navigation in https://github.com/WordPress/gutenberg/pull/63268

**Comment by michalczaplinski** [comment]
I'd like to understand a bit better what remains to be done to improve the handling of assets:

>   - [ ]  Change innerText for textContent and revisit how styles are injected: [link](https://github.com/WordPress/gutenberg/pull/59707).

This should be a trivial 1 line change.

>   - [ ]  Check if **[Preact fails to reconcile scripts correctly when doing client-side navigation](https://github.com/WordPress/block-interactivity-experiments/issues/242)** is still an issue.

I was the person who reported the original issue, and this issue is still present. We might have to implement something like the suggested fix.

>   - [ ]  If the stylesheet remains the same, it should probably be left as-is: [link](https://github.com/WordPress/gutenberg/pull/59707#discussion_r1559964017). It would be nice to be able to reuse DOM diffing from Preact here if possible.

We can't use Preact to render the `<head>` but we should look into this (https://github.com/WordPress/gutenberg/pull/59707#discussion_r1597595496) to prevent performance issues.

>   - [ ]  Ensure caching is required: [link]

This should be a trivial change.

----

Additionally, we should only load the module scripts belonging to the new blocks on the page or other modules that have declared their compatibility with full-page client-side navigation (link).

Are you aware of any other considerations for asset loading? cc @luisherranz @DAreRodz @cbravobernal

**Comment by michalczaplinski** [comment]
I looked at https://github.com/hotwired/turbo to see how they handle assets, and it seems like they kinda side-step the problem by not prefetching the scripts and styles 😄.

They merge the "old" `<head>` with the new one in a way similar to us: 

https://github.com/hotwired/turbo/blob/c339144924e5632d4ef5e3a7b941b3db17d9efa3/src/core/drive/page_renderer.js#L72-L83

Interestingly, they never `fetch()` the scripts and styles. 

Hotwired can prefetch an HTML page for an `<a>` link (like Interactivity API). However, it waits for the page navigation to happen and, upon navigation, injects the new styles & scripts into the head and lets the browser figure out how to load them.

**EDIT**: This is effectively the same strategy for loading assets that @gziolo and I suggested [here](https://github.com/WordPress/gutenberg/pull/59707#issuecomment-2033709520) & [here](https://github.com/WordPress/gutenberg/pull/59707#pullrequestreview-1975274682)

**Comment by DAreRodz** [comment]
Nice! Maybe this is useful as well: a while ago, I did a quick [experiment](https://github.com/WordPress/gutenberg/commit/9baff875ae7007351f6a9b098348edab59bcebde), using the [htmx `head-support` extension](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/head-support/README.md) as an inspiration. 😁

It also injects HTML tags and uses `onload` and `onerror` event handlers to keep track of which assets have been loaded so far, but instead of adding the assets directly to the HTML, it appends `<link>` elements with `rel=preload`, so the new styles or scripts are not displayed/executed until effectively inserted into the HTML.

The htmx `head-support` extension also has other interesting features, like special attributes to control the merge behavior or script re-evaluation.

**Comment by luisherranz** [comment]
Pasting this @michalczaplinski's comment from [this PR](https://github.com/WordPress/gutenberg/pull/64067) to have the conversation centralized 🙂

> We should investigate if calling the `fetch()` ourselves to prefetch & cache scripts is the right way to go as investigated by @DAreRodz in this branch: [9baff87](https://github.com/WordPress/gutenberg/commit/9baff875ae7007351f6a9b098348edab59bcebde). At the minimum, we should [consider passing `{ priority: low }`](https://web.dev/articles/fetch-priority#fetchpriority-attribute) in the fetch requests.

A few things:

- We can't use `onload` on the `rel=preload`/`rel= modulepreload` links because [by the spec, they are not guaranteed to be prefetched](https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload). We need to put the `onload` on the real links or use `fetch` and inject the content ourselves.
- For scripts, as we will only support modules, we can use `link rel="modulepreload"` for preloading, and dynamic imports for loading. We only need to await on the dynamic imports once we want to actually show the new page.

  Something like this:

  ```js
  await Promise.all(newModules.map((module) => import(module)));
  ```

- I'm not quite sure about the CSS strategy yet. We'll probably be fine using link `rel="preload"` for preloading and await on the final link tags `onload` events once we want to actually show the new page (apart from copying over the inlined `style` tags).

**Comment by michalczaplinski** [comment]
Thanks Luis! 

> We need to put the onload on the real links or use fetch and inject the content ourselves.

yup, that was my idea too 🙂 But as we're going to use modules then, for scripts, we only have to do the second thing that you mention which is this:

> we can use link rel="modulepreload" for preloading, and dynamic imports for loading. We only need to await on the dynamic imports once we want to actually show the new page.

For CSS, I was considering something like what you suggested, but I'm also not yet 100% sure. I'll probably have to try it out in a prototype.

**Comment by michalczaplinski** [comment]
## Status Update 

https://github.com/WordPress/gutenberg/pull/64067 has been merged, which fixes https://github.com/WordPress/gutenberg/issues/63880. It improves the handling of JS assets when doing full-page client-side navigation and brings the following improvements: 
 - Remove the `src` attributes from prefetched script tags.
 - Use `.textContent` instead of `.innerText` to set `<script>` contents.
 - Wait for the `load` event of the script element before evaluating it.
 - Only prefetch **module** scripts; never prefetch regular scripts. That's
	because regular scripts (without `async` or `defer` attributes) found in the
	head are blocking and must be executed in order. When prefetching there is no
	guarantee that the scripts will execute in the order they are prefetched.
	Module scripts can be executed in any order.

Now, **follow-up** PRs should focus on:

1. Handle CSS asset loading in a way analogous to how JS assets are handled now:
   1. Handle properly the cache busting hash in the URLs of the block styles. ([comment](https://github.com/WordPress/gutenberg/pull/64067#issuecomment-2317367518))
   2. Moving the styles from a file to `<style>` tags messes up with how the URLs are interpreted in CSS's  `url()` function. ([comment](https://github.com/WordPress/gutenberg/pull/64067#discussion_r1738591715))
   3. CSS should probably be pre-loaded using `<link>` tags as discussed in [this comment](https://github.com/WordPress/gutenberg/pull/64067#discussion_r1738591715). It could possiblly leverage [this](https://stackoverflow.com/questions/46787921/rel-preload-for-stylesheet-isnt-applying-the-styles-once-downloaded) approach: 
   4. Fix other issues with styling: #66123
2. Figure out the way to only load the scripts for the new & compatible interactive blocks on the page. Previously mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/63880#issuecomment-2263605123) & [this comment](https://github.com/WordPress/gutenberg/pull/59707#issuecomment-2106176106)
3. Handle fetching more robustly, consider using `Promise.allSettled()` ([comment](https://github.com/WordPress/gutenberg/pull/64067#discussion_r1784279843))
4. _(low priority)_ Refactor the `fetchHeadAssets()` function so that it's not called inside of `regionsToVdom`.

**Comment by luisherranz** [comment]
Superseded by this, as this is going to be the focus for WP 6.8.

- https://github.com/WordPress/gutenberg/issues/67276

Let's move the conversation there 🙂
