### ISSUE TITLE
Migrate dropdown menu instances to `@wordpress/ui`'s `Menu` component

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#61094]
Track the remaining dropdown menus to migrate to the Base UI-backed `Menu` from `@wordpress/ui`. This replaces both the private Ariakit-backed `Menu` in `@wordpress/components` and legacy menus built with `DropdownMenu`, `ToolbarDropdownMenu`, or `Dropdown` and menu items.

Inventory checked against `trunk` on September 15, 2026, at [809cee109cb3](https://github.com/WordPress/gutenberg/commit/809cee109cb3645799b30713b09bdb41ebee334f). Entries identify shared implementations, so one migration may cover several screens or blocks. Checked entries are migrations merged between August 15 and September 15, 2026. Open PRs remain unchecked until merged.

## Ariakit Menu → @wordpress/ui Menu

This section tracks application consumers of the private Ariakit Menu. Once #81929 and #81930 merge, the currently identified application consumers will all be migrated. Removing the private implementation, export, tests, stories, and documentation in `@wordpress/components` is separate cleanup. Other components still use Ariakit.

### @wordpress/editor

- [x] [Post / document actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-actions/index.jsx). [#81922](https://github.com/WordPress/gutenberg/pull/81922), merged September 14.
- [ ] [Note actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/collab-sidebar/note.jsx). Open PR: [#81930](https://github.com/WordPress/gutenberg/pull/81930).

### @wordpress/widget-dashboard

- [ ] [Dashboard actions overflow](https://github.com/WordPress/gutenberg/blob/trunk/packages/widget-dashboard/src/components/actions-menu/actions-menu.tsx).
- [ ] [Individual widget actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/widget-dashboard/src/components/widget-actions/widget-actions.tsx).
- [ ] [Widget width options](https://github.com/WordPress/gutenberg/blob/trunk/packages/widget-dashboard/src/components/widget-layout-controls/widget-layout-controls.tsx).

Open PR: [#81929](https://github.com/WordPress/gutenberg/pull/81929), covering all three instances. [#81970](https://github.com/WordPress/gutenberg/pull/81970) was closed as superseded by #81929.

### @wordpress/block-editor

- [x] [Block bindings](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-bindings/attribute-control.jsx). [#81925](https://github.com/WordPress/gutenberg/pull/81925), merged September 14.
- [x] [Dedicated block variation transforms menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-variation-transforms/index.jsx). [#81925](https://github.com/WordPress/gutenberg/pull/81925), merged September 14. The general block switcher remains listed under legacy menus.

### @wordpress/dataviews

- [x] [Add-filter menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/components/dataviews-filters/add-filter.tsx). [#81783](https://github.com/WordPress/gutenberg/pull/81783), merged August 24.
- [x] [Item actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/components/dataviews-item-actions/index.tsx). [#81783](https://github.com/WordPress/gutenberg/pull/81783), merged August 24. Also covers template and template-part list actions rendered through DataViews.
- [x] [List layout actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/components/dataviews-layouts/list/index.tsx). [#81783](https://github.com/WordPress/gutenberg/pull/81783), merged August 24.
- [x] [Table column menus](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/components/dataviews-layouts/table/column-header-menu.tsx). [#81783](https://github.com/WordPress/gutenberg/pull/81783), merged August 24.
- [x] [View configuration menus](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/components/dataviews-view-config/index.tsx). [#81783](https://github.com/WordPress/gutenberg/pull/81783), merged August 24.

### @wordpress/global-styles-ui

- [x] [Preset edit menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/global-styles-ui/src/presets/preset-edit-header.tsx). [#81921](https://github.com/WordPress/gutenberg/pull/81921), merged September 11.
- [x] [Preset group menus](https://github.com/WordPress/gutenberg/blob/trunk/packages/global-styles-ui/src/presets/preset-group.tsx). [#81921](https://github.com/WordPress/gutenberg/pull/81921), merged September 11.
- [x] [Block-list filters](https://github.com/WordPress/gutenberg/blob/trunk/packages/global-styles-ui/src/screen-block-list.tsx). [#81921](https://github.com/WordPress/gutenberg/pull/81921), merged September 11.

### @wordpress/block-editor

- [ ] [Block options in the toolbar and List View](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-settings-menu/block-settings-dropdown.jsx). Includes SlotFill extension points.
- [ ] [Block transforms](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-switcher/index.jsx). Includes block, pattern, variation, and style choices. Related design work: [#40208](https://github.com/WordPress/gutenberg/issues/40208).
- [ ] [Block styles dropdown](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-toolbar/block-styles-dropdown.jsx).
- [ ] [Text alignment](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/ui.jsx).
- [ ] [Block alignment](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-alignment-control/ui.jsx).
- [ ] [Vertical alignment](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-vertical-alignment-control/ui.jsx).
- [ ] [Content justification](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/justify-content-control/ui.jsx).
- [ ] [Heading level](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-heading-level-dropdown/index.jsx).
- [ ] [Additional rich-text formatting](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/format-toolbar/index.jsx). Includes registered format controls.
- [ ] [Style state and viewport selector](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/global-styles/state-control.jsx). Includes the block inspector state controls.
- [ ] [Image crop aspect ratio](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/image-editor/aspect-ratio-dropdown.jsx).
- [ ] [Inserter pattern filters](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inserter/block-patterns-tab/patterns-filter.jsx).
- [ ] [Inserter media preview options](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inserter/media-tab/media-preview.jsx).
- [ ] [Block warning secondary actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/warning/index.jsx).
- [ ] [Media replacement](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/media-replace-flow/index.jsx). Shared by image, Site Logo, and other media controls. Needs design review: menu actions share the popup with a URL form.
- [ ] [Image link destinations and lightbox action](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/url-popover/image-url-input-ui.jsx). Needs design review: menu items are embedded in the link-editing popover.

### @wordpress/block-library

- [ ] [Gallery link destination](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/edit.jsx).
- [ ] [Image toolbar More menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/image/image.jsx).
- [ ] [Navigation block item options](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/edit/leaf-more-menu.jsx).
- [ ] [Navigation menu selector and tools](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/edit/navigation-menu-selector.jsx).
- [ ] [Query Total display type](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query-total/edit.jsx).
- [ ] [Table editing actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/table/edit.jsx).
- [ ] [Term Count bracket type](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/term-count/edit.jsx).
- [ ] [Video text-track actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/video/tracks-editor.jsx). Needs design review: the dropdown also displays track information and an editing form.

### @wordpress/components

- [x] [Palette options in PaletteEdit](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/palette-edit/index.tsx). [#82768](https://github.com/WordPress/gutenberg/pull/82768), merged September 14.
- [ ] [ToolsPanel options](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/tools-panel/tools-panel-header/component.tsx). Shared by block inspector and Global Styles panels.
- [ ] [ToolbarDropdownMenu wrapper](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/toolbar/toolbar-dropdown-menu/index.tsx). Preserve the public API and toolbar integration.
- [ ] [Collapsed ToolbarGroup menus](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/toolbar/toolbar-group/toolbar-group-collapsed.tsx). Shared by alignment and other toolbar controls. Coordinate with the consumer migrations above.

### @wordpress/editor

- [x] [Main Options menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/more-menu/index.jsx). [#81564](https://github.com/WordPress/gutenberg/pull/81564), merged September 1. Includes editor modes and plugin-item compatibility.
- [x] [View / preview menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/preview-dropdown/index.jsx). [#82321](https://github.com/WordPress/gutenberg/pull/82321), merged September 4.
- [x] [Global Styles header menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/global-styles/menu.jsx). [#81921](https://github.com/WordPress/gutenberg/pull/81921), merged September 11.
- [ ] [Template options in the post sidebar](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-template/block-theme.jsx).

### @wordpress/edit-site

- [ ] [Add pattern / template part](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/add-new-pattern/index.jsx).
- [ ] [Pattern category actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/page-patterns/actions.jsx).
- [ ] [Navigation menu details actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menu/more-menu.jsx).
- [ ] [Navigation list item options](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/leaf-more-menu.jsx).

### Extensible site editor routes

- [ ] [Navigation editor list item options](https://github.com/WordPress/gutenberg/blob/trunk/routes/navigation-edit/editor/leaf-more-menu.tsx). Keep this migration aligned with the corresponding navigation menus above.

### @wordpress/global-styles-ui

- [ ] [Font collection actions](https://github.com/WordPress/gutenberg/blob/trunk/packages/global-styles-ui/src/font-library/font-collection.tsx).

### @wordpress/media-editor

- [ ] [Image crop aspect ratio](https://github.com/WordPress/gutenberg/blob/trunk/packages/media-editor/src/components/media-editor-image-controls/index.tsx).

### @wordpress/edit-widgets

- [ ] [Widgets editor Options menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/components/more-menu/index.jsx).

### @wordpress/customize-widgets

- [ ] [Customizer widgets Options menu](https://github.com/WordPress/gutenberg/blob/trunk/packages/customize-widgets/src/components/more-menu/index.jsx).

### @wordpress/widgets

- [ ] [Move to widget area](https://github.com/WordPress/gutenberg/blob/trunk/packages/widgets/src/components/move-to-widget-area/index.jsx).

## Related dropdowns needing a component decision

These contain controls or a picker rather than a list of menu actions. Decide the appropriate component before treating them as Menu migrations.

- [ ] [Quick Inserter](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inserter/index.jsx). Retained from the original checklist; contains block search and selection.
- [ ] [Icon block label editor](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/icon/edit.jsx). Currently uses `DropdownMenu` to display a text field.

## Migration notes and design references

The `@wordpress/ui` Menu component landed on August 19 in [#79560](https://github.com/WordPress/gutenberg/pull/79560).

- Preserve existing extension contracts when menus accept third-party items through SlotFill or render callbacks. The editor Options menu provides a merged compatibility example in [#81564](https://github.com/WordPress/gutenberg/pull/81564); extensible-menu guidance is proposed in [#81821](https://github.com/WordPress/gutenberg/pull/81821).
- Check corresponding implementations in both site editors when migrating shared features.
- Some menus need design work, especially block transforms and ToolsPanel options. Existing exploration is available in [Figma](https://www.figma.com/file/7ZZQtG3jswbljn0E7HPuou/Menu-migration?type=design&node-id=1%3A1971&mode=design&t=quRDu6a8STQLlfV3-1).
- Earlier migration exploration: [#57996](https://github.com/WordPress/gutenberg/pull/57996).

**Comment by jameskoster** [comment]
I've mocked up the menus in [Figma](https://www.figma.com/file/7ZZQtG3jswbljn0E7HPuou/Menu-migration?type=design&node-id=1%3A1972&mode=design&t=s43hGdBR6EmeEEuK-1) based on the existing DropdownMenu V2 component.

Here's a sample (current menus are on the left):

![Export](https://github.com/WordPress/gutenberg/assets/846565/61753bec-7a7a-4fb5-a612-75c75889ed0c)


Generally I think the migration should be quite smooth, but some questions arose out of this exercise:

* Do we need a version of `DropdownRadioItem` where the radio indicator is an icon? If yes, how do we differentiate that from regular menu items with icons, and how do we mark the selected item?
* Should we utilise the ellipsis suffix on menu items that have subsequent steps, e.g. "Rename..." vs "Rename"?
* Can we get away without group headings? 
* Are there design details in DropdownMenu V2 that need to change?

Also worth noting: Transforms and Toolspanel will need further investigation as these are more involved menus.

**Comment by tyxla** [comment]
cc @ciampo who's been working on `DropdownMenuV2`

**Comment by ciampo** [comment]
Hey @jameskoster 👋  it's good to be back!

> * Do we need a version of `DropdownRadioItem` where the radio indicator is an icon? If yes, how do we differentiate that from regular menu items with icons, and how do we mark the selected item?

We discussed this aspect a few months ago and concluded that radio items shouldn't show an icon. Have there been any significant pushbacks on this decision or any other reasons why we are reconsidering it?

> * Should we utilise the ellipsis suffix on menu items that have subsequent steps, e.g. "Rename..." vs "Rename"?

Are you proposing that the component automatically adds the ellipsis to the menu item label when it is a sub-menu trigger? Although in the screenshot above, "Rename..." and "Duplicate..." are probably triggering a modal dialog rather than a submenu.

IMO, whether to add the ellipsis to the menu item label or not shouldn't be a responsibility of the `DropdownMenu` component — also because the component in itself doesn't have a way to know when a menu item will open a modal dialog vs only perform an action.

> * Can we get away without group headings?

I think we need them unless we want to make an explicit design decision and move away from them. Group headings would be easy to implement, in case.

> * Are there design details in DropdownMenu V2 that need to change?

I think that the current implementation is already quite solid — unless there are big aspects that need change, I think that the best way forward is to continue to work on replacing existing v1 usages with v2, which should help us uncover any major bugs / missing features and should therefore also inform any design tweaks.

In January, before I took some extended leave, I started [refactoring the "More" dropdown in the block toolbar](https://github.com/WordPress/gutenberg/pull/57996), which is one of the most complex use cases and should give us a good taste for the rest of the migration. I plan on resuming that work soon

**Comment by jameskoster** [comment]
> We discussed this aspect a few months ago and concluded that radio items shouldn't show an icon. Have there been any significant pushbacks on this decision or any other reasons why we are reconsidering it?

No significant pushback that I've seen, and I still think the overall consistency is worth the trade-off of losing the icon for radio items. But this is just my opinion :) We may see some pushback when updating menus like text justification in the block toolbar.

> Are you proposing that the component automatically adds the ellipsis to the menu item label when it is a sub-menu trigger?

The rule of thumb would be; if the user must take subsequent action after clicking, then the label would include an ellipsis. It's becoming a more established convention that we might consider adopting.

<img width="252" alt="Screenshot 2024-06-20 at 10 50 29" src="https://github.com/WordPress/gutenberg/assets/846565/86dc15c1-0ed7-49bc-9a3b-a57f7edbb78e">

One way we might make this part of the component would be to add a `hasNextStep` (or similar) prop, so that we can update holistically in the future. It's probably a separate consideration from this work.

> I think we need them unless we want to make an explicit design decision and move away from them. Group headings would be easy to implement, in case.

I think the main consideration here is the a11y story. I haven't checked in a while, but I don't think headings should live inside `role="menu"` elements, so we'd need to do something like:

```
<h2 id="menuHeading">Menu Title</h2>
<ul role="menu" aria-labelledby="menuHeading">
  <li role="menuitem">Item 1</li>
  <li role="menuitem">Item 2</li>
  <li role="menuitem">Item 3</li>
</ul>
```

**Comment by ciampo** [comment]
> I still think the overall consistency is worth the trade-off of losing the icon for radio items. But this is just my opinion :) We may see some pushback when updating menus like text justification in the block toolbar.

That is my opinion too. Let's see if we can get away with using regular menu items (instead of radio) for those instances, which would avoid the issue altogether.

> if the user must take subsequent action after clicking, then the label would include an ellipsis [...] One way we might make this part of the component would be to add a hasNextStep (or similar) prop, so that we can update holistically in the future. It's probably a separate consideration from this work.

Thank you for clarifying! Personally, I still think that adding ellipses should not be a responsibility of `DropdownMenu`. Components should focus on the core features that they offer, and should try to do that in the most general and open way possible — this is to allow flexibility and composition with other components. That is why, for example, we have a `prefix` prop instead of `icon` and a `suffix` prop instead of `shortcut` from the legacy V1.

Although I agree that it's still a separate conversation, so let's resume it if and when necessary.

>  think the main consideration here is the a11y story. I haven't checked in a while, but I don't think headings should live inside role="menu" elements, so we'd need to do something like:

That shouldn't be a problem. `ariakit` already has the primitives that we'd need — [`MenuGroup`](https://ariakit.org/reference/menu-group) and [`MenuGroupLabel`](https://ariakit.org/reference/menu-group-label)

![Screenshot 2024-07-04 at 12 10 31](https://github.com/WordPress/gutenberg/assets/1083581/4575edb9-4bb2-430f-a457-ea7fc08d46be)

**Comment by stokesman** [comment]
I wonder if it’d be worthwhile to update styles of `DropdownMenu` and related components to look as much as possible like `Menu`. It seems to me that there are going to be plugins that never end up making the switch and it’d mitigate the inconsistent look at least. Besides that, it may make for a more graceful migration for Gutenberg.

**Comment by ciampo** [comment]
We're actually in the process of creating a new UI package ([more context here](https://github.com/WordPress/gutenberg/issues/71196)), and therefore I'm not if it makes sense now to invest time into migrating to the experimental `Menu` from `@wordpress/components`, as we may soon want to migrate directly to the `Menu` from `@wordpress/ui` insted.

Although, regardless of the chosen new component, some of the points above are still valid, such as tweaking existing componentry to miminize visual differences between legacy and new components.

Another difficult challenge will be to ensure backwards compat for all instances where third-party code can inject menu items into existing menus — we may end up in a place where the new `Menu` receives legacy `Item` children (for example, a plugin may inject them via slotfill).

**Comment by Mamaduka** [comment]
@ciampo, any timeline when we might get the `Menu` component in UI package?

> Another difficult challenge will be to ensure backwards compat for all instances where third-party code can inject menu items into existing menus — we may end up in a place where the new Menu receives legacy Item children.

This is important and might be worth starting an experiment early, even if the new component is unstable. IIRC, the block toolbars component had to deal with a similar migration in the past. Maybe we could use a same playbook here.

For example: Legacy `Item` checks if it's rendered in the new `Menu` context, returns proper element and triggers warning/deprecation.

**Comment by ciampo** [comment]
@Mamaduka this is definitely top of mind, but realistically I believe I'll be able to work on this in August / September at the earliest, as my focus is currently on polishing and ironing out as many wrinkles as possible for the `@wordpress/theme` package (`ThemeProvider` and DS tokens), as we plan on marking it as stable for the 7.1 release.

The work that we've been doing on building a compat layer for `@wordpress/ui` overlays (and [the general readiness of overlays](https://github.com/WordPress/gutenberg/issues/76135#:~:text=%40wordpress/components-,Overlay%20components%20(popovers%2C%20dialogs%2C%20modals%2C%20tooltips%2C%20dropdowns...)%20need%20a%20compat%20layer,-Update%20cursor%20styles)) will also play a role.

**Comment by ciampo** [comment]
I'm fine with re-introducing the dot in #79560, but just wanted to remember that we had [previously agreed](https://github.com/WordPress/gutenberg/pull/73104#issuecomment-3534355917) with project stakeholders to use checkmarks for everything. 

If you're all ok with that, I'm happy to go ahead and add dots back.

**Comment by ciampo** [comment]
> Sorry, got carried away with some other tasks.
> 
> I can do a stacked PR on top of [#79560](https://github.com/WordPress/gutenberg/pull/79560) to migrate the main options menu. I'll have something ready this week.

FYI the main options has been migrated to the new `Menu` component. Please test and report back!

**Comment by jameskoster** [comment]
Nice! Please feel free to check items off the list once they're migrated.

**Comment by ciampo** [comment]
Sounds good, I updated the issue's description with a (hopefully) up to date list. We're almost there with migrating all Ariakit-based menus already!
