### ISSUE TITLE
Color & Typography Variations for WP 6.6

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#61215]
Iteration of the [Colors and Typography Presets from theme style variations](https://github.com/WordPress/gutenberg/issues/56604) overview issue: 

### Tasks: 
- [x] https://github.com/WordPress/gutenberg/pull/56622
- [x] https://github.com/WordPress/gutenberg/pull/59717
- [x] https://github.com/WordPress/gutenberg/pull/59590
- [x] https://github.com/WordPress/gutenberg/pull/59514
- [x] https://github.com/WordPress/gutenberg/pull/60220
- [x] https://github.com/WordPress/gutenberg/issues/61213
- [x] https://github.com/WordPress/gutenberg/issues/61216
- [ ] https://github.com/WordPress/gutenberg/issues/61841
- [ ] https://github.com/WordPress/gutenberg/issues/61214
- [x] https://github.com/WordPress/gutenberg/issues/61217

### Visual

https://github.com/WordPress/gutenberg/assets/1813435/8de00943-3c20-4c4d-beb2-129686932f94

**Comment by fabiankaegy** [comment]
Hi all 👋 

Reminder: The release candidate for Gutenberg Version 18.5 is scheduled for next Friday (May 31st). So anything that is supposed to make it into WordPress 6.6 must be merged by then. 

Please raise any important issues that need additional attention :)

**Comment by andrewserong** [comment]
@richtabor @scruffian, while testing out the new color presets on `trunk`, I noticed a couple of bugs, so I've filed issues for them:

* https://github.com/WordPress/gutenberg/issues/61840
* https://github.com/WordPress/gutenberg/issues/61841

I didn't get a chance to look more closely at the code since I'm in the middle of travelling this week (so I'll also be slow to respond), but hopefully those issues might help any debugging, if these ones haven't already been flagged 🙂

**Comment by hbhalodia** [comment]
Hi @andrewserong, thanks for the flagging this out. Just to add in the context, 

- https://github.com/WordPress/gutenberg/issues/61840

The above is already reported and actively worked on here - https://github.com/WordPress/gutenberg/issues/61759. It has a PR already raised for the same - https://github.com/WordPress/gutenberg/pull/61617, hoping it can be fixed soon.

Thank You ✨.

**Comment by annezazu** [comment]
With 6.6 out in the open, closing this iteration issue out. Let's open a next iteration issue for 6.7 for additional bug fixes and refinements.
