### ISSUE TITLE
PHP backports for WP 6.6

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#61226]
We'd like to start backporting the necessary PHP code as soon as possible to catch issues early so that it doesn't block the package release process.

- Guide: [Back-merging code to WordPress Core](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/back-merging-to-wp-core.md).
- If an item does not need backporting, or was already backported, please strike it out.
- **Please [open a new Core Trac ticket for each PR](https://core.trac.wordpress.org/newticket)** and link it next to the citation in this issue.
- For ease of cross-linking and tracking, you can submit your PRs to [WordPress/wordpress-develop](https://github.com/WordPress/wordpress-develop). Refer to docs on [how to fork the repository and create a PR](https://make.wordpress.org/core/handbook/tutorials/trac/submitting-a-patch/#adding-your-github-fork-to-your-wp-trunk-copy). Link any backport PR next to the citation in this issue.
- Try to limit PRs to one feature to make reviewing easier and the commit history clear. See [why](https://github.com/WordPress/gutenberg/issues/47187#issuecomment-1384107056).
- Once your backport PR is up, add it to the [WordPress 6.6 Editor Tasks project board](https://github.com/orgs/WordPress/projects/179) so people can review it.
- If items belong together, please make a nested list where each item is still a checkbox.
- This issue will be updated every once in a while as we we approach [Beta 1](https://make.wordpress.org/core/6-6/), with new lines for any new PHP changes. Last update: 2024-06-03.

Thank you!

---

# 📁 lib

### 📁 wordpress-6.6

- [x] ~~https://github.com/WordPress/gutenberg/pull/61178 - @shail-mehta | Trac ticket | Core backport PR~~
_Should be handled in the next item._
- [x] https://github.com/WordPress/gutenberg/pull/60317 +
  - [x] https://github.com/WordPress/gutenberg/pull/61178 - @fabiankaegy | [Trac ticket](https://core.trac.wordpress.org/ticket/61137) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6494) 
- [x] https://github.com/WordPress/gutenberg/pull/60549 - @carolinan | [Trac ticket](https://core.trac.wordpress.org/ticket/61250) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6579)
- [x] ~~https://github.com/WordPress/gutenberg/pull/60862 - @Mamaduka | [Trac ticket](https://core.trac.wordpress.org/ticket/61023) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6495)~~
See next item.
- [x] https://github.com/WordPress/gutenberg/pull/59243 - @Mamaduka | [Trac ticket](https://core.trac.wordpress.org/ticket/61023) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6495)
- [x] ~~https://github.com/WordPress/gutenberg/pull/60491 - ~~okmttdhr~~ @ellatrix | Trac ticket | Core backport PR~~ 
Handled below.
- [x] ~~https://github.com/WordPress/gutenberg/pull/60464 - @ellatrix | Trac ticket | Core backport PR~~ 
Handled below.
- [x] https://github.com/WordPress/gutenberg/pull/60349 - @ellatrix | Trac ticket | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6673)
  - [x] https://github.com/WordPress/gutenberg/pull/60464
  - [x] https://github.com/WordPress/gutenberg/pull/60491
  - [x] https://github.com/WordPress/gutenberg/pull/61757
- [x] https://github.com/WordPress/gutenberg/pull/60925 - @creativecoder | [Trac ticket](https://core.trac.wordpress.org/ticket/60909) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6420) 
- [x] https://github.com/WordPress/gutenberg/pull/61244 - @Mamaduka | [Trac ticket](https://core.trac.wordpress.org/ticket/61110) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6468) 
- [x] https://github.com/WordPress/gutenberg/pull/61271 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61273) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6608) 
- [x] https://github.com/WordPress/gutenberg/pull/60642 - @huubl | Trac ticket | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6716) 
~~- [ ] https://github.com/WordPress/gutenberg/pull/61351 - @Mamaduka | Trac ticket | Core backport PR~~
Auto synced
- [x] ~~https://github.com/WordPress/gutenberg/pull/61321 - @t-hamano | Trac ticket | Core backport PR~~

### 📁 wordpress-6.5

- [x] https://github.com/WordPress/gutenberg/pull/61080 - @t-hamano | [Trac ticket](https://core.trac.wordpress.org/ticket/61109) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6480) 

### 📁 ~~wordpress-6.4~~

- [x] ~~https://github.com/WordPress/gutenberg/pull/60148 - @interdevel | Trac ticket | Core backport PR~~
See https://github.com/WordPress/gutenberg/pull/60148#issuecomment-2088186433.

---
### 📄 layout.php

- [x] https://github.com/WordPress/gutenberg/pull/60976 - @tellthemachines | Trac ticket | Core backport PR 
See below.
- [x] https://github.com/WordPress/gutenberg/pull/60716 - @richtabor | Trac ticket | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6664)
- [x] ~~https://github.com/WordPress/gutenberg/pull/60652 - @tellthemachines | Trac ticket | Core backport PR~~
**Note: this one is due for 6.7.**
- [x] ~~https://github.com/WordPress/gutenberg/pull/60148 - @interdevel | Trac ticket | Core backport PR~~ 
See https://github.com/WordPress/gutenberg/pull/60148#issuecomment-2088186433.
- [x] ~~https://github.com/WordPress/gutenberg/pull/59483 - @noisysocks | Trac ticket | Core backport PR~~
**Note: this one is due for 6.7.**
~~- [ ] https://github.com/WordPress/gutenberg/pull/59452 - @tellthemachines | Trac ticket | Core backport PR~~
See below.
- [x] https://github.com/WordPress/gutenberg/pull/59057 - @tellthemachines | Trac ticket | Core backport PR 
- [x] https://github.com/WordPress/gutenberg/pull/58539 - @tellthemachines | Trac ticket | Core backport PR 
- [x] https://github.com/WordPress/gutenberg/pull/61392 - @tellthemachines | Trac ticket | Core backport PR 

### 📄 elements.php

- [x] https://github.com/WordPress/gutenberg/pull/59538 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/60681) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6214) 
- [x] https://github.com/WordPress/gutenberg/pull/59535 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/60681) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6214) 
- [x] ~~https://github.com/WordPress/gutenberg/pull/59533 - @tellthemachines | Trac ticket | Core backport PR~~
**Note: this was superseded by #59535**

### 📄 typography.php

~~- [ ] https://github.com/WordPress/gutenberg/pull/59531 - @t-hamano | Trac ticket | Core backport PR~~
See below. 
- [x] https://github.com/WordPress/gutenberg/pull/58362 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61118) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6477)

### 📄 background.php

~~- [ ] https://github.com/WordPress/gutenberg/pull/59889 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482)~~
See below.
~~- [ ] https://github.com/WordPress/gutenberg/pull/59354 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482)~~
See below.
~~- [ ] https://github.com/WordPress/gutenberg/pull/61387 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482)~~
See below.
 
### 📄 shadow.php

- [x] https://github.com/WordPress/gutenberg/pull/59887 - @colinduwe | [Trac ticket](https://core.trac.wordpress.org/ticket/60784) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6279)

### 📄 duotone.php

- [x] https://github.com/WordPress/gutenberg/pull/59764 - @ajlende | [Trac ticket](https://core.trac.wordpress.org/ticket/61271) | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6719)

### 📄 block-style-variations.php
- [x] https://github.com/WordPress/gutenberg/pull/57908 - @aaronrobertshaw  | [Trac ticket](https://core.trac.wordpress.org/ticket/61312) | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6662)

---
### 📄 editor-settings.php

- [x] ~~https://github.com/WordPress/gutenberg/pull/59707 - @SantosGuillamot | Trac ticket | Core backport PR~~
Kept as an experiment.
- [x] ~~https://github.com/WordPress/gutenberg/pull/60813 - @oandregal~~
No need to backport as it's Gutenberg-only code.
- [x] https://github.com/WordPress/gutenberg/pull/59052 - @noisysocks | Trac ticket | Core backport PR 
Adding an experimental flag, no need to backport.
- [x] https://github.com/WordPress/gutenberg/pull/59051 - @tellthemachines | Trac ticket | Core backport PR 
### 📄 kses.php

- [x] https://github.com/WordPress/gutenberg/pull/58539 - @tellthemachines | Trac ticket | Core backport PR

### 📄 blocks.php

- [x] https://github.com/WordPress/gutenberg/pull/61029 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/61274) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6609)

---
## 📄 class-wp-theme-json-gutenberg.php

- [x] https://github.com/WordPress/gutenberg/pull/61033 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/61119) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6475) 
- [x] https://github.com/WordPress/gutenberg/pull/61026 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/61120) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6478) 
- [x] https://github.com/WordPress/gutenberg/pull/61030 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/61121) | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6479)
- [x] https://github.com/WordPress/gutenberg/pull/58409 - @ajlende | Trac ticket | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6616) 
- [x] https://github.com/WordPress/gutenberg/pull/59531 - @t-hamano | [Trac ticket](https://core.trac.wordpress.org/ticket/61256) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6590) 
  - [x] https://github.com/WordPress/gutenberg/pull/61182 - @t-hamano | [Trac ticket](https://core.trac.wordpress.org/ticket/61256) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6590) 
- [x] https://github.com/WordPress/gutenberg/pull/59454 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482) 
- [x] https://github.com/WordPress/gutenberg/pull/42084 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61135) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6489) 
- [x] https://github.com/WordPress/gutenberg/pull/59889 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482) 
- [x] https://github.com/WordPress/gutenberg/pull/59809 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482) 
- [x] https://github.com/WordPress/gutenberg/pull/59938 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61135) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6489) 
- [x] https://github.com/WordPress/gutenberg/pull/58362 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61118) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6477)
- [x] https://github.com/WordPress/gutenberg/pull/59354 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482) 
- [x] https://github.com/WordPress/gutenberg/pull/59452 - @tellthemachines | Trac ticket | Core backport PR 
- [x] ~~https://github.com/WordPress/gutenberg/pull/58991~~ +
  - [x] ~~https://github.com/WordPress/gutenberg/pull/60611 - @tellthemachines | Trac ticket | Core backport PR~~ NOTE: these changes aren't stable enough to go into core this cycle so let's leave them for 6.7.
- [x] https://github.com/WordPress/gutenberg/pull/59258 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/60613) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6169) 
- [x] https://github.com/WordPress/gutenberg/pull/47271 - @fabiankaegy | [Trac ticket](https://core.trac.wordpress.org/ticket/61239) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6567) 
- [x] https://github.com/WordPress/gutenberg/pull/61387 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482)
- [x] https://github.com/WordPress/gutenberg/pull/61469 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482)
- [x] https://github.com/WordPress/gutenberg/pull/61638 - @tellthemachines | [Trac ticket](https://core.trac.wordpress.org/ticket/61165) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6633) 
  - [x] https://github.com/WordPress/gutenberg/pull/60106 - @tellthemachines | [Trac ticket](https://core.trac.wordpress.org/ticket/61165) | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6633)
  - [x] https://github.com/WordPress/gutenberg/pull/60228 - @tellthemachines | [Trac ticket](https://core.trac.wordpress.org/ticket/61165) | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6522)
  - [x] https://github.com/WordPress/gutenberg/pull/61340 - @tellthemachines | [Trac ticket](https://core.trac.wordpress.org/ticket/61165) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6633) 

---
## 📄 class-wp-theme-json-data-gutenberg.php

- [x] https://github.com/WordPress/gutenberg/pull/61262 - @kt-12 | [Trac ticket](https://core.trac.wordpress.org/ticket/61112) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6271) 

---
## 📄 class-wp-rest-global-styles-controller-gutenberg.php

- [x] ~~https://github.com/WordPress/gutenberg/pull/61808 - @ramonjd | Trac ticket | Core backport PR~~

---
## 📄 class-wp-theme-json-schema-gutenberg.php

- [x] https://github.com/WordPress/gutenberg/pull/61328 - @ajlende | Trac ticket | Core backport PR 

---
## 📄 ~~global-styles-and-settings.php~~

- [x] ~~https://github.com/WordPress/gutenberg/pull/60611 - @shail-mehta | Trac ticket | Core backport PR~~
_Should be handled with https://github.com/WordPress/gutenberg/pull/58991._

---
## 📄 interactivity-api.php

- [x] https://github.com/WordPress/gutenberg/pull/60514 - @DAreRodz | [Trac ticket](https://core.trac.wordpress.org/ticket/61171) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6527) 

---
## 📄 class-wp-duotone-gutenberg.php

- [x] ~~https://github.com/WordPress/gutenberg/pull/59764 - @ajlende | Trac ticket | Core backport PR~~
See above

---
## 📄 blocks.php

- [x] ~~https://github.com/WordPress/gutenberg/pull/60098 - @tellthemachines | Trac ticket | Core backport PR~~ Note: this was a Gutenberg-only fix, no need to sync to core. 
- [x] https://github.com/WordPress/gutenberg/pull/51491 - @carolinan | Trac ticket | Core backport PR 
Automatically synced
- [x] https://github.com/WordPress/gutenberg/pull/56469 - @carolinan | Trac ticket | Core backport PR 
Automatically synced

---
## 📄 client-assets.php

- [x] ~~https://github.com/WordPress/gutenberg/pull/59725 - @shail-mehta | Trac ticket | Core backport PR~~
GB only code.
- [x] https://github.com/WordPress/gutenberg/pull/61692 - @youknowriad | [Trac ticket](https://core.trac.wordpress.org/ticket/61324) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6678)

---
# 📁 phpunit

- [ ] https://github.com/WordPress/gutenberg/pull/58975 - @scruffian | [Trac ticket](https://core.trac.wordpress.org/ticket/61267) | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6603/files)
NOT URGENT
- [x] https://github.com/WordPress/gutenberg/pull/60063 - @madhusudhand | [Trac ticket](https://core.trac.wordpress.org/ticket/60784) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6279) 
Has item above.

<details><summary>
The rest is tracked in items above, not sure why these are duplicated.
</summary>

- [ ] https://github.com/WordPress/gutenberg/pull/61033 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/61119) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6475) 
- [x] https://github.com/WordPress/gutenberg/pull/59538 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/60681) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6214) 
- [ ] https://github.com/WordPress/gutenberg/pull/60228 - @tellthemachines | Trac ticket | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6633)
- [ ] https://github.com/WordPress/gutenberg/pull/60106 - @tellthemachines | [Trac ticket](https://core.trac.wordpress.org/ticket/61165) | [Core backport PR ](https://github.com/WordPress/wordpress-develop/pull/6633)
- [x] https://github.com/WordPress/gutenberg/pull/42084 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61135) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6489) 
- [ ] https://github.com/WordPress/gutenberg/pull/59889 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482) 
- [ ] https://github.com/WordPress/gutenberg/pull/59809 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482) 
- [x] https://github.com/WordPress/gutenberg/pull/58362 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61118) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6477)
- [x] https://github.com/WordPress/gutenberg/pull/59535 - @aaronrobertshaw | [Trac ticket](https://core.trac.wordpress.org/ticket/60681) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6214) 
- [ ] https://github.com/WordPress/gutenberg/pull/59354 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482) 
- [x] https://github.com/WordPress/gutenberg/pull/59258 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/60613) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6169) 
- [x] https://github.com/WordPress/gutenberg/pull/58539 - @tellthemachines | Trac ticket | Core backport PR 
- [ ] https://github.com/WordPress/gutenberg/pull/60189 - @ockham | Trac ticket | Core backport PR 
- [x] ~~https://github.com/WordPress/gutenberg/pull/59402 - @matiasbenedetto | Trac ticket | Core backport PR~~
These were removed because they are now [part of core](https://github.com/WordPress/wordpress-develop/tree/trunk/tests/phpunit/tests/fonts). 
- [x] https://github.com/WordPress/gutenberg/pull/58922 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61099) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6460) 
- [ ] https://github.com/WordPress/gutenberg/pull/61387 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61123) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6482)
- [ ] https://github.com/WordPress/gutenberg/pull/61717 - @t-hamano | [Trac ticket](https://core.trac.wordpress.org/ticket/61256) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6590)

</details>

---
# 📁 packages

### 📄 class-wp-style-engine-css-rule.php

- [x] https://github.com/WordPress/gutenberg/pull/58922 - @ramonjd | [Trac ticket](https://core.trac.wordpress.org/ticket/61099) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6460) 

---

# People

- [x] @shail-mehta
- [x] @fabiankaegy
- [x] @carolinan
- [x] @Mamaduka
- [x] @ellatrix
- [x] @interdevel
- [x] @tellthemachines
- [x] @richtabor
- [x] @noisysocks
- [x] @aaronrobertshaw
- [x] @t-hamano
- [x] @ramonjd
- [x] @colinduwe
- [x] @ajlende
- [x] @SantosGuillamot
- [x] @oandregal
- [x] @DAreRodz
- [x] @ockham
- [ ] @scruffian
- [x] @matiasbenedetto
- [x] @youknowriad

**Comment by Mamaduka** [comment]
I already have a backport ticket for my items. I'll try to finalize it this week. Ticket - https://core.trac.wordpress.org/ticket/61023.

**Comment by oandregal** [comment]
I've marked https://github.com/WordPress/gutenberg/pull/60813 as done and left a comment: this is gutenberg-only code that doesn't need to be backported.

**Comment by colinduwe** [comment]
Here's the backport ticket for shadow.php
https://core.trac.wordpress.org/ticket/60784

**Comment by tellthemachines** [comment]
I have a draft in progress for the style engine changes; updated the description with the link.

At this point it's unlikely that #59483 and #60652 will be added to core. I've left them on the list so we know they weren't missed but crossed them out with a note.

Also, I think everything inside `editor-settings.php` can safely be ignored? It's all related to adding and removing Gutenberg experiments.

**Comment by aaronrobertshaw** [comment]
There's a single backport (https://github.com/WordPress/wordpress-develop/pull/6214) to cover both https://github.com/WordPress/gutenberg/pull/59535 & https://github.com/WordPress/gutenberg/pull/59538 for the elements block support.

**Comment by t-hamano** [comment]
I added #61080 to the list.

**Comment by aaronrobertshaw** [comment]
Backports are now available for:
- https://github.com/WordPress/gutenberg/pull/61033
- https://github.com/WordPress/gutenberg/pull/61026
- https://github.com/WordPress/gutenberg/pull/61030 

Ticket and backport PR links have been added to this issue's description.

**Comment by tellthemachines** [comment]
Draft for grid column and row spans [here](https://github.com/WordPress/wordpress-develop/pull/6493), still needs adding tests.

**Comment by fabiankaegy** [comment]
I added https://github.com/WordPress/gutenberg/pull/47271 to the list

**Comment by petitphp** [comment]
PR [Block editor: localize search suggestions' post type in LinkControl component](https://github.com/WordPress/gutenberg/pull/58638) is ready to be merged.

Associated backport is available : [Trac ticket](https://core.trac.wordpress.org/ticket/61254) | [Core backport PR](https://github.com/WordPress/wordpress-develop/pull/6112)

**Comment by scruffian** [comment]
Added a [PR](https://github.com/WordPress/wordpress-develop/pull/6603/files) and [a ticket](https://core.trac.wordpress.org/ticket/61267) for the theme JSON changes.

**Comment by scruffian** [comment]
Added [a PR](https://github.com/WordPress/wordpress-develop/pull/6607) and [a trac ticket](https://core.trac.wordpress.org/ticket/61271) for the Duotone backport.

**Comment by joemcgill** [comment]
Not sure where this belongs, necessarily, but #61262 is being applied to Core in https://core.trac.wordpress.org/ticket/61112.

**Comment by aaronrobertshaw** [comment]
Added a [PR](https://github.com/WordPress/wordpress-develop/pull/6609) and [trac ticket](https://core.trac.wordpress.org/ticket/61274) for [extension](https://github.com/WordPress/gutenberg/pull/61029) to block style registration.

**Comment by ellatrix** [comment]
Updated the issue with the latest PRs until today.

**Comment by t-hamano** [comment]
Just a question; Should we add the `gutenberg-merge` keyword to the core ticket? I couldn't find any documentation about this label.

Similar question on Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1716533231110759?thread_ts=1716367176.433729&cid=C02QB2JS7

**Comment by tellthemachines** [comment]
@t-hamano yes the Trac ticket should have the `gutenberg-merge` keyword. It's not in the dropdown but there's an option to add keywords manually. It's been in use for maybe a year or two now, but unsure if it was ever documented - the processes around merging GB to Core keep evolving so documentation tends to quickly become outdated 😅

**Comment by aaronrobertshaw** [comment]
There's a new [backport PR](https://github.com/WordPress/wordpress-develop/pull/6633) available to cover all the global styles CSS specificity changes from the following Gutenberg PRs:

- https://github.com/WordPress/gutenberg/pull/60106
- https://github.com/WordPress/gutenberg/pull/60228
- https://github.com/WordPress/gutenberg/pull/61340
- https://github.com/WordPress/gutenberg/pull/61638

I've updated the issue description acordingly.

**Comment by tellthemachines** [comment]
👀 I see that #60716 hasn't been done yet, I'll put up a quick PR for that one!

Edit: done in https://github.com/WordPress/wordpress-develop/pull/6664

**Comment by aaronrobertshaw** [comment]
Added a [PR](https://github.com/WordPress/wordpress-develop/pull/6662) and [Ticket](https://core.trac.wordpress.org/ticket/61312) for section styles backport.

**Comment by ellatrix** [comment]
All backports for Beta 1 are done. In time, I'll create a new (smaller) issues with any new backports for Beta 2.
