### ISSUE TITLE
DataViews for Posts, Categories and Tags

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#62371]
Similarly to the pages, patterns and templates pages in the site editor, we should explore how we can leverage the same DataViews UIs, frame, editor, navigation... to power the Posts section of WP-Admin as part of the Admin redesign project.

There are a lot of challenges here:

 - Reusing the "pages" dataviews without duplicating all the code.
 - Reusing the site editor shell, navigation menus and routing logic
 - Generating forms for categories and tags creation and modification without necessarily creating custom code #59745 
 - Extensibility #61084 
 - Backward compatibility
 - Transition 

There's a lot to cover and a lot of uncertainties, for these reasons, I'm proposing that we start a new experimental page in the Gutenberg plugin, where we explore a new page that could serve as a playground to explore these ideas and address all the blockers. 

## Task list:

 - [x] Bootstrap a site-editor like shell #62409 
 - [x] Add the "posts" dataviews page. (@ntsekouras)
 - [ ] Add the "categories" dataviews page.
 - [ ] Add the "tags" dataviews page.
 - [ ] Leverage DataViews forms to implement "Add new category" and "Add new tag" (and edit forms as well)

**Comment by fabiankaegy** [comment]
Thank you for creating this and starting this work :) 

I'm really excited about this one! As you mention there are many challenges / open questions. The main things for me are all focussed around what the rollout of the "Site Editor Frame" will mean to a lot of the other areas of the WordPress Admin. 

Will this experimental posts screen display the old traditional WP left sidebar? Will it feature the admin bar? Admin notifications etc? Or will it replace the entire screen with the site editor like experience? 

So essentially which of these three approaches are we going to take with this? 

| Table Only | Content Area Only | Entire Screen |
|--------|--------|--------|
| ![CleanShot 2024-06-06 at 19 36 48@2x](https://github.com/WordPress/gutenberg/assets/20684594/def56396-99d1-43c6-95f1-efd4f9247fae) | ![CleanShot 2024-06-06 at 19 36 48@2x copy](https://github.com/WordPress/gutenberg/assets/20684594/2c4688ab-a913-4c96-9b2a-9ec4ce5c4063) | ![CleanShot 2024-06-06 at 19 36 48@2x copy 2](https://github.com/WordPress/gutenberg/assets/20684594/b77c58e0-96eb-4141-a461-0ce719ba66c4) |

**Comment by youknowriad** [comment]
> Or will it replace the entire screen with the site editor like experience?

This is how I was going to experiment initially. I'm happy to iterate on these things though as the design settles. Would love to have some mockups to base the initial work on but I'm not too concerned.

**Comment by youknowriad** [comment]
I added some tasks to the issue for folks that want to help. Feel free to graph a task and give it a try.

**Comment by ntsekouras** [comment]
I can try to do `posts` page for start.

**Comment by dannyreaktiv** [comment]
Hi, I'm really interested in these DataViews-powered pages.

Would there be a way to hook into the edit URL/action for the objects? (For example, to offer a custom edit React-based experience rather than the Block Editor)

**Comment by youknowriad** [comment]
@dannyreaktiv Thanks for your interest. I think your use-case makes sense. I think it's fits more with the routing work / navigation customization and less about dataviews but it's definitely something that should be enabled. (Related issue #60584)

**Comment by t-hamano** [comment]
This issue has been punted to 6.8 and has not seen any activity since. Let's move this issue to the 6.9 Editor Task Board and see what can be done in 6.9.

**Comment by youknowriad** [comment]
I think for now, we should remove these from the milestones until it's prioritized a bit more.

**Comment by youknowriad** [comment]
I'm going to close this issue for now. This served its purpose to allow us to build a solid infrastructure. Tracked here [#70862](https://github.com/WordPress/gutenberg/issues/70862)

When it comes the time to take over the whole screen, it's going to be a quick change.
