### ISSUE TITLE
Tracking issue: Further advancing data views

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#63128]
### View options
- [x] #63195
- [x] https://github.com/WordPress/gutenberg/issues/57669
- [x] https://github.com/WordPress/gutenberg/issues/63414
- [x] https://github.com/WordPress/gutenberg/issues/63872
- [x] https://github.com/WordPress/gutenberg/issues/65600

### Bulk actions / editing
- [x] #63193
- [ ] Quick editing https://github.com/WordPress/gutenberg/issues/55101
- [x] https://github.com/WordPress/gutenberg/issues/63150

### Fields
- [x] #63199
- [ ] https://github.com/WordPress/gutenberg/issues/58012
- [x] Pages: Include avatar in Author field (@jorgefilipecosta)
- [ ] https://github.com/WordPress/gutenberg/issues/57596

### Filtering
- [x] https://github.com/WordPress/gutenberg/issues/60696 (@jorgefilipecosta)
- [x] https://github.com/WordPress/gutenberg/issues/60468
- [x] https://github.com/WordPress/gutenberg/issues/60472
- [x] https://github.com/WordPress/gutenberg/issues/62057
- [ ] https://github.com/WordPress/gutenberg/issues/59696
- [x] https://github.com/WordPress/gutenberg/issues/63152

### General polish
- [x] List / Table layout – selected item stroke should be tinted blue. (@jorgefilipecosta)
- [ ] https://github.com/WordPress/gutenberg/issues/56199
- [ ] https://github.com/WordPress/gutenberg/pull/62028
- [x] https://github.com/WordPress/gutenberg/issues/61245
- [x] Pages: Trash view should default to table layout (@jorgefilipecosta)
- [x] Posts: Trash view should default to table layout
- [x] https://github.com/WordPress/gutenberg/issues/63675
- [x] Use 'raquo' icons for pagination. ([PR](https://github.com/WordPress/gutenberg/pull/63594))
- [ ] Sticky actions column in table layout https://github.com/WordPress/gutenberg/pull/65086
- [ ] https://github.com/WordPress/gutenberg/issues/62748
- [x] https://github.com/WordPress/gutenberg/pull/63299
- [x] #63302
- [ ] https://github.com/WordPress/gutenberg/issues/60847
- [ ] https://github.com/WordPress/gutenberg/issues/59832
- [x] https://github.com/WordPress/gutenberg/issues/63153
- [ ] https://github.com/WordPress/gutenberg/issues/58198
- [ ] https://github.com/WordPress/gutenberg/issues/63324
- [ ] https://github.com/WordPress/gutenberg/issues/63897
- [x] Add marks to Preview Size control (blocked by https://github.com/WordPress/gutenberg/issues/64481)
- [x] #65234

### New features
- [x] Add support for hierarchy https://github.com/WordPress/gutenberg/issues/55957
- [x] https://github.com/WordPress/gutenberg/issues/60630 (@jorgefilipecosta)
- [ ] https://github.com/WordPress/gutenberg/issues/60891 (@jorgefilipecosta)
- [x] https://github.com/WordPress/gutenberg/issues/63719 (@jorgefilipecosta)

### Performance
- [x] https://github.com/WordPress/gutenberg/issues/63151

### Bugs
- [x] https://github.com/WordPress/gutenberg/issues/63472
- [x] #63943
- [ ] https://github.com/WordPress/gutenberg/issues/64612

**Comment by ntsekouras** [comment]
I made a small demo for the upcoming [Hallway Hangout](https://make.wordpress.org/core/2024/07/09/hallway-hangout-lets-chat-about-whats-next-in-gutenberg-2/) to showcase some progress around DataViews, [DataForms](https://github.com/WordPress/gutenberg/issues/59745) and [admin redesign ](https://github.com/WordPress/gutenberg/issues/62371)after WP 6.6. I'm sharing here as a small status update.

https://github.com/user-attachments/assets/626e8316-cd1b-471f-b6df-c10f3e61c1d1

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/65086 implements sticky actions in table layout.

**Comment by youknowriad** [comment]
It's not clear to me what this tracking issue is about. How is it different than [#55083](https://github.com/WordPress/gutenberg/issues/55083)

**Comment by jameskoster** [comment]
This issue arose from feedback after 6.6, as a list of items to prioritise for 6.7. Please go ahead and close, merge, update labels as you see fit :)

**Comment by youknowriad** [comment]
I see so it's one of those iteration issues. I'll leave it open and may circle back to triage it properly.

**Comment by youknowriad** [comment]
I did triage the parent issue, so I think we can close this for now.
