### ISSUE TITLE
Writing and Editing Flow / Block Editor Core Polish

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#63255]
_More to come... We should also triage all the feature labels._

## Multi selection ([more](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Block+Multi+Selection%22))

- [ ] #27221
- [ ] #16206
- [x] #53128
- [x] #60025
- [ ] #56068
- [ ] #52745
- [ ]  #63259
- [x] #58788
- [ ] #54193
- [ ] #39456
- [x] #64451
- [ ] #65645
- [ ] #72512

## Pointer

- [x] #63260
- [ ] #9063

## Keyboard ([more](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Writing+Flow%22))

- [x] #63654
- [x]  #44753
- [ ] #53674
- [ ] #63261
- [x] #63262
- [ ]  #63484
- [ ] #34215
- [ ] #21558
- [ ] #9880
- [x]  #62224
- [ ]  #16435
- [x] #56173
- [ ] #59709
- [ ] #64235

## Drag 'n' drop ([more](https://github.com/WordPress/gutenberg/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Drag+and+Drop%22))

- [ ] #54952
- [ ] #63267
- [ ] #29931
- [ ] #23491
- [x]  #9783
- [ ] #44064
- [ ] #44292
- [ ] #24750
- [ ] #24770
- [x] #29511
- [x] #35262
- [ ] #3339

## List ([more](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+List%22))

- [ ] Cannot Tab to indent for multi-selected list items
- [ ] #40979
- [ ]  #21558
- [x] #55757
- [x] #56223
- [x] #62224
- [x] #61716
- [ ]  #45754

## Quote ([more](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+Quote%22))

- [ ]  #59709
- [ ] #61209
- [ ] Consider showing quote as single block if it has only one paragraph (can this be generalised)?

## Image & Gallery ([more](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+Image%22%2C%22%5BBlock%5D+Gallery%22))

- [ ] #47200

## Paste ([more](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Paste%22))

- [x] #60811
- [x] #51047
- [ ] #45774
- [ ] #42570
- [ ] #48040
- [x] #33312
- [ ] #52743
- [ ] #32917
- [x] #63241
- [ ]  #56062
- [ ] #26713
- [ ] #22339
- [x] #56444
- [ ] #73092 

## Transforms ([more](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Block+Transforms%22))

- [ ]  #63635
- [x] #30775 
- [x] #63422
- [ ] #58042
- [ ] #22478
- [ ] #52857

## Convert to Blocks ([more](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Convert%20to%20Blocks))

- [x] #63022

## Navigation/select mode

- [x]  #30155

## Rich Text

- [ ] #38703
- [x] #16627
- [ ] #73022

## UI

- [x] #61196
- [ ]  Can't use arrow down to move to end of link input.
- [ ]  Popover may go offscreen on small screens.
- [x]  #59242
- [ ]  #33494
- [x] #63434
- [ ] #63844
- [ ] #61435

**Comment by ktmn** [comment]
> Pointer
> In-between Inserter: can't scroll over it #63260

Maybe worth mentioning - I don't think I've used that inserter ever. When I get to the editor for the first time I turn off full screen, enable top toolbar and make the list view always open. If there was a preference to disable this inserter I would love to add it to the list of things to configure as well. 

Not that the inserter is inherently bad, it's just that my preference is to insert a block before/after the selected block and use the `/` prefix to find the block I want (or paste the blocks I already have in the clipboard), rather than guess where I need to hover and wait for the inserter to appear (or sometimes not appear at all, for some reason) and then open the block selection popover. 

It's no doubt useful for most people, but given that I'm never using it, whenever it appears it's always an unwanted experience. Doesn't bother me enough to like add custom CSS to hide it, but if there was a toggle I'd use it. Seems like it could skip doing some work as well if it was disabled: https://github.com/WordPress/gutenberg/blob/669002199656f4fa8c31bfff1df76783d3bcb4d1/packages/block-editor/src/components/block-list/use-in-between-inserter.js#L38

**Comment by ellatrix** [comment]
@ktmn Honestly, I never use it either. But I also mostly just write text. If I need to add a block, I just select a block and press Enter. It would be great if others that do use it could give feedback. For those of use that don't use it, it really gets in the way of editing posts.

**Comment by mtias** [comment]
I'd be fine exploring a preference around this. I was watching some user test where people really relied on the visible sibling inserter, so I don't think it can be off by default. The slash inserter will remain a power use feature.

Side note, but we need to really make some progress on the "setup workflow" to expose some of these preferences (top toolbar, always open panel, text buttons, etc) since it can drastically improve the experience for some users.

**Comment by ellatrix** [comment]
> The slash inserter will remain a power use feature.

I wasn't talking about the slash inserter btw (I never use that one), but the empty paragraph inserter. But yes, I think it's useful in certain cases, but maybe not so much in between paragraphs of text.

**Comment by ellatrix** [comment]
Also worth noting that the in-between inserter can be very random: it only works between blocks that have margin between them. In some tricky places like top/bottom or blocks closer together, it just doesn't work. Maybe we need to trigger it even when at the edge of the block, but in a way that doesn't interrupt text blocks.

**Comment by bph** [comment]
Maybe interesting for Paste section?  
- #63434

**Comment by t-hamano** [comment]
This tracking issue has had no activity since it was moved from the 6.7 Editor Tasks project to the 6.9 Editor Tasks project. Let's punt it to 7.0.

**Comment by annezazu** [comment]
Moving this to punted to 7.2 as nothing landed for 7.1 afaik.
