### ISSUE TITLE
Improve Styles > Typography panel 

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#63503]
Quite a few additions have been added to the Styles > Typography panel, but these changes were done in a piecemeal manner rather than following a cohesive plan.

Now that we have these pieces in place, let's explore how to clean up this panel and make it much more useful as a key component of styling a site's typography. 

### Tasks
- [x] https://github.com/WordPress/gutenberg/issues/63502
- [x] Remove "Manage fonts" button from Typography panel in favor of existing UX to open the Font Library
- [x] Use proper 40px height for all items within all ItemGroups. https://github.com/WordPress/gutenberg/pull/63125
- [ ] Figure out something better for font size presets. The current control on the panel is duplicative. 

### Current

![CleanShot 2024-07-12 at 16 47 16](https://github.com/user-attachments/assets/d647e1f9-8661-4823-84c4-018c0a5ae187)

**Comment by richtabor** [comment]
Also relevant (if the groupings are reverted): https://github.com/WordPress/gutenberg/issues/63505

**Comment by richtabor** [comment]
> Remove "Manage fonts" button from Typography panel in favor of existing UX to open the Font Library (backtracking on https://github.com/WordPress/gutenberg/pull/6212).

A potential path: 

![CleanShot 2024-07-12 at 17 23 12](https://github.com/user-attachments/assets/7c7c8991-2865-443e-9a28-dbc3e0763aa2)

- "Add fonts" uses the same style as "Add background image" and related buttons. 
- The vertical ellipsis icon becomes a popover for additional affordances for intent.

**Comment by akasunil** [comment]
https://github.com/WordPress/gutenberg/pull/63125 would fix `Use proper 40px height for all items within all ItemGroups.`
