### ISSUE TITLE
Components: Add eslint rules to prevent usage without `__next40pxDefaultSize` prop

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#63871]
To complete the full transition to the new default component sizes (#46741), we need to make sure all the in-repo usages have been transitioned manually. A repo-wide eslint rule should be added to ensure that new violations are not introduced.

## List of components

- [x] BorderBoxControl #64410
- [x] BorderControl #64410
- [x] BoxControl #65341
- [x] Button
    - [x] #64835
    - [x] Resolve existing violations (extracted to #65018)
- [x] ComboboxControl #64560
- [x] CustomSelectControl #64559
- [x] DimensionControl #64410
- [x] FocalPointPicker (could be switched without deprecation process?) #64456
- [x] FontSizePicker #64410
- [x] FormFileUpload (doesn't document prop yet) #64585
- [x] FormTokenField #64590
- [x] InputControl #64589
- [x] NumberControl #64561
- [x] QueryControls (could be switched without deprecation process?) #64457
- [x] RangeControl #64558
- [x] SelectControl
    - [x] #64486
    - [x] Resolve existing violations #64831
- [x] TextareaControl (needs 40px size) #64586
- [x] TextControl
    - [x] #64455
    - [x] Resolve existing violations #64594
- [x] ToggleGroupControl #64524
- [x] UnitControl 
    - [x] #64520
    - [x] Resolve existing violations (dependent on #64842) #65017

(May include a couple more components exported from `@wordpress/block-editor`) #64591
