### ISSUE TITLE
Command Package - Suggested Improvements

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#64127]
It would be good to see some extension of the existing Commands API to make it more flexible and useful to third-party plugins in particular. 

I am adding this tracking issue to keep a list of the main suggestions in one place. 

I am AFK for a while, so if anybody is interested in picking any of these up, go for it. Feel free to update/close this issue as appropriate.

I am unsure how these things fit in with our use of the underlying `cmdk` library, so feel free to update/delete any of the below if any of these changes are not compatible with that library.

## Suggested enhancements

- [ ] Allow the loader context to be an array. Currently, if a command needs to be in more than one context it needs to be duplicated. [Draft PR](https://github.com/WordPress/gutenberg/pull/55341).
- [ ] Add a `description` property to the command config. Currently, because the label is displayed to the user it can't always be used to provide a full description of the purpose of the command. A description field could be used in a tooltip as a potential solution to #54230 
- [ ] Add a `type` property  to the command config as a solution to #53190  - needs some discussion about how the taxonomy for this would work
- [ ] Add some sort of extensible schema. This could be as simple as a `metadata` property on the command config that the commands package passes around untouched that third parties can use to store more detailed command configurations for custom commands. Or maybe there is a better schema we can add that would also support the multi-step commands mentioned below (needs a separate issue adding for further discussion)?
- [ ] Add support for multi-step commands
