### ISSUE TITLE
Zoom Out Mode: Iteration issue: WordPress 6.7

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#64197]
This issue tries to summarize the changes we'd like to make to [Zoomed Out Mode](https://github.com/WordPress/gutenberg/issues/50739) in the WordPress 6.7 release:

## Next:

- [x] https://github.com/WordPress/gutenberg/issues/63861
- [x] https://github.com/WordPress/gutenberg/pull/64179
- [x] https://github.com/WordPress/gutenberg/issues/63866
- [x] https://github.com/WordPress/gutenberg/pull/63896
- [x] https://github.com/WordPress/gutenberg/issues/63862
- [x] https://github.com/WordPress/gutenberg/issues/63867
- [x] https://github.com/WordPress/gutenberg/pull/64193

## Later (WP 6.8 cycle)
- [ ] https://github.com/WordPress/gutenberg/issues/63863

## Bugs

Bugs can be viewed using [Zoom Out and Bug labels](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+label%3A%22%5BFeature%5D+Zoom+Out%22+label%3A%22%5BType%5D+Bug%22).

The project board for [WP 6.7 tracks the key bugs](https://github.com/orgs/WordPress/projects/210/views/1?filterQuery=zoom+out).

### Later

- [ ] https://github.com/WordPress/gutenberg/issues/64117
- [x] https://github.com/WordPress/gutenberg/issues/63681
- [x] https://github.com/WordPress/gutenberg/issues/63680
- [x] https://github.com/WordPress/gutenberg/issues/61044
- [x] https://github.com/WordPress/gutenberg/issues/63519
- [x] https://github.com/WordPress/gutenberg/issues/63522
- [x] https://github.com/WordPress/gutenberg/issues/63848
- [x] https://github.com/WordPress/gutenberg/issues/64256
- [x] https://github.com/WordPress/gutenberg/issues/64260

**Comment by scruffian** [comment]
Here's a demo of the work we have done so far:
https://drive.google.com/file/d/1aJFhPpiHqr22IxKSJWQMf98fsv93bgGI/view?usp=sharing

**Comment by getdave** [comment]
Some thoughts on ways of exiting Zoom Out mode:

- Exit zoom out and enter edit mode on double click on pattern
- Add "Edit" button to toolbar to allow users to exit zoom out mode.

I'll create an Issue for these.

Also some other things:

- remove unwanted whitespace beneath final pattern
- handle inserting sync patterns (UI and UX Issues present)
- add prompts to improve UX when entering _empty_ Page
- how do we _re-enter_ Zoom Out mode once we've exist by choosing to edit a specific section?
- experimental PR to try adding "Zoom back out" button to block toolbar in normal "Edit" mode when.
- Pattern search exits Zoom Out mode. We need to fix that.

**Comment by stokesman** [comment]
> * Add "Edit" button to toolbar to allow users to exit zoom out mode.

I’ve tried out the recently merged implementation and here’s my feedback related to it.
- It’s place among block related buttons is less prominent than seems warranted.
- Container blocks that aren’t full-width don’t feature the "Edit" button yet their content is not editable so it feels a bit incongruent that you can’t rely on a nearby button like for the full-width blocks.
- That a block has to be selected for the button to be available seems less than ideal.

Overall, it leaves me wishing for a better solution. So far the only idea I’ve had is a button near the canvas. To illustrate, I have a couple screen recordings.

Icon button in the top right:

https://github.com/user-attachments/assets/b58808a3-1d80-4187-a9ed-2b73fa1d65ea

Text button below:

https://github.com/user-attachments/assets/052ebe41-12f4-40e5-8aec-fe2bee3adc51

This placement might seem off-limits given how scrolling in zoom out currently works. However, if #64117 is to be fixed, I'm pretty confident it will involve applying the frame’s spacing outside of the scrolling area and making the area available. (This is from a branch where I was exploring a slider to control the zoom level and that’s what’s seen in the bottom right).

Also perhaps a button like this only needs to be displayed if zoom out is not explicitly triggered. If someone gets there through the Preview dropdown, it seems like they’d understand how to get back.

**Comment by getdave** [comment]
@youknowriad @mtias @richtabor I've been watching the advancement of the new "Edit" (previously "Select" and under the hood `navigation`) mode. Many of its affordances are remarkably similar to what we have in "Zoom Out" today. 

There are some exceptions in Zoom Out:

- vertical toolbar
- only sections are selectable - content is all locked.

...there are probably more.

However, I'm wondering if there's scope to look to merge these two modes? After all, I expect that users will probably want to make _basic_ edits whilst zoomed out (e.g. amend a heading). 

Perhaps we'd have some kind of "click through" whereby once a section is selected in zoom out you could click again to "activate" contentOnly editing on that section. 

I don't recall seeing an Issue capturing this so if it's something you think might be useful I can raise an Issue to track it.

**Comment by youknowriad** [comment]
Yes, I think it seems we can converge in terms of interaction model (selecting sections, potentially selecting content blocks as well) and we can leave the zoom-out mode about setting a zoom level instead.

We need to decide what to do with toolbar: should it switch to vertical toolbar when a zoom level is set or should it always stay consistent.

**Comment by getdave** [comment]
I think the UX for Zoomed Out is probably better as a vertical toolbar but I would defer to @WordPress/gutenberg-design on that one. Maybe @richtabor as he's been heavily involved in Zoom Out.

**Comment by getdave** [comment]
@youknowriad I [proposed merging the two modes](https://github.com/WordPress/gutenberg/issues/65736).

**Comment by getdave** [comment]
@draganescu @MaggieCabrera @jeryj @ajlende @youknowriad @talldan @richtabor 

I've drafted the following dev note for Zoom Out in WP 6.7. Feel free to edit/amend as required.


**Update**: [draft available on Make Blog](https://make.wordpress.org/core/?p=115826&preview=1&_ppp=a54982c044).


------

## Dev note for WordPress 6.7 (draft)

[Zoom Out in WordPress 6.7](https://github.com/WordPress/gutenberg/issues/64197), introduces a new way to easily create and edit content using Patterns rather than lower-level, individual blocks.

Accessible via a toggle in the editor toolbar, when activated the canvas will "zoom out" providing users with a high level view of the content currently being edited. The inserter also automatically enables this new feature when the patterns tab is activated, allowing users to quickly and easily build and/or edit their Page or Template using pre-configured Patterns.

Note that whilst in this mode, blocks outside the "main content" of the current post will be non-editable. This allows users to focus on easily dealing with larger areas of content.

### Theme Compatibility

To facilitate this feature, the Editor will attempt to detect the block which is acting as the "main content" of the current post type. This is achieved via a simple algorithm which optimises for detecting the Post Content (`core/post-content`) block, falling back to a Group with a `tagName` of `main` (i.e. the `<main>` HTML element).

https://github.com/WordPress/gutenberg/blob/7d60169ff4d991f463adb537de9df6abf965854c/packages/editor/src/components/provider/use-block-editor-settings.js#L149-L160

To maximise compatibility with this mode, Theme authors should update their templates to ensure their "main content" is wrapped with a Group block whose `tagName` attribute is configured as `main`. This can be found in the block's sidebar controls under `Advanced`. We recommend using a `core/group` as it is the most generic and flexible "sectioning element" in the editor.


### Decoupling of Zoom Out mode from "zooming" the canvas

As part of this effort, contributors have also elected to decouple the scaling of the Editor canvas from the "Zoom Out" editor mode. This is largely [in anticipation of future efforts around simplifying the editing experience](https://github.com/WordPress/gutenberg/issues/65736). As a result, invoking `zoom-out` editor mode will not longer automatically scale the Editor canvas. 

### Further reading:

- https://github.com/WordPress/gutenberg/issues/50739
- https://github.com/WordPress/gutenberg/issues/65736

**Comment by fabiankaegy** [comment]
@getdave The dev note is looking great to me! 

Feel free to publish it on the make blog and I will then reference it in the field guide :) This can be an independant dev note as far as I am concerned  👍 

In an ideal world I would love to include a quick video / screenshot similar to the ones we have in the Gutenberg Release posts that showcases the feature. 

Looking at the Gutenberg posts this image here has been used: 


![](https://make.wordpress.org/core/files/2024/09/Zoomed-out.png)

**Comment by draganescu** [comment]
I added a few edits @getdave

**Comment by getdave** [comment]
## Update for WordPress 6.7

I posted an update on Friday in WP Slack with my top of mind for the Zoom Out feature in 6.7:

- [ ] [Zooming In doesn't maintain scroll position](https://github.com/WordPress/gutenberg/issues/65884)
- [x] [Wide blocks shrink](https://github.com/WordPress/gutenberg/issues/63519)
- [x] [Vertical Toolbar Placement](https://github.com/WordPress/gutenberg/pull/65627) 
     - could be fixed by https://github.com/WordPress/gutenberg/pull/65627. 
     - [suggestion to remove the vertical toolbar entirely](https://github.com/WordPress/gutenberg/pull/66039).
- [x] [Zoom Out not persisting on template switch or Visual to Code Editor](https://github.com/WordPress/gutenberg/issues/65783) - should be fixed by https://github.com/WordPress/gutenberg/pull/65932 once it's been revised. Simple fix.
- [ ] [Drag and Drop zones inconsistency](https://github.com/WordPress/gutenberg/issues/65927) - this is a particular problem on Safari.
- [x] [No Patterns UX Issue](https://github.com/WordPress/gutenberg/issues/65833) - more [complex Issue](https://github.com/WordPress/gutenberg/issues/65833#issuecomment-2407551979). Some research but no PR.
- [x] [Scaling Issues](https://github.com/WordPress/gutenberg/issues/66099) - PRs in progress to resolve.
- [x] [Grid Block doesn't adapt to Zoom Out](https://github.com/WordPress/gutenberg/issues/65974) - issue for TT5 Theme

I'll update these as and when they are resolved.

**Comment by getdave** [comment]
@fabiankaegy [Dev note draft created on Make Blog](https://make.wordpress.org/core/?p=115826&preview=1&_ppp=a54982c044).

**Comment by fabiankaegy** [comment]
@getdave How do you feel about my suggestion the other day of including an image / video showcasing what it actually looks like in 6.7? 

Besides that this is good to go from my perspective  👍

**Comment by colorful-tones** [comment]
@getdave small edit from your [Dev Note preview](https://make.wordpress.org/core/?p=115826&preview=1&_ppp=a54982c044):

> editor mode will not longer automatically scale the Editor canvas.

should be: 

> editor mode will no longer automatically scale the Editor canvas.

**Comment by youknowriad** [comment]
Hey folks, just noting that the vertical toolbar has been removed in trunk in https://github.com/WordPress/gutenberg/pull/66039 as it suffers a few issues: doesn't scale well to other buttons like "change design", doesn't support text only buttons, feels disconnected from blocks when centered.

We can consider back-porting this change to 6.7 (it's several bug fixes at once). here's the corresponding manual cherry-pick #66200

**Comment by getdave** [comment]
## Update for WordPress 6.7

In general Zoom Out feels like it's in a good place. That said here are my top of mind items that we need to land prior to RC2:

- [x] [Restore ability to delete blocks in Zoom Out](https://github.com/WordPress/gutenberg/issues/66287) - there is a PR but it still needs work.
- [x] [Drag and Drop zones inconsistency](https://github.com/WordPress/gutenberg/issues/65927) - we have a PR which I believe fixes the Issue. Could do with a confidence check.
- [x] [Flex related layout bugs](https://github.com/WordPress/gutenberg/pull/66390) - this has spun out quite a bit but https://github.com/WordPress/gutenberg/pull/66390 looks like it could be the right bug fix to fully resolve. We really need to nail this down as there is too much flux here for this late in the cycle.
- [x] [Sidebar width Issue on small screens](https://github.com/WordPress/gutenberg/issues/66205) - minor debate about the proper solution but should be on track to be fixed.
- [ ] [Zooming In doesn't maintain scroll position](https://github.com/WordPress/gutenberg/issues/65884) - I believe @ajlende is exploring solutions.

Note that RC2 is on Tuesday October 29th, so we should look to release packages on Monday October 28th. Therefore all PRs should aim to land by Friday (or early Monday) latest.

cc @ndiego @ellatrix @colorful-tones @cbravobernal @kevin940726

**Comment by annezazu** [comment]
Let's close this out with 6.7 out the door and get a new one opened for 6.8. Thanks to everyone who contributed to this future.
