### ISSUE TITLE
6.6 Specificity/Style tracking issue

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#64243]
### To do / Needs investigation

- [ ] https://github.com/WordPress/gutenberg/issues/64225
- [ ] https://github.com/WordPress/gutenberg/issues/64856
- [ ] https://github.com/WordPress/gutenberg/issues/30725

### In progress

- [ ] https://github.com/WordPress/gutenberg/pull/64534 (this PR is quite large in scope, so a discussion might be needed around whether it's ok for 6.6)

### Released in 6.6.2

- [x] https://github.com/WordPress/gutenberg/pull/64076
- [x] https://github.com/WordPress/gutenberg/pull/63980
- [x] https://github.com/WordPress/gutenberg/pull/63918 (https://core.trac.wordpress.org/ticket/61748)
- [x] https://github.com/WordPress/gutenberg/pull/63726 (https://core.trac.wordpress.org/ticket/61704)
- [x] https://github.com/WordPress/gutenberg/pull/64458
- [x] https://github.com/WordPress/gutenberg/pull/64463

### Released in 6.6.1

- [x] https://github.com/WordPress/gutenberg/pull/63403
- [x] https://github.com/WordPress/gutenberg/pull/63406

**Comment by annezazu** [comment]
Thank you for opening and tracking this <3

**Comment by t-hamano** [comment]
I submitted #64785 regarding the conflict between element-level margin and layout-level margins.

**Comment by WilliamLeeks** [comment]
https://github.com/WordPress/gutenberg/issues/65329

`theme.json` is not overriding core styles when targeting nested elements.

**Comment by ramonjd** [comment]
closing this as we're at 7.0 soon - individual issues still open
