### ISSUE TITLE
Stabilize the `__experimentalDefaultControls` block supports property

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#64314]
Related to https://github.com/WordPress/gutenberg/issues/43241.

The `__experimentalDefaultControls` property lets developers choose which settings are displayed by default in the Editor for each block support. This property is often used when creating custom blocks that utilize block supports or when customizing the Editor experience. Removing the `__experimental` prefix will make it easier for third-party developers to confidently use this property.

- `__experimentalDefaultControls` → `defaultControls`

Note that in order to provide backward compatibility for block plugins out in the wild, fallback support for the existing `__experimental` prefix should be provided.

## Tasks

_This is a preliminary list based on the format of https://github.com/WordPress/gutenberg/issues/63001, but it is likely incomplete._

- [ ] Update the JS implementations of the default controls to point to the non `__experimental` prefix, falling back to the `__experimental` prefix if available.
- [ ] Update the `block.json` schema to support the non `__experimental` prefix
- [ ] Update the core blocks' `block.json` files to use the non `__experimental` prefixes
- [ ] [Update the supports documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/) to include a section about default controls.
- [ ] Update the `block.json` schema to remove the `__experimental` prefix. Note that the code in WordPress should still support the `__experimental` prefix, but at this stage, the experimental prefix will be treated as deprecated.

**Comment by rdhutchins** [comment]
If this isn't going to be completed any time soon, can we count on the __experimental version staying available? I don't see it documented anywhere official, just mentioned on GitHub issues and blog posts. Personally I find Gutenberg unusable when I have to constantly click to even make options visible (and not even saved between blocks!), but with this one minor adjustment to turn the most used controls on by default, it's much better.
