### ISSUE TITLE
Stabilize Border Block Support Keys

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#64312]
Related to: 

- https://github.com/WordPress/gutenberg/issues/63001 and
- https://github.com/WordPress/gutenberg/issues/43241

Borrowing from the format of https://github.com/WordPress/gutenberg/issues/63001, this issue outlines the tasks needed to stabilize the `__experimentalBorder` support. Doing so will make it easier for third-party extenders to confidently build custom blocks that provide border support and modify existing blocks with this support. 

Note that in order to provide backward compatibility for block plugins out in the wild, fallback support for the existing `__experimental` prefix should be provided.

Stabilize the following border block support and associated properties:

- `__experimentalBorder` → `border`
- `__experimentalBorder.color` → `border.color`
- `__experimentalBorder.radius` → `border.radius`
- `__experimentalBorder.style` → `border.style`
- `__experimentalBorder.width` → `border.width`

## Tasks

- [x] Update PHP block support code in `lib/block-supports/border.php` to use the non `__experimental` prefix
- [x]  Update the JS implementations of the border block supports to point to the non `__experimental` prefix
- [ ]  Update the `block.json` schema to support the non `__experimental` prefix
- [ ]  Update the core blocks' `block.json` files to use the non `__experimental` prefixes
- [ ]  [Update the supports documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/) to include a section for border support.
- [ ]  Update the `block.json` schema to remove the `__experimental` prefix. Note that the code in WordPress should still support the `__experimental` prefix, but at this stage, the experimental prefix will be treated as deprecated.

The PR for this stabilization effort should follow the approach used to stabilize the typography supports in https://github.com/WordPress/gutenberg/pull/63401.

**Comment by hbhalodia** [comment]
Hi @ndiego, I would like to work on the issue.

Thank You,

**Comment by hbhalodia** [comment]
Hi @ndiego, I have created a draft PR - https://github.com/WordPress/gutenberg/pull/64330, but I am seeing this PR needs lots of refactoring once the main referenced PR - https://github.com/WordPress/gutenberg/pull/63401/ is merged and working. This is because we can use a lot of things from the PR so we do not have redundant code issue happening.

Also, there are ongoing discussion happening on the typography supports stabilization, hence I am aiming to wait for the typography support stabilizing to get merged in trunk and then we can pick up the pace on this issue with the PR.

Though, I have once concern about the `border` supports, as the whole `border` is defined as `experimental` and not the inner supports, so if you can look at quickly on the PR if that is the way we can achieve to stabilize the border and have some initial feedbacks on the approach.

Thank You,

**Comment by ndiego** [comment]
@hbhalodia yes, any PR for this issue should follow the similar approach outlined in https://github.com/WordPress/gutenberg/pull/63401. I would also recommend waiting until that PR is successfully merged.

**Comment by hbhalodia** [comment]
Thanks for the response, we can wait until https://github.com/WordPress/gutenberg/pull/63401 PR gets merged.

**Comment by hadamlenz** [comment]
suspense! I hope it'll be backward compatible

**Comment by aaronrobertshaw** [comment]
https://github.com/WordPress/gutenberg/pull/63401 has been merged, so I think we're in a good spot to move forward on the border support stabilization. I've left a review on @hbhalodia's PR, https://github.com/WordPress/gutenberg/pull/64330.

I'm happy to pick up any block support stabilization tasks or move the existing efforts forward.

**Comment by aaronrobertshaw** [comment]
As discussed on #64330, I've spun up a fresh PR (https://github.com/WordPress/gutenberg/pull/66918) that expands on the stabilization approach pioneered via #63401. I plan to give it some testing tomorrow and will then flag it as being ready for review.

Kudos and props to @hbhalodia and @benazeer-ben for all their work to date 🙇 

I'll close the other open PRs so we can push the latest approach across the line.

**Comment by aaronrobertshaw** [comment]
_Quick update:_

There are two PRs around stabilizing block supports ready for extra eyes, testing, and review.

- [Border support stabilization](https://github.com/WordPress/gutenberg/pull/66918)
- [Stabilization of shared support flags](https://github.com/WordPress/gutenberg/pull/67018) e.g. `__experimentalDefaultControls` and `__experimentalSkipSerialization`

**Comment by aaronrobertshaw** [comment]
It looks like stabilization of experimental block supports will be punted for 6.8. See https://github.com/WordPress/gutenberg/pull/68163 and https://github.com/WordPress/gutenberg/pull/67729#issuecomment-2553200639 for context.

**Comment by ramonjd** [comment]
The work that's gone into this so far has been reverted in:

- https://github.com/WordPress/gutenberg/pull/68163

Thanks to everyone who helped move it forward, and tease out lessons for when folks return to it.

See background context: https://github.com/WordPress/gutenberg/pull/67729#issuecomment-2553200639
