### ISSUE TITLE
Tracking: Style Book iterative tasks

### ISSUE THREAD

**Issue by vcanales** [WordPress/gutenberg#64707]
Part of:

- https://github.com/WordPress/gutenberg/issues/41232

Several pieces comprise the work required to iterate over the discussion in #53431, so I'm starting this tracking issue to compile the efforts:

## TODO
- [ ] Implement layout/design in #53431 
- [ ] Create/collate example blocks for the landing category. Include said category. Add click events that open corresponding category tabs.
- [ ] Look at how themes can define their own examples for the "Overview" category.
- [ ] Come up with a way for the UI to display lots of categories.
- [ ] Create missing block examples where appropriate and possible.
       - Query Pagination Link (Previous)
       - Query Pagination Link (Next)
       - Post Comments Count
       - Post Comments Link 
       _The above blocks rely on block context data. Without that context they do not render anything._
- [x] https://github.com/WordPress/gutenberg/issues/62216
- [ ] https://github.com/WordPress/gutenberg/issues/53437

## In Progress
- [x] https://github.com/WordPress/gutenberg/pull/65619
- [ ] https://github.com/WordPress/gutenberg/pull/64705
- [x] https://github.com/WordPress/gutenberg/pull/65692
- [ ] https://github.com/WordPress/gutenberg/pull/64706
- [x] https://github.com/WordPress/gutenberg/pull/65430
- [x] https://github.com/WordPress/gutenberg/pull/65507
~https://github.com/WordPress/gutenberg/pull/64080~

## Misc bugs and enhancements

- [ ] https://github.com/WordPress/gutenberg/issues/65065
- [x] https://github.com/WordPress/gutenberg/issues/51121
- [ ] https://github.com/WordPress/gutenberg/issues/48152
- [ ] https://github.com/WordPress/gutenberg/issues/57297
- [x] https://github.com/WordPress/gutenberg/issues/65630
- [ ] https://github.com/WordPress/gutenberg/issues/57297

## Not planned
- [x] https://github.com/WordPress/gutenberg/issues/53432

**Comment by ramonjd** [comment]
> Come up with a way for the UI to display lots of categories.

Was playing around with something like this. Rough, but you get the idea:

https://github.com/user-attachments/assets/b3f52816-615a-4efe-9283-2e8f797fbea1

**Comment by ramonjd** [comment]
>  Look at how themes can define their own examples for the "Overview" category.

The MVP would be to create a static, curated list of Core blocks to display on the landing page. See: https://github.com/WordPress/gutenberg/issues/53431#issuecomment-2260240806

The style book landing page would, however, provide a convenient space to feature a theme's custom blocks or (one day) [patterns](https://github.com/WordPress/gutenberg/issues/53437).

That means that Gutenberg would need to define a, or piggyback off an existing, API to allow themes et. al to register blocks/patterns that should feature on the landing page. Ideally, the order in which they appear should be configurable.

Some random thoughts/options:

- Create a new core category/taxonomy for the style book landing page - one that blocks and patterns could share. Patterns can have one or more categories. Block cannot. It might be useful for blocks to also support category lists, or [subcategories](https://github.com/WordPress/gutenberg/pull/64706) so that they can "live" in two categories at once, for example, "text" and "featured/style-book/whatever"
- Build up on existing Block/Patterns API to support a flag during block registration, e.g., `$config['featured'] = true`. 
- Create an interface/function/hook to add blocks/patterns to the style book landing page that would, behind the scenes, add a custom, but "hidden" category/taxonomy to the block/pattern. E.g., `add_filter( 'add_to_style_book', $block_or_pattern_name, $order )`.
- ??

**Comment by ramonjd** [comment]
> Come up with a way for the UI to display lots of categories.


The tabs component is used to display the categories. The tab can display with horizontal scrolling —https://wordpress.github.io/gutenberg/?path=/story/components-tabs--size-and-overflow-playground — but it'd be good to be able scroll to the active tab.

**Comment by yogeshbhutkar** [comment]
## Refactor Blocks for Translatable Text in block.json's example attribute

Refactor the following blocks to implement translatable text in contrast to static text in the block.json example. Ensure that the text strings are properly marked for translation, and all necessary fields in block.json's example attribute are updated accordingly to support internationalization (i18n).

### Tracker

- [x] `comments-pagination-next`
- [x] `comments-pagination-previous`
- [x] `post-navigation-link`
- [x] `query-no-results`
- [x] `table-of-contents`

**Comment by ramonjd** [comment]
Closing for now.

**Comment by ramonjd** [comment]
Sorry I closed before I could comment properly. What I wanted to say was that we can track the issues individually and create a new tracking issue as this one is stale. 

In my opinion.
