### ISSUE TITLE
[Tracking issue] Update SlotFill Reference section to be inline the changes introduced in WordPress 6.6

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#64749]
## What problem does this address?
Since the 6.6 release, the majority of SlotFill components have been moved into the `@wordpress/editor` package.  The documentation needs to be updated to reflect that change.

Additionally, there should be a new section on how to conditionally render these slots to control if they are shown in the Edit Post and/or Site Edit screens.

## New
- [x] Add section on conditionally using slots - https://github.com/WordPress/gutenberg/pull/64807

## Updates
- [x] Update main readme to ensure example match copy - https://github.com/WordPress/gutenberg/pull/64751
- [x] https://github.com/WordPress/gutenberg/issues/57870 - https://github.com/WordPress/gutenberg/pull/64753
- [x]  Update [PluginBlockSettingsMenuItem](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-block-settings-menu-item/) documentation - https://github.com/WordPress/gutenberg/pull/64758
- [x] ~Update [PluginDocumentSettingPanel](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-document-setting-panel/) documentation~ Already updated
- [x] ~Update [PluginMoreMenuItem](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-more-menu-item/) documentation~ Already updated
- [x] ~Update [PluginPostPublishPanel](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-post-publish-panel/) documentation~ Already updated
- [x] ~Update [PluginPostStatusInfo](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-post-status-info/) documentation~ Already updated
- [x]  ~Update [PluginPrePublishPanel](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-pre-publish-panel/) documentation~ Already updated
- [x] Update [PluginSidebar](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-sidebar/) documentation - #64759
- [x] Update [PluginSidebarMoreMenuItem](https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-sidebar-more-menu-item/) documentation - https://github.com/WordPress/gutenberg/pull/64761
- [x] ~Update [Plugin Sidebar how-to guide](https://developer.wordpress.org/block-editor/how-to-guides/plugin-sidebar-0/)~ Already updated

**Comment by ryanwelcher** [comment]
Closing this as completed.
