### ISSUE TITLE
Table block polishing issues for 6.7

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#64809]
This is a non exhaustive list of issues we could aim to land for 6.7 to improve the user experience around this block.

More issues will be added and please feel free to add or suggest more to be included.

- [ ] https://github.com/WordPress/gutenberg/issues/61491
- [ ] https://github.com/WordPress/gutenberg/issues/42570
- [ ] https://github.com/WordPress/gutenberg/issues/56311
- [ ] https://github.com/WordPress/gutenberg/issues/45774

**Comment by joedolson** [comment]
I'd really like to also take this opportunity to address some of the accessibility gaps in the table block, if you think that's possible. 

Particularly:

https://github.com/WordPress/gutenberg/issues/41502
https://github.com/WordPress/gutenberg/issues/41014
https://github.com/WordPress/gutenberg/issues/24205

**Comment by colorful-tones** [comment]
@joedolson tjanks for flagging those. These Table block items will certainly be a stretch goal for me on top of my Editor Triage duties for 6.7. We’ll see! 🤞

**Comment by ndiego** [comment]
Seeing that Beta 1 is next week (October 1), I think we should remove from the 6.7 board and punt this to 6.8.

**Comment by annezazu** [comment]
Closing this in favor of https://github.com/WordPress/gutenberg/issues/32400
