### ISSUE TITLE
Tracking: A curated list of high-priority extensibility issues and enhancements

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#64848]
The following is a curated list of extensibility issues that have mostly been identified through various channels and events by DevRel teams, such as Hallway Hangouts, Developer Hours, the [#outreach channel](https://wordpress.slack.com/archives/C015GUFFC00) on Slack, and via the @WordPress/outreach group.

This is a tracking issue to help contributors prioritize issues and enhancements based on direct feedback from extenders. 

It is not an exhaustive list of every extensibility issue ([there's a label for that](https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BFeature%5D+Extensibility%22)). Instead these are oft-repeated blockers for adopting the block system and quality-of-life enhancements that folks want to see. The list is broken down into major categories.

## Theming

- [ ] https://github.com/WordPress/gutenberg/issues/59272
- [x] https://github.com/WordPress/gutenberg/issues/59965
- [ ] https://github.com/WordPress/gutenberg/issues/62661
- [ ] https://github.com/WordPress/gutenberg/issues/38277
- [ ] https://github.com/WordPress/gutenberg/issues/47837
- [x] https://github.com/WordPress/gutenberg/issues/62078
- [ ] https://github.com/WordPress/gutenberg/issues/43405
- [ ] https://github.com/WordPress/gutenberg/issues/47324

## Extending and Building Blocks

- [ ] https://github.com/WordPress/gutenberg/issues/38767
- [ ] https://github.com/WordPress/gutenberg/issues/47990
- [ ] https://github.com/WordPress/gutenberg/issues/41062

## Extending the Editor

- [ ] https://github.com/WordPress/gutenberg/pull/16384
- [ ] https://github.com/WordPress/gutenberg/pull/61768
- [ ] https://github.com/WordPress/gutenberg/pull/52261
- [x] https://github.com/WordPress/gutenberg/pull/50605
- [x] https://github.com/WordPress/gutenberg/pull/31984
- [ ] https://github.com/WordPress/gutenberg/issues/65005
- [ ] https://github.com/WordPress/gutenberg/issues/48068
- [ ] https://github.com/WordPress/gutenberg/issues/49887

## Stabilize experimental block supports

- [ ] https://github.com/WordPress/gutenberg/issues/63001
- [ ] https://github.com/WordPress/gutenberg/issues/64312
- [ ] https://github.com/WordPress/gutenberg/issues/64314

## Developer Experience

- [ ] https://github.com/WordPress/gutenberg/issues/39915
- [ ] https://github.com/WordPress/gutenberg/issues/64057

**Comment by annezazu** [comment]
Love this. Thank you for rounding up and summarizing!

**Comment by paaljoachim** [comment]
Thank you for this tracking issue Justin!
I have one more to the list.
Disable and trash default templates included in the theme one does not want to use. 

- #49640

**Comment by gziolo** [comment]
I landed today:
- https://github.com/WordPress/gutenberg/pull/64644

In effect, we could close some previous attempts:
- https://github.com/WordPress/gutenberg/pull/50605
- https://github.com/WordPress/gutenberg/pull/31984


Although looking at the code in PRs, I figured out that some attempts very more complex as they also tried to integrate more deeply into the editor screen by allowing to replace the visual code editor. We should revisit that later.

**Comment by simison** [comment]
I elaborated more in a new issue about future possibilities for extending preview menu and the canvas:

- https://github.com/WordPress/gutenberg/issues/65005

**Comment by paaljoachim** [comment]
It is difficult when the design shows one thing and the UI controls show something else.
When code has been added to Global styles and/or theme.json this should be reflected in the UI controls. Showing a consistent experience of design that is reflected through the UI controls. 

Local block appearance controls should reflect values from global styles / theme.json

- https://github.com/WordPress/gutenberg/issues/37752

**Comment by justintadlock** [comment]
New PRs for some of the above issues that could use some testing:

- https://github.com/WordPress/gutenberg/pull/65968
- https://github.com/WordPress/gutenberg/pull/65964
- https://github.com/WordPress/gutenberg/pull/65912

**Comment by bph** [comment]
There is also a need to address this: 

- #35848

**Comment by gziolo** [comment]
This one is in progress:
- https://github.com/WordPress/gutenberg/issues/49887

Related PR:
- https://github.com/WordPress/gutenberg/pull/66170

There is an ongoing discussion on how to shape this slot/fill pair so it doesn't get used as a way to promote plugin features instead of being helpful for the user to provide additional details and action items specific to the block type. I would appreciate any feedback you can provide on the topic.

**Comment by akshaya-rane** [comment]
The following tickets are **in Progress.** 

- [Allow to disable settings for specific blocks #38767](https://github.com/WordPress/gutenberg/issues/38767)
 Related PR https://github.com/WordPress/gutenberg/pull/66254

- [Provide ways to extend/customize the Global Styles sidebar #48068](https://github.com/WordPress/gutenberg/issues/48068)
 Related PR https://github.com/WordPress/gutenberg/pull/66282

The following tickets need a **review**. 

- [Stabilize Typography Block Supports Keys for WP 6.8 #63001](https://github.com/WordPress/gutenberg/issues/63001)
Related PR https://github.com/WordPress/gutenberg/pull/65964

- [Stabilize Border Block Support Keys for WP 6.8 #64312](https://github.com/WordPress/gutenberg/issues/64312)
Related PR https://github.com/WordPress/gutenberg/pull/65968

- [Stabilize the ](https://github.com/WordPress/gutenberg/issues/64314)__experimentalDefaultControls[ block supports property #64314](https://github.com/WordPress/gutenberg/issues/64314)
Related PR https://github.com/WordPress/gutenberg/pull/65912

The following ticket **concluded**. 
- [Allow/deny block use based on post-type or template context #41062](https://github.com/WordPress/gutenberg/issues/41062)
