### ISSUE TITLE
Update DocumentBar with post type label

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65167]
In an effort to improve the reference points between post types in the Site Editor, I propose removing the icons and using a visible label for the post types in the DocumentBar. 

### Tasks

- [x] Remove the icon. 
- [x] Add support for the post type label. 
- [x] If there's a post type label, place a `·` between them.

### Current 

<img width="800" alt="current" src="https://github.com/user-attachments/assets/403c3353-042a-47d0-917b-794d2261d45b">

### Proposed 

<img width="800" alt="proposed" src="https://github.com/user-attachments/assets/cf4bdd4b-0174-4756-ad7a-b7b25c09046d">

**Comment by Mamaduka** [comment]
Related #62186. cc @afercia

**Comment by creativecoder** [comment]
@richtabor Note that there's one case with template parts, where the icon is used to identify the template part area (header, footer, or general), in addition to the post type. Do you think it's worth keeping the icon in this case?

Template part names are up to the theme, so these won't necessarily be named "Header" or "Footer":

<img width="468" alt="image" src="https://github.com/user-attachments/assets/934cdc45-9eff-45d1-b065-192b1a5a3ca9">
<img width="463" alt="image" src="https://github.com/user-attachments/assets/c5c93c6e-cb10-4750-8fd9-55d71d7b66dc">

**Comment by richtabor** [comment]
>  Do you think it's worth keeping the icon in this case?

I think it's fine just to use "Template Part". 

![CleanShot 2024-09-09 at 16 19 24](https://github.com/user-attachments/assets/871db497-c47f-475c-aa2f-e8defa6565a9)

**Comment by creativecoder** [comment]
PR here, trying this out: https://github.com/WordPress/gutenberg/pull/65170

**Comment by creativecoder** [comment]
I noticed that we use the same treatment with the purple color, icon, and document name in the sidebar:

<img width="275" alt="image" src="https://github.com/user-attachments/assets/5e060e21-3ca0-404d-a97b-d415cec7c0bb">


Perhaps the title text there should also have the icon removed, to be consistent?

**Comment by jasmussen** [comment]
You'll need to update the color of the template text to #6d6d6d, but otherwise, let's do it, it seems much clearer.

**Comment by afercia** [comment]
> Related #62186. cc @afercia

Thanks for the ping. I'm in favor of reducing proliferation of icons in the editor and, as @Mamaduka pointed out, this would also solve https://github.com/WordPress/gutenberg/issues/62186

Specifically to the Document Bar

It should be entirely reconsidered. Currently, its labeling completely mismatches its functionality.

Some history:

The need to clearly identify _what_ is being edited in the editor isn't new. On April 2017 (more than 7 years ago) in https://github.com/WordPress/gutenberg/issues/503 the accessibility feedback was to use a _visible_ H1 heading as first title in the `<main>` content. All we got is a visually hidden heading.

Years later, the design wanted to add a _visible_ indication of the object being edited thus validating the need for a _visible_ indication. The Document Bar was added but its implementation is less than ideal. I will try to split all this in a separate issue.

For now, I support the removal of the icon in favor of visible text.
