### ISSUE TITLE
Navigation Block: develop a content-only representation

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#65699]
There should be a way to make edits to your menu while on content-only mode. The canvas edits should be restricted but the inspector menu should be reachable.

We should explore exposing the "menu list view" in the inspector of template parts or patterns that contain a menu when the user is on content-only mode.

There should be a clear way to reach that panel from the toolbar of the nav block and the template/pattern. Could be an "edit menu" that just toggles the inspector with the tab for the menu open.

**Comment by youknowriad** [comment]
How do you see this kind of feature being "declared" for block types. In other words, until now, block types were not aware about whether they are in "content only" mode or not. We only detected blocks that have a "content" role attribute and allowed some specific behavior there. How do you see that evolving, should block types receive some kind of `isSection` flag and enable/disable behavior.

**Comment by mtias** [comment]
I don't think we should abstract this too soon. The navigation block already has a special tab in the inspector, so perhaps it's part of formalizing that view down the road. Conceptually, I don't think blocks should be made aware of "modes".

**Comment by getdave** [comment]
Related 

- https://github.com/WordPress/gutenberg/pull/65185
- https://github.com/WordPress/gutenberg/pull/65118

**Comment by SaxonF** [comment]
I think we can tie this work into the content only stream as well as synced patterns in a few iterative ways.

1. Add an "edit menu" button to the Navigation Block toolbar. This is not directly related to content only but it helps to resolve some of the same pain points. The navigation block would be special in that other blocks would go with a generalised label and l[ess prominent action](https://github.com/WordPress/gutenberg/pull/65185).
2. Treat template parts in the same way as synced patterns. Clicking a template part should always select the template part which contains an edit button. Clicking the edit button puts us into focus mode for the part (like synced patterns) with the inspector open. You can currently select the site ltitle block within a template part directly for example.
3. When editing a template part, and in an content only mode, show editable blocks in the inspector. An editable block may site logo, site title or navigation block.
4. Adjust the content only behaviour so that clicking a block that has deeper attributes (like navigation block) it drills down in the inspector but offers a pathway back up. This has previously been explored by @talldan as part of https://github.com/WordPress/gutenberg/issues/60021
5. Allow the selection of template part when in the new zoom out / content only mode. 

It may look something like this


https://github.com/user-attachments/assets/e0456bda-d899-4710-bb94-0215b5943135

The above shows two ways of accessing a menu. The first via the content list, and the second via the canvas with an "edit menu" button that just opens inspector with menu tab open.

In future we can look at surfacing overridable properties directly vs drilling down like what is proposed above.

**Comment by draganescu** [comment]
> until now, block types were not aware about whether they are in "content only" mode or not.

> Conceptually, I don't think blocks should be made aware of "modes".


If blocks are not aware of the mode they're in than something like [#60412](https://github.com/WordPress/gutenberg/pull/60412) can't work. Either the block tells the block editor that something is editable in content only, or the block editor designates what is content in content only. We went the first route and the block tells the block editor via the role prop of attributes what's editable in content only.

But the navigation block does not really have any content. The content is stored in the navigation link and navigation submenu blocks which are navigation block children. Updating the defition of these two types (link and submenu) to include role content on attributes whcih are content partly gets us there.

https://github.com/user-attachments/assets/d3a8f82a-cd94-4cee-9cf1-fab758f1fd79


But, what is lost, we can't see the tree of links 😢 However that seems to be an issue for the whole block tree which is flattened in content only.

1. What's the problem with preserving the flat block tree for navigation as well?
2. What is wrong with editing on canvas? Why would we want the navigation list view? @richtabor expressed his concern about adding drilldown to content only, which is kinda the same with the proposal above (an edit button in navigation's block toolbar). I think we used to have one ...

About 2 there is something else to consider: if a user is only expected to replace pictures and text, then why do we expect them to rearrange the site's hierarchy?

**Comment by draganescu** [comment]
This could work in a world where we show controls for every attribute with role content in the inspector. That could work by allowing blocks to register these controls for the inspector when they are in content only for whatever reason. Then the navigation block could register this whole list view thing.

**Comment by draganescu** [comment]
A bit of trial and error:

- if the block is assumed to be able to mount an affordance in the inspector then it has to be selectable.
- in content only due to how the content locking works, there is no selectable block without a content role attribute
- making the ref attribute role content makes the block selectable and uneditable in canvas (good enough start)
- adding the "list" group inspector slot for when content only blocks are listed allows the off canvas list view of the navigation block to be shown in the inspector when it's edited in content only.
  - ideally when this block is selected the `BlockQuickNavigation` will not be shown
  - since the list view of the navigation block works like the normal list view it will not by default show any blocks
    - because all the blocks in navigation do not have any content role attributes
      - and if any are added (which makes sense say label for links) then they become editable in the canvas
        - and we don't want that
- to edit links and submenus from the offcanvas list view of the navigation block we need to add drill down to the inspector in content only, because that's the way navigation block works. Should we add it only for this block?

So we need some things to achieve this style of editing:

- a way for blocks to signal they're selectable without having any content role attribute (or we can go with rel)
- a slot marked for content only affordances
- a way to mark a tree as editable by the parent even if content only context exists, or have the blocks themselves set their mode
- drill down ...

**Comment by draganescu** [comment]
Follow-up from a discussion with @youknowriad we can update content only to:

- enable blocks with controlled inner blocks to expose these inner blocks in the block inspector via a list view
  - this list view auto engages when a block with controlled inner blocks is selected in content only mode
  - the block inspector will support drilldown for blocks that show this list view of inner blocks
- make blocks with controlled inner blocks in content only are selectable but not editable in the canvas

This is a good start for an exploratory phase which could answer things like:

- Where should this list view appear? Does it appear on its own, or do we squish it bethween parent styles and block quick navigation?
- How is this redefining content only? If all blocks with controlled inner blocks become editable via the inspector, we break the contract that only role="content" is editable in content only.
- How much can we bloat the list view with? To implement the ideas above we'll need a new flag in the list view that tells it to disregard content only and list the full block tree not the flattened editable one.
- How much can we bifurcate the implementation of the block inspector? To add drill down just for this list view but not for other blocks may be a very specific execution path with lots of code serving a single small UX surface.
- Is this UX actually good? Having some exploratory PR will allow hands on interaction.

**Comment by draganescu** [comment]
@youknowriad following the PR ([#66753](https://github.com/WordPress/gutenberg/pull/66753)) the incipient code and the reviews show that we're fighting the system rather than enriching it, implementing the idea [here](https://github.com/WordPress/gutenberg/issues/65699#issuecomment-2456692194). Ideally we should reassess what this issue means.

The way I read both the descriptio and the answer from @mtias we should start with the navigation block being "special" again. Probably a better approach is to not use the block inspector and just update the navigation block to render a popover with it's tree from inside the block. I'll try this too.

**Comment by talldan** [comment]
The two main problems in the PR IMO are:
- Defining this for all controlled block parents in the way the PR does is too broad. This could affect some controlled blocks in weird ways, especially the pattern block which already has its own treatment for editing content. I think it's ok to hard code it to specific block types to start with.
- The inner blocks of the navigation block are `blockEditingMode: 'disabled'` in state, but the PR is circumventing that to make them selectable/editable. I feel this is breaking what `blockEditingMode: 'disabled'` means. It's another thing that could result in some weird bugs. It'd be better to look at giving navigation links (and other navigation inner block types) the correct `role: content` definitions and return the appropriate `blockEditingMode` for these blocks (which might be something that doesn't exist right now).

**Comment by getdave** [comment]
@talldan I've been exploring what you suggested above in https://github.com/WordPress/gutenberg/pull/67389 building off your excellent work refactoring all the blockEditingMode stuff to the reducer.

The main Issue I've come up against is how we handle blocks such as Page List which frequently appear as children of the Navigation block but which don't have any attributes that warrant `role: content`.

Options I've been toying with:

- adding `role: content` to one of the attributes such as `isNested` which don't provide any UI anyway, but which would force the block to be `contentOnly` 
- hard coding exceptions into the state (seems like a huge hack but it is possible).
- creating a new `supports` flag which can be used to derive the `contentOnly` state for the given blocks 

I'd be curious to hear both yours and @draganescu thoughts on this 🙏

**Comment by getdave** [comment]
I'm also wondering whether we need to provide a means to distinguish between block attributes which are `role: content`. Then when in `contentOnly` we conditionalise the render.

We could then incrementally update blocks to render controls for their attributes _conditionally_. We could then we could swap out the attributes exposed to `BlockEdit` based on `blockEditingMode` being `contentOnly`.

**Comment by talldan** [comment]
> The main Issue I've come up against is how we handle blocks such as Page List which frequently appear as children of the Navigation block but which don't have any attributes that warrant role: content.

It's interesting. I think part of the issue is that I'm not sure how Page List should ideally work in `contentOnly` mode. It seems like quite a complicated block when the experience is supposed to be purposely limited to simple content updates.

The one aspect of it that could be an option is changing the parent, so perhaps that's the attribute to add `role: content` to. It does govern the block's content, so maybe it's logical. 

There's also Page List Item, which already has attributes that `role: content` can be added to, so I wonder if that could be visible. Again, I wonder how it should work, if the feature where it converts itself to regular links is still available. It is also possible to show the Page List Items, but hide the Page List. That also partly makes sense to me as it'd be filtering the down to purely content blocks. 🤔 

> I'm also wondering whether we need to provide a means to distinguish between block attributes which are role: content. Then when in contentOnly we conditionalise the render.
> We could then incrementally update blocks to render controls for their attributes conditionally. We could then we could swap out the attributes exposed to BlockEdit based on blockEditingMode being contentOnly.

If I'm understanding correctly, then there's some past discussion around this subject:
- https://github.com/WordPress/gutenberg/issues/58233
- https://github.com/WordPress/gutenberg/issues/62439
- https://github.com/WordPress/gutenberg/pull/60779

**Comment by getdave** [comment]
We should consider this behaviour for Navigation https://github.com/WordPress/gutenberg/issues/52018 whereby we treat it's inner block's as "content".

**Comment by karmatosed** [comment]
I am trying to work out what can be done on this to move it forward. Specifically what needs design as there was an awesome direction from Saxon here: https://github.com/WordPress/gutenberg/issues/65699#issuecomment-2384913467. That said it feels like there might need to be support in other issues @getdave and @talldan. If that is the case, I am very happy to dive in there but just for now trying to figure out where the need is and how to activate.

**Comment by getdave** [comment]
Quick update on progress here and what is "in play".

[Explore alternative Navigation block Write Mode UX via Content Panel #71137](https://github.com/WordPress/gutenberg/pull/71137) – this is the primary prototype PR which shows the PoC UX and is being rebased to pull in PRs as they are merged. This PR clearly shows new APIs will be needed to realise the UX shown.

## PRs

- [x] 	[#71188](https://github.com/WordPress/gutenberg/pull/71188) – Navigation Link: Add page creation functionality to Link UI
- [ ]  	[#71192](https://github.com/WordPress/gutenberg/pull/71192) – Navigation block: Add “Add Page” button to toolbar
- [ ]  	[#71452](https://github.com/WordPress/gutenberg/pull/71452) – Add LinkControl search input to Navigation Link block sidebar
- [x] [#71163](https://github.com/WordPress/gutenberg/pull/71163) – Nav block inserter normalization between canvas and list view sidebar.
- [x] [#71213](https://github.com/WordPress/gutenberg/pull/71213) – Hide “Add block” control in Link UI during contentOnly mode

**Comment by getdave** [comment]
@karmatosed Thank you. It would be great to have more Design input on this work. Perhaps it would be beneficial for you to sync up with @jasmussen who has been active in the various PRs. 

As a start, https://github.com/WordPress/gutenberg/pull/71452 could do with some Design to make sure it's going to provide a good UX.

**Comment by jasmussen** [comment]
Thank you for the nudge/ping Dave. I had forgotten to upload these mockups I created last week, apologies.

The challenge for the navigation block is that it's hard to find where and how to edit the menu, and even basic management of the contents. Secondly, editing navigation is easily confused with a place to add or edit pages. The contentOnly representation can benefit from improvements in all these areas.

**Basic management**

![Image](https://github.com/user-attachments/assets/898de1cf-4378-455a-8edc-170682e0a288)

* Replaced the “edit navigation” button for the navigation block with an “add new page”. This opens the same link dialog other navigation plus buttons do. Paired with the ability to create drafts, and then go to those drafts, it could arguably improve the flow of adding/editing/navigating to new pages as you build out your site.
* Added a “View” button to links, as well as a “Go to this page” link in the inspector.
* Adjusted the spacing and metrics of items in the Contents panel slightly, so things line up, and the same chevron for drilling down is used as for main navigation.
* Explored a very basic “Go to this item” button in the titlebar.

![Image](https://github.com/user-attachments/assets/79435797-85a5-4365-a6cb-b5753eba0509)

**Adding pages, drafts**

This is mostly a visualization of the aforementioned flow to add pages, but it includes an “Edit” button on the draft page link.

**Comment by karmatosed** [comment]
Thanks for the updates @jasmussen, let’s see about getting you some feedback.

More or less I feel this is a good basis to get into code and try, the one thing I wonder is if the ‘add a new page’ also needs an icon? I get the navigation icon is there but I do wonder about a + or something which we all now associate with adding. Just on things like that I feel having a bit more consistency around where we have or don’t have icons and text could be good. Otherwise we have this halfway space and it’s super hard to work out what is an action to add or not.

**Comment by jasmussen** [comment]
Thanks. Valid, I think there's an opportunity to improve some of those text links. In many cases we are very much narrowing in on "Add" as the main term to leverage, with it just being added to the new Accordion block as well. But I'd think it would need to be a bit of a separate holistic exploration, as it would need to consider that there are already a lot of plusses on the page, taking it all into consideration.

**Comment by getdave** [comment]
> More or less I feel this is a good basis to get into code and try

@karmatosed Before you dive into code you might want to check out the recent improvements that have landed in `trunk` and been rebased onto [the prototype PR](https://github.com/WordPress/gutenberg/pull/71137). Hopefully it helps to tie some of this together and provide a feel for what is missing and what does/doesn't work.

**Comment by getdave** [comment]
Having rebased against latest `trunk`, I've done a quick run through of the experience as it stands in [the Prototype PR](https://github.com/WordPress/gutenberg/pull/71137). I noticed several Issues which I've tracked as Sub Issues on this task.

**Comment by getdave** [comment]
We're getting quite close to WP 6.9 and so we need to have the Nav block at least functioning in `contentOnly` mode. As a result I'm prioritising:

- https://github.com/WordPress/gutenberg/issues/72009 - this makes it easier to jump to editing the Nav block from the template part
- https://github.com/WordPress/gutenberg/issues/71757 - this guides users to select the Nav block itself rather than a child and means they are more likely to see the affordances offered to streamline adding Pages (e.g. `Add Page` button on toolbar and the Editable List View sidebar).
- https://github.com/WordPress/gutenberg/issues/71991 - this avoids a suboptimal experience as the `Content` sidebar displays all children of the Nav block which isn't a good fit for the block without the drill down mechanic (which is looking unlikely to be ready).

Once those two items are complete we can see what other features from the Sub Issues above can be landed in time.

I would value a confidence check.

**Comment by getdave** [comment]
@jeryj let's make a list of key outstanding Issues for the Simplified Navigation Editing effort (as opposed to contentOnly) here:

- [ ] https://github.com/WordPress/gutenberg/issues/73964
- [ ] https://github.com/WordPress/gutenberg/issues/71946

Once done let's sort in order of priority based on the impact on the UX of the block.

**Comment by getdave** [comment]
Sharing from https://github.com/WordPress/gutenberg/issues/38275#issuecomment-3907741791.

----

### [Navigation in Pattern Editing (a.k.a contentOnly)(#65699)](https://github.com/WordPress/gutenberg/issues/65699)

The Navigation block is now working intuitively in contentOnly/Pattern Editing mode – popover-based link editing, dual-tab inspector, click-through to List View. A couple of small items to land before the cutoff, all on track.

### [Simplified Navigation Editing (#65699)](https://github.com/WordPress/gutenberg/issues/65699)

Significant UX improvements addressing the core friction points that have long made Navigation feel difficult. We’ve improved discoverability of List View editing, made it easier to work with links and understand their current status, and added validation and guardrails to prevent broken menus (and help fix existing ones). Core scope complete and on track.

Note: Navigation in Pattern Editing and Simplified Navigation Editing both reference #65699. That issue was originally scoped to Pattern Editing only, but Simplified Navigation Editing was folded in during planning for 7.0. The two projects are distinct – if the tracking looks blurred, that’s why. I have a Todo to break these out into two issues as soon as the 17th deadline is passed.

**Comment by getdave** [comment]
@jeryj Can we close this out do you think? Could we make a list of any outstanding tasks?

**Comment by jeryj** [comment]
@getdave I think we can close this - we're now able to edit navigation items while in content only mode using the list view + flyout menu. 

<img width="618" height="709" alt="Editing navigation menu item in content only"  src="https://github.com/user-attachments/assets/532a8bbf-e2e6-4c66-b0cd-62e336c52604" />
