### ISSUE TITLE
Components: Deprecate 36px default size

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#65751]
Part of #46741

In our transition process to the new 40px default sizes, we are now ready to officially start the deprecation period by logging console warnings.

## List of components

- [x] BorderBoxControl #65752
- [x] BorderControl #65755
- [x] BoxControl #66704 
- [ ] Button #68328
    - [x] #68329 
    - [x] #68330
- [x] ComboboxControl #66900
- [x] CustomSelectControl #67441
- [x] DimensionControl #66705 
- [x] FontSizePicker #66920
- [x] FormFileUpload #67438
- [x] FormTokenField #67454 
- [x] InputControl #66897
- [x] NumberControl #66730 
- [x] Radio #66572
- [x] RangeControl #66721 
- [x] SelectControl #66898
- [x] TextControl #66745 
- [x] ToggleGroupControl #66747 
- [x] TreeSelect #67855
- [x] UnitControl #66791 

### Block Editor

- [x] FontAppearanceControl (CustomSelectControl) #67854
- [x] FontFamilyControl (CustomSelectControl) #67853
- [x] LetterSpacingControl (UnitControl) #67429
- [x] LineHeightControl (NumberControl) #67850

## Procedure

```
- [ ] Log deprecation warning
- [ ] Update unit tests
- [ ] Update Storybook (including all stories where the component is used)
- [ ] Update code snippets (Storybook, JSDoc, README)
- [ ] Changelog
- [ ] Add Dev Note tag
```

If used inside another wp-components component and the parent component is dictating the child component's size dynamically, the parent component is responsible for logging the deprecation warning. To suppress the redundant warning from the child component, add the `__shouldNotWarnDeprecated36pxSize` prop as shown [here](https://github.com/WordPress/gutenberg/commit/1b7eeecb693a6b8a28db7592435628b43aeff7c8) for the ToggleGroupControl used inside FontSizePicker.

### Success criteria

```
- [ ] Unit tests must all be passing
- [ ] If used in a Storybook story for another component, it must have the prop so it isn't logging console warnings
```

**Comment by hbhalodia** [comment]
Hi @mirka, I would like to pick some of the controls to add the deprecations. Should I wait until any of the PR get's merged to use the `maybeWarnDeprecated36pxSize` utility function?

Thank You,

**Comment by mirka** [comment]
@hbhalodia Awesome! Yes, I'll need to merge those first. I'll ping you when this is ready for contributors 🙏

**Comment by hbhalodia** [comment]
Hi @mirka, I have raised the PR to deprecate `36px default size` on `BoxControl` - https://github.com/WordPress/gutenberg/pull/66704.

Thank You,

**Comment by hbhalodia** [comment]
Hi @mirka, I have raised the PR to deprecate 36px default size on DimensionControl - https://github.com/WordPress/gutenberg/pull/66705.

Thank You,

**Comment by vipul0425** [comment]
Hi @mirka , I have raised the PR for RangeControl - https://github.com/WordPress/gutenberg/pull/66721

Thank You 🙇

**Comment by PARTHVATALIYA** [comment]
Hi @mirka, I have raised the PR for InputControl - https://github.com/WordPress/gutenberg/pull/66897

Thank You!

**Comment by mirka** [comment]
@hbhalodia @PARTHVATALIYA Unit tests are not passing in the rest of your open PRs. That likely means that the unit tests for the component are not completely updated, and/or some components need a `__shouldNotWarnDeprecated36pxSize` added. Please check the updated Procedure section in the [first issue comment](https://github.com/WordPress/gutenberg/issues/65751#issue-2557104623).

**Comment by mirka** [comment]
At this point it's likely that we won't do a size deprecation for `@wordpress/components` `Button`, and instead wait for the deprecation of the component itself (in favor of the new `Button` from `@wordpress/ui`).

**Comment by mirka** [comment]
## ✍️ Dev Note for WP 7.1

### 40px default size for form controls

Starting in WordPress 7.1, `@wordpress/components` form controls use a 40px default height unconditionally. The opt-in `__next40pxDefaultSize` prop is no longer needed and has no runtime effect when passed.

This completes the rollout that followed the [soft deprecation](https://make.wordpress.org/core/2025/03/25/updates-to-user-interface-components-in-wordpress-6-8/) in WordPress 6.8. The prop was introduced in WordPress 6.7 so plugins could opt in early. Since 6.8, components that had not opted in logged a console warning.

### What changed

- Affected components now render at 40px by default without the prop.
- Passing `__next40pxDefaultSize` is ignored at runtime.
- Passing `__next40pxDefaultSize={ false }` no longer opts out to the previous 36px height.
- On `BorderBoxControl`, `BorderControl`, `FontSizePicker`, and `ToggleGroupControl`, the `size` prop is also deprecated and has no effect.

### What to do

Remove `__next40pxDefaultSize` from your component usage. No replacement prop is needed.

If you were passing `size="__unstable-large"` on the components listed only to get 40px height, remove that as well.

### Affected components

**`@wordpress/components`**

`BorderBoxControl`, `BorderControl`, `BoxControl`, `ComboboxControl`, `CustomSelectControl`, `FontSizePicker`, `FormFileUpload`, `FormTokenField`, `FocalPointPicker`, `InputControl`, `NumberControl`, `QueryControls`, `Radio`, `RangeControl`, `SearchControl`, `SelectControl`, `TextControl`, `ToggleGroupControl`, `TreeSelect`, `UnitControl`

**`@wordpress/block-editor`**

`FontAppearanceControl`, `FontFamilyControl`, `LetterSpacingControl`, `LineHeightControl`

### Not included

This rollout covers form controls only. `Button` still uses the opt-in prop and is unchanged.
