### ISSUE TITLE
6.7 Dev Note Tracking Issue

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#65784]
## Tracking all Dev Notes from Gutenberg plugin releases 18.6 - v19.3

Please read the information below carefully. If you have questions or suggestions, connect with `@fabiankaegy` via Slack, ping @fabiankaegy on GitHub, or comment here. 

> [!IMPORTANT]
> 🗓 Deadline **Drafts for All Dev Notes** - **October 13th, 2024** (a few days before Beta 3, so there's enough time for reviews) 
> 🗓 Deadline **All Dev Notes Published** - **October 20nd, 2024** (a few days before RC1) 

Not all developer-related information must be in a separate DevNote on the Make Core blog for the field guide. We can group related information. We can already decide whether some features warrant a stand-alone blog post or a group post. 

## Stand-alone post

To streamline the process and eliminate bottlenecks, all writers of stand-alone dev notes will write the dev notes on the Make Core Blog.
 

<details>
<summary>Instructions</summary>

- Create your note in a new post,
- Save as Draft
- Enable public preview
- Share the link to the public preview in a comment below as "ready for review"
- "For dev notes, each one must have at least two reviewers" ([Handbook](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/))

</details>

## Part of a group post

If the information related to your PR will be part of a group post, please write the **dev note in a comment on the PR**, so it can be reviewed and, if necessary commented on, by the release docs team or a reviewer. 

## Before you start writing  📣  please read the handbook pages: 

- ⭐️ [Writing developer notes](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/)
- ⭐️ [Style & Substance section](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance) of the Post & Comment Guidelines for Make Blog 
- ⭐️ [Documentation Style Guide](https://make.wordpress.org/docs/style-guide/) - Good for reference, when in doubt, especially when English is not your native language.

---

> [!NOTE]
> The list is incomplete. We are in the process of reviewing plugin release changelogs and add them as we progress on the task. 

There are two labels relevant to DevNotes : 
- [`needs dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+merged%3A%3E%3D2024-05-25+)
- [`has dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22has+dev+note%22+merged%3A%3E%3D2024-05-25+) 

If you worked on a feature/module/component that definitely needs a dev note, please assign the label `needs dev note` If you already added the Dev Note to the make blog on draft or as a comment on the PR, please label it `has dev note` 

---

## TO DO

_Progress of the Documentation work for WP 6.7 release (including the DevNotes tracked on this issue) can also be followed at [WP 6.7 Documentation](https://github.com/orgs/WordPress/projects/223) project dashboard_

_PRs with label `has-dev-note` or a related DevNote draft are marked with [x]_

#### Standalone Posts:
 - [x] #64644 - @lezama 
 - [x] #64351 - @stokesman
 - [x] #61577 - @Aljullu [[Draft](https://docs.google.com/document/d/173s64rpKAZBu4b-VFu3rHGq5yHUHgDJNbPSTGf9l9w8/edit#heading=h.irlo2ckpr1d4)]

**Stabilize Role Attribute Property ✅** - [[Draft](https://github.com/WordPress/gutenberg/pull/65484#issuecomment-2391071662)]
@youknowriad and @getdave have agreed to work on this one and already shared a [Draft](https://github.com/WordPress/gutenberg/pull/65484#issuecomment-2391071662). 

 - [x] #65484 - @getdave
 - [x] #63076 - @youknowriad

**Zoomed Out Mode**
I'd love to have one dev note dedicated to all things Zoomed out mode that explains the feature and how to work with it. Including how stuff like the "Section detection algorithm" work.

~@getdave has volunteered to help triage this :)~ A draft is available at https://github.com/WordPress/gutenberg/issues/64197#issuecomment-2391113558
 - [x] #65482
 - [x] #65404
 - [x] #63896
 - [x] #63668

**Block Bindings**
We should have a dedicated dev note for all things Block Bindings that talks about all the new stabilized API's etc. Assigned to @artemiomorales [[Draft](https://docs.google.com/document/d/1UjxUHs2TfVcfVYvJjsThHOiw5XmD1lBh5ih8yx0XNFk/edit?tab=t.0)]
 - [x] #65713
 - [x] #65099
 - [x] #64570
 - [x] #64102
 - [x] #62880
 - [x] #64072
 - [x] #65639

**Interactivity API Updates**
@DAreRodz or @michalczaplinski , can you help with this? 
 - [x] #65151
 - [x] ~#64006~

 **Components Package Updates**

@mirka @ciampo have volunteered to help with this :) 
 - [x] #63569 - @ciampo [[Draft](https://github.com/WordPress/gutenberg/pull/63569#issue-2408809780)]
 - [x] #63491 @mirka [[Draft](https://github.com/WordPress/gutenberg/issues/39358)]
 - [x] #63258 @ciampo 
 - [x] #63248 @ciampo 
 - [x] #60913 @ciampo 
 - [x] #65469 @ciampo
 - [x] #65131 @mirka [[Draft](https://github.com/WordPress/gutenberg/pull/65131)]
 - [x] #64951 @ciampo 
 - [x] #64526 @mirka [[Draft](https://github.com/WordPress/gutenberg/pull/64526)]
 - [x] #64408 @mirka [[Draft](https://github.com/WordPress/gutenberg/issues/39358)]
 - [x] #62282 - @mirka [[Draft](https://github.com/WordPress/gutenberg/pull/62282#issue-2333548870)]
 - [x] #64069 - @mirka [[Draft](https://github.com/WordPress/gutenberg/pull/64069)]
 - [x] #60613 @mirka  [[Draft](https://github.com/WordPress/gutenberg/pull/60613)]
 - [x] #63450 @ciampo
 - [x] #64613 @ciampo 

**Miscellaneous Editor Updates (TBD)**
 - [x] #63057 - @matiasbenedetto [[Draft](https://github.com/WordPress/gutenberg/issues/65784#issuecomment-2386706602)]
 - [ ] #63656 - @ellatrix
 - [x] #63690 - @carolinan 
 - [x] #64872 - @ntsekouras
 - [x] #63535 - @ndiego 
 - [ ] #63322 - @Mamaduka
 - [x] #63318 - @scruffian [[Draft](https://github.com/WordPress/gutenberg/issues/65784#issuecomment-2444962578)]
 - [x] #62092 - @ockham - [[Draft](https://github.com/WordPress/gutenberg/issues/65784#issuecomment-2396921320)]
 - [x] #62298 - @amitraj2203 - [[Draft](https://github.com/WordPress/gutenberg/pull/62298#issue-2334199441)]
 - [x] #62539 - @scruffian [[Draft](https://github.com/WordPress/gutenberg/issues/65784#issuecomment-2444962578)]
 - [x] #64490 - @ramonjd - [[Draft](https://github.com/WordPress/gutenberg/pull/64490#issuecomment-2390378310)]
 - [x] #64981 - @sgomes
 - [x] #64943 - @DaniGuardiola - [[Draft](https://github.com/WordPress/gutenberg/issues/65784#issuecomment-2389706120)]
 - [x] #64917 - @ramonjd [[Draft](https://github.com/WordPress/gutenberg/pull/64917#issuecomment-2403665594)]
 - [x] #65071 - @ramonjd - [[Draft](https://github.com/WordPress/gutenberg/pull/65071#issuecomment-2390366199)]
 - [x] #64204 - @jsnajdr 
 - [x] #65026 - @ramonjd [[Draft](https://github.com/WordPress/gutenberg/pull/65026#issuecomment-2403642076)]
 - [x] #64198 - @jsnajdr 

**Query Loop Updates**
@ryanwelcher would you be able to help write a dev note for these changes?

 - [x] #63362
 - [x] #63358
 - [x] #58207
 - [x] #64167
 - [x] #65067
 - [x] #63404 - @ellatrix

**Consolidating and expanding block supports** 
@mumtahinafaguni Would you be able to draft a dev note that includes all these updates in one post? 🤔 
 - [x] #63538
 - [x] #63950
 - [x] #63924
 - [x] #64550
 - [x] #64230
 - [x] #64210
 - [x] #64238
 - [x] #64239
 - [x] #64271
 - [x] #64509
 - [x] #63428
 - [x] #63295
 - [x] #63539
 - [x] #63546
 - [x] #63419
 - [x] #63540
 - [x] #63541
 - [x] #63542
 - [x] #63543
 - [x] #64615
 - [x] #64530
 - [x] #64599
 - [x] #64233
 - [x] #62499
 - [x] #64023
 - [x] #64022
 - [x] #64246
 - [x] #64024
 - [x] #64302
 - [x] #64581
 - [x] #63545
 - [x] #62497
 - [x] #63547
 - [x] #63778
 - [x] #63631
 - [x] #63629
 - [x] #63579
 - [x] #63630
 - [x] #62498
 - [x] #62727

**Comment by talldan** [comment]
> [Add JSON Schema for .wp-env.json files](https://github.com/WordPress/gutenberg/pull/36276#top)

This one isn't a WordPress (core) API, so I personally don't think a dev note is the right choice (it isn't something that will be released via WordPress 6.7, it was already released as a change via the npm package update).

From the handbook it seems like dev notes are only for WordPress core releases - https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/.

**Comment by fabiankaegy** [comment]
> > [Add JSON Schema for .wp-env.json files](https://github.com/WordPress/gutenberg/pull/36276#top)
> 
> This one isn't a WordPress (core) API, so I personally don't think a dev note is the right choice (it isn't something that will be released via WordPress 6.7, it was already released as a change via the npm package update).
> 
> From the handbook it seems like dev notes are only for WordPress core releases - https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/.

@talldan Fair point :) 

In the past we [published standalone posts](https://make.wordpress.org/themes/2021/11/30/theme-json-schema/) for the schema. I do think it is something we should somehow inform users about. But it doesn't have to do with a specific release  👍

**Comment by talldan** [comment]
I think standalone posts are good. My understanding is the dev notes are all organized and linked from the general release literature that extenders will read through, so it's good to ensure it contains highly relevant items. There have been complaints in the past about important changes being buried in the details.

The TS changes might also qualify for something that doesn't need to be a dev note (if the public APIs haven't changed).

**Comment by youknowriad** [comment]
@fabiankaegy For the DataViews extensibility APIs, they are still plugin-only for now. So no need for dev notes for 5.7. We should try to gather more feedback and usage there.

**Comment by fabiankaegy** [comment]
> @fabiankaegy For the DataViews extensibility APIs, they are still plugin-only for now. So no need for dev notes for 5.7. We should try to gather more feedback and usage there.

Thanks for confirming that Riad :) Will remove the section  👍

**Comment by matiasbenedetto** [comment]
> - https://github.com/WordPress/gutenberg/pull/63057 - @matiasbenedetto

I think this doesn't need a dev note. It is the implementation of a UI in the editor for an already existing feature in theme.json.

**Comment by fabiankaegy** [comment]
> > * [Adding Font size presets UI #63057](https://github.com/WordPress/gutenberg/pull/63057) - @matiasbenedetto
> 
> I think this doesn't need a dev note. It is the implementation of a UI in the editor for an already existing feature in theme.json.

@matiasbenedetto Happy to remove it. My rationale for adding it here was that I do think it is useful for developers to know about the existence of the new feature. Because it does allow the user to do more things with their theme that they weren't before. 

It is an end user feature but I think developers should be aware of it.

**Comment by matiasbenedetto** [comment]
> It is an end user feature but I think developers should be aware of it.

Gotcha :+1: , here it goes:

--- 
## Font Size Presets UI

A new UI feature has been introduced in the Global Styles section of the editor, allowing users to add, edit, and remove font size presets. 

A font size preset is a predefined font size that can be reused throughout the site via the font size picker. This enhancement provides a more user-friendly way to manage font size options, which were previously only accessible via the manual edition of theme.json file. Users can now modify preset names, base sizes, enable or disable the default fluid behavior, and customize the minimum and maximum values for fluid font size presets directly from the UI.

To access this interface, navigate to the Styles sidebar, then go to Typography → Font Sizes.

**Comment by cbravobernal** [comment]
@artemiomorales started an initial draft of the dev note for block bindings 🚀

**Comment by swissspidy** [comment]
I am confused. Is this ticket about Gutenberg dev-notes or **all** dev-notes for 6.7? There are tickets mentioned in here that have nothing to do with Gutenberg.

In the past, for the dev-notes a separate project board was used (e.g. https://github.com/orgs/WordPress/projects/202). Not an issue in the Gutenberg repo... That's super confusing and can lead to false impressions.

Edit: I see now there is [a board for 6.7](https://github.com/orgs/WordPress/projects/223) as well. So why mention regular trac tickets in here that are completely unrelated to Gutenberg? Are contributors supposed to work here, or on the board?

**Comment by DaniGuardiola** [comment]
Hi @fabiankaegy, responding to https://github.com/WordPress/gutenberg/pull/64943#issuecomment-2389535290 here :)

I think the dev notes could go like:

---

## New `useEvent` utility in `@wordpress/compose`

The new `useEvent` utility creates a stable callback that has access to the latest state (as opposed to a `useCallback` call with an empty dependency array). This is useful to "untrack" dependencies in a callback that is called within event handlers or effects. It cannot be called at render time.

This is a common pattern in React, and it's even being considered as a core React feature (see [the RFC](https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md)). More context can be found [in this popular issue](https://github.com/facebook/react/issues/14099) in the React repository.

Here's an example:

```tsx
 function Component( props ) {
   const onClick = useEvent( props.onClick );
   useEffect( () => {
     onClick();
     // Won't trigger the effect again when `props.onClick` is updated.
   }, [ onClick ] );
   // Won't re-render `Button` when `props.onClick` is updated (if `Button` is
   // wrapped in `React.memo`).
   return <Button onClick={ onClick } />;
 }
 ```

## New `useResizeObserver` API in `@wordpress/compose`

The new API and behavior of `useResizeObserver` is meant as a thin wrapper for the browser-native `ResizeObserver` API,  which enables more use cases and better composition. The previous API is still supported, though it is considered legacy and deprecated.

Now, you must pass [a callback](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver#callback) as the first argument to the hook which is forwarded to [the `ResizeObserver` constructor](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver). The hook returns a setter that must be passed as a callback ref to the target element, or called in an effect in advanced use-cases. Additional [options for the internal `ResizeObserver.observe` call](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe#options) can be passed as the second argument.

Here's an example:

```tsx
const setElement = useResizeObserver(
  ( resizeObserverEntries ) => console.log( resizeObserverEntries ),
  { box: 'border-box' }
);
<div ref={ setElement } />;

// The setter can be used in other ways, for example:
useLayoutEffect( () => {
  setElement( document.querySelector( `data-element-id="${ elementId }"` ) );
}, [ elementId ] );
```

---

Let me know if that works! :)

**Comment by fabiankaegy** [comment]
> I am confused. Is this ticket about Gutenberg dev-notes or **all** dev-notes for 6.7? There are tickets mentioned in here that have nothing to do with Gutenberg.
> 
> In the past, for the dev-notes a separate project board was used (e.g. https://github.com/orgs/WordPress/projects/202). Not an issue in the Gutenberg repo... That's super confusing and can lead to false impressions.
> 
> Edit: I see now there is [a board for 6.7](https://github.com/orgs/WordPress/projects/223) as well. So why mention regular trac tickets in here that are completely unrelated to Gutenberg? Are contributors supposed to work here, or on the board?

Sorry for the confusion @swissspidy. That is completely on me. 

I had attempted to get one single source of truth for all the dev notes in this tracking issue to try and help make it less confusing for the team working on actually triaging the Dev Notes. But I realize how that may add more confusion as it is not respecting the lines of the different parts of the project. 

I will update this ticket here to again be only editor focussed and move the "Core" items to the project board. I may need a day to get back to this but you can safely ignore this ticket for now  👍

**Comment by jasmussen** [comment]
> do you think it would be worth it to have a section in the miscellaneous dev note that showcases the new icons?

My instinct is no, because I feel like adding those icons isn't necessarily a big deal. However this is my own, very soft, and personal opinion, and I'd be more than happy to author dev notes for any such pieces if _you_ think we should!

**Comment by ndiego** [comment]
> My instinct is no, because I feel like adding those icons isn't necessarily a big deal. However this is my own, very soft, and personal opinion, and I'd be more than happy to author dev notes for any such pieces if you think we should!

I agree here. Now, if there were 20+ new icons, that might be nice to highlight.

**Comment by sgomes** [comment]
>  - #64981 - @sgomes

As of #64981, the Media & Text block now uses an `img` element instead of using CSS `background-image` when the "Crop image to fill" option is enabled, removing the last usage of `background-image` in this block. This means that, when rendering the post, all the usual performance benefits of using image elements will now be applied, such as having the image load lazily when appropriate, and letting the browser choose the most appropriate image size from the list of generated sizes.


Please feel free to rephrase as needed! 👍

**Comment by ntsekouras** [comment]
Regarding https://github.com/WordPress/gutenberg/pull/64872 I think it will work best if we have a paragraph for related small enhancements. 


> A parent block's style variations are now surfaced for `contentOnly` locked groups. This way styles can still be applied cohesively across the group of blocks.

**Comment by sirreal** [comment]
> I will update this ticket here to again be only editor focussed and move the "Core" items to the project board. I may need a day to get back to this but you can safely ignore this ticket for now 👍

@fabiankaegy - https://github.com/WordPress/gutenberg/pull/65101 should move to the 6.7 Core release project board. I'm still planning to handle that dev note.

**Comment by ockham** [comment]
@fabiankaegy Here's a Dev Note for https://github.com/WordPress/gutenberg/pull/62092:

### block.json: `variations` field can now be set to name of PHP file that generates block variations

Previously, the `variations` field in a block.json file could be used to provide a static list of the block's variations (i.e., an array). Alternatively, the block's `variation_callback` could be set during server-side block registration to point to a PHP function to generate those variations.
As of WordPress 6.7, it is also possible to set the `variations` field to a string, which will then be interpreted as the filename of a PHP file that generates the variations (akin to how the [`render` field](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#render) works):

```json
{ "variations": "file:./variations.php" }
```

Refer to the [docs](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#variations) for more information.

---

LMK if this is alright!

**Comment by ockham** [comment]
@fabiankaegy 

The following items should probably also move to the [6.7 Core documentation](https://github.com/orgs/WordPress/projects/223/views/1) board:

- [Block Hooks: Allow insertion as first or last child of Template Part block](https://core.trac.wordpress.org/ticket/60854)
- [Block Hooks: "multiple": false not respected](https://core.trac.wordpress.org/ticket/61902)

(I've started working on those Dev Notes already.)

_Edit:_ Draft available [here](https://make.wordpress.org/core/?p=115678&preview=true).

**Comment by DaniGuardiola** [comment]
@fabiankaegy FYI [my note](https://github.com/WordPress/gutenberg/issues/65784#issuecomment-2389706120) had a typo:

```diff
-New `useResizeObserver` API in `@wordpress/components`
+New `useResizeObserver` API in `@wordpress/compose`
```

I edited the comment to correct it. Thanks @mirka for spotting this!

**Comment by ryanwelcher** [comment]
@fabiankaegy here is the dev note for the Query Loop block - preview is [here](https://make.wordpress.org/core/?p=115777)

## Updates to the Query Loop block in WordPress 6.7

WordPress 6.7 brings a number of improvements and changes to the Query Loop block.

The controls to set how many items to display, the offset and max number of pages, have been [moved from the block toolbar to the Inspector Sidebar](https://github.com/WordPress/gutenberg/pull/58207). This change standardizes the location of all of the query controls in the UI, making it much easier to find them.

Query Loop blocks that are inserted into single page, post, or custom post type now no longer display the Query Type control and [defaults to querying posts](https://github.com/WordPress/gutenberg/pull/65067). When using the block on templates, the Posts per page setting is now [inherited by the block](https://github.com/WordPress/gutenberg/pull/63358).

A new filter was added to allow filtering by [Post Formats](https://github.com/WordPress/gutenberg/pull/64167) and the [Posts List variation was removed](https://github.com/WordPress/gutenberg/pull/63404) due to some inconsistencies in how the block would receive defaults.

**Comment by mirka** [comment]
@fabiankaegy My dev note for #64526 (added at the bottom of the PR description) is actually a note for the Block Inspector (`@wordpress/block-editor`) and not the components package, so I'm thinking it should be separate from the other components package notes.

**Comment by artemiomorales** [comment]
@fabiankaegy I've updated the issue description to include the [Block Bindings dev note draft](https://docs.google.com/document/d/1UjxUHs2TfVcfVYvJjsThHOiw5XmD1lBh5ih8yx0XNFk/edit?tab=t.0) and updated myself to be the assignee.

**Comment by ciampo** [comment]
@fabiankaegy all dev notes in the "Components Package Updates" section (excluding #64526, as [explained above](https://github.com/WordPress/gutenberg/issues/65784#issuecomment-2408197107)) are [in this draft post](https://make.wordpress.org/core/?p=115801&preview=true). Feel free to tweak it as needed !

**Comment by DAreRodz** [comment]
@fabiankaegy, here is the [dev note draft](https://make.wordpress.org/core/?p=115821&preview=1&_ppp=73567c4a35) for the Interactivity API's `getServerState()`/`getServerContext()` functions.

**Comment by lezama** [comment]
@fabiankaegy, [here is a draft](https://docs.google.com/document/d/1Mx3T1BqvAtA9YP_QmG9XvBvvh8jb2OJcwbhZ0P3pKxA/edit?usp=sharing) for Extending PreviewOptions. Please let me know if you need anything else, thanks!

**Comment by stokesman** [comment]
@fabiankaegy, I’ve made [a draft](https://gist.github.com/stokesman/abc2cd78bf79b8a37dd70e5cbeb10574) for #64351. I'm a first-timer on dev notes so I hope it’s mostly usable.

**Comment by fabiankaegy** [comment]
@lezama Thank you :) The Dev Notes looks great from my perspective. Are you able to publish it on the Make Core blog yourself or do you need help with that? :)

**Comment by fabiankaegy** [comment]
@ciampo @mirka The Components Package Dev note looks great 💯 It is ready to be published  👍

**Comment by bph** [comment]
I'll prepare a 6.7 [Roster of design tools per block (WordPress 6.6 edition)](https://make.wordpress.org/core/2024/06/20/roster-of-design-tools-per-block-wordpress-6-6-edition/)

**Comment by jsnajdr** [comment]
Dev notes for #64204 and #64198:

## Support for async actions and filters in `@wordpress/hooks`

The `@wordpress/hooks` package has a couple of new functions for running async actions and filters, allowing plugin authors to conveniently register async (promise-based) handlers and make sure that they are run in series, one after another, waiting until the previous async handler finishes.

You can register an async function as an action or a filter handler:
```js
import { addAction, addFilter } from '@wordpress/hooks';

addAction( 'action', 'handler', async () => {
  await doSomethingAsync();
} );

addFilter( 'filter', 'handler', async ( value ) => {
  return await modifyValueAsync( value );
} );
```
In the filter handler, the `value` is always a synchronous value (not a promise) and the handler function returns a promise that resolves to an updated `value`.

Then you can run the filter with a newly introduced `applyFiltersAsync` function:
```js
import { applyFiltersAsync } from '@wordpress/hooks';

const filteredValue = await applyFiltersAsync( 'filter', initialValue );
```
and similarly you can also run an action with the new `doActionAsync` function:
```js
import { doActionAsync } from '@wordpress/hooks';

await doActionAsync( 'action' );
```

The runner functions make sure that handlers are run after each other, in a series. And that when a handler throws an error (or returns a rejected promise), the whole run is aborted and further handlers are not called. The error is propagated and becomes the result of the entire `applyFiltersAsync`/`doActionAsync` call.

## New filters to customize and extend behavior of post save

There are two new hooks (one filter and one action) that allow plugin authors to customize and extend what happens when a post is being saved.

First, there is the (async) `editor.preSavePost` filter that receives two arguments:
- `edits` is an object that contains the `id` of the saved post and the modified attributes. The filter can modify the `edits` and it will be this modified object that will be sent to the server as the payload of the save POST request. The filter can also abort the save, e.g., when some custom validation fails, by throwing an error or returning a rejected promise.
- `options` is a read-only second argument that contains an `isAutosave` (boolean) field that lets the filter distinguish between regular saves and autosaves, and also an `isPreview` field that indicated whether the saved post is a draft intended to be previewed.

The handler can be async, as the filter is being applied using the new `applyFiltersAsync` function:
```js
addFilter( 'editor.preSavePost', 'handler', async ( edits, options ) => {
  if ( ! await customValidation( edits ) ) {
    throw new Error( 'validation failed' );
  }
  return edits;
} );
```

The second new hook is the (async) `editor.savePost` action which is run after the post is saved and lets you perform additional work after the save. For example, the Gutenberg post editor itself uses this action to save legacy metaboxes for the post. This action also receives two arguments: first argument is an object with an `id` field, which is the saved post ID, and the second argument is `options` object, the same one as in the `editor.preSavePost` action.

**Comment by bph** [comment]
@fabiankaegy the [Design Tools roster for 6.7 post](https://make.wordpress.org/core/?p=115905&preview=1&_ppp=93ab123bba) is ready for review

**Comment by colorful-tones** [comment]
> [here is a draft](https://docs.google.com/document/d/1Mx3T1BqvAtA9YP_QmG9XvBvvh8jb2OJcwbhZ0P3pKxA/edit?usp=sharing) for Extending PreviewOptions.

The new plugin extensibility PreviewOptions is a great addition. Thanks for the amazing contribution! 👏 

I read through the draft, and I'm wondering if we could add a tiny bit more code example to answer the immediate question that every developer would likely have after seeing how to create a new `PluginPreviewMenuItem`: How can I manipulate or influence the editor canvas? 🤔 

Otherwise, adding a menu item is merely half the idea, and many developers will be left wanting more. The additional code should be very simple and just leave a breadcrumb for developers to know where or which API to look for next if they want to influence the editor's canvas with their newly added `PluginPreviewMenuItem`.

Perhaps my suggestion is outside the focus of a Dev Note, and I will defer to @fabiankaegy and others to guide us.

**Comment by fabiankaegy** [comment]
@colorful-tones thank you for that callout. From my understanding the API here provides none of that. It literally only allows you to render a button / link there so you can redirect someone somewhere else / trigger your own code from there. @lezama feel free to correct me if I'm wrong/ missing something :)

**Comment by lezama** [comment]
> It literally only allows you to render a button / link there so you can redirect someone somewhere else / trigger your own code from there

That’s correct! Further improvements are being proposed here: https://github.com/WordPress/gutenberg/issues/65005.

**Comment by mikachan** [comment]
@scruffian is away at the moment so here are some notes for his PRs listed above:

### For https://github.com/WordPress/gutenberg/pull/63318:

As part of the work to improve theme switching, WordPress 6.7 introduces two new functions which allow style variations to be called from either the currently active theme or a specific directory: `get_style_variation_files_from_current_theme` and `get_style_variations_from_directory`. When using these functions the requested style variations are displayed under Appearance > Styles and in the Site Editor under Global Styles > Browse Styles. In the future, we plan to expand the style variation options in the Editor by exposing style variations from other themes.

Both new functions work similarly to the existing function, `get_style_variations`, as described in the [docs](https://developer.wordpress.org/reference/classes/wp_theme_json_resolver/get_style_variations/).

### For https://github.com/WordPress/gutenberg/pull/62539:

WordPress 6.7 introduces a new "Typesets" section to Global Styles, which displays all typography presets in a separate panel in Global Styles. This is helpful when there are many typography presets available, as the list can become quite long, and it's easier to view them on a separate panel. This behaviour is also consistent with the way in which colour palettes are displayed in Global Styles.

To see individual typesets displayed in Global Styles, create a style variation JSON file that only contains a `settings.typography` section. This will be displayed under a "Typesets" heading under Styles > Typography.

-----------

I hope this isn't too late and they're helpful for the Miscellaneous Dev Note post!

**Comment by afercia** [comment]
Helloe veryone. @fabiankaegy just wanted to e sure: are all the changes tracked here supposed to be listed in the WordPress 6.7. feilds guide?

I'm not sure all of them are included or linked from the fields guide post.

I may be wrong but, for example, I'm not sure this post: https://make.wordpress.org/core/2024/10/18/editor-components-updates-in-wordpress-6-7/ is linked from [the fields guide post](https://make.wordpress.org/core/2024/10/23/wordpress-6-7-field-guide/) or from [the Miscellaneous Block Editor Changes post](https://make.wordpress.org/core/2024/10/20/miscellaneous-block-editor-changes-in-wordpress-6-7/). Am I missing something?

**Comment by fabiankaegy** [comment]
Hey @afercia 👋 

It is the 4th link from the top in the field guide? 🤔

**Comment by afercia** [comment]
> It is the 4th link from the top in the field guide? 🤔

@fabiankaegy I totally missed it 🤦🏻

**Comment by fabiankaegy** [comment]
Thank you to everyone who helped wrangling and writing these Dev Notes

**Comment by cbravobernal** [comment]
> Thank you to everyone who helped wrangling and writing these Dev Notes

Thank you for wrangling all the Dev Notes 🚀
