### ISSUE TITLE
Storybook: Add and Update Block Editor Components stories

### ISSUE THREAD

**Issue by miminari** [WordPress/gutenberg#67165]
## What problem does this address?

Most of Block Editor components don't have stories.
Block Editor components's Storybook should also be added and updated like the Components.
related #22891

## What is your proposed solution?

We can use this issue to track the addition and updating of the stories for Block Editor.
You can add the link to assign yourself to each component.
As I know, Block Editor Components list has never existed, so at first, we can start to be based on the directory name.
The list was made automatically, and we can ignore the component for native only.

If you cannot edit the list, please comment on which you made the PR for which directory's components.

cc @WordPress/gutenberg-components 

### 1. Use CSF 3 format

Write stories as objects, not functions

<details><summary>Do</summary>

```jsx
export const Default = {
	render: function Template( { onChange, ...args } ) {
		const [ value, setValue ] = useState();
		return (
			<SomeComponent
				{ ...args }
				onChange={ ( ...changeArgs ) => {
					onChange( ...changeArgs );
					setValue( ...changeArgs );
				} }
				value={ value }
			/>
		);
	},
};
```

</details> 

<details><summary>Don't</summary>

```jsx
const Template = ( { onChange, ...args } ) => {
	const [ value, setValue ] = useState();
	return (
		<SomeComponent
			{ ...args }
			onChange={ ( ...changeArgs ) => {
				onChange( ...changeArgs );
				setValue( ...changeArgs );
			} }
			value={ value }
		/>
	);
};

export const Default = Template.bind( {} );
```

</details> 

### 2. Consists of only one component
 
The purpose of Storybook is to test a single UI component itself. Therefore, unless there is a special reason, we should not include anything other than that component.

### 3. Don’t create too many stories

While it's tempting to expose as many variations of a component as possible, the behavior of the component can be changed in the Controls section.

Therefore, additional stories should only be included if they involve significant visual or behavioral changes.

### 4. About meta data

To display the source panel by default, specify `'shown'` in [the `meta.parameters.docs.canvas.sourceState` field](https://storybook.js.org/docs/api/doc-blocks/doc-block-canvas#sourcestate).

<details><summary>Example</summary>

```javascript
const meta = {
	// ...
	parameters: {
		docs: {
			canvas: { sourceState: 'shown' },
			// ...
		},
	},
	// ...
};
```

</details> 

Define the component description via the `meta.parameters.docs.description.component` field instead of a comment.

<details><summary>Example</summary>

```javascript
const meta = {
	// ...
	parameters: {
		docs: {
			// ...
			description: {
				component: 'Component description here...',
			},
		},
	},
	// ...
};
```

</details> 

Explicitly define the type of props via the `meta.argTypes.{propName}.table.type.summary` field.

<details><summary>Example</summary>

```javascript
const meta = {
	// ...
	argTypes: {
		// ...
		propName: {
			// ...
			table: {
				type: {
					summary: 'string',
				},
			},
		},
		// ...
	},
};
```

</details> 

For private components, you may want to define the following fields to display the badge 🔒 ([Private APIs README](https://github.com/WordPress/gutenberg/blob/trunk/packages/private-apis/README.md)).

Check [here](https://github.com/WordPress/gutenberg/blob/f1fadbb036f1e702e3a28072444fd0de28a5dc02/packages/block-editor/src/private-apis.js#L57-L100) to see if the component is exported as private.

<details><summary>Example</summary>

```javascript
const meta = {
	// ...
	tags: [ 'status-private' ],
	// ...
};
```

</details> 

### 5. Others

If the component you're working on doesn't have a README or JDoc, I'd appreciate it if you could do the following to clarify the component's implementation first:

- If there's no README file: This is part of https://github.com/WordPress/gutenberg/issues/22891. If the component already has JSDoc, you can use it to help write the README.
- If there's no README and no JSDoc: You'll need to analyze the component's implementation and clarify the types of props and return types. See https://github.com/WordPress/gutenberg/issues/22891#issuecomment-2543030487 for information on the JSDoc format.

## Block Editor Components directories List

<details><summary>Components List</summary>

Note: 🔒 indicates that the component is private.

- [x] alignment-control #67046
  - `AlignmentControl`
  -  `AlignmentToolbar`
- [x] ~audio-player (for native only)~
- [ ] autocomplete (`BlockEditorAutocomplete` based on `Autocomplete` from `@wordpress/components`. Pending until the `Autocomplete` component's stories are made.) #70926
- [x] ~background-image-control/BackgroundImagePanel~ #67184 
- [x] (Internal) ~block-actions~
- [ ] block-alignment-control #67233
  - `BlockAlignmentControl`
  - `BlockAlignmentToolbar`
- [x] block-alignment-matrix-control (Has `__experimental` prefix) #68007
- [ ] block-breadcrumb #68000 
- [ ] block-canvas #68589
  - `BlockCanvas`
  - 🔒 `ExperimentalBlockCanvas`
- [x] ~block-caption (for native only)~
- [x] ~(Internal) block-card~
  - #67191 
  - #68114
  - #68556
- [x] (Internal) ~block-compare~ #68004
- [ ] block-content-overlay (Has `__experimental` prefix)
- [x] (Internal) ~~block-context~~ #68635
- [ ] block-controls
  - `BlockControls`
  - `BlockFormatControls`
- [x] (Internal) ~block-draggable~ #68269
- [ ] block-edit
- [x] (Internal) ~block-edit-visually-button~
- [x] ~block-editing-mode~ (Reack Hook)
- [ ] block-full-height-alignment-control (Has `__experimental` prefix) #67227
- [x] block-heading-level-dropdown #67294
- [x] block-icon #67186 
- [x] (Removed) ~block-info-slot-fill~
- [ ] block-inspector #68340
- [ ] block-list
- [x] (Internal) ~block-list-appender~
- [x] (Internal) ~block-lock~
- [x] ~block-media-update-progress (for native only)~
- [ ] 🔒 block-manager #68634
- [x] block-mover #66519
- [x] (Deprecated) ~block-navigation~
- [x] (Internal) ~block-parent-selector~
- [ ] block-pattern-setup (Has `__experimental` prefix) #68516
- [ ] block-patterns-list (Has `__experimental` prefix) #68777
- [x] (Internal) ~block-patterns-paging~ #68512
- [ ] block-popover
- [ ] block-preview #68140
- [ ] 🔒 block-quick-navigation #68624
- [ ] 🔒 block-removal-warning-modal
- [x] (Internal) ~block-rename~ #67386
- [ ] block-selection-clearer #68473
- [x] ~block-settings (for native only)~
- [ ] block-settings-menu #68702
  - `BlockSettingsMenu`
  - `__unstableBlockSettingsMenuFirstItem` (Has `__unstable` prefix)
- [ ] block-settings-menu-controls #68729
- [ ] block-styles #68638
- [x] (Internal) ~block-switcher~ #68496
- [x] block-title #67234
- [ ] block-toolbar
  - `__unstableBlockToolbarLastItem` (Has `__unstable` prefix)
  - `__unstableBlockToolbarLastItem` (Has `__unstable` prefix)
- [ ] block-tools #68957
- [x] (Internal) ~block-types-list~ #68497
- [ ] block-variation-picker (Has `__experimental` prefix) #68700
- [ ] block-variation-transforms (Has `__experimental` prefix) #68710
- [ ] block-vertical-alignment-control #68461
  - `BlockVerticalAlignmentToolbar`
  - `BlockVerticalAlignmentControl`
- [x] border-radius-control (Has `__experimental` prefix) #67383
- [ ] button-block-appender #68598
- [x] ~caption (for native only)~
- [x] (Internal) ~child-layout-control~
- [x] (Internal) ~collab~
- [ ] color-palette #67846
  - `ColorPalette`
  - `ColorPaletteControl`
- [x] (Deprecated) ~color-style-selector~ #68543
- [ ] colors
- [ ] colors-gradients (Has `__experimental` prefix) #68675
  - `__experimentalColorGradientControl`
  - `__experimentalColorGradientSettingsDropdown`
  - `__experimentalPanelColorGradientSettings`
- [x] (Internal) ~content-lock~
- [x] contrast-checker #68120
- [x] (Internal) ~convert-to-group-buttons~
- [x] (Deprecated) ~copy-handler~ #68548
- [x] date-format-picker (Has `__experimental` prefix) #67290
- [ ] default-block-appender #70601
- [ ] 🔒 dimensions-tool
- [x] (Not a component) ~duotone~
- [ ] duotone-control (Has `__experimental` prefix)
  - #68293
  - #68262 
- [x] (Internal) ~editable-text~
  - #68314
  - #68291
  - #68256
- [ ] editor-styles (Has `__unstable` prefix) #68739
- [x] (Internal) ~floating-toolbar~ #68379
- [ ] font-appearance-control (Has `__experimental` prefix) #68279 
- [ ] font-family (Has `__experimental` prefix) #67165
- [ ] font-sizes #68171
- [ ] 🔒 global-styles
- [ ] gradients
- [x] (Internal) ~grid~
- [ ] height-control #68001
- [ ] iframe (Has `__unstable` prefix)
- [ ] image-editor (Has `__experimental` prefix) #68645
- [x] ~image-link-destinations (for native only)~
- [x] (Deprecated) ~image-size-control (Has `__experimental` prefix)~ #68285
- [ ] inner-blocks #68651
- [ ] inserter
  - [ ] `_Inserter`
  - [ ] `__experimentalLibrary` (Has `__experimental` prefix)
  - [ ] 🔒 `PrivateQuickInserter`
- [x] ~inserter-button (for native only)~
- [x] (Internal) ~inserter-draggable-blocks~ #68312
- [x] (Internal) ~inserter-list-item~
  - #68403
  - #68366
- [x] (Internal) ~inserter-listbox~
- [ ] inserter-menu-extension (Has `__experimental` prefix)
- [ ] inspector-controls
  - `InspectorControls`
  - `InspectorAdvancedControls`
- [x] (Internal) ~inspector-controls-tabs~
- [ ] inspector-popover-header (Has `__experimental` prefix)
  - #68272 
  - #68394
- [ ] justify-content-control #68137
  - `JustifyToolbar`
  - `JustifyContentControl`
- [ ] keyboard-shortcuts #68459
- [ ] letter-spacing-control (Has `__experimental` prefix) #67342
- [ ] line-height-control #68041
- [ ] link-control #68382
  - `LinkControl`
  - (Deprecated) ~`__experimentalLinkControl` (Has `__experimental` prefix)~
  - (Deprecated) ~__experimentalLinkControlSearchInput` (Has `__experimental` prefix)~
  - (Deprecated) ~`__experimentalLinkControlSearchResults` (Has `__experimental` prefix)~
  - (Deprecated) ~`__experimentalLinkControlSearchItem` (Has `__experimental` prefix)~
- [ ] list-view
  - `ListView` (Has `__experimental` prefix)
  - 🔒 `PrivateListView`
- [ ] media-placeholder #68558
- [ ] media-replace-flow #68571
- [ ] media-upload #68673
  - `MediaUpload`
  - `MediaUploadCheck`
- [x] ~media-upload-progress (for native only)~
- [x] (Internal) ~multi-selection-inspector~ #68308
- [ ] navigable-toolbar #68474
- [ ] observe-typing
- [ ] panel-color-settings #68127
- [x] plain-text #67341
- [x] (Deprecated) ~preview-options (Has `__experimental` prefix)~
- [ ] 🔒 provider
- [ ] publish-date-time-picker (Has `__experimental` prefix) #68192
- [ ] recursion-provider #68593
- [ ] 🔒 resizable-box-popover
- [x] 🔒 resolution-tool #68292
- [ ] responsive-block-control (Has `__experimental` prefix) #68336
- [ ] rich-text
  - `RichText`
  - `RichTextShortcut` #68717
  - `RichTextToolbarButton` #68703
- [x] (Deprecated) ~selection-scroll-into-view~
- [ ] skip-to-selected-block #68289
- [ ] spacing-sizes-control (Has `__experimental` prefix) #68339
- [x] 🔒 tabbed-sidebar #68118
- [x] 🔒 text-alignment-control #67371 
- [x] text-decoration-control (Has `__experimental` prefix) #67337
- [x] text-transform-control (Has `__experimental` prefix) #67365 
- [ ] tool-selector #68586
- [ ] typewriter #68305
- [x] (Internal) ~ungroup-button~
- [x] unit-control (Has `__experimental` prefix) #67346
- [x] (Internal) ~unsupported-block-details~
- [ ] url-input
  - `URLInput` #68286
  - `URLInputButton` #68320
- [ ] url-popover #68449
  - `URLPopover`
  - `__experimentalImageURLInputUI` (Has `__experimental` prefix)
- [x] ~use-block-commands~ (Reack Hook)
- [x] ~use-block-display-information~ (Reack Hook)
- [x] ~use-block-drop-zone~ (Reack Hook)
- [x] ~use-flash-editable-blocks~ (Reack Hook)
- [x] ~use-moving-animation~ (Reack Hook)
- [x] ~use-on-block-drop~ (Reack Hook)
- [x] ~use-paste-styles~ (Reack Hook)
- [x] ~use-resize-canvas~ (Reack Hook)
- [x] ~use-settings~ (Reack Hook)
- [x] ~use-unsupported-block-editor (for native only)~
- [x] ~video-player (for native only)~
- [x] warning #68124
- [ ] writing-flow #70841
- [x] writing-mode-control (Has `__experimental` prefix) #67343

</details>

**Comment by miminari** [comment]
@imanish003 @Sukhendu2002 @Infinite-Null @SainathPoojary @himanshupathak95 @Sukhendu2002 
Thank you all for making PR.
Could you please add links to the list by yourself?
Because it takes time to determine which component is in which directory.
If you cannot edit the list, please comment which you made the PR for which directory's components.

**Comment by im3dabasia** [comment]
Hey @miminari ,

I submitted a [PR](https://github.com/WordPress/gutenberg/pull/67346) for the Unit Control component: gutenberg/packages/block-editor/src/components/unit-control

**Comment by SainathPoojary** [comment]
Hey @miminari,

I have submitted a PR for the following components:

- [x] block-title https://github.com/WordPress/gutenberg/pull/67234
- [x] date-format-picker https://github.com/WordPress/gutenberg/pull/67290
- [x] plain-text https://github.com/WordPress/gutenberg/pull/67341

**Comment by Infinite-Null** [comment]
Hey @miminari,

I have submitted PR for the following components:

- [x] block-card https://github.com/WordPress/gutenberg/pull/67191
- [ ] letter-spacing-control https://github.com/WordPress/gutenberg/pull/67342
- [ ] line-height-control https://github.com/WordPress/gutenberg/pull/68041 
- [ ] font-family-control https://github.com/WordPress/gutenberg/pull/68338
- [x] block-card remove story https://github.com/WordPress/gutenberg/pull/68556

**Comment by Sukhendu2002** [comment]
Hey @miminari,

I have submitted PR for the following components:

- [x] writing-mode-control https://github.com/WordPress/gutenberg/pull/67343
- [x] block-heading-level-dropdown https://github.com/WordPress/gutenberg/pull/67294
- [x] block-alignment-matrix-control https://github.com/WordPress/gutenberg/pull/67292

**Comment by himanshupathak95** [comment]
Hey @miminari,

I have submitted a PR for the following components:

- [x] text-alignment-control https://github.com/WordPress/gutenberg/pull/67371
- [x] text-decoration-control https://github.com/WordPress/gutenberg/pull/67337
- [x] contrast-checker https://github.com/WordPress/gutenberg/pull/68120

**Comment by youknowriad** [comment]
I'm curious about the reasoning here :). I'm not saying we shouldn't be doing this but curious to lean what value you folks will be receiving from this ?

cc @WordPress/gutenberg-core for awareness.

**Comment by mirka** [comment]
I see a couple benefits from the maintainer side:

- Improve engineering quality. Working in the isolated story when iterating on the component (as opposed to working directly in the Gutenberg app) promotes better engineering standards because it forces you to think about encapsulation, clear interfaces, etc.
- Increase iteration speed. Having a story is much faster for discovery and testing different states. You don't have to dig around the app to see where the component is used, figure out what states exist, and how to reproduce them.

I honestly don't know if there is pure documentation value for the extenders.

I'd like to emphasize that we should write the stories in a way that **keeps maintenance cost at a minimum**. It will quickly become a net-negative if the stories incur a maintenance cost. For example, avoid hardcoded values as much as possible, and try to structure things in a way that will not need fixing when the underlying component code changes. Don't write unnecessary descriptions, as those are another thing that need to be updated manually when things change. Let's start with the simplest possible.

**Comment by t-hamano** [comment]
As a plugin developer, I find Storybook extremely useful.

When implementing a UI for a custom block or block editor, I can see what components are exposed, what props are supported, and how they work.

Without Storybook, it's hard to imagine how something would work unless I actually wrote the code while reading the documentation, or found a place in the Gutenberg repository where the component is actually used.

**Comment by t-hamano** [comment]
I have looked at the PR linked to this issue and I think we need some kind of indicator to unify our implementations and approaches for contributors who are already working on this issue or are planning to work on it.

Below are my thoughts on best practices, but @WordPress/gutenberg-components, if there are any mistakes, please let me know.

### Use CSF 3 format

Write stories as objects, not functions

#### Do

```jsx
export const Default = {
	render: function Template( { onChange, ...args } ) {
		const [ value, setValue ] = useState();
		return (
			<SomeComponent
				{ ...args }
				onChange={ ( ...changeArgs ) => {
					onChange( ...changeArgs );
					setValue( ...changeArgs );
				} }
				value={ value }
			/>
		);
	},
};
```

#### Don't

```jsx
const Template = ( { onChange, ...args } ) => {
	const [ value, setValue ] = useState();
	return (
		<SomeComponent
			{ ...args }
			onChange={ ( ...changeArgs ) => {
				onChange( ...changeArgs );
				setValue( ...changeArgs );
			} }
			value={ value }
		/>
	);
};

export const Default = Template.bind( {} );
```

### Consists of only one component

I think the purpose of Storybook is to test a single UI component itself. Therefore, unless there is a special reason, we should not include anything other than that component.

### Don’t create too many stories

While it's tempting to expose as many variations of a component as possible, the behavior of the component can be changed in the Controls section.

Therefore, I think additional stories should only be included if they involve significant visual or behavioral changes.

**Comment by t-hamano** [comment]
Additional Tips - To improve code consistency, I would personally be happy to implement the following rules for existing and future PRs:

To display the source panel by default, specify `'shown'` in [the `meta.parameters.docs.canvas.sourceState` field](https://storybook.js.org/docs/api/doc-blocks/doc-block-canvas#sourcestate).

```javascript
const meta = {
	// ...
	parameters: {
		docs: {
			canvas: { sourceState: 'shown' },
			// ...
		},
	},
	// ...
};
```

Define the component description via the `meta.parameters.docs.description.component` field instead of a comment.

```javascript
const meta = {
	// ...
	parameters: {
		docs: {
			// ...
			description: {
				component: 'Component description here...',
			},
		},
	},
	// ...
};
```

Explicitly define the type of props via the `meta.argTypes.{propName}.table.type.summary` field.

```javascript
const meta = {
	// ...
	argTypes: {
		// ...
		propName: {
			// ...
			table: {
				type: {
					summary: 'string',
				},
			},
		},
		// ...
	},
};
```

**Comment by t-hamano** [comment]
I noticed that some components have the `__experimental` or `__unstable` prefix.

I wondered if I should publish these components to Storybook, but some components with these prefix have already been published.

If the component has a proper README and code examples, I believe it's okay to publish it to Storybook.

**Comment by t-hamano** [comment]
Thanks to everyone working on this issue. Although not directly related to this issue, I noticed that some components don't have a README or JSDoc.

If the component you're working on doesn't have a README or JDoc, I'd appreciate it if you could do the following to clarify the component's implementation first:

- If there's no README file: This is part of #22891. If the component already has JSDoc, you can use it to help write the README.
- If there's no README and no JSDoc: You'll need to analyze the component's implementation and clarify the types of props and return types. See [this comment](https://github.com/WordPress/gutenberg/issues/22891#issuecomment-2543030487) for information on the JSDoc format.

**Comment by Mamaduka** [comment]
Excellent team effort here.

@t-hamano, your tips and suggestions should be included in the issue description. It's helpful information and is currently hidden in GitHub activity. We could use the `details` element to collapse the component list. It's taking up too much space, in my opinion.

**Comment by t-hamano** [comment]
@Mamaduka Thanks for the feedback! I've summarized all the tips and suggestions in the description.

**Comment by t-hamano** [comment]
Update: I would like to propose adding badges (🔒) to private components. Please see the "4. About meta data" section of this issue for more details.

**Comment by t-hamano** [comment]
Update: I noticed that some components are internal and not public, so I updated the list. For internal components, it is marked as `(Internal) component`.

We need to consider whether to expose internal components to Storybook.

If we do, it may be useful for Gutenberg contributors, but it will not be useful for the extenders.

Personally, I don't think internal components need to be exposed. However, some PRs have already been submitted for internal components, so we will need to close them. Sorry, I should have noticed this sooner.

I look forward to your comments.

**Comment by Mamaduka** [comment]
Unlike private components, I think there is no intention of publicizing internal ones, so exposing them doesn't make sense.

**Comment by t-hamano** [comment]
Okay, so let's not add Storybook to the internal components. I will update the list and close the PRs that have already been submitted as well. I apologize to everyone who worked on these issues 🙇‍♂️

**Comment by Mamaduka** [comment]
We should also avoid adding stories for deprecated components. Deprecation means that consumers should avoid using these components, so there's no need to "promote" them via Storybook.

**Comment by t-hamano** [comment]
> We should also avoid adding stories for deprecated components.

That's true. I've added the `(Deprecated)` to the deprecated components.

**Comment by aditya-raj-panjiyara** [comment]
Hello @miminari, Is this issue still open? If so, can I work on this?

**Comment by miminari** [comment]
@aditya-raj-panjiyara Hello! Thank you for your comment.
I believe we’re still working on this, and you can understand how it works by reading the issue documentation.
However, the remaining tasks might be a bit too difficult for a “Good first issue.”

**Comment by HARMANPREETSINGHINBT06373OCT23** [comment]
“Hi! I'd like to work on adding a Storybook story for the BlockTitle component (or any other listed). Is that okay?”

**Comment by t-hamano** [comment]
@HARMANPREETSINGHINBT06373OCT23

The `BlockTitle` component already has a story: https://github.com/WordPress/gutenberg/pull/67234. Check the "Block Editor Components directories List" section at the bottom of [this comment](https://github.com/WordPress/gutenberg/issues/67165#issue-2676118469) and check the components which have no linked PRs.

**Comment by vaibhavshinde8478** [comment]
I will work on adding stories for the Autocomplete component.

**Comment by DHANUSHRAJA22** [comment]
Hi! I'd like to work on adding Storybook stories for the `colors` component. I see it doesn't have a linked PR yet. I'll follow the best practices outlined in the issue description and create stories using CSF 3 format. 

Is this component available for me to work on? Thanks!

**Comment by karmatosed** [comment]
I think it might be important to identify which need and which have already, it seems there are some cross over pieces. I would almost suggest going one by one over having one large issue.

**Comment by Jashnavi25** [comment]
Hi! I'd like to work on this issue for Hacktoberfest. Please assign me.

**Comment by scruffian** [comment]
> Hi! I'd like to work on this issue for Hacktoberfest. Please assign me.

There's no need to be assigned. Feel free to pick it up any time :)
