### ISSUE TITLE
Convert packages to TypeScript

### ISSUE THREAD

**Issue by manzoorwanijk** [WordPress/gutenberg#67691]
This issue tracks the progress in adding native TypeScript support to the `@wordpress/block-editor` package. Currently open PRs:

- [x] https://github.com/WordPress/gutenberg/pull/67667
- [x] https://github.com/WordPress/gutenberg/pull/70362
- [x] `a11y`: https://github.com/WordPress/gutenberg/pull/70680
- [x] `annotations`: https://github.com/WordPress/gutenberg/pull/70602
- [x] `api-fetch`: https://github.com/WordPress/gutenberg/pull/67669
- [x] `block-serialization-default-parser`: https://github.com/WordPress/gutenberg/pull/70766
- [x] `blocks`: https://github.com/WordPress/gutenberg/pull/76312
- [x] `browserslist-config`: https://github.com/WordPress/gutenberg/pull/70521
- [x] `data`: #76149
- [x] `date`: https://github.com/WordPress/gutenberg/pull/67665
- [x] `dom-ready`: https://github.com/WordPress/gutenberg/pull/67671
- [x] `element`: https://github.com/WordPress/gutenberg/pull/70886
- [x] `html-entities`: https://github.com/WordPress/gutenberg/pull/69326
- [x] `hooks`: https://github.com/WordPress/gutenberg/pull/70488
- [x] `i18n`: https://github.com/WordPress/gutenberg/pull/70843
- [x] `icons`: https://github.com/WordPress/gutenberg/pull/70456
- [x] `is-shallow-equal`: https://github.com/WordPress/gutenberg/pull/70407
- [x] `jest-console`: https://github.com/WordPress/gutenberg/pull/70538
- [x] `jest-puppeteer-axe`: https://github.com/WordPress/gutenberg/pull/70523
- [x] `keycodes`: https://github.com/WordPress/gutenberg/pull/70466
- [x] `keyboard-shortcuts`: https://github.com/WordPress/gutenberg/pull/76287
- [x] `lazy-import`: https://github.com/WordPress/gutenberg/pull/70475
- [x] `list-reusable-blocks`: https://github.com/WordPress/gutenberg/pull/70518
- [x] `notices`: https://github.com/WordPress/gutenberg/pull/67670
- [x] `plugins`: https://github.com/WordPress/gutenberg/pull/70773
- [x] `preferences`: https://github.com/WordPress/gutenberg/pull/71915
- [x] `priority-queue`: https://github.com/WordPress/gutenberg/pull/70469
- [x] `prettier-config`: https://github.com/WordPress/gutenberg/pull/70533
- [x] `redux-routine`: https://github.com/WordPress/gutenberg/pull/70686
- [x] `shortcode`: https://github.com/WordPress/gutenberg/pull/74522
- [x] `undo-manager`: https://github.com/WordPress/gutenberg/pull/70757
- [x] `url`: https://github.com/WordPress/gutenberg/pull/70496
- [x] `viewport`: https://github.com/WordPress/gutenberg/pull/71118
- [x] `wordcount`: https://github.com/WordPress/gutenberg/pull/70501
- [x] https://github.com/WordPress/gutenberg/pull/67666
- [ ] `compose`: https://github.com/WordPress/gutenberg/pull/70618
- [ ] `project-management-automation`: https://github.com/WordPress/gutenberg/pull/71193
- [ ] `rich-text`: https://github.com/WordPress/gutenberg/pull/69314
- [ ] `sync`: https://github.com/WordPress/gutenberg/pull/71099

**Comment by margolisj** [comment]
@gziolo Is there a chance to get some of these package conversions reviewed and merged into trunk?

**Comment by margolisj** [comment]
A few missing that need review + approval:
#69314 
#67671

I'm happy to pick any of these up and get them up to trunk head.

**Comment by t-hamano** [comment]
It seems that TypeScript conversion is underway in various packages, not just the `@wordpress/block-editor` package. Let's treat this issue as a tracking issue for all packages.

**Comment by t-hamano** [comment]
Thanks to everyone working on this issue.

I recommend reading https://github.com/WordPress/gutenberg/discussions/67781 once in relation to this issue. Perhaps it would be a good idea to proceed with converting low-level packages.


From https://github.com/WordPress/gutenberg/discussions/67781#discussion-7648178:

> Avoid big scale migration of all packages: This is going to create a lot of noise in open PRs... instead focus on typing as we fix bugs and implement features. Some targeted package migrations can be beneficial though: Especially the low level ones (blocks, rich-text)

**Comment by wwahammy** [comment]
I just started working on migrating commands to TS at https://github.com/WordPress/gutenberg/pull/76286.  I need to some more cleanup but I think it's honestly pretty close.

**Comment by manzoorwanijk** [comment]
> I just started working on migrating commands to TS at [#76286](https://github.com/WordPress/gutenberg/pull/76286). I need to some more cleanup but I think it's honestly pretty close.

I will soon start reviewing the PRs for this. Let us finish this job. 💪
