### ISSUE TITLE
"Undo trap": Avoid getting stuck in an editing state

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#8119]
**Undo trap:** The situation in which a user is "stuck" when continuously pressing Undo. The typical cause: as Undo is pressed and the content is reverted, some event somewhere causes a new undo level to be created. The result is that the user is unable to undo past a certain point, thereby losing access to previous editing states.

This issue aggregates all bugs stemming from that common problem:

- [x] Gallery: Conversion from raw (#6325, https://github.com/WordPress/gutenberg/pull/42001)
- [x] Embeds: Conversion from raw (#7323)
- [x] Image: Adding via upload (#3553)
- [x] File: Adding via drag-and-drop (#8155)

## Problem

At the root of these bugs is the fact that blocks need to manage a transition using specific ephemeral state:
- when converting from `[gallery ids="x,y,z"]`, a Gallery block needs to temporarily keep the IDs `x, y, z` of the images while it waits for API data necessary to the block (the URL and `alt` attribute for each image); once it receives the API data, it adds it to its attributes [resolved state];
- when adding an Image via file upload, the Image block initially keeps the image blob in order to render a pulsing image while waiting for upload conclusion; then, it updates its attributes to store the newly created URL for the uploaded image [resolved state];

Since the temporary states are encoded in the attributes themselves of the blocks, they automatically constitute an undo level of the editor history. Thus, the action of undoing will bring the blocks back to that temporary state, which itself triggers a transition "back" into the resolved state.

## Solutions

There are, as I see it, two approaches:

- Altogether avoid encoding transitional states in a block's attributes. Since this is a problem that is likely to affect third-party blocks as well, ideally the problem wouldn't be fixed _ad hoc_ but rather using a standardized method to express such states. It could be expressed in terms of creating a new block by passing it a "seed" for a future state (e.g. the seed of an image ID to later yield an image URL).
- Go in a very different direction and consider that certain "events" (term used loosely) in the application are made up of a sequence of action dispatches over time. So, for the constitution of a Gallery block converted from shortcode, the actions would be <block created with image IDs> and <block attributes updates with actual URLs>; these would fold into a single event, thus a single undo level. This approach is much more ambitious and likely to be overkill and less robust. I explain it at length in this comment: https://github.com/WordPress/gutenberg/pull/6325/#issuecomment-402242054

The first option seems to be worth exploring first. A quick stab at the second one — by hacking `withHistory` — doesn't inspire a lot of confidence.

**Comment by noisysocks** [comment]
> when adding an Image via file upload, the Image block initially keeps the image blob in order to render a pulsing image while waiting for upload conclusion; then, it updates its attributes to store the newly created URL for the uploaded image [resolved state];

I was looking into this a little. An image can be uploaded by 1) pressing _Upload_ on an image block; 2) drag-and-dropping an image onto an image block; and 3) drag-and-dropping an image straight into the editor. Using `setState()` instead of `setAttributes()` to store image blobs in `ImageEdit` fixes (1) and (2) nicely, but doesn't handle (3). Like you say, we need some way of passing data from `createBlock()` to the `ImageEdit` constructor.

**Comment by noisysocks** [comment]
@talldan discovered another bug to do with this in https://github.com/WordPress/gutenberg/pull/8066#issuecomment-406996686.

**Comment by claudiobrandt** [comment]
I also came across this undo trap when I pasted a text that included a URL. The URL became its own block, and when trying to undo, the browser kept reaching out to the URL and the paste could not be undone.

**Comment by mcsf** [comment]
Thanks for the input, @claudiobrandt. That sounds like an Embed issue (#7323), as listed in this issue's description, correct?

**Comment by claudiobrandt** [comment]
Yes, @mcsf, the same behavior, except that I noticed it while copying/pasting content that included lines with nothing but an URL. These lines were converted to a block after the paste operation, and undoing the conversion was not possible. This behavior doesn't happen all the time and further testing with copy/paste operation should be performed. As you can see in the video I prepared right now, while testing it again, if I copy and paste a list of URLs from a Notepad.exe document, the URLs are not converted and they become a single text block. If I paste the same list from a word processor, where each URL is already presented as a link (I used LibreOffice for testing), the results vary. The first time a paste, the URLs are converted to embeds, and I can undo it. When pasting the same content a second time, I can't undo it anymore. [1'19](http://youtu.be/zi_k9SI6TRQ?hd=1)

**Comment by mcsf** [comment]
Thanks for the details and video, @claudiobrandt.

The difference in results between Notepad and LibreOffice is expected: although sometimes perhaps surprising, Gutenberg determines whether the pasted content is "plain text" or not, and depending on that it may skip certain types of processing (because it assumes the user doesn't want added formatting).

As for the rest, your report will be taken into account. Internally, pasting and manual conversion of blocks essentially work in the same way. :)

**Comment by youknowriad** [comment]
@mcsf I'm moving out of 4.2 but if your work is ready, we can reconsider.

**Comment by mcsf** [comment]
> and (c) from a user's perspective, are these progressions sensible, since a completion could occur after some other intermediary actions they take (e.g. a gallery is created, but before it finishes, the users adds some more text; Undo-ing could remove the gallery before it'd undo the text changes)

In my mind, resolution actions would amend the undo history into the past, e.g.
- a gallery is created, but before it finishes the user adds some text
- if the user undoes at that point, the text is removed and the partial gallery is kept
- if the user doesn't undo and the gallery finishes loading, the history becomes [ "gallery created and complete", "text inserted" ]
- if the user undoes at that point, the text is removed and the finished gallery is kept

Is this achievable and desirable with a cheaper and more predictable model of keeping track of states, such as the "single timeline across stores" you suggested?

> * To the point of a block tracking itself through transient states, it occurred to me an idea that perhaps a block would define some property (e.g. `isTransientState`) where, given a set of attributes, the function would return a value indicating to the framework that it be considered in a transient state. 

Would it be all-or-nothing or attribute-based? It sounds like the former, i.e. `isTransientState` would just return a boolean. It sounds interesting, but how can we tie it back to particular states or attributes (and do we want to)?

> For more than just as it impacts this issue, I'm not as confident now with what I'd proposed there with actions to replay on initial state. Ideally the block implementation doesn't need to search through and replace actions which occurred previously, as it's both inefficient and because there could be _many_ ways a block enters a transient state (unless we made assumptions merely about these very specific creation workflows).

Yeah, I think we need to audit a little and codify possible transient states, and whether the same block type should be allowed more than one such state. As for efficiency, there probably needs to be a "window of replay", after which the resolution of a transient state doesn't amend anything (and it presumably would just add another undo step).

**Comment by talldan** [comment]
> A challenge here is, especially for block transforms (which return a block object, not actions/dispatches), where does this partitioning of transient vs. non-transient values take place?

From a look at the code, the handlers in `BlockDropZone` are a good example:
https://github.com/WordPress/gutenberg/blob/bb6dfea267980c959080fbf9dab8c362159bba47/packages/editor/src/components/block-drop-zone/index.js#L65-L84

They result in an `INSERT_BLOCKS` action that's handled by the `attributes` reducer. 

Could an option be that every INSERT_BLOCKS action is considered transient, providing the opportunity for later attribute updates to collapse their undo state into it?

That would allow something like media blocks to also specify that some of their early attribute updates can be considered part of the same undo action as that created by INSERT_BLOCKS. I have this vague idea that the states would be named to identify that they can be collapsed:
```
setAttributes( {
    id, url
}, 'CREATE_BLOCK' );
```

**Comment by epiqueras** [comment]
>Go in a very different direction and consider that certain "events" (term used loosely) in the application are made up of a sequence of action dispatches over time. So, for the constitution of a Gallery block converted from shortcode, the actions would be and ; these would fold into a single event, thus a single undo level. This approach is much more ambitious and likely to be overkill and less robust. I explain it at length in this comment: #6325

The entities refactor allowed me to take an approach like this in #19937 quite trivially.

**Comment by paaljoachim** [comment]
Can we get a status update here?
Thanks!

**Comment by mcsf** [comment]
> Can we get a status update here?
> Thanks!

It remains a difficult problem, and no one has had the bandwidth to solve it well. It hasn't been forgotten, though.

**Comment by ellatrix** [comment]
Unassigning myself until I intend to work on this again. The bot assigned me because of a PR but didn't unassign me when I closed it.

**Comment by Mamaduka** [comment]
I've encountered another issue related to keeping file blobs in attributes while working on #32157.

**Conditions**
* Block handles temporary image upload on the mount
* Doesn't provide block example
* User registers custom block styles

**Currently affected blocks**
* File
* Audio

When a block has no example, the "Styles" preview will use attributes. Then the block preview will trigger another upload based on the file blob attribute.

A simple solution will be to provide examples for both blocks. Another one will be to store temporary URLs in a state like #30114.

**Comment by Mamaduka** [comment]
I went ahead and created PR for audio block #32333.

File block doesn't have the "Insert from URL" option, so not sure how the example preview should work here.

**Comment by mcsf** [comment]
> I've encountered another issue related to keeping file blobs in attributes while working on #32157. […]

Thanks for spotting that one.

**Comment by Mamaduka** [comment]
@mcsf Any preference on how I should fix this for the File block? Add an example or use the state for temporary URLs?

**Comment by mcsf** [comment]
Referencing #36807 for tracking purposes.

**Comment by Mamaduka** [comment]
@mcsf, we fixed a few others recently. I'm going to add them for tracking purposes - #30203, #34565, #35767.

**Comment by mcsf** [comment]
Thanks, keeping that trail is always useful. :)

**Comment by kevin940726** [comment]
I had some time to dig into the problem of the gallery block and the "undo trap" issue in general. This “undo trap” issue can happen when these conditions meet:

1. The block calls `setAttributes` or any other updating methods that push to the undo stack (create an *undo level*).
2. The method is NOT called as an *“event”*, coined by the [`useEvent` RFC](https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md).

As a general rule of thumb, an action should only be able to push to the undo stack if the action is performed by user interactions. However, there are existing patterns in the gutenberg repository (I believe in other third-party blocks too) that don’t follow this practice. The most common mistake is the misuse of the `useEffect` hook.

The details of when to and not to use the `useEffect` hook are outlined in the new official React [documentation](https://beta.reactjs.org/learn/you-might-not-need-an-effect). We can take real code in the Gallery block as an example here:

https://github.com/WordPress/gutenberg/blob/7f7c24ddb16bc6f75e487557a4b41824d5a1597e/packages/block-library/src/gallery/edit.js#L304-L314

Upon first creating the Gallery block, the `useEffect` here will run to update itself and set the `linkTo` attribute via `setAttributes`. This is an incorrect use of the `useEffect` hook to [update states (attributes) based on props or states (attributes)](https://beta.reactjs.org/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state). More importantly, the `setAttributes` here doesn’t run on user interactions, but runs automatically on change of the attributes.

## The solutions

There are some options for this issue:

1. `__unstableMarkNextChangeAsNotPersistent`

A common pattern in our codebase, is to use a lesser-known API `__unstableMarkNextChangeAsNotPersistent`. Calling it before `setAttributes` will mark the action as not *persistent*, which means it won’t push to the undo stack. It’s exactly how it’s done in #26377. This solution works but relies on an unstable API (which has been unstable for [2 years](https://github.com/WordPress/gutenberg/pull/19521) already) that’s hard and explicit for third-party authors to learn and use in day-to-day life.

```js
__unstableMarkNextChangeAsNotPersistent();
setAttributes( { ... } );
```

2. `__unstableMarkPersistent`

I propose a refined API to wrap the underlying actions inside the callback so that it's easier to reason about.

```js
__unstableMarkPersistent( () => {
  setAttributes( { ... } );
} );
```

The implementation could roughly look like:

```js
function __unstableMarkPersistent( callback ) {
  __unstableMarkNextChangeAsNotPersistent();
  callback();
}
```

So that we can reuse the old API but with a nicer-looking signature. Note that the implementation still only supports one action at a time, but I think it's possible to refactor it so that it can mark all synchronous actions in the callback as persistent (while disallowing asynchronous callback with a linter plugin or runtime warning). A bonus benefit is that the `__unstableMarkNotPersistent` API will look exactly the same with just some tweaking in the underlying implementation.

3. Refactor away from `useEffect`

The more _correct_ way to fix this, IMHO, is to get rid of the misused `useEffect` and calculate the `linkTo` attribute inline.

```js
const linkTo = attributes.linkTo || window?.wp?.media?.view?.settings?.defaultProps?.link || LINK_DESTINATION_NONE;
```

This requires a larger refactor though and could potentially introduce breaking changes if not treated carefully. But I think it's the right way and can prepare us for a more resilient codebase.

## How can we prevent this?

Since this is a hard problem and none of the solutions so far is trivial to fix by third-party authors, I've been thinking of a general solution to this problem so that we can prevent it from happening from the beginning. There are a few options I think we can try.

1. Lint plugin to warn when updating blocks inside `useEffect`

As mentioned above, updating attributes should be performed by user interactions. There's little to no reason that we want to set them on change of some props or states. We would want to also provide a link to the alternatives so that they can follow.

2. Runtime warning

Since pushing to the undo stack should always come from user interactions, maybe we can listen to user events to automatically mark the updating methods as persistent or not. I've tried listening to events that can be triggered by users, similar to how [trusted events](https://developer.mozilla.org/zh-TW/docs/Web/API/Event/isTrusted) work.

We can listen to all the possible [events](https://www.w3.org/TR/2022/WD-event-timing-20220524/#sec-events-exposed) globally and set a variable like `isFromUserGesture` to true. Then we just have to make sure the updating is called within the same synchronous cycle.

```js
// Pseudo code below.
let isFromUserGesture = false;

window.addEventListener( 'click', () => {
  isFromUserGesture = true;
}, true ); // Capturing phase runs first.

// Or an arbitrary timeout.
setImmediate( () => {
  isFromUserGesture = false
} );
```

But that quickly faces a problem when deleting a block. For some reason, deleting a block is [asynchronous](https://github.com/WordPress/gutenberg/blob/2ee09f0edb38588ee77cae1914b527221d5922f9/packages/block-editor/src/store/actions.js#L1144-L1171). Probably because the action is a [thunk](https://github.com/WordPress/gutenberg/pull/27276) and the implementation of thunk depends on asynchronous calling? @adamziel might know better 😅.

Deleting blocks isn't the only action though, I believe there are tons of existing actions that don't follow this rule, so we'll have to go through them one by one.

---

This issue is fairly complicated and I don't think I fully understand it even after days of studying. That's why this is more like a brain dump than a deep dive 😅.

There's no easy solution either, I'd be happy to know if there are better solutions. For now, I believe the best solution is to follow the [best practices](https://beta.reactjs.org/learn/you-might-not-need-an-effect) of `useEffect` and try to rethink our approaches.

**Comment by mcsf** [comment]
I appreciate the detailed account, @kevin940726. As I see it, we could:

* Try adding a linting rule for `setAttributes` calls inside `useEffect` if not preceded by `__unstableMarkNextChangeAsNotPersistent`.
* Stabilise `markNextChangeAsNotPersistent `. I have a slight preference for keeping the current approach instead of what you proposed with a callback, because IMO it lowers the "magic" factor and makes it clearer that there is nothing special about `markNextChangeAsNotPersistent`.

As asked by @annezazu, I don't know what else we can do with this issue. The time may be coming when we finally close it. Thoughts? :)

**Comment by youknowriad** [comment]
> As asked by @annezazu, I don't know what else we can do with this issue. The time may be coming when we finally close it. Thoughts?

I think so :)
