### ISSUE TITLE
Block audit: Cover image

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8199]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

**Name:** Cover Image
**Icon:** 
<img width="108" alt="screen shot 2018-07-25 at 9 37 37 am" src="https://user-images.githubusercontent.com/1202812/43204253-628735e6-8fee-11e8-87a4-9ebac16b39cf.png">
**Description:** Add a full-width image, and layer text over it — great for headers.
**Category:** Common blocks
**CSS class:** `wp-block-cover-image`, also adds `has-background-dim` if the "Background Opacity" slider is set to anything other than `0`. 
**Can be converted to:** Heading

# Empty/placeholder state

The placeholder state is identical to the Image Block placeholder state, except for the icon and block name. 

<img width="642" alt="screen shot 2018-07-25 at 9 35 29 am" src="https://user-images.githubusercontent.com/1202812/43204120-180cfbae-8fee-11e8-98f1-d559dcc07684.png">

# Selected State

After adding an image, you're prompted to "Write title...". 

<img width="640" alt="screen shot 2018-07-25 at 9 36 53 am" src="https://user-images.githubusercontent.com/1202812/43204207-4a64d82e-8fee-11e8-9e12-d095d88db3a0.png">

When you do add text, inline text style controls appear:

<img width="641" alt="screen shot 2018-07-25 at 9 39 56 am" src="https://user-images.githubusercontent.com/1202812/43204410-b707beec-8fee-11e8-8811-afbd368c442a.png">

# Primary (toolbar) settings

Alignment, text alignment, edit image

# Secondary (sidebar) settings

Cover Image Settings: Fixed Background, Background Opacity

# Frontend appearance

**Gutenberg starter theme:**

<img width="636" alt="screen shot 2018-07-25 at 9 46 57 am" src="https://user-images.githubusercontent.com/1202812/43204794-d34c8c08-8fef-11e8-87dc-cc3b814bbe43.png">

**Atomic Blocks**

<img width="749" alt="screen shot 2018-07-25 at 9 47 14 am" src="https://user-images.githubusercontent.com/1202812/43204819-e55d2312-8fef-11e8-9d2f-cc8d126da837.png">

**twentyseventeen:**

<img width="659" alt="screen shot 2018-07-25 at 9 48 59 am" src="https://user-images.githubusercontent.com/1202812/43204855-026a798c-8ff0-11e8-9d83-abd31ca803b4.png">

**twentyten:**

<img width="646" alt="screen shot 2018-07-25 at 9 50 18 am" src="https://user-images.githubusercontent.com/1202812/43204912-29fe9abe-8ff0-11e8-987f-885ec25550aa.png">

# Documentation

No devdocs in https://github.com/WordPress/gutenberg/tree/master/core-blocks/cover-image

Suggestion for user-facing docs: The Cover Image block consists of a large image, with text layered on top of it. 

# Performance on mobile

![cover-image-mobile](https://user-images.githubusercontent.com/1202812/43205553-a365208e-8ff1-11e8-852d-26b2d53d0766.gif)

- Basic functionality works.
- Adjusting the Background Opacity slider is difficult when you can't see the result in real time. 
- When alignment is changed to left/right, it's impossible to access the block toolbar (see Bug 4 below)

# Accessibility

# Bugs/errors

_Note: I'm holding off on opening bugs for some of these until there's a definite conclusion on https://github.com/WordPress/gutenberg/pull/5452_

1. The text styles here are unique to the Cover Image block. The text size is `2em`, and is close to our H2s (Currently `1.95em`). But our `H2`s are bold, and this text is not. This text should match the text size of our `h2`s. I'd also suggest we make it bold by default, as that'll naturally have better readability against a potentially busy background. 

2. [ ] If you consider the "Image" to be the background, the "Background Opacity" slider values are the opposite of what you'd expect: when they're set to 0, the image is at full opacity, and when they're set to 100%, the image is invisible. We're clearly considering the color to be the background right now, but that seems backwards. (#8600)

3. [ ] It's currently impossible make the cover iamge text appear bold inside of Gutenberg. Even if you select the bold toggle, [there's a CSS rule](https://github.com/WordPress/gutenberg/blob/5f5ae541d30d4670da0e3118e5e71517fe0692d0/core-blocks/cover-image/editor.scss#L16) that overrides it. (#8202)

4. [ ] Selecting left/right alignment on mobile completely hides the Block toolbar. This makes it impossible to change the alignment back to any other setting, to change the text alignment, or to change the image. (#8203)

5. [ ] This suffers from the left/right alignment issues raised in #8293. 

6. [ ] Block toolbar overlaps with inline toolbar when there is a lot of text. (#9974)

# Suggestions

_Note: I'm holding off on opening bugs for some of these until there's a definite conclusion on https://github.com/WordPress/gutenberg/pull/5452_

- For consistency, text should be rendered as a heading. We could potentially allow people to select a header size. 

- Consider allowing users to provide a caption below the image.

- [ ] Allow users to transform this into an image block. (#6475)

- [ ] Allow users to select the color of the background: black won't work with all themes. (#9329)

- Description could be clearer: The use of the term "full-width image" is a little confusing considering "full width" is the name of one of the alignment options. Also, we say this is "Great for headers", but the text in a Cover Image gets rendered in a `p` tag.

**Comment by SuperGeniusZeb** [comment]
This block was supposed to switch to using nested blocks. See #5452. I do not know what the status of that PR is, though. Is it still planned for inclusion in 5.0?

**Comment by SuperGeniusZeb** [comment]
Actually, come to think of it... is there even a need for the Cover Image block if the Container block was added? The theoretical Container block would have background image and color options, the ability to nest just about anything, and could have a parallax background if desired. The Cover Image concept could just become a pre-made template of a Container containing a Heading block. See #4900.

**Comment by mtias** [comment]
A few things I want to add to this block:

- Ability to change the color of the overlay.
- Ability to set a video instead of an image as background (video can be from media library or an embed like YouTube).
- Once that support is in, likely rename to "Cover".

**Comment by bph** [comment]
Discovered toolbar overlaps when text is spread out to the top of the image. 
Screenshot: 
![screen shot 2018-09-16 at 12 50 25 pm](https://user-images.githubusercontent.com/39980/45598777-35edea80-b9af-11e8-8f8c-b31ff582f919.png)

Here is a short video on the various scenarios when that happens, also on left and right alignment of the text... 
http://recordit.co/mXAe1TpA38

**Comment by kjellr** [comment]
Thanks @bph — I've opened an issue here so we can track that, and added it to the list above.

**Comment by webmandesign** [comment]
Hi, for reference, here is my addition to Cover Image audit. #10558

**Comment by marybaum** [comment]
And in Genesis only renders text at the size of the p tag -- no way to change. Workaround is to add the image, edit as html to render h2 heading, convert to html block because cover block has a heart attack at discovering I snuck an h2 in there ... ;-P

**Comment by mtias** [comment]
> because cover block has a heart attack at discovering I snuck an h2 in there

:)

@marybaum it won't make it in 5.0, but there is a plan to allow any block inside "Cover". That means you'll get the controls for paragraph (color and font sizes) as well as the ability to add any heading.

**Comment by marybaum** [comment]
Excellent!

**Comment by strarsis** [comment]
@mtias: Yes! I really need this right now (I am currently using an atomic block container as workaround).
An "infobox" with title, paragraphs and a button should be added over the cover image.

**Comment by KaiBuskirk** [comment]
is this block available?
or has it been shelved?
is there a download 
?
test, test, test, fix...

**Comment by ZebulanStanphill** [comment]
@KaiBuskirk The Cover Image block is now the Cover block. It was renamed because it now supports background videos in addition to images.

**Comment by strarsis** [comment]
IMHO the cover block should offer a general way to superimpose elements (z-index), 
like text block on image block or text block on video block or 
a block of formatted textblock on top of a tinted image block.

**Comment by marybaum** [comment]
Absolutely!

**Comment by karmatosed** [comment]
Most of the suggestions in the original audit are now made into issues or added to block. Let's close this and consider splitting out any other issues that need to be into separate logs.
