### ISSUE TITLE
Block audit: Heading

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8230]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="53" alt="screenshot 2018-07-26 17 41 33" src="https://user-images.githubusercontent.com/376315/43276046-683c3fb4-90fb-11e8-9592-4486305f2fc4.png">

**Name:** Heading
**Description:** Insert a headline above your post or page content.
**Category:** Common blocks
**CSS class:** None on frontend, `wp-block-heading` in editor
**Can be converted to:** Quote, cover image, paragraph

# States

*Empty:*
<img width="666" alt="screenshot 2018-07-26 17 41 57" src="https://user-images.githubusercontent.com/376315/43275999-4c27a1ba-90fb-11e8-9f06-42577457a54f.png">
Blinking prompt

*Selected:*
<img width="672" alt="screenshot 2018-07-26 17 42 13" src="https://user-images.githubusercontent.com/376315/43276011-537768c4-90fb-11e8-9805-34ed5a50ea2a.png">

*Unselected:*
<img width="589" alt="screenshot 2018-07-26 17 42 21" src="https://user-images.githubusercontent.com/376315/43276021-598a3ee4-90fb-11e8-923a-cceb5ee55c75.png">

*Placeholder:*
<img width="602" alt="screenshot 2018-07-26 17 41 43" src="https://user-images.githubusercontent.com/376315/43276026-5eb7b978-90fb-11e8-8470-cdda46e89123.png">

If you click through without adding any text, you'll see greyed-out text that says "Write heading...":

# Primary (toolbar) settings

H2, H3, H4, bold, italic, strikethrough, link

# Secondary (sidebar) settings

Heading settings: H1, H2, H3, H4, H5, H6
Text alignment: left, centre, right
Advanced: Additional CSS Class, HTML Anchor

# Frontend appearance

**Gutenberg starter theme:**

<img width="653" alt="screen shot 2018-07-31 at 1 57 18 pm" src="https://user-images.githubusercontent.com/1202812/43479356-3a2c16ae-94ce-11e8-9b73-f29dbf642780.png">

**Atomic Blocks**

<img width="798" alt="screen shot 2018-07-31 at 1 52 43 pm" src="https://user-images.githubusercontent.com/1202812/43477463-3ed0f79c-94c9-11e8-9fe8-c8162fa3e3f8.png">

**twentyseventeen:**

<img width="605" alt="screen shot 2018-07-31 at 2 28 39 pm" src="https://user-images.githubusercontent.com/1202812/43479370-43f8de2e-94ce-11e8-95d3-b27ac19235e5.png">

**twentyten:**

<img width="971" alt="screen shot 2018-07-31 at 2 26 59 pm" src="https://user-images.githubusercontent.com/1202812/43479377-48bb3ec0-94ce-11e8-8005-88804e17acff.png">

# Documentation

No devdocs in https://github.com/WordPress/gutenberg/tree/master/core-blocks/heading

Suggestion for user-facing docs:

# Performance on mobile

# Accessibility

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Bolding part of the heading has no effect on its appearance. (#11107)
- [ ] Typing a hard return (Enter) in the middle of a heading, then using command-z to undo deletes everything that appeared after the line break. (#11108)
- [ ] 3. Stray <br> tags sometimes appear within a heading. (#5872)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] In the paragraph block, alignments are in the primary toolbar. Here, they're in the secondary toolbar. They should be consistent (I'd go with the primary toolbar.) (#3785)
- [x] This should probably be convertible to a subheading block, or (better), combined into a single heading block. (Related: #8140)
- [ ] Consider adding colour settings to more closely align with paragraph—I'd skip on the size though, since it sort of defeats the purpose. (#8171)
- [ ] Use /h1, /h2, /h3, etc in the slash inserter commands. (#7438)

**Comment by SuperGeniusZeb** [comment]
>In the paragraph block, alignments are in the primary toolbar. Here, they're in the secondary toolbar. They should be consistent (I'd go with the primary toolbar.)

I think the term everybody uses is "inspector" or "block inspector", rather than secondary toolbar.

Subheadings should remain separate from the Heading block, in my opinion. Just to be clear, a Subheading is something that should **not** use the `<h1>` to `<h6>` tags. They are commonly used as leads or little statements below the title of the article, though I think I have seen them used the headings of each section of an article, albeit rarely.

https://minecraft.net is the first example that comes to my mind as an example of posts using subheadings. Hover over the blog posts in the masonry layout and a subheading will appear below the title. The subheading is also shown below the title when you go to a blog post.

The HTML 5.2 specification shows some other uses of the Subheading block, including cases where you would have **multiple subheadings following a single heading**.

https://www.w3.org/TR/html52/common-idioms-without-dedicated-elements.html#common-idioms-without-dedicated-elements

Notably, I think the Subheading block, in the context of using it for short blurbs of text below the title (like on news sites), may not even belong in `post_content`, and should be placed in the same area as the title heading. Of course, Gutenberg can not yet edit that area (though it will be able to in the future).

That said, the Subheading block is still useful for situations where you have a subheading below each section heading in your post or page.

You might wonder why you could not just use a Paragraph block to accomplish the same thing. Well, you could. But the Subheading block is slightly more semantic, meaning that:
- Themes could provide special styles to the Subheading block, including multiple styles you could switch between, without exposing them to normal Paragraph block styles and vice-versa.
- If a proper `<subheading>` element was ever added, existing Subheading blocks could be retroactively updated to use the new element, providing increased semantics to existing websites.
- When Gutenberg gets the ability to edit stuff outside of `post_content`, there will already be a Subheading block that can be used there and would presumably already have a bit more theme/plugin support than it would if it were added later.

**Comment by kjellr** [comment]
> In the paragraph block, alignments are in the primary toolbar. Here, they're in the secondary toolbar. They should be consistent (I'd go with the primary toolbar.)

Related: https://github.com/WordPress/gutenberg/issues/3785

**Comment by sarahmonster** [comment]
All issues here have been filed as individual issues, so I'm going to go ahead and close out this tracking bug. Feel free to comment on if I missed anything, or open new issues as needed! 💪
