### ISSUE TITLE
Block audit: Subheading

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8234]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="54" alt="screenshot 2018-07-26 18 24 20" src="https://user-images.githubusercontent.com/376315/43277832-2c2e687a-9101-11e8-9ce8-fcdce1ef337e.png">

**Name:** Subheading
**Description:** What’s a subhead? Smaller than a headline, bigger than basic text.
**Category:** Common blocks
**CSS class:** `wp-block-subhead` in frontend, `wp-block-subhead` in editor
**Can be converted to:** Paragraph

# States

*Empty:*
<img width="665" alt="screenshot 2018-07-26 17 54 17" src="https://user-images.githubusercontent.com/376315/43277897-605ed6ca-9101-11e8-8a86-dc2e846068f5.png">

*Selected:*
<img width="665" alt="screenshot 2018-07-26 17 55 01" src="https://user-images.githubusercontent.com/376315/43277908-676329d0-9101-11e8-90d9-7fad92ef7c39.png">

*Unselected:*
<img width="585" alt="screenshot 2018-07-26 17 55 12" src="https://user-images.githubusercontent.com/376315/43277921-6e2276fe-9101-11e8-9c94-cab89513d569.png">

*Placeholder:*
<img width="627" alt="screenshot 2018-07-26 17 54 42" src="https://user-images.githubusercontent.com/376315/43277931-751d4240-9101-11e8-82f8-2d3e88d6cda6.png">

# Primary (toolbar) settings

Align left | right | centre, bold, italic, strikethrough, link

# Secondary (sidebar) settings

Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

<img width="674" alt="screen shot 2018-07-31 at 1 57 43 pm" src="https://user-images.githubusercontent.com/1202812/43477719-eb0aebbc-94c9-11e8-8189-a442847f9175.png">

**Atomic Blocks**

<img width="790" alt="screen shot 2018-07-31 at 1 53 07 pm" src="https://user-images.githubusercontent.com/1202812/43477538-73c263e6-94c9-11e8-99a1-704f12fa4e7b.png">

**twentyseventeen:**

<img width="617" alt="screen shot 2018-07-31 at 2 29 01 pm" src="https://user-images.githubusercontent.com/1202812/43479718-0e5d0208-94cf-11e8-9ac6-1cab8b1c7d43.png">

**twentyten:**

<img width="735" alt="screen shot 2018-07-31 at 2 27 38 pm" src="https://user-images.githubusercontent.com/1202812/43479721-1200da2e-94cf-11e8-89f8-fee26a2b5bcc.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Typing a hard return (Enter) in the middle of a heading creates two headings, which is inconsistent with how a heading works.

- [ ] Italicising text has no effect. This should un-italicise, or perhaps the italics should be turned on my default.

- [ ] Text lacks sufficient contrast. (#8716)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] Kill it with 🔥. As a new user, I don't have any sense of why there are two different blocks for what are, in many respects, basically the same thing. My understanding, having read various issues, is that the subheading is visually heading-like, but semantically not-heading like, which can be useful for SEO stuff and also for newsrooms or anyone generating a table of Contents from h1-6 headings. That's a good advanced feature if you understand what's behind it, but as a new/inexperienced user, it's totally confusing. A better approach might be to provide this as an advanced setting on the heading block. (Related: #8140)

- [ ] Should be convertible to (at very least) a heading. 

- [ ] Alignment settings should be consistent with the heading block. (See #8230)

- [ ] Consider adding colour settings to more closely align with paragraph—I'd skip on the size though, since it sort of defeats the purpose. (#8171)

- [ ] Allow for as many subheads per page as people want. (See also https://github.com/TomodomoCo/tomodomo-gutenberg-infinite-subheads)

- [ ] The placeholder text looks almost exactly the same as the non-placeholder styling, making it confusing.

- [ ] The icon is the exact same as the one used for preformatted text—and it looks like a paragraph, rather than a heading.

**Comment by chrisvanpatten** [comment]
Just for some extra context, a subhead is in _no way_ a heading. The name is very misleading, but newsrooms have used the term for decades (and will continue to use it) so we're stuck with it :)

(It's also called a "dek" or "deck", "standfirst" in the UK, "kicker", and occasionally "subhed" sans-A.)

I don't know that I'm totally on board with ditching it, although admittedly I'm biased because my clients are editorial teams, newsrooms, and publishers. That said, if it _were_ removed, I'd add it back as a block style option on the Paragraph block, which honestly might be more intuitive anyway.

**Comment by SuperGeniusZeb** [comment]
Copy-pasting what I posted in #8230 (which probably should have been posted here in the first place :stuck_out_tongue:):

Subheadings should remain separate from the Heading block, in my opinion. Just to be clear, a Subheading is something that should **not** use the `<h1>` to `<h6>` tags. They are commonly used as leads or little statements below the title of the article, though I think I have seen them used the headings of each section of an article, albeit rarely.

https://minecraft.net is the first example that comes to my mind as an example of posts using subheadings. Hover over the blog posts in the masonry layout and a subheading will appear below the title. The subheading is also shown below the title when you go to a blog post.

The HTML 5.2 specification shows some other uses of the Subheading block, including cases where you would have **multiple subheadings following a single heading**.

https://www.w3.org/TR/html52/common-idioms-without-dedicated-elements.html#common-idioms-without-dedicated-elements

Notably, I think the Subheading block, in the context of using it for short blurbs of text below the title (like on news sites), may not even belong in `post_content`, and should be placed in the same area as the title heading. Of course, Gutenberg can not yet edit that area (though it will be able to in the future).

That said, the Subheading block is still useful for situations where you have a subheading below each section heading in your post or page.

You might wonder why you could not just use a Paragraph block to accomplish the same thing. Well, you could. But the Subheading block is slightly more semantic, meaning that:
- Themes could provide special styles to the Subheading block, including multiple styles you could switch between, without exposing them to normal Paragraph block styles and vice-versa.
- If a `<subheading>` element was ever added to HTML, existing Subheading blocks could be retroactively updated to use the new element, providing increased semantics to existing websites.
- When Gutenberg gets the ability to edit stuff outside of `post_content`, there will already be a Subheading block that can be used there and would presumably already have a bit more theme/plugin support than it would if it were added later.

**Comment by sarahmonster** [comment]
Thanks for the extra context here! It sounds like there are two potential use cases here:

1. A journalistic subhead
2. A subtitle for the post itself (referred to in the HTML spec linked above)

I'm not entirely sure which this one is intending to act as, which may be part of the problem. The fact that it's limited to a single instance leads me to think it may be intended as a subtitle, but that doesn't seem to track with its description. ("What’s a subhead? Smaller than a headline, bigger than basic text.")

If it's intended to act as a *subtitle* for the post itself, I'm not certain that really belongs inside post content at all, especially if people want to use it on archive pages and the like (which is a pretty common use case). With the current implementation of WordPress, people tend to accomplish this by either using the post excerpt, or by installing one of the many subtitle plugins. If you wanted to accomplish the Minecraft example using Gutenberg, for instance, you couldn't.

For the **subhead**, I still feel it might be better if the block were incorporated into either the heading or the paragraph blocks. From the description [here](https://en.wikipedia.org/wiki/News_style#Subhead), 

> A subhead (also sub-headline, subheading, subtitle or deck; subhed or dek in journalism jargon) can be either a subordinate title under the main headline, or the heading of a subsection of the article.[8][full citation needed] It is a heading that precedes the main text, or a group of paragraphs of the main text. It helps encapsulate the entire piece, or informs the reader of the topic of part of it. Long or complex articles often have more than one subhead. Subheads are thus one type of entry point that help readers make choices, such as where to begin (or continue) reading. 

So again, we have two potential meanings here: the subtitle, and the subheading. From this, though, it rather sounds like this is less of a "heading" and more of a full paragraph, stylistically, and that usage between different publications could very substantially. @chrisvanpatten I'd love if you could share some examples of subheads in use—I think this might really help clarify how newsrooms are using this feature so that we can sort out a balance between providing utility for power-users, and not confusing beginners.

If we wanted to retain this as a standalone block, I'd recommend at least the following:
1. Rename it to "subhead" so it's a bit more distinct from "heading", especially since "subhead" seems to be more standard than "subheading". 
2. Move it out of common blocks. A section (or add-on plugin pack) for "blocks for journalism and newsrooms" could be more appropriate, and would reduce the chance of user confusion ("Do I use a heading, or a subheading?") here.
3. Make it repeatable—the limitation doesn't seem to respect the full range of use cases here.
4. Improve the description so it's clear what it's intended to be used for.

**Comment by chrisvanpatten** [comment]
A few quick examples:

Guardian:

![brexit__uk_warns_eu_of_tit-for-tat_measures_over_financial_services___politics___the_guardian](https://user-images.githubusercontent.com/1231306/43398782-098d9cae-93d7-11e8-849c-2098fc7cd3a5.png)

NiemanLab:

![known_but_not_discussed __low-income_people_aren t_getting_quality_news_and_information__what_can_the_industry_do_about_it__ _nieman_journalism_lab](https://user-images.githubusercontent.com/1231306/43423871-889904c2-941b-11e8-9fad-8998ead68a82.png)

Pew Research:

![growing_partisan_differences_in_views_of_the_fbi__stark_divide_over_ice___pew_research_center](https://user-images.githubusercontent.com/1231306/43423901-a567b6b6-941b-11e8-9c69-1366caba6083.png)

All are rendered via `<p>` tags, fwiw.

**Comment by sarahmonster** [comment]
Interesting—so it looks like here, the *subtitle* use case is actually the most prevalent—and it looks as though some of them *could* be part of the post body, but others (Nieman Lab) aren't. 

Looking at the semantic structure of the other two sources, it looks as though the subhead/_whatever-it-is-anyway_ isn't part of the post body in any of the cases... it's typically a top-level element that's separate from the post body entirely (or at the same level as the post body, the title, the meta), like here:

<img width="1135" alt="screenshot 2018-07-31 09 17 40" src="https://user-images.githubusercontent.com/376315/43447194-d9fa87d2-94a2-11e8-99fa-c7db1daa5229.png">

Both Pew Research and Neiman Lab also uses the subheads on archive pages, which wouldn't be possible with the current implementation of subheads in Gutenberg, unless I'm mistaken. (But would be possible with a subhead plugin or the post excerpt.)

Interestingly, all these options do use a `<p>` tag, only Neiman Lab actually uses a proper "paragraph" if we define "paragraph" as "at least a sentence with a full stop".

It seems like, given these use cases, the subhead really makes more sense as part of the post meta, rather than part of the post content itself—unless this block is intended as more of a layout block to be used in the future.

**Comment by wsydney76** [comment]
> It seems like, given these use cases, the subhead really makes more sense as part of the post meta, rather than part of the post content itself

Definitely.

See also #4472 .

You may also want to see this  in things like recent post widget or next/previous post navigation.

**Comment by kjellr** [comment]
> Looking at the semantic structure of the other two sources, it looks as though the subhead/whatever-it-is-anyway isn't part of the post body in any of the cases... it's typically a top-level element that's separate from the post body entirely (or at the same level as the post body, the title, the meta)

Yep, that's how we do it over at Longreads too. Our dek/subhead is entered as the "Custom Excerpt" for the post. That way, it's part of the post meta (rather than in the content), and can be reused as the post excerpt in social media descriptions, post archives, and other feeds.

<img width="1260" alt="screen shot 2018-07-31 at 2 04 59 pm" src="https://user-images.githubusercontent.com/1202812/43478103-fb9c510e-94ca-11e8-9746-6ca4eba16f79.png">

**Comment by chrisvanpatten** [comment]
@kjellr We do the same thing; I expect that’s a common pattern.

Would be awesome if subheads and excerpts were somehow bridged together but I expect that’s a Phase 2 change.

**Comment by gandalfar** [comment]
It would be also great to have an option for this block as required and present by default field. Right now we use ACF to position it under Title so authors don't miss it.

**Comment by swissspidy** [comment]
Related: https://github.com/benhuson/wp-subtitle/, specifically https://github.com/benhuson/wp-subtitle/tree/gutenberg/develop

**Comment by gandalfar** [comment]
At Val 202 (Slovenian National Radio Broadcaster), we'll have an article such as:
https://val202.rtvslo.si/2018/07/diskgolf/

![screenshot 2018-08-03 12 55 20](https://user-images.githubusercontent.com/13806/43639507-bcb187e4-971c-11e8-96ba-c7c7f45f06fc.png)

In backend, this would look like:

![screenshot 2018-08-03 12 54 48](https://user-images.githubusercontent.com/13806/43639384-70b715fc-971c-11e8-8a8c-b1ed7a6ed3a9.png)

The second line (`Podnaslov prispevka` is 'Article subhead` and an instruction that it should be max 200 characters). The input field is limited to 200 characters and it won't allow any more text after that. This is editorial decision that partially comes from the idea that it to forces journalists to not just paste first paragraph of text in there, but to think about what should go in there.

Because we have many external contributors that might login into Wordpress maybe once a month or even less, having a field visually be present automatically, at the correct reading flow, makes it a good visual cue to not forget to fill it in.

**Comment by sarahmonster** [comment]
Thanks for the additional context!

It looks like you're using a custom field here, rather than the subheading block that ships with Gutenberg, but it's definitely helpful to get a sense of the patterns in use here. Cheers!

**Comment by Retrofitterdk** [comment]
After working quite a lot of years in journalistic newsrooms, I would conclude that the subheading block – in it’s current implemention – is pretty useless in a newsroom setting.

As already said here #6072, here #6409 and [here](https://github.com/WordPress/gutenberg/pull/2091#issuecomment-319629134) a subheading block is not useful in newsrooms unless it can be queried separately in order to use in archive views/frontpages.

**Comment by youknowriad** [comment]
Subheading block is deprecated.

**Comment by strarsis** [comment]
@youknowriad: With what block has it been replaced?
I got many titles, each with a small descriptive text below.
Using title + paragraph as separate blocks would decouple it too much.
Should the theme/site plugin add its own title + subtitle/-heading block?

**Comment by slowaways** [comment]
How to add a required subhead in my Gutenberg editor? For Custom Post Type?

**Comment by swissspidy** [comment]
@slowaways Please don't comment on old closed issues, instead raise your question on the core-editor Slack channel or in a new issue here on GitHub.
