### ISSUE TITLE
Block audit: Quote

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8236]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="52" alt="screenshot 2018-07-26 18 49 34" src="https://user-images.githubusercontent.com/376315/43279362-a37b03b2-9105-11e8-89f9-59a0a067fc59.png">

**Name:** Quote
**Description:** Maybe someone else said it better -- add some quoted text.
**Category:** Common blocks
**CSS class:** `wp-block-quote` in frontend, `wp-block-quote` in editor, `is-style-large` for large style
**Can be converted to:** list, paragraph, heading

# States

*Empty:*
<img width="666" alt="screenshot 2018-07-26 18 54 14" src="https://user-images.githubusercontent.com/376315/43279386-b50712e2-9105-11e8-96a8-c302caed8783.png">

*Selected:*
<img width="675" alt="screenshot 2018-07-26 18 52 25" src="https://user-images.githubusercontent.com/376315/43279403-c07f8c1c-9105-11e8-8cb5-561abc08866f.png">
<img width="672" alt="screenshot 2018-07-26 18 53 05" src="https://user-images.githubusercontent.com/376315/43279425-d5b3a14a-9105-11e8-9796-ed6840878804.png">

*Unselected:*
<img width="604" alt="screenshot 2018-07-26 18 52 34" src="https://user-images.githubusercontent.com/376315/43279407-c93e8e2a-9105-11e8-98dd-4b9d0e95cd37.png">
<img width="610" alt="screenshot 2018-07-26 18 53 26" src="https://user-images.githubusercontent.com/376315/43279412-cdcd2dde-9105-11e8-9ffa-baa4a30a1598.png">

*Placeholder:*
<img width="616" alt="screenshot 2018-07-26 18 49 52" src="https://user-images.githubusercontent.com/376315/43279446-df0dfa6a-9105-11e8-9a17-1fc4388d07d9.png">

# Primary (toolbar) settings

Align left | right | centre, bold, italic, strikethrough, link

# Secondary (sidebar) settings

Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

<img width="1438" alt="screen shot 2018-07-31 at 1 57 33 pm" src="https://user-images.githubusercontent.com/1202812/43478458-edb94276-94cb-11e8-9b28-97e68660496d.png">

**Atomic Blocks**

<img width="827" alt="screen shot 2018-07-31 at 1 52 59 pm" src="https://user-images.githubusercontent.com/1202812/43477515-63594560-94c9-11e8-82bb-8f9c6761816c.png">

**twentyseventeen:**

<img width="555" alt="screen shot 2018-07-31 at 2 28 52 pm" src="https://user-images.githubusercontent.com/1202812/43479654-e0e92c98-94ce-11e8-88ec-16b98165db31.png">

**twentyten:**

<img width="735" alt="screen shot 2018-07-31 at 2 27 30 pm" src="https://user-images.githubusercontent.com/1202812/43479662-e4752a7e-94ce-11e8-893c-947a2d1006c0.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [x] Citation alignment should change with quote alignment changes in large block style.
 
- [x] Italicisation works in the frontend, but doesn't have any visual indicator in the editor.

- [x] Can't delete empty line from start of quote.

- [ ] Citation placeholder lacks sufficient contrast. (#8738)

# Suggestions

_Individual issues will be opened for these soon_

- [x] Converting to a list seems an odd choice. It feels like there may be some more appropriate choices here. (Verse? Preformatted?)

- [x] I was *extremely* surprised to see the "block styles" option in the transforming menu, especially when it then added settings (CSS class) over in the block settings menu. I would expect to see these instead in the block settings menu. Is this a third place for block settings? Do other blocks put settings here?

- [ ] Consider adding colour and/or size options. (#8171)

- [ ] Should a right-aligned quote have the border on the right hand side, rather than the left? Visually, I'd remove it entirely for centre-aligned, and move it to the right for right-aligned. (#11609)

- [ ] It looks like we have two different quotes available: this and a pullquote. I'm guessing that the difference is that a quote is for an external source, whereas a pullquote is a quote pulled from your post. I expect there's been some discussion on this one, so I'll save discussion for the pullquote audit, but I think there's some potential for confusion here, especially where pullquotes allow for a citation, too, *and* quotes have multiple styles. (#11610)

**Comment by SuperGeniusZeb** [comment]
>I was extremely surprised to see the "block styles" option in the transforming menu, especially when it then added settings (CSS class) over in the block settings menu. I would expect to see these instead in the block settings menu. Is this a third place for block settings? Do other blocks put settings here?

This is a standard API introduced recently. Themes/plugins can register custom styles for blocks, making it easy for users to choose a pre-made style for a block. The styles use classes, making them easy to update later on. It was placed in the formatting toolbar because it is close in function/concept to block transformations.

The Quote block was supposed to be converted to use nested blocks. See #6520. This covers the size issues, I think. I am not sure if the text color options would still be wanted, and perhaps even the background color options is something that should not be included in core, in favor of theme-provided styles via the aforementioned Block Styles API.

Personally, I would not mind having text color options for every single text-related block, but I think core is supposed to only contain the most important controls. Most of the time, quotes on your website would all look the same, meaning that the styles should be provided by the theme. The only reason the Paragraph block has color settings is because offsetting a single paragraph with different colors was a common-enough use case to warrant the options being added. Also note that you can (or at least you should be able to) manually change the CSS styles of blocks using the <kbd><samp>Edit as HTML</samp></kbd> option.

**Comment by sarahmonster** [comment]
All issues here have been filed as individual issues, so I'm going to go ahead and close out this tracking bug. Feel free to comment on if I missed anything, or open new issues as needed! 💪
