### ISSUE TITLE
Block audit: List

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8237]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="51" alt="screenshot 2018-07-26 19 37 34" src="https://user-images.githubusercontent.com/376315/43281358-5dd0989e-910b-11e8-95f5-b3503998e9e3.png">

**Name:** List
**Description:** Numbers, bullets, up to you. Add a list of items.
**Category:** Common blocks
**CSS class:** none in frontend or editor
**Can be converted to:** paragraph, quote

# States

*Empty:*
<img width="658" alt="screenshot 2018-07-26 19 35 11" src="https://user-images.githubusercontent.com/376315/43281370-64639936-910b-11e8-9415-9ca7cef45865.png">

*Selected:*
<img width="672" alt="screenshot 2018-07-26 19 35 46" src="https://user-images.githubusercontent.com/376315/43281381-6c1b0cae-910b-11e8-9aaf-ff723b426b20.png">

*Unselected:*
<img width="613" alt="screenshot 2018-07-26 19 35 53" src="https://user-images.githubusercontent.com/376315/43281395-7366c782-910b-11e8-9afb-231cf408a9b0.png">

*Placeholder:*
<img width="617" alt="screenshot 2018-07-26 19 35 21" src="https://user-images.githubusercontent.com/376315/43281405-7ace1bc4-910b-11e8-9835-f107d4188c12.png">

# Primary (toolbar) settings

Bulleted, numbered, decrease indent, increase indent, bold, italic, strikethrough, link

# Secondary (sidebar) settings

Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

<img width="677" alt="screen shot 2018-07-31 at 1 57 39 pm" src="https://user-images.githubusercontent.com/1202812/43478440-e52547a4-94cb-11e8-938e-fd5a6520f2e7.png">

**Atomic Blocks**

<img width="813" alt="screen shot 2018-07-31 at 1 53 03 pm" src="https://user-images.githubusercontent.com/1202812/43477522-6b84eb18-94c9-11e8-920a-3a6e9d37dc64.png">

**twentyseventeen:**

<img width="582" alt="screen shot 2018-07-31 at 2 28 59 pm" src="https://user-images.githubusercontent.com/1202812/43479697-f8445700-94ce-11e8-9bd4-630c354fdacd.png">

**twentyten:**

<img width="539" alt="screen shot 2018-07-31 at 2 27 35 pm" src="https://user-images.githubusercontent.com/1202812/43479707-fefad2ae-94ce-11e8-8d1c-fd676ce9e635.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [x] Empty `<br>` tags appear at the end of list items. _(Cannot reproduce with WP 5.0.3 — @kjellr)_

- [x] Regardless of whether I'm using bulleted or numbered lists, the bulleted option is always selected in the primary toolbar. _(Cannot reproduce with WP 5.0.3 — @kjellr)_

- [x] Using sibling inserter before a list block doesn't seem to work properly. (May be a sibling inserter issue.)_(Cannot reproduce with WP 5.0.3 — @kjellr)_

- [x] Issues related to using tabs to control indentation. (#7051)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] Consider greying out the decrease/increase indent buttons when they won't do anything (for instance, when at the top level of indentation). (#13402)

- [x] It would be nice if copying an indented list copied over my list settings. 

- [ ] Consider adding colour and/or size options. (#8171)

- [x] Add a CSS class!

- [ ] Spacing between individual list items in the same list should be equal or less than spacing between a list item and a new indented sub-list. (#14100)

- [ ] Decrease indentation of nested lists so they align with beginning of text. (#14098)

- [ ] Align lists to paragraphs. (#14098)

- [x] Placeholder should use greyed-out bullets as well as text. (Since the bullet actually appears on the front-end when the user hasn't entered any text, this is probably the correct way of showing it, so I'm going to just moot this one. An alternate solution would be to hide the empty list item from the frontend display so it never appears, but I could see that being tricky and it's probably not super-critical to the UX.)

- [ ] When using a RTL language, the arrows inside the increase/decrease indent buttons do not indicate the actual direction the text will move when you press the button. (#8674)

**Comment by HippDesign** [comment]
I wrote an issue about another bug which happens when pasting multiline text into the list: [#9476](https://github.com/WordPress/gutenberg/issues/9476)

**Comment by sarahmonster** [comment]
All issues here have been filed as individual issues, so I'm going to go ahead and close out this tracking bug. Feel free to comment on if I missed anything, or open new issues as needed! 💪
