### ISSUE TITLE
Block audit: Image

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8291]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="44" alt="screenshot 2018-07-30 13 32 06" src="https://user-images.githubusercontent.com/376315/43398537-493320a8-9400-11e8-89ee-2653062c2bce.png">

**Name:** Image
**Description:** They’re worth 1,000 words! Insert a single image.
**Category:** Common blocks
**CSS class:** `wp-block-image` in editor and in frontend (on `figure` element)
**Can be converted to:** gallery, file

# States

*Empty:*
<img width="668" alt="screenshot 2018-07-30 13 54 06" src="https://user-images.githubusercontent.com/376315/43398552-51b07f96-9400-11e8-9a89-323bfeca0ec1.png">

*Selected:*

Before a caption:
<img width="670" alt="screenshot 2018-07-30 13 54 58" src="https://user-images.githubusercontent.com/376315/43398562-58238e18-9400-11e8-90a4-e0f6fc81d746.png">

With a caption:
<img width="664" alt="screenshot 2018-07-30 13 58 53" src="https://user-images.githubusercontent.com/376315/43398734-ccc1b7c2-9400-11e8-9aa7-c7bb25a69501.png">

*Unselected:*
<img width="576" alt="screenshot 2018-07-30 13 58 26" src="https://user-images.githubusercontent.com/376315/43398743-d4785df4-9400-11e8-90d5-e17cefde5042.png">

*Placeholder:*
<img width="614" alt="screenshot 2018-07-30 13 54 15" src="https://user-images.githubusercontent.com/376315/43398566-5eaec130-9400-11e8-807a-e2d799874756.png">

# Primary (toolbar) settings

Align: left, centre, right, edit
Over caption: bold, italic, strikethrough, link

# Secondary (sidebar) settings

Image Settings: Textual Alternative, Image Size, Image Dimensions
Link Settings: Link To, Link URL
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

**Atomic Blocks**

<img width="810" alt="screen shot 2018-07-31 at 1 52 50 pm" src="https://user-images.githubusercontent.com/1202812/43477482-4ddb09e4-94c9-11e8-9d1f-57dd4b1c8b7a.png">

**twentyseventeen:**

<img width="581" alt="screen shot 2018-07-31 at 2 28 44 pm" src="https://user-images.githubusercontent.com/1202812/43479407-5b4819f0-94ce-11e8-8e06-6dcff9eb3817.png">

**twentyten:**

<img width="734" alt="screen shot 2018-07-31 at 2 27 20 pm" src="https://user-images.githubusercontent.com/1202812/43479412-60305db0-94ce-11e8-8fc3-3f821fb25ce5.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Switching the alignment causes float issues. Sometimes the toolbar (or parts of the toolbar) disappear altogether. Sometimes it'll then appear to be stuck nested inside the previous block. (#8293)

- [x] Converting to a file block can give a title of `[object Object]`. (#7626)

- [x] Breaks out of the content area in some themes and may require frontend styling. (#8334)

- [ ] Secondary settings don't appear on smaller devices. (#8056)

- [x] Caption placeholder lacks sufficient contrast. (#5838)

# Suggestions

_Individual issues will be opened for these soon_

- [x] "Textual alternative" has got to go. (#8063) 

- [ ] It could also use better descriptive text, so people understand better what it's for. (#8391)

- [ ] Simplifying the various different options for image sizing would be 💯. (#8397)

- [x] Should be convertible to a cover image. (#6475)

- [ ] Empty state could be improved from a consistency standpoint. (#8409)

- [ ] Include ability to edit image title. (#11054)

**Comment by SuperGeniusZeb** [comment]
Just in general, floated blocks are the most confusing and broken-feeling things in Gutenberg. There is a lot of stuff that needs to be fixed here.

Regarding sizing options, see #7636 and #7638. Resizing should be easier for keyboard users than it is now. The drag handles are not usable by keyboard users.

>what's the difference between "image dimensions" and "image size"?

The Image Size is the source file, selected from one of the automatically-generated image files of various sizes that WordPress creates when you upload a file. It used to be called Source Type (or something like that). I think the current name of the option is somewhat confusing.

**Comment by postphotos** [comment]
Hi @sarahmonster! I would _strongly_ recommend a limited use of the word "caption" as it relates to media. I outlined why this is important in a Trac ticket [here](https://core.trac.wordpress.org/ticket/43178). It mostly has to do with consistency in how we approach all content with subtitles.

An alternate option that could work would be `Write a description...`. Let me know if this needs a new issue ticket!

**Comment by bph** [comment]
We noticed a few support tickets where people would like to set a title for the image they uploaded via the image block. The sidebar doesn't have all the fields, they see in the current editor. The work around is right now, to save the draft, get out of the editing process, go to the media library look for the newly uploaded image and fill in the title. But even if that is done, the front end doesn't display the image title. It's an SEO relevant attribute for an image, if ranking their image in search result pages is important to the site owner

**Comment by rosswintle** [comment]
+1 for @bph's title issue. Auto-generated media titles are derived from the file name, and no-one wants a media library full of things called "IMG0756" or "Screenshot 2018-09-04 10:20:30" because you can't then find anything in the media library.

I have to work really hard to get my clients to add titles so that when they search for images they can find media that they've added in the past easily.

I'd really like Gutenberg to put some emphasis on giving images titles as well as captions and alt-texts. The classic editor at least made this possible.

Please make editing the title possible, as a minimum, and emphasise it if you can.

Thanks

**Comment by sarahmonster** [comment]
@bph @rosswintle I've filed #11054 for the title issue. 

All issues here have been filed as individual issues, so I'm going to go ahead and close out this tracking bug. Feel free to comment on if I missed anything, or open new issues as needed! 💪
