### ISSUE TITLE
Block audit: File

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8295]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="54" alt="screenshot 2018-07-30 14 31 12" src="https://user-images.githubusercontent.com/376315/43401036-1890d146-9407-11e8-84dc-921c534ae2ad.png">

**Name:** File
**Description:** Add a link to a file that visitors can download. 
**Category:** Common blocks
**CSS class:** `wp-block-file` in frontend and editor
**Can be converted to:** contextual depending on file type: file, image, video, audio

# States

*Empty:*
<img width="667" alt="screenshot 2018-07-30 14 30 32" src="https://user-images.githubusercontent.com/376315/43401065-26bbb9b6-9407-11e8-9175-aec6377e4435.png">

*Selected:*
<img width="666" alt="screenshot 2018-07-30 14 30 59" src="https://user-images.githubusercontent.com/376315/43401085-3248bec8-9407-11e8-85b8-62b55a8d42ad.png">

*Unselected:*
<img width="635" alt="screenshot 2018-07-30 14 31 05" src="https://user-images.githubusercontent.com/376315/43401113-3c6d53dc-9407-11e8-9843-2248902b4d71.png">

*Placeholder:*
<img width="616" alt="screenshot 2018-07-30 14 30 41" src="https://user-images.githubusercontent.com/376315/43401128-42dbe2c4-9407-11e8-8996-4350040b9956.png">

# Primary (toolbar) settings

Align: left, centre, right, edit

# Secondary (sidebar) settings

Text Link Settings: Link To, Open in New Window
Download Button Settings: Show Download Button
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

<img width="662" alt="screen shot 2018-07-31 at 1 57 26 pm" src="https://user-images.githubusercontent.com/1202812/43479586-bb976e28-94ce-11e8-85ea-77bc0c2b81a0.png">

**Atomic Blocks**

<img width="777" alt="screen shot 2018-07-31 at 1 52 54 pm" src="https://user-images.githubusercontent.com/1202812/43477496-569443fc-94c9-11e8-9808-afb8de85a9c6.png">

**twentyseventeen:**

<img width="551" alt="screen shot 2018-07-31 at 2 28 49 pm" src="https://user-images.githubusercontent.com/1202812/43479590-c0294fa6-94ce-11e8-973d-792f298897f4.png">

**twentyten:**

<img width="738" alt="screen shot 2018-07-31 at 2 27 25 pm" src="https://user-images.githubusercontent.com/1202812/43479606-c5198fb2-94ce-11e8-9fb1-3449ea46ef94.png">

# Documentation

No devdocs in https://github.com/WordPress/gutenberg/tree/master/core-blocks/image

Suggestion for user-facing docs:

# Performance on mobile

# Accessibility

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Same float issues as image block. (#8293)

- [x] Centre-aligned block isn't centre-aligned in the editor. (#8296)

- [x] `<br>` is output to the frontend, breaking posts. (#8402)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] The `Show Download Button` toggle has some additional context: `The download button is shown.` that doesn't really add any additional context at all. Let's nix it. (#13429)

- [ ] `Link To` options are `Media File` and `Attachment Page`. I think these are understood by users who've a strong mental model of WordPress, but they aren't initially clear. It could be worth revisiting the wording (here and elsewhere) to better explain what these mean. (#8389)

- [ ] Wide and full widths feel like rather odd choices here. _(@kjellr: Agreed, but I suggest we leave as is for now, since themes may find a use for this.)_

- [ ] Empty state could be improved from a consistency standpoint. (#8409)

**Comment by uamv** [comment]
This appears to be a bug, though I've not tested with a clean install. When I add a custom class to the file block, the Download button loses styling on the back end. The front-end styling still appears properly.
![gutenberg-file-class-bug](https://user-images.githubusercontent.com/6343951/46106541-fa210500-c1a6-11e8-96e8-6adc0d32a282.gif)

**Comment by kjellr** [comment]
Closing this issue, as all bugs/enhancements have been raised as separate issues. 👍
