### ISSUE TITLE
Block audit: Audio

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8297]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="49" alt="screenshot 2018-07-30 15 16 49" src="https://user-images.githubusercontent.com/376315/43402873-9bfecfe8-940b-11e8-9369-1143fb740731.png">

**Name:** Audio
**Description:** Embed an audio file and a simple audio player.
**Category:** Common blocks
**CSS class:** `wp-block-audio` in frontend or editor
**Can be converted to:** file

# States

*Empty:*
<img width="670" alt="screenshot 2018-07-30 15 04 01" src="https://user-images.githubusercontent.com/376315/43402892-a4b6c1f4-940b-11e8-8725-2a18d45bddf6.png">

*Selected:*
<img width="670" alt="screenshot 2018-07-30 15 07 47" src="https://user-images.githubusercontent.com/376315/43402921-b2cb2f32-940b-11e8-9bf6-b3aaee714f5e.png">

With a caption:
<img width="680" alt="screenshot 2018-07-30 15 22 21" src="https://user-images.githubusercontent.com/376315/43403250-7f202ace-940c-11e8-9c15-3b65ee0d37dd.png">

With a caption and right-aligned:
<img width="670" alt="screenshot 2018-07-30 15 07 47" src="https://user-images.githubusercontent.com/376315/43402936-bd2c2e4a-940b-11e8-9c86-c3fc55f0576a.png">

*Unselected:*
<img width="592" alt="screenshot 2018-07-30 15 22 27" src="https://user-images.githubusercontent.com/376315/43403228-7222aa36-940c-11e8-9214-56ade1127df6.png">
<img width="143" alt="screenshot 2018-07-30 15 22 37" src="https://user-images.githubusercontent.com/376315/43403229-724b6660-940c-11e8-8810-6d2302b4dd48.png">

*Placeholder:*
<img width="617" alt="screenshot 2018-07-30 15 04 45" src="https://user-images.githubusercontent.com/376315/43402899-ab841ea0-940b-11e8-9fb5-f1231bd2b822.png">

# Primary (toolbar) settings

Align: left, centre, right, edit
For captions: bold, italic, strikethrough, link

# Secondary (sidebar) settings

Audio Settings: Autoplay, Loop, Preload
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

<img width="663" alt="screen shot 2018-07-31 at 1 57 53 pm" src="https://user-images.githubusercontent.com/1202812/43479851-76ebb292-94cf-11e8-96d3-898e1d8e73a5.png">

**Atomic Blocks**

<img width="766" alt="screen shot 2018-07-31 at 1 53 20 pm" src="https://user-images.githubusercontent.com/1202812/43477551-813a3df0-94c9-11e8-9caa-1adddc1578d6.png">

**twentyseventeen:**

<img width="566" alt="screen shot 2018-07-31 at 2 29 09 pm" src="https://user-images.githubusercontent.com/1202812/43479859-7d0ecac4-94cf-11e8-80d6-ba53c4f23f44.png">

**twentyten:**

<img width="328" alt="screen shot 2018-07-31 at 2 28 08 pm" src="https://user-images.githubusercontent.com/1202812/43479867-830718a0-94cf-11e8-8b12-e3d3a7a720b1.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Same float issues as image block. (#8293) Here, they're actually a bit worse, because the left- and right-aligned versions of the player are so small, it becomes impossible to select anything. (Especially if you have a caption!)

- [x] Converting to a file isn't undoable via the toolbar, and also causes issues with the edit icon moving from the right to the left. _(@kjellr, 2/28/19: Unable to reproduce in `master`, so crossing this out for now.)_

- [x] Converting a formatted caption to a file creates some weird JS [object Object]-y-ness. (#7626)

- [x] Setting an audio file to display full-width (which, honestly, feels a bit like an odd choice) causes it to overflow its container. (#8717)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] What does "Preload" mean? It gives the options for Auto|Metadata|None. (#7726)

- [ ] Good to see that Autoplay is untoggled by default. It could be nice to add a little note, a la colour contrast warnings, when people toggle this, to warn them to be careful autoplaying anything lest they annoy their users.

- [ ] I didn't expect left- and right-aligning the block to change the layout of the audio player so dramatically.

- [ ] Empty state could be improved from a consistency standpoint. (#8409)

**Comment by kadachepta** [comment]
How to prohibit download option? I don't want users to download my audio files. Please suggest..

**Comment by kjellr** [comment]
All of the bugs/errors noted here have been filed as individual issues. 

I'm not going to open individual issues for the two remaining suggestions at this point, but they're recorded here for reference. If we want to pursue in the future, we can open a new issue. 

Closing this in the meantime. 👍

**Comment by carolynrosner** [comment]
Like ajuluri above, I'd like to see a way to disable audio file downloading by hiding the control at far right. I tried to do it with CSS but there is no way to target that one behavior. I have not found a plugin that does the job either. Please consider reopening this issue. Thanks.
