### ISSUE TITLE
Block audit: Video

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8299]
Block audit

_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="52" alt="screenshot 2018-07-30 15 30 37" src="https://user-images.githubusercontent.com/376315/43405315-79f9fd2c-9411-11e8-8418-3b4a6e33e650.png">

**Name:** Video
**Description:** Embed a video file and a simple video player.
**Category:** Common blocks
**CSS class:** `wp-block-video` in frontend or editor
**Can be converted to:** file

# States

*Empty:*
<img width="684" alt="screenshot 2018-07-30 15 30 31" src="https://user-images.githubusercontent.com/376315/43405343-867e23b6-9411-11e8-8fd7-dee64c60ea5c.png">

*Selected:*
<img width="677" alt="screenshot 2018-07-30 15 39 26" src="https://user-images.githubusercontent.com/376315/43405449-b84b4be4-9411-11e8-8062-c25a3b889ccf.png">
<img width="670" alt="screenshot 2018-07-30 15 39 56" src="https://user-images.githubusercontent.com/376315/43405450-b874afb6-9411-11e8-8d1c-db625f5e4f26.png">

*Unselected:*
<img width="625" alt="screenshot 2018-07-30 15 40 05" src="https://user-images.githubusercontent.com/376315/43405426-ae41260a-9411-11e8-8901-b6c7eeaa04c8.png">

*Placeholder:*
<img width="619" alt="screenshot 2018-07-30 15 30 20" src="https://user-images.githubusercontent.com/376315/43405368-92d0189a-9411-11e8-9a05-8a1bfb74cd8a.png">

*Error:*
<img width="642" alt="screenshot 2018-07-30 15 36 28" src="https://user-images.githubusercontent.com/376315/43405392-9dd2268e-9411-11e8-8528-b2ae2690a2ca.png">

<img width="686" alt="screenshot 2018-07-30 16 03 14" src="https://user-images.githubusercontent.com/376315/43405607-1ff95768-9412-11e8-8897-26a8298bac9b.png">

# Primary (toolbar) settings

Align: left, centre, right, edit
For captions: bold, italic, strikethrough, link

# Secondary (sidebar) settings

Audio Settings: Autoplay, Loop, Preload
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

<img width="689" alt="screen shot 2018-07-31 at 1 57 49 pm" src="https://user-images.githubusercontent.com/1202812/43477699-db27bd74-94c9-11e8-81fe-fb22dfb9242f.png">

**Atomic Blocks**

<img width="777" alt="screen shot 2018-07-31 at 1 53 14 pm" src="https://user-images.githubusercontent.com/1202812/43477546-7adc87f6-94c9-11e8-95ba-cd4ea215133a.png">

**twentyseventeen:**

<img width="591" alt="screen shot 2018-07-31 at 2 29 05 pm" src="https://user-images.githubusercontent.com/1202812/43479799-4badd394-94cf-11e8-8e04-1e9b0264a810.png">

**twentyten:**

<img width="490" alt="screen shot 2018-07-31 at 2 27 59 pm" src="https://user-images.githubusercontent.com/1202812/43479803-4f577bd0-94cf-11e8-9afc-f962f3dcc194.png">

# Documentation

No devdocs in https://github.com/WordPress/gutenberg/tree/master/core-blocks/image

Suggestion for user-facing docs:

# Performance on mobile

# Accessibility

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Same float issues as image block. (#8293) 

- [x] Converting a formatted caption to a file creates some weird JS [object Object]-y-ness. (#7626)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] Error states could be improved across the board. (#8408)

- [x] The placeholder state should indicate that it's a video file—otherwise, it can just look like an image.

- [ ] Empty state could be improved from a consistency standpoint. (#8409)

**Comment by Soean** [comment]
1. The supported formats depends on the browser (see https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility), 
2. The error state is also made by the browser. We can check if the browser supports the video format and show a custom error. [Modernizr example](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/video.js) 
3. YouTube/Video should convert to an embed block, see #6824

**Comment by sarahmonster** [comment]
Lovely, thanks for the additional context @Soean! I was thinking that error message looked a lot like Firefox's... definitely felt out of place here. If we could add custom error message to be consistent across all browsers, I think that'd definitely be an improved user experience.

**Comment by paaljoachim** [comment]
Here is how Advanced Gutenberg plugin shows video settings:

![screen shot 2018-08-31 at 22 06 24](https://user-images.githubusercontent.com/5323259/44933829-c64eed00-ad6a-11e8-899c-c471532aa107.png)

**Comment by sarahmonster** [comment]
All issues here have been filed as individual issues, so I'm going to go ahead and close out this tracking bug. Feel free to comment on if I missed anything, or open new issues as needed! 💪
