### ISSUE TITLE
Block audit: Gallery

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8305]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="107" alt="screen shot 2018-07-30 at 2 36 26 pm" src="https://user-images.githubusercontent.com/1202812/43416330-f9993d9c-9405-11e8-98cc-9884961ce169.png">

**Name:** Gallery
**Description:** Display multiple images in an elegantly organized tiled layout.
**Category:** Common blocks
**CSS class:** `wp-block-gallery` in frontend and editor
**Can be converted to:** Image

# States

*Empty:*

<img width="643" alt="screen shot 2018-07-30 at 2 39 03 pm" src="https://user-images.githubusercontent.com/1202812/43416463-55ffcfec-9406-11e8-8291-c9d433994f55.png">

*Selected:*

With one image added:

<img width="640" alt="untitled" src="https://user-images.githubusercontent.com/1202812/43416506-81b64f8a-9406-11e8-9205-5a1f84634c09.png">

With two images added:

<img width="638" alt="screen shot 2018-07-30 at 2 41 14 pm" src="https://user-images.githubusercontent.com/1202812/43416556-a335a390-9406-11e8-8b19-425a117e2f75.png">

With one image selected:

<img width="640" alt="screen shot 2018-07-30 at 2 41 51 pm" src="https://user-images.githubusercontent.com/1202812/43416607-c5baebc8-9406-11e8-83fd-19a481153fb6.png">

With one image selected + caption:

<img width="640" alt="screen shot 2018-07-30 at 2 42 38 pm" src="https://user-images.githubusercontent.com/1202812/43416620-d42a7890-9406-11e8-8513-8f7e709b6106.png">

*Unselected:*

<img width="605" alt="screen shot 2018-07-30 at 2 43 03 pm" src="https://user-images.githubusercontent.com/1202812/43416646-e32e1018-9406-11e8-99ff-66998d1aef81.png">

*Placeholder:*

<img width="609" alt="screen shot 2018-07-30 at 2 38 31 pm" src="https://user-images.githubusercontent.com/1202812/43416672-f48fb528-9406-11e8-800c-ca2c5291c4bc.png">

# Primary (toolbar) settings

Align: left, centre, right, wide, full
Edit

# Secondary (sidebar) settings

Gallery Settings: Columns, Crop Images, Link to
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

![screen shot 2018-07-31 at 1 00 40 pm](https://user-images.githubusercontent.com/1202812/43474760-c5f7f8a4-94c1-11e8-90da-f361b334e6b1.png)

**Atomic Blocks**

![atomic blocks](https://user-images.githubusercontent.com/1202812/43474763-c8571d64-94c1-11e8-96b5-f56290eb4aa9.png)

**twentyseventeen:**

![screen shot 2018-07-31 at 1 01 33 pm](https://user-images.githubusercontent.com/1202812/43474812-e14317ec-94c1-11e8-981a-26428f431936.png)

**twentyten:**

![2010](https://user-images.githubusercontent.com/1202812/43474817-e48121c4-94c1-11e8-8cd0-197363437296.png)

# Documentation

No devdocs in https://github.com/WordPress/gutenberg/tree/master/core-blocks/gallery

Suggestion for user-facing docs:

# Performance on mobile

# Accessibility

# Bugs/errors

_Individual issues will be opened for these soon_

- [x] Links in gallery captions are low-contrast (#7952)
- [ ] Gallery captions placeholder text is low-contrast (#5838)
- [ ] In multi-line captions, the bottom-most line appears closer to the bottom of the box than to the line of text above it. This creates uncomfortable visual tension on that last line, and pulls it away visually from the text above it. (#8018)
- [ ] Long captions are unwieldy to edit. They sometimes result in cut off controls. (#6858)
- [ ] Using the "Edit Gallery" option erases any previously entered image captions without warning. (#8310)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] We should add a clear visual affordance for scrollable image captions (#7963)
- [ ] We should consider offering a caption style that doesn't layer text on top of the images. (#8030)
- [ ] Once an image has been added to the gallery, we don't provide a straightforward way to add more images from the media library. We should consider adding "Upload / Media Library" buttons to the "Add an Image" placeholder area. (#8309)
- [ ] Consider allowing users to reorder the gallery from within Gutenberg, instead of having to jump into the media modal. (#743)
- [ ] Consider an enhancement that allows individual images to link to custom URLs. 
- [ ] A philosophical question: Should this block be recreated so that it uses columns and nested blocks?
- [ ] Empty state could be improved from a consistency standpoint. (#8409)

**Comment by markfinst** [comment]
\+ to suggestions:

Store gallery image attachment IDs in JSON `<!-- wp:gallery -->` block to allow overriding gallery by theme developers (from backend side) without having to parse HTML. https://github.com/WordPress/gutenberg/issues/8193

**Comment by sarahmonster** [comment]
It looks as though all issues surfaced here have been discussed in issues elsewhere. I'm going to close this tracking issue out, but please do go ahead and file new issues if there's anything that hasn't been brought up for discussion yet! 📈
