### ISSUE TITLE
Block audit: Pullquote

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8329]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="52" alt="screenshot 2018-07-31 19 24 40" src="https://user-images.githubusercontent.com/376315/43479100-7f2e2f16-94f7-11e8-9915-9572f920f22b.png">

**Name:** Pullquote
**Description:** Highlight a quote from your post or page by displaying it as a graphic element.
**Category:** Formatting blocks
**CSS class:** `wp-block-pullquote` in frontend or editor
**Can be converted to:** nothing

# States

*Empty:*
<img width="675" alt="screenshot 2018-07-31 19 16 08" src="https://user-images.githubusercontent.com/376315/43479148-96226cfa-94f7-11e8-80b3-f30bcdd0b8a7.png">

*Selected:*
<img width="679" alt="screenshot 2018-07-31 19 21 16" src="https://user-images.githubusercontent.com/376315/43479166-a3b126f4-94f7-11e8-92e4-783451aef54a.png">

*Unselected:*
<img width="606" alt="screenshot 2018-07-31 19 22 05" src="https://user-images.githubusercontent.com/376315/43479167-a3d1a2da-94f7-11e8-9895-b45b9f19b1da.png">

*Placeholder:*
<img width="607" alt="screenshot 2018-07-31 19 16 02" src="https://user-images.githubusercontent.com/376315/43479128-8c340da2-94f7-11e8-8e4d-8e96eef4b5f4.png">

# Primary (toolbar) settings

Align: left, centre, right, bold, italic, strikethrough, link

# Secondary (sidebar) settings

Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**
<img width="727" alt="screenshot 2018-08-01 12 39 24" src="https://user-images.githubusercontent.com/376315/43524250-b48cb1c4-9596-11e8-990c-31d75672ddbe.png">
<img width="722" alt="screenshot 2018-08-01 12 39 29" src="https://user-images.githubusercontent.com/376315/43524251-b4d7b76e-9596-11e8-99bd-043b88b187b6.png">

**Atomic Blocks**
<img width="744" alt="screenshot 2018-08-01 12 43 11" src="https://user-images.githubusercontent.com/376315/43524297-d683c2a4-9596-11e8-9bdc-9155ae761d0f.png">

**twentyseventeen:**
<img width="595" alt="screenshot 2018-08-01 12 38 17" src="https://user-images.githubusercontent.com/376315/43524164-73c9acd2-9596-11e8-9a35-f8e9d485ebf0.png">

**twentyten:**
<img width="692" alt="screenshot 2018-08-01 12 34 52" src="https://user-images.githubusercontent.com/376315/43524052-1cf2ec98-9596-11e8-8e82-4280d2a87da3.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Floating/alignment is buggy. (#8293)

- [ ] Citation lacks sufficient contrast. (#﻿﻿8738)

*Note that toggling italics works as expected here, where it doesn't with the quote block (and a few other blocks that use captions by default.)

# Suggestions

_Individual issues will be opened for these soon_

- [x] My first instinct here is "why do we have two types of quotes, and how does a user decide which to use?" I know that a pull quote is designed to be a graphic element to highlight text from the articles, but I suspect most users don't. We should be careful how we present this block to avoid confusion. (See also #8236)

- [ ] Further to that, the citation should probably be removed entirely. Since the intention of a pullquote is to quote *from the article* itself, a citation doesn't make sense in this context. (#11610)

- [x] Use an `<aside>` rather than a `<blockquote>` makes more semantic sense here. Worth also considering the accessibility constraints here—ideally screen readers wouldn't read the content of a pull quote, since it's basically doubled-up content. (#5457)

- [x] An alternative solution would be to add the pull quote styles to the main quote block, which is probably the easiest and best solution here. (#5947)

- [x] Italic all-caps feels like a pretty awkward style choice for the citation styling, and it's inconsistent with the rest of Gutenberg. Generally the styling feels out-of-place and discordant.

- [x] If we decide to keep it, it should definitely be convertible to a regular quote.

- [x] Probably shouldn't use the same icon as the quote block.

- [x] Could be confusing that this uses image-style alignment icons and functionality, whereas the quote element uses the text-style alignment icons and functionality.

**Comment by SuperGeniusZeb** [comment]
>Further to that, the citation should probably be removed entirely. Since the intention of a pullquote is to quote from the article itself, a citation doesn't make sense in this context.

I agree.

>Use an <aside> rather than a <blockquote> makes more semantic sense here.

I think _both_ should be used here: a `<blockquote>` nested in an `<aside>`.

>My first instinct here is "why do we have two types of quotes, and how does a user decide which to use?" I know that a pull quote is designed to be a graphic element to highlight text from the articles, but I suspect most users don't. We should be careful how we present this block to avoid confusion. (See also #8236)

>An alternative solution would be to add the pull quote styles to the main quote block, which is probably the easiest and best solution here. (#5947)

Block styles currently can only add a class to a block. They cannot change the rest of the markup, so I do not think that having a pullquote be a style of the Quote block makes sense, unless the block styles API is changed to support markup changes, which I think may be a bad idea.

>Could be confusing that this uses image-style alignment icons and functionality, whereas the quote element uses the text-style alignment icons and functionality.

Something I wonder about is what blocks should have float alignment options and why? I am not aware of any standard reasoning for whether or not a block should have the float alignment options, or even alignment options in general.

**Comment by SuperGeniusZeb** [comment]
Thinking about it some more, I think the Pullquote block may not be necessary at all. If the [proposed Container block](#4900) was implemented with the ability to change the HTML element used from `<div>` to `<aside>`, you could make a semantically correct equivalent to the Pullquote block using a Quote block nested in a Container block saved as a Reusable block that would be used as a template. See also: #8403.

The only thing that would be missing is the style of the current Pullquote block, but that could just be added as another style variation of the Quote block.

This brings up another question: should core include some Reusable blocks on new installations to be used as templates, in cases where there is a common piece of content that can be constructed out of existing blocks?

**Comment by sarahmonster** [comment]
Thanks for the discussion and ideas here! I've filed some additional suggestions re: the quote/pullquote confusion over in #11610 for further discussion.

All other issues identified here have been filed as individual issues, so I'm going to go ahead and close out this tracking bug. Feel free to comment if I missed anything, or open new issues as needed! 💪
