### ISSUE TITLE
wp.data Overview

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#8354]
This issue seeks to organize pending work and improvements around the `wp.data` module.

## Tasks

- [x] Adding support for sync generators to allow async action creators. #7546, #8096
- [x] Add support for Core Data Entities Actions. #7175 
- [x] Adding and updating entities. #10089
- [x] Add support for action creators as generators. #6999, #8096
- [x] Write documentation / examples.

## Blocks

- [x] Update all blocks to not have direct API calls.

**Comment by gziolo** [comment]
There are no breaking changes planned, removing from `API freeze`.

**Comment by gziolo** [comment]
I opened #8911 which explicitly imports `@wordpress/core-data` for packages which call `select( 'core' ).*`.

I also noticed the following when looking at the implementation of `core-data`:
- `isPreviewEmbedFallback`, `getEmbedPreview` are used only with embeds block
- `getThemeSupports` is used with `editor` package
- `getAuthors` - referenced only in `editor`
- `getUserQueryResults` - should be internal as it is used only in `getAuthors`...
- everything else is entity based
- it's not possible to customize entities, we use `defaultEntities` and `kinds` as provided by core

The general question is, what should be the strategy for including stores in a given package. In other words, how do we want to ensure that each package works out of the box with all the selectors and action it has listed in the codebase.

**Comment by youknowriad** [comment]
The original purpose oof `core-data` is a data abstraction for WordPress which includes all the data available via REST API (exclusing plugins data):

 - Posts
 - Users
 - Taxonomies
 - Media
 - Embed Proxy Endpoint
 - Settings (theme supports)

So I think these make sense there.

> Extending entities:

 - I'm not certain yet we should make the entities extensible or instead provide helpers to build entities in other `data` packages. (for example `woo/data`)


> The general question is, what should be the strategy for including stores in a given package. In other words, how do we want to ensure that each package works out of the box with all the selectors and action it has listed in the codebase.

I think explicitness (adding `import '@wordpress/core-data'` etc...) should be favored but there's an open question about how to detect/automate those. (Maybe an eslint rule is possible)

**Comment by coderkevin** [comment]
I've done some experimental work to add some more advanced functionality via the [fresh-data](https://github.com/Automattic/fresh-data) project.

This is with a plugin internal to `@wordpress/data`
https://github.com/WordPress/gutenberg/pull/8754

This is with the plugin external from `@wordpress/data`
https://github.com/woocommerce/wc-admin/pull/301

In all, the plugin architecture allowed me to get done what I needed to do this, even with the few key differences in architecture, such as component data mapping, requirements fulfillment, and multi-resource operations.

**Comment by coderkevin** [comment]
I'm also working on some experimental code for a single plugin to hold a larger tree of state within the [Calypso](https://github.com/Automattic/wp-calypso) project. The goal here is to allow a `@wordpress/data` workflow while maintaining compatibility with the existing system. I'll update this comment when I have the PR up for review.

**Comment by jsnajdr** [comment]
Adding a note that there's also the queries/mutation proposal discussed in p4TIVU-96L-p2.

**Comment by youknowriad** [comment]
Most of the basic pieces landed or are going to land in #10089 I'm closing this meta issue for now. It served its purpuse. 

There are still things I want to improve on the data module but it could happen later without breaking changes.
