### ISSUE TITLE
Block audit: Classic

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8368]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="115" alt="screen shot 2018-08-01 at 1 41 10 pm" src="https://user-images.githubusercontent.com/1202812/43538641-95ba34ca-9590-11e8-9eee-72e19b7b786f.png">

**Name:** Classic
**Description:** It’s the classic WordPress editor and it’s a block! Drop the editor right in.
**Category:** Formatting
**CSS class:** `.editor-block-list__block` class in editor, nothing in frontend.
**Can be converted to:** Content within the Classic block can be "Converted to Blocks".

# States

*Empty:*

<img width="654" alt="screen shot 2018-08-01 at 12 43 55 pm" src="https://user-images.githubusercontent.com/1202812/43535797-e6cabee6-9588-11e8-95d5-f01c1973f9d7.png">

*Selected:*

<img width="659" alt="screen shot 2018-08-01 at 12 46 55 pm" src="https://user-images.githubusercontent.com/1202812/43535842-fec653ca-9588-11e8-9ab2-210443aee668.png">

*Unselected:*

<img width="659" alt="screen shot 2018-08-01 at 12 46 55 pm" src="https://user-images.githubusercontent.com/1202812/43535842-fec653ca-9588-11e8-9ab2-210443aee668.png">

*Placeholder:*

<img width="654" alt="screen shot 2018-08-01 at 12 43 55 pm" src="https://user-images.githubusercontent.com/1202812/43535810-ee9160e4-9588-11e8-80a5-bcf53db23496.png">

(that's not a mistake — they're all the same)

# Primary (toolbar) settings

None

# Secondary (sidebar) settings

None

# Frontend appearance

(I'm omitting front end screenshots: Since this block outputs its content directly into `entry-content` — with no wrapper element — it defaults to the theme's standard styles entirely.)

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] The "Read More" tag is missing a text label. (#8372)
- [ ] The header text sizes do not match the text scale used in the rest of Gutenberg.  (#8373)
- [ ] "Paste as Text" notification shows up in a weird place, and with non-standard styles. (#8374)
- [ ] When using a RTL language, the text style listbox is clipped off on the right (#8672)

# Suggestions

_Individual issues will be opened for these soon_

- Is the "Classic" name clear enough? I might suggest calling it the "Classic Editor" or something similar.
- It's a little weird that the black has only one state. Should it have a hover/selected state like the other blocks do? It looks like [this was considered at one point](https://github.com/WordPress/gutenberg/pull/4948#issuecomment-381052960), but must've been removed later on. 
- [x] I fully expected to be able to drag/drop images into the Classic block. I wasn't able to. (https://github.com/WordPress/gutenberg/issues/7762). This is especially confusing because Classic blocks that are auto-created from the Classic editor can have images in them. But it's impossible to add an image to a Classic block that a user has inserted via Gutenberg.  
- [ ] It's confusing that this block includes block-level undo/redo options, and that they don't behave the same way as the global undo/redo buttons do.  (#8729)

**Comment by kjellr** [comment]
All the issues raised here have been opened as individual issues now (except for the naming + single state observations, which I consider more ponderings than actual issues). Going to close this for now, and we can continue discussion in the individual issues instead. 👍
