### ISSUE TITLE
Block audit: Table

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8398]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

![screen shot 2018-08-02 at 1 15 22 pm](https://user-images.githubusercontent.com/1202812/43599597-2349e2c0-9656-11e8-8adc-183732f911f6.png)

**Name:** Table
**Description:** Insert a table -- perfect for sharing charts and data.
**Category:** Formatting
**CSS class:** `wp-block-table` in frontend and editor
**Can be converted to:** Nothing

# States

*Empty:*

![screen shot 2018-08-02 at 2 02 44 pm](https://user-images.githubusercontent.com/1202812/43602263-7bb50bd6-965d-11e8-9ff2-17156ff50e99.png)

*Selected:*

![screen shot 2018-08-02 at 2 08 53 pm](https://user-images.githubusercontent.com/1202812/43602318-9f120f66-965d-11e8-99cf-534fa1b2aa56.png)

*Unselected:*

![screen shot 2018-08-02 at 2 08 25 pm](https://user-images.githubusercontent.com/1202812/43602279-8a78ea66-965d-11e8-9f04-e4dd1b2a753c.png)

*Placeholder:*

![screen shot 2018-08-02 at 2 02 44 pm](https://user-images.githubusercontent.com/1202812/43602330-a45cd758-965d-11e8-8739-1bd9180b637e.png)

(Same as empty)

# Primary (toolbar) settings

- Align left
- Align center
- Align right
- Edit table
    - Add row before
    - Add row after
    - Delete row
    - Add column before
    - Add column after
    - Delete column
- Bold
- Italic
- Strikethrough
- Link

# Secondary (sidebar) settings

Table Settings: Fixed width table cells
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

![screen shot 2018-08-02 at 3 24 52 pm](https://user-images.githubusercontent.com/1202812/43606080-59c070b4-9668-11e8-9cd4-762497b4a90b.png)

**Atomic Blocks**

![screen shot 2018-08-02 at 3 25 30 pm](https://user-images.githubusercontent.com/1202812/43606081-5cb0bf54-9668-11e8-8ce6-2ed992befff0.png)

**twentyseventeen:**

![screen shot 2018-08-02 at 3 25 10 pm](https://user-images.githubusercontent.com/1202812/43606089-6185015c-9668-11e8-9957-d55d8a395294.png)

**twentyten:**

![screen shot 2018-08-02 at 3 24 11 pm](https://user-images.githubusercontent.com/1202812/43606094-64898ba2-9668-11e8-83e1-fdcec50674aa.png)

# Documentation

No devdocs in https://github.com/WordPress/gutenberg/tree/master/core-blocks/table

Suggestion for user-facing docs:

# Performance on mobile

# Accessibility

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] When you add just a couple more columns, the block forces scrollbars. It's not clear this is necessary. (See #8325)
- [ ] Horizontal scrolling is not evident on browsers/devices that hide scrollbars.  (#8401)
- [ ] Row/Column selection color is not in our palette. (#8404)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] I expected to be able to adjust text color/backgrounds. In this case, I assume that those settings would apply to the current cell. (#8171)
- [ ] It'd be great to add some "advanced" table features into the sidebar. There's a great discussion around this in #6923 
- [ ] <strike>Customizing tables would be much faster if the "Edit table" options were exposed in the block toolbar. That said, that might lead to icon overload, and the icons may not be particularly clear on their own.</strike> _Trusting my gut on this one — this would be too many icons in the toolbar._ 
- [ ] <strike>Alignment feels a bit unexpected—it's using the block-level alignment icons and styling, but that doesn't seem to behave consistently. For instance, if I right-align the table, the text remains left-aligned, but if I centre-align the table, the text becomes centre-aligned.</strike> _(Issue no longer occurs after the table block rewrite.)_ 
- [x] Being able to set column and row headings would help improve accessibility of content to screenreader users. (#1470)

**Comment by iseulde** [comment]
Just noting here that the table block has been rewritten recently, so the description may no longer be up to date.

**Comment by kjellr** [comment]
All the issues raised here have been opened as individual issues. Going to close this for now, and we can continue discussion in the individual issues instead. 👍

Thanks!
