### ISSUE TITLE
Block audit: Custom HTML

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8435]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="49" alt="screenshot 2018-08-03 01 14 42" src="https://user-images.githubusercontent.com/376315/43641346-38ba1254-971b-11e8-925e-21e40c781c48.png">

**Name:** Custom HTML
**Description:** Add your own HTML (and view it right here as you edit!).
**Category:** Formatting
**CSS class:** none that I could tell?
**Can be converted to:** nothing

# States

*Empty:*
<img width="678" alt="screenshot 2018-08-03 01 22 24" src="https://user-images.githubusercontent.com/376315/43641359-46b20920-971b-11e8-8971-e559a83a00c3.png">

*Selected:*

*Unselected:*

*Placeholder:*
<img width="615" alt="screenshot 2018-08-03 01 19 13" src="https://user-images.githubusercontent.com/376315/43641382-5fabd3c0-971b-11e8-9477-e5a4cfb6d31b.png">

# Primary (toolbar) settings

HTML and Preview tabs (no settings)

# Secondary (sidebar) settings

none

# Frontend appearance

_I'm omitting front end screenshots: Since this block outputs its content directly into `entry-content` — with no wrapper element — it defaults to the theme's standard styles entirely._

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] This block doesn't use any container div at all when output to frontend, meaning formatting can get weird. (See Gutenberg starter theme.) _This seems expected. Also, since it's just HTML a user can manually add a wrapper div if they so choose_.

- [ ] Refreshing the page yields a "this block has been modified externally" message which is a little confusing. (https://github.com/WordPress/gutenberg/issues/13158)

- [ ] When using a RTL language, the block has a few visual bugs. (#8680)

- [ ] Line numbers lack sufficient contrast. (#8736)

- [ ] I couldn't figure out how to switch between HTML and Preview modes whilst using keyboard navigation. There may be a shortcut I've missed? (Possibly tangentially related: #5274.)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] I get an error before I've finished typing a block of code, which was a bit confusing. _Tested on 2/18/2019, did not see any error reporting._

- [ ] Preview mode should potentially use Gutenberg typeface, rather than falling back to Times. (#9129)

- [ ] The styling here is suffering from the same double-box syndrome as the code block, although it's definitely less pronounced. Considering the design of this alongside the code block may be sensible, since they feel *quite* different. (#13934)

- [ ] How do errors display on mobile devices? Right now, they only appear on hover.  _Tested on 2/18/2019, did not see any error reporting._

- [ ] Should this be convertible to and from a code block? (#13935)

**Comment by talldan** [comment]
I've created https://github.com/WordPress/gutenberg/issues/13158 which seems related to the issue mentioned here:
> Refreshing the page yields a "this block has been modified externally" message which is a little confusing.

**Comment by kjellr** [comment]
I just went through and filed issues (or just made inline notes) for the remaining items in this ticket. I'm going to close this ticket in favor of the smaller issues. 👍
