### ISSUE TITLE
Block audit: Columns

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#9156]
Block audit

_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="56" alt="screenshot 2018-08-15 10 56 26" src="https://user-images.githubusercontent.com/376315/44335603-ec23ea00-a46c-11e8-8352-ebfa826044cd.png">

**Name:** Columns (beta)
**Description:** Add a block that displays content in multiple columns, then add whatever content blocks you’d like.
**Category:** Layout elements
**CSS class:** `wp-block-columns` in editor and frontend
**Can be converted to:** nothing

**Individual column block**
Description: A single column within a columns block.
Advanced: Additional CSS class.

# States

*Empty:*
<img width="418" alt="screenshot 2018-08-20 11 35 24" src="https://user-images.githubusercontent.com/376315/44335714-2f7e5880-a46d-11e8-983c-50920063c042.png">

*Selected:*
<img width="596" alt="screenshot 2018-08-15 10 53 00" src="https://user-images.githubusercontent.com/376315/44335831-84ba6a00-a46d-11e8-8f9f-fa148f9ad8a2.png">

<img width="677" alt="screenshot 2018-08-15 10 56 20" src="https://user-images.githubusercontent.com/376315/44335860-9bf95780-a46d-11e8-9d5b-782184b9bbfd.png">

*Unselected:*
<img width="570" alt="screenshot 2018-08-15 10 55 23" src="https://user-images.githubusercontent.com/376315/44335847-900d9580-a46d-11e8-9996-ec03905c12c1.png">

*Placeholder:*
<img width="381" alt="screenshot 2018-08-20 11 35 34" src="https://user-images.githubusercontent.com/376315/44335722-34dba300-a46d-11e8-90a7-0cbd5af6c1fb.png">

# Primary (toolbar) settings

None

# Secondary (sidebar) settings

Columns (number)
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**
<img width="606" alt="screenshot 2018-08-20 11 56 28" src="https://user-images.githubusercontent.com/376315/44337032-3313de80-a471-11e8-8b17-4cb12f7618bc.png">

**Atomic Blocks**
<img width="725" alt="screenshot 2018-08-20 11 55 28" src="https://user-images.githubusercontent.com/376315/44337046-3ad38300-a471-11e8-8985-96461341725b.png">

**twentyseventeen:**

<img width="533" alt="screenshot 2018-08-20 11 49 36" src="https://user-images.githubusercontent.com/376315/44337067-4757db80-a471-11e8-90a7-91b05fafd0c6.png">

**twentyten:**
<img width="629" alt="screenshot 2018-08-20 11 57 36" src="https://user-images.githubusercontent.com/376315/44337017-28f1e000-a471-11e8-97da-0626550b6322.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Selecting elements (especially the RIGHT element) is very confusing. (#15975)

- [ ] The sub-block toolbars spill out of frame, making some tools inaccessible.

- [ ] Responsiveness is sub-optimal. (#6048)

- [ ] Duplicating an individual column block leads to unexpected behaviour.

- [ ] Column block followed by another column block creates overlap.

- [ ] Base styles should probably include a gutter between columns. (#15975)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] Being able to select the individual columns maybe isn't strictly necessary. The only thing you can do with them is add a CSS class. Why not just add a CSS class to begin with?

- [ ] I wonder if this might make more sense as an option within a container/section block, rather than its own block. 

- [ ] Full-width alignment here could be very nice. 

- [ ] Empty and placeholder states could use some consideration—they feel a bit confusing as it currently stands.

- [ ] Overall, this block just feels confusing across the board, and I'm not sure that putting a "beta" flag in the title helps a great deal, particularly when the entire software is still in some form of beta or another.

**Comment by buzucan** [comment]
Another bug found. If I add some info in columns and after that I will save the info to a reusable block when I try to use the info from the block ...all is deleted.

**Comment by HippDesign** [comment]
It should be possible to change the **columns block** to the setting **"1 column"** - there are many use cases where you need one column like a wrapper with a class, when you want to have an area of different color or background in the fontend. 

At the moment it is not possible to drag the selector to the value of 1, but it is possible to delete the value and type "1" in the settings sidebar.

**Comment by grappler** [comment]
I struggled with two things related to columns. 

I created a 2 columns and added content, then I decided that I did not want to use columns but I could not find an easy way to move the block inside the columns to out of it.

As I hack I changed the number of columns to 1 using @dionysous tip and I lost all of the content in column 2 which was a bit unexpected.

**Comment by apeatling** [comment]
There is a bug where if you select a single column and set an additional CSS class, it is not added to the markup. It does however appear in the markup on front end of the site.

**Comment by erikjoling** [comment]
I'd like to add investigating the markup of the columns-block in the editor to the audit #7770

**Comment by karmatosed** [comment]
I think with all the work going on in other issues this can maybe be closed now. With that in mind, I will do that but we can always reopen.
