### ISSUE TITLE
Block audit: Categories

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9408]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

![screen shot 2018-08-28 at 2 43 58 pm](https://user-images.githubusercontent.com/1202812/44743549-d0ee5580-aad0-11e8-8573-24622c1038e5.png)

**Name:** Categories
**Description:** Display a list of all your site’s categories.
***Category:** Widgets
**CSS class:** `wp-block-categories`, `wp-block-categories-list`
**Can be converted to:** Nothing

# States

*Empty/Selected/Placeholder*

![screen shot 2018-08-28 at 2 45 14 pm](https://user-images.githubusercontent.com/1202812/44743632-05faa800-aad1-11e8-85cf-7a2750c71cff.png)

*Unselected:*

![screen shot 2018-08-28 at 2 45 25 pm](https://user-images.githubusercontent.com/1202812/44743635-098e2f00-aad1-11e8-8fec-61d170a434d9.png)

# Primary (toolbar) settings

Align Left, Align Center, Align Right, Align Full

# Secondary (sidebar) settings

Categories Settings: Display as dropdown, Show Post Counts, Show Hierarchy

# Frontend appearance

**Gutenberg Starter Theme**

![screen shot 2018-08-28 at 2 47 54 pm](https://user-images.githubusercontent.com/1202812/44743766-62f65e00-aad1-11e8-971f-887ce721f084.png)

**Atomic Blocks**

![screen shot 2018-08-28 at 2 48 03 pm](https://user-images.githubusercontent.com/1202812/44743768-6558b800-aad1-11e8-9462-e88869450c1b.png)

**twentyseventeen**

![screen shot 2018-08-28 at 2 48 29 pm](https://user-images.githubusercontent.com/1202812/44743792-71dd1080-aad1-11e8-91bd-be4edf3436af.png)

**twentyten**

![screen shot 2018-08-28 at 2 48 51 pm](https://user-images.githubusercontent.com/1202812/44743808-7dc8d280-aad1-11e8-9598-d78ac0baf3c4.png)

# Bugs/errors

_Individual issues will be opened for these soon_

- [x] Front-end renders an `aligncenter` class, regardless of alignment settings (#7910)

# Suggestions

_Individual issues will be opened for these soon_

- [x] This block is rendered inside of a container `div`, while the similar Archives and Latest Post blocks are rendered directly as `ul`s. Reasoning behind this is unclear. (#9411)
- [ ] We should sync up alignment options with the Archives block. (#9413)
- I'd love to see some additional visual styles for this list.

**Comment by melchoyce** [comment]
> I'd love to see some additional visual styles for this list.

+1 — see https://github.com/WordPress/gutenberg/issues/1464#issuecomment-385119194 for some potential ideas we could consider for categories as well.

**Comment by sarahmonster** [comment]
It looks as though all issues here have been filed or discussed elsewhere, so I'm going to go ahead and close this tracking issue out. Feel free to reopen (or file new issues!) if anything requires further debate. 💪
