### ISSUE TITLE
Block Audit: Latest Posts

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9698]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="34" alt="screen shot 2018-09-07 at 1 22 31 pm" src="https://user-images.githubusercontent.com/1202812/45233549-16fda300-b2a1-11e8-900d-0af98e5dbd12.png">

**Name:** Latest Posts
**Description:** Display a list of your most recent posts.
***Category:** Widgets
**CSS class:** `wp-block-latest-posts`
**Can be converted to:** Nothing

# States

*Empty/Selected/Placeholder*

<img width="709" alt="screen shot 2018-09-07 at 1 27 09 pm" src="https://user-images.githubusercontent.com/1202812/45233766-c5a1e380-b2a1-11e8-88bb-b01b817ada3a.png">

*Unselected:*

<img width="729" alt="screen shot 2018-09-07 at 1 27 17 pm" src="https://user-images.githubusercontent.com/1202812/45233768-c9356a80-b2a1-11e8-9bb5-924dac76e348.png">

# Primary (toolbar) settings

Align Center, Align Wide, Align Full, List View, Grid View

# Secondary (sidebar) settings

Latest Post Settings: Order By, Category, Number of items, Display post date
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg Starter Theme**

<img width="613" alt="screen shot 2018-09-07 at 1 29 54 pm" src="https://user-images.githubusercontent.com/1202812/45233881-229d9980-b2a2-11e8-9689-38d92009fb11.png">

**Atomic Blocks**

<img width="632" alt="screen shot 2018-09-07 at 1 33 36 pm" src="https://user-images.githubusercontent.com/1202812/45234077-a5265900-b2a2-11e8-8b00-b4f80793f77d.png">

**twentyseventeen**

<img width="592" alt="screen shot 2018-09-07 at 1 30 46 pm" src="https://user-images.githubusercontent.com/1202812/45233919-406afe80-b2a2-11e8-97c9-c9e962645475.png">

**twentyten**

<img width="704" alt="screen shot 2018-09-07 at 1 31 31 pm" src="https://user-images.githubusercontent.com/1202812/45233958-5973af80-b2a2-11e8-972e-28f96396df60.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Block does not include left/right alignment options (#8777)
- [ ] Untitled posts are referred to as `(Untitled)`, whereas other areas of WP-Admin refer to them as `(no title)` (#9695)
- [ ] "Grid View" styles clip off bullets on small screens (#9697)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] Block should support custom post types (#9013)
- [ ] This block could use alternate layout options (#1594)

**Comment by Axinet** [comment]
As I understand from the current state, the features from 4.9 core widget "Recent posts" like "Show featured image" and "Show excerpt" are not expected to be found in Wordpress 5.0 Gutenberg block?

**Comment by kjellr** [comment]
@Axinet Apologies for the delayed response. 

> As I understand from the current state, the features from 4.9 core widget "Recent posts" like "Show featured image" and "Show excerpt" are not expected to be found in Wordpress 5.0 Gutenberg block?

That is my understanding, yes. Both of those options are noted as enhancements in https://github.com/WordPress/gutenberg/issues/1594, which is slated for Phase 2.

**Comment by pagelab** [comment]
The class `has-dates` is missing from the block front-end code when "Show post date" is active on the block config.

**Comment by pagelab** [comment]
The `has-dates` issue is [being worked on](https://github.com/WordPress/gutenberg/issues/10701#issuecomment-430890754).

**Comment by sarahmonster** [comment]
All issues here have been filed as individual issues, so I'm going to go ahead and close out this tracking bug. Feel free to comment if we missed anything, or open new issues as needed! 💪
